### PR TITLE
Untie LQP on destruction of the "output" node

### LINKED ISSUE #1109: JoinOrderingRule breaks output of some LQP nodes
After the JoinOrderingRule has executed on query 9, `outputs()` of one of the nodes is broken, as adding

```
  visit_lqp(input, [](const auto& node) {
    Assert(node->outputs().size() >= 0, "??");
    return LQPVisitation::VisitInputs;
  });
```

to the end of `Optimizer::optimize` demonstrates:

```
(debug)!> visualize noexec SELECT nation, o_year, SUM(amount) as sum_profit FROM (SELECT n_name as nation, SUBSTR(o_orderdate, 0, 4) as o_year, l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount FROM "part", supplier, lineitem, partsupp, orders, nation WHERE s_suppkey = l_suppkey AND ps_suppkey = l_suppkey AND ps_partkey = l_partkey AND p_partkey = l_partkey AND o_orderkey = l_orderkey AND s_nationkey = n_nationkey AND p_name like '%green%') as profit GROUP BY nation, o_year ORDER BY nation, o_year DESC;
src/lib/logical_query_plan/abstract_lqp_node.cpp:133 Failed to lock output
```

### PR DESCRIPTION
**Pull request by mrzzzrm**
I'm proposing this again, in order to fix #1109 
Our current approach of "untie LQP(Nodes) you created manually" is error prone and along the lines of the mentality of "free() memory you malloc()ated, manually", frankly.

Up until the `JoinOrderingRule` arrived, this was doable with acceptable effort, now it is not, anymore.
The `JoinOrderingRule` creates a plethora of candidate plans, most of which would need manual cleaning. It also completely abandons parts of the LQP that it optimizes with join ordering and creates new nodes for. 
All in all there are three places where manual untying would be necessary in this rule alone, and in all of these cases there are plans that need to be untied and plans that need to stick and identifying into which category a node belongs is error-prone and hard to read.

I would have liked to abandon the concept of output ptrs in the LQP entirely. Unfortunately, I found that we need them, actually.

### CODE REVIEW

File: src/lib/optimizer/optimizer.cpp [hunk 1]
```diff
@@ -140,6 +140,11 @@ std::shared_ptr<AbstractLQPNode> Optimizer::optimize(const std::shared_ptr<Abstr
   const auto optimized_node = root_node->left_input();
   optimized_node->clear_outputs();
 
+  visit_lqp(optimized_node, [](const auto& node) {
```
Comment (mrks) [inline src/lib/optimizer/optimizer.cpp]: left over?

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 2]
```diff
@@ -272,9 +283,21 @@ std::shared_ptr<AbstractLQPNode> AbstractLQPNode::_shallow_copy(LQPNodeMapping&
...
+     * If nothing else breaks the only way we might get `other.expired()` to be true is if `other` is the expired
+     * weak_ptr<> to output - and thus the element we're looking for - in the following scenario:
+     *
+     * auto node_a = Node::make()
+     * auto node_b = Node::make(..., node_a)
+     *
+     * node_b.reset(); // ~AbstractLQPNode() will call `node_a_remove_output_pointer(node_b)`
+     *                 // But we can't lock node_b anymore, since its ref count is already 0
+     */
+    return &output == other.lock().get() || other.expired();
```
Comment (mrks) [inline src/lib/logical_query_plan/abstract_lqp_node.cpp]: Does this make sense? If it is expired, `other.lock()` will return an empty `shared_ptr`, so isn't the expired check superfluous?

Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: Is what you are suggesting that this can be simplified to 

```c++

    const auto locked_other = other.lock();
    return &output == other.lock().get() || !locked_other;
```
???

I adjusted it accordingly

Comment (mrks) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: Why not `return &output == other.lock().get()`?

Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: This... would not be true if `other` is expired? `&output` will be `!= nullptr`, even if this gets called from `output`'s  destructor?

Comment (mrks) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: Aaaah, I misunderstood the original version. In that case, I think the original one is easier to read. Maybe add a comment "Check if `other` either points to output or to an already deleted node"?

Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: Reverted to `other.expired()` check. I think, however, that the 10 line comment above this check doesn't need further expansion
