### PR TITLE
Catch division by zero

### LINKED ISSUE #584: DIV/0 is uncaught
```
(debug)> load src/test/tables/int_int.tbl t
Loading src/test/tables/int_int.tbl into table "t" ...
(debug)> INSERT INTO t VALUES (3, 0)
===
0 rows total (PARSE: 10 µs, COMPILE: 92 µs, EXECUTE: 5145 µs (wall time))
(debug)> SELECT a/b FROM t
Floating point exception: 8
```

### PR DESCRIPTION
**Pull request by lawben**
Fixes #584.

### CODE REVIEW

File: src/lib/operators/projection.cpp [hunk 1]
```diff
@@ -285,6 +285,23 @@ inline std::function<double(const double&, const double&)> Projection::_get_oper
   return _get_base_operator_function<double>(type);
 }
 
+/**
+ * Specialized arithmetic operator implementation for int
+ * Division by 0 needs to be caught by integers.
```
Comment (mrks) [inline src/lib/operators/projection.cpp]: "caught *by* integers"?
