### PR TITLE
CI: Use clang-10

### LINKED ISSUE #2074: Prepare for next-gen toolchain
<s>Many recent CI fails disappeared after cleaning ccache. I have reason to believe that this fix could apply to us:

> The opt-in “file_macro sloppiness” mode has been removed so that the input file path now is always included in the direct mode hash. This fixes a bug that could result in false cache hits in an edge case when “file_macro sloppiness” is enabled and several identical source files include a relative header file with the same name but in different directories.

Unfortunately, ccache 3.7.6 is only available with Ubuntu Focal, which will be released later this month. We can start now by working on the release candidate.</s> Nope, still broken.

- [x] Build, tag, and push 20.04 Dockerfile
- [x] Update Jenkinsfile
- [x] <s>Reenable ccache (`rm /mnt/ccache/*` on imresx01, which sets the conf file back to default); check if it now works for clang, make sure that it is on tmpfs.</s> #2108 
- [x] Make builds fit for clang-10, add gcc-10 build in CI
- [ ] Make builds fit for gcc-10, add gcc-10 build in CI, at least glance at static analysis
- [x] Add mode for external users that disables -Werror, -Weverything etc.
- [x] Add that mode to https://github.com/hyrise/hyrise/wiki/Step-by-Step-Guide
- [x] Use newer compilers for asan, clang-tidy, etc.
- [x] Update year in LICENSE

Hopefully, this comes without any breaking changes. Currently, I don't see a reason to completely move to a new compiler.

### PR DESCRIPTION
**Pull request by mrks**
Even if clang-10 is not our default version yet, we should change most builds so that we have newer versions of asan, tsan, etc.

We still have a clang-9 debug build and continue to use clang-9 for Mac.

closes #2074, as we will not be able to support gcc-10 any time soon. :(

TODO:
- [x] Rebuild docker image

### CODE REVIEW

**Comment by mrks** [comment]
nope

File: scripts/clang_tidy_wrapper.sh [hunk 1]
```diff
@@ -14,6 +14,9 @@ if grep "$file_relative_to_source" $cmake_source_dir/.clang-tidy-ignore > /dev/n
 	echo "clang-tidy: Ignoring $file_relative_to_source"
 	exit 0
 else
-	exec clang-tidy $file $@
-  exit $?
+	if [ -x /usr/local/bin/brew ]; then
+		exec $(brew --prefix llvm)/bin/clang-tidy $file $@
```
Comment (Bouncner) [inline scripts/clang_tidy_wrapper.sh:18]: Does apple ship it's own clang tidy or what is the reason for this change?

Comment (Bouncner) [reply scripts/clang_tidy_wrapper.sh:18]: Also, why execute v9 when brew is used?

File: src/benchmarklib/benchmark_runner.cpp [hunk 2]
```diff
@@ -400,10 +400,10 @@ cxxopts::Options BenchmarkRunner::get_basic_cli_options(const std::string& bench
   // some point. The way this is solved here is not really nice, but as the TPC-C benchmark binary has just a main
   // method and not a class, retrieving this default value properly would require some major refactoring of how
   // benchmarks interact with the BenchmarkRunner. At this moment, that does not seem to be worth the effort.
-  const auto default_mode = (benchmark_name == "TPC-C Benchmark" ? "Shuffled" : "Ordered");
+  const auto* const default_mode = (benchmark_name == "TPC-C Benchmark" ? "Shuffled" : "Ordered");
 
   // TPC-C does not support binary caching
-  const auto default_dont_cache_binary_tables = (benchmark_name == "TPC-C Benchmark" ? "true" : "false");
+  const auto* const default_dont_cache_binary_tables = (benchmark_name == "TPC-C Benchmark" ? "true" : "false");
```
Comment (Bouncner) [inline src/benchmarklib/benchmark_runner.cpp:406]: What? A const pointer to a const object?

File: src/lib/operators/abstract_join_operator.cpp [hunk 3]
```diff
@@ -56,7 +56,7 @@ std::string AbstractJoinOperator::description(DescriptionMode description_mode)
     return "Column #"s + std::to_string(column_id);
   };
 
-  const auto separator = description_mode == DescriptionMode::MultiLine ? "\n" : " ";
+  const auto* const separator = description_mode == DescriptionMode::MultiLine ? "\n" : " ";
```
Comment (Bouncner) [inline src/lib/operators/abstract_join_operator.cpp:59]: I don't get why this is a pointer?

File: src/lib/operators/join_index.cpp [hunk 4]
```diff
@@ -64,8 +64,8 @@ const std::string& JoinIndex::name() const {
 }
 
 std::string JoinIndex::description(DescriptionMode description_mode) const {
-  const auto separator = description_mode == DescriptionMode::MultiLine ? "\n" : " ";
-  const auto index_side_str = _index_side == IndexSide::Left ? "Left" : "Right";
+  const auto* const separator = description_mode == DescriptionMode::MultiLine ? "\n" : " ";
+  const auto* const index_side_str = _index_side == IndexSide::Left ? "Left" : "Right";
```
Comment (Bouncner) [inline src/lib/operators/join_index.cpp:68]: Same as above.

File: src/lib/storage/index/adaptive_radix_tree/adaptive_radix_tree_nodes.cpp [hunk 5]
```diff
@@ -141,8 +141,8 @@ AbstractIndex::Iterator ARTNode16::_delegate_to_child(
     const std::function<Iterator(std::iterator_traits<std::array<uint8_t, 16>::iterator>::difference_type, size_t)>&
         function) const {
   auto partial_key = key[depth];
-  auto partial_key_iterator = std::lower_bound(_partial_keys.begin(), _partial_keys.end(), partial_key);
-  auto partial_key_pos = std::distance(_partial_keys.begin(), partial_key_iterator);
+  const auto* const partial_key_iterator = std::lower_bound(_partial_keys.begin(), _partial_keys.end(), partial_key);
```
Comment (Bouncner) [inline src/lib/storage/index/adaptive_radix_tree/adaptive_radix_tree_nodes.cpp:144]: Iterator as a pointer?

File: src/lib/storage/vector_compression/simd_bp128/simd_bp128_packing.hpp [hunk 6]
```diff
@@ -21,8 +21,8 @@ class SimdBp128Packing {
   static constexpr auto meta_block_size = block_size * blocks_in_meta_block;
 
  public:
-  static void write_meta_info(const uint8_t* in, uint128_t* out);
-  static void read_meta_info(const uint128_t* in, uint8_t* out);
+  static void write_meta_info(const uint8_t* in, uint128_t* const out);
```
Comment (Bouncner) [inline src/lib/storage/vector_compression/simd_bp128/simd_bp128_packing.hpp:24]: Isn't in double const and the output just const on the pointer?

File: scripts/clang_tidy_wrapper.sh (hunk 1 above)
Comment (mrks) [reply scripts/clang_tidy_wrapper.sh:18]: > Does apple ship it's own clang tidy or what is the reason for this change?

brew does not link `clang-tidy` by default. As such, it is not guaranteed to exist.

> Also, why execute v9 when brew is used?

Where are you seeing that?

File: src/benchmarklib/benchmark_runner.cpp (hunk 2 above)
Comment (mrks) [reply src/benchmarklib/benchmark_runner.cpp:406]: In the end, they both mean the same thing. `const auto` gets deduced to `const char* const`. I have no idea why clang-tidy suddenly wants to make this more explicit, but I think we can't turn it off without turning off other "this could be const" warnings too

File: src/lib/operators/abstract_join_operator.cpp (hunk 3 above)
Comment (mrks) [reply src/lib/operators/abstract_join_operator.cpp:59]: Because "\n" and " " are.

File: src/lib/storage/index/adaptive_radix_tree/adaptive_radix_tree_nodes.cpp (hunk 5 above)
Comment (mrks) [reply src/lib/storage/index/adaptive_radix_tree/adaptive_radix_tree_nodes.cpp:144]: An iterator does not have to be class or a struct.

> Iterators are a generalization of pointers that allow a C++ program to work with different data structures (for example, containers and ranges) in a uniform manner.

As above, I am not sure what the intention of this is, but I don't see real harm being done.

File: src/lib/storage/vector_compression/simd_bp128/simd_bp128_packing.hpp (hunk 6 above)
Comment (mrks) [reply src/lib/storage/vector_compression/simd_bp128/simd_bp128_packing.hpp]: Yepp

File: src/lib/utils/size_estimation_utils.hpp [hunk 7]
```diff
@@ -13,7 +13,8 @@ template <typename T>
 #ifdef __clang__
 __attribute__((optnone))  // Fixes issues with memcheck. As we are only accessing constant values, shouldn't cost much
 #endif
-size_t string_heap_size(const T& string) {
+size_t
```
Comment (Bouncner) [inline src/lib/utils/size_estimation_utils.hpp:16]: ?

File: src/lib/storage/vector_compression/simd_bp128/simd_bp128_packing.hpp (hunk 6 above)
Comment (Bouncner) [reply src/lib/storage/vector_compression/simd_bp128/simd_bp128_packing.hpp]: Ok, the `in` makes sense to me now. What does `uint128_t* const out` actually mean? Can the pointer we non-const but the content is supposed to be const? Doesn't make sense to me.

File: scripts/clang_tidy_wrapper.sh (hunk 1 above)
Comment (Bouncner) [reply scripts/clang_tidy_wrapper.sh:18]: Misread that.

File: src/lib/utils/size_estimation_utils.hpp (hunk 7 above)
Comment (mrks) [reply src/lib/utils/size_estimation_utils.hpp:16]: No idea. clang-format did it.

File: src/lib/storage/vector_compression/simd_bp128/simd_bp128_packing.hpp (hunk 6 above)
Comment (mrks) [reply src/lib/storage/vector_compression/simd_bp128/simd_bp128_packing.hpp]: > Can the pointer we non-const but the content is supposed to be const?

Yes. In that case, you could make the pointer point somewhere else, but you couldn't change the value that is pointed to.

However, in the code above, we have the exact opposite: The pointer cannot be changed, but the value that is pointed to can (const applies to left)

Comment (Bouncner) [reply src/lib/storage/vector_compression/simd_bp128/simd_bp128_packing.hpp]: So the `const auto* const separator` we have all over the place is an example where the const applies to the right side (for the left const it's clear as there is not left of it, but the the right side that's "transitive"???).
But then again here in the SIMD code, it applies to the pointer.

Hmpf ...

Comment (mrks) [reply src/lib/storage/vector_compression/simd_bp128/simd_bp128_packing.hpp]: It's a const pointer to a const thing, i.e., neither can the pointer be changed to point somewhere else nor can the "thing" be changed itself.

What do you mean with "transitive"?

Did you watch the east const video? I think that clarifies it.

File: src/lib/utils/size_estimation_utils.hpp (hunk 7 above)
Comment (Bouncner) [reply src/lib/utils/size_estimation_utils.hpp:16]: Format is drunk.

File: src/lib/storage/vector_compression/simd_bp128/simd_bp128_packing.hpp (hunk 6 above)
Comment (Bouncner) [reply src/lib/storage/vector_compression/simd_bp128/simd_bp128_packing.hpp]: I've seen it. But I am not sure I fully understood it. :)

What bothers me, is that we have two syntaxes in the same line (if I get it right): `const uint8_t* const in, uint128_t* const out` ... for in, the const is on the left side, for out it's on the right side. West coast, east coast. Or am I again mistaken?

Comment (mrks) [reply src/lib/storage/vector_compression/simd_bp128/simd_bp128_packing.hpp]: That's why west const sucks. ;)

If we were using east const only, it would look like this:

`uint8_t const *const in, uint128_t *const out`

Looks like the [clang-format folks are working on it](https://reviews.llvm.org/D69764). It would be interesting to see how many lines would have to change.

Comment (Bouncner) [reply src/lib/storage/vector_compression/simd_bp128/simd_bp128_packing.hpp]: Definitely something I have to get used to. If clang-format will solve that for us: fine. But until then we should make sure that at least we don't mix both styles in a single line.
