### PR TITLE
Fix SQLiteWrapper returning empty table if last char is a newline

### LINKED ISSUE #984: SQLiteWrapper returns empty table if last char is a newline
Don't know if this is SQLite or the wrapper, but

```sql
SELECT * FROM t;
```
returns some table, whereas
```sql
SELECT * FROM t;
<newline>

```
doesn't.

If this can be fixed, we can re-add DROP VIEW to TPC-H 15 and patch the string before handing it to sqlite in the tpch_test.cpp
While the behaviour is as described above, this is too shaky, imo.

@lanice any idea?

### PR DESCRIPTION
**Pull request by lanice**
Fixes #984 

@mrzzzrm, the problem occured because:
The SQLiteWrapper divides the sql string into different queries by the semicolon, so
```
SELECT * FROM t;\n
```
would result in 2 queries, `SELECT * FROM t;`, and `\n`. The result table is determined by the last query executed, which in this case is `\n`. Therefore it just returned an empty table.

Update: Letting the `SQLPipeline` handle the splitting for us now.

### CODE REVIEW

File: src/test/sql/sqlite_testrunner/sqlite_wrapper.cpp [hunk 1]
```diff
@@ -92,7 +92,8 @@ std::shared_ptr<Table> SQLiteWrapper::execute_query(const std::string& sql_query
   std::vector<std::string> queries;
   boost::algorithm::split(queries, sql_query, boost::is_any_of(";"));
 
-  queries.erase(std::remove_if(queries.begin(), queries.end(), [](std::string const& query) { return query.empty(); }),
+  queries.erase(std::remove_if(queries.begin(), queries.end(),
+                               [](std::string const& query) { return query.empty() || query == "\n"; }),
```
Comment (mrzzzrm) [inline src/test/sql/sqlite_testrunner/sqlite_wrapper.cpp]: Dumb question: if there are multiple newlines after a query, this wouldn't fix it, right? Because two newlines is what I had at the end of TPC-H 15 after I removed the `DROP VIEW` statement.

Does it maybe make sense to use the SQLPipeline's functionality of splitting up a query into statements here?

Comment (lanice) [reply src/test/sql/sqlite_testrunner/sqlite_wrapper.cpp]: Right, overlooked that.

I'm not sure. I mean we could, but that would mean parsing the sql strings with our hsql::SQLParser etc, which we don't need for the SQLiteWrapper. I will check it out and see how it looks in the end.
