### PR TITLE
Recreate query plan for subselects

### LINKED ISSUE #777: Cache broken for subqueries
Once #727 is merged, cached queries will be broken:

```
(debug)> load src/test/tables/int_int_int.tbl int_int_int
Loading src/test/tables/int_int_int.tbl into table "int_int_int" ...
(debug)> SELECT * FROM int_int_int WHERE a = (SELECT MAX(b) FROM int_int_int)
=== Columns
|       a|       b|       c|
|     int|     int|     int|
=== Chunk 0 ===
|      10|      10|      10|
===
1 rows total (COMPILE: 57 µs, EXECUTE: 284 µs (wall time))
(debug)> INSERT INTO int_int_int VALUES (11,11,11)
===
0 rows total (COMPILE: 178 µs, EXECUTE: 159 µs (wall time))
(debug)> SELECT * FROM int_int_int WHERE a = (SELECT MAX(b) FROM int_int_int)
=== Columns
|       a|       b|       c|
|     int|     int|     int|
=== Chunk 0 ===
|      10|      10|      10|
===
1 rows total (COMPILE: 57 µs, EXECUTE: 284 µs (wall time))
```
The PQPExpression that holds the subquery does not get re-executed.

Of course this should be tested.

I think it is easier if someone from our team who has dealt with recreation and the cache before looks at this. @lawben maybe?

### PR DESCRIPTION
**Pull request by lawben**
This PR fixes #777. The subselect operator is now also recreated.

### CODE REVIEW

File: src/test/sql/sql_pipeline_statement_test.cpp [hunk 1]
```diff
@@ -683,4 +692,27 @@ TEST_F(SQLPipelineStatementTest, CacheQueryPlan) {
...
+
+  auto expected_first_result = std::make_shared<Table>(_int_int_int_column_definitions, TableType::Data);
+  expected_first_result->append({10, 10, 10});
+
+  EXPECT_TABLE_EQ_UNORDERED(first_subselect_result, expected_first_result);
+
+  SQLPipelineStatement{"INSERT INTO table_int VALUES (11, 11, 11)"}.get_result_table();
+
+  SQLPipelineStatement second_subselect_sql_pipeline{subselect_query};
+  const auto second_subselect_result = second_subselect_sql_pipeline.get_result_table();
```
Comment (mrks) [inline src/test/sql/sql_pipeline_statement_test.cpp]: This test is a bit too high-level. You are assuming that the sql pipeline has a cache.
The bug was with the recreate function, so you should explicitly use that one instead of relying on the cache to call it for you.
Other than that, this is good to go.

Comment (mrzzzrm) [reply src/test/sql/sql_pipeline_statement_test.cpp]: There is recreation_test.cpp (gosh, what a name), test should probably go there.

File: src/lib/operators/pqp_expression.cpp [hunk 2]
```diff
@@ -100,7 +100,7 @@ bool PQPExpression::operator==(const PQPExpression& other) const {
   return _column_id == other._column_id;
 }
 
-std::shared_ptr<PQPExpression> PQPExpression::set_placeholder_value(const AllTypeVariant& value) {
+std::shared_ptr<PQPExpression> PQPExpression::copy_with_placeholder_value(const AllTypeVariant& value) {
```
Comment (mrzzzrm) [inline src/lib/operators/pqp_expression.cpp]: Sorry to point this out in this PR, but what is this function doing? All it is doing is re-using the alias and the _column_id from this expression? It's not even Asserting this Expression is actually a placeholder.
I'd expect a method with this name to recursively search the expression for placeholders and replace those subexpression with placeholders... I think I'll create an issue for this.

Comment (mrzzzrm) [reply src/lib/operators/pqp_expression.cpp]: #780

**Comment by lawben** [comment]
I'm on vacation at the moment, will finish this on Wednesday.
