### PR TITLE
LZ4 binary export/import fix

### LINKED ISSUE #2143: LZ4 binary exports appear to be corrupt
Reproducible with executing the following command twice (first to create the binaries, second will read them): `./hyriseBenchmarkTPCH -e LZ4 -r 1 -s 0.1`.

The second TPC-H run segfaults in Q7:
```- Benchmarking TPC-H 07
[1]    4851 segmentation fault  ./hyriseBenchmarkTPCH -e LZ4 -r 1 -s 0.1
```

Tested on e54ee0 on MacOS and Linux (strangely, here Q5 failed).

### PR DESCRIPTION
**Pull request by j-tr**
fixes #2143 + updating cache files at re-encoding

### CODE REVIEW

File: src/lib/storage/lz4_segment.cpp [hunk 1]
```diff
@@ -235,7 +235,7 @@ template <typename T>
 void LZ4Segment<T>::_decompress_block_to_bytes(const size_t block_index, std::vector<char>& decompressed_data,
                                                const size_t write_offset) const {
   const auto decompressed_block_size = block_index + 1 != _lz4_blocks.size() ? _block_size : _last_block_size;
-  const auto& compressed_block = _lz4_blocks[block_index];
+  const auto& compressed_block = _lz4_blocks.at(block_index);
```
[the remark this answers is not in the document]
Comment (Bouncner) [reply src/lib/storage/lz4_segment.cpp:238]: Since it's not within a hot loop and we don't optimize exporting for performance anywhere else, I'd say it's fine.

File: src/lib/import_export/binary/binary_writer.cpp [hunk 2]
```diff
@@ -265,17 +265,11 @@ void BinaryWriter::_write_segment(const LZ4Segment<T>& lz4_segment, std::ofstrea
...
-    if (lz4_segment.lz4_blocks().size() > 1) {
-      export_value(ofstream, static_cast<uint32_t>(lz4_segment.block_size()));
-    }
-    // Write last decompressed block size
-    export_value(ofstream, static_cast<uint32_t>(lz4_segment.last_block_size()));
-  }
+  // Write block size
+  export_value(ofstream, static_cast<uint32_t>(lz4_segment.block_size()));
+
+  // Write last decompressed block size
```
Comment (Bouncner) [inline src/lib/import_export/binary/binary_writer.cpp:271]: Confusing to talk about " " block sizes and "decompressed" block sizes.

File: src/lib/import_export/binary/binary_writer.hpp [hunk 3]
```diff
@@ -177,25 +177,23 @@ class BinaryWriter {
    * Encoding Type               | EncodingType                        | 1
    * Number of Rows (in seg)     | uint32_t                            | 4
    * Number of Blocks            | uint32_t                            | 4
-   * Block size¹                 | uint32_t                            | 4
+   * Block size                  | uint32_t                            | 4
    * Last Block size             | uint32_t                            | 4
    * lz4 Block sizes             | vector<uint32_t>                    | Number of blocks * 4
```
Comment (Bouncner) [inline src/lib/import_export/binary/binary_writer.hpp:182]: We usually always write "LZ4".
