### PR TITLE
NULL in Projection

### LINKED ISSUE #524: NULL in Projection
```
(debug)> load src/test/tables/int_float_with_null.tbl a
Loading src/test/tables/int_float_with_null.tbl into table "a" ...
(debug)> SELECT a + 5 FROM a
Exception thrown while executing query plan:
  Can’t return value of column type because it is null.
Execution failed and the transaction has been rolled back.
```

### PR DESCRIPTION
**Pull request by mrks**
fixes #524 

```
(debug)> load src/test/tables/int_int4_with_null.tbl t
Loading src/test/tables/int_int4_with_null.tbl into table "t" ...
(debug)> SELECT a, a+1, b, b+1 AS c, a+1 + b+1, a + NULL + 1 FROM t
=== Columns
|       a|   a + 1|       b|       c|((a + 1) + b) + 1|(a + NULL) + 1|
|     int|     int|     int|     int|              int|           int|
=== Chunk 0 ===
|      18|      19|       2|       3|               22|          NULL|
|       7|       8|    NULL|    NULL|             NULL|          NULL|
|       7|       8|      17|      18|               26|          NULL|
|       9|      10|    NULL|    NULL|             NULL|          NULL|
|       6|       7|       7|       8|               15|          NULL|
|    NULL|    NULL|       1|       2|             NULL|          NULL|
|      13|      14|       4|       5|               19|          NULL|
|    NULL|    NULL|    NULL|    NULL|             NULL|          NULL|
|       9|      10|      10|      11|               21|          NULL|
|       7|       8|      13|      14|               22|          NULL|
|       0|       1|       1|       2|                3|          NULL|
===
11 rows total (PARSE: 0.000011 ms, COMPILE: 0.005013 ms, EXECUTE: 0.006261 ms (wall time))
```

### CODE REVIEW

File: src/lib/operators/projection.cpp [hunk 1]
```diff
@@ -116,23 +127,27 @@ const std::string Projection::_get_type_of_expression(const std::shared_ptr<Expr
...
+                                      type_left + " vs " + type_right + ")");
   return type_left;
 }
 
 template <typename T>
-const tbb::concurrent_vector<T> Projection::_evaluate_expression(const std::shared_ptr<Expression>& expression,
-                                                                 const std::shared_ptr<const Table> table,
-                                                                 const ChunkID chunk_id) {
+const pmr_concurrent_vector<std::optional<T>> Projection::_evaluate_expression(
+    const std::shared_ptr<Expression>& expression, const std::shared_ptr<const Table> table, const ChunkID chunk_id) {
```
Comment (mrks) [inline src/lib/operators/projection.cpp]: I am not 100% happy with having vectors of optionals here. This wastes a byte per row. However, for compatibility with `std::plus` and so on, this is really handy. Also, these vectors are only used during execution and will then be destroyed.

File: src/lib/storage/dictionary_column.cpp [hunk 2]
```diff
@@ -67,10 +72,11 @@ std::shared_ptr<const BaseAttributeVector> DictionaryColumn<T>::attribute_vector
 
 // TODO(anyone): This method is part of an algorithm that hasn’t yet been updated to support null values.
 template <typename T>
-const pmr_concurrent_vector<T> DictionaryColumn<T>::materialize_values() const {
-  pmr_concurrent_vector<T> values(_attribute_vector->size(), T(), _dictionary->get_allocator());
+const pmr_concurrent_vector<std::optional<T>> DictionaryColumn<T>::materialize_values() const {
+  pmr_concurrent_vector<std::optional<T>> values(_attribute_vector->size(), std::nullopt, _dictionary->get_allocator());
 
   for (ChunkOffset chunk_offset = 0; chunk_offset < _attribute_vector->size(); ++chunk_offset) {
+    if (is_null(chunk_offset)) continue;
```
Comment (TwoLaid) [inline src/lib/storage/dictionary_column.cpp]: So the TODO comment above can be removed?

File: src/lib/operators/projection.cpp [hunk 3]
```diff
@@ -116,23 +127,27 @@ const std::string Projection::_get_type_of_expression(const std::shared_ptr<Expr
...
+  Assert(type_left == type_right, "Projection currently only supports expressions with same type on both sides (" +
+                                      type_left + " vs " + type_right + ")");
   return type_left;
 }
 
 template <typename T>
-const tbb::concurrent_vector<T> Projection::_evaluate_expression(const std::shared_ptr<Expression>& expression,
-                                                                 const std::shared_ptr<const Table> table,
-                                                                 const ChunkID chunk_id) {
+const pmr_concurrent_vector<std::optional<T>> Projection::_evaluate_expression(
```
Comment (lawben) [inline src/lib/operators/projection.cpp]: could you maybe split this method? it is ~80 lines and covers quite a few different cases. at least the whole `is_literal` block should be extracted for readability.

File: src/lib/storage/dictionary_column.cpp (hunk 2 above)
Comment (mrks) [reply src/lib/storage/dictionary_column.cpp]: Yes. Done.

File: src/lib/storage/dictionary_column.hpp [hunk 4]
```diff
@@ -31,7 +31,11 @@ class DictionaryColumn : public BaseDictionaryColumn {
   // return the value at a certain position. If you want to write efficient operators, back off!
   const AllTypeVariant operator[](const ChunkOffset chunk_offset) const override;
 
+  // Returns whether a value is NULL
+  bool is_null(const ChunkOffset chunk_offset) const;
```
Comment (lawben) [inline src/lib/storage/dictionary_column.hpp]: it seems like this could cause some confusion with out global `is_null`. Maybe the global one should be renamed instead of polluting the namespace with a rather basic name.

Comment (mrks) [reply src/lib/storage/dictionary_column.hpp]: Good point. Should we rename the global one to `variant_is_null`?

Comment (lawben) [reply src/lib/storage/dictionary_column.hpp]: Yes, that seems like a reasonable name.

File: src/lib/operators/projection.cpp (hunk 3 above)
Comment (mrks) [reply src/lib/operators/projection.cpp]: It is quite long, true. What do you mean by the "is_literal" block? Those are four different cases that have to be handled separately.

Having a hard time separating this into meaningful submethods. If they are only called in exactly one order and do not serve any purpose outside of this method, is that better than one single, long method?

Comment (lawben) [reply src/lib/operators/projection.cpp]: I guess this is more of a design preference question than anything else. So if you don't think it makes sense, then leave it as is. It's not a major deal to me.

File: src/lib/storage/dictionary_column.hpp (hunk 4 above)
Comment (mrks) [reply src/lib/storage/dictionary_column.hpp]: done
