### PR TITLE
Don't start operator if Tx already failed

### LINKED ISSUE #76: Forgetting to use Validate leads to obscure behaviour
When, e.g., updating a row twice and not validating after `GetTable` a condition variable deep in the mvcc logic will wait forever. 

screenshot from 2017-06-15 14-26-37

Instead it should be investigated, whether `Delete` might sanity-check for double-deletes in debug builds. This took me a while to find, shouldn't happen to someone else, again.

### PR DESCRIPTION
**Pull request by mrks**
If the TX is already gone, no operator should be executed. This also fixes #76 because the second update will not be executed.

### CODE REVIEW

**Comment by mjendruk** [comment]
Isn’t this the same as in https://github.com/hyrise/hyrise/blob/faf4d6b0a292afd94793132b4e9877775fd26473/src/lib/scheduler/operator_task.cpp#L53

**Comment by mrks** [comment]
Almost, I was not aware of that. This fixes the behavior seen in #76, where no tasks were used. I will move it from the operator_task to the actual operator.

File: src/lib/operators/abstract_operator.cpp [hunk 1]
```diff
@@ -20,7 +20,17 @@ void AbstractOperator::execute() {
...
+    /**
+     * Do not execute Operators if transaction has been aborted.
+     * Not doing so is crucial in order to make sure no other
+     * tasks of the Transaction run while the Rollback happens.
+     */
+    if (transaction_context->aborted()) {
+      return;
+    }
+    transaction_context->on_operator_started();
+  }
```
Comment (mjendruk) [inline src/lib/operators/abstract_operator.cpp]: Just one more suggestion :)
```c++
  if (transaction_context) {
    /**
     * Do not execute Operators if transaction has been aborted.
     * Not doing so is crucial in order to make sure no other
     * tasks of the Transaction run while the Rollback happens.
     */
    if (transaction_context->aborted()) {
      return;
    }
    transaction_context->on_operator_started();
    _output = _on_execute(transaction_context);
    transaction_context->on_operator_finished();
  }
  else {
    _output = _on_execute(transaction_context);
  }
```

Comment (mrks) [reply src/lib/operators/abstract_operator.cpp]: done

File: src/lib/operators/abstract_operator.cpp [hunk 2]
```diff
@@ -20,9 +20,21 @@ void AbstractOperator::execute() {
 
   auto transaction_context = this->transaction_context();
 
-  if (transaction_context) transaction_context->on_operator_started();
-  _output = _on_execute(transaction_context);
-  if (transaction_context) transaction_context->on_operator_finished();
+  if (transaction_context) {
```
Comment (Bensk1) [inline src/lib/operators/abstract_operator.cpp]: Do we have a convention regarding checking for `nullptr`?

Comment (mrks) [reply src/lib/operators/abstract_operator.cpp]: Nope. If you think we should have one, feel free to open an issue for it. Personally, I am fine with either and also with seeing them mixed.
