### PR TITLE
Fix JIT tests - bug #867

### LINKED ISSUE #867: JIT test fails
Current master builds but does not pass a JIT test (https://ares.epic.hpi.uni-potsdam.de/jenkins/blue/organizations/jenkins/Hyrise%2Fhyrise/detail/master/271/pipeline/).

```
[----------] 2 tests from JitVariantVectorTest
[ RUN      ] JitVariantVectorTest.GetAndSet
[       OK ] JitVariantVectorTest.GetAndSet (1 ms)
[ RUN      ] JitVariantVectorTest.IsNullAndSetIsNull
[       OK ] JitVariantVectorTest.IsNullAndSetIsNull (0 ms)
[----------] 2 tests from JitVariantVectorTest (1 ms total)

[----------] 1 test from JitComputeTest
[ RUN      ] JitComputeTest.TriggersComputationOfNestedExpression
../../../src/lib/operators/jit_operator/operators/../jit_operations.hpp:56:88: runtime error: signed integer overflow: 1125898167 + 1059961393 cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../../src/lib/operators/jit_operator/operators/../jit_operations.hpp:56:88 in 
script returned exit code 1
```

An idea, @FabianWiebe ?

### PR DESCRIPTION
**Pull request by FabianWiebe**
Random generated numbers can cause int overflow during addition in JIT tests.
Switched to new random generators in JIT test to specify random number range.

Closes #867 .

### CODE REVIEW

File: src/test/operators/jit_operator/operators/jit_compute_test.cpp [hunk 1]
```diff
@@ -41,11 +43,17 @@ TEST_F(JitComputeTest, TriggersComputationOfNestedExpression) {
...
+  std::random_device rd;
+  std::mt19937 gen(rd());
+
   for (auto i = 0; i < 10; ++i) {
     // Create input tuple values
-    auto a = static_cast<int32_t>(std::rand());
-    auto b = static_cast<int32_t>(std::rand());
-    auto c = static_cast<int32_t>(std::rand());
+    std::uniform_int_distribution<> dis(0, std::numeric_limits<int32_t>::max());
+    auto a = static_cast<int32_t>(dis(gen));
```
Comment (mrks) [inline src/test/operators/jit_operator/operators/jit_compute_test.cpp]: Wouldn't `std::uniform_int_distribution<int32_t>` mean that you don't need this cast?

Comment (FabianWiebe) [reply src/test/operators/jit_operator/operators/jit_compute_test.cpp]: Yes, that makes it clearer. Is changed.
