### PR TITLE
Single Statement per SQLPipeline

### LINKED ISSUE #367: Harmonize calls of SQL interface
We have a couple of places where we execute SQL statements. Sometimes with, sometimes without the optimizer. Sometimes with, sometimes without transaction contexts. Everyone schedules the operators in their own way.

Places I can think of right now:
- Console
- SQL Test Runner
- SqlToResultTest
- TPC-H Test
- Network Interface (in the future)

There should be only one interface to run SQL queries.

### LINKED ISSUE #582: When SQL parsing fails, print proper error message

### PR DESCRIPTION
**Pull request by lawben**
Fixes #367 and fixed #582 

First of all, this is rather large again and changes a lot from the first SQLPipeline version. We needed this change to allow statements like this one to work: `"CREATE VIEW bla AS SELECT * FROM foo; SELECT * FROM bla;"`. In the first version, all statements were translated at once, which meant that `bla` was not yet visible in the second statement. 

```cpp
SQLPipeline sql_pipeline{query};
const auto& result_table = sql_pipeline.get_result_table();
``` 

------
Also, a nicer error message is now printed when an SQL query is not valid. This also supports multiline queries, which was the main purpose of this change.

image

### CODE REVIEW

**Comment by lanice** [comment]
One general comment before I look into the code more detailed, I **really** don't like going back from
`SQLPipeline{sql_query}.get_result_table();`
to
```
auto sql_pipelines = SQLPipeline::from_sql_string(query);
for (auto& sql_pipeline : sql_pipelines) {
  sql_pipeline.get_result_table();
}

const auto& result_table = sql_pipelines.back().get_result_table();
```
everywhere we want to use this.

When using this, I want **one** SQLPipeline executing my statement(s), and not multiple pipelines each holding and executing one (?) statement.
I think, if at all possible, we should handle all this withing the SQLPipeline like in your first version.

**Comment by mrks** [comment]
This comes with a couple of problems. How do we deal with the `get_*_plan` methods for the visualization? If a pipeline holds multiple queries, we would have to return a vector there. Same thing, probably more important, for getting the tasks. Once we have a network interface, that will be the interface used there (not get_result_tabe). How do we deal with multiple select statements inside one string?

What we could do is have a constructor `SQLPipeline(std::string sql)` that creates exactly one pipeline that can be used as it is the case right now. However, you could not give it a multi-statement sql query.

**Comment by lanice** [comment]
I'm not against processing each statement in a multi-statement query individually. I'm against having this be exposed to (or forced upon) the user of the SQLPipeline when it is not necessary. I'd like to create an `SQLPipeline` from a query, doesn't matter if single or multi-statement. Internally the pipeline can divide the query in to multiple `Statement`(s), and when I call `get_result_table()` the pipeline works through these statements as I would do myself as it is in the PR right now.

I think it is not a problem to provide **also** the option to access the individual plans/tasks in the pipeline, if needed (e.g. by the possible future network interface).

**Comment by lanice** [comment]
An option I think could be:

Rename SQLPipeline to, whatever, SQLStatement? Leave most of the functionality as is, except for having a normal constructor instead of a static method returning a vector. So one SQLStatement holds excatly that (what one SQLPipeline does in this PR), holding one statement with the ability to execute, return table, get plan, task, etc.

Create class SQLPipeline, which takes an SQL string in the constructor, and provides the methods `std::shared_ptr<const Table>& get_result_table()`, as well as `std::vector<SQLStatement> get_statements()`. When asked for `get_result_table()`, the pipeline executes the statements one after another, and returns the table. `get_statements()` just returns a vector with the statements, so that the user can do stuff themselves.
That way the simple case can be handles just with 
`SQLPipeline{sql_query}.get_result_table();`,
as well as the more customizable case with
```
auto sql_pipeline = SQLPipeline(sql_query);
for (auto& statement : sql_pipeline->get_statements()) {
  statement.execute();
}
... etc
```

**Comment by mrzzzrm** [comment]
I think having a one line interface for executing a sql query is a very important design goal as it makes the DB accessible for new devs and the code readable. Generating LQPs, PQPs and TaskSets should be one-liners as well. 

I would rename `SQLPipeline` to `SQLStatementPipeline` (or `SQLPipelineStatement`) to emphasize it can only contain **one** SQL statement. `SQLStatementPipeline` has to normal interface of `get_lqp()`, `get_task_set()`, `get_result_table()` which perform their evaluation lazily. Additionally, I would introduce a `SQLStatementType` returned from `type()` that, based on the parse result, indicates whether a `SQLStatementPipeline` is DDL, DML, DQL, etc...
Now, the `SQLPipeline` contains multiple `SQLStatementPipeline`s - to make a long story short, if you call `get_lqps()` on `SQLPipeline` and there is a DDL or DML `SQLStatementPipeline` followed by a DQL one, the request is potentially not fulfillable, because parts of the statements would need to be executed in order to return the LQPs and that wouldn't be okay - so `get_lqps()` throws in this case.

```c++
SQLPipeline{"SELECT * FROM A; SELECT * FROM B;"}.get_lqps(); // That's fine
SQLPipeline{"CREATE VIEW x; SELECT * FROM A; SELECT * FROM B;"}.get_parse_results(); // This is too
SQLPipeline{"CREATE VIEW x; SELECT * FROM A; SELECT * FROM B;"}.get_lqps(); // This is not
SQLPipeline{"CREATE VIEW x; SELECT * FROM A; SELECT * FROM B;"}.get_result_tables(); // This, again, is
```

When you think about the console, the visualization code would look like this:

```c++
try {
  const auto lqps = SQLPipeline{sql}.get_lqps();
  // ...visualize lqps
} catch(const something& e) {
  print("error while visualizing: " + e.what());
}
```

When you do `> visualize lqp SELECT * FROM A;` everything is fine, when you do `> visualize lqp CREATE VIEW ...; SELECT * FROM x;` you'll get an exception along the lines of "(Potentially) can't get the LQP of a statement which follows a DDL statement" and you (as the console user) fix it by turning it into two commands `> CREATE VIEW...` and `visualize lqp SELECT * FROM A`.

How does that sound?

**Comment by mrzzzrm** [comment]
(spoke with @lanice about this and I think we generally agree on this design)

**Comment by lawben** [comment]
Looks like I'm gonna have a great Christmas building this :) @mrzzzrm I like that design too but I still have some questions.

I'm in the office tomorrow, it would be if we could talk about it then. Just so we deal with some open questions. Or is this something for our meeting on Wednesday when everyone is there? I guess @mrks has an opportunity here too...

**Comment by mrzzzrm** [comment]
I'll come in tomorrow afternoon!

**Comment by lanice** [comment]
I'm pro `SQLPipelineStatement` as name. I think it makes sense and sounds good that the `SQLPipeline` contains multiple `SQLPipelineStatement`s.

**Comment by mrks** [comment]
Sorry for the delay. I am still busy with getting that paper ready for submission, but I am fully committed to working through this before I leave for Christmas.

File: src/bin/console/console.cpp [hunk 1]
```diff
@@ -215,36 +215,55 @@ int Console::_eval_command(const CommandFunction& func, const std::string& comma
...
+int Console::_eval_sql(const std::string& sql) {
+  if (!_initialize_pipelines(sql)) return ReturnCode::Error;
+
+  for (auto& pipeline : _sql_pipelines) {
+    try {
+      pipeline.get_result_table();
+    } catch (const std::exception& exception) {
+      out(std::string(exception.what()) + "\n");
+      if (pipeline.transaction_context() && pipeline.transaction_context()->aborted()) {
+        out("The transaction has been rolled back.\nAll previous statements have been commited.\n");
```
Comment (mrks) [inline src/bin/console/console.cpp]: Mmmh? If we have an explicitly created tx context, it should be *completely* rolled back. That is the point of a rollback.

File: src/bin/console/console.cpp [hunk 2]
```diff
@@ -215,36 +215,55 @@ int Console::_eval_command(const CommandFunction& func, const std::string& comma
...
   // Print result (to Console and logfile)
   if (table) {
     out(table);
   }
+
+  std::chrono::microseconds compile_time_micros{};
+  std::chrono::microseconds execution_time_micros{};
+  for (const auto& pipeline : _sql_pipelines) {
+    compile_time_micros += pipeline.compile_time_microseconds();
+    execution_time_micros += pipeline.execution_time_microseconds();
```
Comment (mrks) [inline src/bin/console/console.cpp]: Why not "microseconds?

File: src/bin/console/console.cpp [hunk 3]
```diff
@@ -436,60 +456,96 @@ int Console::print_table(const std::string& args) {
...
+    second_word = input_words[1];
   }
 
-  // Removes mode from sql string. If no mode is set, does nothing.
-  sql = input.substr(mode.size(), input.size());
+  const bool no_execute = (first_word == "noexec" || second_word == "noexec");
+
+  std::string mode;
+  if (first_word == "lqp" || first_word == "lqpopt")
+    mode = first_word;
```
Comment (mrks) [inline src/bin/console/console.cpp]: Please don't use multiline ifs without braces.

File: src/lib/sql/sql_pipeline.cpp [hunk 4]
```diff
@@ -1,163 +1,158 @@
...
-    // Returned cached result
-    return *(_parsed_sql.get());
-  }
-
-  auto parse_result = std::make_unique<hsql::SQLParserResult>();
-
-  const auto started = std::chrono::high_resolution_clock::now();
+std::vector<SQLPipeline> SQLPipeline::_from_sql_string(const std::string& sql,
+                                                       std::shared_ptr<TransactionContext> transaction_context,
+                                                       bool use_mvcc) {
```
Comment (mrks) [inline src/lib/sql/sql_pipeline.cpp]: Do we need the context parameter here? If we pass a context, we shouldn't have to pass use_mvcc. If we set use_mvcc, passing a context makes no sense. This is only for the case that we do not have an explicit context and want to decide if an implicit context should be created or not, correct?

File: src/lib/sql/sql_pipeline.cpp [hunk 5]
```diff
@@ -1,163 +1,158 @@
...
+  if (!parse_result.isValid()) {
+    throw std::runtime_error(_create_parse_error_message(sql, parse_result));
   }
 
-  const auto done = std::chrono::high_resolution_clock::now();
-  _parse_time_sec = std::chrono::duration_cast<std::chrono::microseconds>(done - started);
+  auto pipelines = std::vector<SQLPipeline>();
+  pipelines.reserve(parse_result.size());
+
+  for (auto* statement : parse_result.releaseStatements()) {
```
Comment (mrks) [inline src/lib/sql/sql_pipeline.cpp]: What happens if this fails somewhere? Do the remaining results get released or do they leak?

File: src/lib/sql/sql_pipeline.cpp [hunk 6]
```diff
@@ -168,30 +163,76 @@ const std::shared_ptr<const Table>& SQLPipeline::get_result_table() {
...
-std::chrono::microseconds SQLPipeline::execution_time_microseconds() {
+std::chrono::microseconds SQLPipeline::execution_time_microseconds() const {
   Assert(_result_table != nullptr || !_query_has_output, "Cannot return execution duration without having executed.");
-  return _execution_time_sec;
+  return _execution_time_micro_sec;
+}
+
+// private constructor
+SQLPipeline::SQLPipeline(std::unique_ptr<const hsql::SQLParserResult> parsed_sql,
+                         std::shared_ptr<TransactionContext> transaction_context, bool use_mvcc)
```
Comment (mrks) [inline src/lib/sql/sql_pipeline.cpp]: see above

**Comment by lawben** [comment]
@mrzzzrm @lanice @mrks do any of you know what the problem with the build is? I can't reproduce it locally and have absolutely no idea how to solve this

**Comment by mrzzzrm** [comment]
Smells like you can't have vector of const things https://stackoverflow.com/questions/17313062/vector-of-const-objects-giving-compile-error

**Comment by mrzzzrm** [comment]
what you want is `std::vector<std::shared_ptr<const sql::SQLParserResult>>`, anyway, if anything

**Comment by mrzzzrm** [comment]
though vector<const T> might apparently be C++17 https://stackoverflow.com/a/39652132

File: src/lib/sql/sql_pipeline.cpp [hunk 7]
```diff
@@ -73,125 +110,134 @@ const std::vector<std::shared_ptr<AbstractLQPNode>>& SQLPipeline::get_optimized_
...
-    return _op_task_sets;
+const std::vector<std::vector<std::shared_ptr<OperatorTask>>>& SQLPipeline::get_tasks() {
+  if (!_tasks.empty()) {
+    return _tasks;
   }
 
-  const auto& query_plan = get_query_plan();
-  _op_task_sets.reserve(query_plan.tree_roots().size());
+  Assert(!_requires_execution || _pipeline_was_executed,
+         "Cannot generate tasks for all statements without executing the previous ones.");
```
Comment (mrks) [inline src/lib/sql/sql_pipeline.cpp]: "One ore more SQL statement is dependent on the execution of a previous one. Call [...] one by one."?

File: src/lib/sql/sql_pipeline_statement.cpp [hunk 8]
```diff
@@ -0,0 +1,229 @@
...
+    hsql::SQLParser::parse(_sql_string, _parsed_sql_statement.get());
+  } catch (const std::exception& exception) {
+    throw std::runtime_error("Error while parsing SQL query:\n  " + std::string(exception.what()));
+  }
+
+  if (!_parsed_sql_statement->isValid()) {
+    throw std::runtime_error(SQLPipelineStatement::create_parse_error_message(_sql_string, *_parsed_sql_statement));
+  }
+
+  Assert(_parsed_sql_statement->size() == 1, "SQLPipelineStatement must hold exactly one statement");
```
Comment (mrks) [inline src/lib/sql/sql_pipeline_statement.cpp]: It is helpful if we include suggested fixes in the assert message whenever it makes sense. Maybe "Use SQLPipeline when you have multiple statements."

File: src/lib/sql/sql_pipeline_statement.cpp [hunk 9]
```diff
@@ -0,0 +1,229 @@
...
+
+const std::shared_ptr<AbstractLQPNode>& SQLPipelineStatement::get_unoptimized_logical_plan() {
+  if (_unoptimized_logical_plan) {
+    return _unoptimized_logical_plan;
+  }
+
+  const auto& parsed_sql = get_parsed_sql_statement();
+  try {
+    const auto lqp_roots = SQLTranslator{_use_mvcc}.translate_parse_result(*parsed_sql);
+    DebugAssert(lqp_roots.size() == 1, "LQP translation returned an invalid number of LQP roots");
```
Comment (mrks) [inline src/lib/sql/sql_pipeline_statement.cpp]: "returned more than one LQP root for a single statement"?

File: src/lib/sql/sql_pipeline_statement.cpp [hunk 10]
```diff
@@ -0,0 +1,229 @@
...
+  return _query_plan;
+}
+
+const std::vector<std::shared_ptr<OperatorTask>>& SQLPipelineStatement::get_tasks() {
+  if (!_tasks.empty()) {
+    return _tasks;
+  }
+
+  const auto& query_plan = get_query_plan();
+  DebugAssert(query_plan->tree_roots().size() == 1, "Invalid number of roots in the physical query plan");
```
Comment (mrks) [inline src/lib/sql/sql_pipeline_statement.cpp]: see above

File: src/lib/sql/sql_pipeline_statement.hpp [hunk 11]
```diff
@@ -0,0 +1,88 @@
...
+#include "logical_query_plan/abstract_lqp_node.hpp"
+#include "sql/sql_query_plan.hpp"
+#include "storage/table.hpp"
+
+namespace opossum {
+
+/**
+ * This is the unified interface to handle SQL queries and related operations.
+ *
+ * The basic idea of the SQLPipeline is that it represents the flow from the basic SQL string to the result table with
```
Comment (mrks) [inline src/lib/sql/sql_pipeline_statement.hpp]: This comment looks out of place.

File: src/test/CMakeLists.txt [hunk 12]
```diff
@@ -105,7 +105,7 @@ set(
     utils/cuckoo_hashtable_test.cpp
     utils/numa_memory_resource_test.cpp
     gtest_main.cpp
-)
+        sql/sql_pipeline_test.cpp)
```
Comment (mrks) [inline src/test/CMakeLists.txt]: whitespaces

File: src/bin/console/console.cpp [hunk 13]
```diff
@@ -215,21 +215,36 @@ int Console::_eval_command(const CommandFunction& func, const std::string& comma
...
   try {
     _sql_pipeline->get_result_table();
   } catch (const std::exception& exception) {
     out(std::string(exception.what()) + "\n");
-    if (_sql_pipeline->transaction_context() && _sql_pipeline->transaction_context()->aborted()) {
+    const auto& failed_pipeline = _sql_pipeline->failed_pipeline_statement();
+    if (failed_pipeline->transaction_context() && failed_pipeline->transaction_context()->aborted()) {
       out("The transaction has been rolled back.\n");
+      if (_explicitly_created_transaction_context != nullptr) {
+        out("All previous statements have been committed.\n");
```
[the remark this answers is not in the document]
Comment (lawben) [reply src/bin/console/console.cpp]: Good catch, this should be `==` not `!=`.

File: src/bin/console/console.cpp [hunk 14]
```diff
@@ -313,25 +328,26 @@ int Console::exit(const std::string&) { return Console::ReturnCode::Quit; }
...
-  out("  script SCRIPTFILE            - Execute script specified by SCRIPTFILE\n");
-  out("  print TABLENAME              - Fully print the given table (including MVCC columns)\n");
-  out("  visualize [options] SQL      - Visualize a SQL query\n");
-  out("             noexec               - without executing the query\n");
-  out("             lqp                  - print the raw logical query plans\n");
-  out("             lqpopt               - print the optimized abstract syntax tree\n");
-  out("  begin                        - Manually create a new transaction (Auto-commit is active unless begin is "
+  out("  script SCRIPTFILE                - Execute script specified by SCRIPTFILE\n");
+  out("  print TABLENAME                  - Fully print the given table (including MVCC columns)\n");
+  out("  visualize [options] (noexec) SQL - Visualize a SQL query\n");
```
[the remark this answers is not in the document]
Comment (lawben) [reply src/bin/console/console.cpp]: You have 6 options:
- no option (== query plan) and noexec set
- no option (== query plan) and noexec not set
- lqp and noexec set
- lqp and noexec not set
- lqpopt and noexec set
- lqpopt and noexec not set

How would you display this? The options are the type of visualization and the noexec defines whether it should be executed or not.

File: src/lib/sql/sql_pipeline.cpp [hunk 15]
```diff
@@ -1,68 +1,105 @@
...
+      case hsql::StatementType::kStmtAlter:
+      case hsql::StatementType::kStmtRename:
+        seen_altering_statement = true;
+      default: { /* do nothing */
+      }
+    }
+
+    auto parsed_statement = std::make_shared<hsql::SQLParserResult>(statement);
+    // We know this is always true because the check above would fail otherwise
+    parsed_statement->setIsValid(true);
```
[the remark this answers is not in the document]
Comment (lawben) [reply src/lib/sql/sql_pipeline.cpp]: Because it is false by default and having a valid statement `.is_valid()` return false is contradictiing.

File: src/lib/sql/sql_pipeline.cpp [hunk 16]
```diff
@@ -1,68 +1,105 @@
...
-  if (_use_mvcc) {
-    // We want to use MVCC but didn't pass an explicit context
-    _transaction_context = TransactionManager::get().new_transaction_context();
-  } else {
-    // We don't want to use MVCC
-    _transaction_context = nullptr;
-  }
+SQLPipeline::SQLPipeline(const std::string& sql, std::shared_ptr<opossum::TransactionContext> transaction_context)
+    : SQLPipeline(sql, std::move(transaction_context), true) {
+  DebugAssert(_sql_pipeline_statements.front()->transaction_context() != nullptr,
```
[the remark this answers is not in the document]
Comment (lawben) [reply src/lib/sql/sql_pipeline.cpp]: done :)

File: src/bin/console/console.cpp (hunk 14 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/bin/console/console.cpp]: Does `lqp noexec` make sense?

File: src/lib/sql/sql_pipeline.cpp (hunk 15 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/sql/sql_pipeline.cpp]: Ah, I misread the comment. "always true" was "always" for me, i.e., it was true before and it is true after the method call.

I think this might be one of the few cases where it would be better to leave the comment out.

File: src/bin/console/console.cpp (hunk 14 above)
[the remark this answers is not in the document]
Comment (lawben) [reply src/bin/console/console.cpp]: Why shouldn't it? The whole viz stuff is mainly for debugging or general interest, so why not allow it, if is is possible.

[the remark this answers is not in the document]
Comment (mrks) [reply src/bin/console/console.cpp]: ok
