### PR TITLE
Fix some UnionNode Tests

### LINKED ISSUE #501: Improve column resolving for UnionNode
see comments in `UnionNodeTests`

### PR DESCRIPTION
**Pull request by mrzzzrm**
Fix #501

### CODE REVIEW

**Comment by TwoLaid** [comment]
Thanks! That already clears up some things. I'll review when CI is green

**Comment by mrzzzrm** [comment]
go

File: src/lib/optimizer/abstract_syntax_tree/abstract_ast_node.hpp [hunk 1]
```diff
@@ -123,6 +123,9 @@ class AbstractASTNode : public std::enable_shared_from_this<AbstractASTNode> {
       const std::shared_ptr<AbstractASTNode>& right_child = nullptr) const;
   // @}
 
+  /**
+   * @returns the names of the columns this node outputs without any alias added by this node
+   */
```
Comment (TwoLaid) [inline src/lib/optimizer/abstract_syntax_tree/abstract_ast_node.hpp]: Is this comment added for clarification or did you change the semantics of this function? Or: is this still true for all other nodes?

File: src/lib/optimizer/abstract_syntax_tree/union_node.cpp [hunk 2]
```diff
@@ -18,12 +18,19 @@ std::string UnionNode::description() const { return "[UnionNode] Mode: " + union
 
 std::string UnionNode::get_verbose_column_name(ColumnID column_id) const {
   Assert(left_child() && right_child(), "Need children to determine Column name");
+  Assert(column_id < left_child()->output_column_names().size(), "ColumnID out of range");
+  Assert(right_child()->output_column_names().size() == left_child()->output_column_names().size(),
+         "Input node mismatch");
```
Comment (TwoLaid) [inline src/lib/optimizer/abstract_syntax_tree/union_node.cpp]: this seems like an odd place for this assertion. shouldn't this be checked way earlier, right after the children have been set?

File: src/lib/optimizer/abstract_syntax_tree/union_node.cpp [hunk 3]
```diff
@@ -49,23 +56,25 @@ std::shared_ptr<TableStatistics> UnionNode::derive_statistics_from(
...
+
   if (!named_column_reference_without_local_alias) {
     return {};
-  } else {
-    const auto column_id_in_left =
-        left_child()->find_column_id_by_named_column_reference(*named_column_reference_without_local_alias);
+  }
+
+  // UnionNode can't resolve NamedColumnReference with table_name
+  if (named_column_reference_without_local_alias->table_name) {
```
Comment (TwoLaid) [inline src/lib/optimizer/abstract_syntax_tree/union_node.cpp]: Would you say that asking a `UnionNode` for a named colref with a table name is a logical error? In that case, maybe even a `DebugAssert` could be placed here.

File: src/lib/optimizer/abstract_syntax_tree/union_node.cpp [hunk 4]
```diff
@@ -49,23 +56,25 @@ std::shared_ptr<TableStatistics> UnionNode::derive_statistics_from(
...
+    return {};
+  }
+
+  const auto column_id_in_left =
+      left_child()->find_column_id_by_named_column_reference(*named_column_reference_without_local_alias);
 #if IS_DEBUG
```
Comment (TwoLaid) [inline src/lib/optimizer/abstract_syntax_tree/union_node.cpp]: I think the preferred style is `if (IS_DEBUG)`

File: src/test/optimizer/abstract_syntax_tree/union_node_test.cpp [hunk 5]
```diff
@@ -57,42 +64,45 @@ TEST_F(UnionNodeTest, MismatchingColumnNames) {
...
 }
 
-TEST_F(UnionNodeTest, DISABLED_VerboseColumnNames) {
-  /* 
-   * Currently the verbose column names of the inputs need to be *exactly* the same.
-   * That is why we need to use the same input table for left AND right input.
-   * This is probably a logical error in `UnionNode::get_verbose_column_name`.
+TEST_F(UnionNodeTest, VerboseColumnNames) {
+  /**
+   * UnionNode will only prefix column's with its own ALIAS and forget of any table names / aliases of its input tables
```
Comment (TwoLaid) [inline src/test/optimizer/abstract_syntax_tree/union_node_test.cpp]: -of

File: src/lib/optimizer/abstract_syntax_tree/abstract_ast_node.hpp (hunk 1 above)
Comment (mrzzzrm) [reply src/lib/optimizer/abstract_syntax_tree/abstract_ast_node.hpp]: just docs

File: src/lib/optimizer/abstract_syntax_tree/union_node.cpp (hunk 3 above)
Comment (mrzzzrm) [reply src/lib/optimizer/abstract_syntax_tree/union_node.cpp]: it's not a logical error, might happen, another subtree might contain the NamedColumnRef.

File: src/lib/optimizer/abstract_syntax_tree/union_node.cpp (hunk 4 above)
Comment (mrzzzrm) [reply src/lib/optimizer/abstract_syntax_tree/union_node.cpp]: oh, who made this up.... :( will change it then

Comment (mrzzzrm) [reply src/lib/optimizer/abstract_syntax_tree/union_node.cpp]: Nope, won't: #507

File: src/test/optimizer/abstract_syntax_tree/union_node_test.cpp (hunk 5 above)
Comment (mrzzzrm) [reply src/test/optimizer/abstract_syntax_tree/union_node_test.cpp]: yep

File: src/lib/optimizer/abstract_syntax_tree/union_node.cpp (hunk 2 above)
Comment (mrzzzrm) [reply src/lib/optimizer/abstract_syntax_tree/union_node.cpp]: Asserting this elsewhere loosens the contract the Assert is making. There is no guarantee (apart from the model in our head, but that's precisely what's fallible and therefore needs asserting) that children won't change after `_on_child_changed()`.
So no, I think this Assertion is perfectly fine here... We could probably debate it if it would appear in another 10 places.

File: src/lib/optimizer/abstract_syntax_tree/union_node.cpp (hunk 4 above)
Comment (TwoLaid) [reply src/lib/optimizer/abstract_syntax_tree/union_node.cpp]: Alexa, CANCEL APPROVAL!
