### PR TITLE
Make filter rules use type_cast

### LINKED ISSUE #828: boost::bad_get when executing ChunkPruningRule
Reproduce e.g. in `hyriseConsole`:
```
(debug)> generate CUSTOMER;
Generating TPCC table: "CUSTOMER" ...
(debug)> select * from CUSTOMER where C_ZIP=953411111;
Error while translating query plan:
  Error while optimizing query plan:
  boost::bad_get: failed value get using boost::get
```
This does not happen with string or float values.

Call stack:
image

### PR DESCRIPTION
**Pull request by mrzzzrm**
Fix #828

The SQLTranslator created int64_t values for literal ints in predicates, but the pruned column was int32_t leading to a bad_cast. Since we actually do support scanning a int64_t column with a int32_t and vice versa, I made the filter rules use type_cast instead of boost::get<>.

We should look into running the SQLiteTestrunner with table compressions, that would have caught this. For our current setup the ChunkPruningRule is not applied during the SQLiteTestrunner, since ChunkStatistics are only created during compression.

### CODE REVIEW

File: src/lib/optimizer/chunk_statistics/chunk_statistics.hpp [hunk 1]
```diff
@@ -15,16 +15,19 @@ namespace opossum {
...
+  }
 
   /**
    * calls can_prune on the ChunkColumnStatistics corresponding to column_id
    */
   bool can_prune(const ColumnID column_id, const AllTypeVariant& value, const PredicateCondition predicate_type) const;
 
  protected:
-  std::vector<std::shared_ptr<ChunkColumnStatistics>> _statistics;
+  std::vector<std::shared_ptr<ChunkColumnStatistics>> _chunk_column_statistics;
```
Comment (Bouncner) [inline src/lib/optimizer/chunk_statistics/chunk_statistics.hpp]: That does not really make it better, doesn't it?

Comment (mrzzzrm) [reply src/lib/optimizer/chunk_statistics/chunk_statistics.hpp]: Better than `_statistics` for sure. `_statistics` as a name sounds like an illness.

Comment (Bouncner) [reply src/lib/optimizer/chunk_statistics/chunk_statistics.hpp]: Any better ideas?

I know statistics vs. data statistics vs. aggregates can pretty much mean the same. I would not mind renaming those "statistics" to aggregates and clarify all stored "data statistics" by renaming them to some kind of "aggregates".

What's your take @mrzzzrm ? @mrks & @Bensk1 ?

Comment (mrzzzrm) [reply src/lib/optimizer/chunk_statistics/chunk_statistics.hpp]: Didn't want to spark a naming discussion, and since this fixes a blocker for #715 I reverted the naming

File: src/lib/sql/hsql_expr_translator.cpp [hunk 2]
```diff
@@ -115,7 +115,11 @@ AllParameterVariant HSQLExprTranslator::to_all_parameter_variant(
     const hsql::Expr& expr, const std::optional<std::shared_ptr<AbstractLQPNode>>& input_node) {
   switch (expr.type) {
     case hsql::kExprLiteralInt:
-      return AllTypeVariant(expr.ival);
+      if (static_cast<int32_t>(expr.ival) == expr.ival) {
+        return AllTypeVariant{static_cast<int32_t>(expr.ival)};
```
Comment (Bouncner) [inline src/lib/sql/hsql_expr_translator.cpp]: Wouldnt this lead to type errors when the sql predicate value is small but the column is a bigint/long?
