### PR TITLE
CardinalityEstimator utilizing Histograms

### LINKED ISSUE #1153: Rewrite Statistics Component
To be used for discussions around the statistics component.

### LINKED ISSUE #1310: Modifying tables breaks statistics
The example that I found this with:

```
CREATE TABLE t (i INT, l LONG, f FLOAT, d DOUBLE);
INSERT INTO t (i,l,f,d) VALUES (1,2,3,4);
UPDATE t SET i = 1, f = 1, l = i WHERE d = 4;
UPDATE t SET i = 1, f = 1, l = i + 3 WHERE d = 4;
```

A simpler example:
```
CREATE TABLE t (i INT);
INSERT INTO t (i) VALUES (1);
DELETE FROM t
SELECT * FROM t WHERE i = 1
```

Result in both cases:
```
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: /Users/markus/Projekte/Opossum/Git/src/lib/statistics/column_statistics.cpp:434 Distinct count has to be greater zero
```

### LINKED ISSUE #1513: Benchmark plan visualization takes ages
Generating plan visualizations for the JOB is a pain and takes literal hours. Could probably be done in parallel

### PR DESCRIPTION
**Pull request by mrzzzrm**
Replaces the old cardinality estimation paths via `AbstractLQPNode::derive_statistics_from` with a dedicated `CardinalityEstimator` component. This cardinality estimator works primarily with Histograms spanning entire columns (as opposed to per-segment histograms). Inner Join and Scan operations are estimated more accurately than before. Scans on string columns are estimated reasonably well for the first time, thanks to @timzimmermann. This really helps in the Join Order Benchmark, which has many local predicates on string colums.

* Removes the `EqualWidthHistogram` and `EqualHeightHistogram` (for now), as we only actively use the `EqualDistinctCountHistogram`.
* The old cardinality estimation system had specialized code paths for Outer and Semi Joins - this functionality was removed, mainly, to reduce the amount of code to port over, test and maintain. Outer Joins are now estimated just like inner Joins and Semi/Anti Joins have a selectivity of 1. We don't "need" estimations for these join types anyway, right now. 
* We currently generate 5 (for < 10'000 rows) to 100 (for >= 20'000'000 rows) Bins. These numbers are rather arbitrarily chosen. More bins mean poorer optimization runtime (esp for Joins), but potentially better optimized query plans. As our error margins are measured in factors, it's probably not worth allocating more many bins and hope for better optimization results while sacrificing Optimizer runtime.

### Benchmark results
[Join Order Benchmark](https://gist.github.com/mrzzzrm/cd45479951e44403e3843bcc44732057) improves nicely, which imo is the best argument for the usefulness of this CardinalityEstimator.
[TPC-H with prepared statements](https://gist.github.com/mrzzzrm/4033bd2217148876366a1d65ecca5f15) never hits the Query Cache and therefore profits a bit from the reduced optimization times.

Fix #1153
Fix #1513 
Fix #1310

### CODE REVIEW

**Comment by Bouncner** [comment]
image

The LIKE estimations must be phenomenally by now.

File: src/lib/statistics/generate_table_statistics.cpp [hunk 1]
```diff
@@ -76,47 +78,64 @@ void generate_cardinality_estimation_statistics(const std::shared_ptr<Table>& ta
...
-        segment_statistics->set_statistics_object(std::make_shared<NullValueRatio>(null_value_ratio));
-      } else {
-        // Failure to generate a histogram currently only stems from all-null segments.
-        // TODO(anybody) this is a slippery assumption. But the alternative would be a full segment scan...
-        segment_statistics->set_statistics_object(std::make_shared<NullValueRatio>(1.0f));
+            segment_statistics->set_statistics_object(std::make_shared<NullValueRatio>(null_value_ratio));
+          } else {
+            // Failure to generate a histogram currently only stems from all-null segments.
+            // TODO(anybody) this is a slippery assumption. But the alternative would be a full segment scan...
+            segment_statistics->set_statistics_object(std::make_shared<NullValueRatio>(1.0f));
```
Comment (Bouncner) [inline src/lib/statistics/generate_table_statistics.cpp]: Just to be sure that no one uses such information to prune predicates (or attributes as the wise database gurus often say) such as `a IS NOT NULL`: would it make sense to rather use a ratio of `0.9999f`?

Comment (mrzzzrm) [reply src/lib/statistics/generate_table_statistics.cpp]: a) Stats for CardinalityEstimation and Chunk Pruning are entirely separate atm, see TableStatistics2

b) Statistics that can be used for pruning need to be explicitly marked as such

Comment (Bouncner) [reply src/lib/statistics/generate_table_statistics.cpp]: Ok

**Comment by mrks** [comment]
> Open naming discussions

>     TableCardinalityEstimationStatistics

See comment. Drop "estimation"? Maybe even drop "cardinality"?
-> `TableStatistics`

>     VerticalStatisticsSlice
>     HorizontalStatisticsSlice

I'm always having problems understanding vertical and horizontal. Is it "vertically sliced" or a slice that spans the vertical dimension?
Also for those that contain multiple columns, are these columns disjoint? "Slice" would suggest so.
-> vertical slices represent actually just one column.

> Open architectural discussions

>     Do we want to implement the possibility of multiple horizontal slices of
>     statistics for a Table, even though presently only a single slice - for the
>     entire table - is created?

Depends on how much effort it is. When it comes to bigger tables, I can imagine that we want an LSM-like approach to stats updates
-> For now, check if we can do without it; might reintroduce for TPC-C

>     How many bins do we use by default? Currently
>     it's 5 to 100 bins depending on the row count in the table

Jeez, how should I know? Let @Bensk1 do his magic knob turning. ;)

>     CardinalityEstimator::clone_with_caches() feels dirty.

Oh yes, it is. I added an inline comment. At least in the one place that I have looked at, I did not understand (or forgot again) why we have to pass in the caches from the outside.

>     The interface of AbstractHistgram feels dirty, many functions (estimate_cardinality(),
>     estimate_cardinality_and_distinct_count(), _does_not_contains()) seem to similar
>     things, do we merge them into one big estimation function?

-> Proposal: add CachedEstimator where policies are set but everything is handled internally

>     Do we actually
>     want an AbstractStatisticsObject? Presently we do use the concrete types
>     everywhere. And it seems like you always WANT to know the actual type of a
>     statistics object before you start using it for some estimation. AND finding a
>     common interface for all statistics objects seems almost impossible.

-> Consider this more an interface, not a superclass

**Comment by Bensk1** [comment]
> > ```
> > How many bins do we use by default? Currently
> > it's 5 to 100 bins depending on the row count in the table
> > ```
> 
> Jeez, how should I know? Let @Bensk1 do his magic knob turning. ;)

There is even some magic (heuristic) in Tim's Master's thesis for that.

File: resources/test_data/sqlite_testrunner_queries.sql [hunk 2]
```diff
@@ -10,6 +10,7 @@ SELECT 22 / 5 AS col;
```
Comment (mrzzzrm) [inline resources/test_data/sqlite_testrunner_queries.sql]: (Random line)
@mrks, maybe @Bensk1 

I just removed the `TableStatistics::approx_invalid_row_count` property, so now ValidateNodes will always be estimated with a selectivity of "1".

Reasons are: The property was only manipulated in `Delete`, there was no equivalent in `Insert` so this wouldn't have worked for OLTP anyway. I want us to think of a proper approach for updating statistics once TPC-C support is there, not carry this pseudo-excuse property around. 
Also handing `approx_invalid_row_count` around in the `CardinalityEstimator` is cumbersome. Needs to be computed for the result of Predicates and Joins.
Adding it, or something similar, back in will be easy enough once we have a basis of discussion (cf TPC-C), but I am kind of fed up with keeping in speculative concepts that try to account for a future scenario that we have never thought about properly.

What do you think? Can this property go for now?

File: src/lib/optimizer/strategy/join_ordering_rule.cpp [hunk 3]
```diff
@@ -46,28 +49,51 @@ std::shared_ptr<AbstractLQPNode> JoinOrderingRule::_perform_join_ordering_recurs
...
+  /**
+   * Setup Cardinality and Cost Estimation caches
+   *
+   * Since Join Ordering Algorithms will issue many cost/cardinality estimation requests, caching is crucial to
+   * performance. For caching, we exploit that all Join Ordering Algorithms are based on the JoinGraph and employ the
+   * JoinGraphStatisticsCache. Additionally, since all currently used JOAs build the LQP from the bottom up (i.e.
+   * statistics once associated with a node do not change), we can employ node-pointer-based cost and cardinality
+   * caches.
+   */
+  const auto cost_estimation_cache = std::make_shared<CostEstimationCache>();
```
Comment (mrzzzrm) [inline src/lib/optimizer/strategy/join_ordering_rule.cpp]: @mrks what do you think of something like this:

```c++

  const auto caching_cost_estimator = cost_estimator->new_instance();
  caching_cost_estimator->enable_bottom_up_cache_guarantee();
  caching_cost_estimator->cardinality_estimator->enable_join_graph_cache_guarantee(*join_graph);
```

File: scripts/compare_benchmarks.py [hunk 4]
```diff
@@ -11,40 +11,43 @@
...
+    if diff >= 0:
+        return colored('+' + "{0:.0%}".format(diff), 'green')
+    else:
+        return colored("{0:.0%}".format(diff), 'red')
+
 
 def calculate_and_format_p_value(old, new):
-	p_value = ttest_ind(array('d', old['iteration_durations']), array('d', new['iteration_durations']))[1]
-	is_significant = p_value < p_value_significance_threshold
+    return ""
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply scripts/compare_benchmarks.py]: Will remove this from this PR once #1510 is finally merged

File: scripts/compare_benchmarks.py [hunk 5]
```diff
@@ -11,40 +11,43 @@
...
-if(len(sys.argv) != 3):
-	print("Usage: " + sys.argv[0] + " benchmark1.json benchmark2.json")
-	exit()
+if len(sys.argv) != 3:
+    print("Usage: " + sys.argv[0] + " benchmark1.json benchmark2.json")
+    exit()
 
 with open(sys.argv[1]) as old_file:
-    old_data = json.load(old_file)
+        old_data = json.load(old_file)
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply scripts/compare_benchmarks.py]: Will remove this from this PR once #1510 is finally merged

File: src/lib/CMakeLists.txt [hunk 6]
```diff
@@ -349,37 +350,70 @@ set(
...
+    statistics/cardinality_estimator.hpp
+    statistics/cardinality_estimate.cpp
+    statistics/cardinality_estimate.hpp
+    statistics/cardinality_estimation/cardinality_estimation_join.cpp
+    statistics/cardinality_estimation/cardinality_estimation_join.hpp
+    statistics/cardinality_estimation/cardinality_estimation_scan.cpp
+    statistics/cardinality_estimation/cardinality_estimation_scan.hpp
+    statistics/horizontal_statistics_slice.cpp
+    statistics/horizontal_statistics_slice.hpp
+    statistics/statistics_objects/chunk_statistics.cpp
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/CMakeLists.txt]: The folder now contains all "statistics objects", e.g. histograms, cqfs, pruning stats etc. Is that okay?

File: src/benchmarklib/benchmark_table_encoder.cpp [hunk 7]
```diff
@@ -155,6 +156,8 @@ bool BenchmarkTableEncoder::encode(const std::string& table_name, const std::sha
     });
   }
 
+  generate_chunk_pruning_statistics(table);
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/benchmarklib/benchmark_table_encoder.cpp]: "Other than the file," <-- don't understand what that means, please clarify
"this has "chunk" in it? On purpose?" <-- yes, since those stats created here have the single purpose of being used for Chunk Pruning.

File: src/lib/cost_model/abstract_cost_estimator.cpp [hunk 8]
```diff
@@ -26,11 +30,48 @@ Cost AbstractCostEstimator::estimate_plan_cost(const std::shared_ptr<AbstractLQP
...
+    // Look up this subplan in cache, if a cache is present
+    if (cost_estimation_cache) {
+      const auto cost_estimation_cache_iter = cost_estimation_cache->find(current_node);
+      if (cost_estimation_cache_iter != cost_estimation_cache->end()) {
+        auto subplan_already_visited = false;
+
+        auto subplan_nodes = std::vector<std::shared_ptr<AbstractLQPNode>>{};
+
+        // Check whether the cache entry can be used: This is only the case if the entire subplan has not yet been
+        // visited. If it already has been visited, and we'd use the cache entry anyway, costs would get counted twice
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/cost_model/abstract_cost_estimator.cpp]: Changed to 

```
    /**
     * Look up this subplan in cache, if a cache is present.
     * Needs to pay special attention to diamond shapes in the LQP to avoid costing nodes multiple times.
     */
```

File: src/lib/cost_model/abstract_cost_estimator.cpp [hunk 9]
```diff
@@ -26,11 +30,48 @@ Cost AbstractCostEstimator::estimate_plan_cost(const std::shared_ptr<AbstractLQP
...
+        for (const auto& current_node_input : {current_node->left_input(), current_node->right_input()}) {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/cost_model/abstract_cost_estimator.cpp]: Nope, If we ever had it, I probably removed it in one of my attempts to boil down the interface of AbstractLQPNode

File: src/lib/cost_model/cost_estimation_cache.hpp [hunk 10]
```diff
@@ -0,0 +1,17 @@
...
+#include <unordered_map>
+
+#include "cost.hpp"
+
+namespace opossum {
+
+class AbstractLQPNode;
+
+/**
+ * For now, our means of cost caching are limited to a <node-ptr> -> <cost> mapping
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/cost_model/cost_estimation_cache.hpp]: No idea. Removed the comment

File: src/lib/cost_model/cost_model_logical.hpp [hunk 11]
```diff
@@ -10,8 +10,14 @@ class AbstractExpression;
  * Cost model for logical complexity, i.e., approximate number of tuple accesses
  */
 class CostModelLogical : public AbstractCostEstimator {
- protected:
-  Cost _estimate_node_cost(const std::shared_ptr<AbstractLQPNode>& node) const override;
+ public:
+  using AbstractCostEstimator::AbstractCostEstimator;
+
+  std::shared_ptr<AbstractCostEstimator> clone_with_caches(
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/cost_model/cost_model_logical.hpp]: overrides aren't usually doc'ed, declaration in base class has this doc:

```
  /**
   * @return a new instance of this estimator with a new instance of the wrapped cardinality estimator, both with mint
   *         caches. Used so that caching guarantees can be enabled on the returned estimator.
   */
```

File: src/lib/optimizer/join_ordering/dp_ccp.hpp [hunk 12]
```diff
@@ -17,16 +21,18 @@ namespace opossum {
...
-   * @param join_graph      A JoinGraph for a part of an LQP with further subplans as vertices. DpCcp is only applied
-   *                        to this particular JoinGraph and doesn't modify the subplans in the vertices.
-   * @return                An LQP consisting of
-   *                         * the operations from the JoinGraph in an optimal order
-   *                         * the subplans from the vertices below them
+   * @param join_graph                      A JoinGraph for a part of an LQP with further subplans as vertices. DpCcp is
+   *                                        only applied to this particular JoinGraph and doesn't modify the subplans in
+   *                                        the vertices.
+   * @param cost_estimation_cache           Optional, cache for the CostEstimator
+   * @param cardinality_estimation_cache    Optional, cache for the CardinalityEstimator
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/join_ordering/dp_ccp.hpp]: Adjusted.

File: src/lib/optimizer/optimizer.cpp [hunk 13]
```diff
@@ -6,8 +6,12 @@
 #include "cost_model/cost_model_logical.hpp"
 #include "expression/expression_utils.hpp"
 #include "expression/lqp_subquery_expression.hpp"
+#include "logical_query_plan/join_node.hpp"
 #include "logical_query_plan/logical_plan_root_node.hpp"
 #include "logical_query_plan/lqp_utils.hpp"
+#include "logical_query_plan/predicate_node.hpp"
+#include "optimizer/strategy/predicate_placement_rule.hpp"
+#include "statistics/cardinality_estimator.hpp"
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/optimizer.cpp]: Removed some of those includes, assuming the "?" was short for "why is this here?"

File: src/lib/optimizer/optimizer.hpp [hunk 14]
```diff
@@ -19,12 +24,16 @@ class Optimizer final {
  public:
   static std::shared_ptr<Optimizer> create_default_optimizer();
 
+  explicit Optimizer(const std::shared_ptr<AbstractCostEstimator>& cost_estimator =
+                         std::make_shared<CostModelLogical>(std::make_shared<CardinalityEstimator>()));
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/optimizer.hpp]: settled on "cost estimator"

File: src/lib/logical_query_plan/mock_node.cpp [hunk 15]
```diff
@@ -57,6 +57,15 @@ std::shared_ptr<TableStatistics> MockNode::derive_statistics_from(
 
 void MockNode::set_statistics(const std::shared_ptr<TableStatistics>& statistics) { _table_statistics = statistics; }
 
+const std::shared_ptr<TableCardinalityEstimationStatistics>& MockNode::cardinality_estimation_statistics() const {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/mock_node.cpp]: renamed to just TableStatistics... again.

File: src/lib/optimizer/strategy/chunk_pruning_rule.cpp [hunk 16]
```diff
@@ -78,9 +81,8 @@ void ChunkPruningRule::apply_to(const std::shared_ptr<AbstractLQPNode>& node) co
   }
 }
 
-std::set<ChunkID> ChunkPruningRule::_compute_exclude_list(
-    const std::vector<std::shared_ptr<ChunkStatistics>>& statistics,
-    const std::shared_ptr<PredicateNode>& predicate_node) const {
+std::set<ChunkID> ChunkPruningRule::_compute_exclude_list(const Table& table,
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/strategy/chunk_pruning_rule.cpp]: rather not meddle with code not part of this PR. Or do you insist?

File: src/lib/optimizer/strategy/chunk_pruning_rule.cpp [hunk 17]
```diff
@@ -18,10 +23,11 @@ namespace opossum {
 
 std::string ChunkPruningRule::name() const { return "Chunk Pruning Rule"; }
 
-void ChunkPruningRule::apply_to(const std::shared_ptr<AbstractLQPNode>& node) const {
+void ChunkPruningRule::apply_to(const std::shared_ptr<AbstractLQPNode>& node,
+                                const std::shared_ptr<AbstractCostEstimator>& cost_estimator) const {
   // we only want to follow chains of predicates
   if (node->type != LQPNodeType::Predicate) {
-    _apply_to_inputs(node);
+    _apply_to_inputs(node, cost_estimator);
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/strategy/chunk_pruning_rule.cpp]: There is `AbstractRule::cost_estimator` now, which is set to the Optimizer's cost_estimator in `Optimizer::add_rule()` **after** the rule is constructed. It is this stuff that I never wanted to do, feels so unclean.

File: src/lib/optimizer/strategy/chunk_pruning_rule.cpp [hunk 18]
```diff
@@ -91,19 +93,62 @@ std::set<ChunkID> ChunkPruningRule::_compute_exclude_list(
...
+                                  const std::optional<AllTypeVariant>& variant_value2) const {
+  auto any_filter_prunes = false;
+
+  resolve_data_type(base_vertical_statistics_slice.data_type, [&](const auto data_type_t) {
+    using ColumnDataType = typename decltype(data_type_t)::type;
+
+    const auto& vertical_statistics_slice =
+        static_cast<const VerticalStatisticsSlice<ColumnDataType>&>(base_vertical_statistics_slice);
+
+    if constexpr (std::is_arithmetic_v<ColumnDataType>) {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/strategy/chunk_pruning_rule.cpp]: rather not meddle with code not part of this PR. Or do you insist?

File: src/lib/optimizer/strategy/chunk_pruning_rule.cpp [hunk 19]
```diff
@@ -91,19 +93,62 @@ std::set<ChunkID> ChunkPruningRule::_compute_exclude_list(
...
+      if (vertical_statistics_slice.range_filter) {
+        const auto estimate =
+            vertical_statistics_slice.range_filter->estimate_cardinality(predicate_type, variant_value, variant_value2);
+        if (estimate.type == EstimateType::MatchesNone) any_filter_prunes = true;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/strategy/chunk_pruning_rule.cpp]: now using `*Filter::does_not_contain` (again)

File: src/lib/optimizer/strategy/index_scan_rule.cpp [hunk 20]
```diff
@@ -41,18 +44,19 @@ void IndexScanRule::apply_to(const std::shared_ptr<AbstractLQPNode>& node) const
 
       const auto index_infos = table->get_indexes();
       for (const auto& index_info : index_infos) {
-        if (_is_index_scan_applicable(index_info, predicate_node)) {
+        if (_is_index_scan_applicable(index_info, predicate_node, cost_estimator)) {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/strategy/index_scan_rule.cpp]: rather not meddle with code not part of this PR. Or do you insist?

File: src/lib/statistics/cardinality_estimation/cardinality_estimation_join.cpp [hunk 21]
```diff
@@ -0,0 +1,285 @@
...
+        auto join_column_histogram = std::shared_ptr<AbstractHistogram<ColumnDataType>>{};
+
+        auto left_histogram = left_input_vertical_slices->histogram;
+        auto right_histogram = right_input_vertical_slices->histogram;
+
+        if (left_histogram && right_histogram) {
+          join_column_histogram = histograms_inner_equi_join(*left_histogram, *right_histogram);
+
+          if (!join_column_histogram) {
+            // Not matches in this Chunk-pair
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimation/cardinality_estimation_join.cpp]: code removed

File: src/lib/statistics/cardinality_estimation/cardinality_estimation_join.cpp [hunk 22]
```diff
@@ -0,0 +1,285 @@
...
+    PerformanceWarning("CardinalityEstimation of join is performed on non-compact ChunkStatisticsSet.");
+  }
+
+  const auto left_data_type = left_input_table_statistics.column_data_types[left_column_id];
+  const auto right_data_type = right_input_table_statistics.column_data_types[right_column_id];
+
+  // TODO(anybody) - Implement join estimation for differing column data types
+  //               - Implement join estimation for String columns
+  if (left_data_type != right_data_type || left_data_type == DataType::String) {
+    return cross_join(left_input_table_statistics, right_input_table_statistics);
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimation/cardinality_estimation_join.cpp]: `estimate_cross_join` now. 

> Also, does this really estimate m*n?
yes

File: src/lib/statistics/cardinality_estimation/cardinality_estimation_join.cpp [hunk 23]
```diff
@@ -0,0 +1,285 @@
...
+
+  const auto& left_horizontal_slices = left_input_table_statistics.horizontal_slices;
+  const auto& right_horizontal_slices = right_input_table_statistics.horizontal_slices;
+
+  if (left_horizontal_slices.empty() || right_horizontal_slices.empty()) {
+    // No slices on either side? Return an empty table statistics object
+    return output_table_statistics;
+  }
+
+  // TODO(anybody) For many Chunks on both sides this nested loop further down will be inefficient.
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimation/cardinality_estimation_join.cpp]: Slice concept is removed for now.

File: src/lib/statistics/cardinality_estimation/cardinality_estimation_join.cpp [hunk 24]
```diff
@@ -0,0 +1,285 @@
...
+  }
+
+  return builder.build();
+}
+
+std::shared_ptr<TableCardinalityEstimationStatistics> inner_equi_join(
+    const ColumnID left_column_id, const ColumnID right_column_id,
+    const TableCardinalityEstimationStatistics& left_input_table_statistics,
+    const TableCardinalityEstimationStatistics& right_input_table_statistics) {
+  // Concatenate left and right column data types for the output TableCardinalityEstimationStatistics
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimation/cardinality_estimation_join.cpp]: code replaced by different concept

File: src/lib/statistics/cardinality_estimation/cardinality_estimation_join.cpp [hunk 25]
```diff
@@ -0,0 +1,285 @@
...
+   * E.g., if left_histogram has a single bin [1, 10] and right histogram has a single bin [5, 20] then
+   * unified_left_histogram == {[1, 4], [5, 10]}
+   * unified_right_histogram == {[5, 10], [11, 20]}
+   * The estimation is performed on overlapping bins only, e.g., only the two bins [5, 10] will produce matches.
+   */
+
+  auto unified_left_histogram = left_histogram.split_at_bin_bounds(right_histogram.bin_bounds());
+  auto unified_right_histogram = right_histogram.split_at_bin_bounds(left_histogram.bin_bounds());
+
+  Assert(unified_left_histogram && unified_right_histogram, "Creating unified histograms should not fail");
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimation/cardinality_estimation_join.cpp]: will only fail for strings, but we make sure we never call it with string histograms. assert removed

File: src/lib/statistics/cardinality_estimation/cardinality_estimation_join.cpp [hunk 26]
```diff
@@ -0,0 +1,285 @@
...
+
+  return {match_count, right_distinct_count};
+}
+
+template <typename T>
+std::shared_ptr<GenericHistogram<T>> histograms_inner_equi_join(const AbstractHistogram<T>& left_histogram,
+                                                                const AbstractHistogram<T>& right_histogram) {
+  /**
+   * left_histogram and right_histogram are turned into "unified" histograms by `split_at_bin_bounds`, meaning that
+   * their bins are split until their bin boundaries match.
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimation/cardinality_estimation_join.cpp]: Now: "bins are split so that their bin boundaries match"

File: src/lib/statistics/cardinality_estimation/cardinality_estimation_join.cpp [hunk 27]
```diff
@@ -0,0 +1,285 @@
...
+  }
+
+  // Early out to avoid division by zero below
+  if (left_distinct_count == 0 || right_distinct_count == 0) {
+    return {0.0f, 0.0f};
+  }
+
+  // Perform a basic principle-of-inclusion join estimation
+
+  // Each distinct value on the right side occurs `right_density` times.
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimation/cardinality_estimation_join.cpp]: "Each distinct value on the right side is assumed to occur `right_density` times."

File: src/lib/statistics/cardinality.hpp [hunk 28]
```diff
@@ -0,0 +1,7 @@
+#pragma once
+
+namespace opossum {
+
+using Cardinality = float;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality.hpp]: strongtypdefs were a pain for reasons I forgot, but I moved the normal typedefs of Cardinality, Cost and Selectivity to types.hpp

File: src/lib/statistics/base_vertical_statististics_slice.hpp [hunk 29]
```diff
@@ -0,0 +1,49 @@
...
+namespace opossum {
+
+class AbstractStatisticsObject;
+enum class PredicateCondition;
+
+/**
+ * Base class for VerticalStatisticsSlice<T>.
+ * Statistically represents a range within a Column. Might cover any number of rows or Chunks.
+ *
+ * Contains any number of AbstractStatisticsObjects (Histograms, Filters, etc.), see VerticalStatisticsSlice<T>.
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/base_vertical_statististics_slice.hpp]: Changed to "Contains slots for AbstractStatisticsObjects"

File: src/lib/statistics/base_vertical_statististics_slice.hpp [hunk 30]
```diff
@@ -0,0 +1,49 @@
...
+#include "selectivity.hpp"
+
+namespace opossum {
+
+class AbstractStatisticsObject;
+enum class PredicateCondition;
+
+/**
+ * Base class for VerticalStatisticsSlice<T>.
+ * Statistically represents a range within a Column. Might cover any number of rows or Chunks.
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/base_vertical_statististics_slice.hpp]: Now, with horizontal slicing abandoned, the comment reads "Statistically represents a Column (i.e. covers all Segments with the same ColumnID over all Chunks of a Table)."

File: src/lib/statistics/abstract_statistics_object.hpp [hunk 31]
```diff
@@ -0,0 +1,41 @@
...
+ */
+class AbstractStatisticsObject {
+ public:
+  explicit AbstractStatisticsObject(const DataType data_type);
+  virtual ~AbstractStatisticsObject() = default;
+
+  /**
+   * @return A statistics object that represents the data after the predicate has been applied.
+   */
+  virtual std::shared_ptr<AbstractStatisticsObject> sliced(
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/abstract_statistics_object.hpp]: because the object itself is not manipulated, which "slice" implies, but instead the function returns a "sliced"-off portion of the statistics object.

File: src/lib/statistics/abstract_cardinality_estimator.hpp [hunk 32]
```diff
@@ -0,0 +1,29 @@
...
+ * Interface for algorithms determining the output cardinality/statistics of an LQP during optimization.
+ */
+class AbstractCardinalityEstimator {
+ public:
+  virtual ~AbstractCardinalityEstimator() = default;
+
+  virtual std::shared_ptr<AbstractCardinalityEstimator> clone_with_cache(
+      const std::shared_ptr<CardinalityEstimationCache>& cardinality_estimation_cache) const = 0;
+
+  virtual Cardinality estimate_cardinality(const std::shared_ptr<AbstractLQPNode>& lqp) const = 0;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/abstract_cardinality_estimator.hpp]: Not sure, we estimate a lot of things in hyrise (cardinality, output statistics, memory usage), "estimate_cardinality" seems to make things a bit more clear.

File: src/lib/optimizer/strategy/index_scan_rule.cpp [hunk 33]
```diff
@@ -69,11 +73,11 @@ bool IndexScanRule::_is_index_scan_applicable(const IndexInfo& index_info,
 
   if (index_info.column_ids[0] != operator_predicate.column_id) return false;
 
-  const auto row_count_table = predicate_node->left_input()->derive_statistics_from(nullptr, nullptr)->row_count();
+  const auto row_count_table =
+      cost_estimator->cardinality_estimator->estimate_cardinality(predicate_node->left_input());
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/strategy/index_scan_rule.cpp]: The CostEstimator needs the CardinalityEstimator anyway, so it has a reference to it. makes no sense, imo, to store a separate reference to a CardinalityEstimator.

File: src/lib/statistics/cardinality_estimation/cardinality_estimation_join.hpp [hunk 34]
```diff
@@ -0,0 +1,57 @@
...
+/**
+ * Estimate the inner-equi join of two table statistics
+ */
+std::shared_ptr<TableCardinalityEstimationStatistics> inner_equi_join(
+    const ColumnID left_column_id, const ColumnID right_column_id,
+    const TableCardinalityEstimationStatistics& left_input_table_statistics,
+    const TableCardinalityEstimationStatistics& right_input_table_statistics);
+
+/**
+ * Estimate the cross join of two table statistics
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimation/cardinality_estimation_join.hpp]: actually removed the comment. Function is only exposed for tests. Function itself is documented internally, imo that's sufficient

File: src/lib/statistics/cardinality_estimation/cardinality_estimation_join.hpp [hunk 35]
```diff
@@ -0,0 +1,57 @@
...
+std::pair<HistogramCountType, HistogramCountType> bins_inner_equi_join(const float left_height,
+                                                                       const float left_distinct_count,
+                                                                       const float right_height,
+                                                                       const float right_distinct_count);
+
+/**
+ * Estimate the inner-equi join of two histograms
+ */
+template <typename T>
+std::shared_ptr<GenericHistogram<T>> histograms_inner_equi_join(const AbstractHistogram<T>& histogram_left,
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimation/cardinality_estimation_join.hpp]: All functions from cardinality_estimation_join.hpp and cardinality_estimation_scan.hpp moved to cardinality_estimator.hpp

File: src/lib/statistics/cardinality_estimation/cardinality_estimation_join.hpp [hunk 36]
```diff
@@ -0,0 +1,57 @@
+#pragma once
+
+#include "statistics/histograms/abstract_histogram.hpp"
+#include "types.hpp"
+
+/**
+ * The functions declared here are called by the CardinalityEstimator. They are implemented as free functions in their
+ * own translation unit to facilitate testing of the actual cardinality estimation algorithms and for separation of
+ * concerns between scan- and join- estimation algorithms.
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimation/cardinality_estimation_join.hpp]: they are now public static members of CardinalityEstimator.

File: src/lib/statistics/cardinality_estimation/cardinality_estimation_scan.cpp [hunk 37]
```diff
@@ -0,0 +1,341 @@
...
+namespace {
+
+using namespace opossum;  // NOLINT
+
+template <typename T>
+std::optional<float> estimate_null_value_ratio_of_segment(
+    const std::shared_ptr<HorizontalStatisticsSlice>& chunk_statistics,
+    const std::shared_ptr<VerticalStatisticsSlice<T>>& vertical_slice) {
+  if (vertical_slice->null_value_ratio) {
+    return vertical_slice->null_value_ratio->null_value_ratio;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimation/cardinality_estimation_scan.cpp]: Now reads as `column_statistics.null_value_ratio->ratio` - a bit cumbersome, but we have to treat a null value ratio the same as we treat an histogram if we want it to be passed along nicely when operators are estimated.

File: src/lib/statistics/cardinality_estimation/cardinality_estimation_scan.cpp [hunk 38]
```diff
@@ -0,0 +1,341 @@
...
+  }
+
+  if (vertical_slice->histogram) {
+    if (chunk_statistics->row_count != 0) {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimation/cardinality_estimation_scan.cpp]: yes

File: src/lib/optimizer/optimizer.cpp [hunk 39]
```diff
@@ -112,7 +114,12 @@ std::shared_ptr<Optimizer> Optimizer::create_default_optimizer() {
   return optimizer;
 }
 
-void Optimizer::add_rule(std::unique_ptr<AbstractRule> rule) { _rules.emplace_back(std::move(rule)); }
+Optimizer::Optimizer(const std::shared_ptr<AbstractCostEstimator>& cost_estimator) : _cost_estimator(cost_estimator) {}
+
+void Optimizer::add_rule(std::unique_ptr<AbstractRule> rule) {
```
Comment (mrzzzrm) [inline src/lib/optimizer/optimizer.cpp]: @mrks alternative would be:

```
template<typename RuleType>
void Optimizer::add_rule() {
  rules.emplace_back(std::make_shared<RuleType>(_cost_estimator);
}
```

**Comment by mrzzzrm** [comment]
@mrks

From my side, this PR is feature-complete. All further changes would be based on your feedback. https://github.com/hyrise/hyrise/issues/1153#issuecomment-464515672 documents the follow ups I want to do after this PR. This will be easier to do once this PR is in the master.

**Comment by Bouncner** [comment]
Is the PR description up to date and complete?

**Comment by mrzzzrm** [comment]
> Is the PR description up to date and complete?
Up-to-date, yes. Complete, debatable, could probably write at least a BA about this... let me know if you need anything specific.

File: resources/test_data/sqlite_testrunner_queries.sql (hunk 2 above)
Comment (mrks) [reply resources/test_data/sqlite_testrunner_queries.sql]: > there was no equivalent in Insert

The only reason insert would have to update this is if a transaction with an insert failed. With optimistic concurrency control, we can be optimistic that this does not happen.

I expect a validate that happens always at the end to be bad for performance with the TPC-C. My goal is to clear up the TPC-C code enough over the weekend so that we can test this PR with the TPC-C, too.

File: src/lib/cost_estimation/abstract_cost_estimator.hpp [hunk 40]
```diff
@@ -0,0 +1,67 @@
...
+  /**
+   * @return the estimated cost of a single node. The `cost_estimation_cache` will not be used
+   */
+  virtual Cost estimate_node_cost(const std::shared_ptr<AbstractLQPNode>& node) const = 0;
+
+  /**
+   * @return a new instance of this estimator with a new instance of the wrapped cardinality estimator, both with mint
+   *         caches. Used so that caching guarantees can be enabled on the returned estimator.
+   */
+  virtual std::shared_ptr<AbstractCostEstimator> new_instance() const = 0;
```
Comment (mrks) [inline src/lib/cost_estimation/abstract_cost_estimator.hpp]: Isn't this `clone`?

File: src/lib/operators/operator_join_predicate.hpp [hunk 41]
```diff
@@ -20,6 +21,7 @@ struct OperatorJoinPredicate {
   static std::optional<OperatorJoinPredicate> from_expression(const AbstractExpression& predicate,
                                                               const AbstractLQPNode& left_input,
                                                               const AbstractLQPNode& right_input);
+  static std::optional<OperatorJoinPredicate> from_join_node(const JoinNode& join_node);
```
Comment (mrks) [inline src/lib/operators/operator_join_predicate.hpp]: ?

File: src/lib/optimizer/join_ordering/abstract_join_ordering_algorithm.cpp [hunk 42]
```diff
@@ -102,7 +102,7 @@ std::shared_ptr<AbstractLQPNode> AbstractJoinOrderingAlgorithm::_add_join_to_pla
     lqp = JoinNode::make(JoinMode::Cross, left_lqp, right_lqp);
   }
 
-  // non operator join predicates have to be processed as scans.
+  // Post-JoinNode predicates are processed as scans.
```
Comment (mrks) [inline src/lib/optimizer/join_ordering/abstract_join_ordering_algorithm.cpp]: Isn't "scan" a PQP concept?

File: src/lib/optimizer/optimizer.cpp (hunk 39 above)
Comment (mrks) [reply src/lib/optimizer/optimizer.cpp]: That will be ugly when rules have parameters. Still, I don't like how an `add_x` method touches `x`. `use_rule` is not too much better, but at least it doesn't have that implicit guarantee that the rule won't be modified.

File: src/lib/optimizer/strategy/chunk_pruning_rule.cpp [hunk 43]
```diff
@@ -78,9 +79,8 @@ void ChunkPruningRule::apply_to(const std::shared_ptr<AbstractLQPNode>& node) co
   }
 }
 
-std::set<ChunkID> ChunkPruningRule::_compute_exclude_list(
-    const std::vector<std::shared_ptr<ChunkStatistics>>& statistics, const AbstractExpression& predicate,
-    const StoredTableNode& stored_table_node) const {
+std::set<ChunkID> ChunkPruningRule::_compute_exclude_list(const Table& table, const AbstractExpression& predicate,
```
Comment (mrks) [inline src/lib/optimizer/strategy/chunk_pruning_rule.cpp]: Keeping interface small: Retrieve the table again instead of passing it in?

File: src/lib/optimizer/strategy/chunk_pruning_rule.cpp [hunk 44]
```diff
@@ -90,21 +90,60 @@ std::set<ChunkID> ChunkPruningRule::_compute_exclude_list(
     if (!is_variant(operator_predicate.value)) {
       return std::set<ChunkID>();
     }
+
     const auto& value = boost::get<AllTypeVariant>(operator_predicate.value);
+
     std::optional<AllTypeVariant> value2;
-    if (static_cast<bool>(operator_predicate.value2)) value2 = boost::get<AllTypeVariant>(*operator_predicate.value2);
+    if (static_cast<bool>(operator_predicate.value2)) {
```
Comment (mrks) [inline src/lib/optimizer/strategy/chunk_pruning_rule.cpp]: Do we need this cast?

File: src/lib/optimizer/strategy/chunk_pruning_rule.cpp [hunk 45]
```diff
@@ -90,21 +90,60 @@ std::set<ChunkID> ChunkPruningRule::_compute_exclude_list(
...
+
+    for (auto chunk_id = ChunkID{0}; chunk_id < table.chunk_count(); ++chunk_id) {
+      const auto pruning_statistics = table.get_chunk(chunk_id)->pruning_statistics();
+      if (!pruning_statistics) {
+        continue;
+      }
+
+      const auto segment_statistics = (*pruning_statistics)[operator_predicate.column_id];
+      if (_can_prune(*segment_statistics, condition, value, value2)) {
+        result.insert(ChunkID(chunk_id));
```
Comment (mrks) [inline src/lib/optimizer/strategy/chunk_pruning_rule.cpp]: `chunk_id` already is a `ChunkID`

File: src/lib/optimizer/strategy/chunk_pruning_rule.cpp [hunk 46]
```diff
@@ -90,21 +90,60 @@ std::set<ChunkID> ChunkPruningRule::_compute_exclude_list(
...
       }
     }
   }
   return result;
 }
 
+bool ChunkPruningRule::_can_prune(const BaseColumnStatistics& base_column_statistics,
+                                  const PredicateCondition predicate_condition, const AllTypeVariant& variant_value,
+                                  const std::optional<AllTypeVariant>& variant_value2) const {
+  auto any_filter_prunes = false;
```
Comment (mrks) [inline src/lib/optimizer/strategy/chunk_pruning_rule.cpp]: This is just the return value in a way where it can be written by the lambda, correct? If so, maybe make this clear by calling it `can_prune`, same as the method?

File: src/lib/optimizer/strategy/chunk_pruning_rule.cpp [hunk 47]
```diff
@@ -90,21 +90,60 @@ std::set<ChunkID> ChunkPruningRule::_compute_exclude_list(
...
+  resolve_data_type(base_column_statistics.data_type, [&](const auto data_type_t) {
+    using ColumnDataType = typename decltype(data_type_t)::type;
+
+    const auto& column_statistics = static_cast<const ColumnStatistics<ColumnDataType>&>(base_column_statistics);
+
+    // Range filters are only available for arithmetic (non-string) types.
+    if constexpr (std::is_arithmetic_v<ColumnDataType>) {
+      if (column_statistics.range_filter) {
+        if (column_statistics.range_filter->does_not_contain(predicate_condition, variant_value, variant_value2)) {
+          any_filter_prunes = true;
```
Comment (mrks) [inline src/lib/optimizer/strategy/chunk_pruning_rule.cpp]: return?

File: src/lib/optimizer/strategy/predicate_reordering_rule.cpp [hunk 48]
```diff
@@ -40,27 +46,35 @@ void PredicateReorderingRule::apply_to(const std::shared_ptr<AbstractLQPNode>& n
...
 
-  const auto sort_predicate = [&](auto& left, auto& right) {
-    return left->derive_statistics_from(input)->row_count() > right->derive_statistics_from(input)->row_count();
-  };
-
-  if (std::is_sorted(predicates.begin(), predicates.end(), sort_predicate)) {
-    return;
+  // Setup cardinality estimation cache so that the statistics of `input` (which might be a big plan) do not need to
+  // be determined repeatedly.
+  // We do NOT guarantee bottom-up construction, but we can guarantee that `input` is a "vertex" below which we will not
```
Comment (mrks) [inline src/lib/optimizer/strategy/predicate_reordering_rule.cpp]: I believe we don't use "vertex" outside of the join ordering. "node"?

File: src/lib/optimizer/strategy/predicate_reordering_rule.cpp [hunk 49]
```diff
@@ -40,27 +46,35 @@ void PredicateReorderingRule::apply_to(const std::shared_ptr<AbstractLQPNode>& n
...
+  // change the plan. Thus we construct a dummy-JoinGraph and allow the CardinalityEstimator to use it.
```
Comment (mrks) [inline src/lib/optimizer/strategy/predicate_reordering_rule.cpp]: This sounds like a hack that makes the cache do something that it would usually just do for join graphs. I do not yet understand why this is necessary and what this accomplishes.

File: src/lib/optimizer/strategy/predicate_reordering_rule.cpp [hunk 50]
```diff
@@ -40,27 +46,35 @@ void PredicateReorderingRule::apply_to(const std::shared_ptr<AbstractLQPNode>& n
...
+  const auto caching_cardinality_estimator = cost_estimator->cardinality_estimator->new_instance();
+  caching_cardinality_estimator->guarantee_join_graph(JoinGraph{{input}, {}});
+
+  // Estimate the output cardinalities of each individual predicate on top of the input LQP
```
Comment (mrks) [inline src/lib/optimizer/strategy/predicate_reordering_rule.cpp]: ..., i.e., predicates are estimated independently.

File: src/lib/sql/sql_pipeline_statement.hpp [hunk 51]
```diff
@@ -25,14 +25,15 @@ struct SQLPipelineStatementMetrics {
  * The SQLPipelineStatement represents the flow from a *single* SQL statement to the result table with all intermediate
  * steps. Don't construct this class directly, use the SQLPipelineBuilder instead
  *
- * Note:
+ * NOTE:
  *  Calling get_result_table() will result in the following "call stack"
  *  get_result_table() -> get_tasks() -> get_pyhsical_plan_plan() -> get_optimized_logical_plan() ->
```
Comment (mrks) [inline src/lib/sql/sql_pipeline_statement.hpp]: typo

File: src/lib/statistics/abstract_cardinality_estimator.cpp [hunk 52]
```diff
@@ -0,0 +1,14 @@
+#include "abstract_cardinality_estimator.hpp"
+
+namespace opossum {
+
+void AbstractCardinalityEstimator::guarantee_join_graph(const JoinGraph& join_graph) {
+  cardinality_estimation_cache.join_graph_statistics_cache.emplace(
+      JoinGraphStatisticsCache::from_join_graph(join_graph));
+}
+
+void AbstractCardinalityEstimator::guarantee_bottom_up_construction() {
```
Comment (mrks) [inline src/lib/statistics/abstract_cardinality_estimator.cpp]: Is there any way to identify when these guarantees are violated?

File: src/lib/statistics/abstract_cardinality_estimator.hpp (hunk 32 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/statistics/abstract_cardinality_estimator.hpp]: But this is the cardinality estimator. Calls to this will always look like `cardinality_estimator->estimate_cardinality(...)`.

File: src/lib/statistics/abstract_cardinality_estimator.hpp [hunk 53]
```diff
@@ -0,0 +1,48 @@
...
+
+/**
+ * Base class for algorithms determining the output cardinality/statistics of an LQP during optimization.
+ */
+class AbstractCardinalityEstimator {
+ public:
+  virtual ~AbstractCardinalityEstimator() = default;
+
+  /**
+   * @return a new instance of this estimator with mint caches. Used so that caching guarantees can be enabled on the
```
Comment (mrks) [inline src/lib/statistics/abstract_cardinality_estimator.hpp]: Not sure how commonly understood "mint" is here. "Empty" would serve the same purpose.

File: src/lib/statistics/abstract_cardinality_estimator.hpp [hunk 54]
```diff
@@ -0,0 +1,48 @@
...
+   * returned estimator.
+   */
+  virtual std::shared_ptr<AbstractCardinalityEstimator> new_instance() const = 0;
```
Comment (mrks) [inline src/lib/statistics/abstract_cardinality_estimator.hpp]: As above: clone?

File: src/lib/statistics/abstract_cardinality_estimator.hpp [hunk 55]
```diff
@@ -0,0 +1,48 @@
...
+
+  /**
+   * @return the estimated output row count of @param lqp
+   */
+  virtual Cardinality estimate_cardinality(const std::shared_ptr<AbstractLQPNode>& lqp) const = 0;
+
+  /**
+   * Promises to the CardinalityEstimator that it will only be used to estimate Cardinalities of plans that consists
```
Comment (mrks) [inline src/lib/statistics/abstract_cardinality_estimator.hpp]: *consist

File: src/lib/statistics/abstract_cardinality_estimator.hpp [hunk 56]
```diff
@@ -0,0 +1,48 @@
...
+   * of the Vertices and Predicates in @param JoinGraph. This enables using the JoinGraphStatisticsCache during
+   * Cardinality estimation
```
Comment (mrks) [inline src/lib/statistics/abstract_cardinality_estimator.hpp]: This is not really something about the interface, but I'd like to see another sentence explaining how this makes our live easier.

File: src/lib/statistics/cardinality_estimate.hpp [hunk 57]
```diff
@@ -0,0 +1,20 @@
+#pragma once
+
+#include "types.hpp"
+
+namespace opossum {
+
+enum class EstimateType { MatchesNone, MatchesExactly, MatchesApproximately, MatchesAll };
+
+struct CardinalityEstimate {
```
Comment (mrks) [inline src/lib/statistics/cardinality_estimate.hpp]: Class doc?

File: src/lib/statistics/cardinality_estimation_cache.hpp [hunk 58]
```diff
@@ -0,0 +1,24 @@
...
+
+#include "join_graph_statistics_cache.hpp"
+
+namespace opossum {
+
+class CardinalityEstimationCache {
+ public:
+  /**
+   * Join/Predicate Ordering rules can enable this cache by calling `join_graph_statistics_cache.emplace()`. The docs of
+   * JoinGraphStatisticsCache explain what this cache does.
```
Comment (mrks) [inline src/lib/statistics/cardinality_estimation_cache.hpp]: This comment does not tell me anything.

File: src/lib/statistics/cardinality_estimation_cache.hpp [hunk 59]
```diff
@@ -0,0 +1,24 @@
...
+   */
+  std::optional<JoinGraphStatisticsCache> join_graph_statistics_cache;
+
+  /**
+   * Optimization Rules that !!!do not manipulate subplans after they have build them!!!! can enable
```
Comment (mrks) [inline src/lib/statistics/cardinality_estimation_cache.hpp]: If it's really that important, use caps. Computers should burst into flames when people press `!` twice. ;)

File: src/lib/statistics/cardinality_estimator.cpp [hunk 60]
```diff
@@ -0,0 +1,858 @@
...
+
+template <typename T>
+std::optional<float> estimate_null_ratio_of_column(const TableStatistics& table_statistics,
+                                                   const ColumnStatistics<T>& column_statistics) {
+  // If the column has an explicit null value ratio associated with it, we can just use that
+  if (column_statistics.null_value_ratio) {
+    return column_statistics.null_value_ratio->ratio;
+  }
+
+  // Otherwise derive the NVR from the total count of an histogram (which excludes NULLs) and the TableStatistics
```
Comment (mrks) [inline src/lib/statistics/cardinality_estimator.cpp]: Do we need this abbreviation? Especially because the function does not use the "V"?
Also: a**n** histogram

**Comment by mrzzzrm** [comment]
Btw, @mrks, you said your review only covers half of this PR, which is why I haven't looked at it yet. Did I understand that correctly?

**Comment by mrks** [comment]
Correct. I have some more pending, but am not done with it yet.

File: resources/test_data/sqlite_testrunner_queries.sql (hunk 2 above)
Comment (Bouncner) [reply resources/test_data/sqlite_testrunner_queries.sql]: Any news here? Before TPC-C I would have thought the fixed 1.0 selectivity is sufficient (at least now that we no longer estimate some string predicates with 1.0 as well) as well. 

Do you already have numbers @mrks ?

File: src/lib/optimizer/join_ordering/abstract_join_ordering_algorithm.cpp (hunk 42 above)
Comment (Bouncner) [reply src/lib/optimizer/join_ordering/abstract_join_ordering_algorithm.cpp]: > Isn't "scan" a PQP concept?

+1 and could you elaborate this a little bit? I don't think outsiders understand what the alternative is that you decided against.

File: src/lib/statistics/cardinality_estimator.cpp [hunk 61]
```diff
@@ -0,0 +1,858 @@
...
+  }
+}
+
+std::shared_ptr<TableStatistics> CardinalityEstimator::estimate_join_node(
+    const JoinNode& join_node, const std::shared_ptr<TableStatistics>& left_input_table_statistics,
+    const std::shared_ptr<TableStatistics>& right_input_table_statistics) {
+  if (join_node.join_mode == JoinMode::Cross) {
+    return estimate_cross_join(*left_input_table_statistics, *right_input_table_statistics);
+  } else {
+    // TODO(anybody) Join cardinality estimation is consciously only performed for the primary join predicate. #
```
Comment (mrks) [inline src/lib/statistics/cardinality_estimator.cpp]: #?

File: src/lib/statistics/cardinality_estimator.cpp [hunk 62]
```diff
@@ -0,0 +1,858 @@
...
+            case PredicateCondition::NotIn:
+            case PredicateCondition::Like:
+            case PredicateCondition::NotLike:
+              return estimate_cross_join(*left_input_table_statistics, *right_input_table_statistics);
+
+            case PredicateCondition::IsNull:
+            case PredicateCondition::IsNotNull:
+              Fail("IS NULL is an invalid join predicate");
+          }
+          Fail("Unreachable, but GCC doesn't realize...");
```
Comment (mrks) [inline src/lib/statistics/cardinality_estimator.cpp]: We have a standard text for that. Something like "GCC thinks...". Makes it easier to remove all of these once gcc fixes it.

File: src/lib/statistics/cardinality_estimator.cpp [hunk 63]
```diff
@@ -0,0 +1,858 @@
...
+
+        case JoinMode::Cross:
+          // Should have been forwarded to cardinality_estimation_cross_join
```
Comment (mrks) [inline src/lib/statistics/cardinality_estimator.cpp]: do you mean `estimate_cross_join`?

File: src/lib/statistics/cardinality_estimator.cpp [hunk 64]
```diff
@@ -0,0 +1,858 @@
...
+
+        // All that remains of the column we scanned on are NULL values
+        const auto column_statistics = std::make_shared<ColumnStatistics<ColumnDataType>>();
+        column_statistics->null_value_ratio = std::make_shared<NullValueRatioStatistics>(1.0f);
+        output_column_statistics[left_column_id] = column_statistics;
+      } else {
+        // If have no null-value ratio available, assume a selectivity of 1, for both IS NULL and IS NOT NULL
+        selectivity = 1.0f;
+      }
+    } else if (predicate.predicate_condition == PredicateCondition::IsNotNull) {
```
Comment (mrks) [inline src/lib/statistics/cardinality_estimator.cpp]: this looks like a lot of duplication for something that is essentially `1.0 - x`.

File: src/lib/statistics/cardinality_estimator.cpp [hunk 65]
```diff
@@ -0,0 +1,858 @@
...
+          case PredicateCondition::LessThanEquals:
+          case PredicateCondition::GreaterThan:
+          case PredicateCondition::GreaterThanEquals:
+          case PredicateCondition::Between:
+          case PredicateCondition::In:
+          case PredicateCondition::NotIn:
+          case PredicateCondition::Like:
+          case PredicateCondition::NotLike:
+            // Lacking better options, assume a "magic" selectivity for >, >=, <, <=, ....
+            selectivity = 0.5f;
```
Comment (mrks) [inline src/lib/statistics/cardinality_estimator.cpp]: Sometimes the "dunno selectivity" is 1, here it is .5. Make it a constant?

File: src/lib/statistics/cardinality_estimator.cpp [hunk 66]
```diff
@@ -0,0 +1,858 @@
...
+      }
+    }
+  });
+
+  // Entire chunk matches; simply return the input
+  if (selectivity == 1) {
+    return input_table_statistics;
+  }
+
+  // If predicate has a of 0 < selectivity < 1, scale the other columns' ColumnStatistics that we didn't write
```
Comment (mrks) [inline src/lib/statistics/cardinality_estimator.cpp]: a...?

File: src/lib/statistics/cardinality_estimator.cpp [hunk 67]
```diff
@@ -0,0 +1,858 @@
...
+    auto join_column_histogram = std::shared_ptr<AbstractHistogram<ColumnDataType>>{};
+
+    auto left_histogram = left_input_column_statistics->histogram;
+    auto right_histogram = right_input_column_statistics->histogram;
+
+    if (left_histogram && right_histogram) {
+      join_column_histogram = estimate_inner_equi_join_with_histograms(*left_histogram, *right_histogram);
+      cardinality = join_column_histogram->total_count();
+    } else {
+      // TODO(anybody) If there aren't histograms on both sides, use some other algorithm/statistics to estimate the
```
Comment (mrks) [inline src/lib/statistics/cardinality_estimator.cpp]: What did we do before? Why can't we continue to do that?

File: src/lib/statistics/cardinality_estimator.cpp [hunk 68]
```diff
@@ -0,0 +1,858 @@
...
+    if (right_min < left_min) {
+      ++right_idx;
+      continue;
+    }
+
+    DebugAssert(unified_left_histogram->bin_maximum(left_idx) == unified_right_histogram->bin_maximum(right_idx),
+                "Histogram bin boundaries do not match");
+
+    // Overlapping bins found, estimate the join for these bins' range
+    const auto [height, distinct_count] = estimate_inner_equi_join_of_bins(  // NOLINT
```
Comment (mrks) [inline src/lib/statistics/cardinality_estimator.cpp]: This looks a lot like column-vs-column. Deduplicate and pass "bin function thingy" as a template parameter?

File: src/benchmarklib/benchmark_table_encoder.cpp [hunk 69]
```diff
@@ -157,6 +158,8 @@ bool BenchmarkTableEncoder::encode(const std::string& table_name, const std::sha
 
   for (auto& thread : threads) thread.join();
 
+  generate_chunk_pruning_statistics(table);
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/benchmarklib/benchmark_table_encoder.cpp]: As `Table` such a central class I want new devs to be able to understand it quickly and not bloat it up with functions that are only remotely related. 
I think keeping "Table" (as a storage container) and the associated statistics as separate as possible is a good strategy for keeping the arch understandable.

File: src/lib/cost_estimation/abstract_cost_estimator.hpp [hunk 70]
```diff
@@ -0,0 +1,67 @@
...
+
+  /**
+   * Promises to the CostEstimator (and underlying CardinalityEstimator) that it will only be used to estimate bottom-up
+   * constructed plans. That is, the Cost/Cardinality of a node, once constructed, never changes.
+   * This enables the usage of a <lqp-ptr> -> <cost> cache.
+   */
+  void guarantee_bottom_up_construction();
+
+  std::shared_ptr<AbstractCardinalityEstimator> cardinality_estimator;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/cost_estimation/abstract_cost_estimator.hpp]: const AbstractCardinalityEstimator is not possible since we need to set the guarantees on it (`guarantee_bottom_up_construction`, `guarantee_join_graph`). const std::shared_ptr doesn't give us anything, imo, no harm is done if the cardinality_estimator is replaced after the AbstractCostEstimator construction, but if you like it, I changed it.

[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/cost_estimation/abstract_cost_estimator.hpp]: const AbstractCardinalityEstimator is not possible since we need to set guarantees on it (guarantee_bottom_up_construction()). const std:shared_ptr I added.

File: src/lib/optimizer/strategy/predicate_reordering_rule.cpp (hunk 49 above)
Comment (mrzzzrm) [reply src/lib/optimizer/strategy/predicate_reordering_rule.cpp]: Assume you have a big, big subplan with root node x and on top of the suplan you want to order 3 predicates (a, b, c). The PredicateReorderingRule considers the cardinalities of x->a, x->b and x->c and chooses the order of a, b, c based on those cardinalities. Now that's three cardinality estimations where the entirety of x needs to be estimated because how is the estimator to know that you changed a to b, but everything below that is constant?

I could think of no way more practical than saying: "x and everything below it is constant" than doing the same thing the JoinOrderingRule does: Marking x as a "vertex".

File: src/lib/statistics/abstract_cardinality_estimator.hpp (hunk 53 above)
Comment (mrzzzrm) [reply src/lib/statistics/abstract_cardinality_estimator.hpp]: changed to "empty"

File: src/lib/statistics/abstract_cardinality_estimator.hpp (hunk 56 above)
Comment (mrzzzrm) [reply src/lib/statistics/abstract_cardinality_estimator.hpp]: Added "// For increased cardinality estimation performance: ..."

File: src/lib/statistics/cardinality_estimate.hpp (hunk 57 above)
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimate.hpp]: Better yet, removed the entire thing

File: src/lib/statistics/cardinality_estimation_cache.hpp (hunk 58 above)
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimation_cache.hpp]: Now, that's an unspecific change request. ... 

Anyway, I removed the comments here as they are essentially duplicates of the doc of `AbstractCardinalityEstimator::guarantee_join_graph()/guarantee_bottom_up_construction()` - to which the doc now simply points.

File: src/lib/statistics/cardinality_estimator.cpp [hunk 71]
```diff
@@ -0,0 +1,858 @@
...
+  const auto estimated_statistics = estimate_statistics(lqp);
+  return estimated_statistics->row_count;
+}
+
+std::shared_ptr<TableStatistics> CardinalityEstimator::estimate_statistics(
+    const std::shared_ptr<AbstractLQPNode>& lqp) const {
+  /**
+   * 1. Try a cache lookup for requested LQP
+   */
+  auto bitmask = std::optional<JoinGraphStatisticsCache::Bitmask>{};
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: Renamed "bitmask" to "join_graph_bitmask" and added

```c++
   * The `join_graph_bitmask` is kept so that if cache lookup fails, a new cache entry with this bitmask as a key can
   * be created at the end of this function.
```

File: src/lib/statistics/cardinality_estimator.cpp [hunk 72]
```diff
@@ -0,0 +1,858 @@
...
+  if (cardinality_estimation_cache.join_graph_statistics_cache) {
+    bitmask = cardinality_estimation_cache.join_graph_statistics_cache->bitmask(lqp);
+    if (bitmask) {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: It's exactly the same as not having `cached_statistics`. Maybe the "bitmask"->"join_graph_bitmask" renaming helps here as well. Also I added

```c++
else {
      // The LQP does not represent (a subgraph of) of a JoinGraph and therefore we cannot use the
      // cardinality_estimation_cache.join_graph_statistics_cache
    }
```

File: src/lib/statistics/cardinality_estimator.cpp [hunk 73]
```diff
@@ -0,0 +1,858 @@
...
+      const auto cached_statistics =
+          cardinality_estimation_cache.join_graph_statistics_cache->get(*bitmask, lqp->column_expressions());
+      if (cached_statistics) {
+        return cached_statistics;
+      }
+    }
+  }
+
+  if (cardinality_estimation_cache.statistics_by_lqp) {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: Added 
```c++

   * Lookup in `join_graph_statistics_cache` is expected to have a higher hit-rate (since every bitmask represents
   * multiple LQPs) than `statistics_by_lqp`. Thus lookup in `join_graph_statistics_cache` is performed first.
```

File: src/lib/statistics/cardinality_estimator.cpp [hunk 74]
```diff
@@ -0,0 +1,858 @@
...
+  }
+
+  return output_table_statistics;
+}
+
+std::shared_ptr<TableStatistics> CardinalityEstimator::estimate_alias_node(
+    const AliasNode& alias_node, const std::shared_ptr<TableStatistics>& input_table_statistics) {
+  auto column_statistics = std::vector<std::shared_ptr<BaseColumnStatistics>>{alias_node.column_expressions().size()};
+
+  for (size_t expression_idx{0}; expression_idx < alias_node.column_expressions().size(); ++expression_idx) {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: Alias does indeed shuffle and remove, it doesn't add.

For `SELECT b AS x, a AS y FROM table_with_column_a_b` you'd only need an Alias on top of the GetTable, not a Projection, Alias and GetTable.

File: src/lib/statistics/cardinality_estimator.cpp (hunk 73 above)
[the remark this answers is not in the document]
Comment (Bouncner) [reply src/lib/statistics/cardinality_estimator.cpp]: “hit rate”

File: src/lib/statistics/cardinality_estimator.cpp (hunk 61 above)
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: #1560, now

File: src/lib/statistics/cardinality_estimator.cpp (hunk 64 above)
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: merged those branches into one

File: src/lib/statistics/cardinality_estimator.cpp (hunk 73 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: yep

File: src/lib/statistics/cardinality_estimator.cpp (hunk 66 above)
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: Changed to the much simpler
```

  // Scale the other columns' ColumnStatistics (those that we didn't write to above) with the selectivity
```

File: src/lib/statistics/cardinality_estimator.cpp (hunk 67 above)
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: Before we probably just crashed/failed if there were no statistics available for an operation? There is nothing to "continue" doing, hence.
Atm there will be histograms for all tables and all operations so this TODO is mainly to highlight the place where other cardinality-estimating statistics can be hooked in.

File: src/lib/statistics/cardinality_estimator.cpp (hunk 68 above)
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: Nope, imo not worth it at all. You wanna be able to play around with what column-vs-column does without worrying to break inner equi join estimation. At least I want to.

File: src/lib/statistics/cardinality_estimator.cpp (hunk 65 above)
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: But if sometimes a selectivity of 0.5f just is a better guess and sometimes a 1 is, what value would that constant have? Or one constant for each magic number? I don't think that would improve it in this case.

File: src/lib/statistics/cardinality_estimator.cpp [hunk 75]
```diff
@@ -0,0 +1,858 @@
...
+  }
+
+  if (cardinality_estimation_cache.statistics_by_lqp) {
+    cardinality_estimation_cache.statistics_by_lqp->emplace(lqp, output_table_statistics);
+  }
+
+  return output_table_statistics;
+}
+
+std::shared_ptr<TableStatistics> CardinalityEstimator::estimate_alias_node(
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: Added a in-function doc comment for each `estimate_*_node()` function.

**Comment by mrzzzrm** [comment]
I think I have resolved or at least responded to all comments from the last two rounds.

File: src/benchmarklib/benchmark_table_encoder.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/benchmarklib/benchmark_table_encoder.cpp]: I believe the function name mismatche(s/d) the file name

File: src/lib/statistics/cardinality_estimator.cpp (hunk 65 above)
Comment (mrks) [reply src/lib/statistics/cardinality_estimator.cpp]: If they were deliberately chosen, maybe add a one-line comment on how we ended up with this number?

File: src/lib/optimizer/strategy/predicate_reordering_rule.cpp (hunk 49 above)
Comment (mrks) [reply src/lib/optimizer/strategy/predicate_reordering_rule.cpp]: I think I'm missing a comment here that explains how using a JoinGraph changes things.

File: src/lib/statistics/cardinality_estimator.cpp (hunk 71 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/statistics/cardinality_estimator.cpp]: I think I'm still missing some information about the bit mask. The only thing I found is this:

```
 * The key of the cache is a bitmask (with each bit representing a predicate or a vertex node).
```

Most importantly, I do not understand the meaning of a 1 or a 0.

[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/statistics/cardinality_estimator.cpp]: Also: Can multiple subplans result in the same bitmask and how are they stored in the cache?

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 76]
```diff
@@ -0,0 +1,1035 @@
...
+    return false;
+  }
+
+  switch (predicate_condition) {
+    case PredicateCondition::Like: {
+      if (!LikeMatcher::contains_wildcard(*value)) {
+        return _does_not_contain(PredicateCondition::Equals, *value);
+      }
+
+      // If the pattern starts with a MatchAll, we can not prune it.
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: A list of patterns that are (not) handled would be a great start

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 77]
```diff
@@ -0,0 +1,1035 @@
...
+       *
+       * Example:
+       * bins: [a, b], [d, e]
+       * predicate: col LIKE 'c%'
+       *
+       * With the same argument we can also prune predicates in the form of 'c%foo',
+       * where foo can be any pattern itself.
+       * We only have to consider the pattern up to the first AnyChars wildcard.
+       */
+      const auto match_all_index = value->find('%');
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: I don't see `_` handled anywhere here. Is it tested?

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 78]
```diff
@@ -0,0 +1,1035 @@
...
+
+template <typename T>
+bool AbstractHistogram<T>::_does_not_contain(const PredicateCondition predicate_condition,
+                                             const AllTypeVariant& variant_value,
+                                             const std::optional<AllTypeVariant>& variant_value2) const {
+  return _general_does_not_contain(predicate_condition, variant_value, variant_value2);
+}
+
+template <>
+bool AbstractHistogram<pmr_string>::_does_not_contain(const PredicateCondition predicate_condition,
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: Where are these methods tested?

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 79]
```diff
@@ -0,0 +1,1035 @@
...
+        // of substrings. In that case we cannot prune, because otherwise the previous check would already return true.
+        if (search_prefix == search_prefix_next_value) {
+          return false;
+        }
+
+        if (_does_not_contain(PredicateCondition::LessThan, search_prefix_next_value)) {
+          return true;
+        }
+
+        const auto search_prefix_bin = _bin_for_value(search_prefix);
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: By now you have checked if there is no value greater than our prefix and no value smaller than the next value. I thought you'd be done by now. Please briefly explain what happens next.

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 80]
```diff
@@ -0,0 +1,1035 @@
...
+    const PredicateCondition predicate_condition, const AllTypeVariant& variant_value,
+    const std::optional<AllTypeVariant>& variant_value2) const {
+  auto value = static_variant_cast<T>(variant_value);
+  if (!value) {
+    return {static_cast<Cardinality>(total_count()), static_cast<float>(total_distinct_count())};
+  }
+
+  if constexpr (std::is_same_v<
+                    T,
+                    pmr_string>) {  // NOLINT clang-tidy is crazy and sees a "potentially unintended semicolon" here...
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: format

Comment (mrks) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: Is this even still the case with the new clang version?

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 81]
```diff
@@ -0,0 +1,1035 @@
...
+
+      if (bin_distinct_count == 0) {
+        return {Cardinality{0.0f}, 0.0f};
+      } else {
+        const auto cardinality = Cardinality{bin_height(bin_id) / bin_distinct_count};
+
+        if (bin_distinct_count == 1) {
+          return {cardinality, 1.0f};
+        } else {
+          return {cardinality, std::min(bin_distinct_count, HistogramCountType{1.0f})};
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: min? When would we have `bin_distinct_count < 1`?

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 82]
```diff
@@ -0,0 +1,1035 @@
...
+  switch (predicate_condition) {
+    case PredicateCondition::Like: {
+      if (!LikeMatcher::contains_wildcard(*value)) {
+        return estimate_cardinality(PredicateCondition::Equals, variant_value);
+      }
+
+      // We don't deal with this for now because it is not worth the effort.
+      // TODO(anyone): think about good way to handle SingleChar wildcard in patterns.
+      const auto single_char_count = std::count(value->cbegin(), value->cend(), '_');
+      if (single_char_count > 0u) {
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: Why not find?

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 83]
```diff
@@ -0,0 +1,1035 @@
...
+        return static_cast<Cardinality>(total_count());
+      }
+
+      const auto any_chars_count = std::count(value->cbegin(), value->cend(), '%');
+      DebugAssert(any_chars_count > 0u,
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: find?

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 84]
```diff
@@ -0,0 +1,1035 @@
...
+                  "contains_wildcard() should not return true if there is neither a '%' nor a '_' in the string.");
+
+      // Match everything.
+      if (*value == "%") {
+        return static_cast<Cardinality>(total_count());
+      }
+
+      if (value->front() != '%') {
+        /**
+         * We know now we have some sort of prefix search, because there is at least one AnyChars wildcard,
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: We now know

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 85]
```diff
@@ -0,0 +1,1035 @@
...
+         * and it is not at the start of the pattern.
+         *
+         * We differentiate two cases:
+         *  1. Simple prefix searches, e.g., 'foo%', where there is exactly one AnyChars wildcard in the pattern,
+         *  and it is at the end of the pattern.
+         *  2. All others, e.g., 'foo%bar' or 'foo%bar%'.
+         *
+         *  The way we handle these cases is we only estimate simple prefix patterns and assume uniform distribution
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: is *that* we?

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 86]
```diff
@@ -0,0 +1,1035 @@
...
+std::shared_ptr<AbstractStatisticsObject> AbstractHistogram<T>::sliced(
+    const PredicateCondition predicate_condition, const AllTypeVariant& variant_value,
+    const std::optional<AllTypeVariant>& variant_value2) const {
+  if (_does_not_contain(predicate_condition, variant_value, variant_value2)) {
+    return nullptr;
+  }
+
+  const auto value = static_variant_cast<T>(variant_value);
+  if (!value) {
+    return clone();
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: doc?

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 87]
```diff
@@ -0,0 +1,1035 @@
...
+
+      builder.add_copied_bins(*this, BinID{0}, value_bin_id);
+
+      // Do not create empty bin, if `value` is the only value in the bin
+      if (minimum != maximum) {
+        // A bin [50, 60] sliced with `!= 60` becomes [50, 59]
+        // TODO(anybody) Implement bin bounds trimming for strings
+        if constexpr (!std::is_same_v<
+                          pmr_string,
+                          T>) {  // NOLINT clang-tidy is crazy and sees a "potentially unintended semicolon" here...
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: format

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 88]
```diff
@@ -0,0 +1,1035 @@
...
+      builder.add_copied_bins(*this, value_bin_id + 1, bin_count());
+
+      return builder.build();
+    }
+
+    case PredicateCondition::LessThanEquals:
+      return sliced(PredicateCondition::LessThan, _domain.next_value(*value));
+
+    case PredicateCondition::LessThan: {
+      auto last_bin_id = _bin_for_value(*value);
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: This could be mistaken for the last bin of the histogram. `last_included_bin_id`?

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 89]
```diff
@@ -0,0 +1,1035 @@
...
+      builder.add_copied_bins(*this, BinID{0}, last_bin_id);
+      builder.add_sliced_bin(*this, last_bin_id, bin_minimum(last_bin_id), last_bin_maximum);
+
+      return builder.build();
+    }
+
+    case PredicateCondition::GreaterThan:
+      return sliced(PredicateCondition::GreaterThanEquals, _domain.next_value(*value));
+
+    case PredicateCondition::GreaterThanEquals: {
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: Why is this less complex than LessThan?

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 90]
```diff
@@ -0,0 +1,1035 @@
...
+  if constexpr (std::is_same_v<
+                    T,
+                    pmr_string>) {  // NOLINT clang-tidy is crazy and sees a "potentially unintended semicolon" here...
+    Fail("Cannot split_at_bin_bounds() on string histogram");
+  }
+
+  /**
+   * Create vector with pairs for each split.
+   * For a lower bin edge e, the new histogram will have to be split at previous_value(e) and e.
+   * For an upper bin edge e, the new histogram will have to be split at e and next_value(e).
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: I didn't understand this part

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 91]
```diff
@@ -0,0 +1,1035 @@
...
+   */
+  const auto current_bin_count = bin_count();
+
+  std::unordered_set<std::pair<T, T>, boost::hash<std::pair<T, T>>> split_set;
+
+  for (auto bin_id = BinID{0}; bin_id < current_bin_count; bin_id++) {
+    const auto bin_min = bin_minimum(bin_id);
+    const auto bin_max = bin_maximum(bin_id);
+    if constexpr (std::is_arithmetic_v<
+                      T>) {  // NOLINT clang-tidy is crazy and sees a "potentially unintended semicolon" here...
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: format

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 92]
```diff
@@ -0,0 +1,1035 @@
...
+      split_set.insert(std::make_pair(bin_max, _domain.next_value(bin_max)));
+    } else {
+      // TODO(tim): turn into compile-time error
+      Fail("Not supported for strings.");
+    }
+  }
+
+  for (const auto& edge_pair : additional_bin_edges) {
+    if constexpr (std::is_arithmetic_v<
+                      T>) {  // NOLINT clang-tidy is crazy and sees a "potentially unintended semicolon" here...
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: format

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 93]
```diff
@@ -0,0 +1,1035 @@
...
+      // TODO(tim): turn into compile-time error
+      Fail("Not supported for strings.");
+    }
+  }
+
+  /**
+   * Split pairs into single values.
+   * These are the new bin edges, and we have to sort them.
+   */
+  std::vector<T> all_edges(split_set.size() * 2);
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: I didn't understand why we add this to a map first and then to a vector

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 94]
```diff
@@ -0,0 +1,1035 @@
...
+   * Remove the first and last value.
+   * These are the values introduced in the first step for the first and last split.
+   * The lower edge of bin 0 basically added the upper edge of bin -1,
+   * and the upper edge of the last bin basically added the lower edge of the bin after the last bin.
+   * Both values are obviously not needed.
+   */
+  all_edges.erase(all_edges.begin());
+  all_edges.pop_back();
+
+  // We do not resize the vectors because we might not need all the slots because bins can be empty.
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: Rephrase?

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 95]
```diff
@@ -0,0 +1,1035 @@
...
+    bin_edges[bin_id] = std::make_pair(bin_minimum(bin_id), bin_maximum(bin_id));
+  }
+
+  return bin_edges;
+}
+
+template <typename T>
+void AbstractHistogram<T>::_assert_bin_validity() {
+  for (BinID bin_id{0}; bin_id < bin_count(); ++bin_id) {
+    Assert(bin_minimum(bin_id) <= bin_maximum(bin_id), "Cannot have overlapping bins.");
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: You don't check for overlapping here, but for the maximum of a bin being bigger than its own (!) minimum

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 96]
```diff
@@ -0,0 +1,1035 @@
...
+
+    if (bin_id < bin_count() - 1) {
+      Assert(bin_maximum(bin_id) < bin_minimum(bin_id + 1), "Bins must be sorted and cannot overlap.");
+    }
+
+    if constexpr (
+        std::is_same_v<
+            T, pmr_string>) {  // NOLINT clang-tidy is crazy and sees a "potentially unintended semicolon" here...
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/abstract_histogram.cpp]: format

File: src/lib/statistics/statistics_objects/histogram_domain.cpp [hunk 97]
```diff
@@ -0,0 +1,133 @@
...
+    return string_value + min_char;
+  }
+
+  // Special case: return `value` if it is the last supported one.
+  if (string_value == pmr_string(prefix_length, max_char)) {
+    return string_value;
+  }
+
+  // Otherwise, work on the substring trimmed to `prefix_length` characters.
+  const auto cleaned_value = string_value.substr(0, prefix_length);
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/histogram_domain.cpp]: cleaned of?

File: src/lib/statistics/statistics_objects/min_max_filter.hpp [hunk 98]
```diff
@@ -0,0 +1,50 @@
...
+/**
+ *  Filter that stores a segment's minimum and maximum value
+*/
+template <typename T>
+class MinMaxFilter : public AbstractStatisticsObject {
+ public:
+  explicit MinMaxFilter(T min, T max);
+  ~MinMaxFilter() override = default;
+
+  // cppcoreguidelines-special-member-functions
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/min_max_filter.hpp]: ?

File: src/lib/statistics/statistics_objects/min_max_filter.hpp [hunk 99]
```diff
@@ -0,0 +1,50 @@
...
+#include "all_type_variant.hpp"
+#include "types.hpp"
+
+namespace opossum {
+
+/**
+ *  Filter that stores a segment's minimum and maximum value
+*/
+template <typename T>
+class MinMaxFilter : public AbstractStatisticsObject {
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/min_max_filter.hpp]: Naming and/or documentation, more for @Bouncner: What makes this a "filter"?

File: src/lib/statistics/statistics_objects/null_value_ratio_statistics.hpp [hunk 100]
```diff
@@ -0,0 +1,21 @@
+#pragma once
+
+#include "abstract_statistics_object.hpp"
+
+namespace opossum {
+
+// A single float value as an AbstractStatisticsObject, to keep architectures consistent....
+class NullValueRatioStatistics : public AbstractStatisticsObject {
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/null_value_ratio_statistics.hpp]: I believe we changed "null value ratio" to "null ratio" somewhere above. I find it more concise, how about you?

File: src/lib/statistics/statistics_objects/min_max_filter.hpp (hunk 99 above)
Comment (mrks) [inline src/lib/statistics/statistics_objects/min_max_filter.hpp]: This could use some more documentation. What is it good for, why don't we keep the number of entries (because then it would be a one-bucket histogram?)?

File: src/lib/statistics/statistics_objects/range_filter.hpp [hunk 101]
```diff
@@ -0,0 +1,66 @@
...
+
+namespace opossum {
+
+//! default number of maximum range count
+static constexpr uint32_t MAX_RANGES_COUNT = 10;
+
+/**
+ * Filter that stores a certain number of value ranges. Each range represents a spread
+ * of values that is contained within the bounds.
+ * Example: [1, 2, 4, 7] might be represented as [1, 7]
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/range_filter.hpp]: This example would also serve for the MinMaxFilter, wouldn't it? Can we find a better one?

File: src/lib/statistics/statistics_objects/range_filter.hpp [hunk 102]
```diff
@@ -0,0 +1,66 @@
...
+*/
+template <typename T>
+class RangeFilter : public AbstractStatisticsObject {
+ public:
+  static_assert(std::is_arithmetic_v<T>, "RangeFilter should not be instantiated for strings.");
+
+  explicit RangeFilter(std::vector<std::pair<T, T>> ranges);
+  ~RangeFilter() override = default;
+
+  // cppcoreguidelines-special-member-functions
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/range_filter.hpp]: ?

File: src/lib/statistics/statistics_objects/range_filter.cpp [hunk 103]
```diff
@@ -0,0 +1,288 @@
...
+
+template <typename T>
+RangeFilter<T>::RangeFilter(std::vector<std::pair<T, T>> ranges)
+    : AbstractStatisticsObject(data_type_from_type<T>()), ranges(std::move(ranges)) {}
+
+template <typename T>
+Cardinality RangeFilter<T>::estimate_cardinality(const PredicateCondition predicate_condition,
+                                                 const AllTypeVariant& variant_value,
+                                                 const std::optional<AllTypeVariant>& variant_value2) const {
+  return 0;
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/range_filter.cpp]: When would someone reasonably ask the RangeFilter for a cardinality estimation? Simply returning a random number does not feel right.

File: src/lib/statistics/statistics_objects/range_filter.hpp [hunk 104]
```diff
@@ -0,0 +1,66 @@
...
+
+//! default number of maximum range count
+static constexpr uint32_t MAX_RANGES_COUNT = 10;
+
+/**
+ * Filter that stores a certain number of value ranges. Each range represents a spread
+ * of values that is contained within the bounds.
+ * Example: [1, 2, 4, 7] might be represented as [1, 7]
+ * These ranges can be used to check whether a certain value exists in the segment.
+ * Once the between operator uses two parameters, the ranges can be used for that as well.
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/range_filter.hpp]: I don't understand the between part

File: src/lib/statistics/statistics_objects/range_filter.hpp [hunk 105]
```diff
@@ -0,0 +1,66 @@
...
+#include <memory>
+#include <optional>
+#include <vector>
+
+#include "abstract_statistics_object.hpp"
+#include "types.hpp"
+
+namespace opossum {
+
+//! default number of maximum range count
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/range_filter.hpp]: Where does the `!` come from?

File: src/lib/statistics/statistics_objects/range_filter.cpp [hunk 106]
```diff
@@ -0,0 +1,288 @@
...
+
+template <typename T>
+std::shared_ptr<AbstractStatisticsObject> RangeFilter<T>::scaled(const Selectivity /*selectivity*/) const {
+  return std::make_shared<RangeFilter<T>>(ranges);
+}
+
+template <typename T>
+std::unique_ptr<RangeFilter<T>> RangeFilter<T>::build_filter(const pmr_vector<T>& dictionary,
+                                                             uint32_t max_ranges_count) {
+  static_assert(std::is_arithmetic_v<T>, "Range filters are only allowed on arithmetic types.");
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/range_filter.cpp]: This was not mentioned in the class comment. Why is this the case?

File: src/lib/statistics/statistics_objects/range_filter.cpp [hunk 107]
```diff
@@ -0,0 +1,288 @@
...
+
+  if (dictionary.size() == 1) {
+    std::vector<std::pair<T, T>> ranges;
+    ranges.emplace_back(dictionary.front(), dictionary.front());
+    return std::make_unique<RangeFilter<T>>(std::move(ranges));
+  }
+
+  /*
+  * In case more than one value is present, first the elements are checked for potential overflows (e.g., when calculating
+  * the distince between INT::MIN() and INT::MAX(), the resulting distance might be to large for signed types).
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/range_filter.cpp]: two typos

Comment (mrks) [inline src/lib/statistics/statistics_objects/range_filter.cpp]: Please explain why you are talking about the distance at all

File: src/lib/statistics/statistics_objects/histogram_domain.cpp [hunk 108]
```diff
@@ -0,0 +1,133 @@
...
+  for (auto pos = size_t{0}; pos < string_value.size(); ++pos) {
+    if (string_value[pos] > max_char || string_value[pos] < min_char) {
+      return false;
+    }
+  }
+  return true;
+}
+
+pmr_string HistogramDomain<pmr_string>::next_value(const pmr_string& string_value) const {
+  DebugAssert(contains(string_value), "Unsupported character, cannot compute next_value()");
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/histogram_domain.cpp]: What happens if I search for `s LIKE a☺a%`?

File: src/lib/statistics/statistics_objects/range_filter.cpp [hunk 109]
```diff
@@ -0,0 +1,288 @@
...
+  * While being rather unlikely for doubles, it's more likely to happen when Opossum includes tinyint etc.
+  * std::make_unsigned<T>::type would be possible to use for signed int types, but not for floating types.
+  * Approach: take the min and max values and simply check if the distance between both might overflow. In this case,
+  * fall back to a single range filter.
+  */
+  const auto min_max = std::minmax_element(dictionary.cbegin(), dictionary.cend());
+  if ((*min_max.first < 0) &&
+      (*min_max.second > std::numeric_limits<T>::max() + *min_max.first)) {  // min_value is negative
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/range_filter.cpp]: This reads as if "min_value is negative" is a problem in itself

File: src/lib/statistics/statistics_objects/range_filter.cpp [hunk 110]
```diff
@@ -0,0 +1,288 @@
...
+  // start   end  next_startpoint
+  // v       v    v
+  // 1 2 3 4 5    10 11     15 16
+  //         ^
+  //         distance 5, index 4
+  //
+  // next_startpoint is the start of the next range
+
+  std::vector<std::pair<T, T>> ranges;
+  size_t next_startpoint = 0u;
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/range_filter.cpp]: `next_start_point`?

File: src/lib/statistics/statistics_objects/range_filter.cpp [hunk 111]
```diff
@@ -0,0 +1,288 @@
...
+  std::sort(distances.begin(), distances.end(),
+            [](const auto& pair1, const auto& pair2) { return pair1.second < pair2.second; });
+  // we want a range until the last element in the dictionary
+  distances.emplace_back(T{}, dictionary.size() - 1);
+
+  // derive intervals from distances where items exist
+  //
+  // start   end  next_startpoint
+  // v       v    v
+  // 1 2 3 4 5    10 11     15 16
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/range_filter.cpp]: I think this would be clearer if the example would run like a golden thread through this. Reading this from the start, I had to think for a while why you sort the distances etc.

File: src/lib/statistics/statistics_objects/range_filter.cpp [hunk 112]
```diff
@@ -0,0 +1,288 @@
...
+}
+
+template <typename T>
+bool RangeFilter<T>::does_not_contain(const PredicateCondition predicate_condition, const AllTypeVariant& variant_value,
+                                      const std::optional<AllTypeVariant>& variant_value2) const {
+  /*
+      * Early exit for NULL-checking predicates and NULL variants. Predicates with one or
+      * more variant parameter being NULL are not prunable. Malformed predicates such as
+      * can_prune(PredicateCondition::LessThan, {5}, NULL_VALUE) are not pruned either,
+      * the caller is expected to call the function correctly.
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/range_filter.cpp]: Shouldn't we assert this then?

File: src/lib/statistics/statistics_objects/range_filter.cpp [hunk 113]
```diff
@@ -0,0 +1,288 @@
...
+      */
+  if (variant_is_null(variant_value) || (variant_value2.has_value() && variant_is_null(variant_value2.value())) ||
+      predicate_condition == PredicateCondition::IsNull || predicate_condition == PredicateCondition::IsNotNull) {
+    return false;
+  }
+
+  const auto value = boost::get<T>(variant_value);
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/range_filter.cpp]: We check for NULL values, but what if `variant_value` is of a different type?

File: src/lib/statistics/statistics_objects/range_filter.cpp [hunk 114]
```diff
@@ -0,0 +1,288 @@
...
+       *    - both bounds are within the same gap
+       */
+
+      Assert(variant_value2.has_value(), "Between operator needs two values.");
+      const auto value2 = boost::get<T>(*variant_value2);
+
+      // a BETWEEN 5 AND 4 will always be empty
+      if (value2 < value) return true;
+
+      // Smaller than the segment's minimum.
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/range_filter.cpp]: I thought statistics objects might span multiple chunks?

File: src/lib/statistics/statistics_objects/range_filter.cpp [hunk 115]
```diff
@@ -0,0 +1,288 @@
...
+      if (does_not_contain(PredicateCondition::LessThanEquals, std::max(value, value2))) {
+        return true;
+      }
+
+      // Larger than the segment's maximum.
+      if (does_not_contain(PredicateCondition::GreaterThanEquals, std::min(value, value2))) {
+        return true;
+      }
+
+      const auto range_comp = [](std::pair<T, T> range, T compare_value) -> bool {
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/range_filter.cpp]: Any reason you're explicitly listing the return type here?

File: src/lib/statistics/statistics_objects/single_bin_histogram.hpp [hunk 116]
```diff
@@ -0,0 +1,50 @@
...
+#include <vector>
+
+#include "abstract_histogram.hpp"
+#include "types.hpp"
+
+namespace opossum {
+
+/**
+ * Histogram with a single bin.
+ * This histogram type is intended for statistics where only minimal information is known or required (e.g. in Tests).
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/single_bin_histogram.hpp]: What advantage does this have over the generic histogram that justifies having another class?

File: src/lib/statistics/table_statistics.cpp [hunk 117]
```diff
@@ -1,317 +1,96 @@
...
 namespace opossum {
 
-TableStatistics::TableStatistics(const TableType table_type, const float row_count,
-                                 const std::vector<std::shared_ptr<const BaseColumnStatistics>>& column_statistics)
-    : _table_type(table_type), _row_count(row_count), _column_statistics(column_statistics) {}
+std::shared_ptr<TableStatistics> TableStatistics::from_table(const Table& table) {
+  std::vector<std::shared_ptr<BaseColumnStatistics>> column_statistics(table.column_count());
 
-TableType TableStatistics::table_type() const { return _table_type; }
+  const auto histogram_bin_count = std::min<size_t>(100, std::max<size_t>(5, table.row_count() / 2'000));
```
Comment (mrks) [inline src/lib/statistics/table_statistics.cpp]: Where do these numbers come from?

File: src/lib/statistics/table_statistics.cpp [hunk 118]
```diff
@@ -1,317 +1,96 @@
...
 
-uint64_t TableStatistics::approx_valid_row_count() const {
-  return static_cast<size_t>(row_count()) - _approx_invalid_row_count;
-}
+  for (auto thread_id = 0u;
+       thread_id < std::min(static_cast<uint>(table.column_count()), std::thread::hardware_concurrency() + 1);
+       ++thread_id) {
+    threads.emplace_back([&] {
+      while (true) {
+        auto my_column_id = ColumnID{static_cast<ColumnID::base_type>(next_column_id++)};
```
Comment (mrks) [inline src/lib/statistics/table_statistics.cpp]: Isn't that cast done implicitly?

File: src/lib/statistics/table_statistics.cpp [hunk 119]
```diff
@@ -1,317 +1,96 @@
...
+  auto threads = std::vector<std::thread>{};
 
-uint64_t TableStatistics::approx_valid_row_count() const {
-  return static_cast<size_t>(row_count()) - _approx_invalid_row_count;
-}
+  for (auto thread_id = 0u;
+       thread_id < std::min(static_cast<uint>(table.column_count()), std::thread::hardware_concurrency() + 1);
+       ++thread_id) {
+    threads.emplace_back([&] {
+      while (true) {
```
Comment (mrks) [inline src/lib/statistics/table_statistics.cpp]: A thread with a `while (true)` loop first looks like it is meant to run for a long time. Why is this necessary here?

File: src/lib/statistics/table_statistics.cpp [hunk 120]
```diff
@@ -1,317 +1,96 @@
...
-    const auto selectivity =
-        predicate_condition == PredicateCondition::Like ? DEFAULT_LIKE_SELECTIVITY : 1.0f - DEFAULT_LIKE_SELECTIVITY;
-    return {TableType::References, _row_count * selectivity, _column_statistics};
-  }
+          auto histogram = std::shared_ptr<AbstractHistogram<ColumnDataType>>{};
 
-  // Create copies to modify below and insert into result
-  auto predicated_row_count = _row_count;
-  auto predicated_column_statistics = _column_statistics;
+          histogram =
```
Comment (mrks) [inline src/lib/statistics/table_statistics.cpp]: Why can't we do `auto histogram =`?

File: src/lib/statistics/table_statistics.cpp [hunk 121]
```diff
@@ -1,317 +1,96 @@
...
-    predicated_column_statistics[column_id] = left_operand_column_statistics->without_null_values();
-    predicated_row_count *= 1.0f - left_operand_column_statistics->non_null_value_ratio();
-  } else if (predicate_condition == PredicateCondition::IsNull) {
-    predicated_column_statistics[column_id] = left_operand_column_statistics->only_null_values();
-    predicated_row_count *= left_operand_column_statistics->non_null_value_ratio();
-  } else if (is_column_id(value)) {
-    const auto column_id_of_value = boost::get<ColumnID>(value);
-    const auto estimation = left_operand_column_statistics->estimate_predicate_with_column(
-        predicate_condition, *_column_statistics[column_id_of_value]);
+            // Use the insight the the histogram will only contain non-null values to generate the NullValueRatio
```
Comment (mrks) [inline src/lib/statistics/table_statistics.cpp]: `that the`?

File: src/lib/statistics/table_statistics.cpp [hunk 122]
```diff
@@ -1,317 +1,96 @@
...
+            // property
+            const auto null_value_ratio =
+                table.row_count() == 0 ? 0.0f
+                                       : 1.0f - (static_cast<float>(histogram->total_count()) / table.row_count());
+            output_column_statistics->set_statistics_object(
+                std::make_shared<NullValueRatioStatistics>(null_value_ratio));
+          } else {
+            // Failure to generate a histogram currently only stems from all-null segments.
+            // TODO(anybody) this is a slippery assumption. But the alternative would be a full segment scan...
```
Comment (mrks) [inline src/lib/statistics/table_statistics.cpp]: At least check it? With a 100% null segment, someone else might introduce pruning rules for something that is apparently empty.

File: src/lib/statistics/table_statistics.hpp [hunk 123]
```diff
@@ -1,75 +1,41 @@
...
-  static constexpr auto DEFAULT_DISJUNCTION_SELECTIVITY = 0.2f;
-
-  TableStatistics(const TableType table_type, const float row_count,
-                  const std::vector<std::shared_ptr<const BaseColumnStatistics>>& column_statistics);
-  TableStatistics(const TableStatistics& table_statistics) = default;
-
   /**
-   * @defgroup Member access
-   * @{
+   * Generates histograms for all columns
```
Comment (mrks) [inline src/lib/statistics/table_statistics.hpp]: It should become clearer that this is a design decision

File: src/lib/storage/table.hpp [hunk 124]
```diff
@@ -154,9 +154,15 @@ class Table : private Noncopyable {
 
   std::unique_lock<std::mutex> acquire_append_mutex();
 
-  void set_table_statistics(std::shared_ptr<TableStatistics> table_statistics) { _table_statistics = table_statistics; }
+  /**
+   * Tables, typically those stored in the StorageManager, can be associated with statistcs to perform Cardinality
+   * Estimation during Optimization.
```
Comment (mrks) [inline src/lib/storage/table.hpp]: typo. Also, why are cardinality estimation and optimization written in caps?

File: src/lib/optimizer/strategy/predicate_reordering_rule.cpp (hunk 49 above)
Comment (mrzzzrm) [reply src/lib/optimizer/strategy/predicate_reordering_rule.cpp]: Tried again, at loss whether this makes it better:

```
  // Setup cardinality estimation cache so that the statistics of `input` (which might be a big plan) do not need to
  // be determined repeatedly. For this, we hijack the `guarantee_join_graph()`-guarantee and via it promise the
  // CardinalityEstimator that we will not change the LQP below the `input` node by marking it as a "vertex". 
  // This allows the CardinalityEstimator to compute the statistics of `input` once, chache them and then re-use them.
```

File: src/lib/statistics/cardinality_estimator.cpp (hunk 71 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: > 1 or a 0

```
  // One bit for each of JoinGraph's vertices followed by one bit for each predicate. Represents a subgraph of a 
  // JoinGraph. "1" means that the vertex/predicate is included in the subgraph.
```

> Also: Can multiple subplans result in the same bitmask and how are they stored in the cache?

That's the entire point: different subplans that perform the same operation will have the same bitmask and thus can share a cache entry.

File: src/lib/statistics/cardinality_estimator.cpp (hunk 65 above)
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: This is awkward, really. I have now arrived at this comment:
```
            // Lacking better options, assume a "magic" selectivity for >, >=, <, <=, ... Any number would be equally
            // right and wrong here. In some examples, this seemed like a good guess ¯\_(ツ)_/¯
```

It doesn't get much better imo. For some magic numbers the justification is literally that: it seemed to be a good choice in an example I looked at.

File: src/lib/statistics/generate_pruning_statistics.cpp [hunk 125]
```diff
@@ -0,0 +1,94 @@
...
+#include "statistics/table_statistics.hpp"
+#include "storage/create_iterable_from_segment.hpp"
+#include "storage/table.hpp"
+
+namespace {
+
+using namespace opossum;  // NOLINT
+
+template <typename T>
+void create_pruning_filter_for_segment(ColumnStatistics<T>& column_statistics, const pmr_vector<T>& dictionary) {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/generate_pruning_statistics.cpp]: I know what you mean. Chunks can have a ColumnStatistics object for each of their Segments to be used as pruning statistics. Since statistics objects can be used for both pruning (which happens on a single Chunk/Segment) and cardinality estimation (which happens on the entire Table/column) ColumnStatistics is used to wrap the statistics of both purposes.

I once called this "VerticalStatisticsSlice" as a name that covers both purposes equally, but I don't think that's any better

File: src/lib/statistics/generate_pruning_statistics.cpp [hunk 126]
```diff
@@ -0,0 +1,94 @@
...
+  std::shared_ptr<AbstractStatisticsObject> pruning_filter;
+  if constexpr (std::is_arithmetic_v<T>) {
+    if (!column_statistics.range_filter) {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/generate_pruning_statistics.cpp]: I know what you mean... Those checks were there to prevent redundant work from being done, but I removed them, generate_chunk_pruning_statistics shouldn't be called multiple times anyway...

File: src/lib/statistics/generate_pruning_statistics.cpp [hunk 127]
```diff
@@ -0,0 +1,94 @@
...
+      resolve_data_and_segment_type(*segment, [&](auto type, auto& typed_segment) {
+        using SegmentType = std::decay_t<decltype(typed_segment)>;
+        using ColumnDataType = typename decltype(type)::type;
+
+        const auto segment_statistics = std::make_shared<ColumnStatistics<ColumnDataType>>();
+
+        if constexpr (std::is_same_v<SegmentType, DictionarySegment<ColumnDataType>>) {
+          // we can use the fact that dictionary segments have an accessor for the dictionary
+          const auto& dictionary = *typed_segment.dictionary();
+          create_pruning_filter_for_segment(*segment_statistics, dictionary);
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/generate_pruning_statistics.cpp]: See https://github.com/hyrise/hyrise/pull/1489#discussion_r288135239 - we can also talk about this in person if you like.

File: src/lib/statistics/column_statistics.hpp [hunk 128]
```diff
@@ -1,96 +1,82 @@
...
+template <typename T>
+class MinMaxFilter;
+template <typename T>
+class RangeFilter;
+template <typename T>
+class CountingQuotientFilter;
+
 /**
- * @tparam ColumnDataType   the DataType of the values in the Column that these statistics represent
+ * Statistically represents a slice of a Column. Might cover any number of rows or Chunks.
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/column_statistics.hpp]: Shortened to 

```
/**
 * Statistically represents a Column (when used in TableStatistics) or a Segment (when used in ColumnPruningStatistics).
 *
 * Contains any number of AbstractStatisticsObjects (Histograms, Filters, etc.).
 */
```

but this is the same discussion as https://github.com/hyrise/hyrise/pull/1489#discussion_r288135239 and we should probably discuss this in person

File: src/lib/statistics/join_graph_statistics_cache.hpp [hunk 129]
```diff
@@ -0,0 +1,71 @@
...
+ * The key of the cache is a bitmask (with each bit representing a predicate or a vertex node).
+ *
+ * This cache exists primarily to aid the performance of the JoinOrderingRule.
+ * The JOR frequently request statistics for different plans consisting of the same set of Join and Scan predicates.
+ */
+class JoinGraphStatisticsCache {
+ public:
+  using Bitmask = boost::dynamic_bitset<>;
+  using VertexIndexMap = std::unordered_map<std::shared_ptr<AbstractLQPNode>, size_t>;
+  using PredicateIndexMap = ExpressionUnorderedMap<size_t>;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/join_graph_statistics_cache.hpp]: Docs for all three types now read as follows:

```
  // One bit for each of JoinGraph's vertices followed by one bit for each predicate. Represents a subgraph of a
  // JoinGraph. "1" means that the vertex/predicate is included in the subgraph.
  using Bitmask = boost::dynamic_bitset<>;
  
  // Maps vertices to their index in the Bitmask
  using VertexIndexMap = std::unordered_map<std::shared_ptr<AbstractLQPNode>, size_t>;
  
  // Maps predicates to their index in the Bitmask
  using PredicateIndexMap = ExpressionUnorderedMap<size_t>;
```

File: src/lib/statistics/join_graph_statistics_cache.hpp [hunk 130]
```diff
@@ -0,0 +1,71 @@
...
+
+  static JoinGraphStatisticsCache from_join_graph(const JoinGraph& join_graph);
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/join_graph_statistics_cache.hpp]: Added 
```
  // Creates a JoinGraphStatisticsCache with VertexIndexMap and PredicateIndexMap pointing to the vertices / predicates
  // in the JoinGraph
```

why is this not a "proper constructor"? Because, imo, a constructor should take the arguments that actually make up the data structure and not some other class from which they can be derived. I want to emphasize that there is actual work being done to get from JoinGraph to JoinGraphStatisticsCache.

File: src/lib/statistics/join_graph_statistics_cache.hpp [hunk 131]
```diff
@@ -0,0 +1,71 @@
...
+
+  JoinGraphStatisticsCache(VertexIndexMap&& vertex_indices, PredicateIndexMap&& predicate_indices);
+
+  /**
+   * Try to build a bitmask (aka cache key) from an LQP. This will either return the bitmask or std::nullopt, if
+   * Predicates or Vertices not registered in _vertex_indices and _predicate_indices are encountered.
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/join_graph_statistics_cache.hpp]: Shouldn't be present, thinking about it. Put in asserts.

[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/join_graph_statistics_cache.hpp]: Let's see whether they are triggered.

File: src/lib/statistics/join_graph_statistics_cache.hpp [hunk 132]
```diff
@@ -0,0 +1,71 @@
...
+   */
+  std::optional<Bitmask> bitmask(const std::shared_ptr<AbstractLQPNode>& lqp) const;
+
+  /**
+   * Retrieve the cached statistics associated with @param bitmask. The order of columns in the returned TableStatistics
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/join_graph_statistics_cache.hpp]: Dunno what "above" refers to. What is a "duplicate bitmask"?

File: src/lib/statistics/join_graph_statistics_cache.hpp (hunk 131 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/join_graph_statistics_cache.hpp]: Ah, I remember. Unexpected nodes can be encountered once the CardinalityEstimator "enters" a vertex subplan. 
No, I won't disable the cache in the CardinalityEstimator once that happens.

File: src/lib/statistics/join_graph_statistics_cache.hpp [hunk 133]
```diff
@@ -0,0 +1,71 @@
...
+   * will be as specified by @param requested_column_order. Returns nullptr if no cache entry exists for the specified
+   * bitmask.
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/join_graph_statistics_cache.hpp]: I found this way simpler than having the cache return a statistics object + a column order which the caller then has to reorganize. Tacked on or not, I'd leave it as it is. Caching statistics for JoinGraphs is fundamentally something that needs to deal with column reordering as different LQPs representing the same join graph will have different column orders.

File: src/lib/statistics/join_graph_statistics_cache.hpp [hunk 134]
```diff
@@ -0,0 +1,71 @@
...
+  const PredicateIndexMap _predicate_indices;
+
+  struct CacheEntry {
+    std::shared_ptr<TableStatistics> table_statistics;
+    // TableStatistics hold no info about which column corresponds to which expression. We need this info in
+    // JoinGraphStatisticsCache::get(), so we cache it here.
+    ExpressionUnorderedMap<ColumnID> column_expression_order;
+  };
+
+  // There is no std::hash<Bitmask>... :(
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/join_graph_statistics_cache.hpp]: Extended to
```
  // There is no std::hash<Bitmask> and Bitmask/boost::dynamic_bitset<> doesn't expose the data necessary to implement
  // this efficiently... :(
```

File: src/lib/statistics/join_graph_statistics_cache.cpp [hunk 135]
```diff
@@ -0,0 +1,152 @@
...
+
+#include "logical_query_plan/lqp_utils.hpp"
+#include "optimizer/join_ordering/join_graph.hpp"
+#include "statistics/table_statistics.hpp"
+
+namespace {
+
+using namespace opossum;  // NOLINT
+
+}  // namespace
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/join_graph_statistics_cache.cpp]: none

File: src/lib/statistics/join_graph_statistics_cache.cpp [hunk 136]
```diff
@@ -0,0 +1,152 @@
...
+    for (const auto& predicate : edge.predicates) {
+      predicate_indices.emplace(predicate, predicate_idx++);
+    }
+  }
+
+  return {std::move(vertex_indices), std::move(predicate_indices)};
+}
+
+JoinGraphStatisticsCache::JoinGraphStatisticsCache(VertexIndexMap&& vertex_indices,
+                                                   PredicateIndexMap&& predicate_indices)
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/join_graph_statistics_cache.cpp]: Since when do we use noexcept and why in this place in particular. I know close to nothing about c++ exceptions

File: src/lib/statistics/join_graph_statistics_cache.cpp [hunk 137]
```diff
@@ -0,0 +1,152 @@
...
+    : _vertex_indices(std::move(vertex_indices)), _predicate_indices(std::move(predicate_indices)) {}
+
+std::optional<JoinGraphStatisticsCache::Bitmask> JoinGraphStatisticsCache::bitmask(
+    const std::shared_ptr<AbstractLQPNode>& lqp) const {
+  auto bitmask = std::optional<Bitmask>{_vertex_indices.size() + _predicate_indices.size()};
+
+  visit_lqp(lqp, [&](const auto& node) {
+    if (!bitmask) return LQPVisitation::DoNotVisitInputs;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/join_graph_statistics_cache.cpp]: `visit_lqp` goes through the entire lqp and potentially writes to the bitmask?

File: src/lib/statistics/join_graph_statistics_cache.cpp [hunk 138]
```diff
@@ -0,0 +1,152 @@
...
+
+std::shared_ptr<TableStatistics> JoinGraphStatisticsCache::get(
+    const Bitmask& bitmask, const std::vector<std::shared_ptr<AbstractExpression>>& requested_column_order) const {
+  const auto cache_iter = _cache.find(bitmask);
+  if (cache_iter == _cache.end()) {
+    return nullptr;
+  }
+
+  /**
+   * We found a matching cache_entry. Now, let's adjust its column order
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/join_graph_statistics_cache.cpp]: In person?

File: src/lib/statistics/statistics_objects/abstract_histogram.hpp [hunk 139]
```diff
@@ -0,0 +1,256 @@
...
+
+template <typename T>
+struct HistogramBin {
+  HistogramBin(const T& min, const T& max, const HistogramCountType height, const HistogramCountType distinct_count)
+      : min(min), max(max), height(height), distinct_count(distinct_count) {}
+
+  T min{};
+  T max{};
+  HistogramCountType height{};
+  HistogramCountType distinct_count{};
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.hpp]: In person. I'm making a list

File: src/lib/statistics/statistics_objects/abstract_histogram.hpp [hunk 140]
```diff
@@ -0,0 +1,256 @@
...
+
+  /**
+   * Returns the width of a bin.
+   * This method is specialized for strings to return a numerical width.
+   */
+  virtual HistogramWidthType bin_width(const BinID index) const;
+
+  /**
+   * Helper function
+   * @return {bin_minimum(index), bin_maximum(index), bin_height(index), bin_distinct_count(index)}
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.hpp]: There is no such thing as the "actual" bin. minima/maxima/height/distinct count will be retrieved from different data sources depending on the histogram type. E.g. EqualDistinctCount will store a single distinct count, not one per bin

File: src/lib/statistics/statistics_objects/abstract_histogram.hpp [hunk 141]
```diff
@@ -0,0 +1,256 @@
...
+   * Currently, this is just a dummy heuristic that ensures the resulting distinct count does not exceed the resulting
+   * value count
+   */
+  Cardinality _scale_distinct_count(Selectivity selectivity, Cardinality value_count, Cardinality distinct_count) const;
+
+  // Call after constructor of the derived histogram has finished to check whether the bins are valid
+  // (e.g. do not overlap).
+  void _assert_bin_validity();
+
+  HistogramDomain<T> _domain;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.hpp]: No point, imo. That's the entire point of having EqualDistinctCount/EqualWidth/... derivates. I wanted to change this to a Histogram class having a "AbstractHistogramBinStorage" class but it wasn't worth the struggle for the moment. In person.

File: src/lib/statistics/statistics_objects/abstract_histogram.hpp [hunk 142]
```diff
@@ -0,0 +1,256 @@
...
+   */
+  HistogramBin<T> bin(const BinID index) const;
+
+  /**
+   * Returns the share of the value range of a bin that are smaller (or equals) than `value`.
+   * This method is specialized for strings.
+   * @{
+   */
+  float bin_ratio_less_than(const BinID bin_id, const T& value) const;
+  float bin_ratio_less_than_equals(const BinID bin_id, const T& value) const;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.hpp]: totally different things imo.

File: src/lib/statistics/statistics_objects/abstract_histogram.hpp [hunk 143]
```diff
@@ -0,0 +1,256 @@
...
+  /** @} */
+
+ protected:
+  Cardinality _invert_estimate(const Cardinality& estimate) const;
+  CardinalityAndDistinctCountEstimate _invert_estimate(const CardinalityAndDistinctCountEstimate& estimate) const;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.hpp]: why doc internal functions that are 4 lines long and are better explained by their implementation anyway?

File: src/lib/statistics/statistics_objects/abstract_histogram.hpp [hunk 144]
```diff
@@ -0,0 +1,256 @@
...
+   * This method is specialized for strings to handle predicates uniquely applicable to string columns.
+   */
+  bool _does_not_contain(const PredicateCondition predicate_condition, const AllTypeVariant& variant_value,
+                         const std::optional<AllTypeVariant>& variant_value2 = std::nullopt) const;
+
+  /**
+   * Returns whether a given predicate type and its parameter(s) can belong to a bin or not
+   * for predicate types supported by all data types.
+   */
+  bool _general_does_not_contain(const PredicateCondition predicate_condition, const AllTypeVariant& variant_value,
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.hpp]: Cocky answer: "You" call none of both, because they are internal. But I don't like this duality either. In person.

File: src/lib/statistics/statistics_objects/abstract_histogram.hpp [hunk 145]
```diff
@@ -0,0 +1,256 @@
...
+
+  /**
+   * @returns detailed information about the histogram, including the properties of the individual bins.
+   */
+  std::string description() const;
+
+  Cardinality estimate_cardinality(const PredicateCondition predicate_condition, const AllTypeVariant& variant_value,
+                                   const std::optional<AllTypeVariant>& variant_value2 = std::nullopt) const;
+
+  CardinalityAndDistinctCountEstimate estimate_cardinality_and_distinct_count(
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.hpp]: That's what `estimate_cardinality` is doing for the caller, right?

```c++
template <typename T>
Cardinality AbstractHistogram<T>::estimate_cardinality(const PredicateCondition predicate_condition,
                                                       const AllTypeVariant& variant_value,
                                                       const std::optional<AllTypeVariant>& variant_value2) const {
  const auto estimate = estimate_cardinality_and_distinct_count(predicate_condition, variant_value, variant_value2);
  return estimate.first;
}
````

File: src/lib/statistics/statistics_objects/abstract_histogram.hpp [hunk 146]
```diff
@@ -0,0 +1,256 @@
...
+   * for predicate types supported by all data types.
+   */
+  bool _general_does_not_contain(const PredicateCondition predicate_condition, const AllTypeVariant& variant_value,
+                                 const std::optional<AllTypeVariant>& variant_value2 = std::nullopt) const;
+
+  /**
+   * Returns the id of the bin that holds the given `value`.
+   * Returns INVALID_BIN_ID if `value` does not belong to any bin.
+   */
+  virtual BinID _bin_for_value(const T& value) const = 0;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.hpp]: legacy. But. no one would use them right now, and if they were public I'd need to add tests for them, which would - since they're only used internally anyway - just be boilerplate.

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 147]
```diff
@@ -0,0 +1,1035 @@
...
+    * We need to convert strings to their numerical representation to calculate a share.
+    * This conversion is done based on prefixes because strings of arbitrary length cannot be converted to a numerical
+    * representation that satisfies the following requirements:
+    *  1. For two strings s1 and s2: s1 < s2 -> repr(s1) < repr(s2)
+    *  2. For two strings s1 and s2: dist(s1, s2) == repr(s2) - repr(s1)
+    *  repr(s) is the numerical representation for a string s, and dist(s1, s2) returns the number of strings between
+    *  s1 and s2 in the domain of strings with at most length `string_prefix_length`
+    *  and the set of supported characters `supported_characters`.
+    *
+    * Thus, we calculate the range based only on a domain of strings with a maximum length of `string_prefix_length`
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: Bloody walls of comments. This was renamed to "common_prefix_length"

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 148]
```diff
@@ -0,0 +1,1035 @@
...
+    *  Instead, we strip the common prefix ("intelli") and calculate the share based on the numerical representation
+    *  of the substring after the common prefix.
+    *  That is, what is the share of values smaller than "gent" in the range ["gence", "j"]?
+    */
+
+    const auto bin_min = bin_minimum(bin_id);
+    const auto bin_max = bin_maximum(bin_id);
+
+    auto common_prefix_length = size_t{0};
+    const auto max_common_prefix_len = std::min(bin_min.length(), bin_max.length());
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: Maybe this makes sense with this comment:
```
    // Determine the common_prefix_lengths of bin_min and bin_max. E.g. bin_max=abcdefgh and bin_max=abcz have a
    // common_prefix_length=3
```

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 149]
```diff
@@ -0,0 +1,1035 @@
...
+    for (; common_prefix_length < max_common_prefix_len; ++common_prefix_length) {
+      if (bin_min[common_prefix_length] != bin_max[common_prefix_length]) {
+        break;
+      }
+    }
+
+    DebugAssert(value.substr(0, common_prefix_length) == bin_min.substr(0, common_prefix_length),
+                "Value does not belong to bin");
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: legacy. removed. we check for 
```
  if (value < bin_minimum(bin_id)) {
    return 0.0f;
  }

  if (value >= bin_maximum(bin_id)) {
    return 1.0f;
  }
```

above anyway

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 150]
```diff
@@ -0,0 +1,1035 @@
...
+  }
+
+  switch (predicate_condition) {
+    case PredicateCondition::Equals: {
+      const auto bin_id = _bin_for_value(*value);
+      // It is possible for EqualWidthHistograms to have empty bins.
+      return bin_id == INVALID_BIN_ID || bin_height(bin_id) == 0ul;
+    }
+    case PredicateCondition::NotEquals:
+      return bin_minimum(BinID{0}) == value && bin_maximum(bin_count() - 1) == value;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: legacy, I believe. Changed to `
      return _bin_for_value(*value) == INVALID_BIN_ID;`

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 151]
```diff
@@ -0,0 +1,1035 @@
...
+      return value > bin_maximum(bin_count() - 1);
+    case PredicateCondition::GreaterThan:
+      return value >= bin_maximum(bin_count() - 1);
+    case PredicateCondition::BetweenInclusive:
+    case PredicateCondition::BetweenLowerExclusive:
+    case PredicateCondition::BetweenUpperExclusive:
+    case PredicateCondition::BetweenExclusive: {
+      Assert(static_cast<bool>(variant_value2), "Between operator needs two values.");
+
+      if (_does_not_contain(PredicateCondition::GreaterThanEquals, *value)) {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: Added 
```
    // These are statistical estimations, currently there is no point in distinguishing between the different Between*
    // types.
```

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 76 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: With the Between to >= AND <= rewrite rule, we might not need these estimations anymore. in person.

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 77 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: legacy. not tested. in person. let's make this dependent on whether we keep like estimations in the histograms.

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 78 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: they are internal, they are tested via the publicly exposed methods (which are tested) that use them

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 79 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: "you" is the one addressee here, this is Tim's doing ;). in person.  let's make this dependent on whether we keep like estimations in the histograms.

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 80 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: thankfully apparently not

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 81 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: histograms are statistical estimation. histograms resulting from previous estimations of predicates can easily have bin_heights/distinct counts < 1. We still want these numbers as they are, and not rounded up to 1, or something. This is so widespread that doc'ing this won't help. It is an intrinsic properties of statistics objects that they are estimations.

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 82 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: legacy. changed to find

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 83 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: legacy. changed to find

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 150 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: Nope, fallacy. the function is to return true if the predicate would have a cardinality of zero. for NOT EQUALS this is only the case if the histogram contained a single value and we check != that value.-

**Comment by mrks** [comment]
@mrzzzrm - Did we discuss all open questions in our last meeting or should I do another pass?

**Comment by mrzzzrm** [comment]
I only extracted a selection of the open discussions for that personal meeting (tagged with "in person"). Everything else we need to discuss here on github.

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 77 above)
Comment (mrks) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: iirc, we decided to kill this.

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 76 above)
Comment (mrks) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: iirc, we decided to kill this.

File: src/lib/statistics/statistics_objects/abstract_histogram.hpp (hunk 143 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/statistics/statistics_objects/abstract_histogram.hpp]: So that people who have a first look at a class get an idea of what it is able to do. Of course you could look into the implementation, but that requires a much deeper understanding.

File: src/lib/statistics/statistics_objects/abstract_histogram.hpp (hunk 140 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/statistics/statistics_objects/abstract_histogram.hpp]: Got it. Maybe add this as a comment?

File: src/lib/statistics/statistics_objects/abstract_histogram.hpp (hunk 145 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/statistics/statistics_objects/abstract_histogram.hpp]: Looked at the hpp first. Personally, I'd drop the convenience method in favor of a structured binding on the caller side, but I don't have strong feelings about this.

File: src/lib/statistics/join_graph_statistics_cache.cpp (hunk 137 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/statistics/join_graph_statistics_cache.cpp]: Ah. I mistook this for `boost::dynamic_bitset<>::operator bool() const;`. I wish `optional<T>` would enforce the use of `has_value` if `T` is convertible to bool.

File: src/lib/statistics/join_graph_statistics_cache.hpp (hunk 134 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/statistics/join_graph_statistics_cache.hpp]: Hey, this has only been an issue [for ten years](https://svn.boost.org/trac10/ticket/2841)...

File: src/lib/statistics/generate_pruning_statistics.cpp (hunk 125 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/generate_pruning_statistics.cpp]: Right now I feel like renaming `ColumnStatistics` to `AttributeStatistics` with the class comment "// Represents either an entire Column or a single Segment` is the best course. You cool with this?

File: src/lib/statistics/join_graph_statistics_cache.hpp (hunk 133 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/join_graph_statistics_cache.hpp]: We discussed this in person and while there is also the possibility of `JoinGraphStatisticsCache::get()` returning a `CacheEntry`, which in turn might have a function `CacheEntry::get_statistics_with_column_order(....)` I like the current interface better since it makes cache set/get a single step respectively. I think in our discussion we concluded that this is acceptable.

File: src/lib/statistics/join_graph_statistics_cache.cpp (hunk 137 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/join_graph_statistics_cache.cpp]: Changed to 

```c++
    // Early out if `bitmask.reset()` was called during the search below
    if (!bitmask.has_value()) return LQPVisitation::DoNotVisitInputs;
```

File: src/lib/statistics/statistics_objects/abstract_histogram.hpp (hunk 139 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.hpp]: Still opposed to making struct members const. If C++ were const-by-default this would be a different matter, but since it isn't the const qualifier makes it look like elaborate thought went into it, and people will be afraid to remove it again. A dumb struct should look like a dumb struct. 

[This](https://www.reddit.com/r/cpp/comments/8wbeom/coding_guideline_avoid_const_member_variables/) thread provides more, maybe obscure points. 
* "[...] your type is not going to be naturally move assignable, or swappable"
* "In general, using `const` in a member variable is bad because you are enforcing an API invariant at too low a level" <- I guess this is mostly my point
* " `const` on a member variable can force your class to have a throwing move"

File: src/lib/statistics/statistics_objects/abstract_histogram.hpp (hunk 140 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.hpp]: Better?
```c++
  /**
   * Helper function to retrieve all properties of a bin in a single struct. Convenience method, as histogram 
   * implementations do store bins in different ways (EqualDistinctCountHistogram, e.g., has a single member holding
   * the distinct count of all bins).
   * @return {bin_minimum(index), bin_maximum(index), bin_height(index), bin_distinct_count(index)}
   */
  HistogramBin<T> bin(const BinID index) const;
```

File: src/lib/statistics/statistics_objects/abstract_histogram.hpp [hunk 152]
```diff
@@ -0,0 +1,256 @@
...
+   * This transformation is based on uint64_t.
+   */
+  using HistogramWidthType = std::conditional_t<std::is_same_v<T, pmr_string>, StringHistogramDomain::IntegralType, T>;
+
+  explicit AbstractHistogram(const HistogramDomain<T>& domain = {});
+
+  ~AbstractHistogram() override = default;
+
+  // Non-copyable
+  AbstractHistogram(AbstractHistogram&&) = default;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.hpp]: I recall Tim and me trying this and it didn't work. Now it works for some reason....

File: src/lib/statistics/statistics_objects/abstract_histogram.hpp (hunk 143 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.hpp]: but the non-public functions do not do anything for "people", they are *internal*? But lest we argue more, I added a comment:

```c++

  /**
   * Helper for implementing, e.g., LessThan as an inversion of GreaterThanEquals. 
   * @return total_[distinct_]count() - estimate 
   */
  Cardinality _invert_estimate(const Cardinality& estimate) const;
  std::pair<Cardinality, DistinctCount> _invert_estimate(const std::pair<Cardinality, DistinctCount>& estimate) const;
```

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 76 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: killed

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 77 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: killed.

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 79 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: killed.

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 78 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: Made public for testing with the clear comment that one probably shouldn't be using this function

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 89 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: _next_bin_for_value can return INVALID_BIN_ID for LessThan, for GreaterThanEquals, this is already handled by does_not_contain, e.g.

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 95 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: Wrong message, is now "Bin minimum must be <= bin maximum"

File: src/lib/statistics/statistics_objects/counting_quotient_filter.cpp [hunk 153]
```diff
@@ -126,6 +123,34 @@ bool CountingQuotientFilter<ElementType>::is_full() const {
...
+template <typename ElementType>
+Cardinality CountingQuotientFilter<ElementType>::estimate_cardinality(
+    const PredicateCondition predicate_condition, const AllTypeVariant& variant_value,
+    const std::optional<AllTypeVariant>& variant_value2) const {
+  if (predicate_condition == PredicateCondition::Equals) {
+    if (does_not_contain(variant_value)) return 0;
+    return static_cast<Cardinality>(count(variant_value));
+  } else {
+    // Cannot use CQFs for cardinality estimation beyond equality predicates
+    return 0;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/counting_quotient_filter.cpp]: selectivity of 1 should be default, this 0 was misplaced here. Sadly we cannot make that a constant across statistics object, since it requires a member function call
```c++

    // Cannot use CQFs for cardinality estimation beyond equality predicates
    return static_cast<Cardinality>(count(variant_value));
```

File: src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp [hunk 154]
```diff
@@ -0,0 +1,223 @@
...
+#include "generic_histogram.hpp"
+#include "resolve_type.hpp"
+#include "storage/segment_iterate.hpp"
+
+namespace {
+
+using namespace opossum;  // NOLINT
+
+template <typename T>
+std::unordered_map<T, HistogramCountType> value_distribution_from_segment_impl(
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp]: no particular reason, removed.

File: src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp [hunk 155]
```diff
@@ -0,0 +1,223 @@
...
+    const BaseSegment& segment, std::unordered_map<T, HistogramCountType> value_distribution,
+    const HistogramDomain<T>& domain) {
+  segment_iterate<T>(segment, [&](const auto& iterator_value) {
+    if (!iterator_value.is_null()) {
+      if constexpr (std::is_same_v<T, pmr_string>) {
+        if (domain.contains(iterator_value.value())) {
+          ++value_distribution[iterator_value.value()];
+        } else {
+          ++value_distribution[domain.string_to_domain(iterator_value.value())];
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp]: Added comment 
```c++
// Do "contains()" check first to avoid the string copy incurred by string_to_domain() if we can
```

File: src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp [hunk 156]
```diff
@@ -0,0 +1,223 @@
...
+  });
+
+  return value_distribution;
+}
+
+template <typename T>
+std::vector<std::pair<T, HistogramCountType>> value_distribution_from_column(const Table& table,
+                                                                             const ColumnID column_id,
+                                                                             const HistogramDomain<T>& domain) {
+  std::unordered_map<T, HistogramCountType> value_distribution_map;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp]: but to what value? Would be hacky whatever we choose, I'd not do it and rather focus on more efficient distinct count estimation (HyperLogLog) later.

File: src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp [hunk 157]
```diff
@@ -0,0 +1,223 @@
...
+
+  for (const auto& chunk : table.chunks()) {
+    value_distribution_map = value_distribution_from_segment_impl<T>(*chunk->get_segment(column_id),
+                                                                     std::move(value_distribution_map), domain);
+  }
+
+  auto value_distribution =
+      std::vector<std::pair<T, HistogramCountType>>{value_distribution_map.begin(), value_distribution_map.end()};
+  std::sort(value_distribution.begin(), value_distribution.end(),
+            [&](const auto& l, const auto& r) { return l.first < r.first; });
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp]: Benchmarked this once and it was, wouldn't want to do it again. "Proper" optimization for this will need to come from HyperLogLog, I guess.

File: src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp [hunk 158]
```diff
@@ -0,0 +1,223 @@
...
+                 bin_count_with_extra_value}) {
+  Assert(_bin_data.bin_minima.size() == _bin_data.bin_maxima.size(),
+         "Must have the same number of lower as upper bin edges.");
+  Assert(_bin_data.bin_minima.size() == _bin_data.bin_heights.size(),
+         "Must have the same number of edges and heights.");
+  Assert(_bin_data.distinct_count_per_bin > 0, "Cannot have bins with no distinct values.");
+  Assert(_bin_data.bin_count_with_extra_value < _bin_data.bin_minima.size(),
+         "Cannot have more bins with extra value than bins.");
+
+  AbstractHistogram<T>::_assert_bin_validity();
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp]: if it's a template and we're accessing one of its members, right?

File: src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp [hunk 159]
```diff
@@ -0,0 +1,223 @@
...
+
+  auto value_distribution = value_distribution_from_column(table, column_id, domain);
+
+  if (value_distribution.empty()) {
+    return nullptr;
+  }
+
+  auto bins = EqualDistinctCountHistogram<T>::_build_bins(std::move(value_distribution), max_bin_count);
+
+  return std::make_shared<EqualDistinctCountHistogram<T>>(std::move(bins.bin_minima), std::move(bins.bin_maxima),
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp]: lol, legacy, I believe. Removed it. Slowly but steadily, the whole Histogram code get's simpler

File: src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp [hunk 160]
```diff
@@ -0,0 +1,223 @@
...
+  return "EqualDistinctCount";
+}
+
+template <typename T>
+std::shared_ptr<AbstractHistogram<T>> EqualDistinctCountHistogram<T>::clone() const {
+  auto bin_minima = _bin_data.bin_minima;
+  auto bin_maxima = _bin_data.bin_maxima;
+  auto bin_heights = _bin_data.bin_heights;
+
+  return std::make_shared<EqualDistinctCountHistogram<T>>(std::move(bin_minima), std::move(bin_maxima),
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp]: Since EqualDistinctCountHistogram::EqualDistinctCountHistogram() takes an rvalue ref, clang says no.
image

File: src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp [hunk 161]
```diff
@@ -0,0 +1,223 @@
...
+                                                          _bin_data.bin_count_with_extra_value);
+}
+
+template <typename T>
+BinID EqualDistinctCountHistogram<T>::bin_count() const {
+  return _bin_data.bin_heights.size();
+}
+
+template <typename T>
+BinID EqualDistinctCountHistogram<T>::_bin_for_value(const T& value) const {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp]: Negative, EqualWidthHistograms wouldn't need the binary search and could jump directly to the correct bin, e.g.

File: src/lib/statistics/statistics_objects/generic_histogram.cpp [hunk 162]
```diff
@@ -0,0 +1,117 @@
...
+
+template <typename T>
+HistogramCountType GenericHistogram<T>::bin_distinct_count(const BinID index) const {
+  DebugAssert(index < _bin_data.bin_distinct_counts.size(), "Index is not a valid bin.");
+  return _bin_data.bin_distinct_counts[index];
+}
+
+template <typename T>
+HistogramCountType GenericHistogram<T>::total_count() const {
+  return std::accumulate(_bin_data.bin_heights.cbegin(), _bin_data.bin_heights.cend(), HistogramCountType{0});
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/generic_histogram.cpp]: Now computed in constructor and cached in member variable

File: src/lib/statistics/statistics_objects/generic_histogram.hpp [hunk 163]
```diff
@@ -0,0 +1,77 @@
...
+#include "abstract_histogram.hpp"
+#include "types.hpp"
+
+namespace opossum {
+
+/**
+ * We use multiple vectors rather than a vector of structs for ease-of-use with STL library functions.
+ */
+template <typename T>
+struct GenericBinData {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/generic_histogram.hpp]: legacy, and agreed. removed.

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 164]
```diff
@@ -0,0 +1,1035 @@
...
+  // [5.1, 5.2] is 0.1
+
+  if constexpr (std::is_same_v<T, pmr_string>) {
+    const auto repr_min = _domain.string_to_number(bin_minimum(index));
+    const auto repr_max = _domain.string_to_number(bin_maximum(index));
+    return repr_max - repr_min + 1u;
+  } else if constexpr (std::is_floating_point_v<T>) {
+    return bin_maximum(index) - bin_minimum(index);
+  } else {
+    return _domain.next_value(bin_maximum(index) - bin_minimum(index));
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: Oh, that was convoluted. Changed to 
```c++
    // The width of a integral-histogram bin [4,5] is 5 - 4 + 1 = 2
    return bin_maximum(index) - bin_minimum(index) + 1;
```

File: src/lib/statistics/statistics_objects/histogram_domain.hpp [hunk 165]
```diff
@@ -0,0 +1,105 @@
...
+ */
+
+template <typename T, typename Enable = void>
+class HistogramDomain {};
+
+template <typename T>
+class HistogramDomain<T, std::enable_if_t<std::is_integral_v<T>>> {
+ public:
+  T next_value(T v) const {
+    if (v == std::numeric_limits<T>::max()) return v;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/histogram_domain.hpp]: Renamed to `next_value_clamped` and doc'ed with 

```c++
 * HistogramDomain<T> is a template specialized for integral types, floating point types, and strings respectively.
 * It provides a function `next_value_clamped()` for all three type categories and `previous_value_clamped()`
 * for arithmetic types.
 * The functions are "clamped" simply because, e.g. there is no next value for INT_MAX in the domain of integers. As
 * histograms are only used for estimations (and not for pruning decisions), this is acceptable.
```

File: src/lib/statistics/statistics_objects/histogram_domain.hpp [hunk 166]
```diff
@@ -0,0 +1,105 @@
...
+    return v + 1;
+  }
+
+  T previous_value(T v) const {
+    if (v == std::numeric_limits<T>::min()) return v;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/histogram_domain.hpp]: https://github.com/hyrise/hyrise/pull/1489#discussion_r290471062

File: src/test/statistics/statistics_objects/generic_histogram_test.cpp [hunk 167]
```diff
@@ -0,0 +1,902 @@
+#include <limits>
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/test/statistics/statistics_objects/generic_histogram_test.cpp]: does_not_contain was made public and is tested now. Are there other "things" that you cannot find tests for? 

Excuse my fingerpointing, but what is it with this newfound affection for doc'ing and testing internal functions? The TableScan internals, most of these `_scan_non_reference_segment`, `_simd_scan_with_iterators`, `_scan_generic_segment`, functions lack both doc and dedicated tests - and are iirc your creation.

File: src/lib/statistics/statistics_objects/histogram_domain.hpp [hunk 168]
```diff
@@ -0,0 +1,105 @@
...
+  /**
+   * @return a numerical representation of @param string_value. Not that only the first prefix_length are considered and
+   *         that each character of @param string_value is capped by [min_char, max_char]
+   */
+  IntegralType string_to_number(const pmr_string& string_value) const;
+
+  /**
+   * @return a copy of @param string_value with all characters capped by [min_char, max_char]
+   */
+  pmr_string string_to_domain(const pmr_string& string_value) const;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/histogram_domain.hpp]: Discussed in person. Choosing the domain to "represent all characters seen in the input" would require a prepass over the column and doesn't help. Extending the character range for some obscure characters would shorten the maximum possible prefix length noticeably.

File: src/lib/statistics/statistics_objects/min_max_filter.hpp (hunk 99 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/min_max_filter.hpp]: I thought statistics objects used for chunk pruning carry the suffix "filter" short for "pruning filter". Right @Bouncner

File: src/lib/statistics/statistics_objects/null_value_ratio_statistics.hpp (hunk 100 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/null_value_ratio_statistics.hpp]: "null ratio" was used in only three places and I changed it to "null value ratio" there. We have `ValueSegment::_values` and `ValueSegment::_null_values` and use the same naming scheme elsewhere, too. So I think its appropriate to talk about a "null value ratio"

File: src/lib/statistics/statistics_objects/min_max_filter.hpp (hunk 99 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/min_max_filter.hpp]: legacy. I wouldn't want to work on the pruning filters - which were mostly just copied into a different folder - in this PR

File: src/lib/statistics/statistics_objects/histogram_domain.cpp (hunk 108 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/histogram_domain.cpp]: As discussed, the emoji is previously clamped to the supported character range. renamed the parameter to "string_in_domain" and dc'ed it.

File: src/lib/statistics/statistics_objects/abstract_histogram.hpp (hunk 145 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.hpp]: I'll leave it as it is if there are no strong feelings.

File: src/lib/statistics/statistics_objects/histogram_domain.hpp [hunk 169]
```diff
@@ -0,0 +1,105 @@
...
+  pmr_string next_value(const pmr_string& string_value) const;
+
+  bool operator==(const HistogramDomain& rhs) const;
+
+  char min_char{};
+  char max_char{};
+  size_t prefix_length;
+
+ private:
+  IntegralType _base_number() const;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/histogram_domain.hpp]: I doc'ed this with 
```c++

  // For a prefix length of 4 and a character range width of 26 this returns `26^3 + 26^2 + 26^1 + 26^0`. This is the
  // base number used for transforming strings into integral values. The base number is the "weight" of the first
  // character in the string. The second character has the weight `26^2 + 26^1 + 26^0` and so forth.
  IntegralType _base_number() const;
```

File: src/lib/statistics/statistics_objects/histogram_domain.cpp [hunk 170]
```diff
@@ -0,0 +1,133 @@
+#include "histogram_domain.hpp"
+
+#include "utils/assert.hpp"
+
+namespace opossum {
+
+HistogramDomain<pmr_string>::HistogramDomain()
+    :  // Support most of ASCII with maximum prefix length for number of characters.
+      HistogramDomain<pmr_string>(' ', '~', 9) {}
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/histogram_domain.cpp]: Adjusted comment to
```c++
    :  // Support most of ASCII with maximum prefix length for number of characters. The character range and the prefix
      // length were chosen so that the entire range of IntegralType is covered
```

File: src/lib/statistics/statistics_objects/histogram_domain.cpp (hunk 97 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/histogram_domain.cpp]: Renamed to "value_clipped_to_prefix_length"

File: src/lib/statistics/table_statistics.cpp (hunk 117 above)
Comment (mrzzzrm) [reply src/lib/statistics/table_statistics.cpp]: Doc'ed with
```c++

  /**
   * Determine bin count, within mostly arbitrarily chose bounds: 5 (for tables with <=2k rows) up to 100 bins 
   * (for tables with >= 200m rows) are created. 
   */
  const auto histogram_bin_count = std::min<size_t>(100, std::max<size_t>(5, table.row_count() / 2'000));
```

File: src/lib/statistics/table_statistics.cpp (hunk 119 above)
Comment (mrzzzrm) [reply src/lib/statistics/table_statistics.cpp]: This is 1:1 copied from your encoding threading which also performs per column work.

File: src/lib/statistics/table_statistics.cpp (hunk 118 above)
Comment (mrzzzrm) [reply src/lib/statistics/table_statistics.cpp]: no :(

File: src/lib/statistics/table_statistics.cpp (hunk 119 above)
Comment (mrzzzrm) [reply src/lib/statistics/table_statistics.cpp]: Added
```

  /**
   * Paralelly create statistics objects for the Table's columns
   */
```

File: src/lib/statistics/table_statistics.hpp (hunk 123 above)
Comment (mrzzzrm) [reply src/lib/statistics/table_statistics.hpp]:
```c++

  /**
   * Currently, we generate EqualDistinctCountHistograms for all columns and determine their null value ratio.
   * Histograms are used because they are currently our best option to estimate predicate and join cardinalities during
   * optimization.
   */
  static std::shared_ptr<TableStatistics> from_table(const Table& table);

```

File: src/lib/statistics/statistics_objects/single_bin_histogram.hpp (hunk 116 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/single_bin_histogram.hpp]: Was great for less typing in tests, I introduced `GenericHistogram::with_single_bin` which provides the same convenience and removed SingleBinHistogram

File: src/lib/statistics/table_statistics.cpp (hunk 118 above)
Comment (mrzzzrm) [reply src/lib/statistics/table_statistics.cpp]: next_column_id is an atomic size_t

**Comment by mrzzzrm** [comment]
I think I am through with your comments - I have skipped the MinMaxFilter and the RangeFilter, though. Those were just copied to a different folder and I don't think it falls into the scope of this PR to alter them.

File: src/lib/statistics/table_statistics.cpp (hunk 122 above)
Comment (mrzzzrm) [reply src/lib/statistics/table_statistics.cpp]: As the comment states "But the alternative would be a full segment scan". This Assert would be pretty awkward to type.

People need to be very careful with pruning ;)

File: src/lib/statistics/table_statistics.cpp (hunk 119 above)
Comment (mrks) [reply src/lib/statistics/table_statistics.cpp]: How about this (looking at benchmark_table_encoder.cpp):

```
      while (next_chunk + 1 < table->chunk_count()) {
        auto my_chunk = next_chunk++;
```

That seems to make the intent much clearer. No idea how the `while(true)` made it in back then.

File: src/lib/statistics/table_statistics.cpp (hunk 117 above)
Comment (mrks) [reply src/lib/statistics/table_statistics.cpp]: "chosen"?

File: src/test/statistics/statistics_objects/generic_histogram_test.cpp (hunk 167 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/test/statistics/statistics_objects/generic_histogram_test.cpp]: Documenting and testing internal functions are two different things. For the first, I find that it makes it easier to understand existing code. When reading the main method, it is helpful to have a quick summary of the helper methods that are called. Sure, for methods that span only a couple of lines, it's easy to read them, but still increases the complexity.

With testing, I don't think that every private method needs to be tested by itself. This one came up because I had a hard time finding which tests cover this.

It is hard to draw a precise line here. In cases where adding comments and/or tests would be a significant effort, I am more than willing to reconsider the PR comment. If existing code lacks comments and/or tests, feel free to open an issue for it. The fact that it's in the code base does not mean that it's perfect; no matter who wrote it.

File: src/lib/statistics/generate_pruning_statistics.cpp (hunk 125 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/statistics/generate_pruning_statistics.cpp]: Sounds good.

File: src/lib/statistics/join_graph_statistics_cache.hpp (hunk 129 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/statistics/join_graph_statistics_cache.hpp]: Starting to understand it. Are there invalid bitmasks (where a predicate is included but the corresponding vertices are not)?

File: src/lib/statistics/join_graph_statistics_cache.hpp (hunk 131 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/statistics/join_graph_statistics_cache.hpp]: Simply add that sentence?

File: src/lib/statistics/join_graph_statistics_cache.hpp (hunk 129 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/statistics/join_graph_statistics_cache.hpp]: Maybe add that this is a unique identifier of <...>, not a hash. That would have helped me quite a bit.

File: src/lib/statistics/join_graph_statistics_cache.hpp (hunk 132 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/statistics/join_graph_statistics_cache.hpp]: I always imagined the bitmask as some type of hash. See above.

**Comment by mrks** [comment]
I went over the comments, which mostly seem resolved. I'll do a hopefully last pass later today.

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 94 above)
Comment (mrks) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: ping

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 90 above)
Comment (mrks) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: We can also discuss this in person and see if anything about this comment can be improved.

File: src/lib/statistics/join_graph_statistics_cache.hpp (hunk 129 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/join_graph_statistics_cache.hpp]: I probably have tunnel vision by now, I don't see what the comment leaves open. However, I extended it.

```c++
  // One bit for each of JoinGraph's vertices followed by one bit for each predicate. Represents a subgraph of a
  // JoinGraph. "1" means that the vertex/predicate is included in the subgraph.
  // A Bitmask is a unique identifier for a subplan of a JoinGraph (not a hash). If the bit for a predicate 
  // `V1.a = V2.a` is set the bits for `V1` and `V2` need to be set as well.
  using Bitmask = boost::dynamic_bitset<>;
```

File: src/lib/statistics/join_graph_statistics_cache.hpp (hunk 131 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/join_graph_statistics_cache.hpp]:
```c++
  /**
   * Try to build a bitmask (aka cache key) from an LQP. This will either return the bitmask or std::nullopt, if
   * Predicates or Vertices not registered in _vertex_indices and _predicate_indices are encountered. The latter can be
   * the case if `lqp` is a suplan of a vertex node.
   */
  std::optional<Bitmask> bitmask(const std::shared_ptr<AbstractLQPNode>& lqp) const;
```

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 90 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: First measure, I extended the doc of the function:
```c++
  /**
   * Derive a Histogram from this histograms splitting its bins so that both the current bounds as well as the bounds
   * specified in @param additional_bin_edges are present.
   * 
   * E.g., for a histogram with bins {[0, 10], [15, 20]}, split_at_bin_bounds({{-4, 5}, {16, 18}}) returns 
   * a histogram with bins {[0, 5], [6, 10], [15, 15], [16, 18], [19, 20]}
   * 
   * @param additional_bin_edges    Pair of minima and maxima of new bins
   */
  std::shared_ptr<AbstractHistogram<T>> split_at_bin_bounds(
      const std::vector<std::pair<T, T>>& additional_bin_edges) const;

```

Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: Also, I heavily rewrote the comments in the function and added examples. 

It is kind of hacky, I admit it, but Tim assured me it was pretty hard to cover all edge cases, so I am glad we have a solution that works at all.

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 94 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: Should hopefully be addressed by https://github.com/hyrise/hyrise/pull/1489#discussion_r291065394

File: src/lib/statistics/table_statistics.cpp (hunk 119 above)
Comment (mrzzzrm) [reply src/lib/statistics/table_statistics.cpp]: that alone is not thread-safe, we still need the `if (my_chunk >= table->chunk_count()) return;` check. And then we might just as well make it "while(true)" because the loop condition you proposed would essentially be pointless?

File: src/lib/statistics/table_statistics.cpp (hunk 117 above)
Comment (mrzzzrm) [reply src/lib/statistics/table_statistics.cpp]: bloody wireless keyboard swallowing chars....

File: src/lib/statistics/generate_pruning_statistics.cpp (hunk 125 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/generate_pruning_statistics.cpp]: Renamed. Variables of this type are called "column_statistics" in cardinality estimation contexts and "segment_statistics" in chunk pruning contexts

**Comment by mrzzzrm** [comment]
All currently open comments should be addressed

File: src/lib/statistics/cardinality_estimator.cpp [hunk 171]
```diff
@@ -0,0 +1,911 @@
...
+        predicate.predicate_condition == PredicateCondition::IsNotNull) {
+      const auto is_not_null = predicate.predicate_condition == PredicateCondition::IsNotNull;
+
+      const auto null_value_ratio =
+          estimate_null_value_ratio_of_column(*input_table_statistics, *left_input_column_statistics);
+
+      if (null_value_ratio) {
+        selectivity = is_not_null ? 1 - *null_value_ratio : *null_value_ratio;
+
+        // All that remains of the column we scanned on are NULL values
```
Comment (mrks) [inline src/lib/statistics/cardinality_estimator.cpp]: \+ `(non-)`

File: src/lib/statistics/cardinality_estimator.cpp [hunk 172]
```diff
@@ -0,0 +1,911 @@
...
+        const auto column_statistics = std::make_shared<AttributeStatistics<ColumnDataType>>();
+        column_statistics->null_value_ratio = std::make_shared<NullValueRatioStatistics>(is_not_null ? 0.0f : 1.0f);
+        output_column_statistics[left_column_id] = column_statistics;
+      } else {
+        // If there is no null-value ratio available, assume a selectivity of 1, for both IS NULL and IS NOT NULL, as no
+        // magic number makes real sense here.
+        selectivity = 1.0f;
```
Comment (mrks) [inline src/lib/statistics/cardinality_estimator.cpp]: Any reason you are not returning here?

File: src/lib/statistics/cardinality_estimator.cpp [hunk 173]
```diff
@@ -0,0 +1,911 @@
...
+          // right and wrong here. In some examples, this seemed like a good guess ¯\_(ツ)_/¯
+          selectivity = 0.9f;
+          return;
+        }
+
+        auto value2_variant = std::optional<AllTypeVariant>{};
+        if (predicate.value2) {
+          if (predicate.value2->type() != typeid(AllTypeVariant)) {
+            selectivity = 1.0f;
+            return;
```
Comment (mrks) [inline src/lib/statistics/cardinality_estimator.cpp]: Sometimes you return for `selectivity = ...`, sometimes you don't. Can we make this consistent?

File: src/lib/statistics/cardinality_estimator.cpp [hunk 174]
```diff
@@ -0,0 +1,911 @@
...
+
+      } else {
+        /**
+         * Estimate ColumnVsValue
+         */
+
+        Assert(predicate.value.type() == typeid(AllTypeVariant), "Expected AllTypeVariant");
+
+        // TODO(anybody) For (NOT) LIKE predicates that start with a wildcard, Histograms won't yield reasonable
+        //               results. Assume a magic selectivity for now
```
Comment (mrks) [inline src/lib/statistics/cardinality_estimator.cpp]: I don't see this "start with a wildcard" part here. Any chance the comments here are out-of-date?

File: src/lib/statistics/cardinality_estimator.cpp [hunk 175]
```diff
@@ -0,0 +1,911 @@
...
+          }
+
+          value2_variant = boost::get<AllTypeVariant>(*predicate.value2);
+        }
+
+        const auto sliced_statistics_object = scan_statistics_object->sliced(
+            predicate.predicate_condition, boost::get<AllTypeVariant>(predicate.value), value2_variant);
+
+        if (!sliced_statistics_object) {
+          selectivity = 0.0f;
```
Comment (mrks) [inline src/lib/statistics/cardinality_estimator.cpp]: Why is this 0 while row 585 returns 1? Aren't these two cases where we don't know what to do? I'd still like for "dunno" to be coded more specifically.

File: src/lib/statistics/cardinality_estimator.cpp [hunk 176]
```diff
@@ -0,0 +1,911 @@
...
+
+    output_table_statistics = std::make_shared<TableStatistics>(std::move(column_statistics), cardinality);
+  });
+
+  return output_table_statistics;
+}
+
+std::shared_ptr<TableStatistics> CardinalityEstimator::estimate_cross_join(
+    const TableStatistics& left_input_table_statistics, const TableStatistics& right_input_table_statistics) {
+  // Every tuple from the left side get's emitted once for each tuple on the right side - and vice versa
```
Comment (mrks) [inline src/lib/statistics/cardinality_estimator.cpp]: gets

File: src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp [hunk 177]
```diff
@@ -0,0 +1,220 @@
...
+
+  // Split values evenly among bins.
+  const auto distinct_count_per_bin = static_cast<size_t>(value_distribution.size() / bin_count);
+  const BinID bin_count_with_extra_value = value_distribution.size() % bin_count;
+
+  std::vector<T> bin_minima(bin_count);
+  std::vector<T> bin_maxima(bin_count);
+  std::vector<HistogramCountType> bin_heights(bin_count);
+
+  auto current_bin_begin_index = BinID{0};
```
Comment (mrks) [inline src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp]: Add a comment that `_index` means index into the list of distinct values? That took me some time to figure out.

File: src/lib/cost_estimation/abstract_cost_estimator.cpp [hunk 178]
```diff
@@ -0,0 +1,105 @@
...
+    const auto current_node = bfs_queue.front();
+    bfs_queue.pop();
+
+    const auto visited_iter = visited.find(current_node);
+    if (visited_iter != visited.end()) {
+      continue;
+    }
+    visited.emplace(current_node);
+
+    const auto cached_cost = _get_subplan_cost_from_cache(current_node, visited);
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/cost_estimation/abstract_cost_estimator.cpp]: I hope this explains it somewhat:

```c++
    // Not every visited node has a cached cost. Costs are only cached for the roots of the plans for which 
    // `AbstractCostEstimator::estimate_plan_cost()` is called. For subplans below the root, costs cannot be cached
    // because their costs are never aggregated due to the traversal being a BFS.
```

File: src/lib/cost_estimation/abstract_cost_estimator.hpp [hunk 179]
```diff
@@ -0,0 +1,66 @@
...
+ * Base class of an algorithm that predicts Cost for operators and plans.
+ */
+class AbstractCostEstimator {
+ public:
+  explicit AbstractCostEstimator(const std::shared_ptr<AbstractCardinalityEstimator>& cardinality_estimator);
+  virtual ~AbstractCostEstimator() = default;
+
+  /**
+   * Estimate the Cost of a (sub-)plan.
+   * If `cost_estimation_by_lqp_cache` is enabled:
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/cost_estimation/abstract_cost_estimator.hpp]: I extended this do read: `// If 'cost_estimation_by_lqp_cache' is enabled by calling 'guarantee_bottom_up_construction()':`

File: src/lib/cost_estimation/cost_estimator_logical.cpp [hunk 180]
```diff
@@ -1,20 +1,26 @@
...
+std::shared_ptr<AbstractCostEstimator> CostEstimatorLogical::new_instance() const {
+  return std::make_shared<CostEstimatorLogical>(cardinality_estimator->new_instance());
+}
+
+Cost CostEstimatorLogical::estimate_node_cost(const std::shared_ptr<AbstractLQPNode>& node) const {
+  const auto output_row_count = cardinality_estimator->estimate_cardinality(node);
+  const auto left_input_row_count =
+      node->left_input() ? cardinality_estimator->estimate_cardinality(node->left_input()) : 0.0f;
+  const auto right_input_row_count =
+      node->right_input() ? cardinality_estimator->estimate_cardinality(node->right_input()) : 0.0f;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/cost_estimation/cost_estimator_logical.cpp]: If `node->right_input()` is nullptr, then `right_input_row_count` is/should not be used in the rest of the function if the LQP is valid. std::optional would be an option, but more typing and error handling. NaN would be more correct, but still a lot of typing. 0.0f is not incorrect, and the least amount of typing. I'd leave it at 0.0f.

File: src/lib/optimizer/strategy/chunk_pruning_rule.cpp [hunk 181]
```diff
@@ -81,12 +82,12 @@ void ChunkPruningRule::apply_to(const std::shared_ptr<AbstractLQPNode>& node) co
...
 
 std::set<ChunkID> ChunkPruningRule::_compute_exclude_list(
-    const std::vector<std::shared_ptr<ChunkStatistics>>& statistics, const AbstractExpression& predicate,
+    const Table& table, const AbstractExpression& predicate,
     const std::shared_ptr<StoredTableNode>& stored_table_node) const {
   // Hacky:
-  // `statistics` contains SegmentStatistics for all columns, even those that are pruned in `stored_table_node`.
-  // To be able to build a OperatorScanPredicate that contains a ColumnID referring to the correct SegmentStatistics in
-  // `statistics`, we create a clone of `stored_table_node` without the pruning info.
+  // `statistics` contains AttributeStatistics for all columns, even those that are pruned in `stored_table_node`.
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/strategy/chunk_pruning_rule.cpp]: Changed to `table->table_statistics()`

File: src/lib/static_variant_cast.hpp [hunk 182]
```diff
@@ -0,0 +1,50 @@
...
+#include <type_traits>
+
+#include "boost/variant.hpp"
+
+#include "resolve_type.hpp"
+
+namespace opossum {
+
+template <typename Target>
+std::optional<Target> static_variant_cast(const AllTypeVariant& source) {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/static_variant_cast.hpp]:
```c++
/**
 * Contrary to the functions in lossless_cast.hpp, converts from an AllTypeVariant to any target, even if accuracy/data
 * is lost by the conversion.
 *
 * Use this function only in contexts where (query-)result accuracy is not affected (e.g., statistics/estimations)
 *
 * If @param source is NULL, return std::nullopt
 * If @param source is a string, perform a boost::lexical_cast<>
 * If @param source is arithmetic, perform a static_cast<>, clamping the returned value at
 *                                 `std::numeric_limits<Target>::min()/max()` to avoid undefined behaviour.
 */
template <typename Target>
std::optional<Target> static_variant_cast(const AllTypeVariant& source) {
```

and

```c++

/**
 * Same as `static_variant_cast()`, only that this variant Assert()s that @param source is not NULL
 */
template <typename Target>
Target non_null_static_variant_cast(const AllTypeVariant& source) {
```

File: src/lib/cost_estimation/cost_estimator_logical.cpp (hunk 180 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/cost_estimation/cost_estimator_logical.cpp]: ok

File: src/lib/static_variant_cast.hpp (hunk 182 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/static_variant_cast.hpp]: One more thought: Should we call this `lossy_variant_cast`? I worry that `static_...` does not generate enough attention when reading it somewhere else.

[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/static_variant_cast.hpp]: Good idea. And I removed/inlined non_null_static_variant_cast because it was only used once

[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/static_variant_cast.hpp]: Upsi, they are now, in `LossyCastTest`

File: src/lib/statistics/attribute_statistics.cpp [hunk 183]
```diff
@@ -0,0 +1,113 @@
...
+  if (min_max_filter) {
+    statistics->set_statistics_object(min_max_filter->scaled(selectivity));
+  }
+
+  if (counting_quotient_filter) {
+    statistics->set_statistics_object(counting_quotient_filter->scaled(selectivity));
+  }
+
+  if constexpr (std::is_arithmetic_v<
+                    T>) {  // NOLINT clang-tidy is crazy and sees a "potentially unintended semicolon" here...
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/attribute_statistics.cpp]: In another file - and now here as well. I grepped for if constexpr and didn't find any more places where this was broken.

File: src/lib/statistics/base_attribute_statistics.hpp [hunk 184]
```diff
@@ -0,0 +1,48 @@
...
+#include "all_type_variant.hpp"
+
+namespace opossum {
+
+class AbstractStatisticsObject;
+enum class PredicateCondition;
+
+/**
+ * Base class for AttributeStatistics<T>.
+ * Statistically represents a Column (i.e. covers all Segments with the same ColumnID over all Chunks of a Table).
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/base_attribute_statistics.hpp]: Copied over the docs from AttributeStatistics and made the docs of AttributeStatistics read
```c++
/**
 * For docs, see BaseAttributeStatistics
 */
```

File: src/lib/statistics/cardinality_estimator.cpp [hunk 185]
```diff
@@ -0,0 +1,911 @@
...
+
+std::shared_ptr<TableStatistics> CardinalityEstimator::estimate_validate_node(
+    const ValidateNode& validate_node, const std::shared_ptr<TableStatistics>& input_table_statistics) {
+  // Currently no statistics available to base ValidateNode on
+  return input_table_statistics;
+}
+
+std::shared_ptr<TableStatistics> CardinalityEstimator::estimate_predicate_node(
+    const PredicateNode& predicate_node, const std::shared_ptr<TableStatistics>& input_table_statistics) {
+  // For PredicateNodes, the statistics of the columns scanned on are sliced and all other columns statistics' are
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: I thought this is how you do English when you want to express ownership of a word ending with "s":

[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: "Rule 2: To show plural possession of a word ending in an s or s sound, form the plural first; then immediately use the apostrophe." 
https://data.grammarbook.com/blog/apostrophes/apostrophes-with-words-ending-in-s/

[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: I'm not very good at doing the English, so I might be wrong.

File: src/lib/statistics/cardinality_estimator.cpp [hunk 186]
```diff
@@ -0,0 +1,911 @@
...
+
+    if (primary_operator_join_predicate) {
+      switch (join_node.join_mode) {
+        case JoinMode::Semi:
+        case JoinMode::AntiNullAsTrue:
+        case JoinMode::AntiNullAsFalse:
+          // TODO(anybody) Implement estimation of Semi/Anti joins
+          return left_input_table_statistics;
+
+        // TODO(anybody) For now, handle outer joins just as inner joins
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]:
```c++
        // For now, handle outer joins just as inner joins
        // TODO(anybody) Handle them more accurately, i.e., estimate how many tuples don't find matches.
```

[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: bloody comments not having a test suite...
```c++
  // For inner-equi JoinNodes, an principle-of-inclusion algorithm is used.
  // The same algorithm is used for outer-equi JoinNodes, lacking a better alternative at the moment.
  // All other join modes and predicate conditions are treated as cross joins for now.
```

File: src/lib/statistics/cardinality_estimator.cpp [hunk 187]
```diff
@@ -0,0 +1,911 @@
...
+  const auto row_count = Cardinality{left_input_table_statistics->row_count + right_input_table_statistics->row_count};
+
+  const auto output_table_statistics = std::make_shared<TableStatistics>(std::move(column_statistics), row_count);
+
+  return output_table_statistics;
+}
+
+std::shared_ptr<TableStatistics> CardinalityEstimator::estimate_limit_node(
+    const LimitNode& limit_node, const std::shared_ptr<TableStatistics>& input_table_statistics) {
+  // For LimitNodes with a value as limit_expression, create a TableStatistics object with that value as row_count.
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: we do now,

File: src/lib/statistics/cardinality_estimator.cpp (hunk 173 above)
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: Now returning for all cases where `scan_statistics_object->sliced()` should not be called.

File: src/lib/statistics/cardinality_estimator.cpp (hunk 172 above)
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: do now

File: src/lib/statistics/cardinality_estimator.cpp (hunk 174 above)
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: Todo was out of date, referred to code previously removed.

File: src/lib/statistics/cardinality_estimator.cpp (hunk 175 above)
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: Okay, let's go crazy. How about
```c++
// Constants used in places where a better estimation would be implementable, either with
// unavailable statistics objects or new algorithms, but wasn't warranted yet
constexpr auto PLACEHOLDER_SELECTIVITY_ONE = 1.0f
constexpr auto PLACEHOLDER_SELECTIVITY_ZERO = 1.0f
constexpr auto PLACEHOLDER_SELECTIVITY_LOW = 0.1f
constexpr auto PLACEHOLDER_SELECTIVITY_MEDIUM = 0.5f
constexpr auto PLACEHOLDER_SELECTIVITY_HIGH = 0.5f
```

File: src/lib/statistics/generate_pruning_statistics.cpp [hunk 188]
```diff
@@ -0,0 +1,94 @@
...
+  if (pruning_filter) {
+    segment_statistics.set_statistics_object(pruning_filter);
+  }
+}
+
+}  // namespace
+
+namespace opossum {
+
+void generate_chunk_pruning_statistics(const std::shared_ptr<Chunk>& chunk) {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/generate_pruning_statistics.cpp]: To avoid confusion, all variable names now use the term "pruning statistics". I am not really comfortable with "Filter" meaning "statistics object usable for pruning", but that's beyond this PR.

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 189]
```diff
@@ -0,0 +1,758 @@
...
+HistogramBin<T> AbstractHistogram<T>::bin(const BinID index) const {
+  return {bin_minimum(index), bin_maximum(index), bin_height(index), bin_distinct_count(index)};
+}
+
+template <typename T>
+typename AbstractHistogram<T>::HistogramWidthType AbstractHistogram<T>::bin_width(const BinID index) const {
+  DebugAssert(index < bin_count(), "Index is not a valid bin.");
+
+  // The width of an integer bin [5, 5] is 1, same for a string bin ["aa", "aa"], whereas the width of a float bin
+  // [5.1, 5.2] is 0.1
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: This is surprisingly hard to justify, I kept it relatively vague:

```
  // The width of an float bin [5.0, 7.0] is 2, as one would expect, but the width of an integer bin [5, 7] is 3. This
  // makes our math more correct in multiple places, makes sure a bin [5, 5] has a non-zero width which in turn makes
  // sure that the domain of a histograms can be continuous, i.e. there are no "gaps", even for integer histograms.
```

File: src/lib/static_variant_cast.hpp (hunk 182 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/static_variant_cast.hpp]: Sounds good

File: src/lib/statistics/cardinality_estimator.cpp (hunk 185 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/statistics/cardinality_estimator.cpp]: What is the thing being possessed here though? I feel like I’m missing something

File: src/lib/statistics/cardinality_estimator.cpp (hunk 175 above)
Comment (mrks) [reply src/lib/statistics/cardinality_estimator.cpp]: I’d use “all” and “none” instead of one and zero. Also it seems like you adjusted only half of those numbers (zero, high).

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 189 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: Sounds reasonable. I’d drop the “also” in the third line. You didn’t give a first reason before.

File: src/lib/statistics/cardinality_estimator.cpp (hunk 185 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: The statistics are possessed/associated by/with the column. 
"the statistics of the columns scanned on are sliced and all other columns statistics' are scaled"

I think that makes sense?

File: src/lib/statistics/cardinality_estimator.cpp (hunk 175 above)
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: Using these in all places where a magic selectivity constant was used before.

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 190]
```diff
@@ -0,0 +1,758 @@
...
+std::shared_ptr<AbstractStatisticsObject> AbstractHistogram<T>::sliced(
+    const PredicateCondition predicate_condition, const AllTypeVariant& variant_value,
+    const std::optional<AllTypeVariant>& variant_value2) const {
+  if (does_not_contain(predicate_condition, variant_value, variant_value2)) {
+    return nullptr;
+  }
+
+  const auto value = static_variant_cast<T>(variant_value);
+  if (!value) {
+    // variant_value is NULL and slicing with NULL is nothing we can do anything meaningful for.
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: Asserting now, the CardinalityEstimator returns a selectivity of 0 for `a = NULL` now, that's the right place to handle this.

File: src/lib/visualization/lqp_visualizer.cpp [hunk 191]
```diff
@@ -90,9 +94,9 @@ void LQPVisualizer::_build_dataflow(const std::shared_ptr<AbstractLQPNode>& from
 
   if (from->left_input()) {
     try {
-      float input_count = from->left_input()->get_statistics()->row_count();
+      float input_count = CardinalityEstimator{}.estimate_cardinality(from->left_input());
       if (from->right_input()) {
-        input_count *= from->right_input()->get_statistics()->row_count();
+        input_count *= CardinalityEstimator{}.estimate_cardinality(from->right_input());
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/visualization/lqp_visualizer.cpp]: oh dear, yes. well spotted

File: src/lib/statistics/table_statistics.hpp [hunk 192]
```diff
@@ -1,75 +1,44 @@
...
-  static constexpr auto DEFAULT_DISJUNCTION_SELECTIVITY = 0.2f;
-
-  TableStatistics(const TableType table_type, const float row_count,
-                  const std::vector<std::shared_ptr<const BaseColumnStatistics>>& column_statistics);
-  TableStatistics(const TableStatistics& table_statistics) = default;
-
   /**
-   * @defgroup Member access
-   * @{
+   * Currently, we generate EqualDistinctCountHistograms for all columns and determine their null value ratio.
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/table_statistics.hpp]:
```c++
  /**
   * Creates statistics objects for cardinality estimation for all Columns in @param table. See implementation for 
   * which statistics objects are created.
   */
  static std::shared_ptr<TableStatistics> from_table(const Table& table);

```

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp [hunk 193]
```diff
@@ -0,0 +1,758 @@
...
+    case PredicateCondition::LessThan: {
+      auto last_included_bin_id = _bin_for_value(*value);
+
+      if (last_included_bin_id == INVALID_BIN_ID) {
+        last_included_bin_id = _next_bin_for_value(*value);
+
+        if (last_included_bin_id == INVALID_BIN_ID) {
+          last_included_bin_id = bin_count() - 1;
+        } else {
+          last_included_bin_id = last_included_bin_id - 1;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: very much so. As always, I'd blame Tim

File: src/lib/statistics/statistics_objects/abstract_histogram.cpp (hunk 94 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/abstract_histogram.cpp]: That comment made no sense to me either... I removed it

File: src/lib/statistics/statistics_objects/equal_distinct_count_histogram.hpp [hunk 194]
```diff
@@ -0,0 +1,85 @@
...
+#include "abstract_histogram.hpp"
+#include "types.hpp"
+
+namespace opossum {
+
+class Table;
+
+/**
+ * Distinct-balanced histogram.
+ * Bins contain roughly the same number of distinct values actually occurring in the data.
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/equal_distinct_count_histogram.hpp]: Changed to

```
/**
 * Distinct-balanced histogram.
 * The first `bin_count_with_extra_value` contain each contain `distinct_count_per_bin + 1` distinct values,
 * all other bins contain `distinct_count_per_bin` distinct values.
 * There might be gaps between bins.
 */
```

File: src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp [hunk 195]
```diff
@@ -0,0 +1,220 @@
...
+  });
+
+  return value_distribution;
+}
+
+template <typename T>
+std::vector<std::pair<T, HistogramCountType>> value_distribution_from_column(const Table& table,
+                                                                             const ColumnID column_id,
+                                                                             const HistogramDomain<T>& domain) {
+  std::unordered_map<T, HistogramCountType> value_distribution_map;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp]: I took the liberty to just add that as a comment
```c++
  // TODO(anybody) If you want to look into performance, this would probably benefit greatly from monotonic buffer 
  //               resources.
  std::unordered_map<T, HistogramCountType> value_distribution_map;
```

File: src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp (hunk 177 above)
Comment (mrzzzrm) [reply src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp]: How about 

```c++
  // `bin_minimum_distinct_value_idx` and `bin_maximum_distinct_value_idx` are indices into `value_distribution`
  // describing which range of distinct values goes into a bin
  auto bin_minimum_distinct_value_idx = BinID{0};
  for (BinID bin_index = 0; bin_index < bin_count; bin_index++) {
    auto bin_maximum_distinct_value_idx = bin_minimum_distinct_value_idx + distinct_count_per_bin - 1;
```

**Comment by mrzzzrm** [comment]
Cannot find the original comment, but this is still required with clang 7:

```c++
  // NOLINTNEXTLINE clang-tidy is crazy and sees a "potentially unintended semicolon" here...
  if constexpr (std::is_arithmetic_v<T>) {
```

**Comment by mrzzzrm** [comment]
Otherwise, all comments should be commented on/addressed

File: src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp (hunk 177 above)
Comment (mrks) [reply src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp]: Maybe just `min_value_idx`? Also, is `BinID` the correct type here?

File: src/lib/statistics/cardinality_estimator.cpp (hunk 185 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/statistics/cardinality_estimator.cpp]: But if the other columns are the possessor and the statistics are the possessee, shouldn't it be "all other columns' statistics"?

File: src/lib/statistics/cardinality_estimator.cpp (hunk 175 above)
Comment (mrks) [reply src/lib/statistics/cardinality_estimator.cpp]: Except for line 589 (`selectivity = 0.0f;`)

**Comment by mrks** [comment]
Three things remain, which should not take more than 10 minutes in total:

https://github.com/hyrise/hyrise/pull/1489#discussion_r293727869
https://github.com/hyrise/hyrise/pull/1489#discussion_r294140402
https://github.com/hyrise/hyrise/pull/1489#discussion_r294140820

File: src/lib/statistics/cardinality_estimator.cpp (hunk 175 above)
Comment (mrks) [reply src/lib/statistics/cardinality_estimator.cpp]: Actually, there are a couple more. Better to grep for `selectivity = (0|1)`

File: src/lib/statistics/cardinality_estimator.cpp (hunk 185 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: I'm stupid, did I really write `columns statistics'`? Fixed.

File: src/lib/statistics/cardinality_estimator.cpp (hunk 175 above)
Comment (mrzzzrm) [reply src/lib/statistics/cardinality_estimator.cpp]: For those four instances of `selectivity = 0.0f`, 0.0f is actually the intended estimation and not a placeholder for "we do not really handle this predicate"

589, e.g. is doc'ed like this:

```c++
          // A predicate `<column> <condition> NULL` always has a selectivity of 0
          selectivity = 0.0f;
```

I'd not use the PLACEHOLDER_ constants for such cases, no?

**Comment by mrzzzrm** [comment]
Except for the `selectivity = 0.0f` discussion, those should be addressed now.

File: src/lib/statistics/cardinality_estimator.cpp (hunk 175 above)
Comment (mrks) [reply src/lib/statistics/cardinality_estimator.cpp]: Ok.

**Comment by mrks** [comment]
Hmpf. Any idea what happened here:

```
+----------------+----------------+------+----------------+------+------------+---------------------------------+
| Benchmark      | prev. iter/s   | runs | new iter/s     | runs | change [%] | p-value (significant if <0.001) |
+----------------+----------------+------+----------------+------+------------+---------------------------------+
| TPC-H 1        | 0.416509717703 | 25   | 0.422871738672 | 26   | +2%        |                          0.0082 |
| TPC-H 2        | 7.35165786743  | 442  | 6.8515920639   | 412  | -7%        |                          0.0000 |
| TPC-H 3        | 4.99258899689  | 300  | 5.69833135605  | 342  | +14%       |                          0.0000 |
| TPC-H 4        | 1.85804867744  | 112  | 1.85260641575  | 112  | -0%        |                          0.1730 |
| TPC-H 5        | 3.51340556145  | 211  | 3.47849822044  | 209  | -1%        |                          0.1035 |
| TPC-H 6        | 5.88655853271  | 354  | 21.4299888611  | 1286 | +264%      |                          0.0000 |
| TPC-H 7        | 1.23606228828  | 75   | 1.32252848148  | 80   | +7%        |                          0.0000 |
| TPC-H 8        | 4.27073669434  | 257  | 5.15991306305  | 310  | +21%       |                          0.0000 |
| TPC-H 9        | 1.45151174068  | 88   | 1.30700814724  | 79   | -10%       |                          0.0000 |
| TPC-H 10       | 2.62522554398  | 158  | 2.7554295063   | 166  | +5%        |                          0.0000 |
| TPC-H 11       | 22.8823184967  | 1373 | 22.785692215   | 1368 | -0%        |                          0.0000 |
| TPC-H 12       | 4.355717659    | 262  | 6.87513017654  | 413  | +58%       |                          0.0000 |
| TPC-H 13       | 1.59325110912  | 96   | 2.07508969307  | 125  | +30%       |                          0.0000 |
| TPC-H 14       | 9.46248245239  | 568  | 16.4045295715  | 985  | +73%       |                          0.0000 |
| TPC-H 15       | 8.04388237     | 483  | 8.82925987244  | 530  | +10%       |                          0.0000 |
| TPC-H 16       | 6.63388681412  | 399  | 6.27568006516  | 377  | -5%        |                          0.0000 |
| TPC-H 17       | 1.06945919991  | 65   | 0.959816336632 | 58   | -10%       |                          0.0000 |
| TPC-H 18       | 1.33208918571  | 80   | 1.30771172047  | 79   | -2%        |                          0.0003 |
| TPC-H 19       | 5.1266412735   | 308  | 4.35862827301  | 262  | -15%       |                          0.0000 |
| TPC-H 20       | 1.81808567047  | 110  | 1.54277944565  | 93   | -15%       |                          0.0000 |
| TPC-H 21       | 0.345343142748 | 21   | 0.322106540203 | 20   | -7%        |                          0.0000 |
| TPC-H 22       | 10.2023992538  | 613  | 8.23470973969  | 495  | -19%       |                          0.0000 |
| geometric mean |                |      |                |      | +10%       |                                 |
+----------------+----------------+------+----------------+------+------------+---------------------------------+
```

**Comment by mrks** [comment]
When you made the benchmark linked in the PR description, was that with or without MVCC?

**Comment by mrzzzrm** [comment]
erm, whatever was the default, I guess...

**Comment by mrzzzrm** [comment]
gimme the full command line, please. I am surprised about both the improvements and the regressions. Or did you do before/after visualization already, by chance?

**Comment by mrks** [comment]
Just `./hyriseBenchmarkTPCH`. My guess is that the validate is now placed further up, meaning that more scans can profit from the AVX scan.

**Comment by mrks** [comment]
Comparing 2e69dd19b00646b2b3e91d13eb70c56b516f0a4d and 17da1caed0776eafa7be68c7d128b9aa79060ef6, my assumption is true for TPC-H 6:

old:
Screenshot 2019-06-17 at 11 36 44
new:
Screenshot 2019-06-17 at 11 36 51

**Comment by mrzzzrm** [comment]
I'll run master against this branch on pella and visualize them all. Now I just hope the BenchmarkRunner still includes optimization duration in its report... :(

**Comment by mrks** [comment]
Yes, it does. Let me re-run my benchmarks too. Something looks fishy here.

**Comment by mrks** [comment]
New benchmark:

```
+----------------+----------------+------+----------------+------+------------+---------------------------------+
| Benchmark      | prev. iter/s   | runs | new iter/s     | runs | change [%] | p-value (significant if <0.001) |
+----------------+----------------+------+----------------+------+------------+---------------------------------+
| TPC-H 1        | 0.417543411255 | 26   | 0.421859234571 | 26   | +1%        |                          0.0642 |
| TPC-H 2        | 7.33052539825  | 440  | 6.82059860229  | 410  | -7%        |                          0.0000 |
| TPC-H 3        | 4.99199914932  | 300  | 5.81864643097  | 350  | +17%       |                          0.0000 |
| TPC-H 4        | 1.84340202808  | 111  | 1.86600208282  | 112  | +1%        |                          0.0000 |
| TPC-H 5        | 3.5273296833   | 212  | 3.59771800041  | 216  | +2%        |                          0.0000 |
| TPC-H 6        | 5.86318254471  | 352  | 21.7224788666  | 1304 | +270%      |                          0.0000 |
| TPC-H 7        | 1.23007845879  | 74   | 1.32614791393  | 80   | +8%        |                          0.0000 |
| TPC-H 8        | 4.06058835983  | 244  | 5.24118041992  | 315  | +29%       |                          0.0000 |
| TPC-H 9        | 1.44279062748  | 87   | 1.36081516743  | 82   | -6%        |                          0.0000 |
| TPC-H 10       | 2.62416672707  | 158  | 2.75450086594  | 166  | +5%        |                          0.0000 |
| TPC-H 11       | 22.7471389771  | 1365 | 22.540391922   | 1353 | -1%        |                          0.0000 |
| TPC-H 12       | 5.89864492416  | 354  | 6.79898309708  | 409  | +15%       |                          0.0000 |
| TPC-H 13       | 2.08888292313  | 126  | 2.0949678421   | 126  | +0%        |                          0.6700 |
| TPC-H 14       | 13.1729059219  | 791  | 21.5598888397  | 1294 | +64%       |                          0.0000 |
| TPC-H 15       | 8.01867961884  | 482  | 14.4870843887  | 870  | +81%       |                          0.0000 |
| TPC-H 16       | 6.615275383    | 397  | 6.5488448143   | 393  | -1%        |                          0.0000 |
| TPC-H 17       | 1.01763153076  | 62   | 1.08181285858  | 65   | +6%        |                          0.0000 |
| TPC-H 18       | 1.35288786888  | 82   | 1.31301867962  | 79   | -3%        |                          0.0000 |
| TPC-H 19       | 5.13816976547  | 309  | 5.15665817261  | 310  | +0%        |                          0.1841 |
| TPC-H 20       | 1.8084871769   | 109  | 1.91983425617  | 116  | +6%        |                          0.0000 |
| TPC-H 21       | 0.341508060694 | 21   | 0.347041189671 | 21   | +2%        |                          0.0001 |
| TPC-H 22       | 10.2478065491  | 615  | 10.1082115173  | 607  | -1%        |                          0.0000 |
| geometric mean |                |      |                |      | +15%       |                                 |
+----------------+----------------+------+----------------+------+------------+---------------------------------+
```

No idea what went wrong the first time.

**Comment by mrzzzrm** [comment]
pella is also noise + improvements

```
+----------------+----------------+------+----------------+------+------------+---------------------------------+
| Benchmark      | prev. iter/s   | runs | new iter/s     | runs | change [%] | p-value (significant if <0.001) |
+----------------+----------------+------+----------------+------+------------+---------------------------------+
| TPC-H 1        | 0.203374877572 | 13   | 0.207562536001 | 13   | +2%        |                          0.2797 |
| TPC-H 2        | 3.15163397789  | 190  | 3.04016518593  | 183  | -4%        |                          0.0000 |
| TPC-H 3        | 1.44134581089  | 87   | 2.01005029678  | 121  | +39%       |                          0.0000 |
| TPC-H 4        | 0.775962173939 | 47   | 0.779792189598 | 47   | +0%        |                          0.3492 |
| TPC-H 5        | 1.25059568882  | 76   | 1.34217679501  | 81   | +7%        |                          0.0000 |
| TPC-H 6        | 3.31403112411  | 199  | 9.68686199188  | 582  | +192%      |                          0.0000 |
| TPC-H 7        | 0.520214438438 | 32   | 0.580667495728 | 35   | +12%       |                          0.0000 |
| TPC-H 8        | 1.3527084589   | 82   | 1.56375598907  | 94   | +16%       |                          0.0000 |
| TPC-H 9        | 0.574751198292 | 35   | 0.551979422569 | 34   | -4%        |                          0.0000 |
| TPC-H 10       | 1.12452018261  | 68   | 1.19480133057  | 72   | +6%        |                          0.0000 |
| TPC-H 11       | 7.24875402451  | 435  | 7.34158086777  | 441  | +1%        |                          0.0000 |
| TPC-H 12       | 1.74565196037  | 105  | 2.69882655144  | 162  | +55%       |                          0.0000 |
| TPC-H 13       | 1.11245429516  | 67   | 1.09100031853  | 66   | -2%        |                          0.0058 |
| TPC-H 14       | 2.85199213028  | 172  | 8.44591331482  | 507  | +196%      |                          0.0000 |
| TPC-H 15       | 1.54507493973  | 93   | 4.93121194839  | 296  | +219%      |                          0.0000 |
| TPC-H 16       | 2.91377091408  | 175  | 2.94488859177  | 177  | +1%        |                          0.0137 |
| TPC-H 17       | 0.494169384241 | 30   | 0.501609683037 | 31   | +2%        |                          0.0000 |
| TPC-H 18       | 0.495650231838 | 30   | 0.503508806229 | 31   | +2%        |                          0.0001 |
| TPC-H 19       | 2.27594566345  | 137  | 2.22132825851  | 134  | -2%        |                          0.0000 |
| TPC-H 20       | 0.750438809395 | 46   | 0.906421899796 | 55   | +21%       |                          0.0000 |
| TPC-H 21       | 0.178327053785 | 11   | 0.176393866539 | 11   | -1%        |                          0.0001 |
| TPC-H 22       | 3.55865073204  | 214  | 3.53019356728  | 212  | -1%        |                          0.0000 |
| geometric mean |                |      |                |      | +23%       |                                 |
+----------------+----------------+------+----------------+------+------------+---------------------------------+
```

**Comment by mrzzzrm** [comment]
still running visualization to make sure this is only Validate placement

**Comment by Bouncner** [comment]
Don't we expect improvements for Q6 apart from the validate placements? Just by reordering the few predicates?

**Comment by mrks** [comment]
Wheeee

**Comment by mrks** [comment]
huiii

**Comment by mrzzzrm** [comment]
one off my bucket list. I'm starting to feel warmth and that inner calm thingy.
