### PR TITLE
Fix RandomCache's eviction bug

### LINKED ISSUE #922: [Sanitizer] RandomCache resize to smaller cache size not working correctly
Found like issue #920 .

[Function `_evict` in random_cache.hpp](https://github.com/hyrise/hyrise/blob/1085fc208d66f32362d804d7e77792d05949428f/src/lib/sql/random_cache.hpp) is not working correctly.

Minimal example:
>   TypeParam cache(2);
  cache.set(1, 2);
  cache.set(2, 4);
  cache.resize(1);
  ASSERT_TRUE(cache.has(2));
  ASSERT_EQ(cache.get(2), 4);

Before cache resize:
entry | _list    | _map
0   | (1, 2)  | (2, 1)
1    | (2, 4) | (1, 0)

After cache resize:
entry | _list   | _map
0    | (2, 4) | (2, **1**)

The problem is that `_evict` does not update the `_list` index in the `_map`.

It should be:
entry | _list   | _map
0    | (2, 4) | (2, **0**)

Found via test: CacheTest-4-RandomCache<int,int>:ResizeShrink [line 285](https://github.com/hyrise/hyrise/blob/4bdd2cba56b686af18d5ded1b6abcfbba08a5295/src/test/sql/sql_basic_cache_test.cpp)

Log:
> =================================================================
==69792==ERROR: AddressSanitizer: container-overflow on address 0x6030000d62b4 at pc 0x00010651107a bp 0x7ffee9bab230 sp 0x7ffee9bab228
READ of size 4 at 0x6030000d62b4 thread T0
    # 0 0x106511079 in testing::AssertionResult testing::internal::CmpHelperEQ<int, int>(char const*, char const*, int const&, int const&) gtest.h:1392
    # 1 0x1064ea449 in testing::AssertionResult testing::internal::EqHelper<false>::Compare<int, int>(char const*, char const*, int const&, int const&) gtest.h:1421
    # 2 0x10a620853 in opossum::CacheTest_ResizeShrink_Test<opossum::RandomCache<int, int> >::TestBody() sql_basic_cache_test.cpp:302
    # 3 0x11a8bd136 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2402
    # 4 0x11a6a8122 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2438
    # 5 0x11a6a7948 in testing::Test::Run() gtest.cc:2474
    # 6 0x11a6b3596 in testing::TestInfo::Run() gtest.cc:2656
    # 7 0x11a6bd25d in testing::TestCase::Run() gtest.cc:2774
    # 8 0x11a732c15 in testing::internal::UnitTestImpl::RunAllTests() gtest.cc:4649
    # 9 0x11a8e1e34 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2402
    # 10 0x11a730732 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2438
    # 11 0x11a72ff56 in testing::UnitTest::Run() gtest.cc:4257
    # 12 0x10633b5ae in RUN_ALL_TESTS() gtest.h:2233
    # 13 0x10633b1c3 in main gtest_main.cpp:44
    # 14 0x7fff58fdd014 in start (libdyld.dylib:x86_64+0x1014)
.
0x6030000d62b4 is located 20 bytes inside of 24-byte region [0x6030000d62a0,0x6030000d62b8)
allocated by thread T0 here:
    # 0 0x13c1a7c72 in wrap__Znwm (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x62c72)
    # 1 0x109591401 in std::__1::__split_buffer<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int> >&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<std::__1::pair<int, int> >&) new:228
    # 2 0x10958c922 in std::__1::__split_buffer<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int> >&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<std::__1::pair<int, int> >&) __split_buffer:310
    # 3 0x10a54212b in std::__1::vector<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int> > >::reserve(unsigned long) vector:1541
    # 4 0x10a5415e5 in opossum::RandomCache<int, int>::RandomCache(unsigned long) random_cache.hpp:21
    # 5 0x10a42b7ac in opossum::RandomCache<int, int>::RandomCache(unsigned long) random_cache.hpp:20
    # 6 0x10a61c5bb in opossum::CacheTest_ResizeShrink_Test<opossum::RandomCache<int, int> >::TestBody() sql_basic_cache_test.cpp:286
    # 7 0x11a8bd136 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2402
    # 8 0x11a6a8122 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2438
    # 9 0x11a6a7948 in testing::Test::Run() gtest.cc:2474
    # 10 0x11a6b3596 in testing::TestInfo::Run() gtest.cc:2656
    # 11 0x11a6bd25d in testing::TestCase::Run() gtest.cc:2774
    # 12 0x11a732c15 in testing::internal::UnitTestImpl::RunAllTests() gtest.cc:4649
    # 13 0x11a8e1e34 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2402
    # 14 0x11a730732 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2438
    # 15 0x11a72ff56 in testing::UnitTest::Run() gtest.cc:4257
    # 16 0x10633b5ae in RUN_ALL_TESTS() gtest.h:2233
    # 17 0x10633b1c3 in main gtest_main.cpp:44
    # 18 0x7fff58fdd014 in start (libdyld.dylib:x86_64+0x1014)
.
HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_container_overflow=0.
If you suspect a false positive see also: https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow.
SUMMARY: AddressSanitizer: container-overflow gtest.h:1392 in testing::AssertionResult testing::internal::CmpHelperEQ<int, int>(char const*, char const*, int const&, int const&)
Shadow bytes around the buggy address:
  0x1c060001ac00: fd fd fd fd fa fa fd fd fd fd fa fa fa fa fa fa
  0x1c060001ac10: fa fa fd fd fd fd fa fa fa fa fa fa fa fa fa fa
  0x1c060001ac20: fa fa fa fa fa fa fa fa fa fa fd fd fd fd fa fa
  0x1c060001ac30: fd fd fd fa fa fa fa fa fa fa fa fa fd fd fd fa
  0x1c060001ac40: fa fa fd fd fd fd fa fa fd fd fd fd fa fa fd fd
=>0x1c060001ac50: fd fa fa fa 00 fc[fc]fa fa fa fd fd fd fd fa fa
  0x1c060001ac60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c060001ac70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c060001ac80: fa fa fa fa fa fa fa fa fa fa fd fd fd fa fa fa
  0x1c060001ac90: fa fa fa fa fa fa fd fd fd fa fa fa fd fd fd fa
  0x1c060001aca0: fa fa fd fd fd fa fa fa fd fd fd fa fa fa fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==69792==ABORTING

### PR DESCRIPTION
**Pull request by Bensk1**
This should fix #922. @FabianWiebe could you double check that with your sanitizer?

### CODE REVIEW

File: src/lib/sql/random_cache.hpp [hunk 1]
```diff
@@ -84,6 +84,11 @@ class RandomCache : public AbstractCache<Key, Value> {
   void _evict() {
     _map.erase(_list[0].first);
     _list.erase(_list.cbegin());
```
Comment (FabianWiebe) [inline src/lib/sql/random_cache.hpp]: Maybe an item can be deleted from the back instead of the front so that there is no need for the extra loop. Then this function can continue to run in O(1).

**Comment by mrks** [comment]
This highlights a bigger issue: `_evict` is used in all caches only for `resize()`, not for set. That is quite surprising. Either use `_evict` whenever we need to get rid of an entry (and return a handle for the position that should be used next) or let `resize` deal with it itself.

**Comment by Bensk1** [comment]
`_evict` is used in the `set()` method of the LRU and GDS cache.

There is a reason why the RandomCache does not use evict in the `set` method or better to say why there are two kinds of evicting entries. During `set` a random element should be evicted. During resize, it should be deterministic which elements are deleted. 

@FabianWiebe We decided to remove elements from the front during resizing because of our query cache demo, but I do not remember the exact reason.

File: src/lib/sql/random_cache.hpp (hunk 1 above)
Comment (Bensk1) [reply src/lib/sql/random_cache.hpp]: We decided to remove elements from the front during resizing because of our query cache demo, but I do not remember the exact reason.

Comment (FabianWiebe) [reply src/lib/sql/random_cache.hpp]: Ok, I just wanted to check that there is a reason for this overhead.
