### PR TITLE
Let server sessions finish before exiting

### LINKED ISSUE #1977: Server: Session destruction mismatch
In #1973 (https://hyrise-ci.epic-hpi.de/blue/organizations/jenkins/hyrise%2Fhyrise/detail/PR-1973/9/pipeline):

<pre>
[ RUN      ] ServerTestRunner.ValidateCorrectTransfer
Server started at 0.0.0.0 and port 37139
Run 'psql -h localhost' to connect to the server
=================================================================
==10364==ERROR: AddressSanitizer: heap-use-after-free on address 0x6040021fd6b8 at pc 0x000003b494fd bp 0x7fd4822d8190 sp 0x7fd4822d8188
READ of size 8 at 0x6040021fd6b8 thread T446 (server_p_53456)
    #0 0x3b494fc in boost::asio::detail::<strong>reactive_socket_service_base::destroy</strong>(boost::asio::detail::reactive_socket_service_base::base_implementation_type&) /usr/include/boost/asio/detail/impl/reactive_socket_service_base.ipp:94:5
    [...]
    #11 0x93e872a in <strong>opossum::Session::~Session()</strong> /var/lib/jenkins/workspace/hyrise_hyrise_PR-1973/clang-debug-addr-ub-sanitizers/src/lib/../../../src/lib/server/session.hpp:15:7
    [...]
    #19 0x93aa214 in opossum::Server::_start_session(std::shared_ptr<opossum::Session> const&, boost::system::error_code const&)::<strong$_1::~$_1()</strong> /var/lib/jenkins/workspace/hyrise_hyrise_PR-1973/clang-debug-addr-ub-sanitizers/src/lib/../../../src/lib/server/server.cpp:35:30
    [...]

0x6040021fd6b8 is located 40 bytes inside of 48-byte region [0x6040021fd690,0x6040021fd6c0)
freed by thread T0 here:
    #0 0x39fe12d in operator delete(void*) (/var/lib/jenkins/workspace/hyrise_hyrise_PR-1973/clang-debug-addr-ub-sanitizers/hyriseSystemTest+0x39fe12d)
    #1 0x93cf050 in boost::asio::detail::reactive_socket_service<boost::asio::ip::tcp>::<strong>~reactive_socket_service()</strong> /usr/include/boost/asio/detail/reactive_socket_service.hpp:48:7
    [...]
    #6 0x3b48d7a in boost::asio::io_context::<strong>~io_context()</strong> /usr/include/boost/asio/impl/io_context.ipp:58:1
    #7 0x3b48ca9 in opossum::Server::<strong>~Server()</strong> /var/lib/jenkins/workspace/hyrise_hyrise_PR-1973/clang-debug-addr-ub-sanitizers/src/test/../../../src/lib/server/server.hpp:29:7
    #8 0x3b488fb in std::default_delete<opossum::Server>::operator()(opossum::Server*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:81:2
    #9 0x3b47eb3 in std::unique_ptr<opossum::Server, std::default_delete<opossum::Server> >::~unique_ptr() /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:284:4
    #10 0x3b46c12 in opossum::ServerTestRunner::<strong>~ServerTestRunner()</strong> /var/lib/jenkins/workspace/hyrise_hyrise_PR-1973/clang-debug-addr-ub-sanitizers/src/test/../../../src/test/server/server_test_runner.cpp:18:7
    [...]
</pre>

The way I see it, `Server::_start_session` detaches the `session_thread`. If the server is destroyed before the thread finishes, the `reactive_socket_service` has been destroyed by `~Server` (bottom stack trace), but `~Session` wants to do some kind of deregistration in `reactive_socket_service`.

[log(1).txt](https://github.com/hyrise/hyrise/files/4044886/log.1.txt)

On first sight, I see two options:
1. Pass the io_service as a shared_ptr into the session. This ensures that it is not deleted too early, but likely has performance implications.
2. Track the number of open `session_thread`s and hold the server destructor until all of those are closed. In a perfect world, it seems good for the server to wait for everything to be finished, but I am not sure how this would become a problem with client timeouts.

This has caused a number of CI fails in the last days, both with asan/ubsan and with tsan (different error message, but similar problem). As such, it directly impedes development and we should find a solution quickly.

### PR DESCRIPTION
**Pull request by mrks**
#1977 showed issues with the server stopping before all sessions are closed. To quote from the new test:

> Test that open sessions are allowed to finish before the server is destroyed. This is more relevant for tests than for the actual execution. In "real-life", i.e., during our experiments, we usually simply kill the server. In tests however, the server finishing while sessions might not be completely finished could lead to issues like #1977.

Benchmark:
```
echo 'CREATE TABLE t (a INT)' | psql -h localhost -p 1241
echo 'SELECT * FROM t;' > test
pgbench -h localhost -p 1241 -f test -n -c 100 -j 100 -T 10
```

old:
> tps = 151788.790109 (including connections establishing)
> tps = 152061.524404 (excluding connections establishing)

new:
> tps = 152625.496717 (including connections establishing)
> tps = 152822.493136 (excluding connections establishing)

Thus, the atomic does not seem to make any noteworthy difference.

This should fix #1977 (which I haven't seen since January and cannot be found in any non-purged Jenkins logs) by making sure that the io_service outlives the sessions.

### CODE REVIEW

File: src/lib/server/server.cpp [hunk 1]
```diff
@@ -32,14 +32,23 @@ void Server::_accept_new_session() {
 void Server::_start_session(const std::shared_ptr<Session>& new_session, const boost::system::error_code& error) {
   Assert(!error, error.message());
 
-  std::thread session_thread([new_session] {
-    const std::string thread_name = "server_p_" + std::to_string(new_session->socket()->remote_endpoint().port());
+  std::thread session_thread([session = new_session, &num_running_sessions = this->_num_running_sessions]() mutable {
```
Comment (mrks) [inline src/lib/server/server.cpp:35]: As discussed out-of-band: Explain why we detach threads.

**Comment by mrks** [comment]
@klauck good to go?
