### PR TITLE
Fix tmpfile handling in visualization

### LINKED ISSUE #1869: hyriseBenchmarkTPCDS --visualize fails with too many open files
```
- Benchmarking 01
sh: 1: 1: Too many open files
terminate called after throwing an instance of 'std::logic_error'
  what():  src/lib/visualization/abstract_visualizer.hpp:139 Calling graphviz' dot failed. Have you installed graphviz (apt-get install graphviz / brew install graphviz)?
```

7e98ab168755dfe00f31bb67056fb1b915357f87

```
$ ulimit -n
1024
```

Probably there is a file that we are not closing properly.

### PR DESCRIPTION
**Pull request by mrks**
We never (a) closed the tempfile and we (b) never deleted it. You might want to run `rm -f /tmp/hyrise_viz_*` on your machine(s).

fixes #1869

### CODE REVIEW

File: src/lib/visualization/abstract_visualizer.hpp [hunk 1]
```diff
@@ -95,11 +95,19 @@ class AbstractVisualizer {
...
+    close(file_descriptor);
     std::ofstream file(tmpname);
 
-    // By now, the pen widths are set to either the number of rows (for edges) or the execution time in ns (for
+    // This unique_ptr serves as a scope guard that guarantees the deletion of the temp file once we return from this
+    // method.
+    const auto delete_temp_file = [&tmpname](auto) { std::remove(tmpname); };
+    const auto delete_guard = std::unique_ptr<char, decltype(delete_temp_file)>(new char, delete_temp_file);
+
+    // The caller set the pen widths to either the number of rows (for edges) or the execution time in ns (for
```
Comment (Bensk1) [inline src/lib/visualization/abstract_visualizer.hpp]: `sets`?

Comment (mrks) [reply src/lib/visualization/abstract_visualizer.hpp]: No. Past tense.
