### PR TITLE
Fix `show tables` and subqueries involving meta tables (#2162)

### LINKED ISSUE #2162: Some queries involving Metatables give wrong results
To reproduce in hyriseConsole:

```
SHOW tables
generate_tpch 0.01
SHOW tables
```

The second `SHOW tables` should display the tables of the TPC-H dataset. Instead, it displays an empty table because the plan (metatable) of the initial `SHOW tables` has been cached.

The same applies if `SHOW tables` is replaced with `SELECT table_name FROM (SELECT table_name, column_count FROM meta_tables) as subquery`.

### PR DESCRIPTION
**Pull request by Bensk1**
Fixes #2162.

There are two things I don't really like, they are up for discussion:

- ~~Solving the subquery involving non-cacheable metatables problem by making `SQLTranslator's` `_cacheable` a public member~~
- ~~The way this is tested: adding an optional parameter to `SQLTranslatorTest's` `compile_query` method. We could also change the function's return type but then we would need to adapt almost all 147 SQLTranslatorTests.~~

### CODE REVIEW

File: src/lib/sql/sql_translator.hpp [hunk 1]
```diff
@@ -203,12 +203,13 @@ class SQLTranslator final {
 
   static std::string _trim_meta_table_name(const std::string& name);
 
+  // The current LQP might not be cacheable if it involves a meta table
+  bool cacheable{true};
```
Comment (Bensk1) [inline src/lib/sql/sql_translator.hpp:207]: See PR discussion.

File: src/test/lib/sql/sql_translator_test.cpp [hunk 2]
```diff
@@ -79,15 +79,22 @@ class SQLTranslatorTest : public BaseTest {
     int_int_int_c = stored_table_node_int_int_int->get_column("c");
   }
 
-  std::shared_ptr<opossum::AbstractLQPNode> compile_query(const std::string& query,
-                                                          const UseMvcc use_mvcc = UseMvcc::No) {
+  std::shared_ptr<opossum::AbstractLQPNode> compile_query(
+      const std::string& query, const UseMvcc use_mvcc = UseMvcc::No,
+      const std::shared_ptr<SQLTranslationInfo>& translation_info = nullptr) {
```
Comment (Bensk1) [inline src/test/lib/sql/sql_translator_test.cpp:84]: See PR discussion.

File: src/lib/sql/sql_translator.cpp [hunk 3]
```diff
@@ -640,6 +640,10 @@ SQLTranslator::TableSourceState SQLTranslator::_translate_table_origin(const hsq
                                         _with_descriptions, _meta_tables};
       lqp = subquery_translator._translate_select_statement(*hsql_table_ref.select);
 
+      // If a statement of the subquery is not cacheable (e.g., for meta tables),
+      // this statement should not be cacheable either.
+      cacheable = subquery_translator.cacheable;
```
Comment (mrks) [inline src/lib/sql/sql_translator.cpp:645]: Shouldn't it be `|=`?

Comment (mrks) [reply src/lib/sql/sql_translator.cpp:645]: If yes, there is probably a test missing.

File: src/lib/sql/sql_translator.hpp (hunk 1 above)
Comment (mrks) [reply src/lib/sql/sql_translator.hpp:207]: > Solving the subquery involving non-cacheable metatables problem by making SQLTranslator's _cacheable a public member

Why does it have to be public? Where are you accessing it from the outside?

File: src/test/lib/sql/sql_translator_test.cpp (hunk 2 above)
Comment (mrks) [reply src/test/lib/sql/sql_translator_test.cpp:84]: I don't like `compile_query` too much. Maybe `sql_to_lqp_helper`?

File: src/test/lib/sql/sql_translator_test.cpp [hunk 4]
```diff
@@ -79,15 +79,22 @@ class SQLTranslatorTest : public BaseTest {
...
 
     const auto translation_result = SQLTranslator{use_mvcc}.translate_parser_result(parser_result);
     const auto lqps = translation_result.lqp_nodes;
 
+    if (translation_info) {
+      translation_info->cacheable = translation_result.translation_info.cacheable;
+      translation_info->parameter_ids_of_value_placeholders =
+          translation_result.translation_info.parameter_ids_of_value_placeholders;
+    }
+
```
Comment (mrks) [inline src/test/lib/sql/sql_translator_test.cpp:97]: Any reason you can't return a pair instead of having an output parameter?

File: src/lib/sql/sql_translator.cpp (hunk 3 above)
Comment (Bensk1) [reply src/lib/sql/sql_translator.cpp:645]: Agreed!

File: src/lib/sql/sql_translator.hpp (hunk 1 above)
Comment (Bensk1) [reply src/lib/sql/sql_translator.hpp:207]: The SubqueryTranslator is another SQLTranslator, isn't it?

File: src/test/lib/sql/sql_translator_test.cpp (hunk 4 above)
Comment (Bensk1) [reply src/test/lib/sql/sql_translator_test.cpp:97]: Nope. Just that we have to change all tests then.

File: src/lib/sql/sql_translator.cpp (hunk 3 above)
Comment (mrks) [reply src/lib/sql/sql_translator.cpp:645]: Ah wait. It should be `&=`, right?

File: src/lib/sql/sql_translator.hpp (hunk 1 above)
Comment (mrks) [reply src/lib/sql/sql_translator.hpp:207]: So?

> A private member of a class is only accessible to the members and friends of that class, regardless of whether the members are on the same or different instances

Am I missing something?

File: src/lib/sql/sql_translator.cpp (hunk 3 above)
Comment (Bensk1) [reply src/lib/sql/sql_translator.cpp:645]: Right, thank you! Only if outer and inner plan are cacheable, it should be set to `true`.

File: src/lib/sql/sql_translator.hpp (hunk 1 above)
Comment (Bensk1) [reply src/lib/sql/sql_translator.hpp:207]: No, but I did, apparently.

File: src/test/lib/sql/sql_translator_test.cpp (hunk 4 above)
Comment (mrks) [reply src/test/lib/sql/sql_translator_test.cpp:97]: Looks like 90% can be covered with a single Regexp

**Comment by mrks** [comment]
As the final commit message includes the PR number, I'd suggest leaving "(#2162)" out of the PR title. For context, people will easily find the "fixes ..." in the text.
