### PR TITLE
Fix operator performance counters in hash aggregate

### LINKED ISSUE #2266: Incorrect performance counters in hash aggregate
image

Here, it's 35 + 528 + 31 + 46 ms. Which is 640 ms, while the operator runtime is 615 ms.
~~Moreover, step "GroupByColumnsWriting" is often written twice, which overwrites the first runtime. So the error would be even larger, if we wouldn't overwrite.~~

I looked into the aggregate, but couldn't find a reason for the mismatch. @mrks : you did a lot lately on the aggregate, any ideas?

### PR DESCRIPTION
**Pull request by Bouncner**
Resolves #2266.

`_write_groupby_output` can be called at two places. In one of the (`write_aggregate_output()`), its self-recorded step runtime is included in the runtime of the AggregateColumnWriting step, leading to cumulative step runtimes that are larger than the actual operator runtime.

### CODE REVIEW

File: src/lib/operators/aggregate_hash.cpp [hunk 1]
```diff
@@ -624,10 +628,7 @@ std::shared_ptr<const Table> AggregateHash::_on_execute() {
     }
     _write_groupby_output(pos_list);
   }
-
-  // _aggregate and _write_groupby_output have their own, internal timer. Start measuring once they are done.
-  auto& step_performance_data = static_cast<OperatorPerformanceData<OperatorSteps>&>(*performance_data);
-  Timer timer;
+  step_performance_data.set_step_runtime(OperatorSteps::GroupByColumnsWriting, timer.lap());
```
Comment (mrks) [inline src/lib/operators/aggregate_hash.cpp:631]: Have a look at what your timer measures. If `_has_aggregate_functions` is true, no code is executed between the creation of the timer and `timer.lap()`.

`_write_groupby_output` is also called from `_write_aggregate_output`.

**Review by mrks — CHANGES_REQUESTED** [review]

File: src/lib/operators/aggregate_hash.cpp (hunk 1 above)
Comment (Bouncner) [reply src/lib/operators/aggregate_hash.cpp]: Changed that. Not sure how happy I am with this solution.

Comment (mrks) [reply src/lib/operators/aggregate_hash.cpp]: Have a look at #2270, where I ran into a similar problem. We should decide for one solution.

Comment (Bouncner) [reply src/lib/operators/aggregate_hash.cpp]: Doesn't look the same to me as you are adding step times within another function, aren't you? I don't want to pass runtimes between functions.

Comment (Bouncner) [reply src/lib/operators/aggregate_hash.cpp]: Just reviewed and saw that you are using members. I'll think about it...

File: src/lib/operators/aggregate_hash.cpp [hunk 2]
```diff
@@ -946,6 +952,8 @@ void AggregateHash::write_aggregate_output(ColumnID aggregate_index) {
         std::make_shared<ValueSegment<decltype(aggregate_type)>>(std::move(values), std::move(null_values));
   }
   _output_segments[output_column_id] = output_segment;
+
+  aggregate_columns_writing_duration += timer.lap() - write_groupby_output_duration;
```
Comment (mrks) [inline src/lib/operators/aggregate_hash.cpp:956]: `_write_groupby_output` is only called for `aggregate_index == 0`. Did you test this?

Comment (Bouncner) [reply src/lib/operators/aggregate_hash.cpp:956]: Not sure what you are asking for. `write_groupby_output_duration` does only store non-zero runtimes, when  `aggregate_index == 0` was true. Was this the question?

Comment (mrks) [reply src/lib/operators/aggregate_hash.cpp:956]: I confused it with `groupby_columns_writing_duration`. Maybe, we can find clearer names? Also, should we a comment explaining that `write_groupby_output_duration` is 0 for all but the first aggregate?

Comment (Bouncner) [reply src/lib/operators/aggregate_hash.cpp:956]: Like this?

```
// Used to track the duration of groupby columns writing, which is done for the first aggregate only. Value is
  // substraced from the runtime of this method (thus, it's either 0 or non-zero for the first aggregate).
  auto first_aggregate_groupby_column_writing_time = std::chrono::nanoseconds{};
```

Don't like the var name.

Comment (mrks) [reply src/lib/operators/aggregate_hash.cpp]: Typo: subtracted

Maybe just call it `excluded_time`?

Comment (Bouncner) [reply src/lib/operators/aggregate_hash.cpp]: Changed.

**Review by mrks — APPROVED** [review]
