### PR TITLE
Fix some scheduling errors, improve error handling

### LINKED ISSUE #535: TransactionContext hides exceptions
In some cases, the transaction context (line 34) hides the actual exception by bringing up another one which can be really confusing.

Example in hyriseConsole:
> generate ITEM 
SELECT * FROM ITEM;

shows a problem with the ValidateOperator even though the error is caused by the unquoted keyword `ITEM`

### PR DESCRIPTION
**Pull request by mrks**
* fixed generation of ITEM table changing the scheduler
* makes it possible to enable/disable scheduler in console
* AbstractOperator now checks if tx context is still valid
* AbstractOperator now checks if at least one column is in output (unless no output is produced)
* AbstractOperator now tracks its OperatorTask, making sure that only one task exists
* fixed false reference capture in hash join - capturing `&current_partition_id` breaks a lot of things here:
https://github.com/hyrise/hyrise/blob/master/src/lib/operators/join_hash.cpp#L350-L354
* fixed `OperatorTask::make_tasks_from_operator` creating two tasks if an operator had two successors
* don't execute OperatorTask if the tx already failed
* makes sqlite testrunner run all tests with an enabled scheduler

closes #535

### CODE REVIEW

File: src/bin/console/console.cpp [hunk 1]
```diff
@@ -588,6 +597,29 @@ int Console::visualize(const std::string& input) {
   return ReturnCode::Ok;
 }
 
+int Console::change_runtime_setting(const std::string& input) {
```
[the remark this answers is not in the document]
Comment (mrks) [reply src/bin/console/console.cpp]: Once we do have multiple methods, we could move them into their own methods or have some generalized way of doing that. This could also relate to #63

File: src/lib/operators/join_hash.cpp [hunk 2]
```diff
@@ -349,7 +349,7 @@ class JoinHash::JoinHashImpl : public AbstractJoinOperatorImpl {
 
     for (size_t current_partition_id = 0; current_partition_id < (radix_container.partition_offsets.size() - 1);
          ++current_partition_id) {
-      jobs.emplace_back(std::make_shared<JobTask>([&]() {
+      jobs.emplace_back(std::make_shared<JobTask>([&, current_partition_id]() {
```
Comment (mjendruk) [inline src/lib/operators/join_hash.cpp]: 👍

File: src/bin/console/console.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (Bensk1) [reply src/bin/console/console.cpp]: Correct

File: src/lib/operators/abstract_read_only_operator.hpp [hunk 3]
```diff
@@ -31,6 +31,9 @@ class AbstractReadOnlyOperator : public AbstractOperator {
     virtual ~AbstractReadOnlyOperatorImpl() = default;
     virtual std::shared_ptr<const Table> _on_execute() = 0;
   };
+
+  // for access to _on_execute
+  friend class AbstractOperator;
```
Comment (mjendruk) [inline src/lib/operators/abstract_read_only_operator.hpp]: Could you explain why this is needed, please?

Comment (mrks) [reply src/lib/operators/abstract_read_only_operator.hpp]: The `_on_execute` method without a transaction context only exists in this class, so `AbstractOperator` would not know about it.

**Comment by mrks** [comment]
> Looks good. I don’t like the interdependence of tasks and operators that much but it seems to be the easiest way. Since this is only used during the creation of tasks, we could also use a map and pass it through the tree.

This would not necessarily make sure that nobody creates a task at a later time.

File: src/lib/operators/abstract_read_only_operator.hpp (hunk 3 above)
Comment (mrks) [reply src/lib/operators/abstract_read_only_operator.hpp]: ping @mjendruk

File: src/lib/operators/abstract_operator.cpp [hunk 4]
```diff
@@ -33,7 +35,14 @@ void AbstractOperator::execute() {
     _output = _on_execute(transaction_context);
     transaction_context->on_operator_finished();
   } else {
-    _output = _on_execute(transaction_context);
+    if (dynamic_cast<SQLQueryOperator*>(this)) {
+      // TODO(anyone): Once the SQL Query Operator is refactored (#304), this should be removed
+      _output = _on_execute(nullptr);
+    } else {
+      auto read_only_operator = dynamic_cast<AbstractReadOnlyOperator*>(this);
+      DebugAssert(read_only_operator, "Trying to execute read write operator without transaction context");
```
Comment (mjendruk) [inline src/lib/operators/abstract_operator.cpp]: This is already taken care of in the `AbstractReadWriteOperator::_on_execute()`

File: src/lib/operators/abstract_operator.cpp [hunk 5]
```diff
@@ -33,7 +35,14 @@ void AbstractOperator::execute() {
     _output = _on_execute(transaction_context);
     transaction_context->on_operator_finished();
   } else {
-    _output = _on_execute(transaction_context);
+    if (dynamic_cast<SQLQueryOperator*>(this)) {
+      // TODO(anyone): Once the SQL Query Operator is refactored (#304), this should be removed
+      _output = _on_execute(nullptr);
```
Comment (mjendruk) [inline src/lib/operators/abstract_operator.cpp]: I’d just use this call for every operator. Then the friend declaration could be removed.

**Comment by mjendruk** [comment]
> This would not necessarily make sure that nobody creates a task at a later time.

true

File: src/lib/operators/abstract_operator.cpp (hunk 4 above)
Comment (mrks) [reply src/lib/operators/abstract_operator.cpp]: Good point, removed.

File: src/lib/operators/abstract_operator.cpp (hunk 5 above)
Comment (mrks) [reply src/lib/operators/abstract_operator.cpp]: done
