### PR TITLE
Prune tables regardless of predicates with subqueries

### LINKED ISSUE #2540: Chunk pruning does not work with uncorrelated subqueries
### Expected behavior
Let `lqp` be a query plan with a table (`StoredTableNode`) and  two predicate nodes, where `PredicateNodeB` is a regular scan (`b > 6`) and `PredicateNodeA` is a scan with an uncorrelated subquery result (`a = <subquery>`). The `ChunkPruningRule` prunes `StoredTableNode` according to the predicate of `PredicateNodeA`. 

### Actual behavior
`StoredTableNode` is not pruned at all.

### Steps to reproduce
```c++
const auto& table_a = load_table("resources/test_data/tbl/int_sorted_value_clustered.tbl", ChunkOffset{2});
const auto& table_b = load_table("resources/test_data/tbl/int_int_int2.tbl", ChunkOffset{2});
Hyrise::get().storage_manager.add_table("table_a", table_a);
Hyrise::get().storage_manager.add_table("table_b", table_b);

const auto stored_table_a = StoredTableNode::make("table_a");
const auto stored_table_b = StoredTableNode::make("table_b");

const auto a_a = stored_table_a->get_column("a");
const auto a_b = stored_table_a->get_column("b");
const auto b_a = stored_table_b->get_column("a");
const auto b_b = stored_table_b->get_column("b");

Print::print(table_a);

std::cout << std::endl << std::endl;

// clang-format off
// Maximal prossible pruning with b > 6 and < = 4.
auto lqp_1 =
PredicateNode::make(greater_than_(a_b, value_(6)),
  PredicateNode::make(equals_(a_a, value_(4)),
    stored_table_a))->deep_copy();

// Pruning with b > 6.
auto lqp_2 =
PredicateNode::make(greater_than_(a_b, value_(6)),
  stored_table_a)->deep_copy();

auto subquery =
ProjectionNode::make(expression_vector(b_a),
  PredicateNode::make(equals_(b_b, value_(5)),
    stored_table_b));

// Pruning with b > 6 and subquery.
auto lqp_3 =
PredicateNode::make(greater_than_(a_b, value_(6)),
  PredicateNode::make(equals_(a_a, lqp_subquery_(subquery)),
   stored_table_a))->deep_copy();
// clang-format on

const auto optimizer = std::make_shared<Optimizer>();
optimizer->add_rule(std::make_unique<ChunkPruningRule>());

std::cout << *optimizer->optimize(std::move(lqp_1)) << std::endl << std::endl;
std::cout << *optimizer->optimize(std::move(lqp_2)) << std::endl << std::endl;
std::cout << *optimizer->optimize(std::move(lqp_3)) << std::endl << std::endl;
```

The output is:
```
=== Columns
|       a|       b|
|     int|     int|
|not null|not null|
=== Chunk 0 ===
|<ValueS>|<ValueS>|
|       1|       2|
|       1|       3|
=== Chunk 1 ===
|<ValueS>|<ValueS>|
|       3|       7|
|       5|       1|
=== Chunk 2 ===
|<ValueS>|<ValueS>|
|       5|       2|
|       5|       3|
=== Chunk 3 ===
|<ValueS>|<ValueS>|
|       2|       5|
|       2|       9|
=== Chunk 4 ===
|<ValueS>|<ValueS>|
|       4|       3|
|       4|       5|
=== Chunk 5 ===
|<ValueS>|<ValueS>|
|       4|       7|
|       4|       9|


[0] [Predicate] 0x141704098.b > 6 @ 0x6000003a4228
 \_[1] [Predicate] 0x141704098.a = 4 @ 0x6000003a4178
    \_[2] [StoredTable] Name: 'table_a' pruned: 5/6 chunk(s), 0/2 column(s) @ 0x141704098


[0] [Predicate] 0x1417041b8.b > 6 @ 0x6000003a40c8
 \_[1] [StoredTable] Name: 'table_a' pruned: 3/6 chunk(s), 0/2 column(s) @ 0x1417041b8


[0] [Predicate] 0x141704e18.b > 6 @ 0x6000003a4598
 \_[1] [Predicate] 0x141704e18.a = SUBQUERY (LQP, 0x6000005a0158) @ 0x6000003a44e8
    \_[2] [StoredTable] Name: 'table_a' pruned: 0/6 chunk(s), 0/2 column(s) @ 0x141704e18
-------- Subqueries ---------
0x6000005a0158:
[0] [Projection] 0x141704f38.a @ 0x6000005a0158
 \_[1] [Predicate] 0x141704f38.b = 5 @ 0x6000003a4438
    \_[2] [StoredTable] Name: 'table_b' pruned: 1/2 chunk(s), 0/3 column(s) @ 0x141704f38
```

As we can see, with the predicates `a = 4` and `b > 6`, or with the predicate `b > 6`, `table_a`is pruned as exprected. However, with `a = <subquery>` and `b > 6`, `table_a` is not pruned.

### Possible fix
`ChunkPruningRule` uses `OperatorScanPredicate`s to prune the table. An `OperatorScanPredicate` cannot be build if the predicate contains a subquery. If the rule cannot build an `OperatorScanPredicate`, it aborts: https://github.com/hyrise/hyrise/blob/9dc0fe58708bd47e07932114cbc49e4547f0cd33/src/lib/optimizer/strategy/chunk_pruning_rule.cpp#L234-L240

 However, it should continue but simply not use the predicate for pruning.

### PR DESCRIPTION
**Pull request by dey4ss**
This PR enables chunk pruning for tables if there are predicates with subqueries on them. These predicates themselves are ignored, but pruning with other predicates is done.

Furthermore, some style guidelines are applied to the `ChunkPruningRule` and its test.

closes #2540 

## Benchmarks
**System**
<details>
<summary>nemea - click to expand</summary>

| property | value |
| -- | -- |
| Hostname | nemea |
| CPU | Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz |
| Memory | 1.1TB |
| numactl | nodebind: 2  |
| numactl | membind: 2  |
</details>

**Commit Info and Build Time**
| commit | date | message | build time |
| -- | -- | -- | -- |
| 9dc0fe587 | 08.02.2023 13:18 | Remove Boost overrides (#2538) | real 334.55 user 2858.62 sys 88.51|
| 4dcd16447 | 09.02.2023 10:26 | allow correlated subqueries | real 337.99 user 2863.47 sys 86.52|

**hyriseBenchmarkTPCH - single-threaded, SF 10.0**
<details>
<summary>
Sum of avg. item runtimes: +2%
 ||
Geometric mean of throughput changes: -2%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview----+--------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCH_9dc0fe58708bd47e07932114cbc49e4547f0cd33_st.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCH_4dcd16447406e725257d578bd8e0af9351361606_st.json |
 +--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                | 9dc0fe58708bd47e07932114cbc49e4547f0cd33-dirty                                                                                             | 4dcd16447406e725257d578bd8e0af9351361606-dirty                                                                                             |
 |  benchmark_mode          | Ordered                                                                                                                                    | Ordered                                                                                                                                    |
 |  build_type              | release                                                                                                                                    | release                                                                                                                                    |
 |  chunk_size              | 65535                                                                                                                                      | 65535                                                                                                                                      |
 |  clients                 | 1                                                                                                                                          | 1                                                                                                                                          |
 |  clustering              | None                                                                                                                                       | None                                                                                                                                       |
 |  compiler                | clang 14.0.0                                                                                                                               | clang 14.0.0                                                                                                                               |
 |  cores                   | 0                                                                                                                                          | 0                                                                                                                                          |
 |  data_preparation_cores  | 0                                                                                                                                          | 0                                                                                                                                          |
 |  date                    | 2023-02-09 10:43:04                                                                                                                        | 2023-02-09 14:04:27                                                                                                                        |
 |  encoding                | {'default': {'encoding': 'Dictionary'}}                                                                                                    | {'default': {'encoding': 'Dictionary'}}                                                                                                    |
 |  indexes                 | False                                                                                                                                      | False                                                                                                                                      |
 |  max_duration            | 60000000000                                                                                                                                | 60000000000                                                                                                                                |
 |  max_runs                | 100                                                                                                                                        | 100                                                                                                                                        |
 |  scale_factor            | 10.0                                                                                                                                       | 10.0                                                                                                                                       |
 |  time_unit               | ns                                                                                                                                         | ns                                                                                                                                         |
 |  use_prepared_statements | False                                                                                                                                      | False                                                                                                                                      |
 |  using_scheduler         | False                                                                                                                                      | False                                                                                                                                      |
 |  verify                  | False                                                                                                                                      | False                                                                                                                                      |
 |  warmup_duration         | 1000000000                                                                                                                                 | 1000000000                                                                                                                                 |
 +--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++----------++----------+----------+--------++----------+----------+--------+---------+
+| Item     || Latency (ms/iter)   | Change || Throughput (iter/s) | Change | p-value |
+|          ||      old |      new |        ||      old |      new |        |         |
++----------++----------+----------+--------++----------+----------+--------+---------+
+| TPC-H 01 ||  5796.67 |  5900.39 |   +2%  ||     0.17 |     0.17 |   -2%  |  0.4183 |
+| TPC-H 02 ||    43.06 |    43.39 |   +1%˄ ||    23.22 |    23.05 |   -1%˄ |  0.5232 |
+| TPC-H 03 ||  2219.32 |  2261.79 |   +2%  ||     0.45 |     0.44 |   -2%  |  0.0615 |
+| TPC-H 04 ||  1373.15 |  1430.67 |   +4%  ||     0.73 |     0.70 |   -4%  |  0.0000 |
+| TPC-H 05 ||  3046.53 |  3098.80 |   +2%  ||     0.33 |     0.32 |   -2%  |  0.0134 |
+| TPC-H 06 ||   150.99 |   156.86 |   +4%˄ ||     6.62 |     6.37 |   -4%˄ |  0.0000 |
+| TPC-H 07 ||   899.89 |   922.84 |   +3%  ||     1.11 |     1.08 |   -2%  |  0.0000 |
+| TPC-H 08 ||   695.86 |   705.19 |   +1%  ||     1.44 |     1.42 |   -1%  |  0.0000 |
+| TPC-H 09 ||  5117.90 |  5199.54 |   +2%  ||     0.20 |     0.19 |   -2%  |  0.0001 |
+| TPC-H 10 ||  2927.39 |  2921.23 |   -0%  ||     0.34 |     0.34 |   +0%  |  0.8358 |
+| TPC-H 11 ||    72.37 |    72.56 |   +0%˄ ||    13.82 |    13.78 |   -0%˄ |  0.7072 |
+| TPC-H 12 ||   999.03 |   976.91 |   -2%  ||     1.00 |     1.02 |   +2%  |  0.0000 |
+| TPC-H 13 ||  4597.27 |  4651.22 |   +1%  ||     0.22 |     0.21 |   -1%  |  0.1235 |
+| TPC-H 14 ||   415.67 |   419.84 |   +1%˄ ||     2.41 |     2.38 |   -1%˄ |  0.0016 |
+| TPC-H 15 ||   188.08 |   191.71 |   +2%˄ ||     5.32 |     5.22 |   -2%˄ |  0.0000 |
+| TPC-H 16 ||   629.37 |   646.26 |   +3%  ||     1.59 |     1.55 |   -3%  |  0.0000 |
+| TPC-H 17 ||   212.68 |   215.32 |   +1%˄ ||     4.70 |     4.64 |   -1%˄ |  0.0000 |
+| TPC-H 18 ||  1520.13 |  1570.22 |   +3%  ||     0.66 |     0.64 |   -3%  |  0.0033 |
+| TPC-H 19 ||   265.86 |   269.23 |   +1%˄ ||     3.76 |     3.71 |   -1%˄ |  0.0000 |
+| TPC-H 20 ||   391.39 |   398.38 |   +2%˄ ||     2.55 |     2.51 |   -2%˄ |  0.0003 |
+| TPC-H 21 ||  4673.95 |  4776.42 |   +2%  ||     0.21 |     0.21 |   -2%  |  0.0278 |
+| TPC-H 22 ||   415.32 |   417.57 |   +1%˄ ||     2.41 |     2.39 |   -1%˄ |  0.0000 |
++----------++----------+----------+--------++----------+----------+--------+---------+
+| Sum      || 36651.87 | 37246.34 |   +2%  ||          |          |        |         |
+| Geomean  ||          |          |        ||          |          |   -2%  |         |
++----------++----------+----------+--------++----------+----------+--------+---------+
+|    Notes || ˄ Execution stopped due to max runs reached                            |
++----------++----------+----------+--------++----------+----------+--------+---------+
```
</details>

**hyriseBenchmarkTPCH - single-threaded, SF 0.01**
<details>
<summary>
Sum of avg. item runtimes: -0%
 ||
Geometric mean of throughput changes: -0%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview----+------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCH_9dc0fe58708bd47e07932114cbc49e4547f0cd33_st_s01.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCH_4dcd16447406e725257d578bd8e0af9351361606_st_s01.json |
 +--------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                | 9dc0fe58708bd47e07932114cbc49e4547f0cd33-dirty                                                                                                 | 4dcd16447406e725257d578bd8e0af9351361606-dirty                                                                                                 |
 |  benchmark_mode          | Ordered                                                                                                                                        | Ordered                                                                                                                                        |
 |  build_type              | release                                                                                                                                        | release                                                                                                                                        |
 |  chunk_size              | 65535                                                                                                                                          | 65535                                                                                                                                          |
 |  clients                 | 1                                                                                                                                              | 1                                                                                                                                              |
 |  clustering              | None                                                                                                                                           | None                                                                                                                                           |
 |  compiler                | clang 14.0.0                                                                                                                                   | clang 14.0.0                                                                                                                                   |
 |  cores                   | 0                                                                                                                                              | 0                                                                                                                                              |
 |  data_preparation_cores  | 0                                                                                                                                              | 0                                                                                                                                              |
 |  date                    | 2023-02-09 11:02:23                                                                                                                            | 2023-02-09 14:23:50                                                                                                                            |
 |  encoding                | {'default': {'encoding': 'Dictionary'}}                                                                                                        | {'default': {'encoding': 'Dictionary'}}                                                                                                        |
 |  indexes                 | False                                                                                                                                          | False                                                                                                                                          |
 |  max_duration            | 60000000000                                                                                                                                    | 60000000000                                                                                                                                    |
 |  max_runs                | 100                                                                                                                                            | 100                                                                                                                                            |
 |  scale_factor            | 0.009999999776482582                                                                                                                           | 0.009999999776482582                                                                                                                           |
 |  time_unit               | ns                                                                                                                                             | ns                                                                                                                                             |
 |  use_prepared_statements | False                                                                                                                                          | False                                                                                                                                          |
 |  using_scheduler         | False                                                                                                                                          | False                                                                                                                                          |
 |  verify                  | False                                                                                                                                          | False                                                                                                                                          |
 |  warmup_duration         | 1000000000                                                                                                                                     | 1000000000                                                                                                                                     |
 +--------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++----------++----------+---------+--------++----------+----------+--------+---------+
+| Item     || Latency (ms/iter)  | Change || Throughput (iter/s) | Change | p-value |
+|          ||      old |     new |        ||      old |      new |        |         |
++----------++----------+---------+--------++----------+----------+--------+---------+
+| TPC-H 01 ||     4.88 |    4.88 |   +0%˄ ||   204.90 |   204.74 |   -0%˄ |  0.7677 |
+| TPC-H 02 ||     3.74 |    3.74 |   +0%˄ ||   267.22 |   267.06 |   -0%˄ |  0.9927 |
+| TPC-H 03 ||     0.64 |    0.64 |   +1%˄ ||  1567.94 |  1559.09 |   -1%˄ |  0.5842 |
+| TPC-H 04 ||     0.42 |    0.42 |   -0%˄ ||  2374.37 |  2379.27 |   +0%˄ |  0.5653 |
+| TPC-H 05 ||     0.97 |    0.98 |   +1%˄ ||  1024.18 |  1013.75 |   -1%˄ |  0.1994 |
+| TPC-H 06 ||     0.17 |    0.17 |   +1%˄ ||  5729.23 |  5697.88 |   -1%˄ |  0.2793 |
+| TPC-H 07 ||    11.68 |   11.59 |   -1%˄ ||    85.58 |    86.29 |   +1%˄ |  0.8785 |
+| TPC-H 08 ||    15.49 |   15.68 |   +1%˄ ||    64.53 |    63.79 |   -1%˄ |  0.5997 |
+| TPC-H 09 ||     3.78 |    3.55 |   -6%˄ ||   264.63 |   281.35 |   +6%˄ |  0.6827 |
+| TPC-H 10 ||     0.77 |    0.78 |   +1%˄ ||  1293.57 |  1284.09 |   -1%˄ |  0.0861 |
+| TPC-H 11 ||     0.20 |    0.20 |   -2%˄ ||  4895.71 |  4977.88 |   +2%˄ |  0.1793 |
+| TPC-H 12 ||     0.59 |    0.59 |   +0%˄ ||  1680.83 |  1677.89 |   -0%˄ |  0.6385 |
+| TPC-H 13 ||     2.02 |    1.98 |   -2%˄ ||   494.34 |   504.05 |   +2%˄ |  0.0000 |
+| TPC-H 14 ||     0.33 |    0.34 |   +1%˄ ||  2983.93 |  2964.90 |   -1%˄ |  0.5181 |
+| TPC-H 15 ||     1.16 |    1.17 |   +0%˄ ||   856.83 |   854.11 |   -0%˄ |  0.1957 |
+| TPC-H 16 ||     1.98 |    1.99 |   +1%˄ ||   505.19 |   502.12 |   -1%˄ |  0.0252 |
+| TPC-H 17 ||     0.65 |    0.69 |   +6%˄ ||  1525.93 |  1442.05 |   -5%˄ |  0.6424 |
+| TPC-H 18 ||     1.12 |    1.12 |   -0%˄ ||   889.04 |   891.65 |   +0%˄ |  0.0156 |
+| TPC-H 19 ||     5.07 |    5.07 |   +0%˄ ||   197.27 |   197.18 |   -0%˄ |  0.6395 |
+| TPC-H 20 ||     2.13 |    2.14 |   +0%˄ ||   469.53 |   467.58 |   -0%˄ |  0.8660 |
+| TPC-H 21 ||     1.35 |    1.38 |   +2%˄ ||   739.35 |   722.74 |   -2%˄ |  0.6080 |
+| TPC-H 22 ||     0.99 |    0.99 |   +1%˄ ||  1010.37 |  1004.17 |   -1%˄ |  0.0000 |
++----------++----------+---------+--------++----------+----------+--------+---------+
+| Sum      ||    60.15 |   60.10 |   -0%  ||          |          |        |         |
+| Geomean  ||          |         |        ||          |          |   -0%  |         |
++----------++----------+---------+--------++----------+----------+--------+---------+
+|    Notes || ˄ Execution stopped due to max runs reached                           |
++----------++----------+---------+--------++----------+----------+--------+---------+
```
</details>

**hyriseBenchmarkTPCH - multi-threaded, ordered, 1 client, 28 cores, SF 10.0**
<details>
<summary>
Sum of avg. item runtimes: -0%
 ||
Geometric mean of throughput changes: +1%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview---------+----------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                     | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCH_9dc0fe58708bd47e07932114cbc49e4547f0cd33_mt_ordered.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCH_4dcd16447406e725257d578bd8e0af9351361606_mt_ordered.json |
 +-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                     | 9dc0fe58708bd47e07932114cbc49e4547f0cd33-dirty                                                                                                     | 4dcd16447406e725257d578bd8e0af9351361606-dirty                                                                                                     |
 |  benchmark_mode               | Ordered                                                                                                                                            | Ordered                                                                                                                                            |
 |  build_type                   | release                                                                                                                                            | release                                                                                                                                            |
 |  chunk_size                   | 65535                                                                                                                                              | 65535                                                                                                                                              |
 |  clients                      | 1                                                                                                                                                  | 1                                                                                                                                                  |
 |  clustering                   | None                                                                                                                                               | None                                                                                                                                               |
 |  compiler                     | clang 14.0.0                                                                                                                                       | clang 14.0.0                                                                                                                                       |
 |  cores                        | 28                                                                                                                                                 | 28                                                                                                                                                 |
 |  data_preparation_cores       | 0                                                                                                                                                  | 0                                                                                                                                                  |
 |  date                         | 2023-02-09 11:02:51                                                                                                                                | 2023-02-09 14:24:18                                                                                                                                |
 |  encoding                     | {'default': {'encoding': 'Dictionary'}}                                                                                                            | {'default': {'encoding': 'Dictionary'}}                                                                                                            |
 |  indexes                      | False                                                                                                                                              | False                                                                                                                                              |
 |  max_duration                 | 60000000000                                                                                                                                        | 60000000000                                                                                                                                        |
 |  max_runs                     | -1                                                                                                                                                 | -1                                                                                                                                                 |
 |  scale_factor                 | 10.0                                                                                                                                               | 10.0                                                                                                                                               |
 |  time_unit                    | ns                                                                                                                                                 | ns                                                                                                                                                 |
 |  use_prepared_statements      | False                                                                                                                                              | False                                                                                                                                              |
 |  using_scheduler              | True                                                                                                                                               | True                                                                                                                                               |
 |  utilized_cores_per_numa_node | [0, 0, 28]                                                                                                                                         | [0, 0, 28]                                                                                                                                         |
 |  verify                       | False                                                                                                                                              | False                                                                                                                                              |
 |  warmup_duration              | 0                                                                                                                                                  | 0                                                                                                                                                  |
 +-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++----------++----------+----------+--------++----------+----------+--------+----------------------+
+| Item     || Latency (ms/iter)   | Change || Throughput (iter/s) | Change |              p-value |
+|          ||      old |      new |        ||      old |      new |        |                      |
++----------++----------+----------+--------++----------+----------+--------+----------------------+
+| TPC-H 01 ||  4824.89 |  4824.13 |   -0%  ||     0.20 |     0.20 |   +0%  | (run time too short) |
+| TPC-H 02 ||    65.33 |    62.82 |   -4%  ||    14.16 |    14.55 |   +3%  |               0.0002 |
+| TPC-H 03 ||  1134.08 |  1132.76 |   -0%  ||     0.87 |     0.87 |   -0%  | (run time too short) |
+| TPC-H 04 ||   608.13 |   620.52 |   +2%  ||     1.62 |     1.60 |   -1%  | (run time too short) |
+| TPC-H 05 ||  1033.59 |  1017.51 |   -2%  ||     0.95 |     0.97 |   +2%  | (run time too short) |
+| TPC-H 06 ||    77.22 |    71.90 |   -7%  ||    12.12 |    12.98 |   +7%  |               0.0000 |
+| TPC-H 07 ||   468.63 |   460.74 |   -2%  ||     2.10 |     2.13 |   +2%  |               0.0026 |
+| TPC-H 08 ||   402.65 |   403.33 |   +0%  ||     2.45 |     2.45 |   +0%  |               0.7537 |
+| TPC-H 09 ||  2524.32 |  2526.07 |   +0%  ||     0.38 |     0.38 |   +0%  | (run time too short) |
+| TPC-H 10 ||  1622.67 |  1625.75 |   +0%  ||     0.60 |     0.60 |   +0%  | (run time too short) |
+| TPC-H 11 ||    87.07 |    86.06 |   -1%  ||    10.83 |    10.93 |   +1%  |               0.0593 |
+| TPC-H 12 ||   557.98 |   553.20 |   -1%  ||     1.77 |     1.78 |   +1%  |               0.0837 |
+| TPC-H 13 ||  3013.34 |  3021.00 |   +0%  ||     0.32 |     0.32 |   -0%  | (run time too short) |
+| TPC-H 14 ||   172.70 |   171.62 |   -1%  ||     5.62 |     5.65 |   +1%  |               0.1276 |
+| TPC-H 15 ||   170.39 |   169.21 |   -1%  ||     5.70 |     5.73 |   +1%  |               0.1826 |
+| TPC-H 16 ||   782.72 |   785.64 |   +0%  ||     1.27 |     1.25 |   -1%  | (run time too short) |
+| TPC-H 17 ||    99.78 |    93.67 |   -6%  ||     9.55 |    10.15 |   +6%  |               0.0000 |
+| TPC-H 18 ||  2574.98 |  2535.06 |   -2%  ||     0.38 |     0.38 |   +0%  | (run time too short) |
+| TPC-H 19 ||   164.77 |   158.23 |   -4%  ||     5.88 |     6.12 |   +4%  |               0.0000 |
+| TPC-H 20 ||   257.28 |   254.82 |   -1%  ||     3.80 |     3.83 |   +1%  |               0.2195 |
+| TPC-H 21 ||  1206.19 |  1210.71 |   +0%  ||     0.82 |     0.82 |   -0%  |               0.6647 |
+| TPC-H 22 ||   153.54 |   152.47 |   -1%  ||     6.30 |     6.33 |   +1%  |               0.0949 |
++----------++----------+----------+--------++----------+----------+--------+----------------------+
+| Sum      || 22002.26 | 21937.25 |   -0%  ||          |          |        |                      |
+| Geomean  ||          |          |        ||          |          |   +1%  |                      |
++----------++----------+----------+--------++----------+----------+--------+----------------------+
```
</details>

**hyriseBenchmarkTPCH - multi-threaded, shuffled, 28 clients, 28 cores, SF 10.0**
<details>
<summary>
Sum of avg. item runtimes: +0%
 ||
Geometric mean of throughput changes: -0%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview---------+--------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                     | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCH_9dc0fe58708bd47e07932114cbc49e4547f0cd33_mt.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCH_4dcd16447406e725257d578bd8e0af9351361606_mt.json |
 +-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                     | 9dc0fe58708bd47e07932114cbc49e4547f0cd33-dirty                                                                                             | 4dcd16447406e725257d578bd8e0af9351361606-dirty                                                                                             |
 |  benchmark_mode               | Shuffled                                                                                                                                   | Shuffled                                                                                                                                   |
 |  build_type                   | release                                                                                                                                    | release                                                                                                                                    |
 |  chunk_size                   | 65535                                                                                                                                      | 65535                                                                                                                                      |
 |  clients                      | 28                                                                                                                                         | 28                                                                                                                                         |
 |  clustering                   | None                                                                                                                                       | None                                                                                                                                       |
 |  compiler                     | clang 14.0.0                                                                                                                               | clang 14.0.0                                                                                                                               |
 |  cores                        | 28                                                                                                                                         | 28                                                                                                                                         |
 |  data_preparation_cores       | 0                                                                                                                                          | 0                                                                                                                                          |
 |  date                         | 2023-02-09 11:26:36                                                                                                                        | 2023-02-09 14:48:04                                                                                                                        |
 |  encoding                     | {'default': {'encoding': 'Dictionary'}}                                                                                                    | {'default': {'encoding': 'Dictionary'}}                                                                                                    |
 |  indexes                      | False                                                                                                                                      | False                                                                                                                                      |
 |  max_duration                 | 1200000000000                                                                                                                              | 1200000000000                                                                                                                              |
 |  max_runs                     | -1                                                                                                                                         | -1                                                                                                                                         |
 |  scale_factor                 | 10.0                                                                                                                                       | 10.0                                                                                                                                       |
 |  time_unit                    | ns                                                                                                                                         | ns                                                                                                                                         |
 |  use_prepared_statements      | False                                                                                                                                      | False                                                                                                                                      |
 |  using_scheduler              | True                                                                                                                                       | True                                                                                                                                       |
 |  utilized_cores_per_numa_node | [0, 0, 28]                                                                                                                                 | [0, 0, 28]                                                                                                                                 |
 |  verify                       | False                                                                                                                                      | False                                                                                                                                      |
 |  warmup_duration              | 0                                                                                                                                          | 0                                                                                                                                          |
 +-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++----------++----------+----------+--------++----------+----------+--------+---------+
+| Item     || Latency (ms/iter)   | Change || Throughput (iter/s) | Change | p-value |
+|          ||      old |      new |        ||      old |      new |        |         |
++----------++----------+----------+--------++----------+----------+--------+---------+
+| TPC-H 01 ||  5742.71 |  5796.98 |   +1%  ||     0.46 |     0.46 |   -0%  |  0.5179 |
+| TPC-H 02 ||   316.68 |   323.10 |   +2%  ||     0.46 |     0.46 |   +0%  |  0.9293 |
+| TPC-H 03 ||  3806.94 |  3501.48 |   -8%  ||     0.46 |     0.46 |   +0%  |  0.1314 |
+| TPC-H 04 ||  2358.03 |  2270.19 |   -4%  ||     0.46 |     0.46 |   +0%  |  0.5475 |
+| TPC-H 05 ||  4174.43 |  4232.36 |   +1%  ||     0.46 |     0.46 |   -0%  |  0.7914 |
+| TPC-H 06 ||   396.25 |   481.18 |  +21%  ||     0.46 |     0.46 |   +0%  |  0.1194 |
+| TPC-H 07 ||  2585.58 |  2279.71 |  -12%  ||     0.46 |     0.46 |   -0%  |  0.0825 |
+| TPC-H 08 ||  1875.91 |  1993.67 |   +6%  ||     0.46 |     0.46 |   +0%  |  0.4794 |
+| TPC-H 09 ||  5581.79 |  5726.69 |   +3%  ||     0.46 |     0.46 |   +0%  |  0.4856 |
+| TPC-H 10 ||  4995.97 |  4700.44 |   -6%  ||     0.46 |     0.46 |   +0%  |  0.1626 |
+| TPC-H 11 ||   608.49 |   673.55 |  +11%  ||     0.46 |     0.46 |   -0%  |  0.5493 |
+| TPC-H 12 ||  2085.10 |  2167.94 |   +4%  ||     0.46 |     0.46 |   -0%  |  0.5528 |
+| TPC-H 13 ||  5575.89 |  5804.35 |   +4%  ||     0.46 |     0.46 |   -0%  |  0.0581 |
+| TPC-H 14 ||  1013.80 |  1065.62 |   +5%  ||     0.46 |     0.46 |   -0%  |  0.6534 |
+| TPC-H 15 ||   457.50 |   502.39 |  +10%  ||     0.46 |     0.46 |   -0%  |  0.5473 |
+| TPC-H 16 ||  2317.14 |  2288.45 |   -1%  ||     0.46 |     0.46 |   -0%  |  0.8533 |
+| TPC-H 17 ||   656.25 |   583.53 |  -11%  ||     0.46 |     0.46 |   -0%  |  0.5052 |
+| TPC-H 18 ||  3549.71 |  3694.13 |   +4%  ||     0.46 |     0.46 |   +0%  |  0.2032 |
+| TPC-H 19 ||   759.96 |   731.38 |   -4%  ||     0.46 |     0.46 |   +0%  |  0.7593 |
+| TPC-H 20 ||  1164.66 |  1135.32 |   -3%  ||     0.46 |     0.46 |   -0%  |  0.7517 |
+| TPC-H 21 ||  5560.11 |  5583.46 |   +0%  ||     0.46 |     0.46 |   -0%  |  0.9294 |
+| TPC-H 22 ||   861.79 |   993.15 |  +15%  ||     0.46 |     0.46 |   -0%  |  0.2341 |
++----------++----------+----------+--------++----------+----------+--------+---------+
+| Sum      || 56444.70 | 56529.08 |   +0%  ||          |          |        |         |
+| Geomean  ||          |          |        ||          |          |   -0%  |         |
++----------++----------+----------+--------++----------+----------+--------+---------+
```
</details>

**hyriseBenchmarkTPCDS - single-threaded**
<details>
<summary>
Sum of avg. item runtimes: -1%
 ||
Geometric mean of throughput changes: +0%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview---+---------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter               | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCDS_9dc0fe58708bd47e07932114cbc49e4547f0cd33_st.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCDS_4dcd16447406e725257d578bd8e0af9351361606_st.json |
 +-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH               | 9dc0fe58708bd47e07932114cbc49e4547f0cd33-dirty                                                                                              | 4dcd16447406e725257d578bd8e0af9351361606-dirty                                                                                              |
 |  benchmark_mode         | Ordered                                                                                                                                     | Ordered                                                                                                                                     |
 |  build_type             | release                                                                                                                                     | release                                                                                                                                     |
 |  chunk_size             | 65535                                                                                                                                       | 65535                                                                                                                                       |
 |  clients                | 1                                                                                                                                           | 1                                                                                                                                           |
 |  compiler               | clang 14.0.0                                                                                                                                | clang 14.0.0                                                                                                                                |
 |  cores                  | 0                                                                                                                                           | 0                                                                                                                                           |
 |  data_preparation_cores | 0                                                                                                                                           | 0                                                                                                                                           |
 |  date                   | 2023-02-09 11:48:17                                                                                                                         | 2023-02-09 15:09:46                                                                                                                         |
 |  encoding               | {'default': {'encoding': 'Dictionary'}}                                                                                                     | {'default': {'encoding': 'Dictionary'}}                                                                                                     |
 |  indexes                | False                                                                                                                                       | False                                                                                                                                       |
 |  max_duration           | 60000000000                                                                                                                                 | 60000000000                                                                                                                                 |
 |  max_runs               | 100                                                                                                                                         | 100                                                                                                                                         |
 |  time_unit              | ns                                                                                                                                          | ns                                                                                                                                          |
 |  using_scheduler        | False                                                                                                                                       | False                                                                                                                                       |
 |  verify                 | False                                                                                                                                       | False                                                                                                                                       |
 |  warmup_duration        | 1000000000                                                                                                                                  | 1000000000                                                                                                                                  |
 +-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++---------++----------+----------+--------++----------+----------+--------+---------+
+| Item    || Latency (ms/iter)   | Change || Throughput (iter/s) | Change | p-value |
+|         ||      old |      new |        ||      old |      new |        |         |
++---------++----------+----------+--------++----------+----------+--------+---------+
+| 01      ||   263.35 |   261.91 |   -1%˄ ||     3.80 |     3.82 |   +1%˄ |  0.1925 |
+| 03      ||    69.58 |    69.32 |   -0%˄ ||    14.37 |    14.42 |   +0%˄ |  0.2015 |
+| 06      ||   151.18 |   151.04 |   -0%˄ ||     6.61 |     6.62 |   +0%˄ |  0.5783 |
+| 07      ||   302.08 |   300.42 |   -1%˄ ||     3.31 |     3.33 |   +1%˄ |  0.4772 |
+| 09      ||   669.09 |   665.26 |   -1%  ||     1.49 |     1.50 |   +1%  |  0.3278 |
+| 10      ||   130.35 |   132.87 |   +2%˄ ||     7.67 |     7.53 |   -2%˄ |  0.0001 |
+| 13      ||   428.77 |   424.92 |   -1%˄ ||     2.33 |     2.35 |   +1%˄ |  0.0406 |
+| 15      ||   105.77 |   104.94 |   -1%˄ ||     9.45 |     9.53 |   +1%˄ |  0.0249 |
+| 16      ||   154.71 |   156.51 |   +1%˄ ||     6.46 |     6.39 |   -1%˄ |  0.0150 |
+| 17      ||   310.24 |   310.09 |   -0%˄ ||     3.22 |     3.22 |   +0%˄ |  0.8201 |
+| 19      ||   100.95 |    99.84 |   -1%˄ ||     9.91 |    10.02 |   +1%˄ |  0.0000 |
+| 25      ||   165.13 |   164.13 |   -1%˄ ||     6.06 |     6.09 |   +1%˄ |  0.0481 |
+| 26      ||   134.45 |   133.62 |   -1%˄ ||     7.44 |     7.48 |   +1%˄ |  0.2816 |
+| 28      ||   604.30 |   597.31 |   -1%˄ ||     1.65 |     1.67 |   +1%˄ |  0.0000 |
+| 29      ||   485.13 |   470.15 |   -3%˄ ||     2.06 |     2.13 |   +3%˄ |  0.0000 |
+| 31      ||  1292.33 |  1275.06 |   -1%  ||     0.77 |     0.78 |   +1%  |  0.0000 |
+| 32      ||    42.61 |    42.11 |   -1%˄ ||    23.47 |    23.74 |   +1%˄ |  0.0005 |
+| 34      ||   159.72 |   160.25 |   +0%˄ ||     6.26 |     6.24 |   -0%˄ |  0.5944 |
+| 35      ||   615.30 |   611.09 |   -1%  ||     1.63 |     1.64 |   +1%  |  0.0005 |
+| 37      ||   277.23 |   273.43 |   -1%˄ ||     3.61 |     3.66 |   +1%˄ |  0.0654 |
+| 39a     ||  1769.22 |  1709.38 |   -3%  ||     0.57 |     0.59 |   +4%  |  0.0000 |
+| 39b     ||  1716.51 |  1684.39 |   -2%  ||     0.58 |     0.59 |   +2%  |  0.0000 |
+| 41      ||   299.83 |   298.82 |   -0%˄ ||     3.34 |     3.35 |   +0%˄ |  0.0113 |
+| 42      ||    82.54 |    82.33 |   -0%˄ ||    12.11 |    12.15 |   +0%˄ |  0.5219 |
+| 43      ||   948.80 |   945.59 |   -0%  ||     1.05 |     1.06 |   +0%  |  0.3520 |
+| 45      ||   115.41 |   114.51 |   -1%˄ ||     8.66 |     8.73 |   +1%˄ |  0.0000 |
+| 48      ||  1045.52 |  1044.90 |   -0%  ||     0.96 |     0.96 |   +0%  |  0.9065 |
+| 50      ||   110.09 |   110.55 |   +0%˄ ||     9.08 |     9.05 |   -0%˄ |  0.0193 |
+| 52      ||    80.90 |    81.35 |   +1%˄ ||    12.36 |    12.29 |   -1%˄ |  0.0952 |
+| 55      ||    77.28 |    77.88 |   +1%˄ ||    12.94 |    12.84 |   -1%˄ |  0.0032 |
+| 62      ||   549.44 |   547.60 |   -0%˄ ||     1.82 |     1.83 |   +0%˄ |  0.0501 |
+| 65      ||  1776.68 |  1770.83 |   -0%  ||     0.56 |     0.56 |   +0%  |  0.5200 |
+| 69      ||   120.56 |   123.93 |   +3%˄ ||     8.29 |     8.07 |   -3%˄ |  0.0000 |
+| 73      ||    77.18 |    79.70 |   +3%˄ ||    12.96 |    12.55 |   -3%˄ |  0.0000 |
+| 79      ||   472.93 |   473.40 |   +0%˄ ||     2.11 |     2.11 |   -0%˄ |  0.5033 |
+| 81      ||   208.44 |   201.87 |   -3%˄ ||     4.80 |     4.95 |   +3%˄ |  0.0000 |
+| 82      ||   356.52 |   356.56 |   +0%˄ ||     2.80 |     2.80 |   -0%˄ |  0.9864 |
+| 83      ||    40.68 |    40.85 |   +0%˄ ||    24.58 |    24.48 |   -0%˄ |  0.7764 |
+| 85      ||   134.34 |   133.75 |   -0%˄ ||     7.44 |     7.48 |   +0%˄ |  0.0845 |
+| 88      ||   625.01 |   637.24 |   +2%  ||     1.60 |     1.57 |   -2%  |  0.0000 |
+| 91      ||    15.62 |    15.75 |   +1%˄ ||    64.03 |    63.47 |   -1%˄ |  0.0019 |
+| 92      ||    35.18 |    34.82 |   -1%˄ ||    28.42 |    28.72 |   +1%˄ |  0.0001 |
+| 93      ||  3903.83 |  3884.54 |   -0%  ||     0.26 |     0.26 |   +0%  |  0.3238 |
+| 94      ||    98.56 |    96.25 |   -2%˄ ||    10.15 |    10.39 |   +2%˄ |  0.0000 |
+| 95      ||  9012.62 |  8858.33 |   -2%  ||     0.11 |     0.11 |   +2%  |       ˅ |
+| 96      ||    57.87 |    58.87 |   +2%˄ ||    17.28 |    16.98 |   -2%˄ |  0.0391 |
+| 97      ||  3277.53 |  3251.98 |   -1%  ||     0.31 |     0.31 |   +1%  |  0.2566 |
+| 99      ||  1048.92 |  1056.17 |   +1%  ||     0.95 |     0.95 |   -1%  |  0.0003 |
++---------++----------+----------+--------++----------+----------+--------+---------+
+| Sum     || 34520.26 | 34176.40 |   -1%  ||          |          |        |         |
+| Geomean ||          |          |        ||          |          |   +0%  |         |
++---------++----------+----------+--------++----------+----------+--------+---------+
+|   Notes || ˄ Execution stopped due to max runs reached                            |
+|         || ˅ Insufficient number of runs for p-value calculation                  |
++---------++----------+----------+--------++----------+----------+--------+---------+
```
</details>

**hyriseBenchmarkTPCDS - multi-threaded, shuffled, 28 clients, 28 cores**
<details>
<summary>
Sum of avg. item runtimes: +0%
 ||
Geometric mean of throughput changes: +0%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview---------+---------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                     | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCDS_9dc0fe58708bd47e07932114cbc49e4547f0cd33_mt.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCDS_4dcd16447406e725257d578bd8e0af9351361606_mt.json |
 +-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                     | 9dc0fe58708bd47e07932114cbc49e4547f0cd33-dirty                                                                                              | 4dcd16447406e725257d578bd8e0af9351361606-dirty                                                                                              |
 |  benchmark_mode               | Shuffled                                                                                                                                    | Shuffled                                                                                                                                    |
 |  build_type                   | release                                                                                                                                     | release                                                                                                                                     |
 |  chunk_size                   | 65535                                                                                                                                       | 65535                                                                                                                                       |
 |  clients                      | 28                                                                                                                                          | 28                                                                                                                                          |
 |  compiler                     | clang 14.0.0                                                                                                                                | clang 14.0.0                                                                                                                                |
 |  cores                        | 28                                                                                                                                          | 28                                                                                                                                          |
 |  data_preparation_cores       | 0                                                                                                                                           | 0                                                                                                                                           |
 |  date                         | 2023-02-09 12:14:24                                                                                                                         | 2023-02-09 15:35:51                                                                                                                         |
 |  encoding                     | {'default': {'encoding': 'Dictionary'}}                                                                                                     | {'default': {'encoding': 'Dictionary'}}                                                                                                     |
 |  indexes                      | False                                                                                                                                       | False                                                                                                                                       |
 |  max_duration                 | 1200000000000                                                                                                                               | 1200000000000                                                                                                                               |
 |  max_runs                     | -1                                                                                                                                          | -1                                                                                                                                          |
 |  time_unit                    | ns                                                                                                                                          | ns                                                                                                                                          |
 |  using_scheduler              | True                                                                                                                                        | True                                                                                                                                        |
 |  utilized_cores_per_numa_node | [0, 0, 28]                                                                                                                                  | [0, 0, 28]                                                                                                                                  |
 |  verify                       | False                                                                                                                                       | False                                                                                                                                       |
 |  warmup_duration              | 0                                                                                                                                           | 0                                                                                                                                           |
 +-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++---------++----------+----------+--------++----------+----------+--------+---------+
+| Item    || Latency (ms/iter)   | Change || Throughput (iter/s) | Change | p-value |
+|         ||      old |      new |        ||      old |      new |        |         |
++---------++----------+----------+--------++----------+----------+--------+---------+
+| 01      ||   643.47 |   726.21 |  +13%  ||     0.47 |     0.47 |   +0%  |  0.2911 |
+| 03      ||   211.18 |   307.04 |  +45%  ||     0.47 |     0.47 |   -0%  |  0.0878 |
+| 06      ||   598.75 |   605.09 |   +1%  ||     0.47 |     0.47 |   +0%  |  0.9370 |
+| 07      ||   729.66 |   864.39 |  +18%  ||     0.47 |     0.47 |   -0%  |  0.0768 |
+| 09      ||   552.54 |   515.32 |   -7%  ||     0.47 |     0.47 |   -0%  |  0.5717 |
+| 10      ||   499.46 |   532.62 |   +7%  ||     0.47 |     0.47 |   -0%  |  0.7290 |
+| 13      ||  1631.59 |  1531.26 |   -6%  ||     0.47 |     0.47 |   -0%  |  0.4593 |
+| 15      ||   429.38 |   565.00 |  +32%  ||     0.47 |     0.47 |   -0%  |  0.0787 |
+| 16      ||   658.71 |   849.10 |  +29%  ||     0.47 |     0.47 |   +0%  |  0.0765 |
+| 17      ||  1033.04 |  1171.24 |  +13%  ||     0.47 |     0.47 |   -0%  |  0.2657 |
+| 19      ||   453.87 |   427.16 |   -6%  ||     0.47 |     0.47 |   -0%  |  0.6672 |
+| 25      ||   788.56 |   733.79 |   -7%  ||     0.47 |     0.47 |   -0%  |  0.5656 |
+| 26      ||   500.46 |   585.92 |  +17%  ||     0.47 |     0.47 |   -0%  |  0.2614 |
+| 28      ||   539.06 |   686.21 |  +27%  ||     0.47 |     0.47 |   -0%  |  0.0582 |
+| 29      ||  1363.01 |  1254.02 |   -8%  ||     0.47 |     0.47 |   -0%  |  0.3172 |
+| 31      ||  1940.79 |  1802.00 |   -7%  ||     0.47 |     0.47 |   +0%  |  0.3514 |
+| 32      ||   241.96 |   253.99 |   +5%  ||     0.47 |     0.47 |   -0%  |  0.8241 |
+| 34      ||   475.99 |   430.12 |  -10%  ||     0.47 |     0.47 |   -0%  |  0.4694 |
+| 35      ||  2030.25 |  1894.98 |   -7%  ||     0.47 |     0.47 |   +0%  |  0.3766 |
+| 37      ||   561.88 |   517.46 |   -8%  ||     0.47 |     0.47 |   -0%  |  0.5143 |
+| 39a     ||  2141.99 |  2157.05 |   +1%  ||     0.47 |     0.47 |   +0%  |  0.9027 |
+| 39b     ||  2216.30 |  2139.42 |   -3%  ||     0.47 |     0.47 |   -0%  |  0.5111 |
+| 41      ||  3033.01 |  2909.31 |   -4%  ||     0.47 |     0.47 |   +0%  |  0.4267 |
+| 42      ||   363.13 |   408.25 |  +12%  ||     0.47 |     0.47 |   -0%  |  0.5629 |
+| 43      ||  1479.67 |  1331.76 |  -10%  ||     0.47 |     0.47 |   +0%  |  0.1372 |
+| 45      ||   600.21 |   535.09 |  -11%  ||     0.47 |     0.47 |   +0%  |  0.4601 |
+| 48      ||  2768.38 |  2585.54 |   -7%  ||     0.47 |     0.47 |   +0%  |  0.3071 |
+| 50      ||   482.04 |   577.87 |  +20%  ||     0.47 |     0.47 |   -0%  |  0.1862 |
+| 52      ||   331.22 |   405.97 |  +23%  ||     0.47 |     0.47 |   -0%  |  0.2824 |
+| 55      ||   326.45 |   322.79 |   -1%  ||     0.47 |     0.47 |   -0%  |  0.9596 |
+| 62      ||   883.95 |   861.56 |   -3%  ||     0.47 |     0.47 |   -0%  |  0.7603 |
+| 65      ||  3597.08 |  3687.85 |   +3%  ||     0.47 |     0.47 |   +0%  |  0.2974 |
+| 69      ||   577.13 |   567.55 |   -2%  ||     0.47 |     0.47 |   -0%  |  0.9132 |
+| 73      ||   278.15 |   322.32 |  +16%  ||     0.47 |     0.47 |   -0%  |  0.4084 |
+| 79      ||  1149.12 |  1091.94 |   -5%  ||     0.47 |     0.47 |   -0%  |  0.4154 |
+| 81      ||   834.17 |   694.58 |  -17%  ||     0.47 |     0.47 |   -0%  |  0.0974 |
+| 82      ||   679.73 |   792.75 |  +17%  ||     0.47 |     0.47 |   +0%  |  0.1621 |
+| 83      ||   304.63 |   260.20 |  -15%  ||     0.47 |     0.47 |   -0%  |  0.3624 |
+| 85      ||   611.25 |   786.68 |  +29%  ||     0.47 |     0.47 |   +0%  |  0.0389 |
+| 88      ||   705.17 |   795.64 |  +13%  ||     0.47 |     0.47 |   +0%  |  0.3275 |
+| 91      ||   208.40 |   155.80 |  -25%  ||     0.47 |     0.47 |   -0%  |  0.2672 |
+| 92      ||   226.82 |   311.82 |  +37%  ||     0.47 |     0.47 |   -0%  |  0.1090 |
+| 93      ||  2479.94 |  2312.46 |   -7%  ||     0.47 |     0.47 |   -0%  |  0.2414 |
+| 94      ||   695.34 |   613.90 |  -12%  ||     0.47 |     0.47 |   -0%  |  0.4239 |
+| 95      ||  7907.90 |  8123.48 |   +3%  ||     0.47 |     0.46 |   -0%  |  0.2381 |
+| 96      ||   277.31 |   185.27 |  -33%  ||     0.47 |     0.47 |   -0%  |  0.0844 |
+| 97      ||  4412.14 |  4279.93 |   -3%  ||     0.47 |     0.47 |   -0%  |  0.3480 |
+| 99      ||  1312.32 |  1313.88 |   +0%  ||     0.47 |     0.47 |   +0%  |  0.9837 |
++---------++----------+----------+--------++----------+----------+--------+---------+
+| Sum     || 56766.56 | 56783.58 |   +0%  ||          |          |        |         |
+| Geomean ||          |          |        ||          |          |   +0%  |         |
++---------++----------+----------+--------++----------+----------+--------+---------+
```
</details>

**hyriseBenchmarkTPCC - single-threaded**
<details>
<summary>
Sum of avg. item runtimes: +0%
 ||
Geometric mean of throughput changes: -0%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview---+--------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter               | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCC_9dc0fe58708bd47e07932114cbc49e4547f0cd33_st.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCC_4dcd16447406e725257d578bd8e0af9351361606_st.json |
 +-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH               | 9dc0fe58708bd47e07932114cbc49e4547f0cd33-dirty                                                                                             | 4dcd16447406e725257d578bd8e0af9351361606-dirty                                                                                             |
 |  benchmark_mode         | Shuffled                                                                                                                                   | Shuffled                                                                                                                                   |
 |  build_type             | release                                                                                                                                    | release                                                                                                                                    |
 |  chunk_size             | 65535                                                                                                                                      | 65535                                                                                                                                      |
 |  clients                | 1                                                                                                                                          | 1                                                                                                                                          |
 |  compiler               | clang 14.0.0                                                                                                                               | clang 14.0.0                                                                                                                               |
 |  cores                  | 0                                                                                                                                          | 0                                                                                                                                          |
 |  data_preparation_cores | 0                                                                                                                                          | 0                                                                                                                                          |
 |  date                   | 2023-02-09 12:34:54                                                                                                                        | 2023-02-09 15:56:20                                                                                                                        |
 |  encoding               | {'default': {'encoding': 'Dictionary'}}                                                                                                    | {'default': {'encoding': 'Dictionary'}}                                                                                                    |
 |  indexes                | False                                                                                                                                      | False                                                                                                                                      |
 |  max_duration           | 60000000000                                                                                                                                | 60000000000                                                                                                                                |
 |  max_runs               | -1                                                                                                                                         | -1                                                                                                                                         |
 |  scale_factor           | 1                                                                                                                                          | 1                                                                                                                                          |
 |  time_unit              | ns                                                                                                                                         | ns                                                                                                                                         |
 |  using_scheduler        | False                                                                                                                                      | False                                                                                                                                      |
 |  verify                 | False                                                                                                                                      | False                                                                                                                                      |
 |  warmup_duration        | 0                                                                                                                                          | 0                                                                                                                                          |
 +-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++--------------++----------+---------+--------++----------+----------+--------+---------+
+| Item         || Latency (ms/iter)  | Change || Throughput (iter/s) | Change | p-value |
+|              ||      old |     new |        ||      old |      new |        |         |
++--------------++----------+---------+--------++----------+----------+--------+---------+
+| Delivery     ||    23.42 |   23.40 |   -0%  ||     4.20 |     4.20 |   +0%  |  0.7764 |
+| New-Order    ||    16.60 |   16.65 |   +0%  ||    47.39 |    47.20 |   -0%  |  0.7060 |
+| Order-Status ||     1.10 |    1.10 |   -0%  ||     4.20 |     4.18 |   -0%  |  0.9375 |
+| Payment      ||     2.07 |    2.10 |   +1%  ||    45.21 |    45.12 |   -0%  |  0.0070 |
+| Stock-Level  ||     3.61 |    3.61 |   -0%  ||     4.20 |     4.20 |   +0%  |  0.7777 |
++--------------++----------+---------+--------++----------+----------+--------+---------+
+| Sum          ||    46.80 |   46.84 |   +0%  ||          |          |        |         |
+| Geomean      ||          |         |        ||          |          |   -0%  |         |
++--------------++----------+---------+--------++----------+----------+--------+---------+
```
</details>

**hyriseBenchmarkTPCC - multi-threaded, shuffled, 28 clients, 28 cores**
<details>
<summary>
Sum of avg. item runtimes: +1%
 ||
Geometric mean of throughput changes: -1%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview---------+--------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                     | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCC_9dc0fe58708bd47e07932114cbc49e4547f0cd33_mt.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCC_4dcd16447406e725257d578bd8e0af9351361606_mt.json |
 +-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                     | 9dc0fe58708bd47e07932114cbc49e4547f0cd33-dirty                                                                                             | 4dcd16447406e725257d578bd8e0af9351361606-dirty                                                                                             |
 |  benchmark_mode               | Shuffled                                                                                                                                   | Shuffled                                                                                                                                   |
 |  build_type                   | release                                                                                                                                    | release                                                                                                                                    |
 |  chunk_size                   | 65535                                                                                                                                      | 65535                                                                                                                                      |
 |  clients                      | 28                                                                                                                                         | 28                                                                                                                                         |
 |  compiler                     | clang 14.0.0                                                                                                                               | clang 14.0.0                                                                                                                               |
 |  cores                        | 28                                                                                                                                         | 28                                                                                                                                         |
 |  data_preparation_cores       | 0                                                                                                                                          | 0                                                                                                                                          |
 |  date                         | 2023-02-09 12:35:55                                                                                                                        | 2023-02-09 15:57:21                                                                                                                        |
 |  encoding                     | {'default': {'encoding': 'Dictionary'}}                                                                                                    | {'default': {'encoding': 'Dictionary'}}                                                                                                    |
 |  indexes                      | False                                                                                                                                      | False                                                                                                                                      |
 |  max_duration                 | 1200000000000                                                                                                                              | 1200000000000                                                                                                                              |
 |  max_runs                     | -1                                                                                                                                         | -1                                                                                                                                         |
 |  scale_factor                 | 1                                                                                                                                          | 1                                                                                                                                          |
 |  time_unit                    | ns                                                                                                                                         | ns                                                                                                                                         |
 |  using_scheduler              | True                                                                                                                                       | True                                                                                                                                       |
 |  utilized_cores_per_numa_node | [0, 0, 28]                                                                                                                                 | [0, 0, 28]                                                                                                                                 |
 |  verify                       | False                                                                                                                                      | False                                                                                                                                      |
 |  warmup_duration              | 0                                                                                                                                          | 0                                                                                                                                          |
 +-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++--------------++----------+---------+--------++----------+----------+--------+---------+
+| Item         || Latency (ms/iter)  | Change || Throughput (iter/s) | Change | p-value |
+|              ||      old |     new |        ||      old |      new |        |         |
++--------------++----------+---------+--------++----------+----------+--------+---------+
+| Delivery     ||   211.48 |  213.11 |   +1%  ||     4.48 |     4.45 |   -1%  |  0.2703 |
+|    unsucc.:  ||     3.62 |    3.55 |   -2%  ||    64.94 |    64.77 |   -0%  |         |
+| New-Order    ||    55.24 |   55.86 |   +1%  ||   139.22 |   138.02 |   -1%  |  0.0000 |
+|    unsucc.:  ||     4.32 |    4.36 |   +1%  ||   641.82 |   640.71 |   -0%  |         |
+| Order-Status ||     7.40 |    7.41 |   +0%  ||    69.43 |    69.22 |   -0%  |  0.5856 |
+| Payment      ||     9.34 |    9.49 |   +2%  ||    21.06 |    20.95 |   -1%  |  0.0059 |
+|    unsucc.:  ||     3.92 |    3.98 |   +1%  ||   725.27 |   723.17 |   -0%  |         |
+| Stock-Level  ||    16.55 |   16.69 |   +1%  ||    69.43 |    69.22 |   -0%  |  0.0127 |
++--------------++----------+---------+--------++----------+----------+--------+---------+
+| Sum          ||   300.00 |  302.56 |   +1%  ||          |          |        |         |
+| Geomean      ||          |         |        ||          |          |   -1%  |         |
++--------------++----------+---------+--------++----------+----------+--------+---------+
```
</details>

**hyriseBenchmarkJoinOrder - single-threaded**
<details>
<summary>
Sum of avg. item runtimes: -2%
 ||
Geometric mean of throughput changes: +1%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview---+-------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter               | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkJoinOrder_9dc0fe58708bd47e07932114cbc49e4547f0cd33_st.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkJoinOrder_4dcd16447406e725257d578bd8e0af9351361606_st.json |
 +-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH               | 9dc0fe58708bd47e07932114cbc49e4547f0cd33-dirty                                                                                                  | 4dcd16447406e725257d578bd8e0af9351361606-dirty                                                                                                  |
 |  benchmark_mode         | Ordered                                                                                                                                         | Ordered                                                                                                                                         |
 |  build_type             | release                                                                                                                                         | release                                                                                                                                         |
 |  chunk_size             | 65535                                                                                                                                           | 65535                                                                                                                                           |
 |  clients                | 1                                                                                                                                               | 1                                                                                                                                               |
 |  compiler               | clang 14.0.0                                                                                                                                    | clang 14.0.0                                                                                                                                    |
 |  cores                  | 0                                                                                                                                               | 0                                                                                                                                               |
 |  data_preparation_cores | 0                                                                                                                                               | 0                                                                                                                                               |
 |  date                   | 2023-02-09 12:56:02                                                                                                                             | 2023-02-09 16:17:28                                                                                                                             |
 |  encoding               | {'default': {'encoding': 'Dictionary'}}                                                                                                         | {'default': {'encoding': 'Dictionary'}}                                                                                                         |
 |  indexes                | False                                                                                                                                           | False                                                                                                                                           |
 |  max_duration           | 60000000000                                                                                                                                     | 60000000000                                                                                                                                     |
 |  max_runs               | 100                                                                                                                                             | 100                                                                                                                                             |
 |  time_unit              | ns                                                                                                                                              | ns                                                                                                                                              |
 |  using_scheduler        | False                                                                                                                                           | False                                                                                                                                           |
 |  verify                 | False                                                                                                                                           | False                                                                                                                                           |
 |  warmup_duration        | 1000000000                                                                                                                                      | 1000000000                                                                                                                                      |
 +-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++---------++----------+----------+--------++----------+----------+--------+---------+
+| Item    || Latency (ms/iter)   | Change || Throughput (iter/s) | Change | p-value |
+|         ||      old |      new |        ||      old |      new |        |         |
++---------++----------+----------+--------++----------+----------+--------+---------+
+| 10a     ||   167.17 |   165.82 |   -1%˄ ||     5.98 |     6.03 |   +1%˄ |  0.0001 |
+| 10b     ||   116.68 |   116.18 |   -0%˄ ||     8.57 |     8.61 |   +0%˄ |  0.0683 |
+| 10c     ||   321.38 |   317.99 |   -1%˄ ||     3.11 |     3.14 |   +1%˄ |  0.0492 |
+| 11a     ||    15.22 |    15.20 |   -0%˄ ||    65.71 |    65.77 |   +0%˄ |  0.6231 |
+| 11b     ||    15.04 |    15.02 |   -0%˄ ||    66.46 |    66.55 |   +0%˄ |  0.0033 |
+| 11c     ||    20.58 |    20.59 |   +0%˄ ||    48.59 |    48.56 |   -0%˄ |  0.6079 |
+| 11d     ||    23.48 |    23.63 |   +1%˄ ||    42.58 |    42.32 |   -1%˄ |  0.0000 |
+| 12a     ||    48.69 |    48.31 |   -1%˄ ||    20.54 |    20.70 |   +1%˄ |  0.0000 |
+| 12b     ||    29.36 |    29.15 |   -1%˄ ||    34.06 |    34.30 |   +1%˄ |  0.0002 |
+| 12c     ||    83.76 |    83.77 |   +0%˄ ||    11.94 |    11.94 |   -0%˄ |  0.9379 |
+| 13a     ||   275.06 |   272.54 |   -1%˄ ||     3.64 |     3.67 |   +1%˄ |  0.0000 |
+| 13b     ||   153.60 |   152.19 |   -1%˄ ||     6.51 |     6.57 |   +1%˄ |  0.0000 |
+| 13c     ||   115.88 |   115.89 |   +0%˄ ||     8.63 |     8.63 |   -0%˄ |  0.8110 |
+| 13d     ||   604.05 |   604.43 |   +0%˄ ||     1.66 |     1.65 |   -0%˄ |  0.8361 |
+| 14a     ||   435.88 |   415.96 |   -5%˄ ||     2.29 |     2.40 |   +5%˄ |  0.0000 |
+| 14b     ||   246.80 |   232.13 |   -6%˄ ||     4.05 |     4.31 |   +6%˄ |  0.0000 |
+| 14c     ||   525.10 |   485.41 |   -8%˄ ||     1.90 |     2.06 |   +8%˄ |  0.0000 |
+| 15a     ||    90.09 |    81.22 |  -10%˄ ||    11.10 |    12.31 |  +11%˄ |  0.0000 |
+| 15b     ||    92.75 |    80.12 |  -14%˄ ||    10.78 |    12.48 |  +16%˄ |  0.0000 |
+| 15c     ||    96.41 |    85.85 |  -11%˄ ||    10.37 |    11.65 |  +12%˄ |  0.0000 |
+| 15d     ||    92.84 |    82.08 |  -12%˄ ||    10.77 |    12.18 |  +13%˄ |  0.0000 |
+| 16a     ||  2328.34 |  2221.81 |   -5%  ||     0.43 |     0.45 |   +5%  |  0.0000 |
+| 16b     ||  3457.15 |  3294.99 |   -5%  ||     0.29 |     0.30 |   +5%  |  0.0008 |
+| 16c     ||  2408.14 |  2326.03 |   -3%  ||     0.42 |     0.43 |   +4%  |  0.0025 |
+| 16d     ||  2325.07 |  2291.14 |   -1%  ||     0.43 |     0.44 |   +1%  |  0.0101 |
+| 17a     ||   585.19 |   578.65 |   -1%˄ ||     1.71 |     1.73 |   +1%˄ |  0.0000 |
+| 17b     ||   469.27 |   457.73 |   -2%˄ ||     2.13 |     2.18 |   +3%˄ |  0.0000 |
+| 17c     ||   435.58 |   434.48 |   -0%˄ ||     2.30 |     2.30 |   +0%˄ |  0.0000 |
+| 17d     ||   515.24 |   513.74 |   -0%˄ ||     1.94 |     1.95 |   +0%˄ |  0.0000 |
+| 17e     ||  1578.12 |  1581.24 |   +0%  ||     0.63 |     0.63 |   -0%  |  0.2596 |
+| 17f     ||   937.09 |   939.71 |   +0%  ||     1.07 |     1.06 |   -0%  |  0.0000 |
+| 18a     ||   597.03 |   595.76 |   -0%˄ ||     1.67 |     1.68 |   +0%˄ |  0.0286 |
+| 18b     ||   112.86 |   112.08 |   -1%˄ ||     8.86 |     8.92 |   +1%˄ |  0.0000 |
+| 18c     ||   563.35 |   561.15 |   -0%˄ ||     1.78 |     1.78 |   +0%˄ |  0.0000 |
+| 19a     ||   185.91 |   184.84 |   -1%˄ ||     5.38 |     5.41 |   +1%˄ |  0.0000 |
+| 19b     ||   126.48 |   125.59 |   -1%˄ ||     7.91 |     7.96 |   +1%˄ |  0.0000 |
+| 19c     ||   198.82 |   197.13 |   -1%˄ ||     5.03 |     5.07 |   +1%˄ |  0.0000 |
+| 19d     ||   725.04 |   743.92 |   +3%  ||     1.38 |     1.34 |   -3%  |  0.0000 |
+| 1a      ||     9.01 |     9.00 |   -0%˄ ||   110.98 |   111.03 |   +0%˄ |  0.7655 |
+| 1b      ||     8.41 |     8.41 |   -0%˄ ||   118.93 |   118.93 |   +0%˄ |  0.9907 |
+| 1c      ||     9.53 |     9.46 |   -1%˄ ||   104.96 |   105.69 |   +1%˄ |  0.0129 |
+| 1d      ||     8.37 |     8.40 |   +0%˄ ||   119.51 |   118.98 |   -0%˄ |  0.0000 |
+| 20a     ||   394.08 |   390.99 |   -1%˄ ||     2.54 |     2.56 |   +1%˄ |  0.0000 |
+| 20b     ||   230.60 |   229.58 |   -0%˄ ||     4.34 |     4.36 |   +0%˄ |  0.0000 |
+| 20c     ||   223.21 |   222.09 |   -1%˄ ||     4.48 |     4.50 |   +1%˄ |  0.0000 |
+| 21a     ||    35.28 |    35.06 |   -1%˄ ||    28.35 |    28.52 |   +1%˄ |  0.0000 |
+| 21b     ||    19.33 |    19.32 |   -0%˄ ||    51.73 |    51.77 |   +0%˄ |  0.2866 |
+| 21c     ||    34.90 |    34.79 |   -0%˄ ||    28.65 |    28.75 |   +0%˄ |  0.0000 |
+| 22a     ||   196.30 |   195.42 |   -0%˄ ||     5.09 |     5.12 |   +0%˄ |  0.0000 |
+| 22b     ||   142.94 |   142.19 |   -1%˄ ||     7.00 |     7.03 |   +1%˄ |  0.0000 |
+| 22c     ||   491.11 |   493.84 |   +1%˄ ||     2.04 |     2.02 |   -1%˄ |  0.0000 |
+| 22d     ||   906.06 |   895.69 |   -1%  ||     1.10 |     1.12 |   +1%  |  0.0001 |
+| 23a     ||    42.86 |    42.87 |   +0%˄ ||    23.33 |    23.32 |   -0%˄ |  0.9262 |
+| 23b     ||    44.70 |    44.62 |   -0%˄ ||    22.37 |    22.41 |   +0%˄ |  0.0250 |
+| 23c     ||    85.73 |    85.65 |   -0%˄ ||    11.66 |    11.68 |   +0%˄ |  0.0382 |
+| 24a     ||   145.26 |   144.27 |   -1%˄ ||     6.88 |     6.93 |   +1%˄ |  0.0000 |
+| 24b     ||   123.59 |   122.85 |   -1%˄ ||     8.09 |     8.14 |   +1%˄ |  0.0000 |
+| 25a     ||   277.70 |   275.96 |   -1%˄ ||     3.60 |     3.62 |   +1%˄ |  0.0000 |
+| 25b     ||   113.57 |   113.17 |   -0%˄ ||     8.80 |     8.84 |   +0%˄ |  0.0000 |
+| 25c     ||   917.04 |   904.87 |   -1%  ||     1.09 |     1.11 |   +1%  |  0.0000 |
+| 26a     ||   165.07 |   164.33 |   -0%˄ ||     6.06 |     6.09 |   +0%˄ |  0.0000 |
+| 26b     ||   131.95 |   131.94 |   -0%˄ ||     7.58 |     7.58 |   +0%˄ |  0.9791 |
+| 26c     ||   235.78 |   234.32 |   -1%˄ ||     4.24 |     4.27 |   +1%˄ |  0.0000 |
+| 27a     ||    23.21 |    23.21 |   -0%˄ ||    43.07 |    43.08 |   +0%˄ |  0.9514 |
+| 27b     ||    22.66 |    22.83 |   +1%˄ ||    44.13 |    43.80 |   -1%˄ |  0.0003 |
+| 27c     ||    34.90 |    34.86 |   -0%˄ ||    28.65 |    28.69 |   +0%˄ |  0.1911 |
+| 28a     ||   290.30 |   289.43 |   -0%˄ ||     3.44 |     3.46 |   +0%˄ |  0.0000 |
+| 28b     ||    37.76 |    37.38 |   -1%˄ ||    26.48 |    26.75 |   +1%˄ |  0.0000 |
+| 28c     ||   328.50 |   327.87 |   -0%˄ ||     3.04 |     3.05 |   +0%˄ |  0.0000 |
+| 29a     ||   102.02 |   102.25 |   +0%˄ ||     9.80 |     9.78 |   -0%˄ |  0.0261 |
+| 29b     ||    76.62 |    76.49 |   -0%˄ ||    13.05 |    13.07 |   +0%˄ |  0.1545 |
+| 29c     ||   149.06 |   148.41 |   -0%˄ ||     6.71 |     6.74 |   +0%˄ |  0.0000 |
+| 2a      ||    46.30 |    46.07 |   -1%˄ ||    21.60 |    21.71 |   +1%˄ |  0.0000 |
+| 2b      ||    37.58 |    37.58 |   -0%˄ ||    26.61 |    26.61 |   +0%˄ |  0.9320 |
+| 2c      ||    21.92 |    21.79 |   -1%˄ ||    45.62 |    45.89 |   +1%˄ |  0.0000 |
+| 2d      ||    64.94 |    65.20 |   +0%˄ ||    15.40 |    15.34 |   -0%˄ |  0.0000 |
+| 30a     ||   149.26 |   148.56 |   -0%˄ ||     6.70 |     6.73 |   +0%˄ |  0.0000 |
+| 30b     ||   128.14 |   127.36 |   -1%˄ ||     7.80 |     7.85 |   +1%˄ |  0.0000 |
+| 30c     ||   375.27 |   372.45 |   -1%˄ ||     2.66 |     2.68 |   +1%˄ |  0.0000 |
+| 31a     ||   146.49 |   145.85 |   -0%˄ ||     6.83 |     6.86 |   +0%˄ |  0.0000 |
+| 31b     ||   125.15 |   124.38 |   -1%˄ ||     7.99 |     8.04 |   +1%˄ |  0.0000 |
+| 31c     ||   170.61 |   169.64 |   -1%˄ ||     5.86 |     5.89 |   +1%˄ |  0.0000 |
+| 32a     ||    12.91 |    12.91 |   -0%˄ ||    77.43 |    77.46 |   +0%˄ |  0.4853 |
+| 32b     ||    30.71 |    30.74 |   +0%˄ ||    32.56 |    32.53 |   -0%˄ |  0.2646 |
+| 33a     ||    19.42 |    19.31 |   -1%˄ ||    51.50 |    51.77 |   +1%˄ |  0.0002 |
+| 33b     ||    18.80 |    18.84 |   +0%˄ ||    53.20 |    53.07 |   -0%˄ |  0.0865 |
+| 33c     ||    22.67 |    22.65 |   -0%˄ ||    44.11 |    44.15 |   +0%˄ |  0.1733 |
+| 3a      ||   122.37 |   122.35 |   -0%˄ ||     8.17 |     8.17 |   +0%˄ |  0.8655 |
+| 3b      ||    12.75 |    12.77 |   +0%˄ ||    78.44 |    78.30 |   -0%˄ |  0.3822 |
+| 3c      ||   429.46 |   428.30 |   -0%˄ ||     2.33 |     2.33 |   +0%˄ |  0.0145 |
+| 4a      ||   112.29 |   112.72 |   +0%˄ ||     8.90 |     8.87 |   -0%˄ |  0.0150 |
+| 4b      ||    11.63 |    11.61 |   -0%˄ ||    85.97 |    86.15 |   +0%˄ |  0.3336 |
+| 4c      ||   124.18 |   124.63 |   +0%˄ ||     8.05 |     8.02 |   -0%˄ |  0.0143 |
+| 5a      ||    53.10 |    53.17 |   +0%˄ ||    18.83 |    18.81 |   -0%˄ |  0.6457 |
+| 5b      ||   134.74 |   135.90 |   +1%˄ ||     7.42 |     7.36 |   -1%˄ |  0.0000 |
+| 5c      ||   183.02 |   182.29 |   -0%˄ ||     5.46 |     5.49 |   +0%˄ |  0.0002 |
+| 6a      ||   103.97 |   103.08 |   -1%˄ ||     9.62 |     9.70 |   +1%˄ |  0.0000 |
+| 6b      ||   116.88 |   116.05 |   -1%˄ ||     8.56 |     8.62 |   +1%˄ |  0.0000 |
+| 6c      ||    99.00 |    98.33 |   -1%˄ ||    10.10 |    10.17 |   +1%˄ |  0.0000 |
+| 6d      ||   528.66 |   526.53 |   -0%˄ ||     1.89 |     1.90 |   +0%˄ |  0.0000 |
+| 6e      ||   103.73 |   103.07 |   -1%˄ ||     9.64 |     9.70 |   +1%˄ |  0.0000 |
+| 6f      ||   706.82 |   703.22 |   -1%  ||     1.41 |     1.42 |   +1%  |  0.0000 |
+| 7a      ||    53.42 |    53.25 |   -0%˄ ||    18.72 |    18.78 |   +0%˄ |  0.0518 |
+| 7b      ||    49.76 |    49.86 |   +0%˄ ||    20.09 |    20.05 |   -0%˄ |  0.3392 |
+| 7c      ||   585.47 |   585.07 |   -0%˄ ||     1.71 |     1.71 |   +0%˄ |  0.7902 |
+| 8a      ||    39.50 |    39.40 |   -0%˄ ||    25.32 |    25.38 |   +0%˄ |  0.3193 |
+| 8b      ||    37.29 |    37.34 |   +0%˄ ||    26.81 |    26.78 |   -0%˄ |  0.5851 |
+| 8c      ||  1859.66 |  1845.60 |   -1%  ||     0.54 |     0.54 |   +1%  |  0.0012 |
+| 8d      ||   304.77 |   302.46 |   -1%˄ ||     3.28 |     3.31 |   +1%˄ |  0.0000 |
+| 9a      ||   193.27 |   191.85 |   -1%˄ ||     5.17 |     5.21 |   +1%˄ |  0.0000 |
+| 9b      ||   106.34 |   105.94 |   -0%˄ ||     9.40 |     9.44 |   +0%˄ |  0.0000 |
+| 9c      ||   274.26 |   274.94 |   +0%˄ ||     3.65 |     3.64 |   -0%˄ |  0.0000 |
+| 9d      ||   479.48 |   491.24 |   +2%˄ ||     2.09 |     2.04 |   -2%˄ |  0.0000 |
++---------++----------+----------+--------++----------+----------+--------+---------+
+| Sum     || 35371.88 | 34799.59 |   -2%  ||          |          |        |         |
+| Geomean ||          |          |        ||          |          |   +1%  |         |
++---------++----------+----------+--------++----------+----------+--------+---------+
+|   Notes || ˄ Execution stopped due to max runs reached                            |
++---------++----------+----------+--------++----------+----------+--------+---------+
```
</details>

**hyriseBenchmarkJoinOrder - multi-threaded, shuffled, 28 clients, 28 cores**
<details>
<summary>
Sum of avg. item runtimes: -1%
 ||
Geometric mean of throughput changes: +0%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview---------+-------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                     | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkJoinOrder_9dc0fe58708bd47e07932114cbc49e4547f0cd33_mt.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkJoinOrder_4dcd16447406e725257d578bd8e0af9351361606_mt.json |
 +-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                     | 9dc0fe58708bd47e07932114cbc49e4547f0cd33-dirty                                                                                                  | 4dcd16447406e725257d578bd8e0af9351361606-dirty                                                                                                  |
 |  benchmark_mode               | Shuffled                                                                                                                                        | Shuffled                                                                                                                                        |
 |  build_type                   | release                                                                                                                                         | release                                                                                                                                         |
 |  chunk_size                   | 65535                                                                                                                                           | 65535                                                                                                                                           |
 |  clients                      | 28                                                                                                                                              | 28                                                                                                                                              |
 |  compiler                     | clang 14.0.0                                                                                                                                    | clang 14.0.0                                                                                                                                    |
 |  cores                        | 28                                                                                                                                              | 28                                                                                                                                              |
 |  data_preparation_cores       | 0                                                                                                                                               | 0                                                                                                                                               |
 |  date                         | 2023-02-09 13:38:28                                                                                                                             | 2023-02-09 16:59:38                                                                                                                             |
 |  encoding                     | {'default': {'encoding': 'Dictionary'}}                                                                                                         | {'default': {'encoding': 'Dictionary'}}                                                                                                         |
 |  indexes                      | False                                                                                                                                           | False                                                                                                                                           |
 |  max_duration                 | 1200000000000                                                                                                                                   | 1200000000000                                                                                                                                   |
 |  max_runs                     | -1                                                                                                                                              | -1                                                                                                                                              |
 |  time_unit                    | ns                                                                                                                                              | ns                                                                                                                                              |
 |  using_scheduler              | True                                                                                                                                            | True                                                                                                                                            |
 |  utilized_cores_per_numa_node | [0, 0, 28]                                                                                                                                      | [0, 0, 28]                                                                                                                                      |
 |  verify                       | False                                                                                                                                           | False                                                                                                                                           |
 |  warmup_duration              | 0                                                                                                                                               | 0                                                                                                                                               |
 +-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++---------++----------+----------+--------++----------+----------+--------+---------+
+| Item    || Latency (ms/iter)   | Change || Throughput (iter/s) | Change | p-value |
+|         ||      old |      new |        ||      old |      new |        |         |
++---------++----------+----------+--------++----------+----------+--------+---------+
+| 10a     ||   190.87 |   189.94 |   -0%  ||     0.50 |     0.50 |   +0%  |  0.9719 |
+| 10b     ||   150.50 |   135.10 |  -10%  ||     0.50 |     0.50 |   -0%  |  0.4393 |
+| 10c     ||   426.91 |   401.60 |   -6%  ||     0.50 |     0.50 |   +0%  |  0.4530 |
+| 11a     ||    43.00 |    54.51 |  +27%  ||     0.50 |     0.50 |   +0%  |  0.4015 |
+| 11b     ||    42.57 |    40.99 |   -4%  ||     0.50 |     0.50 |   +0%  |  0.8308 |
+| 11c     ||    65.80 |    76.53 |  +16%  ||     0.50 |     0.50 |   -0%  |  0.4688 |
+| 11d     ||    83.48 |    68.70 |  -18%  ||     0.50 |     0.50 |   -0%  |  0.2993 |
+| 12a     ||   183.56 |   202.46 |  +10%  ||     0.50 |     0.50 |   +0%  |  0.5669 |
+| 12b     ||    78.56 |    65.86 |  -16%  ||     0.50 |     0.50 |   -0%  |  0.4872 |
+| 12c     ||   315.69 |   314.63 |   -0%  ||     0.50 |     0.50 |   +0%  |  0.9740 |
+| 13a     ||   649.69 |   664.56 |   +2%  ||     0.50 |     0.50 |   +0%  |  0.7526 |
+| 13b     ||   277.22 |   325.64 |  +17%  ||     0.50 |     0.50 |   +0%  |  0.2115 |
+| 13c     ||   219.83 |   217.90 |   -1%  ||     0.50 |     0.50 |   +0%  |  0.9369 |
+| 13d     ||  1062.46 |  1024.83 |   -4%  ||     0.50 |     0.50 |   +0%  |  0.4666 |
+| 14a     ||   833.69 |   784.94 |   -6%  ||     0.50 |     0.50 |   +0%  |  0.3216 |
+| 14b     ||   481.02 |   437.29 |   -9%  ||     0.50 |     0.50 |   +0%  |  0.2072 |
+| 14c     ||   990.89 |   987.81 |   -0%  ||     0.50 |     0.50 |   +0%  |  0.9593 |
+| 15a     ||   136.54 |   154.85 |  +13%  ||     0.50 |     0.50 |   +0%  |  0.3264 |
+| 15b     ||   119.83 |   155.78 |  +30%  ||     0.50 |     0.50 |   -0%  |  0.0775 |
+| 15c     ||   141.72 |   169.16 |  +19%  ||     0.50 |     0.50 |   +0%  |  0.1947 |
+| 15d     ||   202.57 |   217.78 |   +8%  ||     0.50 |     0.50 |   +0%  |  0.6458 |
+| 16a     ||  2459.32 |  2501.59 |   +2%  ||     0.50 |     0.50 |   +0%  |  0.4256 |
+| 16b     ||  3808.10 |  3794.23 |   -0%  ||     0.50 |     0.50 |   -0%  |  0.8017 |
+| 16c     ||  2660.92 |  2687.85 |   +1%  ||     0.50 |     0.50 |   +0%  |  0.6435 |
+| 16d     ||  2606.95 |  2628.54 |   +1%  ||     0.50 |     0.50 |   -0%  |  0.6940 |
+| 17a     ||   804.36 |   850.24 |   +6%  ||     0.50 |     0.50 |   +0%  |  0.4094 |
+| 17b     ||   574.94 |   542.43 |   -6%  ||     0.50 |     0.50 |   +0%  |  0.3694 |
+| 17c     ||   495.50 |   485.00 |   -2%  ||     0.50 |     0.50 |   -0%  |  0.7499 |
+| 17d     ||   671.56 |   572.76 |  -15%  ||     0.50 |     0.50 |   +0%  |  0.0619 |
+| 17e     ||  1560.56 |  1521.97 |   -2%  ||     0.50 |     0.50 |   +0%  |  0.4352 |
+| 17f     ||  1071.56 |  1011.04 |   -6%  ||     0.50 |     0.50 |   +0%  |  0.1778 |
+| 18a     ||   775.97 |   786.75 |   +1%  ||     0.50 |     0.50 |   +0%  |  0.8603 |
+| 18b     ||   159.65 |   160.61 |   +1%  ||     0.50 |     0.50 |   +0%  |  0.9614 |
+| 18c     ||   608.44 |   652.85 |   +7%  ||     0.50 |     0.50 |   +0%  |  0.2332 |
+| 19a     ||   492.12 |   418.54 |  -15%  ||     0.50 |     0.50 |   +0%  |  0.1031 |
+| 19b     ||   331.23 |   298.50 |  -10%  ||     0.50 |     0.50 |   +0%  |  0.2994 |
+| 19c     ||   477.43 |   480.01 |   +1%  ||     0.50 |     0.50 |   +0%  |  0.9521 |
+| 19d     ||  1253.37 |  1215.40 |   -3%  ||     0.50 |     0.50 |   +0%  |  0.4944 |
+| 1a      ||    35.13 |    40.28 |  +15%  ||     0.50 |     0.50 |   +0%  |  0.6071 |
+| 1b      ||    26.10 |    26.88 |   +3%  ||     0.50 |     0.50 |   +0%  |  0.8959 |
+| 1c      ||    79.01 |    39.90 |  -49%  ||     0.50 |     0.50 |   +0%  |  0.0979 |
+| 1d      ||    44.37 |    37.83 |  -15%  ||     0.50 |     0.50 |   +0%  |  0.6138 |
+| 20a     ||   577.48 |   648.92 |  +12%  ||     0.50 |     0.50 |   +0%  |  0.1275 |
+| 20b     ||   378.26 |   412.22 |   +9%  ||     0.50 |     0.50 |   +0%  |  0.3189 |
+| 20c     ||   433.73 |   446.39 |   +3%  ||     0.50 |     0.50 |   -0%  |  0.7691 |
+| 21a     ||    73.86 |    65.07 |  -12%  ||     0.50 |     0.50 |   +0%  |  0.3779 |
+| 21b     ||    69.11 |    63.02 |   -9%  ||     0.50 |     0.50 |   +0%  |  0.6726 |
+| 21c     ||    67.61 |    65.18 |   -4%  ||     0.50 |     0.50 |   -0%  |  0.8094 |
+| 22a     ||   506.42 |   530.37 |   +5%  ||     0.50 |     0.50 |   +0%  |  0.6310 |
+| 22b     ||   343.74 |   313.35 |   -9%  ||     0.50 |     0.50 |   +0%  |  0.3774 |
+| 22c     ||   891.27 |   916.59 |   +3%  ||     0.50 |     0.50 |   -0%  |  0.6384 |
+| 22d     ||  1185.76 |  1266.16 |   +7%  ||     0.50 |     0.50 |   +0%  |  0.1598 |
+| 23a     ||   140.61 |   158.30 |  +13%  ||     0.50 |     0.50 |   -0%  |  0.4130 |
+| 23b     ||   135.29 |   112.96 |  -17%  ||     0.50 |     0.50 |   +0%  |  0.2677 |
+| 23c     ||   195.27 |   177.94 |   -9%  ||     0.50 |     0.50 |   +0%  |  0.5019 |
+| 24a     ||   239.08 |   232.53 |   -3%  ||     0.50 |     0.50 |   +0%  |  0.7881 |
+| 24b     ||   147.65 |   143.55 |   -3%  ||     0.50 |     0.50 |   +0%  |  0.8219 |
+| 25a     ||   555.42 |   454.23 |  -18%  ||     0.50 |     0.50 |   +0%  |  0.0192 |
+| 25b     ||   141.91 |   102.02 |  -28%  ||     0.50 |     0.50 |   +0%  |  0.0163 |
+| 25c     ||   949.79 |   926.64 |   -2%  ||     0.50 |     0.50 |   +0%  |  0.6417 |
+| 26a     ||   346.61 |   296.91 |  -14%  ||     0.50 |     0.50 |   +0%  |  0.1521 |
+| 26b     ||   167.56 |   196.94 |  +18%  ||     0.50 |     0.50 |   +0%  |  0.1211 |
+| 26c     ||   491.40 |   443.87 |  -10%  ||     0.50 |     0.50 |   +0%  |  0.2982 |
+| 27a     ||   103.09 |    79.04 |  -23%  ||     0.50 |     0.50 |   +0%  |  0.2307 |
+| 27b     ||   107.96 |   103.57 |   -4%  ||     0.50 |     0.50 |   +0%  |  0.8775 |
+| 27c     ||    76.07 |    85.24 |  +12%  ||     0.50 |     0.50 |   +0%  |  0.5951 |
+| 28a     ||   691.69 |   689.28 |   -0%  ||     0.50 |     0.50 |   +0%  |  0.9599 |
+| 28b     ||   143.54 |   175.75 |  +22%  ||     0.50 |     0.50 |   +0%  |  0.1095 |
+| 28c     ||   827.47 |   720.51 |  -13%  ||     0.50 |     0.50 |   +0%  |  0.0626 |
+| 29a     ||   173.35 |   202.06 |  +17%  ||     0.50 |     0.50 |   +0%  |  0.1940 |
+| 29b     ||   140.99 |   150.10 |   +6%  ||     0.50 |     0.50 |   +0%  |  0.6992 |
+| 29c     ||   226.75 |   242.68 |   +7%  ||     0.50 |     0.50 |   +0%  |  0.5609 |
+| 2a      ||   140.70 |   148.92 |   +6%  ||     0.50 |     0.50 |   +0%  |  0.6641 |
+| 2b      ||   142.14 |   124.10 |  -13%  ||     0.50 |     0.50 |   +0%  |  0.4041 |
+| 2c      ||    83.23 |    65.58 |  -21%  ||     0.50 |     0.50 |   -0%  |  0.2465 |
+| 2d      ||   185.69 |   210.00 |  +13%  ||     0.50 |     0.50 |   +0%  |  0.3516 |
+| 30a     ||   285.36 |   303.31 |   +6%  ||     0.50 |     0.50 |   -0%  |  0.5644 |
+| 30b     ||   236.49 |   260.76 |  +10%  ||     0.50 |     0.50 |   +0%  |  0.4205 |
+| 30c     ||   735.10 |   700.66 |   -5%  ||     0.50 |     0.50 |   +0%  |  0.5461 |
+| 31a     ||   295.02 |   297.35 |   +1%  ||     0.50 |     0.50 |   +0%  |  0.9495 |
+| 31b     ||   158.37 |   144.20 |   -9%  ||     0.50 |     0.50 |   +0%  |  0.4458 |
+| 31c     ||   312.65 |   318.88 |   +2%  ||     0.50 |     0.50 |   +0%  |  0.8527 |
+| 32a     ||    38.46 |    33.93 |  -12%  ||     0.50 |     0.50 |   -0%  |  0.5989 |
+| 32b     ||   112.57 |   128.69 |  +14%  ||     0.50 |     0.50 |   +0%  |  0.3603 |
+| 33a     ||    69.76 |    77.43 |  +11%  ||     0.50 |     0.50 |   -0%  |  0.6732 |
+| 33b     ||    58.57 |    49.58 |  -15%  ||     0.50 |     0.50 |   +0%  |  0.3869 |
+| 33c     ||    77.00 |   113.30 |  +47%  ||     0.50 |     0.50 |   +0%  |  0.1557 |
+| 3a      ||   329.53 |   336.36 |   +2%  ||     0.50 |     0.50 |   +0%  |  0.8419 |
+| 3b      ||    48.70 |    76.52 |  +57%  ||     0.50 |     0.50 |   +0%  |  0.1239 |
+| 3c      ||   541.19 |   548.01 |   +1%  ||     0.50 |     0.50 |   +0%  |  0.8651 |
+| 4a      ||   205.62 |   222.14 |   +8%  ||     0.50 |     0.50 |   +0%  |  0.5971 |
+| 4b      ||    58.83 |    56.74 |   -4%  ||     0.50 |     0.50 |   -0%  |  0.9019 |
+| 4c      ||   241.20 |   208.07 |  -14%  ||     0.50 |     0.50 |   +0%  |  0.2304 |
+| 5a      ||   149.32 |   161.71 |   +8%  ||     0.50 |     0.50 |   +0%  |  0.5032 |
+| 5b      ||   253.69 |   216.31 |  -15%  ||     0.50 |     0.50 |   +0%  |  0.2827 |
+| 5c      ||   213.25 |   211.80 |   -1%  ||     0.50 |     0.50 |   +0%  |  0.9532 |
+| 6a      ||    93.56 |   116.89 |  +25%  ||     0.50 |     0.50 |   +0%  |  0.2014 |
+| 6b      ||   128.44 |   146.89 |  +14%  ||     0.50 |     0.50 |   +0%  |  0.2647 |
+| 6c      ||    97.28 |    92.77 |   -5%  ||     0.50 |     0.50 |   +0%  |  0.7552 |
+| 6d      ||   576.13 |   562.32 |   -2%  ||     0.50 |     0.50 |   +0%  |  0.7559 |
+| 6e      ||   101.14 |   103.17 |   +2%  ||     0.50 |     0.50 |   +0%  |  0.8953 |
+| 6f      ||   955.43 |   953.81 |   -0%  ||     0.50 |     0.50 |   +0%  |  0.9642 |
+| 7a      ||   112.76 |   144.60 |  +28%  ||     0.50 |     0.50 |   +0%  |  0.2317 |
+| 7b      ||    98.62 |   104.87 |   +6%  ||     0.50 |     0.50 |   +0%  |  0.6935 |
+| 7c      ||   902.72 |   841.99 |   -7%  ||     0.50 |     0.50 |   +0%  |  0.1925 |
+| 8a      ||   117.46 |   125.64 |   +7%  ||     0.50 |     0.50 |   +0%  |  0.6841 |
+| 8b      ||   113.48 |   143.24 |  +26%  ||     0.50 |     0.50 |   +0%  |  0.1922 |
+| 8c      ||  2304.98 |  2184.63 |   -5%  ||     0.50 |     0.50 |   -0%  |  0.0414 |
+| 8d      ||   594.79 |   574.48 |   -3%  ||     0.50 |     0.50 |   +0%  |  0.6374 |
+| 9a      ||   458.96 |   497.51 |   +8%  ||     0.50 |     0.50 |   +0%  |  0.3768 |
+| 9b      ||   419.00 |   347.01 |  -17%  ||     0.50 |     0.50 |   +0%  |  0.1207 |
+| 9c      ||   580.24 |   680.47 |  +17%  ||     0.50 |     0.50 |   +0%  |  0.0313 |
+| 9d      ||   918.75 |   863.40 |   -6%  ||     0.50 |     0.50 |   +0%  |  0.2177 |
++---------++----------+----------+--------++----------+----------+--------+---------+
+| Sum     || 51767.90 | 51363.43 |   -1%  ||          |          |        |         |
+| Geomean ||          |          |        ||          |          |   +0%  |         |
++---------++----------+----------+--------++----------+----------+--------+---------+
```
</details>

### CODE REVIEW

File: src/test/lib/optimizer/strategy/chunk_pruning_rule_test.cpp [hunk 1]
```diff
@@ -102,351 +95,386 @@ TEST_F(ChunkPruningRuleTest, SimplePruningTest) {
...
+  // clang-format off
+  // SELECT * FROM compressed WHERE a > 200 AND b = (SELECT 1.1);
+  const auto input_lqp_1 =
+  PredicateNode::make(greater_than_(stored_table_node_1->get_column("a"), value_(200)),  // Prunes chunk 1.
+    PredicateNode::make(equals_(stored_table_node_1->get_column("b"), lqp_subquery_(subquery_1)),
+      stored_table_node_1));
+
+  // SELECT * FROM compressed WHERE a > 200 AND b BETWEEN (SELECT 1.1) AND (SELECT 3.3);
+  const auto input_lqp_2 =
+  PredicateNode::make(greater_than_(stored_table_node_2->get_column("a"), value_(200)),  // Prunes chunk 1.
```
Comment (Bouncner) [inline src/test/lib/optimizer/strategy/chunk_pruning_rule_test.cpp:439]: Shouldn't matter, but can you pull the subquery-predicate up? Just to have both orders in this test.

File: src/test/lib/optimizer/strategy/chunk_pruning_rule_test.cpp [hunk 2]
```diff
@@ -102,351 +95,386 @@ TEST_F(ChunkPruningRuleTest, SimplePruningTest) {
...
+  const auto actual_lqp_2 = StrategyBaseTest::apply_rule(_rule, input_lqp_2);
+
+  EXPECT_EQ(actual_lqp_1, input_lqp_1);
+  EXPECT_EQ(actual_lqp_2, input_lqp_2);
+  const auto expected_chunk_ids = std::vector<ChunkID>{ChunkID{1}};
+  EXPECT_EQ(stored_table_node_1->pruned_chunk_ids(), expected_chunk_ids);
+  EXPECT_EQ(stored_table_node_2->pruned_chunk_ids(), expected_chunk_ids);
+}
+
+TEST_F(ChunkPruningRuleTest, PredicateWithCorrelatedSubquery) {
```
Comment (Bouncner) [inline src/test/lib/optimizer/strategy/chunk_pruning_rule_test.cpp:454]: Can you add a comment similar to `PredicateWithUncorrelatedSubquery`?

Comment (Bouncner) [reply src/test/lib/optimizer/strategy/chunk_pruning_rule_test.cpp:454]: I know the comment above states everything. I am just not a fan of reading the comments of other test to understand the current test. Maybe split the comment?

**Review by Bouncner — APPROVED** [review]
Looks good to me.

**Comment by dey4ss** [comment]
## Benchmark this PR merged with #2536 without vs. with dependency discovery

**System**
<details>
<summary>nemea - click to expand</summary>

| property | value |
| -- | -- |
| Hostname | nemea |
| CPU | Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz |
| Memory | 844GB |
| numactl | nodebind: 2  |
| numactl | membind: 2  |
</details>

**Commit Info and Build Time**
| commit | date | message | build time |
| -- | -- | -- | -- |
| 2a532f27a | 10.02.2023 15:24 | Merge branch 'dey4ss/prune_subquery_scans' into dey4ss/benchmark_subquery_estimation | real 343.58 user 3369.57 sys 97.79|
| 0aba9fd9b | 14.02.2023 15:57 | execute with plugin | real 345.32 user 3408.22 sys 98.88|


**hyriseBenchmarkTPCH - single-threaded, SF 10.0**
<details>
<summary>
Sum of avg. item runtimes: +1%
 ||
Geometric mean of throughput changes: -1%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview----+--------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCH_2a532f27a764bf868ff02e995ebd630b9a1cd78a_st.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCH_0aba9fd9b25d9b8b9b666fea96adf65890f0253a_mining_st.json |
 +--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                | 2a532f27a764bf868ff02e995ebd630b9a1cd78a-dirty                                                                                             | 0aba9fd9b25d9b8b9b666fea96adf65890f0253a-dirty                                                                                                    |
 |  benchmark_mode          | Ordered                                                                                                                                    | Ordered                                                                                                                                           |
 |  build_type              | release                                                                                                                                    | release                                                                                                                                           |
 |  chunk_size              | 65535                                                                                                                                      | 65535                                                                                                                                             |
 |  clients                 | 1                                                                                                                                          | 1                                                                                                                                                 |
 |  clustering              | None                                                                                                                                       | None                                                                                                                                              |
 |  compiler                | clang 14.0.0                                                                                                                               | clang 14.0.0                                                                                                                                      |
 |  cores                   | 0                                                                                                                                          | 0                                                                                                                                                 |
 |  data_preparation_cores  | 0                                                                                                                                          | 0                                                                                                                                                 |
 |  date                    | 2023-02-10 15:41:45                                                                                                                        | 2023-02-14 19:30:27                                                                                                                               |
 |  encoding                | {'default': {'encoding': 'Dictionary'}}                                                                                                    | {'default': {'encoding': 'Dictionary'}}                                                                                                           |
 |  indexes                 | False                                                                                                                                      | False                                                                                                                                             |
 |  max_duration            | 60000000000                                                                                                                                | 60000000000                                                                                                                                       |
 |  max_runs                | 100                                                                                                                                        | 100                                                                                                                                               |
 |  scale_factor            | 10.0                                                                                                                                       | 10.0                                                                                                                                              |
 |  time_unit               | ns                                                                                                                                         | ns                                                                                                                                                |
 |  use_prepared_statements | False                                                                                                                                      | False                                                                                                                                             |
 |  using_scheduler         | False                                                                                                                                      | False                                                                                                                                             |
 |  verify                  | False                                                                                                                                      | False                                                                                                                                             |
 |  warmup_duration         | 1000000000                                                                                                                                 | 1000000000                                                                                                                                        |
 +--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++----------++----------+----------+--------++----------+----------+--------+---------+
+| Item     || Latency (ms/iter)   | Change || Throughput (iter/s) | Change | p-value |
+|          ||      old |      new |        ||      old |      new |        |         |
++----------++----------+----------+--------++----------+----------+--------+---------+
+| TPC-H 01 ||  5871.45 |  5796.90 |   -1%  ||     0.17 |     0.17 |   +1%  |  0.4481 |
+| TPC-H 02 ||    49.49 |    48.68 |   -2%˄ ||    20.20 |    20.54 |   +2%˄ |  0.2080 |
+| TPC-H 03 ||  2233.82 |  2299.54 |   +3%  ||     0.45 |     0.43 |   -3%  |  0.0016 |
+| TPC-H 04 ||  1461.35 |  1497.22 |   +2%  ||     0.68 |     0.67 |   -2%  |  0.0340 |
+| TPC-H 05 ||  3095.82 |  3101.88 |   +0%  ||     0.32 |     0.32 |   -0%  |  0.7958 |
+| TPC-H 06 ||   155.82 |   156.58 |   +0%˄ ||     6.42 |     6.39 |   -0%˄ |  0.4065 |
+| TPC-H 07 ||   968.57 |   984.02 |   +2%  ||     1.03 |     1.02 |   -2%  |  0.0000 |
+| TPC-H 08 ||   721.41 |   727.42 |   +1%  ||     1.39 |     1.37 |   -1%  |  0.0000 |
+| TPC-H 09 ||  5205.84 |  5266.16 |   +1%  ||     0.19 |     0.19 |   -1%  |  0.0001 |
+| TPC-H 10 ||  2944.54 |  3033.89 |   +3%  ||     0.34 |     0.33 |   -3%  |  0.0037 |
+| TPC-H 11 ||    77.77 |    78.40 |   +1%˄ ||    12.86 |    12.75 |   -1%˄ |  0.1381 |
+| TPC-H 12 ||   998.75 |  1008.99 |   +1%  ||     1.00 |     0.99 |   -1%  |  0.0000 |
+| TPC-H 13 ||  4583.56 |  4604.94 |   +0%  ||     0.22 |     0.22 |   -0%  |  0.2917 |
+| TPC-H 14 ||   424.06 |   429.34 |   +1%˄ ||     2.36 |     2.33 |   -1%˄ |  0.0000 |
+| TPC-H 15 ||   193.76 |   197.58 |   +2%˄ ||     5.16 |     5.06 |   -2%˄ |  0.0000 |
+| TPC-H 16 ||   642.97 |   648.99 |   +1%  ||     1.56 |     1.54 |   -1%  |  0.0000 |
+| TPC-H 17 ||   219.45 |   221.90 |   +1%˄ ||     4.56 |     4.51 |   -1%˄ |  0.0000 |
+| TPC-H 18 ||  1630.78 |  1618.05 |   -1%  ||     0.61 |     0.62 |   +1%  |  0.6240 |
+| TPC-H 19 ||   273.06 |   275.67 |   +1%˄ ||     3.66 |     3.63 |   -1%˄ |  0.0665 |
+| TPC-H 20 ||   412.39 |   413.02 |   +0%˄ ||     2.42 |     2.42 |   -0%˄ |  0.7477 |
+| TPC-H 21 ||  4925.30 |  5011.51 |   +2%  ||     0.20 |     0.20 |   -2%  |  0.0462 |
+| TPC-H 22 ||   424.39 |   427.24 |   +1%˄ ||     2.36 |     2.34 |   -1%˄ |  0.0000 |
++----------++----------+----------+--------++----------+----------+--------+---------+
+| Sum      || 37514.36 | 37847.90 |   +1%  ||          |          |        |         |
+| Geomean  ||          |          |        ||          |          |   -1%  |         |
++----------++----------+----------+--------++----------+----------+--------+---------+
+|    Notes || ˄ Execution stopped due to max runs reached                            |
++----------++----------+----------+--------++----------+----------+--------+---------+
```
</details>


**hyriseBenchmarkTPCH - single-threaded, SF 0.01**
<details>
<summary>
Sum of avg. item runtimes: -0%
 ||
Geometric mean of throughput changes: +1%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview----+------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCH_2a532f27a764bf868ff02e995ebd630b9a1cd78a_st_s01.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCH_0aba9fd9b25d9b8b9b666fea96adf65890f0253a_mining_st_s01.json |
 +--------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                | 2a532f27a764bf868ff02e995ebd630b9a1cd78a-dirty                                                                                                 | 0aba9fd9b25d9b8b9b666fea96adf65890f0253a-dirty                                                                                                        |
 |  benchmark_mode          | Ordered                                                                                                                                        | Ordered                                                                                                                                               |
 |  build_type              | release                                                                                                                                        | release                                                                                                                                               |
 |  chunk_size              | 65535                                                                                                                                          | 65535                                                                                                                                                 |
 |  clients                 | 1                                                                                                                                              | 1                                                                                                                                                     |
 |  clustering              | None                                                                                                                                           | None                                                                                                                                                  |
 |  compiler                | clang 14.0.0                                                                                                                                   | clang 14.0.0                                                                                                                                          |
 |  cores                   | 0                                                                                                                                              | 0                                                                                                                                                     |
 |  data_preparation_cores  | 0                                                                                                                                              | 0                                                                                                                                                     |
 |  date                    | 2023-02-10 16:01:16                                                                                                                            | 2023-02-14 19:50:36                                                                                                                                   |
 |  encoding                | {'default': {'encoding': 'Dictionary'}}                                                                                                        | {'default': {'encoding': 'Dictionary'}}                                                                                                               |
 |  indexes                 | False                                                                                                                                          | False                                                                                                                                                 |
 |  max_duration            | 60000000000                                                                                                                                    | 60000000000                                                                                                                                           |
 |  max_runs                | 100                                                                                                                                            | 100                                                                                                                                                   |
 |  scale_factor            | 0.009999999776482582                                                                                                                           | 0.009999999776482582                                                                                                                                  |
 |  time_unit               | ns                                                                                                                                             | ns                                                                                                                                                    |
 |  use_prepared_statements | False                                                                                                                                          | False                                                                                                                                                 |
 |  using_scheduler         | False                                                                                                                                          | False                                                                                                                                                 |
 |  verify                  | False                                                                                                                                          | False                                                                                                                                                 |
 |  warmup_duration         | 1000000000                                                                                                                                     | 1000000000                                                                                                                                            |
 +--------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++----------++----------+---------+--------++----------+----------+--------+---------+
+| Item     || Latency (ms/iter)  | Change || Throughput (iter/s) | Change | p-value |
+|          ||      old |     new |        ||      old |      new |        |         |
++----------++----------+---------+--------++----------+----------+--------+---------+
+| TPC-H 01 ||     4.88 |    4.84 |   -1%˄ ||   204.70 |   206.58 |   +1%˄ |  0.0032 |
+| TPC-H 02 ||     3.77 |    3.79 |   +1%˄ ||   265.40 |   264.06 |   -1%˄ |  0.9374 |
+| TPC-H 03 ||     0.69 |    0.68 |   -2%˄ ||  1445.60 |  1469.78 |   +2%˄ |  0.1001 |
+| TPC-H 04 ||     0.47 |    0.46 |   -1%˄ ||  2135.05 |  2153.64 |   +1%˄ |  0.0036 |
+| TPC-H 05 ||     1.02 |    1.01 |   -1%˄ ||   979.48 |   991.90 |   +1%˄ |  0.0924 |
+| TPC-H 06 ||     0.18 |    0.18 |   +0%˄ ||  5608.95 |  5589.28 |   -0%˄ |  0.4038 |
+| TPC-H 07 ||    10.53 |   10.77 |   +2%˄ ||    94.91 |    92.80 |   -2%˄ |  0.7527 |
+| TPC-H 08 ||    15.62 |   15.83 |   +1%˄ ||    64.01 |    63.16 |   -1%˄ |  0.5462 |
+| TPC-H 09 ||     4.01 |    3.70 |   -8%˄ ||   249.39 |   270.02 |   +8%˄ |  0.5909 |
+| TPC-H 10 ||     0.83 |    0.81 |   -2%˄ ||  1208.22 |  1227.16 |   +2%˄ |  0.0000 |
+| TPC-H 11 ||     0.21 |    0.21 |   -3%˄ ||  4707.52 |  4838.62 |   +3%˄ |  0.0177 |
+| TPC-H 12 ||     0.63 |    0.61 |   -3%˄ ||  1592.85 |  1636.03 |   +3%˄ |  0.1716 |
+| TPC-H 13 ||     2.01 |    1.98 |   -2%˄ ||   496.21 |   504.11 |   +2%˄ |  0.0000 |
+| TPC-H 14 ||     0.35 |    0.34 |   -2%˄ ||  2882.63 |  2937.16 |   +2%˄ |  0.0513 |
+| TPC-H 15 ||     1.25 |    1.24 |   -1%˄ ||   794.77 |   801.43 |   +1%˄ |  0.0000 |
+| TPC-H 16 ||     1.99 |    1.98 |   -0%˄ ||   502.59 |   504.10 |   +0%˄ |  0.2309 |
+| TPC-H 17 ||     0.62 |    0.75 |  +22%˄ ||  1618.82 |  1327.24 |  -18%˄ |  0.0854 |
+| TPC-H 18 ||     1.18 |    1.17 |   -1%˄ ||   844.48 |   850.63 |   +1%˄ |  0.0000 |
+| TPC-H 19 ||     5.13 |    5.12 |   -0%˄ ||   194.87 |   195.21 |   +0%˄ |  0.0837 |
+| TPC-H 20 ||     2.21 |    1.94 |  -12%˄ ||   452.08 |   516.04 |  +14%˄ |  0.0000 |
+| TPC-H 21 ||     1.42 |    1.43 |   +1%˄ ||   703.42 |   699.80 |   -1%˄ |  0.9071 |
+| TPC-H 22 ||     1.01 |    1.02 |   +1%˄ ||   983.46 |   974.68 |   -1%˄ |  0.0000 |
++----------++----------+---------+--------++----------+----------+--------+---------+
+| Sum      ||    60.00 |   59.87 |   -0%  ||          |          |        |         |
+| Geomean  ||          |         |        ||          |          |   +1%  |         |
++----------++----------+---------+--------++----------+----------+--------+---------+
+|    Notes || ˄ Execution stopped due to max runs reached                           |
++----------++----------+---------+--------++----------+----------+--------+---------+
```
</details>


**hyriseBenchmarkTPCH - multi-threaded, ordered, 1 client, 28 cores, SF 10.0**
<details>
<summary>
Sum of avg. item runtimes: -0%
 ||
Geometric mean of throughput changes: +0%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview---------+----------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                     | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCH_2a532f27a764bf868ff02e995ebd630b9a1cd78a_mt_ordered.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCH_0aba9fd9b25d9b8b9b666fea96adf65890f0253a_mining_mt_ordered.json |
 +-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                     | 2a532f27a764bf868ff02e995ebd630b9a1cd78a-dirty                                                                                                     | 0aba9fd9b25d9b8b9b666fea96adf65890f0253a-dirty                                                                                                            |
 |  benchmark_mode               | Ordered                                                                                                                                            | Ordered                                                                                                                                                   |
 |  build_type                   | release                                                                                                                                            | release                                                                                                                                                   |
 |  chunk_size                   | 65535                                                                                                                                              | 65535                                                                                                                                                     |
 |  clients                      | 1                                                                                                                                                  | 1                                                                                                                                                         |
 |  clustering                   | None                                                                                                                                               | None                                                                                                                                                      |
 |  compiler                     | clang 14.0.0                                                                                                                                       | clang 14.0.0                                                                                                                                              |
 |  cores                        | 28                                                                                                                                                 | 28                                                                                                                                                        |
 |  data_preparation_cores       | 0                                                                                                                                                  | 0                                                                                                                                                         |
 |  date                         | 2023-02-10 16:01:45                                                                                                                                | 2023-02-14 19:51:05                                                                                                                                       |
 |  encoding                     | {'default': {'encoding': 'Dictionary'}}                                                                                                            | {'default': {'encoding': 'Dictionary'}}                                                                                                                   |
 |  indexes                      | False                                                                                                                                              | False                                                                                                                                                     |
 |  max_duration                 | 60000000000                                                                                                                                        | 60000000000                                                                                                                                               |
 |  max_runs                     | -1                                                                                                                                                 | -1                                                                                                                                                        |
 |  scale_factor                 | 10.0                                                                                                                                               | 10.0                                                                                                                                                      |
 |  time_unit                    | ns                                                                                                                                                 | ns                                                                                                                                                        |
 |  use_prepared_statements      | False                                                                                                                                              | False                                                                                                                                                     |
 |  using_scheduler              | True                                                                                                                                               | True                                                                                                                                                      |
 |  utilized_cores_per_numa_node | [0, 0, 28]                                                                                                                                         | [0, 0, 28]                                                                                                                                                |
 |  verify                       | False                                                                                                                                              | False                                                                                                                                                     |
 |  warmup_duration              | 0                                                                                                                                                  | 0                                                                                                                                                         |
 +-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++----------++----------+----------+--------++----------+----------+--------+----------------------+
+| Item     || Latency (ms/iter)   | Change || Throughput (iter/s) | Change |              p-value |
+|          ||      old |      new |        ||      old |      new |        |                      |
++----------++----------+----------+--------++----------+----------+--------+----------------------+
+| TPC-H 01 ||  4795.89 |  4824.90 |   +1%  ||     0.20 |     0.20 |   +0%  | (run time too short) |
+| TPC-H 02 ||    67.09 |    67.84 |   +1%  ||    13.92 |    13.82 |   -1%  |               0.2818 |
+| TPC-H 03 ||  1138.89 |  1148.75 |   +1%  ||     0.87 |     0.87 |   -0%  |               0.3821 |
+| TPC-H 04 ||   617.45 |   621.32 |   +1%  ||     1.60 |     1.58 |   -1%  |               0.6262 |
+| TPC-H 05 ||  1023.01 |  1014.72 |   -1%  ||     0.97 |     0.97 |   +0%  | (run time too short) |
+| TPC-H 06 ||    77.02 |    77.63 |   +1%  ||    12.13 |    12.10 |   -0%  |               0.0438 |
+| TPC-H 07 ||   468.55 |   471.88 |   +1%  ||     2.10 |     2.08 |   -1%  |               0.1712 |
+| TPC-H 08 ||   411.46 |   410.52 |   -0%  ||     2.40 |     2.40 |   +0%  |               0.6688 |
+| TPC-H 09 ||  2498.42 |  2519.47 |   +1%  ||     0.38 |     0.38 |   -0%  | (run time too short) |
+| TPC-H 10 ||  1646.72 |  1637.22 |   -1%  ||     0.60 |     0.60 |   -0%  | (run time too short) |
+| TPC-H 11 ||    90.15 |    90.26 |   +0%  ||    10.50 |    10.48 |   -0%  |               0.8385 |
+| TPC-H 12 ||   561.51 |   565.05 |   +1%  ||     1.75 |     1.75 |   +0%  |               0.1490 |
+| TPC-H 13 ||  2997.18 |  3002.97 |   +0%  ||     0.32 |     0.32 |   +0%  | (run time too short) |
+| TPC-H 14 ||   175.68 |   174.70 |   -1%  ||     5.53 |     5.57 |   +1%  |               0.2394 |
+| TPC-H 15 ||   172.31 |   172.76 |   +0%  ||     5.62 |     5.62 |   +0%  |               0.5877 |
+| TPC-H 16 ||   800.53 |   798.07 |   -0%  ||     1.23 |     1.23 |   -0%  |               0.5694 |
+| TPC-H 17 ||   100.15 |    99.53 |   -1%  ||     9.48 |     9.57 |   +1%  |               0.2008 |
+| TPC-H 18 ||  2663.71 |  2551.23 |   -4%  ||     0.37 |     0.38 |   +5%  | (run time too short) |
+| TPC-H 19 ||   165.62 |   166.16 |   +0%  ||     5.85 |     5.82 |   -1%  |               0.5002 |
+| TPC-H 20 ||   262.36 |   260.43 |   -1%  ||     3.73 |     3.77 |   +1%  |               0.3512 |
+| TPC-H 21 ||  1232.75 |  1227.09 |   -0%  ||     0.80 |     0.80 |   +0%  | (run time too short) |
+| TPC-H 22 ||   154.35 |   155.11 |   +0%  ||     6.27 |     6.23 |   -1%  |               0.2279 |
++----------++----------+----------+--------++----------+----------+--------+----------------------+
+| Sum      || 22120.81 | 22057.62 |   -0%  ||          |          |        |                      |
+| Geomean  ||          |          |        ||          |          |   +0%  |                      |
++----------++----------+----------+--------++----------+----------+--------+----------------------+
```
</details>


**hyriseBenchmarkTPCH - multi-threaded, shuffled, 28 clients, 28 cores, SF 10.0**
<details>
<summary>
Sum of avg. item runtimes: -1%
 ||
Geometric mean of throughput changes: -2%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview---------+--------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                     | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCH_2a532f27a764bf868ff02e995ebd630b9a1cd78a_mt.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCH_0aba9fd9b25d9b8b9b666fea96adf65890f0253a_mining_mt.json |
 +-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                     | 2a532f27a764bf868ff02e995ebd630b9a1cd78a-dirty                                                                                             | 0aba9fd9b25d9b8b9b666fea96adf65890f0253a-dirty                                                                                                    |
 |  benchmark_mode               | Shuffled                                                                                                                                   | Shuffled                                                                                                                                          |
 |  build_type                   | release                                                                                                                                    | release                                                                                                                                           |
 |  chunk_size                   | 65535                                                                                                                                      | 65535                                                                                                                                             |
 |  clients                      | 28                                                                                                                                         | 28                                                                                                                                                |
 |  clustering                   | None                                                                                                                                       | None                                                                                                                                              |
 |  compiler                     | clang 14.0.0                                                                                                                               | clang 14.0.0                                                                                                                                      |
 |  cores                        | 28                                                                                                                                         | 28                                                                                                                                                |
 |  data_preparation_cores       | 0                                                                                                                                          | 0                                                                                                                                                 |
 |  date                         | 2023-02-10 16:25:30                                                                                                                        | 2023-02-14 20:15:12                                                                                                                               |
 |  encoding                     | {'default': {'encoding': 'Dictionary'}}                                                                                                    | {'default': {'encoding': 'Dictionary'}}                                                                                                           |
 |  indexes                      | False                                                                                                                                      | False                                                                                                                                             |
 |  max_duration                 | 1200000000000                                                                                                                              | 1200000000000                                                                                                                                     |
 |  max_runs                     | -1                                                                                                                                         | -1                                                                                                                                                |
 |  scale_factor                 | 10.0                                                                                                                                       | 10.0                                                                                                                                              |
 |  time_unit                    | ns                                                                                                                                         | ns                                                                                                                                                |
 |  use_prepared_statements      | False                                                                                                                                      | False                                                                                                                                             |
 |  using_scheduler              | True                                                                                                                                       | True                                                                                                                                              |
 |  utilized_cores_per_numa_node | [0, 0, 28]                                                                                                                                 | [0, 0, 28]                                                                                                                                        |
 |  verify                       | False                                                                                                                                      | False                                                                                                                                             |
 |  warmup_duration              | 0                                                                                                                                          | 0                                                                                                                                                 |
 +-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++----------++----------+----------+--------++----------+----------+--------+---------+
+| Item     || Latency (ms/iter)   | Change || Throughput (iter/s) | Change | p-value |
+|          ||      old |      new |        ||      old |      new |        |         |
++----------++----------+----------+--------++----------+----------+--------+---------+
+| TPC-H 01 ||  5804.23 |  5757.54 |   -1%  ||     0.45 |     0.45 |   -1%  |  0.5753 |
+| TPC-H 02 ||   426.26 |   281.83 |  -34%  ||     0.46 |     0.45 |   -2%  |  0.0596 |
+| TPC-H 03 ||  3764.40 |  3519.43 |   -7%  ||     0.45 |     0.45 |   -1%  |  0.2231 |
+| TPC-H 04 ||  2408.89 |  2433.17 |   +1%  ||     0.45 |     0.45 |   -2%  |  0.8858 |
+| TPC-H 05 ||  4017.75 |  4239.82 |   +6%  ||     0.45 |     0.45 |   -2%  |  0.2690 |
+| TPC-H 06 ||   420.90 |   418.86 |   -0%  ||     0.46 |     0.45 |   -2%  |  0.9631 |
+| TPC-H 07 ||  2602.98 |  2649.92 |   +2%  ||     0.46 |     0.45 |   -2%  |  0.7867 |
+| TPC-H 08 ||  1925.06 |  1785.06 |   -7%  ||     0.45 |     0.45 |   -1%  |  0.3282 |
+| TPC-H 09 ||  6085.77 |  5641.10 |   -7%  ||     0.45 |     0.45 |   -2%  |  0.0264 |
+| TPC-H 10 ||  4800.31 |  4676.89 |   -3%  ||     0.46 |     0.45 |   -2%  |  0.5672 |
+| TPC-H 11 ||   531.51 |   502.24 |   -6%  ||     0.45 |     0.45 |   -1%  |  0.7265 |
+| TPC-H 12 ||  2339.72 |  2170.01 |   -7%  ||     0.46 |     0.45 |   -2%  |  0.2669 |
+| TPC-H 13 ||  5611.81 |  5612.61 |   +0%  ||     0.45 |     0.45 |   -1%  |  0.9945 |
+| TPC-H 14 ||  1125.27 |  1134.83 |   +1%  ||     0.46 |     0.45 |   -2%  |  0.9348 |
+| TPC-H 15 ||   412.88 |   391.31 |   -5%  ||     0.45 |     0.45 |   -1%  |  0.3662 |
+| TPC-H 16 ||  1957.35 |  2264.63 |  +16%  ||     0.45 |     0.45 |   -2%  |  0.0198 |
+| TPC-H 17 ||   648.99 |   642.30 |   -1%  ||     0.46 |     0.45 |   -2%  |  0.9400 |
+| TPC-H 18 ||  3499.45 |  3703.59 |   +6%  ||     0.45 |     0.45 |   -2%  |  0.0489 |
+| TPC-H 19 ||   822.33 |   914.59 |  +11%  ||     0.46 |     0.45 |   -2%  |  0.4049 |
+| TPC-H 20 ||  1389.40 |  1342.78 |   -3%  ||     0.46 |     0.45 |   -2%  |  0.7372 |
+| TPC-H 21 ||  5442.69 |  5432.16 |   -0%  ||     0.45 |     0.45 |   -2%  |  0.9639 |
+| TPC-H 22 ||   823.87 |   910.15 |  +10%  ||     0.46 |     0.45 |   -2%  |  0.3531 |
++----------++----------+----------+--------++----------+----------+--------+---------+
+| Sum      || 56861.80 | 56424.83 |   -1%  ||          |          |        |         |
+| Geomean  ||          |          |        ||          |          |   -2%  |         |
++----------++----------+----------+--------++----------+----------+--------+---------+
```
</details>


**hyriseBenchmarkTPCDS - single-threaded**
<details>
<summary>
Sum of avg. item runtimes: -0%
 ||
Geometric mean of throughput changes: +1%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview---+---------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter               | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCDS_2a532f27a764bf868ff02e995ebd630b9a1cd78a_st.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCDS_0aba9fd9b25d9b8b9b666fea96adf65890f0253a_mining_st.json |
 +-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH               | 2a532f27a764bf868ff02e995ebd630b9a1cd78a-dirty                                                                                              | 0aba9fd9b25d9b8b9b666fea96adf65890f0253a-dirty                                                                                                     |
 |  benchmark_mode         | Ordered                                                                                                                                     | Ordered                                                                                                                                            |
 |  build_type             | release                                                                                                                                     | release                                                                                                                                            |
 |  chunk_size             | 65535                                                                                                                                       | 65535                                                                                                                                              |
 |  clients                | 1                                                                                                                                           | 1                                                                                                                                                  |
 |  compiler               | clang 14.0.0                                                                                                                                | clang 14.0.0                                                                                                                                       |
 |  cores                  | 0                                                                                                                                           | 0                                                                                                                                                  |
 |  data_preparation_cores | 0                                                                                                                                           | 0                                                                                                                                                  |
 |  date                   | 2023-02-10 16:47:13                                                                                                                         | 2023-02-14 20:37:19                                                                                                                                |
 |  encoding               | {'default': {'encoding': 'Dictionary'}}                                                                                                     | {'default': {'encoding': 'Dictionary'}}                                                                                                            |
 |  indexes                | False                                                                                                                                       | False                                                                                                                                              |
 |  max_duration           | 60000000000                                                                                                                                 | 60000000000                                                                                                                                        |
 |  max_runs               | 100                                                                                                                                         | 100                                                                                                                                                |
 |  time_unit              | ns                                                                                                                                          | ns                                                                                                                                                 |
 |  using_scheduler        | False                                                                                                                                       | False                                                                                                                                              |
 |  verify                 | False                                                                                                                                       | False                                                                                                                                              |
 |  warmup_duration        | 1000000000                                                                                                                                  | 1000000000                                                                                                                                         |
 +-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++---------++----------+----------+--------++----------+----------+--------+---------+
+| Item    || Latency (ms/iter)   | Change || Throughput (iter/s) | Change | p-value |
+|         ||      old |      new |        ||      old |      new |        |         |
++---------++----------+----------+--------++----------+----------+--------+---------+
+| 01      ||   263.18 |   262.02 |   -0%˄ ||     3.80 |     3.82 |   +0%˄ |  0.1694 |
+| 03      ||    80.60 |    78.61 |   -2%˄ ||    12.41 |    12.72 |   +3%˄ |  0.0000 |
+| 06      ||   129.75 |   126.94 |   -2%˄ ||     7.71 |     7.88 |   +2%˄ |  0.0000 |
+| 07      ||   321.41 |   302.60 |   -6%˄ ||     3.11 |     3.30 |   +6%˄ |  0.0000 |
+| 09      ||   662.47 |   664.96 |   +0%  ||     1.51 |     1.50 |   -0%  |  0.4151 |
+| 10      ||   166.25 |   158.26 |   -5%˄ ||     6.01 |     6.32 |   +5%˄ |  0.0000 |
+| 13      ||   444.52 |   429.64 |   -3%˄ ||     2.25 |     2.33 |   +3%˄ |  0.0000 |
+| 15      ||   114.96 |   112.10 |   -2%˄ ||     8.70 |     8.92 |   +3%˄ |  0.0000 |
+| 16      ||   176.60 |   172.59 |   -2%˄ ||     5.66 |     5.79 |   +2%˄ |  0.0000 |
+| 17      ||   345.02 |   330.73 |   -4%˄ ||     2.90 |     3.02 |   +4%˄ |  0.0000 |
+| 19      ||   121.75 |   117.19 |   -4%˄ ||     8.21 |     8.53 |   +4%˄ |  0.0000 |
+| 25      ||   195.45 |   189.43 |   -3%˄ ||     5.12 |     5.28 |   +3%˄ |  0.0000 |
+| 26      ||   143.10 |   137.03 |   -4%˄ ||     6.99 |     7.30 |   +4%˄ |  0.0000 |
+| 28      ||   607.51 |   603.89 |   -1%˄ ||     1.65 |     1.66 |   +1%˄ |  0.0000 |
+| 29      ||   505.18 |   496.07 |   -2%˄ ||     1.98 |     2.02 |   +2%˄ |  0.0000 |
+| 31      ||  1376.08 |  1365.84 |   -1%  ||     0.73 |     0.73 |   +1%  |  0.0001 |
+| 32      ||    51.19 |    51.50 |   +1%˄ ||    19.54 |    19.42 |   -1%˄ |  0.1454 |
+| 34      ||   182.23 |   174.82 |   -4%˄ ||     5.49 |     5.72 |   +4%˄ |  0.0000 |
+| 35      ||   651.17 |   645.17 |   -1%  ||     1.54 |     1.55 |   +1%  |  0.0000 |
+| 37      ||   364.32 |   367.43 |   +1%˄ ||     2.74 |     2.72 |   -1%˄ |  0.1590 |
+| 39a     ||  1915.47 |  1888.04 |   -1%  ||     0.52 |     0.53 |   +1%  |  0.0002 |
+| 39b     ||  1934.15 |  1858.86 |   -4%  ||     0.52 |     0.54 |   +4%  |  0.0000 |
+| 41      ||   285.87 |   286.71 |   +0%˄ ||     3.50 |     3.49 |   -0%˄ |  0.0061 |
+| 42      ||   100.67 |    98.46 |   -2%˄ ||     9.93 |    10.16 |   +2%˄ |  0.0000 |
+| 43      ||   953.76 |   950.13 |   -0%  ||     1.05 |     1.05 |   +0%  |  0.3011 |
+| 45      ||   119.21 |   118.02 |   -1%˄ ||     8.39 |     8.47 |   +1%˄ |  0.0000 |
+| 48      ||  1038.53 |  1045.05 |   +1%  ||     0.96 |     0.96 |   -1%  |  0.1739 |
+| 50      ||   129.96 |   128.58 |   -1%˄ ||     7.69 |     7.78 |   +1%˄ |  0.0000 |
+| 52      ||   100.22 |    97.62 |   -3%˄ ||     9.98 |    10.24 |   +3%˄ |  0.0000 |
+| 55      ||    96.60 |    94.48 |   -2%˄ ||    10.35 |    10.58 |   +2%˄ |  0.0000 |
+| 62      ||   542.58 |   543.70 |   +0%˄ ||     1.84 |     1.84 |   -0%˄ |  0.0012 |
+| 65      ||  1812.82 |  1778.24 |   -2%  ||     0.55 |     0.56 |   +2%  |  0.0078 |
+| 69      ||   157.89 |   153.44 |   -3%˄ ||     6.33 |     6.52 |   +3%˄ |  0.0000 |
+| 73      ||    99.59 |    95.33 |   -4%˄ ||    10.04 |    10.49 |   +4%˄ |  0.0000 |
+| 79      ||   490.62 |   482.77 |   -2%˄ ||     2.04 |     2.07 |   +2%˄ |  0.0000 |
+| 81      ||   209.06 |   209.13 |   +0%˄ ||     4.78 |     4.78 |   -0%˄ |  0.8998 |
+| 82      ||   452.56 |   453.75 |   +0%˄ ||     2.21 |     2.20 |   -0%˄ |  0.5661 |
+| 83      ||    43.54 |    43.64 |   +0%˄ ||    22.97 |    22.91 |   -0%˄ |  0.8458 |
+| 85      ||   140.48 |   139.57 |   -1%˄ ||     7.12 |     7.16 |   +1%˄ |  0.0000 |
+| 88      ||   783.00 |   776.96 |   -1%  ||     1.28 |     1.29 |   +1%  |  0.0000 |
+| 91      ||    16.86 |    16.90 |   +0%˄ ||    59.30 |    59.15 |   -0%˄ |  0.1115 |
+| 92      ||    39.52 |    39.34 |   -0%˄ ||    25.30 |    25.42 |   +0%˄ |  0.0003 |
+| 93      ||  3914.82 |  3865.41 |   -1%  ||     0.26 |     0.26 |   +1%  |  0.0366 |
+| 94      ||   107.79 |   107.92 |   +0%˄ ||     9.28 |     9.27 |   -0%˄ |  0.6806 |
+| 95      ||  8845.75 |  9015.28 |   +2%  ||     0.11 |     0.11 |   -2%  |       ˅ |
+| 96      ||    77.22 |    76.98 |   -0%˄ ||    12.95 |    12.99 |   +0%˄ |  0.5697 |
+| 97      ||  3245.69 |  3263.01 |   +1%  ||     0.31 |     0.31 |   -1%  |  0.5006 |
+| 99      ||  1045.84 |  1052.11 |   +1%  ||     0.96 |     0.95 |   -1%  |  0.0025 |
++---------++----------+----------+--------++----------+----------+--------+---------+
+| Sum     || 35602.79 | 35466.27 |   -0%  ||          |          |        |         |
+| Geomean ||          |          |        ||          |          |   +1%  |         |
++---------++----------+----------+--------++----------+----------+--------+---------+
+|   Notes || ˄ Execution stopped due to max runs reached                            |
+|         || ˅ Insufficient number of runs for p-value calculation                  |
++---------++----------+----------+--------++----------+----------+--------+---------+
```
</details>


**hyriseBenchmarkTPCDS - multi-threaded, shuffled, 28 clients, 28 cores**
<details>
<summary>
Sum of avg. item runtimes: +1%
 ||
Geometric mean of throughput changes: -3%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview---------+---------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                     | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCDS_2a532f27a764bf868ff02e995ebd630b9a1cd78a_mt.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCDS_0aba9fd9b25d9b8b9b666fea96adf65890f0253a_mining_mt.json |
 +-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                     | 2a532f27a764bf868ff02e995ebd630b9a1cd78a-dirty                                                                                              | 0aba9fd9b25d9b8b9b666fea96adf65890f0253a-dirty                                                                                                     |
 |  benchmark_mode               | Shuffled                                                                                                                                    | Shuffled                                                                                                                                           |
 |  build_type                   | release                                                                                                                                     | release                                                                                                                                            |
 |  chunk_size                   | 65535                                                                                                                                       | 65535                                                                                                                                              |
 |  clients                      | 28                                                                                                                                          | 28                                                                                                                                                 |
 |  compiler                     | clang 14.0.0                                                                                                                                | clang 14.0.0                                                                                                                                       |
 |  cores                        | 28                                                                                                                                          | 28                                                                                                                                                 |
 |  data_preparation_cores       | 0                                                                                                                                           | 0                                                                                                                                                  |
 |  date                         | 2023-02-10 17:14:24                                                                                                                         | 2023-02-14 21:04:57                                                                                                                                |
 |  encoding                     | {'default': {'encoding': 'Dictionary'}}                                                                                                     | {'default': {'encoding': 'Dictionary'}}                                                                                                            |
 |  indexes                      | False                                                                                                                                       | False                                                                                                                                              |
 |  max_duration                 | 1200000000000                                                                                                                               | 1200000000000                                                                                                                                      |
 |  max_runs                     | -1                                                                                                                                          | -1                                                                                                                                                 |
 |  time_unit                    | ns                                                                                                                                          | ns                                                                                                                                                 |
 |  using_scheduler              | True                                                                                                                                        | True                                                                                                                                               |
 |  utilized_cores_per_numa_node | [0, 0, 28]                                                                                                                                  | [0, 0, 28]                                                                                                                                         |
 |  verify                       | False                                                                                                                                       | False                                                                                                                                              |
 |  warmup_duration              | 0                                                                                                                                           | 0                                                                                                                                                  |
 +-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++---------++----------+----------+--------++----------+----------+--------+---------+
+| Item    || Latency (ms/iter)   | Change || Throughput (iter/s) | Change | p-value |
+|         ||      old |      new |        ||      old |      new |        |         |
++---------++----------+----------+--------++----------+----------+--------+---------+
+| 01      ||   572.84 |   689.71 |  +20%  ||     0.46 |     0.45 |   -3%  |  0.0925 |
+| 03      ||   269.61 |   269.30 |   -0%  ||     0.46 |     0.45 |   -3%  |  0.9950 |
+| 06      ||   538.55 |   668.18 |  +24%  ||     0.46 |     0.45 |   -3%  |  0.0994 |
+| 07      ||   820.49 |   880.16 |   +7%  ||     0.46 |     0.45 |   -3%  |  0.5029 |
+| 09      ||   505.88 |   588.87 |  +16%  ||     0.46 |     0.45 |   -3%  |  0.2512 |
+| 10      ||   537.98 |   441.23 |  -18%  ||     0.46 |     0.45 |   -3%  |  0.2670 |
+| 13      ||  1467.51 |  1564.34 |   +7%  ||     0.46 |     0.45 |   -3%  |  0.4608 |
+| 15      ||   519.74 |   380.03 |  -27%  ||     0.46 |     0.45 |   -3%  |  0.0540 |
+| 16      ||   717.68 |   800.88 |  +12%  ||     0.46 |     0.45 |   -3%  |  0.3785 |
+| 17      ||  1057.97 |  1222.65 |  +16%  ||     0.46 |     0.45 |   -2%  |  0.1869 |
+| 19      ||   573.06 |   544.89 |   -5%  ||     0.46 |     0.45 |   -3%  |  0.7626 |
+| 25      ||   772.99 |   733.35 |   -5%  ||     0.46 |     0.45 |   -3%  |  0.6700 |
+| 26      ||   468.74 |   531.36 |  +13%  ||     0.46 |     0.45 |   -3%  |  0.3400 |
+| 28      ||   514.10 |   610.22 |  +19%  ||     0.46 |     0.45 |   -3%  |  0.1528 |
+| 29      ||  1279.85 |  1352.71 |   +6%  ||     0.46 |     0.45 |   -3%  |  0.5033 |
+| 31      ||  2001.41 |  1736.43 |  -13%  ||     0.46 |     0.45 |   -3%  |  0.0499 |
+| 32      ||   246.81 |   288.65 |  +17%  ||     0.46 |     0.45 |   -2%  |  0.4172 |
+| 34      ||   487.33 |   489.56 |   +0%  ||     0.46 |     0.45 |   -3%  |  0.9718 |
+| 35      ||  2154.61 |  1908.08 |  -11%  ||     0.46 |     0.45 |   -3%  |  0.1227 |
+| 37      ||   545.42 |   654.57 |  +20%  ||     0.46 |     0.45 |   -3%  |  0.1676 |
+| 39a     ||  2098.91 |  2117.18 |   +1%  ||     0.46 |     0.45 |   -3%  |  0.8727 |
+| 39b     ||  2137.26 |  2277.59 |   +7%  ||     0.46 |     0.45 |   -3%  |  0.2161 |
+| 41      ||  2840.84 |  2983.96 |   +5%  ||     0.46 |     0.45 |   -2%  |  0.3639 |
+| 42      ||   381.49 |   328.71 |  -14%  ||     0.46 |     0.45 |   -3%  |  0.4018 |
+| 43      ||  1275.96 |  1280.41 |   +0%  ||     0.46 |     0.45 |   -3%  |  0.9506 |
+| 45      ||   562.98 |   496.64 |  -12%  ||     0.46 |     0.45 |   -3%  |  0.3476 |
+| 48      ||  2567.92 |  2795.82 |   +9%  ||     0.46 |     0.45 |   -3%  |  0.1941 |
+| 50      ||   618.21 |   597.80 |   -3%  ||     0.46 |     0.45 |   -3%  |  0.7957 |
+| 52      ||   330.03 |   430.21 |  +30%  ||     0.46 |     0.45 |   -3%  |  0.1243 |
+| 55      ||   319.91 |   271.17 |  -15%  ||     0.46 |     0.45 |   -3%  |  0.3827 |
+| 62      ||   934.15 |   828.29 |  -11%  ||     0.46 |     0.45 |   -3%  |  0.1679 |
+| 65      ||  3650.52 |  3603.86 |   -1%  ||     0.46 |     0.45 |   -3%  |  0.6038 |
+| 69      ||   703.10 |   614.41 |  -13%  ||     0.46 |     0.45 |   -3%  |  0.3828 |
+| 73      ||   378.41 |   326.08 |  -14%  ||     0.46 |     0.45 |   -3%  |  0.4955 |
+| 79      ||  1069.85 |  1116.82 |   +4%  ||     0.46 |     0.45 |   -3%  |  0.5517 |
+| 81      ||   712.65 |   789.81 |  +11%  ||     0.46 |     0.45 |   -3%  |  0.3314 |
+| 82      ||   786.30 |   828.01 |   +5%  ||     0.46 |     0.45 |   -2%  |  0.6189 |
+| 83      ||   370.49 |   299.52 |  -19%  ||     0.46 |     0.45 |   -3%  |  0.2453 |
+| 85      ||   722.79 |   671.35 |   -7%  ||     0.46 |     0.45 |   -3%  |  0.5621 |
+| 88      ||   993.30 |   861.98 |  -13%  ||     0.46 |     0.45 |   -3%  |  0.2341 |
+| 91      ||   132.28 |   167.35 |  +27%  ||     0.46 |     0.45 |   -3%  |  0.2971 |
+| 92      ||   313.88 |   258.72 |  -18%  ||     0.46 |     0.45 |   -3%  |  0.2928 |
+| 93      ||  2339.91 |  2363.82 |   +1%  ||     0.46 |     0.45 |   -3%  |  0.8547 |
+| 94      ||   764.08 |   688.31 |  -10%  ||     0.46 |     0.45 |   -3%  |  0.4797 |
+| 95      ||  7857.93 |  8091.96 |   +3%  ||     0.46 |     0.45 |   -3%  |  0.1825 |
+| 96      ||   236.91 |   262.06 |  +11%  ||     0.46 |     0.45 |   -3%  |  0.6460 |
+| 97      ||  4233.74 |  4275.76 |   +1%  ||     0.46 |     0.45 |   -2%  |  0.7637 |
+| 99      ||  1394.01 |  1338.07 |   -4%  ||     0.46 |     0.45 |   -3%  |  0.4934 |
++---------++----------+----------+--------++----------+----------+--------+---------+
+| Sum     || 56780.38 | 57320.83 |   +1%  ||          |          |        |         |
+| Geomean ||          |          |        ||          |          |   -3%  |         |
++---------++----------+----------+--------++----------+----------+--------+---------+
```
</details>


**hyriseBenchmarkTPCC - single-threaded**
<details>
<summary>
Sum of avg. item runtimes: +0%
 ||
Geometric mean of throughput changes: +0%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview---+--------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter               | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCC_2a532f27a764bf868ff02e995ebd630b9a1cd78a_st.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCC_0aba9fd9b25d9b8b9b666fea96adf65890f0253a_mining_st.json |
 +-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH               | 2a532f27a764bf868ff02e995ebd630b9a1cd78a-dirty                                                                                             | 0aba9fd9b25d9b8b9b666fea96adf65890f0253a-dirty                                                                                                    |
 |  benchmark_mode         | Shuffled                                                                                                                                   | Shuffled                                                                                                                                          |
 |  build_type             | release                                                                                                                                    | release                                                                                                                                           |
 |  chunk_size             | 65535                                                                                                                                      | 65535                                                                                                                                             |
 |  clients                | 1                                                                                                                                          | 1                                                                                                                                                 |
 |  compiler               | clang 14.0.0                                                                                                                               | clang 14.0.0                                                                                                                                      |
 |  cores                  | 0                                                                                                                                          | 0                                                                                                                                                 |
 |  data_preparation_cores | 0                                                                                                                                          | 0                                                                                                                                                 |
 |  date                   | 2023-02-10 17:34:53                                                                                                                        | 2023-02-14 21:25:55                                                                                                                               |
 |  encoding               | {'default': {'encoding': 'Dictionary'}}                                                                                                    | {'default': {'encoding': 'Dictionary'}}                                                                                                           |
 |  indexes                | False                                                                                                                                      | False                                                                                                                                             |
 |  max_duration           | 60000000000                                                                                                                                | 60000000000                                                                                                                                       |
 |  max_runs               | -1                                                                                                                                         | -1                                                                                                                                                |
 |  scale_factor           | 1                                                                                                                                          | 1                                                                                                                                                 |
 |  time_unit              | ns                                                                                                                                         | ns                                                                                                                                                |
 |  using_scheduler        | False                                                                                                                                      | False                                                                                                                                             |
 |  verify                 | False                                                                                                                                      | False                                                                                                                                             |
 |  warmup_duration        | 0                                                                                                                                          | 0                                                                                                                                                 |
 +-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++--------------++----------+---------+--------++----------+----------+--------+---------+
+| Item         || Latency (ms/iter)  | Change || Throughput (iter/s) | Change | p-value |
+|              ||      old |     new |        ||      old |      new |        |         |
++--------------++----------+---------+--------++----------+----------+--------+---------+
+| Delivery     ||    23.42 |   23.43 |   +0%  ||     4.20 |     4.26 |   +1%  |  0.9218 |
+| New-Order    ||    16.43 |   16.47 |   +0%  ||    47.70 |    47.53 |   -0%  |  0.7798 |
+| Order-Status ||     1.09 |    1.09 |   +0%  ||     4.25 |     4.23 |   -1%  |  0.7566 |
+| Payment      ||     2.10 |    2.07 |   -2%  ||    45.58 |    45.47 |   -0%  |  0.0001 |
+| Stock-Level  ||     3.65 |    3.64 |   -0%  ||     4.23 |     4.24 |   +0%  |  0.7985 |
++--------------++----------+---------+--------++----------+----------+--------+---------+
+| Sum          ||    46.70 |   46.70 |   +0%  ||          |          |        |         |
+| Geomean      ||          |         |        ||          |          |   +0%  |         |
++--------------++----------+---------+--------++----------+----------+--------+---------+
```
</details>


**hyriseBenchmarkTPCC - multi-threaded, shuffled, 28 clients, 28 cores**
<details>
<summary>
Sum of avg. item runtimes: +0%
 ||
Geometric mean of throughput changes: -0%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview---------+--------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                     | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCC_2a532f27a764bf868ff02e995ebd630b9a1cd78a_mt.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkTPCC_0aba9fd9b25d9b8b9b666fea96adf65890f0253a_mining_mt.json |
 +-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                     | 2a532f27a764bf868ff02e995ebd630b9a1cd78a-dirty                                                                                             | 0aba9fd9b25d9b8b9b666fea96adf65890f0253a-dirty                                                                                                    |
 |  benchmark_mode               | Shuffled                                                                                                                                   | Shuffled                                                                                                                                          |
 |  build_type                   | release                                                                                                                                    | release                                                                                                                                           |
 |  chunk_size                   | 65535                                                                                                                                      | 65535                                                                                                                                             |
 |  clients                      | 28                                                                                                                                         | 28                                                                                                                                                |
 |  compiler                     | clang 14.0.0                                                                                                                               | clang 14.0.0                                                                                                                                      |
 |  cores                        | 28                                                                                                                                         | 28                                                                                                                                                |
 |  data_preparation_cores       | 0                                                                                                                                          | 0                                                                                                                                                 |
 |  date                         | 2023-02-10 17:35:54                                                                                                                        | 2023-02-14 21:26:56                                                                                                                               |
 |  encoding                     | {'default': {'encoding': 'Dictionary'}}                                                                                                    | {'default': {'encoding': 'Dictionary'}}                                                                                                           |
 |  indexes                      | False                                                                                                                                      | False                                                                                                                                             |
 |  max_duration                 | 1200000000000                                                                                                                              | 1200000000000                                                                                                                                     |
 |  max_runs                     | -1                                                                                                                                         | -1                                                                                                                                                |
 |  scale_factor                 | 1                                                                                                                                          | 1                                                                                                                                                 |
 |  time_unit                    | ns                                                                                                                                         | ns                                                                                                                                                |
 |  using_scheduler              | True                                                                                                                                       | True                                                                                                                                              |
 |  utilized_cores_per_numa_node | [0, 0, 28]                                                                                                                                 | [0, 0, 28]                                                                                                                                        |
 |  verify                       | False                                                                                                                                      | False                                                                                                                                             |
 |  warmup_duration              | 0                                                                                                                                          | 0                                                                                                                                                 |
 +-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++--------------++----------+---------+--------++----------+----------+--------+---------+
+| Item         || Latency (ms/iter)  | Change || Throughput (iter/s) | Change | p-value |
+|              ||      old |     new |        ||      old |      new |        |         |
++--------------++----------+---------+--------++----------+----------+--------+---------+
+| Delivery     ||   211.62 |  211.40 |   -0%  ||     4.48 |     4.48 |   +0%  |  0.8787 |
+|    unsucc.:  ||     3.59 |    3.59 |   +0%  ||    64.71 |    64.70 |   -0%  |         |
+| New-Order    ||    56.14 |   56.19 |   +0%  ||   136.92 |   136.95 |   +0%  |  0.5942 |
+|    unsucc.:  ||     4.38 |    4.35 |   -1%  ||   641.41 |   641.40 |   -0%  |         |
+| Order-Status ||     7.43 |    7.47 |   +1%  ||    69.19 |    69.19 |   +0%  |  0.1438 |
+| Payment      ||     9.44 |    9.46 |   +0%  ||    20.60 |    20.42 |   -1%  |  0.8244 |
+|    unsucc.:  ||     3.85 |    3.84 |   -0%  ||   723.14 |   723.35 |   +0%  |         |
+| Stock-Level  ||    16.75 |   16.91 |   +1%  ||    69.18 |    69.19 |   +0%  |  0.0067 |
++--------------++----------+---------+--------++----------+----------+--------+---------+
+| Sum          ||   301.39 |  301.44 |   +0%  ||          |          |        |         |
+| Geomean      ||          |         |        ||          |          |   -0%  |         |
++--------------++----------+---------+--------++----------+----------+--------+---------+
```
</details>


**hyriseBenchmarkJoinOrder - single-threaded**
<details>
<summary>
Sum of avg. item runtimes: -4%
 ||
Geometric mean of throughput changes: +10%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview---+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter               | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkJoinOrder_2a532f27a764bf868ff02e995ebd630b9a1cd78a_st.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkJoinOrder_0aba9fd9b25d9b8b9b666fea96adf65890f0253a_mining_st.json |
 +-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH               | 2a532f27a764bf868ff02e995ebd630b9a1cd78a-dirty                                                                                                  | 0aba9fd9b25d9b8b9b666fea96adf65890f0253a-dirty                                                                                                         |
 |  benchmark_mode         | Ordered                                                                                                                                         | Ordered                                                                                                                                                |
 |  build_type             | release                                                                                                                                         | release                                                                                                                                                |
 |  chunk_size             | 65535                                                                                                                                           | 65535                                                                                                                                                  |
 |  clients                | 1                                                                                                                                               | 1                                                                                                                                                      |
 |  compiler               | clang 14.0.0                                                                                                                                    | clang 14.0.0                                                                                                                                           |
 |  cores                  | 0                                                                                                                                               | 0                                                                                                                                                      |
 |  data_preparation_cores | 0                                                                                                                                               | 0                                                                                                                                                      |
 |  date                   | 2023-02-10 17:56:01                                                                                                                             | 2023-02-14 21:47:03                                                                                                                                    |
 |  encoding               | {'default': {'encoding': 'Dictionary'}}                                                                                                         | {'default': {'encoding': 'Dictionary'}}                                                                                                                |
 |  indexes                | False                                                                                                                                           | False                                                                                                                                                  |
 |  max_duration           | 60000000000                                                                                                                                     | 60000000000                                                                                                                                            |
 |  max_runs               | 100                                                                                                                                             | 100                                                                                                                                                    |
 |  time_unit              | ns                                                                                                                                              | ns                                                                                                                                                     |
 |  using_scheduler        | False                                                                                                                                           | False                                                                                                                                                  |
 |  verify                 | False                                                                                                                                           | False                                                                                                                                                  |
 |  warmup_duration        | 1000000000                                                                                                                                      | 1000000000                                                                                                                                             |
 +-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++---------++----------+----------+--------++----------+----------+--------+----------------------+
+| Item    || Latency (ms/iter)   | Change || Throughput (iter/s) | Change |              p-value |
+|         ||      old |      new |        ||      old |      new |        |                      |
++---------++----------+----------+--------++----------+----------+--------+----------------------+
+| 10a     ||   180.89 |   175.11 |   -3%˄ ||     5.53 |     5.71 |   +3%˄ |               0.0000 |
+| 10b     ||   129.83 |   127.37 |   -2%˄ ||     7.70 |     7.85 |   +2%˄ |               0.0000 |
+| 10c     ||   327.98 |   318.43 |   -3%˄ ||     3.05 |     3.14 |   +3%˄ |               0.0000 |
+| 11a     ||    20.37 |    13.69 |  -33%˄ ||    49.10 |    73.01 |  +49%˄ |               0.0000 |
+| 11b     ||    20.17 |    13.52 |  -33%˄ ||    49.57 |    73.97 |  +49%˄ |               0.0000 |
+| 11c     ||    25.56 |    25.50 |   -0%˄ ||    39.13 |    39.22 |   +0%˄ |               0.0135 |
+| 11d     ||    28.42 |    28.22 |   -1%˄ ||    35.19 |    35.44 |   +1%˄ |               0.0000 |
+| 12a     ||    51.45 |    48.06 |   -7%˄ ||    19.43 |    20.81 |   +7%˄ |               0.0000 |
+| 12b     ||    41.17 |    38.72 |   -6%˄ ||    24.29 |    25.83 |   +6%˄ |               0.0000 |
+| 12c     ||    87.07 |    71.82 |  -18%˄ ||    11.48 |    13.92 |  +21%˄ |               0.0000 |
+| 13a     ||   288.71 |   276.01 |   -4%˄ ||     3.46 |     3.62 |   +5%˄ |               0.0000 |
+| 13b     ||   167.65 |   160.25 |   -4%˄ ||     5.96 |     6.24 |   +5%˄ |               0.0000 |
+| 13c     ||   129.73 |   122.53 |   -6%˄ ||     7.71 |     8.16 |   +6%˄ |               0.0000 |
+| 13d     ||   606.66 |   582.52 |   -4%˄ ||     1.65 |     1.72 |   +4%˄ | (run time too short) |
+| 14a     ||   417.99 |   407.74 |   -2%˄ ||     2.39 |     2.45 |   +3%˄ |               0.0000 |
+| 14b     ||   237.24 |   227.39 |   -4%˄ ||     4.22 |     4.40 |   +4%˄ |               0.0000 |
+| 14c     ||   503.51 |   478.56 |   -5%˄ ||     1.99 |     2.09 |   +5%˄ |               0.0000 |
+| 15a     ||    94.02 |    39.03 |  -58%˄ ||    10.64 |    25.62 | +141%˄ |               0.0000 |
+| 15b     ||    92.63 |    37.41 |  -60%˄ ||    10.80 |    26.73 | +148%˄ |               0.0000 |
+| 15c     ||    98.28 |    42.23 |  -57%˄ ||    10.17 |    23.68 | +133%˄ |               0.0000 |
+| 15d     ||    96.08 |    39.74 |  -59%˄ ||    10.41 |    25.16 | +142%˄ |               0.0000 |
+| 16a     ||  2261.10 |  2223.30 |   -2%  ||     0.44 |     0.45 |   +2%  |               0.0004 |
+| 16b     ||  3279.47 |  3222.79 |   -2%  ||     0.30 |     0.31 |   +2%  |               0.0004 |
+| 16c     ||  2351.18 |  2303.17 |   -2%  ||     0.43 |     0.43 |   +2%  |               0.0000 |
+| 16d     ||  2315.60 |  2288.54 |   -1%  ||     0.43 |     0.44 |   +1%  |               0.0100 |
+| 17a     ||   600.13 |   589.59 |   -2%˄ ||     1.67 |     1.70 |   +2%˄ |               0.0000 |
+| 17b     ||   479.95 |   470.59 |   -2%˄ ||     2.08 |     2.12 |   +2%˄ |               0.0000 |
+| 17c     ||   461.28 |   448.24 |   -3%˄ ||     2.17 |     2.23 |   +3%˄ |               0.0000 |
+| 17d     ||   541.59 |   529.96 |   -2%˄ ||     1.85 |     1.89 |   +2%˄ |               0.0000 |
+| 17e     ||  1610.15 |  1575.27 |   -2%  ||     0.62 |     0.63 |   +2%  |               0.0000 |
+| 17f     ||   963.65 |   943.90 |   -2%  ||     1.04 |     1.06 |   +2%  |               0.0000 |
+| 18a     ||   611.92 |   599.13 |   -2%˄ ||     1.63 |     1.67 |   +2%˄ |               0.0000 |
+| 18b     ||   125.57 |   124.28 |   -1%˄ ||     7.96 |     8.05 |   +1%˄ |               0.0000 |
+| 18c     ||   585.53 |   575.59 |   -2%˄ ||     1.71 |     1.74 |   +2%˄ |               0.0000 |
+| 19a     ||   195.80 |   183.53 |   -6%˄ ||     5.11 |     5.45 |   +7%˄ |               0.0000 |
+| 19b     ||   139.40 |   130.22 |   -7%˄ ||     7.17 |     7.68 |   +7%˄ |               0.0000 |
+| 19c     ||   208.13 |   195.23 |   -6%˄ ||     4.80 |     5.12 |   +7%˄ |               0.0000 |
+| 19d     ||   732.24 |   711.76 |   -3%  ||     1.37 |     1.40 |   +3%  |               0.0000 |
+| 1a      ||    12.41 |     9.96 |  -20%˄ ||    80.58 |   100.38 |  +25%˄ |               0.0000 |
+| 1b      ||    11.82 |     9.41 |  -20%˄ ||    84.61 |   106.20 |  +26%˄ |               0.0000 |
+| 1c      ||    12.94 |    10.49 |  -19%˄ ||    77.28 |    95.30 |  +23%˄ |               0.0000 |
+| 1d      ||    11.85 |     9.42 |  -20%˄ ||    84.41 |   106.09 |  +26%˄ |               0.0000 |
+| 20a     ||   409.98 |   406.22 |   -1%˄ ||     2.44 |     2.46 |   +1%˄ |               0.0000 |
+| 20b     ||   246.35 |   243.31 |   -1%˄ ||     4.06 |     4.11 |   +1%˄ |               0.0000 |
+| 20c     ||   238.27 |   235.75 |   -1%˄ ||     4.20 |     4.24 |   +1%˄ |               0.0000 |
+| 21a     ||    48.75 |    42.28 |  -13%˄ ||    20.51 |    23.65 |  +15%˄ |               0.0000 |
+| 21b     ||    24.49 |    24.36 |   -1%˄ ||    40.83 |    41.05 |   +1%˄ |               0.0000 |
+| 21c     ||    48.21 |    41.73 |  -13%˄ ||    20.74 |    23.96 |  +16%˄ |               0.0000 |
+| 22a     ||   204.81 |   195.26 |   -5%˄ ||     4.88 |     5.12 |   +5%˄ |               0.0000 |
+| 22b     ||   151.60 |   141.71 |   -7%˄ ||     6.60 |     7.06 |   +7%˄ |               0.0000 |
+| 22c     ||   500.59 |   488.47 |   -2%˄ ||     2.00 |     2.05 |   +2%˄ |               0.0000 |
+| 22d     ||   906.69 |   884.47 |   -2%  ||     1.10 |     1.13 |   +3%  |               0.0000 |
+| 23a     ||    55.59 |    53.59 |   -4%˄ ||    17.99 |    18.66 |   +4%˄ |               0.0000 |
+| 23b     ||    56.08 |    55.64 |   -1%˄ ||    17.83 |    17.97 |   +1%˄ |               0.0000 |
+| 23c     ||    98.04 |    42.29 |  -57%˄ ||    10.20 |    23.65 | +132%˄ |               0.0000 |
+| 24a     ||   170.56 |   170.18 |   -0%˄ ||     5.86 |     5.88 |   +0%˄ |               0.0000 |
+| 24b     ||   149.15 |   147.82 |   -1%˄ ||     6.70 |     6.76 |   +1%˄ |               0.0000 |
+| 25a     ||   294.18 |   288.72 |   -2%˄ ||     3.40 |     3.46 |   +2%˄ |               0.0000 |
+| 25b     ||   137.40 |   136.71 |   -1%˄ ||     7.28 |     7.31 |   +1%˄ |               0.0000 |
+| 25c     ||   934.34 |   920.86 |   -1%  ||     1.07 |     1.09 |   +1%  |               0.0000 |
+| 26a     ||   182.32 |   179.80 |   -1%˄ ||     5.48 |     5.56 |   +1%˄ |               0.0000 |
+| 26b     ||   149.22 |   147.51 |   -1%˄ ||     6.70 |     6.78 |   +1%˄ |               0.0000 |
+| 26c     ||   251.56 |   248.12 |   -1%˄ ||     3.98 |     4.03 |   +1%˄ |               0.0000 |
+| 27a     ||    28.29 |    27.98 |   -1%˄ ||    35.35 |    35.74 |   +1%˄ |               0.0000 |
+| 27b     ||    27.85 |    27.61 |   -1%˄ ||    35.90 |    36.21 |   +1%˄ |               0.0003 |
+| 27c     ||    48.47 |    42.00 |  -13%˄ ||    20.63 |    23.81 |  +15%˄ |               0.0000 |
+| 28a     ||   297.89 |   286.28 |   -4%˄ ||     3.36 |     3.49 |   +4%˄ |               0.0000 |
+| 28b     ||    43.95 |    42.19 |   -4%˄ ||    22.75 |    23.70 |   +4%˄ |               0.0000 |
+| 28c     ||   335.51 |   323.21 |   -4%˄ ||     2.98 |     3.09 |   +4%˄ |               0.0000 |
+| 29a     ||   137.24 |   114.07 |  -17%˄ ||     7.29 |     8.77 |  +20%˄ |               0.0000 |
+| 29b     ||   111.28 |   110.66 |   -1%˄ ||     8.99 |     9.04 |   +1%˄ |               0.0000 |
+| 29c     ||   176.41 |   162.50 |   -8%˄ ||     5.67 |     6.15 |   +9%˄ |               0.0000 |
+| 2a      ||    51.64 |    44.21 |  -14%˄ ||    19.36 |    22.62 |  +17%˄ |               0.0000 |
+| 2b      ||    42.53 |    35.47 |  -17%˄ ||    23.51 |    28.19 |  +20%˄ |               0.0000 |
+| 2c      ||    26.76 |    19.78 |  -26%˄ ||    37.36 |    50.54 |  +35%˄ |               0.0000 |
+| 2d      ||    70.60 |    63.93 |   -9%˄ ||    14.16 |    15.64 |  +10%˄ |               0.0000 |
+| 30a     ||   166.40 |   163.82 |   -2%˄ ||     6.01 |     6.10 |   +2%˄ |               0.0000 |
+| 30b     ||   145.18 |   142.55 |   -2%˄ ||     6.89 |     7.02 |   +2%˄ |               0.0000 |
+| 30c     ||   395.94 |   388.48 |   -2%˄ ||     2.53 |     2.57 |   +2%˄ |               0.0000 |
+| 31a     ||   173.39 |   171.79 |   -1%˄ ||     5.77 |     5.82 |   +1%˄ |               0.0000 |
+| 31b     ||   151.68 |   151.12 |   -0%˄ ||     6.59 |     6.62 |   +0%˄ |               0.0000 |
+| 31c     ||   198.00 |   195.77 |   -1%˄ ||     5.05 |     5.11 |   +1%˄ |               0.0000 |
+| 32a     ||    17.03 |     9.27 |  -46%˄ ||    58.71 |   107.91 |  +84%˄ |               0.0000 |
+| 32b     ||    35.26 |    28.19 |  -20%˄ ||    28.36 |    35.47 |  +25%˄ |               0.0000 |
+| 33a     ||    26.33 |    26.22 |   -0%˄ ||    37.98 |    38.13 |   +0%˄ |               0.0006 |
+| 33b     ||    25.66 |    25.48 |   -1%˄ ||    38.97 |    39.24 |   +1%˄ |               0.0000 |
+| 33c     ||    29.48 |    29.39 |   -0%˄ ||    33.92 |    34.02 |   +0%˄ |               0.0000 |
+| 3a      ||   127.45 |   126.53 |   -1%˄ ||     7.85 |     7.90 |   +1%˄ |               0.0000 |
+| 3b      ||    16.53 |    16.36 |   -1%˄ ||    60.47 |    61.10 |   +1%˄ |               0.0000 |
+| 3c      ||   439.15 |   431.42 |   -2%˄ ||     2.28 |     2.32 |   +2%˄ |               0.0000 |
+| 4a      ||   116.15 |   109.13 |   -6%˄ ||     8.61 |     9.16 |   +6%˄ |               0.0000 |
+| 4b      ||    15.47 |    15.30 |   -1%˄ ||    64.63 |    65.37 |   +1%˄ |               0.0000 |
+| 4c      ||   127.27 |   121.72 |   -4%˄ ||     7.86 |     8.22 |   +5%˄ |               0.0000 |
+| 5a      ||    54.66 |    54.27 |   -1%˄ ||    18.29 |    18.42 |   +1%˄ |               0.0016 |
+| 5b      ||   137.64 |   136.46 |   -1%˄ ||     7.27 |     7.33 |   +1%˄ |               0.0000 |
+| 5c      ||   185.57 |   182.49 |   -2%˄ ||     5.39 |     5.48 |   +2%˄ |               0.0000 |
+| 6a      ||   119.56 |   118.54 |   -1%˄ ||     8.36 |     8.44 |   +1%˄ |               0.0000 |
+| 6b      ||   131.03 |   129.70 |   -1%˄ ||     7.63 |     7.71 |   +1%˄ |               0.0000 |
+| 6c      ||   114.29 |   113.61 |   -1%˄ ||     8.75 |     8.80 |   +1%˄ |               0.0000 |
+| 6d      ||   547.66 |   541.27 |   -1%˄ ||     1.83 |     1.85 |   +1%˄ |               0.0000 |
+| 6e      ||   119.80 |   118.78 |   -1%˄ ||     8.35 |     8.42 |   +1%˄ |               0.0000 |
+| 6f      ||   717.47 |   709.63 |   -1%  ||     1.39 |     1.41 |   +1%  |               0.0000 |
+| 7a      ||    78.40 |    77.97 |   -1%˄ ||    12.76 |    12.82 |   +1%˄ |               0.0000 |
+| 7b      ||    74.93 |    74.50 |   -1%˄ ||    13.35 |    13.42 |   +1%˄ |               0.0000 |
+| 7c      ||   604.75 |   602.79 |   -0%˄ ||     1.65 |     1.66 |   +0%˄ |               0.2361 |
+| 8a      ||    43.78 |    41.87 |   -4%˄ ||    22.84 |    23.88 |   +5%˄ |               0.0000 |
+| 8b      ||    41.46 |    39.63 |   -4%˄ ||    24.12 |    25.23 |   +5%˄ |               0.0000 |
+| 8c      ||  1896.50 |  1745.23 |   -8%  ||     0.53 |     0.57 |   +9%  |               0.0000 |
+| 8d      ||   333.40 |   264.05 |  -21%˄ ||     3.00 |     3.79 |  +26%˄ |               0.0000 |
+| 9a      ||   194.85 |   181.03 |   -7%˄ ||     5.13 |     5.52 |   +8%˄ |               0.0000 |
+| 9b      ||   111.32 |   100.80 |   -9%˄ ||     8.98 |     9.92 |  +10%˄ |               0.0000 |
+| 9c      ||   276.48 |   262.84 |   -5%˄ ||     3.62 |     3.80 |   +5%˄ |               0.0000 |
+| 9d      ||   480.54 |   464.58 |   -3%˄ ||     2.08 |     2.15 |   +3%˄ |               0.0000 |
++---------++----------+----------+--------++----------+----------+--------+----------------------+
+| Sum     || 36284.18 | 34935.45 |   -4%  ||          |          |        |                      |
+| Geomean ||          |          |        ||          |          |  +10%  |                      |
++---------++----------+----------+--------++----------+----------+--------+----------------------+
+|   Notes || ˄ Execution stopped due to max runs reached                                         |
++---------++----------+----------+--------++----------+----------+--------+----------------------+
```
</details>


**hyriseBenchmarkJoinOrder - multi-threaded, shuffled, 28 clients, 28 cores**
<details>
<summary>
Sum of avg. item runtimes: -3%
 ||
Geometric mean of throughput changes: -3%
</summary>

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview---------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                     | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkJoinOrder_2a532f27a764bf868ff02e995ebd630b9a1cd78a_mt.json | /home/Daniel.Lindner/hyrise/cmake-build-release/benchmark_all_results/hyriseBenchmarkJoinOrder_0aba9fd9b25d9b8b9b666fea96adf65890f0253a_mining_mt.json |
 +-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                     | 2a532f27a764bf868ff02e995ebd630b9a1cd78a-dirty                                                                                                  | 0aba9fd9b25d9b8b9b666fea96adf65890f0253a-dirty                                                                                                         |
 |  benchmark_mode               | Shuffled                                                                                                                                        | Shuffled                                                                                                                                               |
 |  build_type                   | release                                                                                                                                         | release                                                                                                                                                |
 |  chunk_size                   | 65535                                                                                                                                           | 65535                                                                                                                                                  |
 |  clients                      | 28                                                                                                                                              | 28                                                                                                                                                     |
 |  compiler                     | clang 14.0.0                                                                                                                                    | clang 14.0.0                                                                                                                                           |
 |  cores                        | 28                                                                                                                                              | 28                                                                                                                                                     |
 |  data_preparation_cores       | 0                                                                                                                                               | 0                                                                                                                                                      |
 |  date                         | 2023-02-10 18:40:15                                                                                                                             | 2023-02-14 22:30:49                                                                                                                                    |
 |  encoding                     | {'default': {'encoding': 'Dictionary'}}                                                                                                         | {'default': {'encoding': 'Dictionary'}}                                                                                                                |
 |  indexes                      | False                                                                                                                                           | False                                                                                                                                                  |
 |  max_duration                 | 1200000000000                                                                                                                                   | 1200000000000                                                                                                                                          |
 |  max_runs                     | -1                                                                                                                                              | -1                                                                                                                                                     |
 |  time_unit                    | ns                                                                                                                                              | ns                                                                                                                                                     |
 |  using_scheduler              | True                                                                                                                                            | True                                                                                                                                                   |
 |  utilized_cores_per_numa_node | [0, 0, 28]                                                                                                                                      | [0, 0, 28]                                                                                                                                             |
 |  verify                       | False                                                                                                                                           | False                                                                                                                                                  |
 |  warmup_duration              | 0                                                                                                                                               | 0                                                                                                                                                      |
 +-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

```diff
++---------++----------+----------+--------++----------+----------+--------+---------+
+| Item    || Latency (ms/iter)   | Change || Throughput (iter/s) | Change | p-value |
+|         ||      old |      new |        ||      old |      new |        |         |
++---------++----------+----------+--------++----------+----------+--------+---------+
+| 10a     ||   186.79 |   177.93 |   -5%  ||     0.49 |     0.48 |   -3%  |  0.6548 |
+| 10b     ||   169.24 |   141.95 |  -16%  ||     0.49 |     0.48 |   -2%  |  0.2245 |
+| 10c     ||   399.63 |   435.12 |   +9%  ||     0.49 |     0.48 |   -2%  |  0.2845 |
+| 11a     ||    53.17 |    44.45 |  -16%  ||     0.49 |     0.47 |   -3%  |  0.5516 |
+| 11b     ||    49.66 |    41.32 |  -17%  ||     0.49 |     0.47 |   -3%  |  0.5174 |
+| 11c     ||    79.70 |    66.02 |  -17%  ||     0.49 |     0.48 |   -3%  |  0.3466 |
+| 11d     ||    83.31 |    84.71 |   +2%  ||     0.49 |     0.47 |   -3%  |  0.9267 |
+| 12a     ||   156.28 |   167.20 |   +7%  ||     0.49 |     0.47 |   -3%  |  0.6002 |
+| 12b     ||    59.17 |    60.54 |   +2%  ||     0.49 |     0.48 |   -2%  |  0.9150 |
+| 12c     ||   322.83 |   284.27 |  -12%  ||     0.49 |     0.47 |   -3%  |  0.2790 |
+| 13a     ||   638.93 |   607.02 |   -5%  ||     0.49 |     0.47 |   -3%  |  0.4423 |
+| 13b     ||   241.14 |   260.69 |   +8%  ||     0.49 |     0.48 |   -2%  |  0.4764 |
+| 13c     ||   216.24 |   234.19 |   +8%  ||     0.49 |     0.48 |   -2%  |  0.5275 |
+| 13d     ||  1093.72 |  1016.40 |   -7%  ||     0.49 |     0.47 |   -3%  |  0.1667 |
+| 14a     ||   809.44 |   806.51 |   -0%  ||     0.49 |     0.48 |   -2%  |  0.9526 |
+| 14b     ||   471.93 |   470.19 |   -0%  ||     0.49 |     0.48 |   -2%  |  0.9626 |
+| 14c     ||   955.03 |   864.14 |  -10%  ||     0.49 |     0.47 |   -3%  |  0.0386 |
+| 15a     ||   160.19 |    77.39 |  -52%  ||     0.49 |     0.47 |   -3%  |  0.0000 |
+| 15b     ||   143.16 |    70.35 |  -51%  ||     0.49 |     0.47 |   -3%  |  0.0004 |
+| 15c     ||   144.73 |   100.76 |  -30%  ||     0.49 |     0.47 |   -3%  |  0.0012 |
+| 15d     ||   225.03 |   124.11 |  -45%  ||     0.49 |     0.48 |   -2%  |  0.0004 |
+| 16a     ||  2593.02 |  2539.68 |   -2%  ||     0.49 |     0.47 |   -3%  |  0.3811 |
+| 16b     ||  3898.92 |  3860.66 |   -1%  ||     0.49 |     0.47 |   -3%  |  0.5558 |
+| 16c     ||  2695.69 |  2758.11 |   +2%  ||     0.49 |     0.47 |   -2%  |  0.3085 |
+| 16d     ||  2598.11 |  2647.85 |   +2%  ||     0.49 |     0.47 |   -2%  |  0.3653 |
+| 17a     ||   786.38 |   856.58 |   +9%  ||     0.49 |     0.47 |   -3%  |  0.1463 |
+| 17b     ||   597.17 |   558.15 |   -7%  ||     0.49 |     0.48 |   -3%  |  0.3713 |
+| 17c     ||   501.54 |   553.56 |  +10%  ||     0.49 |     0.47 |   -3%  |  0.2461 |
+| 17d     ||   609.12 |   530.40 |  -13%  ||     0.49 |     0.48 |   -2%  |  0.0530 |
+| 17e     ||  1478.88 |  1500.98 |   +1%  ||     0.49 |     0.47 |   -2%  |  0.6191 |
+| 17f     ||  1078.40 |  1087.73 |   +1%  ||     0.49 |     0.47 |   -3%  |  0.8525 |
+| 18a     ||   787.24 |   735.38 |   -7%  ||     0.49 |     0.47 |   -3%  |  0.2832 |
+| 18b     ||   170.30 |   152.70 |  -10%  ||     0.49 |     0.48 |   -3%  |  0.3428 |
+| 18c     ||   648.80 |   662.84 |   +2%  ||     0.49 |     0.47 |   -3%  |  0.7074 |
+| 19a     ||   435.22 |   383.26 |  -12%  ||     0.49 |     0.47 |   -3%  |  0.1679 |
+| 19b     ||   360.65 |   345.97 |   -4%  ||     0.49 |     0.48 |   -2%  |  0.7473 |
+| 19c     ||   491.87 |   442.62 |  -10%  ||     0.49 |     0.48 |   -2%  |  0.2289 |
+| 19d     ||  1274.24 |  1298.63 |   +2%  ||     0.49 |     0.48 |   -2%  |  0.6951 |
+| 1a      ||    38.33 |    28.62 |  -25%  ||     0.49 |     0.47 |   -3%  |  0.2403 |
+| 1b      ||    27.72 |    34.86 |  +26%  ||     0.49 |     0.48 |   -2%  |  0.3492 |
+| 1c      ||    37.93 |    28.85 |  -24%  ||     0.49 |     0.48 |   -2%  |  0.3167 |
+| 1d      ||    37.81 |    35.53 |   -6%  ||     0.49 |     0.48 |   -2%  |  0.8410 |
+| 20a     ||   610.48 |   560.84 |   -8%  ||     0.49 |     0.47 |   -3%  |  0.1799 |
+| 20b     ||   411.20 |   430.33 |   +5%  ||     0.49 |     0.47 |   -3%  |  0.5569 |
+| 20c     ||   449.66 |   373.31 |  -17%  ||     0.49 |     0.47 |   -3%  |  0.0464 |
+| 21a     ||   109.77 |    63.16 |  -42%  ||     0.49 |     0.48 |   -2%  |  0.0056 |
+| 21b     ||    72.81 |    77.42 |   +6%  ||     0.49 |     0.48 |   -3%  |  0.7007 |
+| 21c     ||    80.13 |    62.13 |  -22%  ||     0.49 |     0.48 |   -2%  |  0.2382 |
+| 22a     ||   509.00 |   587.43 |  +15%  ||     0.49 |     0.47 |   -3%  |  0.0957 |
+| 22b     ||   345.82 |   366.66 |   +6%  ||     0.49 |     0.48 |   -3%  |  0.5785 |
+| 22c     ||   877.27 |   874.20 |   -0%  ||     0.49 |     0.47 |   -3%  |  0.9504 |
+| 22d     ||  1234.53 |  1167.26 |   -5%  ||     0.49 |     0.47 |   -3%  |  0.2182 |
+| 23a     ||   170.87 |   158.57 |   -7%  ||     0.49 |     0.48 |   -2%  |  0.5548 |
+| 23b     ||   113.13 |    97.95 |  -13%  ||     0.49 |     0.47 |   -3%  |  0.2489 |
+| 23c     ||   182.43 |   147.60 |  -19%  ||     0.49 |     0.47 |   -3%  |  0.1517 |
+| 24a     ||   269.19 |   264.82 |   -2%  ||     0.49 |     0.48 |   -2%  |  0.8789 |
+| 24b     ||   184.31 |   144.63 |  -22%  ||     0.49 |     0.47 |   -3%  |  0.0700 |
+| 25a     ||   592.77 |   541.69 |   -9%  ||     0.49 |     0.47 |   -3%  |  0.3223 |
+| 25b     ||   131.48 |   131.90 |   +0%  ||     0.49 |     0.47 |   -3%  |  0.9807 |
+| 25c     ||  1038.02 |   992.42 |   -4%  ||     0.49 |     0.47 |   -2%  |  0.4310 |
+| 26a     ||   337.42 |   339.75 |   +1%  ||     0.49 |     0.48 |   -2%  |  0.9444 |
+| 26b     ||   209.82 |   233.84 |  +11%  ||     0.49 |     0.47 |   -3%  |  0.3846 |
+| 26c     ||   499.83 |   440.86 |  -12%  ||     0.49 |     0.47 |   -3%  |  0.1041 |
+| 27a     ||    96.00 |    93.23 |   -3%  ||     0.49 |     0.47 |   -3%  |  0.8753 |
+| 27b     ||    87.93 |    90.34 |   +3%  ||     0.49 |     0.47 |   -3%  |  0.8726 |
+| 27c     ||    77.52 |    83.65 |   +8%  ||     0.49 |     0.47 |   -3%  |  0.6997 |
+| 28a     ||   744.16 |   719.37 |   -3%  ||     0.49 |     0.48 |   -2%  |  0.6388 |
+| 28b     ||   194.42 |   141.95 |  -27%  ||     0.49 |     0.48 |   -2%  |  0.0411 |
+| 28c     ||   769.15 |   729.24 |   -5%  ||     0.49 |     0.47 |   -3%  |  0.4622 |
+| 29a     ||   210.65 |   185.50 |  -12%  ||     0.49 |     0.47 |   -3%  |  0.3778 |
+| 29b     ||   176.93 |   186.35 |   +5%  ||     0.49 |     0.48 |   -2%  |  0.7519 |
+| 29c     ||   266.02 |   210.58 |  -21%  ||     0.49 |     0.47 |   -3%  |  0.0413 |
+| 2a      ||   195.02 |   149.12 |  -24%  ||     0.49 |     0.47 |   -3%  |  0.0731 |
+| 2b      ||   136.56 |   130.04 |   -5%  ||     0.49 |     0.47 |   -3%  |  0.7816 |
+| 2c      ||    75.63 |    84.86 |  +12%  ||     0.49 |     0.48 |   -3%  |  0.6612 |
+| 2d      ||   208.02 |   190.67 |   -8%  ||     0.49 |     0.47 |   -3%  |  0.5030 |
+| 30a     ||   341.44 |   336.09 |   -2%  ||     0.49 |     0.48 |   -3%  |  0.8814 |
+| 30b     ||   221.33 |   237.47 |   +7%  ||     0.49 |     0.47 |   -3%  |  0.5098 |
+| 30c     ||   718.97 |   712.41 |   -1%  ||     0.49 |     0.47 |   -2%  |  0.9004 |
+| 31a     ||   285.18 |   296.42 |   +4%  ||     0.49 |     0.47 |   -3%  |  0.6891 |
+| 31b     ||   164.23 |   158.66 |   -3%  ||     0.49 |     0.48 |   -2%  |  0.7580 |
+| 31c     ||   340.59 |   315.40 |   -7%  ||     0.49 |     0.48 |   -2%  |  0.4212 |
+| 32a     ||    27.17 |    28.52 |   +5%  ||     0.49 |     0.47 |   -3%  |  0.8078 |
+| 32b     ||   136.37 |   129.54 |   -5%  ||     0.49 |     0.48 |   -2%  |  0.7307 |
+| 33a     ||    81.61 |    67.40 |  -17%  ||     0.49 |     0.48 |   -3%  |  0.3038 |
+| 33b     ||    77.53 |    68.56 |  -12%  ||     0.49 |     0.48 |   -3%  |  0.4577 |
+| 33c     ||    95.60 |    69.02 |  -28%  ||     0.49 |     0.48 |   -2%  |  0.1009 |
+| 3a      ||   331.63 |   387.54 |  +17%  ||     0.49 |     0.47 |   -2%  |  0.1636 |
+| 3b      ||    50.83 |    60.20 |  +18%  ||     0.49 |     0.47 |   -3%  |  0.4373 |
+| 3c      ||   551.26 |   515.88 |   -6%  ||     0.49 |     0.48 |   -3%  |  0.3682 |
+| 4a      ||   229.37 |   182.07 |  -21%  ||     0.49 |     0.47 |   -3%  |  0.0478 |
+| 4b      ||    58.36 |    37.72 |  -35%  ||     0.49 |     0.47 |   -3%  |  0.1208 |
+| 4c      ||   207.20 |   212.54 |   +3%  ||     0.49 |     0.47 |   -3%  |  0.8202 |
+| 5a      ||   168.54 |   164.96 |   -2%  ||     0.49 |     0.47 |   -3%  |  0.8764 |
+| 5b      ||   169.72 |   217.32 |  +28%  ||     0.49 |     0.47 |   -3%  |  0.0476 |
+| 5c      ||   219.88 |   227.26 |   +3%  ||     0.49 |     0.47 |   -3%  |  0.7599 |
+| 6a      ||   105.21 |   113.63 |   +8%  ||     0.49 |     0.48 |   -3%  |  0.5915 |
+| 6b      ||   132.66 |   158.94 |  +20%  ||     0.49 |     0.48 |   -2%  |  0.1449 |
+| 6c      ||   101.31 |   112.02 |  +11%  ||     0.49 |     0.47 |   -3%  |  0.5313 |
+| 6d      ||   544.20 |   538.70 |   -1%  ||     0.49 |     0.47 |   -3%  |  0.8689 |
+| 6e      ||   103.72 |   105.64 |   +2%  ||     0.49 |     0.47 |   -3%  |  0.9000 |
+| 6f      ||   926.91 |   914.02 |   -1%  ||     0.49 |     0.48 |   -2%  |  0.6572 |
+| 7a      ||   109.56 |   150.26 |  +37%  ||     0.49 |     0.48 |   -2%  |  0.1359 |
+| 7b      ||   126.74 |   101.80 |  -20%  ||     0.49 |     0.47 |   -3%  |  0.2138 |
+| 7c      ||   847.29 |   849.53 |   +0%  ||     0.49 |     0.47 |   -3%  |  0.9562 |
+| 8a      ||   142.10 |   122.45 |  -14%  ||     0.49 |     0.48 |   -2%  |  0.4490 |
+| 8b      ||   177.99 |   114.35 |  -36%  ||     0.49 |     0.48 |   -2%  |  0.0298 |
+| 8c      ||  2200.80 |  2179.23 |   -1%  ||     0.49 |     0.47 |   -3%  |  0.6935 |
+| 8d      ||   653.60 |   606.67 |   -7%  ||     0.49 |     0.48 |   -3%  |  0.3231 |
+| 9a      ||   479.68 |   509.94 |   +6%  ||     0.49 |     0.48 |   -3%  |  0.4646 |
+| 9b      ||   357.51 |   304.93 |  -15%  ||     0.49 |     0.48 |   -2%  |  0.1163 |
+| 9c      ||   644.67 |   623.14 |   -3%  ||     0.49 |     0.47 |   -3%  |  0.5851 |
+| 9d      ||   897.17 |   851.18 |   -5%  ||     0.49 |     0.47 |   -3%  |  0.2869 |
++---------++----------+----------+--------++----------+----------+--------+---------+
+| Sum     || 52502.55 | 51011.26 |   -3%  ||          |          |        |         |
+| Geomean ||          |          |        ||          |          |   -3%  |         |
++---------++----------+----------+--------++----------+----------+--------+---------+
```
</details>

File: src/test/lib/optimizer/strategy/chunk_pruning_rule_test.cpp [hunk 3]
```diff
@@ -102,351 +95,386 @@ TEST_F(ChunkPruningRuleTest, SimplePruningTest) {
...
-        common),
-      PredicateNode::make(greater_than_(b, 850),  // would allow for pruning of chunk 1
-        common));
+  const auto common =
+  PredicateNode::make(greater_than_(b, 700),    // Allows for pruning of chunk 0.
+    PredicateNode::make(greater_than_(a, 123),  // Allows for pruning of chunk 2.
+      stored_table_node));
+  const auto lqp =
+  UnionNode::make(SetOperationMode::All,
+    PredicateNode::make(less_than_(b, 850),     // Would allow for pruning of chunk 3.
```
[the remark this answers is not in the document]
Comment (dey4ss) [reply src/test/lib/optimizer/strategy/chunk_pruning_rule_test.cpp:125]: Just reformatted this. But indeed, we only prune with predicates that apply to all possible paths in the plan, not only to branches. Is the comment in L112 sufficient?
https://github.com/hyrise/hyrise/blob/5c4a15c8db206e9c4aaccdb0bf3ae60a465d74c8/src/test/lib/optimizer/strategy/chunk_pruning_rule_test.cpp#L112

File: src/test/lib/optimizer/strategy/chunk_pruning_rule_test.cpp (hunk 2 above)
Comment (dey4ss) [reply src/test/lib/optimizer/strategy/chunk_pruning_rule_test.cpp:454]: We now have
```
// Predicates that have uncorrelated subqueries as arguments cannot be used for pruning as we do not know the predicate
// values yet. However, such predicates should not prevent us from pruning by other predicates.
```

for the first case and
```
// Similar to PredicateWithUncorrelatedSubquery, we cannot use predicates with correlated subqueries as arguments for
// pruning because their values are not known before execution. However, pruning by other predicates is still possible.
```

for the second case.

File: src/test/lib/optimizer/strategy/chunk_pruning_rule_test.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (Bouncner) [reply src/test/lib/optimizer/strategy/chunk_pruning_rule_test.cpp:125]: Due to the discussion with Jan: should we be more explicit here and state that we might want to revisit this in the future when pruning becomes more relevant? For example by not re-using table nodes and optimize each path's pruning.

[the remark this answers is not in the document]
Comment (dey4ss) [reply src/test/lib/optimizer/strategy/chunk_pruning_rule_test.cpp:125]: Nice idea. I think it might be the best to add a comment to the ChunkPruningRule's hpp. From
```c++
/**
 * For a given LQP, this rule determines the set of chunks that can be pruned from a table. To calculate the sets of
 * pruned chunks, it analyzes the predicates of PredicateNodes in a given LQP. The resulting pruning information is
 * stored inside the StoredTableNode objects.
 */ 
```

to:

```c++
/**
 * For a given LQP, this rule determines the set of chunks that can be pruned from a table. To calculate the sets of
 * pruned chunks, it analyzes the predicates of PredicateNodes in a given LQP. The resulting pruning information is
 * stored inside the StoredTableNode objects. Currently, we do not want to have StoredTableNodes that are duplicates
 * and only differ in the pruned chunks. Thus, we only use predicates for pruning that apply to all paths in the plan,
 * not only to branches. We might revisit this behavior in the future, where we might even consider run-time pruning.
 */ 
```

Comments?
