### PR TITLE
Two expression resolution fixes in SQLTranslator

### LINKED ISSUE #1771: Changes to identifier resolution broke query
```
(release)> generate_tpcc
Generating TPCC tables (this might take a while) ...
(release)> SELECT C_W_ID, C_D_ID, C_ID, MAX(C_BALANCE), (CASE WHEN SUM_OL_AMOUNT IS NULL THEN 0 ELSE SUM_OL_AMOUNT END) AS SUM_OL_AMOUNT_NONNULL FROM CUSTOMER LEFT JOIN (SELECT O_W_ID, O_D_ID, O_C_ID, SUM(OL_AMOUNT) FROM "ORDER", ORDER_LINE WHERE OL_W_ID = O_W_ID AND OL_D_ID = O_D_ID AND OL_O_ID = O_ID AND OL_DELIVERY_D <> -1 GROUP BY O_W_ID, O_D_ID, O_C_ID) AS sub1(O_W_ID, O_D_ID, O_C_ID, SUM_OL_AMOUNT) ON O_W_ID = C_W_ID AND O_D_ID = C_D_ID AND O_C_ID = C_ID GROUP BY C_W_ID, C_D_ID, C_ID, SUM_OL_AMOUNT_NONNULL;
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: src/lib/sql/sql_identifier_resolver.cpp:82 The expression does not exist.
```

"The expression" being `SUM(OL_AMOUNT)`.

Works on 7fa0d1bf68cf666f0460e2991a68272bc253223f, broken on e71169a1e18f73b03ac9054af0f5e3e1d04cf944. Will try to reduce the test case, but not today.

Mentioned query formatted:
```sql
SELECT
   C_W_ID,
   C_D_ID,
   C_ID,
   MAX(C_BALANCE),
   (
      CASE
         WHEN
            SUM_OL_AMOUNT IS NULL 
         THEN
            0 
         ELSE
            SUM_OL_AMOUNT 
      END
   )
   AS SUM_OL_AMOUNT_NONNULL 
FROM
   CUSTOMER 
   LEFT JOIN
      (
         SELECT
            O_W_ID,
            O_D_ID,
            O_C_ID,
            SUM(OL_AMOUNT) 
         FROM
            "ORDER",
            ORDER_LINE 
         WHERE
            OL_W_ID = O_W_ID 
            AND OL_D_ID = O_D_ID 
            AND OL_O_ID = O_ID 
            AND OL_DELIVERY_D <> - 1 
         GROUP BY
            O_W_ID,
            O_D_ID,
            O_C_ID
      )
      AS sub1(O_W_ID, O_D_ID, O_C_ID, SUM_OL_AMOUNT) 
      ON O_W_ID = C_W_ID 
      AND O_D_ID = C_D_ID 
      AND O_C_ID = C_ID 
GROUP BY
   C_W_ID,
   C_D_ID,
   C_ID,
   SUM_OL_AMOUNT_NONNULL
```

### LINKED ISSUE #1799: Division should always return a float/double
```
(debug)> SELECT 5/3
...
|       1|
```

No.

### LINKED ISSUE #1820: Cannot access aggregate with arithmetics outside subquery
The query
```sql
SELECT total_managers
FROM (SELECT i_item_sk,
             count(i_manager_id) + 3 total_managers
      FROM item
      GROUP BY i_item_sk) managers_by_item;
```
crashes with the message `Invalid input error: Failed to resolve Column 'i_manager_id', LQP is invalid` because we cannot access an aggregate that is changed by arithmetic operations from outside a subquery.
There is currently no pressure to fix this, although the error message is misleading.
(This used to be a problem with [query 39](https://github.com/hyrise-mp/tpcds-result-reproduction/commit/91989ede0a8886f8b2545a6c7e8354996e1a89ac#diff-cb0b896c1c63ee0c445ac5cd54b4f59c) in TPC-DS.)

### PR DESCRIPTION
**Pull request by mrks**
fixes #1771
fixes #1820
fixes #1799

### CODE REVIEW

File: src/lib/sql/sql_identifier_resolver.cpp [hunk 1]
```diff
@@ -17,8 +17,10 @@ void SQLIdentifierResolver::add_column_name(const std::shared_ptr<AbstractExpres
 }
 
 void SQLIdentifierResolver::reset_column_names(const std::shared_ptr<opossum::AbstractExpression>& expression) {
-  auto& entry = _find_expression_entry(expression);
-  entry.column_names.clear();
+  auto entry_iter = std::find_if(_entries.begin(), _entries.end(),
+                                 [&](const auto& entry) { return *entry.expression == *expression; });
+  if (entry_iter == _entries.end()) return;
+  entry_iter->column_names.clear();
```
Comment (mrks) [inline src/lib/sql/sql_identifier_resolver.cpp]: Taken from `_find_expression_entry`, which was not used anywhere else. Only change is that the assertion is removed. An expression might not have a name yet (because it is, e.g., an aggregate), but we want to call `reset_column_names` indiscriminately.

File: src/lib/sql/sql_translator.cpp [hunk 2]
```diff
@@ -879,6 +877,8 @@ void SQLTranslator::_translate_select_groupby_having(const hsql::SelectStatement
      */
     if (_current_lqp->find_column_id(*sub_expression)) return ExpressionVisitation::DoNotVisitArguments;
 
+    if (sub_expression->type != ExpressionType::Aggregate) return ExpressionVisitation::VisitArguments;
```
Comment (mrks) [inline src/lib/sql/sql_translator.cpp]: Recurse into the arguments only if the entire expression was not already computed (line before)

**Comment by mrks** [comment]
@janetzki Since you were the last one to look at the SQL identifiers, do you think you could spend five minutes reviewing this?

**Comment by mrks** [comment]
Also sneaked in a one-line comment that clarifies #1799.
