### PR TITLE
Improve PredicateReorderingRule, fix MVCC bug in Projection

### LINKED ISSUE #1155: Predicate Reordering does not do what it is supposed to do
`./hyriseBenchmarkTPCH --queries 6 -r 1 -s 0.1 --verbose --visualize`

screenshot 2018-10-02 at 16 24 09

Why isn't the BETWEEN pushed to the very bottom, if the estimated selectivity is 20%?

### PR DESCRIPTION
**Pull request by mrks**
fixes #1155 

```
 Benchmark | prev. iter/s | new iter/s | change
-----------+--------------+------------+---------------
 TPC-H 1   | 3.796        | 3.825      | +1%
 TPC-H 2   | 90.833       | 90.14      | -1%
 TPC-H 3   | 39.735       | 40.506     | +2%
 TPC-H 4   | 0.504        | 0.662      | +32%
 TPC-H 5   | 26.022       | 25.699     | -1%
 TPC-H 6   | 60.536       | 62.533     | +3%
 TPC-H 7   | 7.621        | 7.526      | -1%
 TPC-H 8   | 34.466       | 33.566     | -3%
 TPC-H 9   | 16.338       | 15.591     | -5%
 TPC-H 10  | 21.448       | 21.705     | +1%
 TPC-H 11  | 117.838      | 117.655    | -0%
 TPC-H 12  | 35.17        | 33.955     | -3%
 TPC-H 13  | 25.302       | 25.145     | -1%
 TPC-H 14  | 84.726       | 84.794     | +0%
 TPC-H 15  | 40.504       | 40.573     | +0%
 TPC-H 16  | 17.17        | 17.312     | +1%
 TPC-H 17  | 4.342        | 4.368      | +1%
 TPC-H 18  | 3.307        | 3.163      | -4%
 TPC-H 19  | 2.348        | 2.402      | +2%
 TPC-H 20  | 0.031        | 0.031      | -2%
 TPC-H 21  | 0.3          | 0.394      | +31%
 TPC-H 22  | 1.159        | 1.123      | -3%
 average   |              |            | +2%
```

### CODE REVIEW

File: src/lib/optimizer/strategy/predicate_reordering_rule.cpp [hunk 1]
```diff
@@ -44,14 +44,11 @@ bool PredicateReorderingRule::apply_to(const std::shared_ptr<AbstractLQPNode>& n
...
       reordered |= _apply_to_inputs(predicate_nodes.back());
-    } else {
-      // No chain was found, continue with the current nodes inputren.
-      reordered = _apply_to_inputs(node);
     }
-  } else {
-    reordered = _apply_to_inputs(node);
   }
 
+  reordered = _apply_to_inputs(node);
```
Comment (mrzzzrm) [inline src/lib/optimizer/strategy/predicate_reordering_rule.cpp]: Shouldn't that be `_apply_to_inputs(node_at_the_end_of_the_predicate_chain_OR_the_input_node)`? The way it is done here, the rule gets applied multiple times to subsets of a predicate chain, right?
