### PR TITLE
JoinOrderingRule

### LINKED ISSUE #1081: ColumnStatistics cannot handle NullValues
`ColumnStatistics` cannot handle predicates with NULL values, such as in ```SELECT a FROM t WHERE t IS NULL```.

It tries to cast the underlying `NullValue` to the respective column type, which fails.

### PR DESCRIPTION
**Pull request by mrzzzrm**
Fixes #1081 

Introduces a JoinOrderingRule powered by DPccp (https://dl.acm.org/citation.cfm?id=1164207). 

The underlying cost estimation was further simplified and is now just very straight forward logical cost model. See it as a intermediate soluation ;)
@SvenLehmann, @timzimmermann and myself discussed the whole Optimizer-CostModel-CardinalityEstimation interaction this week and this PR is not meant to fully build out this architecture.
The important bit is that the cost-based rules **only** interact with the cost estimation component and do so over small interface.

## Performance

Apparently TPC-H join ordering wasn't that bad? I seem to recall the MP had massive problems with TPC-H 5 (@adi64 @toniSta @marcelja), but in my tests it went through in less than 2s on the master with a scale factor of 1.

Some queries (6, 12, 15) got slower - this is not because of join ordering as such, but because of local predicates on string columns that changed order, e.g. `l_shipdate >= '1994-01-01' AND l_shipdate < '1995-01-01'` - one order is faster than the other, but our current cardinality estimation and cost model assign the same cost to both predicates, so their resulting order is random. I could hack-fix this, but decided not to, I think Tim will fix this.

```
Scale=1.0
+-----------+-------------------+------+-------------------+------+--------+---------------------------------+
| Benchmark | prev. iter/s      | runs | new iter/s        | runs | change | p-value (significant if <0.001) |
+-----------+-------------------+------+-------------------+------+--------+---------------------------------+
| TPC-H 1   | 0.106143422425    | 10   | 0.107446424663    | 10   | +1%    |                          0.0000 |
| TPC-H 2   | 0.523863613605    | 10   | 0.529823958874    | 10   | +1%    |     (run time too short) 0.0001 |
| TPC-H 3   | 0.827535748482    | 10   | 0.828190803528    | 10   | +0%    |     (run time too short) 0.9065 |
| TPC-H 4   | 0.000871691911016 | 2    | 0.000912576797418 | 2    | +5%    |        (not enough runs) 0.0000 |
| TPC-H 5   | 0.601907670498    | 10   | 0.668963193893    | 10   | +11%   |     (run time too short) 0.0000 |
| TPC-H 6   | 1.28956949711     | 10   | 1.1786544323      | 10   | -9%    |     (run time too short) 0.0000 |
| TPC-H 7   | 0.132361784577    | 10   | 0.13339394331     | 10   | +1%    |                          0.1771 |
| TPC-H 8   | 0.0137062324211   | 10   | 0.740254282951    | 10   | +5301% |     (run time too short) 0.0000 |
| TPC-H 9   | 0.0693450197577   | 10   | 0.414652377367    | 10   | +498%  |     (run time too short) 0.0000 |
| TPC-H 10  | 0.430270910263    | 10   | 0.519147455692    | 10   | +21%   |     (run time too short) 0.0000 |
| TPC-H 11  | 1.93563330173     | 10   | 4.68636655807     | 10   | +142%  |     (run time too short) 0.0000 |
| TPC-H 12  | 0.776796936989    | 10   | 0.705871284008    | 10   | -9%    |     (run time too short) 0.0000 |
| TPC-H 13  | 0.702049076557    | 10   | 0.807989239693    | 10   | +15%   |     (run time too short) 0.0000 |
| TPC-H 14  | 1.50640630722     | 10   | 1.56736207008     | 10   | +4%    |     (run time too short) 0.0008 |
| TPC-H 15  | 0.438291549683    | 10   | 0.290296584368    | 10   | -34%   |     (run time too short) 0.0000 |
| TPC-H 16  | 0.366202861071    | 10   | 0.401498913765    | 10   | +10%   |     (run time too short) 0.0000 |
| TPC-H 17  | 0.00817817635834  | 10   | 0.00895469170064  | 10   | +9%    |                          0.0000 |
| TPC-H 18  | 0.00155706331134  | 4    | 0.00156903022435  | 4    | +1%    |        (not enough runs) 0.8629 |
| TPC-H 19  | 0.0606515929103   | 10   | 0.0609992034733   | 10   | +1%    |                          0.0096 |
| TPC-H 21  | 0.000621643965133 | 2    | 0.00063610059442  | 2    | +2%    |        (not enough runs) 0.4894 |
| TPC-H 22  | 0.00160693004727  | 4    | 0.00162598362658  | 4    | +1%    |        (not enough runs) 0.1277 |
| average   |                   |      |                   |      | +284%  |                                 |
+-----------+-------------------+------+-------------------+------+--------+---------------------------------+
```

### CODE REVIEW

File: src/lib/optimizer/join_graph_builder.cpp [hunk 1]
```diff
@@ -0,0 +1,265 @@
+#include "join_graph_builder.hpp"
```
Comment (mrzzzrm) [inline src/lib/optimizer/join_graph_builder.cpp]: This is mostly the JoinGraphBuilder that was already part of the master prior to #882, simplified now thanks to the new expression system. A thorough review shouldn't be required.

**Comment by mrzzzrm** [comment]
Ready for review

File: src/lib/optimizer/enumerate_ccp.cpp [hunk 2]
```diff
@@ -0,0 +1,173 @@
...
+    exclusion_set.set(exclusion_vertex_idx);
+  }
+  return exclusion_set;
+}
+
+JoinGraphVertexSet EnumerateCcp::_neighborhood(const JoinGraphVertexSet& vertex_set,
+                                               const JoinGraphVertexSet& exclusion_set) const {
+  JoinGraphVertexSet neighborhood(_num_vertices);
+
+  for (auto current_vertex_idx = size_t{0}; current_vertex_idx < _num_vertices; ++current_vertex_idx) {
```
Comment (timzimmermann) [inline src/lib/optimizer/enumerate_ccp.cpp]: Same question as above.

File: src/lib/optimizer/join_graph_builder.cpp [hunk 3]
```diff
@@ -0,0 +1,265 @@
...
+      }
+    }
+  }
+
+  if (one_vertex_per_component.size() < 2) return {};
+
+  std::vector<JoinGraphEdge> inter_component_edges;
+  inter_component_edges.reserve(one_vertex_per_component.size() - 1);
+
+  for (auto component_idx = size_t{1}; component_idx < one_vertex_per_component.size(); ++component_idx) {
```
Comment (timzimmermann) [inline src/lib/optimizer/join_graph_builder.cpp]: Same question as above.

File: src/lib/optimizer/join_graph_builder.cpp [hunk 4]
```diff
@@ -0,0 +1,265 @@
...
+    inter_component_edges.emplace_back(vertex_set);
+  }
+
+  return inter_component_edges;
+}
+
+JoinGraphVertexSet JoinGraphBuilder::_get_vertex_set_accessed_by_expression(
+    const AbstractExpression& expression, const std::vector<std::shared_ptr<AbstractLQPNode>>& vertices) {
+  auto vertex_set = JoinGraphVertexSet{vertices.size()};
+  for (auto vertex_idx = size_t{0}; vertex_idx < vertices.size(); ++vertex_idx) {
```
Comment (timzimmermann) [inline src/lib/optimizer/join_graph_builder.cpp]: Same question as above.

File: src/lib/optimizer/strategy/join_ordering_rule.cpp [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+  auto result_lqp = _perform_join_ordering_recursively(root->left_input());
+
+  // Join ordering might change the output column order, let's fix that
+  if (!expressions_equal(expected_column_order, result_lqp->column_expressions())) {
+    result_lqp = ProjectionNode::make(expected_column_order, result_lqp);
+  }
+
+  root->set_left_input(result_lqp);
+
+  // Figuring out whether JoinOrderingRule changed to LQP is hard, and it should be applied only once, anyway.
```
Comment (timzimmermann) [inline src/lib/optimizer/strategy/join_ordering_rule.cpp]: Typo: changed THE LQP

File: src/lib/statistics/base_column_statistics.cpp [hunk 6]
```diff
@@ -22,4 +22,10 @@ std::shared_ptr<BaseColumnStatistics> BaseColumnStatistics::without_null_values(
   return clone;
 }
 
+std::shared_ptr<BaseColumnStatistics> BaseColumnStatistics::only_null_values() const {
```
Comment (timzimmermann) [inline src/lib/statistics/base_column_statistics.cpp]: I'm not super happy about this but not sure what to do.
If there is a statistics object that says there are only null values then distinct count and min/max should not be set to inconsistent values.
This seems like a larger problem, though, and not part of this PR.
I wanted to mention it and hear what you think about it.
My proposal would be to introduce an additional type of column statistics that represents a column full of null values.

File: src/lib/optimizer/enumerate_ccp.cpp [hunk 7]
```diff
@@ -0,0 +1,173 @@
...
+  }
+#endif
+}
+
+std::vector<std::pair<JoinGraphVertexSet, JoinGraphVertexSet>> EnumerateCcp::operator()() {
+  /**
+   * Initialize vertex neighborhood lookup table
+   */
+  _vertex_neighborhoods.resize(_num_vertices);
+  for (auto vertex_idx = size_t{0}; vertex_idx < _num_vertices; ++vertex_idx) {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/enumerate_ccp.cpp]: Herb Sutter once said C++ is moving towards `auto name = type{args}` as the universal initializer form to rule them all. Here I am following the word of god.

File: src/lib/optimizer/enumerate_ccp.cpp [hunk 8]
```diff
@@ -0,0 +1,173 @@
...
+    _vertex_neighborhoods[vertex_idx] = _single_vertex_neighborhood(vertex_idx);
+  }
+
+  /**
+   * This loop corresponds to EnumerateCsg in the paper
+   * Iterate fro the highest to the lowest vertex index
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/enumerate_ccp.cpp]: done

File: src/lib/optimizer/enumerate_ccp.cpp [hunk 9]
```diff
@@ -0,0 +1,173 @@
...
+
+#if IS_DEBUG
+  // Assert that the algorithm didn't create duplicates and that all created ccps contain only previously enumerated
+  // subsets
+
+  std::set<JoinGraphVertexSet> enumerated_subsets;
+  std::set<std::pair<JoinGraphVertexSet, JoinGraphVertexSet>> enumerated_ccps;
+
+  for (auto csg_cmp_pair : _csg_cmp_pairs) {
+    // Components must be either single-vertex or must have been enumerated as the vertex set of a previously CCP
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/enumerate_ccp.cpp]: done

File: src/lib/optimizer/enumerate_ccp.cpp (hunk 2 above)
Comment (mrzzzrm) [reply src/lib/optimizer/enumerate_ccp.cpp]: same answer as above ;)

File: src/lib/optimizer/strategy/join_ordering_rule.cpp (hunk 5 above)
Comment (mrzzzrm) [reply src/lib/optimizer/strategy/join_ordering_rule.cpp]: done

File: src/lib/statistics/base_column_statistics.cpp (hunk 6 above)
Comment (mrzzzrm) [reply src/lib/statistics/base_column_statistics.cpp]: The BaseColumnStatistics are such a zombie that this method feels almost clean to me. I'd leave it as it is, added this function mainly for consistency with `without_null_values()`

File: src/lib/optimizer/enumerate_ccp.cpp [hunk 10]
```diff
@@ -0,0 +1,174 @@
...
+  return neighbourhood;
+}
+
+std::vector<JoinGraphVertexSet> EnumerateCcp::_non_empty_subsets(const JoinGraphVertexSet& vertex_set) const {
+  if (vertex_set.none()) return {};
+
+  std::vector<JoinGraphVertexSet> subsets;
+
+  const auto s = vertex_set.to_ulong();
+  auto s1 = s & -s;
```
Comment (SvenLehmann) [inline src/lib/optimizer/enumerate_ccp.cpp]: That's not intuitive to me. Could you add a comment?

File: src/lib/optimizer/enumerate_ccp.cpp [hunk 11]
```diff
@@ -0,0 +1,174 @@
...
+
+  while (s1 != s) {
+    subsets.emplace_back(_num_vertices, s1);
+    s1 = s & (s1 - s);
```
Comment (SvenLehmann) [inline src/lib/optimizer/enumerate_ccp.cpp]: See above

File: src/lib/optimizer/enumerate_ccp.hpp [hunk 12]
```diff
@@ -0,0 +1,52 @@
...
+ * CsgCmpPair enumeration algorithm described in in https://dl.acm.org/citation.cfm?id=1164207
+ */
+class EnumerateCcp final {
+ public:
+  EnumerateCcp(const size_t num_vertices, std::vector<std::pair<size_t, size_t>> edges);
+
+  // Corresponds to EnumerateCsg in the paper
+  std::vector<std::pair<JoinGraphVertexSet, JoinGraphVertexSet>> operator()();
+
+ private:
```
Comment (SvenLehmann) [inline src/lib/optimizer/enumerate_ccp.hpp]: I think in most other header files we first have private methods and then private class variables. Any reason you changed the order here?

File: src/lib/optimizer/enumerate_ccp.hpp [hunk 13]
```diff
@@ -0,0 +1,52 @@
...
+#include "join_graph_edge.hpp"
+
+namespace opossum {
+
+class JoinGraph;
+
+/**
+ * CsgCmpPair enumeration algorithm described in in https://dl.acm.org/citation.cfm?id=1164207
+ */
+class EnumerateCcp final {
```
Comment (SvenLehmann) [inline src/lib/optimizer/enumerate_ccp.hpp]: General remark: Without reading it is quite hard to get what you are doing in this class. Could you add a short comment explaining the most basic steps?

File: src/lib/optimizer/join_graph.hpp [hunk 14]
```diff
@@ -0,0 +1,53 @@
...
+ *      -> Vertices: output tables subplans
+ *      -> Edges: predicates clustered by the vertices that they access
+ *
+ * It is used by join ordering algorithms.
+ */
+class JoinGraph final {
+ public:
+  /**
+   * Tries to turn the subplan rooted at @lqp into a JoinGraph.
+   * @return nullptr, it this is impossible (e.g., lqp is a Sort/AggregateNode)
```
Comment (SvenLehmann) [inline src/lib/optimizer/join_graph.hpp]: Did you mean `returns empty optional`?

File: src/lib/statistics/column_statistics.cpp [hunk 15]
```diff
@@ -114,7 +114,7 @@ FilterByValueEstimate ColumnStatistics<std::string>::estimate_predicate_with_val
       return estimate_not_equals_with_value(casted_value);
     }
     // TODO(anybody) implement other table-scan operators for string.
-    default: { return {non_null_value_ratio(), without_null_values()}; }
+    default: { return {non_null_value_ratio() * 0.1f, without_null_values()}; }
```
Comment (SvenLehmann) [inline src/lib/statistics/column_statistics.cpp]: Where does this number come from?

File: src/lib/statistics/column_statistics.cpp [hunk 16]
```diff
@@ -373,7 +373,7 @@ FilterByColumnComparisonEstimate ColumnStatistics<std::string>::estimate_predica
     return {0.f, without_null_values(), right_column_statistics.without_null_values()};
   }
 
-  return {non_null_value_ratio() * right_column_statistics.non_null_value_ratio(), without_null_values(),
+  return {non_null_value_ratio() * right_column_statistics.non_null_value_ratio() * 0.1f, without_null_values(),
```
Comment (SvenLehmann) [inline src/lib/statistics/column_statistics.cpp]: See above

File: src/test/optimizer/dp_ccp_test.cpp [hunk 17]
```diff
@@ -0,0 +1,103 @@
...
+    b_a = node_b->get_column("a");
+    c_a = node_c->get_column("a");
+  }
+
+  std::shared_ptr<MockNode> node_a, node_b, node_c;
+  std::shared_ptr<AbstractCostEstimator> cost_estimator;
+  LQPColumnReference a_a, b_a, c_a;
+};
+
+TEST_F(DpCcpTest, Basic) {
```
Comment (SvenLehmann) [inline src/test/optimizer/dp_ccp_test.cpp]: Only two tests for this rather complex algorithm? I'd like to see additional tests with multiple tables and additional predicates. These two seem too simple to me :)

File: src/test/optimizer/strategy/join_ordering_rule_test.cpp [hunk 18]
```diff
@@ -0,0 +1,85 @@
...
+    d_a = node_d->get_column("a");
+  }
+
+  std::shared_ptr<MockNode> node_a, node_b, node_c, node_d;
+  LQPColumnReference a_a, b_a, c_a, d_a;
+  std::shared_ptr<AbstractCostEstimator> cost_estimator;
+  std::shared_ptr<JoinOrderingRule> rule;
+};
+
+TEST_F(JoinOrderingRuleTest, MultipleJoinGraphs) {
```
Comment (SvenLehmann) [inline src/test/optimizer/strategy/join_ordering_rule_test.cpp]: Again, this single tests looks rather simple to me not covering many cases. Could you add some more?

File: src/lib/optimizer/enumerate_ccp.hpp (hunk 13 above)
Comment (Bouncner) [reply src/lib/optimizer/enumerate_ccp.hpp]: Also `in in`.

And please add in quotes what paper you are referring to. This is not a DOI link which should be more stable over years. ACM is currently restructuring the DL site. I hope that won't screw up existing links but you never know.

File: src/lib/optimizer/strategy/join_ordering_rule.cpp [hunk 19]
```diff
@@ -0,0 +1,68 @@
...
+namespace opossum {
+
+JoinOrderingRule::JoinOrderingRule(const std::shared_ptr<AbstractCostEstimator>& cost_estimator)
+    : _cost_estimator(cost_estimator) {}
+
+std::string JoinOrderingRule::name() const { return "JoinOrderingRule"; }
+
+bool JoinOrderingRule::apply_to(const std::shared_ptr<AbstractLQPNode>& root) const {
+  /**
+   * Dispatch _perform_join_ordering_recursively() and fix the column order afterwards
```
Comment (mrks) [inline src/lib/optimizer/strategy/join_ordering_rule.cpp]: What does "fix" mean here?

File: src/lib/optimizer/strategy/join_ordering_rule.cpp [hunk 20]
```diff
@@ -0,0 +1,68 @@
...
+
+  // Join ordering might change the output column order, let's fix that
+  if (!expressions_equal(expected_column_order, result_lqp->column_expressions())) {
+    result_lqp = ProjectionNode::make(expected_column_order, result_lqp);
+  }
+
+  root->set_left_input(result_lqp);
+
+  // Figuring out whether the JoinOrderingRule changed the LQP is hard, and the rule should be applied only once,
+  // anyway. So, return false.
```
Comment (mrks) [inline src/lib/optimizer/strategy/join_ordering_rule.cpp]: Isn't that made sure by the execution policy? Returning a false result just because you (currently) know what the caller does with it smells.

File: src/lib/optimizer/join_graph_edge.hpp [hunk 21]
```diff
@@ -0,0 +1,41 @@
...
+ * as union, intersection and subtraction.
+ */
+using JoinGraphVertexSet = boost::dynamic_bitset<>;
+
+/**
+ * Represents a (hyper)edge in a JoinGraph.
+ *
+ * Each predicate must operate exactly on the vertices in vertex_set. That is, each predicate must reference columns
+ * from all vertices in vertex_set and no columns from vertices not in vertex_set. If the predicate wouldn't, then it
+ * would belong to another edge.
```
Comment (mrks) [inline src/lib/optimizer/join_graph_edge.hpp]: Enforce in constructor?

File: src/lib/optimizer/join_graph_edge.hpp [hunk 22]
```diff
@@ -0,0 +1,41 @@
...
+ */
+class JoinGraphEdge final {
+ public:
+  explicit JoinGraphEdge(const JoinGraphVertexSet& vertex_set,
+                         const std::vector<std::shared_ptr<AbstractExpression>>& predicates = {});
+
+  void print(std::ostream& stream = std::cout) const;
+
+  JoinGraphVertexSet vertex_set;
+  std::vector<std::shared_ptr<AbstractExpression>> predicates;
```
Comment (mrks) [inline src/lib/optimizer/join_graph_edge.hpp]: const?

File: src/lib/optimizer/join_graph_builder.hpp [hunk 23]
```diff
@@ -0,0 +1,94 @@
...
+ *        \_[4] [MockTable] y
+ *
+ * The JoinGraph created from it would contain two vertices (x and y), one edge (between x and y, with the predicate
+ * x2 <= y1) and one output_relation (Projection, left input side)
+ */
+class JoinGraphBuilder final {
+ public:
+  /**
+   * From an LQP, build a JoinGraph. The LQP is not modified during this process.
+   * std::nullopt is returned if the JoinGraph would be trivial (i.e., one vertex, no predicates)
```
Comment (mrks) [inline src/lib/optimizer/join_graph_builder.hpp]: This seems to be different from the comment in `from_lqp` above

File: src/lib/optimizer/join_graph_builder.hpp [hunk 24]
```diff
@@ -0,0 +1,94 @@
...
+      const std::vector<std::shared_ptr<AbstractLQPNode>>& vertices,
+      const std::vector<std::shared_ptr<AbstractExpression>>& predicates);
+
+  static std::vector<JoinGraphEdge> cross_edges_between_components(
+      const std::vector<std::shared_ptr<AbstractLQPNode>>& vertices, std::vector<JoinGraphEdge> edges);
+
+  /**
+   * Traverse the LQP recursively identifying predicates and vertices along the way
+   */
+  void traverse(const std::shared_ptr<AbstractLQPNode>& node);
```
Comment (mrks) [inline src/lib/optimizer/join_graph_builder.hpp]: This doesn't look like it is used from the outside. Make it private?

File: src/lib/optimizer/join_graph_builder.cpp [hunk 25]
```diff
@@ -0,0 +1,265 @@
...
+
+      if (union_node->union_mode == UnionMode::Positions) {
+        const auto parse_result = _parse_union(union_node);
+
+        traverse(parse_result.base_node);
+        _predicates.emplace_back(parse_result.predicate);
+      } else {
+        _vertices.emplace_back(node);
+      }
+    } break;
```
Comment (mrks) [inline src/lib/optimizer/join_graph_builder.cpp]: I think we usually have the break within the block

File: src/lib/cost_model/cost_model_logical.cpp [hunk 26]
```diff
@@ -1,45 +1,63 @@
...
-  switch (operator_type) {
-    case OperatorType::JoinHash:
-      return feature_proxy.extract_feature(CostFeature::LeftInputRowCount).scalar() +
-             feature_proxy.extract_feature(CostFeature::RightInputRowCount).scalar();
-
-    case OperatorType::TableScan:
-      return feature_proxy.extract_feature(CostFeature::LeftInputRowCount).scalar();
+  switch (node->type) {
+    case LQPNodeType::Join:
+      return left_row_count + right_row_count + output_row_count;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/cost_model/cost_model_logical.cpp]: Your proposed formula taxes cross joins the same as predicated joins. Mine taxes cross joins higher, since output_row_count will be higher for them.
A logical cost model returns the approximate number of tuple read/writes.

File: src/lib/optimizer/dp_ccp.cpp [hunk 27]
```diff
@@ -0,0 +1,182 @@
...
+    const auto first_vertex_idx = edge.vertex_set.find_first();
+    const auto second_vertex_idx = edge.vertex_set.find_next(first_vertex_idx);
+
+    enumerate_ccp_edges.emplace_back(first_vertex_idx, second_vertex_idx);
+  }
+
+  /**
+   * 3. Actual DpCcp algorithm: Enumerate the CsgCmpPairs; build candidate plans; update best_plan
+   */
+  const auto csg_cmp_pairs = EnumerateCcp{join_graph.vertices.size(), enumerate_ccp_edges}();  // NOLINT
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/dp_ccp.cpp]: CsgCmpPair is canon if you deal with join ordering algorithms, yes. I don't feel like explaining the concept in code is doing the reader a favour, since a more formal and correct explanation will always be in the paper.

File: src/lib/optimizer/dp_ccp.cpp [hunk 28]
```diff
@@ -0,0 +1,182 @@
...
+   * directly on top of `lqp`, with the cheapest predicate becoming the primary predicate.
+   */
+
+  if (join_predicates.empty()) return JoinNode::make(JoinMode::Cross, left_lqp, right_lqp);
+
+  // Sort the predicates by increasing cost
+  auto join_predicates_and_cost = std::vector<std::pair<std::shared_ptr<AbstractExpression>, Cost>>{};
+  join_predicates_and_cost.reserve(join_predicates.size());
+  for (const auto& join_predicate : join_predicates) {
+    const auto join_node = JoinNode::make(JoinMode::Inner, join_predicate, left_lqp, right_lqp);
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/dp_ccp.cpp]: Will be treated as vertices on JoinGraph creation. Dealing with non-inner joins in join ordering is possible, but wasn't in the scope of my MA and this PR

File: src/lib/statistics/column_statistics.cpp (hunk 15 above)
Comment (mrzzzrm) [reply src/lib/statistics/column_statistics.cpp]: leftovers, removed

File: src/lib/statistics/column_statistics.cpp (hunk 16 above)
Comment (mrzzzrm) [reply src/lib/statistics/column_statistics.cpp]: leftovers, removed

File: src/benchmark/tpch_benchmark.cpp [hunk 29]
```diff
@@ -1,3 +1,4 @@
+#include <numa.h>
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/benchmark/tpch_benchmark.cpp]: leftover, removed

File: src/lib/cost_model/abstract_cost_estimator.cpp [hunk 30]
```diff
@@ -0,0 +1,35 @@
...
+
+#include <queue>
+#include <unordered_set>
+
+#include "logical_query_plan/abstract_lqp_node.hpp"
+
+namespace opossum {
+
+Cost AbstractCostEstimator::estimate_plan_cost(const std::shared_ptr<AbstractLQPNode>& lqp) const {
+  // Cost all operators in arbitrary order
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/cost_model/abstract_cost_estimator.cpp]: Changed to 
```

  // Sum up the costs of all operators in the plan, while making sure to cost each operator exactly once, even in the
  // presence of diamond shapes.
```

File: src/lib/cost_model/cost_model_logical.cpp [hunk 31]
```diff
@@ -1,45 +1,63 @@
...
+      return left_row_count * _get_expression_cost_multiplier(predicate_node->predicate) + output_row_count;
+    }
 
     default:
-      return 0.0f;
+      return left_row_count + output_row_count;
   }
 }
 
+float CostModelLogical::_get_expression_cost_multiplier(const std::shared_ptr<AbstractExpression>& expression) {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/cost_model/cost_model_logical.cpp]: was in header, I moved it here.

File: src/lib/optimizer/join_graph.hpp (hunk 14 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/join_graph.hpp]: Changed to `@return nullopt, if the root node would already be a vertex and thus the JoinGraph wouldn't be meaningful`

File: src/lib/optimizer/join_graph.cpp [hunk 32]
```diff
@@ -0,0 +1,72 @@
...
+
+    for (const auto& predicate : edge.predicates) {
+      predicates.emplace_back(predicate);
+    }
+  }
+
+  return predicates;
+}
+
+void JoinGraph::print(std::ostream& stream) const {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/join_graph.cpp]: I do have a JoinGraphVisualizer in my MA branch. Issue + another PR if you want it, I don't find it thaaat useful.

File: src/lib/optimizer/strategy/join_ordering_rule.hpp [hunk 33]
```diff
@@ -0,0 +1,26 @@
...
+
+#include <memory>
+
+#include "abstract_rule.hpp"
+
+namespace opossum {
+
+class AbstractCostEstimator;
+
+class JoinOrderingRule : public AbstractRule {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/strategy/join_ordering_rule.hpp]: Jup

File: src/lib/optimizer/strategy/join_ordering_rule.hpp [hunk 34]
```diff
@@ -0,0 +1,26 @@
...
+ public:
+  explicit JoinOrderingRule(const std::shared_ptr<AbstractCostEstimator>& cost_estimator);
+
+  std::string name() const override;
+  bool apply_to(const std::shared_ptr<AbstractLQPNode>& root) const override;
+
+ private:
+  std::shared_ptr<AbstractLQPNode> _perform_join_ordering_recursively(
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/strategy/join_ordering_rule.hpp]: Above you look in the cpp for explanations when they were actually in the hpp. Here, they are in the cpp and you look for them in the header. Which one do you want? :stuck_out_tongue:

File: src/lib/optimizer/strategy/join_ordering_rule.cpp (hunk 19 above)
Comment (mrzzzrm) [reply src/lib/optimizer/strategy/join_ordering_rule.cpp]: The comment below states "Join ordering might change the output column order, let's fix that". Sufficient?

File: src/lib/optimizer/strategy/join_ordering_rule.cpp (hunk 20 above)
Comment (mrzzzrm) [reply src/lib/optimizer/strategy/join_ordering_rule.cpp]: I do it because "Figuring out whether the JoinOrderingRule changed the LQP is hard"

I put the "(and the rule should be applied only once, anyway)" bit in parentheses.

File: src/lib/optimizer/join_graph_edge.hpp (hunk 21 above)
Comment (mrzzzrm) [reply src/lib/optimizer/join_graph_edge.hpp]: Cannot be done, the JoinGraphEdge has no idea which LQPNode a vertex index refers to, and rightly so.

File: src/lib/optimizer/join_graph_edge.hpp (hunk 22 above)
Comment (mrzzzrm) [reply src/lib/optimizer/join_graph_edge.hpp]: Makes it impossible to store JoinGraphEdges in a vector, since they can't be assigned to on vector resize. I grow increasingly hostile towards const-ing. Or the STL. 

Solution would be to const these fields and to store the JoinGraphEdges in a vector of unique_ptrs. Should I do that?

File: src/lib/optimizer/join_graph_builder.hpp (hunk 23 above)
Comment (mrzzzrm) [reply src/lib/optimizer/join_graph_builder.hpp]: Adjusted comment for from_lqp, they are similar in wording now.

File: src/lib/optimizer/join_graph_builder.hpp (hunk 24 above)
Comment (mrzzzrm) [reply src/lib/optimizer/join_graph_builder.hpp]: done.

File: src/lib/optimizer/join_graph_builder.cpp (hunk 25 above)
Comment (mrzzzrm) [reply src/lib/optimizer/join_graph_builder.cpp]: I never do, and some other places don't do it either. I think having it outside the block makes it clearer that this break has nothing to do with the logic in the block and is just there since c++'s switch is a stone age tool

File: src/test/optimizer/dp_ccp_test.cpp (hunk 17 above)
Comment (mrzzzrm) [reply src/test/optimizer/dp_ccp_test.cpp]: First, the bulk of the testing is done once EnumerateCCP is proven to work. DPccp is just a "thin" layer around it, conceptually.

Secondly, and more importantly, testing DPccp means making assumptions about a cost model and a cardinality estimator and will thus become quite messy and will need to be changed every time these two are changed. I don't want anyone having to fix 10 DPccp tests everytime they change the cost model or the cardinality estimation.

Anyway, long story short, I'll think about adding more tests, but I might conclude that the current coverage is a good compromise.

File: src/test/optimizer/strategy/join_ordering_rule_test.cpp (hunk 18 above)
Comment (mrzzzrm) [reply src/test/optimizer/strategy/join_ordering_rule_test.cpp]: Again, for the same reasons, I don't think that's a good idea. Yes, I could add more tests and yes, that would make the code less error prone, but oh the horror when you change a bit of estimator logic. 

I'll think if the current test missed some important bit and add it, though.

**Comment by mrzzzrm** [comment]
Two main issues raised here:

### Documentation of `DpCcp` and `EnumerateCcp`
I added some more comments, more out of goodwill than out of belief that this will actually help understanding the algorithm. 
I spend, I think, 10 pages of my MA explaining this algorithm. I cannot hope to boil that down to something that I can put in here as comment without distorting its content.

My stance here is the following: 
* Someone who has read and understood the paper will have no problem following this implementation since all concepts used directly map to concepts in the paper. Any comment explaining DPccp would just be noise for this person.
* Someone who has not understood the algorithm, frankly, doesn't stand a chance understanding it from any commenting I might add. I cannot magically make understanding of a subtle graph-processing algorithm appear in some readers brain just from a few comments, I am sorry. 

I recognize that this makes `DpCcp` and `EnumerateCcp` hard to review in depth, and I cannot offer a satisfying solution for this. Some things are just not simple, and I am afraid this is one of them.

### Testing of `DpCcp` and the `JoinOrderingRule`

@SvenLehmann rightly pointed out that there are not that many tests for `DpCcp` and `JoinOrderingRule`. I will add one or two more tests for `DpCcp` but stand by my point that it is not a good idea to test these too heavily since they heavily rely on the behaviour of the underlying cost model and cardinality estimators and therefore there is no clear definition of what a correctly functioning `DpCcp` or `JoinOrderingRule` entails. Any test I implement will likely need to be adjusted every time these estimators are changed. 
The bulk of correctness for `DpCcp` and therefore the `JoinOrderingRule` is ensured by the `EnumerateCcp`-Test.

File: src/lib/optimizer/dp_ccp.hpp [hunk 35]
```diff
@@ -0,0 +1,34 @@
...
+
+namespace opossum {
+
+class AbstractExpression;
+class AbstractCostEstimator;
+class AbstractLQPNode;
+class JoinGraph;
+
+/**
+ * Optimal join ordering algorithm described in https://dl.acm.org/citation.cfm?id=1164207
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/dp_ccp.hpp]: Added
```
 * DpCcp is an optimal join ordering algorithm based on dynamic programming. It handles only inner joins and cross
 * joins and treats outer joins as opaque (i.e. outer joins are not moved and no other joins are moved pass them).
 * DpCcp is driven by EnumerateCcp which enumerates all candidate join operations. 
 ```

What do you mean by "phases"? (I already dissected `DpCcp::operator()()` into phases and explained them)

File: src/lib/optimizer/enumerate_ccp.cpp (hunk 10 above)
Comment (mrzzzrm) [reply src/lib/optimizer/enumerate_ccp.cpp]: I added a comment that I cannot give a convincing explanation of this algorithm. I added an explanation of its result, though

```
  /**
   * Returns all proper subsets of `vertex_set`, e.g., for 01101 return {00001, 00100, 01000, 01001, 01100}
   *
   * The algorithm listed here is from stackoverflow, but I can't find the link to it anymore, hard as I tried.
   * Neither can I convincingly explain the bit-magic here, but it works nicely.
   */
```

Comment (mrzzzrm) [reply src/lib/optimizer/enumerate_ccp.cpp]: Also added ` // s1 is the current subset subset [sic]. s & -s initializes it to the least significant bit in s`

File: src/lib/optimizer/enumerate_ccp.cpp (hunk 11 above)
Comment (mrzzzrm) [reply src/lib/optimizer/enumerate_ccp.cpp]: Added
```c++

    // This assigns to s1 the next subset of s. Somehow, this bit magic is binary incrementing s1, but only within the 
    // bits set in s. So, if s is 01101 and s1 is 00101, s1 will be update to 01000.
    s1 = s & (s1 - s);
```

File: src/lib/optimizer/dp_ccp.hpp (hunk 35 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/optimizer/dp_ccp.hpp]: nevermind

File: src/lib/optimizer/join_graph.cpp (hunk 32 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/optimizer/join_graph.cpp]: If it's no work and only adds that one visualizer, I would say it doesn't hurt.

File: src/lib/optimizer/strategy/join_ordering_rule.hpp (hunk 34 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/optimizer/strategy/join_ordering_rule.hpp]: The only excuse that I have is that the PR interface sometimes makes me forget which file I am in. Method-level comments should be in the hpp, the way most other classes do it as well.

File: src/lib/optimizer/join_graph_edge.hpp (hunk 21 above)
Comment (mrks) [reply src/lib/optimizer/join_graph_edge.hpp]: Got it. Maybe add this as a comment?

File: src/lib/optimizer/join_graph_edge.hpp (hunk 22 above)
Comment (mrks) [reply src/lib/optimizer/join_graph_edge.hpp]: Vector of unique_ptrs sounds good. Also, because having a vector of JoinGraphEdges would mean that the copy assignment copies the vector of predicates.

File: src/lib/optimizer/dp_ccp.hpp [hunk 36]
```diff
@@ -0,0 +1,42 @@
...
+ * joins and treats outer joins as opaque (i.e. outer joins are not moved and no other joins are moved pass them).
+ * DpCcp is driven by EnumerateCcp which enumerates all candidate join operations.
+ *
+ * Local predicates are pushed down and sorted by increasing cost.
+ */
+class DpCcp final {
+ public:
+  explicit DpCcp(const std::shared_ptr<AbstractCostEstimator>& cost_estimator);
+
+  std::shared_ptr<AbstractLQPNode> operator()(const JoinGraph& join_graph);
```
Comment (mrks) [inline src/lib/optimizer/dp_ccp.hpp]: Could you document the in- and output here? `join_graph` was created based on a partial LQP, correct, so the return LQP only contains the nodes in that partial LQP?

File: src/lib/optimizer/enumerate_ccp.hpp [hunk 37]
```diff
@@ -12,7 +12,9 @@ namespace opossum {
 class JoinGraph;
 
 /**
- * CsgCmpPair enumeration algorithm described in in https://dl.acm.org/citation.cfm?id=1164207
+ * CsgCmpPair enumeration algorithm described in "Analysis of two existing and one new dynamic programming algorithm for
```
Comment (mrks) [inline src/lib/optimizer/enumerate_ccp.hpp]: ("CCP")

File: src/lib/optimizer/enumerate_ccp.cpp (hunk 10 above)
Comment (timzimmermann) [reply src/lib/optimizer/enumerate_ccp.cpp]: Does it also return `00101`?

**Comment by mrks** [comment]
I get your point about the documentation. Maybe it would help to have a high-level explanation of what the different classes do. For example, would it be possible to add a couple of lines to `enumerate_ccp.hpp` explaining what the algorithm takes as input and what its output is? It should at least be possible to understand the public interfaces of the different classes and what they do. *How* they do it is something that people can look up in the paper.

File: src/lib/optimizer/join_graph_edge.hpp (hunk 22 above)
Comment (mrzzzrm) [reply src/lib/optimizer/join_graph_edge.hpp]: I decided that the fields will stay mutual and I will store the edges as instances in a vector. I also made `JoinGraphEdge` a struct, since it is just POD.

*  The `predicates` field needs to be mutable anyway since predicates are collected after the edge is created.
* Copying the occasional vector of predicates isn't ideal, yes, but scattering the edges across the heap (because unique_ptr) is worse. Might just use a `std::list` then, and nobody would do that.

File: src/lib/optimizer/enumerate_ccp.cpp (hunk 10 above)
Comment (mrzzzrm) [reply src/lib/optimizer/enumerate_ccp.cpp]: yes, looks like I forgot that one

File: src/lib/optimizer/dp_ccp.hpp (hunk 36 above)
Comment (mrzzzrm) [reply src/lib/optimizer/dp_ccp.hpp]: Here it is:

```
  /**
   * @param join_graph      A JoinGraph for a part of an LQP with further subplans as vertices. DpCcp is only applied
   *                        to this particular JoinGraph and doesn't modify the subplans in the vertices.
   * @return                An LQP consisting of
   *                         * the operations from the JoinGraph in an optimal order
   *                         * the subplans from the vertices below them
   */
  std::shared_ptr<AbstractLQPNode> operator()(const JoinGraph& join_graph);
```

(I don't like comments like this, because actually there is close to no "new" information in this wall of a comment)

File: src/lib/optimizer/join_graph_edge.hpp (hunk 21 above)
Comment (mrzzzrm) [reply src/lib/optimizer/join_graph_edge.hpp]: Done.

**Comment by mrzzzrm** [comment]
Lots of comments added.

**Comment by mrzzzrm** [comment]
More tests added, I think that's sufficient now. Also added comments explaining why there are so "few" tests for the JoinOrderingRule and DpCcp

File: src/lib/optimizer/join_graph.cpp (hunk 32 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/join_graph.cpp]: Will do this in #1090

File: src/lib/optimizer/strategy/join_ordering_rule.hpp (hunk 34 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/optimizer/strategy/join_ordering_rule.hpp]: I put docs for private functions into the cpp as 
* they are not part of the class interface and thus there is no need to have them in the cpp
* if they are in the cpp they can be a bit more verbose than comments in a header are justified to be

**Comment by mrzzzrm** [comment]
Everything I am aware of is addressed.

**Comment by mrks** [comment]
@SvenLehmann ready?
