### PR TITLE
Fix JoinIndex, add to JoinTestRunner

### LINKED ISSUE #1755: Extending the join test runner for index joins
Using the join test runner, we are doing a state verification for the output table of an executed join operator. Therefore, we don't do a state verification for a join operator which is necessary for index joins. If we expect a join operator to use the indexes but the fall back nested loop join is used instead, the resulting output table will be the same. Therefore we should take `performance_data()` of an executed index join operator into account to verify that indexes were used if they were available.

Additionally, the tables used for the join test runner do currently not contain any indexes. If the intended fast execution paths (using indexes instead of falling back to nested loop) of the index join shall be executed, indexes have to be available for the corresponding join columns.

On top of that, the join test runner doesn't specify the index side for an index join. Therefore the default index side is always used.

### LINKED ISSUE #1852: Find (and fix) index join bugs using the join test runner
With #1851 many different join index test configurations are created and therefore a comprehensive test suite for the index join is executed. By executing these tests, bugs are revealed which are currently not documented and investigated in detail.
Therefore, the following lines are currently commented out:
```c++
// INSTANTIATE_TEST_SUITE_P(JoinIndex, JoinTestRunner,
//                          testing::ValuesIn(JoinTestRunner::create_configurations<JoinIndex>()));
```

### PR DESCRIPTION
**Pull request by mweisgut**
### JoinTestRunner Extension: Tests for Index Join
The `JoinTestRunner` creates different join configurations in order to simulate different join scenarios. These join scenarios are then executed by using different join operators (currently `JoinNestedLoop`, `JoinHash`, `JoinSortMerge`).

This PR integrates the creation of join configurations for the `JoinIndex` operator and the execution of the corresponding join scenarios (closes #1755).

Compared to other join operators, the execution of `JoinIndex` is influenced by additional parameters (index side, indexes available). Therefore, a general function for creating more specialized configurations for operators whose executions are influenced by additional parameters is added. This function needs one basic configuration as input and returns a vector of specialized configurations as output.

### Identifying and Fixing Bugs
In addition, the newly integrated tests for the Index Join are used to find bugs that are either fixed in this PR or documented in the issue list (closes #1852).

**Bug Tracker**
- no support for inequality between probe value type and indexed value type - #2077 
- Semi Join, IndexSide::Left - **fixed** (ceb068b7bd41e6dd7cdbfbf6d78db8400bad5378, c0ad173cfc59cdc006c2bc09426e0c87d65bf9ca)
- incorrect results when the join mode `AntiNullAsTrue` is used: execution is currently not null-aware as proposed by Bellamkonda et al. [1]. - **fixed** (ee550e7f19b72120dc749f45e73e6760af2ceed6, 9f60fb0df32d034b6b5c2d8959df01680c5affb9)
- Semi/Anti Join, IndexSide::Right - ~~**fixed**~~ (6c5f0ab03cab127b1c987251da466f0a17d75ef6), **removed the support** (0e58af38af06508007ce20ebf9387fd3775651aa)

### Adapting the Index Join Test Suite
Since the `JoinTestRunner` generates many different test cases for testing the `JoinIndex`, the previous test suite for the Index Join is significantly reduced.

### References
[1] Bellamkonda, Srikanth & Ahmed, Rafi & Witkowski, Andrew & Amor, Angela & Zaït, Mohamed & Lin, Chun. (2009). Enhanced Subquery Optimizations in Oracle.. PVLDB. 2. 1366-1377. 10.14778/1687553.1687563. (Section 6: NULL-AWARE ANTI JOIN (NAAJ))

### CODE REVIEW

File: src/test/operators/join_test_runner.cpp [hunk 1]
```diff
@@ -163,6 +173,7 @@ class JoinTestRunner : public BaseTestWithParam<JoinTestConfiguration> {
         {{{ColumnID{0}, ColumnID{0}}, PredicateCondition::LessThan}},
         {{{ColumnID{0}, ColumnID{0}}, PredicateCondition::GreaterThanEquals}},
         {{{ColumnID{0}, ColumnID{0}}, PredicateCondition::NotEquals}}};
+    const auto all_index_sides = std::vector{IndexSide::Left, IndexSide::Right};
```
Comment (Bouncner) [inline src/test/operators/join_test_runner.cpp]: Just scrolling over the code. Do we also need to test `IndexSide::Left`? Could there be a case where to use both sides' indexes?

File: src/test/operators/join_test_runner.cpp [hunk 2]
```diff
@@ -189,16 +200,56 @@ class JoinTestRunner : public BaseTestWithParam<JoinTestConfiguration> {
     };
     // clang-format on
 
-    const auto add_configuration_if_supported = [&](const auto& configuration) {
-      // String vs non-String comparisons are not supported in Hyrise and therefore cannot be tested
-      if ((configuration.data_type_left == DataType::String) != (configuration.data_type_right == DataType::String)) {
-        return;
+    /**
+     * Returns a set of adapted configurations is the join type provides further configuration possibilities
```
Comment (Bouncner) [inline src/test/operators/join_test_runner.cpp]: is > if
Else COMMA?

File: src/test/operators/join_test_runner.cpp [hunk 3]
```diff
@@ -189,16 +200,56 @@ class JoinTestRunner : public BaseTestWithParam<JoinTestConfiguration> {
...
+     * which are should be tested.
+     * Else a vector containing only the passed configuration is returned.
+     */
+    const auto build_join_type_specific_variations = [&](const auto& configuration) {
+      if constexpr (std::is_same_v<JoinOperator, JoinIndex>) {
+        // using factor 2 since has_indexes can either be true or false.
+        std::vector<JoinTestConfiguration> variations(all_index_sides.size() /* TODO * 2 */, configuration);
```
Comment (Bouncner) [inline src/test/operators/join_test_runner.cpp]: What's that todo?

File: src/test/operators/join_test_runner.cpp [hunk 4]
```diff
@@ -189,16 +200,56 @@ class JoinTestRunner : public BaseTestWithParam<JoinTestConfiguration> {
...
+        uint8_t variation_index{0};
+        for (const auto& index_side : all_index_sides) {
+          for (const auto& has_indexes : {true /* TODO , false*/}) {
```
Comment (Bouncner) [inline src/test/operators/join_test_runner.cpp]: dto

File: src/test/operators/join_test_runner.cpp [hunk 5]
```diff
@@ -484,6 +535,23 @@ class JoinTestRunner : public BaseTestWithParam<JoinTestConfiguration> {
         table = reference_table;
       }
 
+      /**
+       * To sufficiently test IndexJoins, indexes has to be created. Therefore, if index_side is set in the configuration,
```
Comment (Bouncner) [inline src/test/operators/join_test_runner.cpp]: has > have

File: src/test/operators/join_test_runner.cpp [hunk 6]
```diff
@@ -484,6 +535,23 @@ class JoinTestRunner : public BaseTestWithParam<JoinTestConfiguration> {
...
+       * indexes for the table have to be created. The index type is either GroupKeyIndex for dictionary segmetns or
```
Comment (Bouncner) [inline src/test/operators/join_test_runner.cpp]: segmetns

File: src/test/operators/join_test_runner.cpp [hunk 7]
```diff
@@ -535,12 +603,14 @@ TEST_P(JoinTestRunner, TestJoin) {
     Print::print(input_table_left, PrintFlags::IgnoreChunkBoundaries);
     std::cout << "Chunk size: " << configuration.input_left.chunk_size << std::endl;
     std::cout << "Table type: " << input_table_type_to_string.at(configuration.input_left.table_type) << std::endl;
+    std::cout << "Has indexes: " << (input_table_left->indexes_statistics().empty() ? "false" : "true") << std::endl;
```
Comment (Bouncner) [inline src/test/operators/join_test_runner.cpp]: std::boolalpha

File: src/test/operators/join_test_runner.cpp [hunk 8]
```diff
@@ -535,12 +603,14 @@ TEST_P(JoinTestRunner, TestJoin) {
...
     std::cout << get_table_path(configuration.input_left) << std::endl;
     std::cout << std::endl;
     std::cout << "===================== Right Input Table ====================" << std::endl;
     Print::print(input_table_right, PrintFlags::IgnoreChunkBoundaries);
     std::cout << "Chunk size: " << configuration.input_right.chunk_size << std::endl;
     std::cout << "Table size: " << input_table_type_to_string.at(configuration.input_right.table_type) << std::endl;
+    std::cout << "Has indexes: " << (input_table_right->indexes_statistics().empty() ? "false" : "true") << std::endl;
```
Comment (Bouncner) [inline src/test/operators/join_test_runner.cpp]: std::boolalpha

File: src/test/operators/join_test_runner.cpp [hunk 9]
```diff
@@ -585,6 +655,17 @@ TEST_P(JoinTestRunner, TestJoin) {
     print_configuration_info();
     FAIL();
   }
+
+  // TODO(anyone) check performance data if an index join was used.
```
Comment (Bouncner) [inline src/test/operators/join_test_runner.cpp]: This todo is pretty concrete, why not implement it?

File: src/test/operators/join_test_runner.cpp [hunk 10]
```diff
@@ -593,9 +674,9 @@ INSTANTIATE_TEST_SUITE_P(JoinHash, JoinTestRunner,
                          testing::ValuesIn(JoinTestRunner::create_configurations<JoinHash>()));
 INSTANTIATE_TEST_SUITE_P(JoinSortMerge, JoinTestRunner,
                          testing::ValuesIn(JoinTestRunner::create_configurations<JoinSortMerge>()));
+// TODO(anyone) #1852
```
Comment (Bouncner) [inline src/test/operators/join_test_runner.cpp]: That's doesn't help a lot. Can you give a short description of what's the todo here?

File: src/test/operators/join_test_runner.cpp [hunk 11]
```diff
@@ -593,9 +674,9 @@ INSTANTIATE_TEST_SUITE_P(JoinHash, JoinTestRunner,
...
 // INSTANTIATE_TEST_SUITE_P(JoinIndex, JoinTestRunner,
 //                          testing::ValuesIn(JoinTestRunner::create_configurations<JoinIndex>()));
 INSTANTIATE_TEST_SUITE_P(JoinMPSM, JoinTestRunner,
                          testing::ValuesIn(JoinTestRunner::create_configurations<JoinMPSM>()));
-
```
Comment (Bouncner) [inline src/test/operators/join_test_runner.cpp]: MPSM: merge with master.

File: src/test/operators/join_test_runner.cpp [hunk 12]
```diff
@@ -189,16 +200,56 @@ class JoinTestRunner : public BaseTestWithParam<JoinTestConfiguration> {
...
-      // String vs non-String comparisons are not supported in Hyrise and therefore cannot be tested
-      if ((configuration.data_type_left == DataType::String) != (configuration.data_type_right == DataType::String)) {
-        return;
+    /**
+     * Returns a set of adapted configurations is the join type provides further configuration possibilities
+     * which are should be tested.
+     * Else a vector containing only the passed configuration is returned.
+     */
+    const auto build_join_type_specific_variations = [&](const auto& configuration) {
+      if constexpr (std::is_same_v<JoinOperator, JoinIndex>) {
```
Comment (Bouncner) [inline src/test/operators/join_test_runner.cpp]: A short description for the index join adaptions would be great.

**Comment by mrks** [comment]
Closing this for now, as it is evident that no one currently has the resources to work on it. :(

File: src/test/operators/join_test_runner.cpp (hunk 1 above)
Comment (mweisgut) [reply src/test/operators/join_test_runner.cpp:175]: >Do we also need to test IndexSide::Left?

Since both `IndexSide::Left` and `IndexSide::Right` are currently supported by the JoinIndex implementation, `IndexSide::Left` should be tested. If the index is on the left side, the swapping mechanism is triggered, which is implemented as part of the JoinIndex operator itself.

>Could there be a case where to use both sides' indexes?

I'm not sure if there could be a case where using both sides' indexes would be beneficial. However, we currently only support either left or right as an index side in the JoinIndex operator implementation.

File: src/test/operators/join_test_runner.cpp (hunk 9 above)
Comment (mweisgut) [reply src/test/operators/join_test_runner.cpp:654]: Due to time constraints in the past. Is now being tackled.

**Comment by mweisgut** [comment]
Next bug: `./hyriseTest --gtest_filter=*x/J*T*R*/510`

**Comment by mweisgut** [comment]
```
====================== JoinOperator ========================
JoinIndex
(AntiNullAsTrue Join where l_int_null = r_int_null)
Index side: Left
===================== Left Input Table =====================
=== Columns
|   l_int|l_int_null| l_float|l_float_null|   l_double|l_double_null|    l_long|l_long_null|l_string|l_string_null|
|     int|       int|   float|       float|     double|       double|      long|       long|  string|       string|
|not null|      null|not null|        null|   not null|         null|  not null|       null|not null|         null|
|    1338|      7331|    1338|       724.3|       1338|       1337.2|      7331| 4294968633|       m|            m|
|     724|      1338|    1338|        1337|4.29497e+09|       7331.6|4294968633|       NULL|       o|         NULL|
|    1337|      7331|    1338|        NULL|     1337.7|         NULL|      1337|       7331|       p|            o|
|    7331|      NULL|  1337.2|        NULL|     1337.2|  4.29497e+09|      1337|       1337|       p|            d|
|    7331|      NULL|  1337.7|        1338|      724.3|         NULL|4294968633|       1338|       a|            a|
|     724|      7331|    1337|      1337.2|4.29497e+09|         NULL|      7331|        724|       r|         NULL|
|    7331|      1337|  7331.6|      1337.2|     7331.6|         1338|       724|       NULL|       m|            o|
|    1338|      NULL|    1337|        NULL|       1337|       1337.7|       724|       NULL|       d|         NULL|
|    1337|       724|   724.3|      7331.6|      724.3|        724.3|      1337|       1338|       p|            r|
|    7331|      1338|    1337|      1337.7|     1337.7|         1337|      1338|       7331|       a|            p|
Chunk size: 10
Table type: Data
Has indexes: true
resources/test_data/tbl/join_test_runner/input_table_left_10.tbl

===================== Right Input Table ====================
=== Columns
|   r_int|r_int_null| r_float|r_float_null|   r_double|r_double_null|    r_long|r_long_null|r_string|r_string_null|
|     int|       int|   float|       float|     double|       double|      long|       long|  string|       string|
|not null|      null|not null|        null|   not null|         null|  not null|       null|not null|         null|
|    1337|      1338|  9331.8|      1337.8|4.29497e+09|       9331.8|      1338|       NULL|       c|            c|
|    1338|      1337|  1337.8|       976.1|      976.1|        976.1|      1338|       9331|       m|            p|
|    1338|      1338|  1337.8|        NULL|       1337|         NULL|      1338|       NULL|       p|         NULL|
|    9331|       976|   976.1|        NULL|     1337.8|         1337|      9331| 4294968633|       c|         NULL|
|    9331|       976|  9331.8|      1337.8|     1337.7|         1338|       976|       NULL|       l|         NULL|
|    1337|      NULL|  1337.8|      1337.7|     1337.8|       1337.7|4294968633|       NULL|       p|            l|
|     976|      NULL|  1337.8|        NULL|       1337|  4.29497e+09|      1337|       NULL|       l|            t|
|     976|      NULL|  1337.7|      9331.8|       1338|       1337.8|       976|       1337|       t|            d|
|    1337|      NULL|    1337|        1337|     9331.8|         NULL|      9331|       1338|       m|            m|
|    9331|      9331|    1338|        1338|     1337.8|         NULL|      1337|        976|       d|         NULL|
Chunk size: 10
Table size: Data
Has indexes: false
resources/test_data/tbl/join_test_runner/input_table_right_10.tbl

==================== Actual Output Table ===================
=== Columns
|   l_int|l_int_null| l_float|l_float_null|   l_double|l_double_null|    l_long|l_long_null|l_string|l_string_null|
|     int|       int|   float|       float|     double|       double|      long|       long|  string|       string|
|not null|      null|not null|        null|   not null|         null|  not null|       null|not null|         null|
|    1338|      7331|    1338|       724.3|       1338|       1337.2|      7331| 4294968633|       m|            m|
|    1337|      7331|    1338|        NULL|     1337.7|         NULL|      1337|       7331|       p|            o|
|    7331|      NULL|  1337.2|        NULL|     1337.2|  4.29497e+09|      1337|       1337|       p|            d|
|    7331|      NULL|  1337.7|        1338|      724.3|         NULL|4294968633|       1338|       a|            a|
|     724|      7331|    1337|      1337.2|4.29497e+09|         NULL|      7331|        724|       r|         NULL|
|    1338|      NULL|    1337|        NULL|       1337|       1337.7|       724|       NULL|       d|         NULL|
|    1337|       724|   724.3|      7331.6|      724.3|        724.3|      1337|       1338|       p|            r|

=================== Expected Output Table ==================
=== Columns
|   l_int|l_int_null| l_float|l_float_null|l_double|l_double_null|  l_long|l_long_null|l_string|l_string_null|
|     int|       int|   float|       float|  double|       double|    long|       long|  string|       string|
|not null|      null|not null|        null|not null|         null|not null|       null|not null|         null|

======================== Difference ========================
===================== Tables are not equal =====================
------------------------- Actual Result ------------------------
       l_int l_int_null  l_float l_float_null l_double l_double_null   l_long l_long_null l_string l_string_null 
         int      int    float    float   double   double     long     long   string   string 
    NOT NULL     NULL NOT NULL     NULL NOT NULL     NULL NOT NULL     NULL NOT NULL     NULL 
   0     724     7331     1337   1337.2 4.29497e+09     NULL     7331      724        r     NULL 
   1    1337      724    724.3   7331.6    724.3    724.3     1337     1338        p        r 
   2    1337     7331     1338     NULL   1337.7     NULL     1337     7331        p        o 
   3    1338     NULL     1337     NULL     1337   1337.7      724     NULL        d     NULL 
   4    1338     7331     1338    724.3     1338   1337.2     7331 4294968633        m        m 
   5    7331     NULL   1337.2     NULL   1337.2 4.29497e+09     1337     1337        p        d 
   6    7331     NULL   1337.7     1338    724.3     NULL 4294968633     1338        a        a 
----------------------------------------------------------------

------------------------ Expected Result -----------------------
       l_int l_int_null  l_float l_float_null l_double l_double_null   l_long l_long_null l_string l_string_null 
         int      int    float    float   double   double     long     long   string   string 
    NOT NULL     NULL NOT NULL     NULL NOT NULL     NULL NOT NULL     NULL NOT NULL     NULL 
----------------------------------------------------------------
Type of error: Row count mismatch
================================================================

Actual number of rows: 7
Expected number of rows: 0
```

File: src/lib/operators/join_index.cpp [hunk 13]
```diff
@@ -339,6 +339,15 @@ std::vector<IndexRange> JoinIndex::_index_ranges_for_value(const SegmentPosition
   std::vector<IndexRange> index_ranges{};
   index_ranges.reserve(2);
 
+  if (_mode == JoinMode::AntiNullAsTrue) {
```
Comment (mrks) [inline src/lib/operators/join_index.cpp:342]: doc?

File: src/test/operators/join_index_test.cpp [hunk 14]
```diff
@@ -121,345 +114,119 @@ class JoinIndexTest : public BaseTest {
...
-}
+  performance_data.executed = true;
+  performance_data.has_output = true;
+  performance_data.output_row_count = 2u;
+  performance_data.output_chunk_count = 1u;
+  performance_data.walltime = std::chrono::nanoseconds{999u};
+  performance_data.chunks_scanned_with_index = 10u;
+  performance_data.chunks_scanned_without_index = 5u;
+  stream << performance_data;
+  EXPECT_EQ(stream.str(), "2 row(s) in 1 chunk(s), 999 ns / 10 of 15 chunks used an index");
```
Comment (mrks) [inline src/test/operators/join_index_test.cpp:206]: chunks don't really "use" an index. Maybe "indexes used for 10 of 15 chunk(s)"?

Also, we should use either `,` or `/` as the separator, not both.

File: src/test/operators/join_index_test.cpp [hunk 15]
```diff
@@ -121,345 +114,119 @@ class JoinIndexTest : public BaseTest {
...
 
-TYPED_TEST(JoinIndexTest, JoinLessThanOnDictAndDict) {
-  this->test_join_output(this->_table_wrapper_a, this->_table_wrapper_b,
-                         {{ColumnID{0}, ColumnID{0}}, PredicateCondition::LessThanEquals}, JoinMode::Inner,
-                         "resources/test_data/tbl/join_operators/int_float_leq_dict.tbl", 1);
+  stream.str("");
+  performance_data.output_to_stream(stream, DescriptionMode::MultiLine);
+  EXPECT_EQ(stream.str(), "2 row(s) in 1 chunk(s), 999 ns\n10 of 15 chunks used an index");
```
Comment (mrks) [inline src/test/operators/join_index_test.cpp:210]: (Really minor:) Not a fan of reusing variable names. You could add a scope for the two tests.

File: src/test/operators/join_test_runner.cpp [hunk 16]
```diff
@@ -184,16 +195,65 @@ class JoinTestRunner : public BaseTestWithParam<JoinTestConfiguration> {
     };
     // clang-format on
 
-    const auto add_configuration_if_supported = [&](const auto& configuration) {
-      // String vs non-String comparisons are not supported in Hyrise and therefore cannot be tested
-      if ((configuration.data_type_left == DataType::String) != (configuration.data_type_right == DataType::String)) {
-        return;
+    /**
+     * Returns a set of adapted configurations if the join type provides further configuration possibilities
+     * which should be tested.
```
Comment (mrks) [inline src/test/operators/join_test_runner.cpp:200]: that

File: src/test/operators/join_test_runner.cpp [hunk 17]
```diff
@@ -184,16 +195,65 @@ class JoinTestRunner : public BaseTestWithParam<JoinTestConfiguration> {
...
+        // Currently the Index Join cannot deal with configurations where the join column
+        // data types are different, see Issue #2077
+        if (configuration.data_type_left != configuration.data_type_right) {
+          return std::vector<JoinTestConfiguration>{};
+        }
+
+        // For the JoinIndex, two additional parameters influence its execution behavior.
+        // These are the index side and the availability of indexes on that index side.
+        // Based on the input configuration, two configurations are generated for each possible
+        // index side: configurations (1) with and (2) without indexes on the index side.
```
Comment (mrks) [inline src/test/operators/join_test_runner.cpp:214]: Executing JoinIndex without indexes seems pointless. I'd be more interested in a configuration where the majority of the chunks are indexed, but one chunk is not.

File: src/test/operators/join_test_runner.cpp [hunk 18]
```diff
@@ -479,6 +539,24 @@ class JoinTestRunner : public BaseTestWithParam<JoinTestConfiguration> {
         table = reference_table;
       }
 
+      /**
+       * To sufficiently test IndexJoins, indexes have to be created. Therefore, if index_side is set in the configuration,
+       * indexes for the table are created. The index type is either GroupKeyIndex for dictionary segments or BTreeIndex
+       * for non-disctionary segments.
```
Comment (mrks) [inline src/test/operators/join_test_runner.cpp:545]: typo

Comment (mrks) [inline src/test/operators/join_test_runner.cpp:545]: typo

File: src/test/operators/join_test_runner.cpp [hunk 19]
```diff
@@ -479,6 +539,24 @@ class JoinTestRunner : public BaseTestWithParam<JoinTestConfiguration> {
...
+       */
+      if (has_indexes) {
+        // If the table to index is a referenced table, this table is not
+        // (dictionary) encoded in Join Test Runner scenarios
```
Comment (mrks) [inline src/test/operators/join_test_runner.cpp:549]: line wrapping

File: src/test/operators/join_test_runner.cpp [hunk 20]
```diff
@@ -580,6 +660,49 @@ TEST_P(JoinTestRunner, TestJoin) {
...
+
+  if (configuration.index_side) {  // configuration is a specialized JoinIndex configuration
+    std::shared_ptr<const Table> index_table = nullptr;
+    if (configuration.index_side == IndexSide::Left) {
+      index_table = join_op->input_table_left();
+    } else {
+      index_table = join_op->input_table_right();
+    }
+
+    // count how many chunks had to be scanned with index
```
Comment (mrks) [inline src/test/operators/join_test_runner.cpp:672]: Shouldn't it be possible to determine that number from the test parameters?

File: src/test/operators/operator_performance_data_test.cpp [hunk 21]
```diff
@@ -0,0 +1,34 @@
...
+ public:
+  void SetUp() override {}
+};
+
+TEST_F(OperatorsOperatorPerformanceDataTest, OutputToStream) {
+  auto performance_data = OperatorPerformanceData{};
+  std::stringstream stream;
+
+  stream << performance_data;
+  EXPECT_EQ(stream.str(), "not executed");
```
Comment (mrks) [inline src/test/operators/operator_performance_data_test.cpp:18]: See above. I'd prefer
```
{
  std::stringstream stream;
  stream << performance_data;
  EXPECT_EQ(stream.str(), "not executed");
}

{
  ...
}
```

File: src/lib/operators/join_index.cpp [hunk 22]
```diff
@@ -467,16 +487,30 @@ void JoinIndex::_append_matches_non_inner(const bool is_semi_or_anti_join) {
...
+      const auto chunk_count = _index_input_table->chunk_count();
+      for (ChunkID chunk_id{0}; chunk_id < chunk_count; ++chunk_id) {
+        const auto chunk = _index_input_table->get_chunk(chunk_id);
+        Assert(chunk, "Physically deleted chunk should not reach this point, see get_chunk / #1686.");
+
+        const auto chunk_size = chunk->size();
+        for (ChunkOffset chunk_offset{0}; chunk_offset < chunk_size; ++chunk_offset) {
+          if (_index_matches[chunk_id][chunk_offset] ^ invert) {
+            _index_pos_list->emplace_back(RowID{chunk_id, chunk_offset});
+          }
```
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/operators/join_index.cpp]: Not sure if I understand the change correctly. I would have expected a new assertion `_index_side == IndexSide::Right` somewhere.

File: src/lib/operators/join_index.cpp [hunk 23]
```diff
@@ -37,9 +37,16 @@ bool JoinIndex::supports(const JoinConfiguration config) {
...
+    } else if (config.secondary_predicates) {
+      return false;  // multi predicate index joins are not supported
     } else {
-      return !config.secondary_predicates;
+      const auto is_semi_or_anti_join = config.join_mode == JoinMode::Semi ||
+                                        config.join_mode == JoinMode::AntiNullAsFalse ||
+                                        config.join_mode == JoinMode::AntiNullAsTrue;
+      // if a Semi or Anti* join is executed, the left side is outputted by definition. Choosing the index join when
+      // indexes are not available for the right table would not be beneficial.
+      return !(is_semi_or_anti_join && config.index_side == IndexSide::Left);
```
Comment (mweisgut) [inline src/lib/operators/join_index.cpp:49]: @mrks here we do not support the configuration that you mentioned: if we don't have indexes for the right table chunks but a Semi or Anti* join, why should we choose the index join? I would expect the optimizer to choose a different join operator in that case since we cannot benefit from the indexed position lookups.

File: src/lib/operators/join_index.cpp (hunk 22 above)
[the remark this answers is not in the document]
Comment (mweisgut) [reply src/lib/operators/join_index.cpp]: The index joins does not support the configuration "(Semi || Anti*) && index side is Left" anymore. Therefore, at your referenced core section, if we have a Semi or Anti* join, the index side is always `Right`.

File: src/test/operators/join_test_runner.cpp [hunk 24]
```diff
@@ -207,19 +219,34 @@ class JoinTestRunner : public BaseTestWithParam<JoinTestConfiguration> {
...
+        // chunks are not indexed.
+        std::vector<ChunkPosList> missing_index_lists{
+            // no missing indexes
+            ChunkPosList{},
+            // an index for the first segment is missing
+            ChunkPosList{ChunkPosition::First},
+            // an index for a segment that is not the first or last one is missing
+            ChunkPosList{ChunkPosition::Inner},
+            // an index for the last segment is missing
+            ChunkPosList{ChunkPosition::Last}};
```
Comment (mweisgut) [inline src/test/operators/join_test_runner.cpp:232]: Having four different options here increases the number of test cases a lot. We have almost 4000 join index test cases now. To address https://github.com/hyrise/hyrise/pull/1851#discussion_r409575868, we also need an additional configuration parameter for "single chunk reference guarantee". This is important when it comes to calculating the number of used indexes: If the indexed table is a reference table, we currently only use an index for a segment if the join mode is `Inner` and the reference segment's PosList references a single chunk. Currently, the join test runner does not create scenarios with indexed reference tables that have segments with this "single chunk reference guarantee".

Comment (mrks) [reply src/test/operators/join_test_runner.cpp:232]: Is there anything in the code where the handling for the first or last index missing is different? If not, I'd say that given the chunk-based nature of the approach, a single configuration with `0% < x < 100%` chunks not being indexed should be sufficient.

Regarding the single chunk PosList - can't we make the reference table contain both a single and a multi chunk PosList?

File: src/test/operators/join_test_runner.cpp (hunk 20 above)
Comment (mweisgut) [reply src/test/operators/join_test_runner.cpp]: We now provide two different shares of indexed segments: 100% and 10%. cdf931d3370b0c4855cb5173e6616537d6ac18d0

File: src/test/operators/join_test_runner.cpp (hunk 24 above)
Comment (mweisgut) [reply src/test/operators/join_test_runner.cpp]: Now two different shares of indexed segments are provided: 100% and 10%. The indexed segments are at the beginning of the column. cdf931d3370b0c4855cb5173e6616537d6ac18d0

File: src/test/operators/join_test_runner.cpp (hunk 20 above)
Comment (mweisgut) [reply src/test/operators/join_test_runner.cpp]: I agree. Therefore, `indexed_chunk_count` was added to an `InputTableConfiguration` in a0a199f37952b8a4e0e3680887651d0a31585618

**Comment by mrks** [comment]
Weird, haven't seen this one before which looks like no Hyrise code has yet been executed:

```

==45312== Conditional jump or move depends on uninitialised value(s)
==45312==    at 0xA7562F8: __vfprintf_internal (vfprintf-internal.c:1687)
==45312==    by 0xA76A029: __vsnprintf_internal (vsnprintf.c:114)
==45312==    by 0xA73FED5: snprintf (snprintf.c:31)
==45312==    by 0x2004A2D: testing::internal2::PrintBytesInObjectTo(unsigned char const*, unsigned long, std::ostream*) (in /var/lib/jenkins/workspace/hyrise_hyrise_PR-1851/clang-release/hyriseTest)
==45312==    by 0x11582BA: testing::internal::ParameterizedTestSuiteInfo<opossum::JoinTestRunner>::RegisterTests() (in /var/lib/jenkins/workspace/hyrise_hyrise_PR-1851/clang-release/hyriseTest)
==45312==    by 0x1FF6CE8: testing::internal::UnitTestImpl::PostFlagParsingInit() (in /var/lib/jenkins/workspace/hyrise_hyrise_PR-1851/clang-release/hyriseTest)
==45312==    by 0x200BAB9: void testing::internal::InitGoogleTestImpl<char>(int*, char**) (in /var/lib/jenkins/workspace/hyrise_hyrise_PR-1851/clang-release/hyriseTest)
==45312==    by 0xCF6280: main (in /var/lib/jenkins/workspace/hyrise_hyrise_PR-1851/clang-release/hyriseTest)
==45312== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:__vfprintf_internal
   fun:__vsnprintf_internal
   fun:snprintf
   fun:_ZN7testing9internal220PrintBytesInObjectToEPKhmPSo
   fun:_ZN7testing8internal26ParameterizedTestSuiteInfoIN7opossum14JoinTestRunnerEE13RegisterTestsEv
   fun:_ZN7testing8internal12UnitTestImpl19PostFlagParsingInitEv
   fun:_ZN7testing8internal18InitGoogleTestImplIcEEvPiPPT_
   fun:main
}
==45312== Conditional jump or move depends on uninitialised value(s)
==45312==    at 0xA7557BE: __vfprintf_internal (vfprintf-internal.c:1687)
==45312==    by 0xA76A029: __vsnprintf_internal (vsnprintf.c:114)
==45312==    by 0xA73FED5: snprintf (snprintf.c:31)
==45312==    by 0x2004A2D: testing::internal2::PrintBytesInObjectTo(unsigned char const*, unsigned long, std::ostream*) (in /var/lib/jenkins/workspace/hyrise_hyrise_PR-1851/clang-release/hyriseTest)
==45312==    by 0x11582BA: testing::internal::ParameterizedTestSuiteInfo<opossum::JoinTestRunner>::RegisterTests() (in /var/lib/jenkins/workspace/hyrise_hyrise_PR-1851/clang-release/hyriseTest)
==45312==    by 0x1FF6CE8: testing::internal::UnitTestImpl::PostFlagParsingInit() (in /var/lib/jenkins/workspace/hyrise_hyrise_PR-1851/clang-release/hyriseTest)
==45312==    by 0x200BAB9: void testing::internal::InitGoogleTestImpl<char>(int*, char**) (in /var/lib/jenkins/workspace/hyrise_hyrise_PR-1851/clang-release/hyriseTest)
==45312==    by 0xCF6280: main (in /var/lib/jenkins/workspace/hyrise_hyrise_PR-1851/clang-release/hyriseTest)
==45312== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:__vfprintf_internal
   fun:__vsnprintf_internal
   fun:snprintf
   fun:_ZN7testing9internal220PrintBytesInObjectToEPKhmPSo
   fun:_ZN7testing8internal26ParameterizedTestSuiteInfoIN7opossum14JoinTestRunnerEE13RegisterTestsEv
   fun:_ZN7testing8internal12UnitTestImpl19PostFlagParsingInitEv
   fun:_ZN7testing8internal18InitGoogleTestImplIcEEvPiPPT_
   fun:main
}
```

Re-running CI now.

**Comment by mrks** [comment]
Could you merge the master, please? Hopefully that fixes the server test.

**Comment by mrks** [comment]
About the memcheck thing: Maybe try initializing `std::optional<IndexSide> index_side{std::nullopt};` with something other than nullopt? That might be related, as nullopt does not set the unused bytes.

**Comment by mweisgut** [comment]
> About the memcheck thing: Maybe try initializing `std::optional<IndexSide> index_side{std::nullopt};` with something other than nullopt? That might be related, as nullopt does not set the unused bytes.

**Comment by mweisgut** [comment]
closed by accident

**Comment by mrks** [comment]
Restarted the Jenkins job. No idea why this appeared:

> Notifies GitHub of the status of a Pull Request
The supplied credentials are invalid to login

The fact that it took 30s suggests that it actually was a timeout thing.

**Comment by mrks** [comment]
For a test, you could try adding `IndexSide::None` and removing the optional.

**Comment by mweisgut** [comment]
> For a test, you could try adding `IndexSide::None` and removing the optional.

I will try soon after the CI finished the current run but `std::optional<size_t> radix_bits;` with nullopt initialization seems to work fine, so I don't understand why `std::optional<IndexSide> index_side;` shouldn't.

File: src/test/operators/join_test_runner.cpp [hunk 25]
```diff
@@ -417,38 +507,42 @@ class JoinTestRunner : public BaseTestWithParam<JoinTestConfiguration> {
...
+        ChunkEncoder::encode_all_chunks(data_table, chunk_encoding_spec);
       }
 
       /**
-       * Create a Reference-Table pointing 1-to-1 and in-order to the rows in the original table. This tests the
+       * Create a Reference-Table pointing 1-to-1 and in-order to the rows in the original data table. This tests the
        * writing of the output table in the JoinOperator, which has to make sure not to create ReferenceSegments
-       * pointing to ReferenceSegments.
+       * pointing to ReferenceSegments. In addition, special index join executions are tested. The first
+       * 0.5 * indexed_chunk_count segments provide the guarantee referencing only a single chunk.
```
Comment (mrks) [inline src/test/operators/join_test_runner.cpp:537]: At least in Github, I can't find the 0,5.

File: src/test/operators/join_test_runner.cpp [hunk 26]
```diff
@@ -180,20 +197,92 @@ class JoinTestRunner : public BaseTestWithParam<JoinTestConfiguration> {
...
+          }
+
+          for (const auto indexed_chunk_count : indexed_chunk_counts) {
+            auto variation = configuration;
+            auto& variation_indexed_input =
+                index_side == IndexSide::Left ? variation.input_left : variation.input_right;
+            variation.index_side = index_side;
+            variation_indexed_input.indexed_chunk_count = indexed_chunk_count;
+
+            if (variation_indexed_input.table_type != InputTableType::Data && variation.join_mode == JoinMode::Inner) {
```
Comment (mrks) [inline src/test/operators/join_test_runner.cpp:245]: minor: Why not `== InputTableType::Reference`?

File: src/test/operators/join_test_runner.cpp [hunk 27]
```diff
@@ -180,20 +197,92 @@ class JoinTestRunner : public BaseTestWithParam<JoinTestConfiguration> {
...
+              variation_indexed_input.single_chunk_reference_count = indexed_chunk_count;
```
Comment (mrks) [inline src/test/operators/join_test_runner.cpp:246]: Do we want to guarantee this for each chunk?

File: src/test/operators/join_test_runner.cpp [hunk 28]
```diff
@@ -180,20 +197,92 @@ class JoinTestRunner : public BaseTestWithParam<JoinTestConfiguration> {
...
+          return std::vector<JoinTestConfiguration>{};
+        }
+
+        // For the JoinIndex, additional parameters influence its execution behavior:
+        //  - index side (left or right)
+        //  - availability of an index for a join column segment
+        //  - presence of "single chunk reference guarantee" for join column reference segments
+
+        // share of indexed segments; 1 means all segments are indexed
+        std::array<float, 2> indexed_segment_shares{1.0f, .1f};
```
Comment (mrks) [inline src/test/operators/join_test_runner.cpp:223]: is .1f meaningful for most configurations (i.e., do most configs have at least 10 chunks)?

File: src/lib/operators/join_index.cpp [hunk 29]
```diff
@@ -398,22 +420,30 @@ void JoinIndex::_append_matches(const AbstractIndex::Iterator& range_begin, cons
     return;
   }
 
-  // Remember the matches for outer joins
-  if ((_mode == JoinMode::Left && _index_side == IndexSide::Right) ||
+  const auto is_semi_or_anti_join =
+      _mode == JoinMode::Semi || _mode == JoinMode::AntiNullAsFalse || _mode == JoinMode::AntiNullAsTrue;
+
```
Comment (mrks) [inline src/lib/operators/join_index.cpp:425]: `if (is_semi_or_anti_join) Assert(_index_side == IndexSide::Right, "...");`?

File: src/test/operators/join_test_runner.cpp (hunk 26 above)
Comment (mweisgut) [reply src/test/operators/join_test_runner.cpp:245]: Because we only have ´InputTableType::Data´, ´InputTableType::SharedPosList´, ´InputTableType::IndividualPosLists´ as possible values. The latter two are reference types.

File: src/test/operators/join_test_runner.cpp (hunk 27 above)
Comment (mweisgut) [reply src/test/operators/join_test_runner.cpp:246]: The idea was to have this guarantee for each indexed chunk and for an additional (non-indexed) one if the number of non-indexed segments is greater than 1. Therefore we cover (a) and (b) of the following execution branches:
  - (a) ref. segment with single chunk reference guarantee, indexed
  - (b) ref. segment with single chunk reference guarantee, not indexed (fallback nested loop)
  - (c) ref. segment with no single chunk reference guarantee (fallback nested loop)

But yes, (c) is not covered which might be your concern here? How about defining a range for segments with this guarantee that starts at a position larger than 0 and ends at a position larger than the last indexed segment? Let's say the first segment never provides this guarantee but all other indexed segments and an additional non-indexed do?

Example:
- segment 0, no guarantee, indexed --> covers (c)
- segment 1, guarantee, indexed --> covers (a)
- segment 2, guarantee, not indexed --> covers (b)
- segment 3, no guarantee, not indexed --> covers (c)

File: src/test/operators/join_test_runner.cpp (hunk 28 above)
Comment (mweisgut) [reply src/test/operators/join_test_runner.cpp:223]: Could be improved with `std::ceil`?

Before:
`indexed_chunk_count = static_cast<uint32_t>(indexed_share * chunk_count);`

After:
`indexed_chunk_count = static_cast<uint32_t>(std::ceil(indexed_share * chunk_count))`

Whith this extension, we have at least one indexed segment.

Comment (mrks) [reply src/test/operators/join_test_runner.cpp:223]: Sounds good! Add a check that this is not the same as chunk_count, otherwise skip it?

File: src/test/operators/join_test_runner.cpp (hunk 27 above)
Comment (mrks) [reply src/test/operators/join_test_runner.cpp:246]: Sounds good. :)

File: src/test/operators/join_test_runner.cpp (hunk 26 above)
Comment (mrks) [reply src/test/operators/join_test_runner.cpp:245]: Ah, I mistook InputTableType with TableType, sorry.

**Comment by mweisgut** [comment]
>For a test, you could try adding IndexSide::None and removing the optional.

Memcheck issue is still present, even without the ´std::nullopt´

**Comment by mrks** [comment]
I just googled `memcheck _ZN7testing9internal220PrintBytesInObjectToEPKhmPSo`.

[Chromium](https://1252-00bb8fd8c843-dot-chromiumcodereview-hr.appspot.com/2991643002/) and [zfs](https://reviews.freebsd.org/D6564) have the same issue, too. At this point, just suppress it.

**Comment by mweisgut** [comment]
> I just googled `memcheck _ZN7testing9internal220PrintBytesInObjectToEPKhmPSo`.
> 
> [Chromium](https://1252-00bb8fd8c843-dot-chromiumcodereview-hr.appspot.com/2991643002/) and [zfs](https://reviews.freebsd.org/D6564) have the same issue, too. At this point, just suppress it.

Just for documentation purposes, another (chromium reference)[https://bugs.chromium.org/p/chromium/issues/detail?id=263315] of this issue.

File: src/test/operators/join_test_runner.cpp (hunk 28 above)
Comment (mweisgut) [reply src/test/operators/join_test_runner.cpp:226]: In the current implementation, we add the calculated `indexed_chunk_range` for each `indexed_share` to a set of `ChunkRange`s. If the calculated range for share `.1f` would cover all segments, it wouldn't be a problem here since we also have `1.0f`, i.e., we want to have the test case in which all segments are indexed. Since a set is used for storing the ranges, we don't have duplicates of `ChunkRange`s.

```
auto indexed_chunk_ranges = std::set<ChunkRange>{};
for (const auto indexed_share : indexed_segment_shares) {
            indexed_chunk_ranges.insert(ChunkRange{0, static_cast<uint32_t>(std::ceil(indexed_share * chunk_count))});
          }

          for (const auto& indexed_chunk_range : indexed_chunk_ranges) {
             [...]
```

**Comment by mrks** [comment]
nice :)
