### PR TITLE
benchmark_all script

### LINKED ISSUE #1963: Create benchmark_all script
#1958 had a performance regression for TPC-DS which was not caught because I was too lazy to run both benchmarks. For as long as we don't have benchmarks as part of our CI (read: forever), I'd like a script that can be used to run all relevant benchmarks for a PR:

`../scripts/run_all_benchmarks.py <old git rev selector> <new git rev selector>`

The json files of the different benchmarks should appear in the current directory and a comparison should be printed. As a bonus, we might consider printing a summary of the notable changes (those that are colored) and collapsed details:

https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab

### PR DESCRIPTION
**Pull request by mrks**
- [x] Include #2091 
- [ ] Include TPCH SF 0.1

Introduces a script that compares the performance of two Git references. fixes #1963 

Depending on what gets done first, we can add the sum of all items (#2091) in this PR or over there. That's the TODO that you will see below.

Example output for the commit that introduced the poor-man's bloom filter, called as 
`../scripts/benchmark_all.sh a15e3d6^ a15e3d6`:

----------------------------------

**System**
<details>
<summary>nemea - click to expand</summary>

| property | value |
| -- | -- |
| Hostname | nemea |
| CPU | Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz |
| Memory | 1.4TB |
| numactl nodebind | nodebind: 0  |
| numactl nodebind | membind: 0  |
</details>

**Build Time**
| commit | build time |
| -- | -- |
| f14e215994744bd4d7aa8007c596b57847c11815 |real 217.46 user 2586.86 sys 156.13|
| a15e3d668b8ee9bdcf5c7e97fa74ce74a26da7e5 |real 217.23 user 2582.04 sys 152.88|

**hyriseBenchmarkTPCH - single-threaded**
<details>
<summary>
Sum of average per-item runtime: TODO,
Geometric Mean: +39%
</summary>

```diff
 +----------------+--------------------+------+--------------------+------+------------+----------------------+
 | Benchmark      | prev. iter/s       | runs | new iter/s         | runs | change [%] |              p-value |
 +----------------+--------------------+------+--------------------+------+------------+----------------------+
 | TPC-H 01       | 1.2048733234405518 | 13   | 1.2412058115005493 | 13   | +3%        | (run time too short) |
+| TPC-H 02       | 49.38113784790039  | 494  | 89.8923110961914   | 899  | +82%       | (run time too short) |
+| TPC-H 03       | 8.928854942321777  | 90   | 11.384787559509277 | 114  | +28%       | (run time too short) |
+| TPC-H 04       | 7.971709728240967  | 80   | 14.059837341308594 | 141  | +76%       | (run time too short) |
+| TPC-H 05       | 4.1957688331604    | 42   | 4.479614734649658  | 45   | +7%        | (run time too short) |
 | TPC-H 06       | 285.8074035644531  | 2859 | 272.74432373046875 | 2728 | -5%        | (run time too short) |
+| TPC-H 07       | 8.47539234161377   | 85   | 12.882302284240723 | 129  | +52%       | (run time too short) |
+| TPC-H 08       | 6.8916425704956055 | 70   | 14.885615348815918 | 149  | +116%      | (run time too short) |
+| TPC-H 09       | 1.696704387664795  | 17   | 1.9024797677993774 | 20   | +12%       | (run time too short) |
+| TPC-H 10       | 3.268155813217163  | 33   | 3.571420431137085  | 36   | +9%        | (run time too short) |
+| TPC-H 11       | 40.04581832885742  | 401  | 115.32002258300781 | 1154 | +188%      | (run time too short) |
+| TPC-H 12       | 16.450387954711914 | 165  | 21.152437210083008 | 212  | +29%       | (run time too short) |
 | TPC-H 13       | 2.7499239444732666 | 28   | 2.7923617362976074 | 28   | +2%        | (run time too short) |
 | TPC-H 14       | 44.36190414428711  | 444  | 46.288570404052734 | 463  | +4%        | (run time too short) |
 | TPC-H 15       | 115.37980651855469 | 1154 | 118.58972930908203 | 1186 | +3%        | (run time too short) |
 | TPC-H 16       | 9.967753410339355  | 100  | 10.04690933227539  | 101  | +1%        | (run time too short) |
+| TPC-H 17       | 5.553668975830078  | 56   | 26.671323776245117 | 267  | +380%      | (run time too short) |
 | TPC-H 18       | 1.3788436651229858 | 14   | 1.4441574811935425 | 15   | +5%        | (run time too short) |
+| TPC-H 19       | 7.778407573699951  | 78   | 15.269028663635254 | 153  | +96%       | (run time too short) |
+| TPC-H 20       | 32.577579498291016 | 326  | 55.253944396972656 | 553  | +70%       | (run time too short) |
+| TPC-H 21       | 1.3958383798599243 | 14   | 1.7105176448822021 | 18   | +23%       | (run time too short) |
 | TPC-H 22       | 18.773115158081055 | 188  | 18.185161590576172 | 182  | -3%        | (run time too short) |
+| geometric mean |                    |      |                    |      | +39%       |                      |
 +----------------+--------------------+------+--------------------+------+------------+----------------------+
```
</details>

**hyriseBenchmarkTPCH - multi-threaded (50 clients)**
<details>
<summary>
Sum of average per-item runtime: TODO,
Geometric Mean: +34%
</summary>

```diff
 +----------------+--------------------+-------+--------------------+-------+------------+---------+
 | Benchmark      | prev. iter/s       | runs  | new iter/s         | runs  | change [%] | p-value |
 +----------------+--------------------+-------+--------------------+-------+------------+---------+
-| TPC-H 01       | 9.195795059204102  | 92    | 8.499185562133789  | 85    | -8%        |  0.8962 |
+| TPC-H 02       | 702.8336181640625  | 7033  | 1544.321044921875  | 15452 | +120%      |  0.0000 |
+| TPC-H 03       | 49.07808303833008  | 491   | 66.56806945800781  | 666   | +36%       |  0.0000 |
+| TPC-H 04       | 70.27102661132812  | 703   | 123.662841796875   | 1237  | +76%       |  0.0000 |
+| TPC-H 05       | 20.38298797607422  | 204   | 22.67823028564453  | 227   | +11%       |  0.5839 |
-| TPC-H 06       | 1381.2235107421875 | 13815 | 1226.6002197265625 | 12278 | -11%       |  0.0000 |
+| TPC-H 07       | 78.0540542602539   | 781   | 124.10938262939453 | 1242  | +59%       |  0.0000 |
+| TPC-H 08       | 68.06844329833984  | 681   | 124.48457336425781 | 1246  | +83%       |  0.0000 |
+| TPC-H 09       | 9.198715209960938  | 92    | 9.692984580993652  | 97    | +5%        |  0.9197 |
 | TPC-H 10       | 19.281312942504883 | 193   | 18.585979461669922 | 186   | -4%        |  0.6548 |
+| TPC-H 11       | 260.9160461425781  | 2611  | 492.2288513183594  | 4924  | +89%       |  0.0000 |
+| TPC-H 12       | 179.5786590576172  | 1796  | 244.37887573242188 | 2445  | +36%       |  0.0000 |
-| TPC-H 13       | 13.699187278747559 | 137   | 12.092103004455566 | 121   | -12%       |  0.1376 |
-| TPC-H 14       | 271.5982971191406  | 2718  | 240.15988159179688 | 2404  | -12%       |  0.0000 |
-| TPC-H 15       | 625.6376342773438  | 6261  | 575.8467407226562  | 5763  | -8%        |  0.0000 |
 | TPC-H 16       | 79.92158508300781  | 800   | 78.24249267578125  | 783   | -2%        |  0.7131 |
+| TPC-H 17       | 47.05849075317383  | 471   | 197.23377990722656 | 1974  | +319%      |  0.0000 |
-| TPC-H 18       | 2.2979235649108887 | 23    | 2.099320888519287  | 21    | -9%        |  0.0019 |
+| TPC-H 19       | 73.92677307128906  | 740   | 188.70681762695312 | 1888  | +155%      |  0.0000 |
+| TPC-H 20       | 242.7777557373047  | 2429  | 533.5027465820312  | 5338  | +120%      |  0.0000 |
+| TPC-H 21       | 5.594910144805908  | 56    | 6.992980003356934  | 70    | +25%       |  0.3470 |
-| TPC-H 22       | 52.05335235595703  | 521   | 48.08906555175781  | 481   | -8%        |  0.6512 |
+| geometric mean |                    |       |                    |       | +34%       |         |
 +----------------+--------------------+-------+--------------------+-------+------------+---------+
```
</details>

**hyriseBenchmarkTPCDS - single-threaded**
<details>
<summary>
Sum of average per-item runtime: TODO,
Geometric Mean: +52%
</summary>

```diff
 +----------------+--------------------+------+--------------------+------+------------+----------------------+
 | Benchmark      | prev. iter/s       | runs | new iter/s         | runs | change [%] |              p-value |
 +----------------+--------------------+------+--------------------+------+------------+----------------------+
+| 01             | 28.54338836669922  | 286  | 30.0107479095459   | 301  | +5%        | (run time too short) |
+| 03             | 28.079484939575195 | 281  | 151.78753662109375 | 1518 | +441%      | (run time too short) |
+| 06             | 29.80824851989746  | 299  | 49.79105758666992  | 498  | +67%       | (run time too short) |
+| 07             | 14.7157564163208   | 148  | 17.45510482788086  | 175  | +19%       | (run time too short) |
-| 09             | 9.359025955200195  | 94   | 8.863388061523438  | 89   | -5%        | (run time too short) |
+| 10             | 17.845949172973633 | 179  | 50.790855407714844 | 508  | +185%      | (run time too short) |
-| 13             | 7.140738487243652  | 72   | 6.625092506408691  | 67   | -7%        | (run time too short) |
+| 15             | 54.518619537353516 | 546  | 77.44190979003906  | 775  | +42%       | (run time too short) |
+| 17             | 18.314632415771484 | 184  | 32.19193649291992  | 322  | +76%       | (run time too short) |
+| 19             | 39.43385696411133  | 395  | 88.76908111572266  | 888  | +125%      | (run time too short) |
+| 25             | 25.583600997924805 | 256  | 54.68630599975586  | 547  | +114%      | (run time too short) |
+| 26             | 30.008176803588867 | 301  | 34.32243728637695  | 344  | +14%       | (run time too short) |
-| 28             | 10.671170234680176 | 107  | 9.933248519897461  | 100  | -7%        | (run time too short) |
+| 29             | 18.6044979095459   | 187  | 32.08706283569336  | 321  | +72%       | (run time too short) |
+| 31             | 5.6047773361206055 | 57   | 7.624622344970703  | 77   | +36%       | (run time too short) |
+| 34             | 26.576793670654297 | 266  | 40.12943649291992  | 402  | +51%       | (run time too short) |
+| 35             | 7.02392053604126   | 71   | 9.947848320007324  | 100  | +42%       | (run time too short) |
+| 39a            | 2.993875741958618  | 30   | 4.728511810302734  | 48   | +58%       | (run time too short) |
+| 39b            | 3.2259209156036377 | 33   | 4.777234077453613  | 48   | +48%       | (run time too short) |
 | 41             | 38.72869873046875  | 388  | 37.82381057739258  | 379  | -2%        | (run time too short) |
+| 42             | 49.235450744628906 | 493  | 132.21824645996094 | 1323 | +169%      | (run time too short) |
 | 43             | 3.866744041442871  | 39   | 4.004608631134033  | 41   | +4%        | (run time too short) |
+| 45             | 54.70286178588867  | 548  | 83.22296905517578  | 833  | +52%       | (run time too short) |
+| 48             | 7.796730041503906  | 78   | 8.420939445495605  | 85   | +8%        | (run time too short) |
+| 50             | 34.69765090942383  | 347  | 80.9028091430664   | 810  | +133%      | (run time too short) |
+| 52             | 49.171085357666016 | 492  | 130.05592346191406 | 1301 | +164%      | (run time too short) |
+| 55             | 49.7746467590332   | 498  | 132.04847717285156 | 1321 | +165%      | (run time too short) |
 | 62             | 12.285978317260742 | 123  | 12.75119400024414  | 128  | +4%        | (run time too short) |
+| 65             | 11.99399185180664  | 120  | 13.480032920837402 | 135  | +12%       | (run time too short) |
+| 69             | 15.303696632385254 | 154  | 38.68205261230469  | 387  | +153%      | (run time too short) |
+| 73             | 32.52635955810547  | 326  | 56.338905334472656 | 564  | +73%       | (run time too short) |
+| 79             | 14.884858131408691 | 149  | 18.899417877197266 | 189  | +27%       | (run time too short) |
+| 81             | 45.63010025024414  | 457  | 50.34293746948242  | 504  | +10%       | (run time too short) |
+| 83             | 49.071353912353516 | 491  | 101.51397705078125 | 1016 | +107%      | (run time too short) |
+| 85             | 10.234930038452148 | 103  | 12.918397903442383 | 130  | +26%       | (run time too short) |
+| 88             | 5.118659019470215  | 52   | 10.135051727294922 | 102  | +98%       | (run time too short) |
+| 91             | 43.729305267333984 | 438  | 46.23649215698242  | 463  | +6%        | (run time too short) |
 | 93             | 3.6388540267944336 | 37   | 3.735135078430176  | 38   | +3%        | (run time too short) |
+| 96             | 47.68337631225586  | 477  | 106.90794372558594 | 1070 | +124%      | (run time too short) |
+| 97             | 2.3739373683929443 | 24   | 2.515254020690918  | 26   | +6%        | (run time too short) |
 | 99             | 6.093935966491699  | 61   | 6.345204830169678  | 64   | +4%        | (run time too short) |
+| geometric mean |                    |      |                    |      | +52%       |                      |
 +----------------+--------------------+------+--------------------+------+------------+----------------------+
```
</details>

**hyriseBenchmarkTPCDS - multi-threaded (50 clients)**
<details>
<summary>
Sum of average per-item runtime: TODO,
Geometric Mean: +48%
</summary>

```diff
 +----------------+--------------------+------+--------------------+------+------------+---------+
 | Benchmark      | prev. iter/s       | runs | new iter/s         | runs | change [%] | p-value |
 +----------------+--------------------+------+--------------------+------+------------+---------+
 | 01             | 152.7295379638672  | 1528 | 150.30020141601562 | 1504 | -2%        |  0.3159 |
+| 03             | 208.51466369628906 | 2087 | 395.6208190917969  | 3960 | +90%       |  0.0000 |
+| 06             | 127.49842834472656 | 1275 | 249.0469207763672  | 2492 | +95%       |  0.0000 |
+| 07             | 55.38947677612305  | 554  | 68.08348846435547  | 681  | +23%       |  0.0002 |
 | 09             | 84.15428161621094  | 842  | 84.14092254638672  | 842  | -0%        |  0.9274 |
+| 10             | 76.3825912475586   | 764  | 362.0825500488281  | 3623 | +374%      |  0.0000 |
 | 13             | 62.590492248535156 | 626  | 64.07978820800781  | 641  | +2%        |  0.6619 |
+| 15             | 230.86666870117188 | 2309 | 430.01715087890625 | 4303 | +86%       |  0.0000 |
+| 17             | 79.69676971435547  | 797  | 188.31924438476562 | 1885 | +136%      |  0.0000 |
-| 19             | 186.61672973632812 | 1868 | 162.476806640625   | 1625 | -13%       |  0.0002 |
+| 25             | 101.3938980102539  | 1014 | 153.30795288085938 | 1534 | +51%       |  0.0000 |
+| 26             | 102.86083984375    | 1029 | 117.3241958618164  | 1174 | +14%       |  0.0235 |
-| 28             | 172.5399169921875  | 1727 | 163.69178771972656 | 1637 | -5%        |  0.3495 |
+| 29             | 79.25570678710938  | 793  | 166.7517852783203  | 1669 | +110%      |  0.0000 |
+| 31             | 23.686214447021484 | 237  | 40.58694076538086  | 406  | +71%       |  0.0000 |
+| 34             | 129.80795288085938 | 1299 | 254.46026611328125 | 2547 | +96%       |  0.0000 |
+| 35             | 24.980087280273438 | 250  | 32.49614715576172  | 325  | +30%       |  0.0006 |
+| 39a            | 8.996088027954102  | 90   | 17.28689956665039  | 173  | +92%       |  0.0000 |
+| 39b            | 8.699431419372559  | 87   | 18.195337295532227 | 182  | +109%      |  0.0000 |
+| 41             | 29.996807098388672 | 300  | 33.29404067993164  | 333  | +11%       |  0.3843 |
+| 42             | 217.70858764648438 | 2179 | 363.8388671875     | 3641 | +67%       |  0.0000 |
+| 43             | 42.79618453979492  | 428  | 51.079185485839844 | 511  | +19%       |  0.0002 |
+| 45             | 341.6644592285156  | 3417 | 495.73162841796875 | 4962 | +45%       |  0.0000 |
+| 48             | 42.89738464355469  | 429  | 51.74850082397461  | 518  | +21%       |  0.0854 |
+| 50             | 174.86383056640625 | 1749 | 261.6268615722656  | 2618 | +50%       |  0.0000 |
+| 52             | 215.92221069335938 | 2161 | 365.1882019042969  | 3653 | +69%       |  0.0000 |
+| 55             | 214.6847381591797  | 2148 | 360.54852294921875 | 3609 | +68%       |  0.0000 |
 | 62             | 97.3674087524414   | 974  | 99.7457046508789   | 998  | +2%        |  0.6897 |
+| 65             | 44.26861572265625  | 443  | 50.08232879638672  | 501  | +13%       |  0.0036 |
+| 69             | 65.75625610351562  | 658  | 197.6092529296875  | 1977 | +201%      |  0.0000 |
+| 73             | 148.692138671875   | 1488 | 346.3992919921875  | 3466 | +133%      |  0.0000 |
+| 79             | 89.4736557006836   | 895  | 131.66009521484375 | 1317 | +47%       |  0.0000 |
 | 81             | 229.63101196289062 | 2297 | 226.64601135253906 | 2268 | -1%        |  0.4191 |
+| 83             | 235.2252960205078  | 2354 | 477.6727600097656  | 4778 | +103%      |  0.0000 |
+| 85             | 60.95421600341797  | 610  | 87.84254455566406  | 879  | +44%       |  0.0504 |
+| 88             | 18.382474899291992 | 184  | 37.09587478637695  | 371  | +102%      |  0.0003 |
+| 91             | 376.2187805175781  | 3765 | 456.6812744140625  | 4568 | +21%       |  0.0000 |
 | 93             | 24.28481674194336  | 243  | 23.577505111694336 | 236  | -3%        |  0.0367 |
+| 96             | 202.0947723388672  | 2021 | 290.7749938964844  | 2909 | +44%       |  0.0000 |
 | 97             | 5.899343013763428  | 59   | 5.89868688583374   | 59   | -0%        |  0.6033 |
 | 99             | 37.387855529785156 | 374  | 36.06416702270508  | 361  | -4%        |  0.3946 |
+| geometric mean |                    |      |                    |      | +48%       |         |
 +----------------+--------------------+------+--------------------+------+------------+---------+
```
</details>

**hyriseBenchmarkTPCC - single-threaded**
<details>
<summary>
Sum of average per-item runtime: TODO,
Geometric Mean: +0%
</summary>

```diff
 +----------------+--------------------+------+--------------------+------+------------+----------------------+
 | Benchmark      | prev. iter/s       | runs | new iter/s         | runs | change [%] |              p-value |
 +----------------+--------------------+------+--------------------+------+------------+----------------------+
 | Delivery       | 1.9975433349609375 | 20   | 2.0945632457733154 | 21   | +5%        | (run time too short) |
 | New-Order      | 22.77199363708496  | 228  | 23.23967933654785  | 233  | +2%        | (run time too short) |
 | Order-Status   | 2.0974204540252686 | 21   | 1.9948222637176514 | 20   | -5%        | (run time too short) |
 | Payment        | 21.873098373413086 | 219  | 21.643821716308594 | 217  | -1%        | (run time too short) |
 | Stock-Level    | 1.9975433349609375 | 20   | 1.9948222637176514 | 20   | -0%        | (run time too short) |
 | geometric mean |                    |      |                    |      | +0%        |                      |
 +----------------+--------------------+------+--------------------+------+------------+----------------------+
```
</details>

**hyriseBenchmarkTPCC - multi-threaded (50 clients)**
<details>
<summary>
Sum of average per-item runtime: TODO,
Geometric Mean: +2%
</summary>

```diff
 +----------------+--------------------+--------+--------------------+--------+------------+----------------------+
 | Benchmark      | prev. iter/s       | runs   | new iter/s         | runs   | change [%] |              p-value |
 +----------------+--------------------+--------+--------------------+--------+------------+----------------------+
-| Delivery       | 2.962062120437622  | 30     | 2.747035503387451  | 28     | -7%        | (run time too short) |
 |   unsucc.:     |  93.13364308025464 |  932   |  94.48530344410081 |  945   |  +1%       |                      |
 | New-Order      | 60.32733154296875  | 611    | 60.925323486328125 | 621    | +1%        |               0.5042 |
 |   unsucc.:     |  1018.973989795447 |  10197 |  1032.739364311235 |  10329 |  +1%       |                      |
 | Order-Status   | 94.88471984863281  | 961    | 95.65570068359375  | 975    | +1%        | (run time too short) |
+| Payment        | 7.207684516906738  | 73     | 8.437323570251465  | 86     | +17%       | (run time too short) |
 |   unsucc.:     |  1025.969005906625 |  10267 |  1038.138524508041 |  10383 |  +1%       |                      |
 | Stock-Level    | 93.69989776611328  | 949    | 94.77272033691406  | 966    | +1%        |               0.0000 |
 | geometric mean |                    |        |                    |        | +2%        |                      |
 +----------------+--------------------+--------+--------------------+--------+------------+----------------------+
```
</details>

**hyriseBenchmarkJoinOrder - single-threaded**
<details>
<summary>
Sum of average per-item runtime: TODO,
Geometric Mean: +64%
</summary>

```diff
 +----------------+---------------------+------+---------------------+------+------------+----------------------+
 | Benchmark      | prev. iter/s        | runs | new iter/s          | runs | change [%] |              p-value |
 +----------------+---------------------+------+---------------------+------+------------+----------------------+
+| 10a            | 0.7666268944740295  | 8    | 2.917487621307373   | 30   | +281%      | (run time too short) |
+| 10b            | 0.8090618252754211  | 9    | 2.918529987335205   | 30   | +261%      | (run time too short) |
+| 10c            | 0.7433853149414062  | 8    | 0.8056604862213135  | 9    | +8%        | (run time too short) |
+| 11a            | 3.2909069061279297  | 33   | 6.386143207550049   | 64   | +94%       | (run time too short) |
+| 11b            | 3.3963606357574463  | 34   | 6.885761260986328   | 69   | +103%      | (run time too short) |
+| 11c            | 1.343322515487671   | 14   | 1.7090436220169067  | 18   | +27%       | (run time too short) |
 | 11d            | 0.17191210389137268 | 2    | 0.173066183924675   | 2    | +1%        | (run time too short) |
+| 12a            | 1.920884132385254   | 20   | 2.6068296432495117  | 27   | +36%       | (run time too short) |
+| 12b            | 1.1456183195114136  | 12   | 1.6101311445236206  | 17   | +41%       | (run time too short) |
+| 12c            | 0.2497260719537735  | 3    | 0.2719617187976837  | 3    | +9%        | (run time too short) |
+| 13a            | 3.4650051593780518  | 35   | 5.695309162139893   | 57   | +64%       | (run time too short) |
-| 13b            | 3.116473913192749   | 32   | 2.5057780742645264  | 26   | -20%       | (run time too short) |
-| 13c            | 4.667132377624512   | 47   | 3.4521257877349854  | 35   | -26%       | (run time too short) |
+| 13d            | 3.5071258544921875  | 36   | 5.727149486541748   | 58   | +63%       | (run time too short) |
+| 14a            | 0.22662214934825897 | 3    | 0.24697422981262207 | 3    | +9%        | (run time too short) |
+| 14b            | 0.19831699132919312 | 2    | 0.21665635704994202 | 3    | +9%        | (run time too short) |
+| 14c            | 0.22638185322284698 | 3    | 0.24704821407794952 | 3    | +9%        | (run time too short) |
+| 15a            | 2.14037823677063    | 22   | 4.418459415435791   | 45   | +106%      | (run time too short) |
+| 15b            | 2.379394054412842   | 24   | 4.632963180541992   | 47   | +95%       | (run time too short) |
+| 15c            | 3.19360089302063    | 32   | 5.777309894561768   | 58   | +81%       | (run time too short) |
+| 15d            | 1.3168753385543823  | 14   | 1.9497520923614502  | 20   | +48%       | (run time too short) |
+| 16a            | 0.14912189543247223 | 2    | 0.17789943516254425 | 2    | +19%       | (run time too short) |
+| 16b            | 0.11995795369148254 | 2    | 0.13829168677330017 | 2    | +15%       | (run time too short) |
+| 16c            | 0.14719624817371368 | 2    | 0.17683950066566467 | 2    | +20%       | (run time too short) |
+| 16d            | 0.14933092892169952 | 2    | 0.18182910978794098 | 2    | +22%       | (run time too short) |
+| 17a            | 0.5072794556617737  | 6    | 0.941189706325531   | 10   | +86%       | (run time too short) |
+| 17b            | 0.5679396390914917  | 6    | 1.245987892150879   | 13   | +119%      | (run time too short) |
+| 17c            | 0.6054059863090515  | 7    | 1.3312627077102661  | 14   | +120%      | (run time too short) |
+| 17d            | 0.5690008997917175  | 6    | 1.150716781616211   | 12   | +102%      | (run time too short) |
+| 17e            | 0.21398410201072693 | 3    | 0.2956011891365051  | 3    | +38%       | (run time too short) |
+| 17f            | 0.3698388338088989  | 4    | 0.5708553791046143  | 6    | +54%       | (run time too short) |
+| 18a            | 0.7757340669631958  | 8    | 1.4229909181594849  | 15   | +83%       | (run time too short) |
+| 18b            | 0.9222990274429321  | 10   | 3.9423747062683105  | 40   | +327%      | (run time too short) |
+| 18c            | 0.20496845245361328 | 3    | 0.2709575593471527  | 3    | +32%       | (run time too short) |
-| 19a            | 0.1265053153038025  | 2    | 0.12012678384780884 | 2    | -5%        | (run time too short) |
-| 19b            | 0.20533756911754608 | 3    | 0.18748605251312256 | 2    | -9%        | (run time too short) |
 | 19c            | 0.12986841797828674 | 2    | 0.12401843816041946 | 2    | -5%        | (run time too short) |
+| 19d            | 0.14912006258964539 | 2    | 0.16106007993221283 | 2    | +8%        | (run time too short) |
+| 1a             | 9.33112621307373    | 94   | 12.139434814453125  | 122  | +30%       | (run time too short) |
+| 1b             | 16.396347045898438  | 164  | 42.790035247802734  | 428  | +161%      | (run time too short) |
+| 1c             | 12.123202323913574  | 122  | 43.425636291503906  | 435  | +258%      | (run time too short) |
+| 1d             | 16.40367889404297   | 165  | 44.06511688232422   | 441  | +169%      | (run time too short) |
+| 20a            | 0.441412091255188   | 5    | 0.7179332971572876  | 8    | +63%       | (run time too short) |
+| 20b            | 0.5149846076965332  | 6    | 0.8272765278816223  | 9    | +61%       | (run time too short) |
+| 20c            | 0.4578174948692322  | 5    | 0.798258364200592   | 8    | +74%       | (run time too short) |
+| 21a            | 0.2449592649936676  | 3    | 0.26994094252586365 | 3    | +10%       | (run time too short) |
+| 21b            | 2.3118796348571777  | 24   | 3.866885185241699   | 39   | +67%       | (run time too short) |
+| 21c            | 0.23509597778320312 | 3    | 0.25943878293037415 | 3    | +10%       | (run time too short) |
+| 22a            | 0.26428523659706116 | 3    | 0.2935495376586914  | 3    | +11%       | (run time too short) |
+| 22b            | 0.2643534541130066  | 3    | 0.29349860548973083 | 3    | +11%       | (run time too short) |
+| 22c            | 0.22534365952014923 | 3    | 0.24715588986873627 | 3    | +10%       | (run time too short) |
+| 22d            | 0.2241673767566681  | 3    | 0.2453813999891281  | 3    | +9%        | (run time too short) |
+| 23a            | 3.4517617225646973  | 35   | 5.809810638427734   | 59   | +68%       | (run time too short) |
+| 23b            | 1.9657924175262451  | 20   | 8.305229187011719   | 84   | +322%      | (run time too short) |
+| 23c            | 3.0298705101013184  | 31   | 5.127095699310303   | 52   | +69%       | (run time too short) |
+| 24a            | 0.168451189994812   | 2    | 0.18344646692276    | 2    | +9%        | (run time too short) |
 | 24b            | 0.17541778087615967 | 2    | 0.18027441203594208 | 2    | +3%        | (run time too short) |
+| 25a            | 0.9690513014793396  | 10   | 3.965226888656616   | 40   | +309%      | (run time too short) |
+| 25b            | 1.5764234066009521  | 16   | 3.862997055053711   | 39   | +145%      | (run time too short) |
+| 25c            | 0.20188511908054352 | 3    | 0.27106136083602905 | 3    | +34%       | (run time too short) |
+| 26a            | 0.7740569114685059  | 8    | 0.924584150314331   | 10   | +19%       | (run time too short) |
+| 26b            | 0.8006780743598938  | 9    | 0.9237695336341858  | 10   | +15%       | (run time too short) |
+| 26c            | 0.7762975096702576  | 8    | 0.9202499985694885  | 10   | +19%       | (run time too short) |
+| 27a            | 0.2626008689403534  | 3    | 0.2965477406978607  | 3    | +13%       | (run time too short) |
+| 27b            | 0.2673353850841522  | 3    | 0.3017827570438385  | 4    | +13%       | (run time too short) |
+| 27c            | 1.5438058376312256  | 16   | 4.872625350952148   | 49   | +216%      | (run time too short) |
+| 28a            | 0.21277092397212982 | 3    | 0.23512689769268036 | 3    | +11%       | (run time too short) |
+| 28b            | 0.25556206703186035 | 3    | 0.28280118107795715 | 3    | +11%       | (run time too short) |
+| 28c            | 0.21448779106140137 | 3    | 0.2350950986146927  | 3    | +10%       | (run time too short) |
-| 29a            | 0.1809266060590744  | 2    | 0.1709602028131485  | 2    | -6%        | (run time too short) |
+| 29b            | 1.4797697067260742  | 15   | 4.224630355834961   | 43   | +185%      | (run time too short) |
+| 29c            | 0.158352330327034   | 2    | 0.1690806746482849  | 2    | +7%        | (run time too short) |
+| 2a             | 4.019091606140137   | 41   | 9.408187866210938   | 95   | +134%      | (run time too short) |
+| 2b             | 4.743913173675537   | 48   | 12.101358413696289  | 122  | +155%      | (run time too short) |
+| 2c             | 7.7538580894470215  | 78   | 18.829469680786133  | 189  | +143%      | (run time too short) |
+| 2d             | 3.6066808700561523  | 37   | 7.42840576171875    | 75   | +106%      | (run time too short) |
+| 30a            | 1.68599271774292    | 17   | 3.5267584323883057  | 36   | +109%      | (run time too short) |
+| 30b            | 0.6998084187507629  | 7    | 0.8722491264343262  | 9    | +25%       | (run time too short) |
+| 30c            | 0.1981561779975891  | 2    | 0.2572510540485382  | 3    | +30%       | (run time too short) |
+| 31a            | 1.169984221458435   | 12   | 3.2974116802215576  | 33   | +182%      | (run time too short) |
+| 31b            | 0.7017995119094849  | 8    | 0.8812888860702515  | 9    | +26%       | (run time too short) |
+| 31c            | 1.2739460468292236  | 13   | 3.2460732460021973  | 33   | +155%      | (run time too short) |
+| 32a            | 15.259864807128906  | 153  | 26.491806030273438  | 265  | +74%       | (run time too short) |
+| 32b            | 2.2383975982666016  | 23   | 3.4589455127716064  | 35   | +55%       | (run time too short) |
+| 33a            | 4.092402935028076   | 41   | 13.398865699768066  | 134  | +227%      | (run time too short) |
+| 33b            | 4.161233901977539   | 42   | 13.741423606872559  | 138  | +230%      | (run time too short) |
+| 33c            | 3.305326461791992   | 34   | 11.294214248657227  | 113  | +242%      | (run time too short) |
+| 3a             | 0.2396663874387741  | 3    | 0.26414069533348083 | 3    | +10%       | (run time too short) |
+| 3b             | 7.5411882400512695  | 76   | 27.845273971557617  | 279  | +269%      | (run time too short) |
+| 3c             | 0.18668223917484283 | 2    | 0.2024061530828476  | 3    | +8%        | (run time too short) |
+| 4a             | 4.208930492401123   | 43   | 7.451892852783203   | 75   | +77%       | (run time too short) |
+| 4b             | 8.840843200683594   | 89   | 37.19252395629883   | 372  | +321%      | (run time too short) |
+| 4c             | 4.033318042755127   | 41   | 6.583630561828613   | 66   | +63%       | (run time too short) |
+| 5a             | 0.2558465898036957  | 3    | 0.2768539786338806  | 3    | +8%        | (run time too short) |
 | 5b             | 3.378668785095215   | 34   | 3.4401891231536865  | 35   | +2%        | (run time too short) |
+| 5c             | 0.2181481122970581  | 3    | 0.23368321359157562 | 3    | +7%        | (run time too short) |
+| 6a             | 0.8107407093048096  | 9    | 4.07851505279541    | 41   | +403%      | (run time too short) |
+| 6b             | 0.5616432428359985  | 6    | 1.027351975440979   | 11   | +83%       | (run time too short) |
+| 6c             | 0.8640299439430237  | 9    | 4.080198287963867   | 41   | +372%      | (run time too short) |
+| 6d             | 0.551241934299469   | 6    | 1.0332849025726318  | 11   | +87%       | (run time too short) |
+| 6e             | 0.8606554269790649  | 9    | 4.078732013702393   | 41   | +374%      | (run time too short) |
+| 6f             | 0.42222052812576294 | 5    | 0.6479713916778564  | 7    | +53%       | (run time too short) |
+| 7a             | 1.2209159135818481  | 13   | 3.4583017826080322  | 35   | +183%      | (run time too short) |
+| 7b             | 1.7871497869491577  | 18   | 7.710299491882324   | 78   | +331%      | (run time too short) |
+| 7c             | 0.07144394516944885 | 1    | 0.07535656541585922 | 1    | +5%        | (run time too short) |
+| 8a             | 3.4913294315338135  | 35   | 8.711466789245605   | 88   | +150%      | (run time too short) |
+| 8b             | 4.190774440765381   | 42   | 5.3305277824401855  | 54   | +27%       | (run time too short) |
+| 8c             | 0.18403223156929016 | 2    | 0.2062613070011139  | 3    | +12%       | (run time too short) |
+| 8d             | 0.4418218731880188  | 5    | 0.6184670329093933  | 7    | +40%       | (run time too short) |
 | 9a             | 0.2762354016304016  | 3    | 0.2847209870815277  | 3    | +3%        | (run time too short) |
+| 9b             | 1.9471502304077148  | 20   | 2.5681002140045166  | 26   | +32%       | (run time too short) |
+| 9c             | 0.2682841420173645  | 3    | 0.28597429394721985 | 3    | +7%        | (run time too short) |
 | 9d             | 0.23090165853500366 | 3    | 0.24156227707862854 | 3    | +5%        | (run time too short) |
+| geometric mean |                     |      |                     |      | +64%       |                      |
 +----------------+---------------------+------+---------------------+------+------------+----------------------+
```
</details>

**hyriseBenchmarkJoinOrder - multi-threaded (50 clients)**
<details>
<summary>
Sum of average per-item runtime: TODO,
Geometric Mean: +119%
</summary>

```diff
 +----------------+---------------------+------+---------------------+------+------------+----------------------+
 | Benchmark      | prev. iter/s        | runs | new iter/s          | runs | change [%] |              p-value |
 +----------------+---------------------+------+---------------------+------+------------+----------------------+
+| 10a            | 3.699583053588867   | 37   | 8.893267631530762   | 89   | +140%      |               0.0000 |
+| 10b            | 3.8993027210235596  | 39   | 13.491964340209961  | 135  | +246%      |               0.0000 |
+| 10c            | 0.3998482823371887  | 4    | 1.2996926307678223  | 13   | +225%      | (run time too short) |
+| 11a            | 21.28736114501953   | 213  | 45.8770751953125    | 459  | +116%      |               0.0000 |
+| 11b            | 22.78888511657715   | 228  | 47.28084182739258   | 473  | +107%      |               0.0000 |
+| 11c            | 5.196394920349121   | 52   | 9.495923042297363   | 95   | +83%       |               0.0000 |
 | 11d            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
+| 12a            | 5.794860363006592   | 58   | 7.495157241821289   | 75   | +29%       |               0.4668 |
+| 12b            | 8.192689895629883   | 82   | 23.596393585205078  | 236  | +188%      |               0.0000 |
 | 12c            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
+| 13a            | 11.29316234588623   | 113  | 31.8809757232666    | 319  | +182%      |               0.0000 |
+| 13b            | 9.495664596557617   | 95   | 17.29761505126953   | 173  | +82%       |               0.0000 |
+| 13c            | 8.894241333007812   | 89   | 17.59716033935547   | 176  | +98%       |               0.0000 |
+| 13d            | 11.294106483459473  | 113  | 29.183393478393555  | 292  | +158%      |               0.0000 |
 | 14a            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 14b            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 14c            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
+| 15a            | 8.094030380249023   | 81   | 18.692367553710938  | 187  | +131%      |               0.0000 |
+| 15b            | 8.099735260009766   | 81   | 22.87955093383789   | 229  | +182%      |               0.0000 |
+| 15c            | 27.39204978942871   | 274  | 66.17123413085938   | 662  | +142%      |               0.0000 |
+| 15d            | 3.8968820571899414  | 39   | 9.69709587097168    | 97   | +149%      |               0.0000 |
 | 16a            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 16b            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 16c            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 16d            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 17a            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
+| 17b            | 0.1998743861913681  | 2    | 2.299175262451172   | 23   | +1050%     | (run time too short) |
+| 17c            | 0.8994766473770142  | 9    | 2.1993672847747803  | 22   | +145%      |    (not enough runs) |
+| 17d            | 0.19986625015735626 | 2    | 1.7994316816329956  | 18   | +800%      | (run time too short) |
 | 17e            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 17f            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
+| 18a            | 0.19979776442050934 | 2    | 4.196922302246094   | 42   | +2001%     | (run time too short) |
+| 18b            | 4.296347141265869   | 43   | 13.791266441345215  | 138  | +221%      |               0.0000 |
 | 18c            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 19a            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 19b            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 19c            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 19d            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
+| 1a             | 52.889015197753906  | 529  | 110.19194030761719  | 1102 | +108%      |               0.0000 |
+| 1b             | 68.37557983398438   | 684  | 612.675537109375    | 6127 | +796%      |               0.0000 |
+| 1c             | 59.24996566772461   | 593  | 584.0279541015625   | 5841 | +886%      |               0.0000 |
+| 1d             | 68.97191619873047   | 690  | 609.9950561523438   | 6106 | +784%      |               0.0000 |
-| 20a            | 1.6990795135498047  | 17   | 0.6993725299835205  | 7    | -59%       |    (not enough runs) |
-| 20b            | 1.9984859228134155  | 20   | 0.09990601986646652 | 1    | -95%       | (run time too short) |
-| 20c            | 1.2993099689483643  | 13   | 0.099964439868927   | 1    | -92%       | (run time too short) |
 | 21a            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
+| 21b            | 11.495401382446289  | 115  | 33.79765701293945   | 338  | +194%      |               0.0000 |
 | 21c            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 22a            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 22b            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 22c            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 22d            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
+| 23a            | 25.49987030029297   | 255  | 81.699951171875     | 817  | +220%      |               0.0000 |
+| 23b            | 10.39931583404541   | 104  | 14.29743766784668   | 143  | +37%       |               0.0004 |
+| 23c            | 23.67658042907715   | 237  | 69.2973403930664    | 693  | +193%      |               0.0000 |
 | 24a            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 24b            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
+| 25a            | 4.999326229095459   | 50   | 13.593585014343262  | 136  | +172%      |               0.0000 |
+| 25b            | 4.396481990814209   | 44   | 11.099846839904785  | 111  | +152%      |               0.0000 |
 | 25c            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
+| 26a            | 3.0998237133026123  | 31   | 7.396584510803223   | 74   | +139%      |               0.0000 |
+| 26b            | 2.999920129776001   | 30   | 7.296200752258301   | 73   | +143%      |               0.0000 |
+| 26c            | 2.7971816062927246  | 28   | 7.094931602478027   | 71   | +154%      |               0.0000 |
 | 27a            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 27b            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
+| 27c            | 8.398283958435059   | 84   | 12.489882469177246  | 125  | +49%       |               0.0010 |
 | 28a            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 28b            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 28c            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 29a            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
+| 29b            | 1.6998920440673828  | 17   | 7.197262763977051   | 72   | +323%      |               0.2832 |
 | 29c            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
+| 2a             | 18.892410278320312  | 189  | 43.481773376464844  | 435  | +130%      |               0.0000 |
+| 2b             | 25.387588500976562  | 254  | 34.18230056762695   | 342  | +35%       |               0.0390 |
+| 2c             | 35.386329650878906  | 354  | 51.26487350463867   | 513  | +45%       |               0.0000 |
+| 2d             | 17.89550018310547   | 179  | 42.46092224121094   | 425  | +137%      |               0.0000 |
+| 30a            | 6.194784641265869   | 62   | 12.59260368347168   | 126  | +103%      |               0.0000 |
+| 30b            | 3.4988317489624023  | 35   | 9.397550582885742   | 94   | +169%      |               0.0000 |
 | 30c            | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
+| 31a            | 3.6964938640594482  | 37   | 8.894533157348633   | 89   | +141%      |               0.0000 |
+| 31b            | 2.499040126800537   | 25   | 7.696518421173096   | 77   | +208%      |               0.0000 |
+| 31c            | 3.5975050926208496  | 36   | 8.795791625976562   | 88   | +144%      |               0.0000 |
+| 32a            | 47.06801223754883   | 471  | 347.8757629394531   | 3482 | +639%      |               0.0000 |
+| 32b            | 13.08917236328125   | 131  | 26.489837646484375  | 265  | +102%      |               0.0000 |
+| 33a            | 20.279409408569336  | 203  | 111.21633911132812  | 1113 | +448%      |               0.0000 |
+| 33b            | 20.882347106933594  | 209  | 123.08650207519531  | 1231 | +489%      |               0.0000 |
+| 33c            | 19.685335159301758  | 197  | 95.37092590332031   | 954  | +384%      |               0.0000 |
 | 3a             | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
+| 3b             | 46.75751876831055   | 468  | 51.59648513793945   | 516  | +10%       |               0.1827 |
 | 3c             | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
+| 4a             | 16.883056640625     | 169  | 37.471107482910156  | 375  | +122%      |               0.0000 |
+| 4b             | 50.482337951660156  | 505  | 148.08575439453125  | 1481 | +193%      |               0.0000 |
+| 4c             | 15.198683738708496  | 152  | 30.3825626373291    | 304  | +100%      |               0.0000 |
 | 5a             | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
+| 5b             | 17.79039192199707   | 178  | 23.977230072021484  | 240  | +35%       |               0.0000 |
 | 5c             | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
-| 6a             | 4.495729923248291   | 45   | 3.398386240005493   | 34   | -24%       |               0.7674 |
+| 6b             | 1.7993957996368408  | 18   | 2.69860577583313    | 27   | +50%       |               0.0012 |
 | 6c             | 3.5972044467926025  | 36   | 3.598436117172241   | 36   | +0%        |               0.0505 |
+| 6d             | 1.498530387878418   | 15   | 2.898303985595703   | 29   | +93%       |               0.0000 |
-| 6e             | 3.798957347869873   | 38   | 3.198610782623291   | 32   | -16%       |               0.0086 |
 | 6f             | 0.0                 | 0    | 0.09990392625331879 | 1    | +nan%      | (run time too short) |
+| 7a             | 2.899414539337158   | 29   | 9.592265129089355   | 96   | +231%      |               0.0000 |
+| 7b             | 5.396141052246094   | 54   | 17.49181365966797   | 175  | +224%      |               0.0000 |
 | 7c             | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
-| 8a             | 22.188383102416992  | 222  | 10.891783714294434  | 109  | -51%       |               0.0000 |
-| 8b             | 39.789390563964844  | 398  | 13.5897855758667    | 136  | -66%       |               0.0000 |
 | 8c             | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 8d             | 0.0                 | 0    | 0.09991838783025742 | 1    | +nan%      | (run time too short) |
 | 9a             | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 9b             | 8.292988777160645   | 83   | 8.298184394836426   | 83   | +0%        |               0.0525 |
 | 9c             | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
 | 9d             | 0.0                 | 0    | 0.0                 | 0    | +nan%      | (run time too short) |
+| geometric mean |                     |      |                     |      | +119%      |                      |
 +----------------+---------------------+------+---------------------+------+------------+----------------------+
```
</details>

### CODE REVIEW

**Comment by mrks** [comment]
@Bouncner Might be of interest for you too.

File: scripts/benchmark_all.sh [hunk 1]
```diff
@@ -0,0 +1,152 @@
...
+end_commit=$(git rev-parse $end_commit_reference | head -n 1)
+
+# Check status of repository
+if [[ $(git status --untracked-files=no --porcelain) ]]
+then
+  echo 'Cowardly refusing to execute on a dirty workspace'
+  exit 1
+fi
+
+# Ensure that this is run on a release build. Not really necessary, just a sanity check.
```
Comment (j-tr) [inline scripts/benchmark_all.sh:31]: *runs | *is running

**Comment by j-tr** [comment]
maybe add a line about this somewhere in the readme

**Comment by Bouncner** [comment]
Loving it! I'll take a look when I am done with the remaining tests of the compare benchmark script. Would like to avoid parallel work here.

File: scripts/benchmark_all.sh [hunk 2]
```diff
@@ -0,0 +1,152 @@
...
+    sleep 1  # Easiest way to make sure the above is read
+    continue
+  fi
+
+  # Checkout and build from scratch, tracking the compile time
+  git checkout $commit
+  git submodule update --init
+  echo "Building $commit..."
+  $build clean
+  /usr/bin/time -p sh -c "( $build -j $(nproc) ${benchmarks} 2>&1 ) | tee benchmark_all_results/build_${commit}.log" 2>"benchmark_all_results/build_time_${commit}.txt"
```
Comment (julianmenzler) [inline scripts/benchmark_all.sh:70]: `nproc` is a Linux-only utility. The equivalent on macOS is `sysctl -n hw.logicalcpu`

File: scripts/benchmark_all.sh [hunk 3]
```diff
@@ -0,0 +1,152 @@
...
+# Print information about the system
+echo "**System**"
+echo "<details>"
+echo "<summary>$(hostname) - click to expand</summary>"
+echo ""
+echo "| property | value |"
+echo "| -- | -- |"
+echo "| Hostname | $(hostname) |"
+if [[ "$(uname)" == 'Darwin' ]]; then
+  echo "| Model | $(defaults read ~/Library/Preferences/com.apple.SystemProfiler.plist 'CPU Names' | cut -sd '"' -f 4) |"
```
Comment (julianmenzler) [inline scripts/benchmark_all.sh:103]:
```bash
$ defaults read ~/Library/Preferences/com.apple.SystemProfiler.plist 'CPU Names'
{
    "JHD4-en-DE_DE" = "MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)";
    "ML7M-en-DE_DE" = "MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)";
}
```
Special case since I have upgraded my system previously. Consider using the following:
```bash
$ sysctl -n hw.model
MacBookPro16,2
```

File: scripts/benchmark_all.sh [hunk 4]
```diff
@@ -0,0 +1,152 @@
...
+  echo "| CPU | $(sysctl -n machdep.cpu.brand_string) |"
+  echo "| Memory | $(system_profiler SPHardwareDataType | grep '  Memory:' | sed 's/Memory://') |"
```
Comment (julianmenzler) [inline scripts/benchmark_all.sh:105]:
```
$ system_profiler SPHardwareDataType | grep '  Memory:' | sed 's/Memory://'
       16 GB
```

To get rid of the preceding whitespaces:
```
$ system_profiler SPHardwareDataType | grep '  Memory:' | sed -E "s/[[:space:]]+Memory://"
 16 GB
```

**Comment by mrks** [comment]
> maybe add a line about this somewhere in the readme

We don't even mention compare_benchmarks.py there. "Our" people will learn about it sooner than later. For outsiders, this is not too relevant, so I wouldn't want to overload the readme.

File: scripts/benchmark_all.sh (hunk 2 above)
Comment (mrks) [reply scripts/benchmark_all.sh:70]: How about adding coreutils to the brew requirements?

Comment (mrks) [reply scripts/benchmark_all.sh:70]: Might be overkill for this one instance, but since that is one of the most useful packets and provides compatibility for a lot of GNU tools, it might be a good idea anyway.

File: scripts/benchmark_all.sh (hunk 3 above)
Comment (mrks) [reply scripts/benchmark_all.sh:103]: Interesting. I took the code from StackExchange, where people seem to be unaware of this. Added `tail -n1` and added a comment over there.

```
$ sysctl -n hw.model
MacBookPro16,2
```

Looked at it before, hated it. What does 16 mean? Apparently neither the year, nor the display size.

File: scripts/benchmark_all.sh (hunk 4 above)
Comment (mrks) [reply scripts/benchmark_all.sh:105]: Github-flavored Markdown doesn't care about it, so I rather avoid making this more complicated. Glad to see that someone is more comfortable than @Bouncner though ;)

**Comment by mrks** [comment]
> add an option to adjust the scale factor (e.g. s=0.01 for optimizer-related changes)

Good idea, and I was about to add it when I realized that this wouldn't work, e.g., for TPC-C where the "scale factor" has to be an integer.

File: scripts/benchmark_all.sh (hunk 4 above)
Comment (Bouncner) [reply scripts/benchmark_all.sh:106]: Let's take a bet that we'll need to revisit this regex before I finish my thesis!

Comment (julianmenzler) [reply scripts/benchmark_all.sh:106]: Ok ;)

File: scripts/benchmark_all.sh (hunk 3 above)
Comment (julianmenzler) [reply scripts/benchmark_all.sh]: > Looked at it before, hated it. What does 16 mean? Apparently neither the year, nor the display size.

They seem to count up with every new generation. Here is a [list](https://everymac.com/systems/by_capability/mac-specs-by-machine-model-machine-id.html).  But it is not nice. So stay with the above and `tail -n1` ;)

File: scripts/benchmark_all.sh (hunk 2 above)
Comment (julianmenzler) [reply scripts/benchmark_all.sh]: Ok for me. But it should be part of the install-script.

**Comment by julianmenzler** [comment]
> > add an option to adjust the scale factor (e.g. s=0.01 for optimizer-related changes)
> 
> Good idea, and I was about to add it when I realized that this wouldn't work, e.g., for TPC-C where the "scale factor" has to be an integer.

Ok, then we should leave it as is.

File: scripts/benchmark_all.sh [hunk 5]
```diff
@@ -0,0 +1,153 @@
...
+    echo -n "**${benchmark} - "
+    case "${config}" in
+      "st") echo -n "single-threaded" ;;
+      "mt") echo -n "multi-threaded (${num_mt_clients} clients)" ;;
+    esac
+    echo "**"
+    echo "<details>"
+    echo "<summary>"
+    echo "Sum of average per-item runtime: TODO,"
+    echo "$output" | grep 'geometric mean' | sed -E 's/^[+-]//' | sed 's/geometric mean//; s/[ |]//g; s/^/Geometric Mean: /'
```
Comment (Bouncner) [inline scripts/benchmark_all.sh:148]: `  | grep 'Sum' | sed -E 's/^[+-]//' | awk -F"|" '{print $2, $6}' | sed 's/Sum//; s/[ ]//g; s/^/Sum of avg. query runtimes: /'
` | grep 'Geomean' | sed -E 's/^[+-]//' | sed 's/Geomean//; s/[ |]//g; s/^/Geometric Mean: /'`

???

File: scripts/benchmark_all.sh [hunk 6]
```diff
@@ -0,0 +1,153 @@
...
+    echo ""
+    echo -n "**${benchmark} - "
+    case "${config}" in
+      "st") echo -n "single-threaded" ;;
+      "mt") echo -n "multi-threaded (${num_mt_clients} clients)" ;;
+    esac
+    echo "**"
+    echo "<details>"
+    echo "<summary>"
+    echo "$output" | grep '| Sum ' | sed -E 's/^[+-]//' | awk -F"|" '{print $2, $6}'  | sed 's/Sum//; s/[ ]//g; s/^/Sum of avg. query runtimes: /'
```
Comment (Bouncner) [inline scripts/benchmark_all.sh:147]: Argh, actually it's "item runtimes", isn't it?

**Comment by mrks** [comment]
This is what it looks now. @Bouncner - zünd the knaller?

**System**
<details>
<summary>nemea - click to expand</summary>

| property | value |
| -- | -- |
| Hostname | nemea |
| CPU | Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz |
| Memory | 1.2TB |
| numactl | nodebind: 0  |
| numactl | membind: 0  |
</details>

**Build Time**
| commit | build time |
| -- | -- |
| afa7559f02a5714bc2cea7c3b213840b1fdf01c3 |real 287.22 user 2552.80 sys 149.19|
| 1c5715cbffb21ad6a89b2406d6f010072106a0b6 |real 286.31 user 2544.61 sys 152.38|


**hyriseBenchmarkTPCH - single-threaded**
<details>
<summary>
Sum of avg. item runtimes: -3%
 ||
Geometric mean of throughput changes: +2%
</summary>

```diff
 +Configuration Overview----+----------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                | /home/Markus.Dreseler/hyrise5/build-release/benchmark_all_results/hyriseBenchmarkTPCH_afa7559f02a5714bc2cea7c3b213840b1fdf01c3_st.json | /home/Markus.Dreseler/hyrise5/build-release/benchmark_all_results/hyriseBenchmarkTPCH_1c5715cbffb21ad6a89b2406d6f010072106a0b6_st.json |
 +--------------------------+----------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                | afa7559f02a5714bc2cea7c3b213840b1fdf01c3-dirty                                                                                         | 1c5715cbffb21ad6a89b2406d6f010072106a0b6-dirty                                                                                         |
 |  benchmark_mode          | Ordered                                                                                                                                | Ordered                                                                                                                                |
 |  build_type              | release                                                                                                                                | release                                                                                                                                |
 |  chunk_size              | 65535                                                                                                                                  | 65535                                                                                                                                  |
 |  clients                 | 1                                                                                                                                      | 1                                                                                                                                      |
 |  compiler                | gcc 9.2                                                                                                                                | gcc 9.2                                                                                                                                |
 |  cores                   | 0                                                                                                                                      | 0                                                                                                                                      |
 |  date                    | 2020-08-25 20:22:40                                                                                                                    | 2020-08-26 03:14:54                                                                                                                    |
 |  encoding                | {'default': {'encoding': 'Dictionary'}}                                                                                                | {'default': {'encoding': 'Dictionary'}}                                                                                                |
 |  indexes                 | False                                                                                                                                  | False                                                                                                                                  |
 |  max_duration            | 60000000000                                                                                                                            | 60000000000                                                                                                                            |
 |  max_runs                | -1                                                                                                                                     | -1                                                                                                                                     |
 |  scale_factor            | 1.0                                                                                                                                    | 1.0                                                                                                                                    |
 |  time_unit               | ns                                                                                                                                     | ns                                                                                                                                     |
 |  use_prepared_statements | False                                                                                                                                  | False                                                                                                                                  |
 |  using_scheduler         | False                                                                                                                                  | False                                                                                                                                  |
 |  verify                  | False                                                                                                                                  | False                                                                                                                                  |
 |  warmup_duration         | 0                                                                                                                                      | 0                                                                                                                                      |
 +--------------------------+----------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+

 +----------++----------+---------+--------++----------+----------+--------+---------+
 | Item     || Latency (ms/iter)  | Change || Throughput (iter/s) | Change | p-value |
 |          ||      old |     new |        ||      old |      new |        |         |
 +----------++----------+---------+--------++----------+----------+--------+---------+
 | TPC-H 01 ||    805.4 |   835.4 |   +4%  ||     1.24 |     1.20 |   -4%  |  0.0000 |
 | TPC-H 02 ||      4.7 |     4.7 |   -0%  ||   210.54 |   211.43 |   +0%  |  0.5842 |
 | TPC-H 03 ||     82.8 |    81.9 |   -1%  ||    12.08 |    12.22 |   +1%  |  0.0000 |
 | TPC-H 04 ||     66.8 |    67.1 |   +0%  ||    14.96 |    14.91 |   -0%  |  0.0000 |
 | TPC-H 05 ||    220.4 |   210.9 |   -4%  ||     4.54 |     4.74 |   +5%  |  0.0000 |
+| TPC-H 06 ||      3.6 |     3.2 |  -11%  ||   279.97 |   312.86 |  +12%  |  0.0000 |
 | TPC-H 07 ||     59.0 |    58.7 |   -1%  ||    16.95 |    17.05 |   +1%  |  0.5185 |
 | TPC-H 08 ||     66.3 |    66.4 |   +0%  ||    15.08 |    15.05 |   -0%  |  0.7543 |
 | TPC-H 09 ||    525.9 |   518.3 |   -1%  ||     1.90 |     1.93 |   +1%  |  0.0000 |
 | TPC-H 10 ||    252.4 |   253.8 |   +1%  ||     3.96 |     3.94 |   -1%  |  0.5972 |
 | TPC-H 11 ||      8.6 |     8.7 |   +1%  ||   116.49 |   115.23 |   -1%  |  0.0000 |
 | TPC-H 12 ||     44.7 |    44.0 |   -2%  ||    22.35 |    22.71 |   +2%  |  0.0000 |
+| TPC-H 13 ||    425.6 |   353.5 |  -17%  ||     2.35 |     2.83 |  +20%  |  0.0000 |
 | TPC-H 14 ||     21.2 |    21.1 |   -1%  ||    47.14 |    47.44 |   +1%  |  0.0000 |
 | TPC-H 15 ||      7.9 |     8.0 |   +1%  ||   126.14 |   125.35 |   -1%  |  0.0000 |
 | TPC-H 16 ||     94.1 |    93.6 |   -1%  ||    10.63 |    10.69 |   +1%  |  0.0708 |
 | TPC-H 17 ||     21.6 |    21.7 |   +0%  ||    46.26 |    46.06 |   -0%  |  0.0188 |
+| TPC-H 18 ||    706.8 |   669.2 |   -5%  ||     1.41 |     1.49 |   +6%  |  0.0000 |
 | TPC-H 19 ||     33.7 |    33.1 |   -2%  ||    29.70 |    30.19 |   +2%  |  0.0000 |
 | TPC-H 20 ||     17.7 |    17.0 |   -4%  ||    56.62 |    58.81 |   +4%  |  0.0000 |
 | TPC-H 21 ||    418.1 |   416.6 |   -0%  ||     2.39 |     2.40 |   +0%  |  0.4106 |
 | TPC-H 22 ||     51.7 |    52.4 |   +1%  ||    19.33 |    19.07 |   -1%  |  0.0000 |
 +----------++----------+---------+--------++----------+----------+--------+---------+
 | Sum      ||   3938.9 |  3839.1 |   -3%  ||          |          |        |         |
 | Geomean  ||          |         |        ||          |          |   +2%  |         |
 +----------++----------+---------+--------++----------+----------+--------+---------+
```
</details>


**hyriseBenchmarkTPCH - multi-threaded (50 clients)**
<details>
<summary>
Sum of avg. item runtimes: -3%
 ||
Geometric mean of throughput changes: +4%
</summary>

```diff
 +Configuration Overview---------+----------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                     | /home/Markus.Dreseler/hyrise5/build-release/benchmark_all_results/hyriseBenchmarkTPCH_afa7559f02a5714bc2cea7c3b213840b1fdf01c3_mt.json | /home/Markus.Dreseler/hyrise5/build-release/benchmark_all_results/hyriseBenchmarkTPCH_1c5715cbffb21ad6a89b2406d6f010072106a0b6_mt.json |
 +-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                     | afa7559f02a5714bc2cea7c3b213840b1fdf01c3-dirty                                                                                         | 1c5715cbffb21ad6a89b2406d6f010072106a0b6-dirty                                                                                         |
 |  benchmark_mode               | Ordered                                                                                                                                | Ordered                                                                                                                                |
 |  build_type                   | release                                                                                                                                | release                                                                                                                                |
 |  chunk_size                   | 65535                                                                                                                                  | 65535                                                                                                                                  |
 |  clients                      | 50                                                                                                                                     | 50                                                                                                                                     |
 |  compiler                     | gcc 9.2                                                                                                                                | gcc 9.2                                                                                                                                |
 |  cores                        | 0                                                                                                                                      | 0                                                                                                                                      |
 |  date                         | 2020-08-25 20:45:22                                                                                                                    | 2020-08-26 03:37:12                                                                                                                    |
 |  encoding                     | {'default': {'encoding': 'Dictionary'}}                                                                                                | {'default': {'encoding': 'Dictionary'}}                                                                                                |
 |  indexes                      | False                                                                                                                                  | False                                                                                                                                  |
 |  max_duration                 | 60000000000                                                                                                                            | 60000000000                                                                                                                            |
 |  max_runs                     | -1                                                                                                                                     | -1                                                                                                                                     |
 |  scale_factor                 | 1.0                                                                                                                                    | 1.0                                                                                                                                    |
 |  time_unit                    | ns                                                                                                                                     | ns                                                                                                                                     |
 |  use_prepared_statements      | False                                                                                                                                  | False                                                                                                                                  |
 |  using_scheduler              | True                                                                                                                                   | True                                                                                                                                   |
 |  utilized_cores_per_numa_node | [56, 0, 0, 0]                                                                                                                          | [56, 0, 0, 0]                                                                                                                          |
 |  verify                       | False                                                                                                                                  | False                                                                                                                                  |
 |  warmup_duration              | 0                                                                                                                                      | 0                                                                                                                                      |
 +-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+

 +----------++----------+---------+--------++----------+----------+--------+---------+
 | Item     || Latency (ms/iter)  | Change || Throughput (iter/s) | Change | p-value |
 |          ||      old |     new |        ||      old |      new |        |         |
 +----------++----------+---------+--------++----------+----------+--------+---------+
+| TPC-H 01 ||   3028.2 |  2635.4 |  -13%  ||    16.05 |    18.36 |  +14%  |  0.0000 |
 | TPC-H 02 ||     21.1 |    21.0 |   -1%  ||  1986.99 |  2001.32 |   +1%  |  0.0214 |
+| TPC-H 03 ||    598.4 |   555.4 |   -7%  ||    82.27 |    88.67 |   +8%  |  0.0000 |
 | TPC-H 04 ||    328.4 |   323.7 |   -1%  ||   149.07 |   151.23 |   +1%  |  0.3583 |
 | TPC-H 05 ||   1600.4 |  1564.0 |   -2%  ||    30.33 |    31.03 |   +2%  |  0.4999 |
 | TPC-H 06 ||     29.0 |    25.3 |  -13%  ||  1556.83 |  1620.94 |   +4%  |  0.0000 |
 | TPC-H 07 ||    307.1 |   294.9 |   -4%  ||   159.50 |   165.81 |   +4%  |  0.0054 |
 | TPC-H 08 ||    382.9 |   383.6 |   +0%  ||   127.83 |   127.99 |   +0%  |  0.9176 |
 | TPC-H 09 ||   3260.3 |  3165.2 |   -3%  ||    14.66 |    15.00 |   +2%  |  0.4455 |
 | TPC-H 10 ||   1856.6 |  1832.5 |   -1%  ||    26.30 |    26.80 |   +2%  |  0.5440 |
 | TPC-H 11 ||     81.1 |    79.8 |   -2%  ||   583.18 |   591.24 |   +1%  |  0.0067 |
+| TPC-H 12 ||    166.9 |   153.0 |   -8%  ||   290.02 |   315.86 |   +9%  |  0.0000 |
 | TPC-H 13 ||   2696.3 |  2641.1 |   -2%  ||    17.98 |    18.20 |   +1%  |  0.5197 |
 | TPC-H 14 ||    167.7 |   165.2 |   -1%  ||   289.16 |   293.37 |   +1%  |  0.0158 |
+| TPC-H 15 ||     69.6 |    61.4 |  -12%  ||   672.85 |   755.95 |  +12%  |  0.0000 |
 | TPC-H 16 ||    519.0 |   516.2 |   -1%  ||    94.94 |    95.42 |   +1%  |  0.6371 |
 | TPC-H 17 ||    209.6 |   205.0 |   -2%  ||   232.29 |   237.22 |   +2%  |  0.1138 |
 | TPC-H 18 ||   7608.0 |  7505.3 |   -1%  ||     6.08 |     6.02 |   -1%  |  0.7064 |
 | TPC-H 19 ||    154.5 |   151.0 |   -2%  ||   312.88 |   320.04 |   +2%  |  0.0410 |
+| TPC-H 20 ||     78.3 |    63.5 |  -19%  ||   601.35 |   730.90 |  +22%  |  0.0000 |
 | TPC-H 21 ||   2462.2 |  2429.3 |   -1%  ||    19.53 |    19.97 |   +2%  |  0.7069 |
 | TPC-H 22 ||    822.2 |   808.7 |   -2%  ||    59.43 |    60.32 |   +1%  |  0.5612 |
 +----------++----------+---------+--------++----------+----------+--------+---------+
 | Sum      ||  26447.7 | 25580.6 |   -3%  ||          |          |        |         |
 | Geomean  ||          |         |        ||          |          |   +4%  |         |
 +----------++----------+---------+--------++----------+----------+--------+---------+
```
</details>


**hyriseBenchmarkTPCDS - single-threaded**
<details>
<summary>
Sum of avg. item runtimes: +0%
 ||
Geometric mean of throughput changes: -0%
</summary>

```diff
 +Configuration Overview--------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter        | /home/Markus.Dreseler/hyrise5/build-release/benchmark_all_results/hyriseBenchmarkTPCDS_afa7559f02a5714bc2cea7c3b213840b1fdf01c3_st.json | /home/Markus.Dreseler/hyrise5/build-release/benchmark_all_results/hyriseBenchmarkTPCDS_1c5715cbffb21ad6a89b2406d6f010072106a0b6_st.json |
 +------------------+-----------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH        | afa7559f02a5714bc2cea7c3b213840b1fdf01c3-dirty                                                                                          | 1c5715cbffb21ad6a89b2406d6f010072106a0b6-dirty                                                                                          |
 |  benchmark_mode  | Ordered                                                                                                                                 | Ordered                                                                                                                                 |
 |  build_type      | release                                                                                                                                 | release                                                                                                                                 |
 |  chunk_size      | 65535                                                                                                                                   | 65535                                                                                                                                   |
 |  clients         | 1                                                                                                                                       | 1                                                                                                                                       |
 |  compiler        | gcc 9.2                                                                                                                                 | gcc 9.2                                                                                                                                 |
 |  cores           | 0                                                                                                                                       | 0                                                                                                                                       |
 |  date            | 2020-08-25 21:07:54                                                                                                                     | 2020-08-26 03:59:42                                                                                                                     |
 |  encoding        | {'default': {'encoding': 'Dictionary'}}                                                                                                 | {'default': {'encoding': 'Dictionary'}}                                                                                                 |
 |  indexes         | False                                                                                                                                   | False                                                                                                                                   |
 |  max_duration    | 60000000000                                                                                                                             | 60000000000                                                                                                                             |
 |  max_runs        | -1                                                                                                                                      | -1                                                                                                                                      |
 |  time_unit       | ns                                                                                                                                      | ns                                                                                                                                      |
 |  using_scheduler | False                                                                                                                                   | False                                                                                                                                   |
 |  verify          | False                                                                                                                                   | False                                                                                                                                   |
 |  warmup_duration | 0                                                                                                                                       | 0                                                                                                                                       |
 +------------------+-----------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+

 +---------++----------+---------+--------++----------+----------+--------+---------+
 | Item    || Latency (ms/iter)  | Change || Throughput (iter/s) | Change | p-value |
 |         ||      old |     new |        ||      old |      new |        |         |
 +---------++----------+---------+--------++----------+----------+--------+---------+
 | 01      ||     31.0 |    30.7 |   -1%  ||    32.25 |    32.57 |   +1%  |  0.0000 |
 | 03      ||      6.6 |     6.6 |   +1%  ||   152.39 |   151.04 |   -1%  |  0.0000 |
 | 06      ||     20.3 |    20.4 |   +1%  ||    49.34 |    49.01 |   -1%  |  0.0000 |
 | 07      ||     56.8 |    57.1 |   +1%  ||    17.60 |    17.51 |   -1%  |  0.0000 |
 | 09      ||    106.7 |   107.2 |   +0%  ||     9.37 |     9.33 |   -0%  |  0.0000 |
 | 10      ||     19.9 |    19.9 |   -0%  ||    50.13 |    50.34 |   +0%  |  0.0000 |
 | 13      ||    135.1 |   135.3 |   +0%  ||     7.40 |     7.39 |   -0%  |  0.8665 |
 | 15      ||     11.9 |    12.0 |   +0%  ||    83.94 |    83.54 |   -0%  |  0.0000 |
 | 17      ||     30.8 |    30.7 |   -0%  ||    32.47 |    32.58 |   +0%  |  0.5723 |
 | 19      ||     11.4 |    11.4 |   -0%  ||    88.03 |    88.07 |   +0%  |  0.5774 |
 | 25      ||     18.1 |    18.2 |   +0%  ||    55.21 |    54.97 |   -0%  |  0.4808 |
 | 26      ||     29.5 |    29.4 |   -0%  ||    33.87 |    33.98 |   +0%  |  0.0000 |
 | 28      ||     94.0 |    94.7 |   +1%  ||    10.63 |    10.56 |   -1%  |  0.0000 |
 | 29      ||     30.9 |    31.0 |   +0%  ||    32.38 |    32.24 |   -0%  |  0.5165 |
 | 31      ||    130.2 |   130.7 |   +0%  ||     7.68 |     7.65 |   -0%  |  0.0001 |
 | 34      ||     29.0 |    29.0 |   +0%  ||    34.52 |    34.45 |   -0%  |  0.0000 |
 | 35      ||    101.1 |   101.0 |   -0%  ||     9.89 |     9.90 |   +0%  |  0.0401 |
 | 39a     ||    209.4 |   213.7 |   +2%  ||     4.78 |     4.68 |   -2%  |  0.0000 |
 | 39b     ||    208.0 |   211.8 |   +2%  ||     4.81 |     4.72 |   -2%  |  0.0000 |
 | 41      ||     25.8 |    25.8 |   -0%  ||    38.73 |    38.82 |   +0%  |  0.0000 |
 | 42      ||      7.6 |     7.6 |   +1%  ||   131.66 |   130.71 |   -1%  |  0.0000 |
 | 43      ||    245.1 |   246.1 |   +0%  ||     4.08 |     4.06 |   -0%  |  0.0000 |
 | 45      ||     10.5 |    10.5 |   +0%  ||    94.96 |    94.78 |   -0%  |  0.0003 |
 | 48      ||    102.2 |   101.7 |   -0%  ||     9.79 |     9.83 |   +0%  |  0.0402 |
 | 50      ||     12.3 |    12.4 |   +1%  ||    81.05 |    80.60 |   -1%  |  0.0000 |
 | 52      ||      7.8 |     7.8 |   +0%  ||   128.97 |   128.43 |   -0%  |  0.0000 |
 | 55      ||      7.6 |     7.7 |   +0%  ||   131.02 |   130.40 |   -0%  |  0.0000 |
 | 62      ||     80.0 |    79.5 |   -1%  ||    12.51 |    12.59 |   +1%  |  0.0000 |
 | 65      ||     73.1 |    73.9 |   +1%  ||    13.68 |    13.52 |   -1%  |  0.0000 |
 | 69      ||     25.1 |    25.3 |   +1%  ||    39.89 |    39.59 |   -1%  |  0.0000 |
 | 73      ||     18.7 |    18.7 |   +0%  ||    53.47 |    53.39 |   -0%  |  0.0001 |
 | 79      ||     51.9 |    52.1 |   +0%  ||    19.27 |    19.20 |   -0%  |  0.0000 |
 | 81      ||     20.0 |    20.1 |   +1%  ||    50.06 |    49.63 |   -1%  |  0.0000 |
 | 83      ||      9.9 |    10.0 |   +1%  ||   101.17 |    99.68 |   -1%  |  0.0000 |
 | 85      ||     65.2 |    64.8 |   -1%  ||    15.35 |    15.44 |   +1%  |  0.7780 |
 | 88      ||    107.8 |   108.0 |   +0%  ||     9.28 |     9.26 |   -0%  |  0.3658 |
 | 91      ||     23.0 |    23.0 |   +0%  ||    43.57 |    43.55 |   -0%  |  0.5795 |
 | 93      ||    262.6 |   267.2 |   +2%  ||     3.81 |     3.74 |   -2%  |  0.0000 |
 | 96      ||      9.9 |    10.0 |   +0%  ||   100.83 |   100.42 |   -0%  |  0.0000 |
 | 97      ||    398.4 |   395.6 |   -1%  ||     2.51 |     2.53 |   +1%  |  0.1602 |
 | 99      ||    161.0 |   160.4 |   -0%  ||     6.21 |     6.23 |   +0%  |  0.0000 |
 +---------++----------+---------+--------++----------+----------+--------+---------+
 | Sum     ||   3006.0 |  3019.0 |   +0%  ||          |          |        |         |
 | Geomean ||          |         |        ||          |          |   -0%  |         |
 +---------++----------+---------+--------++----------+----------+--------+---------+
```
</details>


**hyriseBenchmarkTPCDS - multi-threaded (50 clients)**
<details>
<summary>
Sum of avg. item runtimes: -2%
 ||
Geometric mean of throughput changes: +2%
</summary>

```diff
 +Configuration Overview---------+-----------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                     | /home/Markus.Dreseler/hyrise5/build-release/benchmark_all_results/hyriseBenchmarkTPCDS_afa7559f02a5714bc2cea7c3b213840b1fdf01c3_mt.json | /home/Markus.Dreseler/hyrise5/build-release/benchmark_all_results/hyriseBenchmarkTPCDS_1c5715cbffb21ad6a89b2406d6f010072106a0b6_mt.json |
 +-------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                     | afa7559f02a5714bc2cea7c3b213840b1fdf01c3-dirty                                                                                          | 1c5715cbffb21ad6a89b2406d6f010072106a0b6-dirty                                                                                          |
 |  benchmark_mode               | Ordered                                                                                                                                 | Ordered                                                                                                                                 |
 |  build_type                   | release                                                                                                                                 | release                                                                                                                                 |
 |  chunk_size                   | 65535                                                                                                                                   | 65535                                                                                                                                   |
 |  clients                      | 50                                                                                                                                      | 50                                                                                                                                      |
 |  compiler                     | gcc 9.2                                                                                                                                 | gcc 9.2                                                                                                                                 |
 |  cores                        | 0                                                                                                                                       | 0                                                                                                                                       |
 |  date                         | 2020-08-25 21:49:13                                                                                                                     | 2020-08-26 04:40:49                                                                                                                     |
 |  encoding                     | {'default': {'encoding': 'Dictionary'}}                                                                                                 | {'default': {'encoding': 'Dictionary'}}                                                                                                 |
 |  indexes                      | False                                                                                                                                   | False                                                                                                                                   |
 |  max_duration                 | 60000000000                                                                                                                             | 60000000000                                                                                                                             |
 |  max_runs                     | -1                                                                                                                                      | -1                                                                                                                                      |
 |  time_unit                    | ns                                                                                                                                      | ns                                                                                                                                      |
 |  using_scheduler              | True                                                                                                                                    | True                                                                                                                                    |
 |  utilized_cores_per_numa_node | [56, 0, 0, 0]                                                                                                                           | [56, 0, 0, 0]                                                                                                                           |
 |  verify                       | False                                                                                                                                   | False                                                                                                                                   |
 |  warmup_duration              | 0                                                                                                                                       | 0                                                                                                                                       |
 +-------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+

 +---------++----------+---------+--------++----------+----------+--------+---------+
 | Item    || Latency (ms/iter)  | Change || Throughput (iter/s) | Change | p-value |
 |         ||      old |     new |        ||      old |      new |        |         |
 +---------++----------+---------+--------++----------+----------+--------+---------+
 | 01      ||    262.4 |   260.5 |   -1%  ||   186.43 |   187.79 |   +1%  |  0.3728 |
 | 03      ||    105.8 |   105.4 |   -0%  ||   450.33 |   451.58 |   +0%  |  0.6653 |
 | 06      ||    163.5 |   161.8 |   -1%  ||   296.19 |   299.27 |   +1%  |  0.2623 |
 | 07      ||    586.4 |   580.7 |   -1%  ||    83.71 |    84.41 |   +1%  |  0.5838 |
 | 09      ||    575.5 |   549.9 |   -4%  ||    85.36 |    88.45 |   +4%  |  0.1554 |
 | 10      ||    114.4 |   113.2 |   -1%  ||   419.55 |   423.52 |   +1%  |  0.2689 |
 | 13      ||    483.4 |   480.0 |   -1%  ||   101.79 |   102.53 |   +1%  |  0.6157 |
 | 15      ||     91.4 |    90.6 |   -1%  ||   519.28 |   523.77 |   +1%  |  0.1632 |
 | 17      ||    207.5 |   206.3 |   -1%  ||   234.05 |   235.92 |   +1%  |  0.6115 |
+| 19      ||    293.3 |   257.9 |  -12%  ||   166.68 |   189.01 |  +13%  |  0.0000 |
+| 25      ||    298.5 |   260.2 |  -13%  ||   163.69 |   187.74 |  +15%  |  0.0000 |
 | 26      ||    349.6 |   344.9 |   -1%  ||   140.45 |   142.21 |   +1%  |  0.2816 |
 | 28      ||    227.4 |   229.4 |   +1%  ||   213.62 |   212.57 |   -0%  |  0.6167 |
 | 29      ||    233.8 |   230.5 |   -1%  ||   208.83 |   211.55 |   +1%  |  0.2329 |
 | 31      ||    927.2 |   936.1 |   +1%  ||    51.92 |    52.28 |   +1%  |  0.7569 |
 | 34      ||    165.4 |   163.7 |   -1%  ||   292.71 |   295.72 |   +1%  |  0.2066 |
 | 35      ||   1149.7 |  1140.9 |   -1%  ||    42.53 |    42.96 |   +1%  |  0.7686 |
 | 39a     ||   1992.9 |  1959.3 |   -2%  ||    24.22 |    24.78 |   +2%  |  0.6222 |
 | 39b     ||   2002.5 |  1964.6 |   -2%  ||    24.23 |    24.73 |   +2%  |  0.5269 |
 | 41      ||   1406.8 |  1349.7 |   -4%  ||    32.53 |    33.40 |   +3%  |  0.5092 |
+| 42      ||    125.6 |   116.0 |   -8%  ||   382.28 |   412.67 |   +8%  |  0.0000 |
 | 43      ||    840.9 |   837.4 |   -0%  ||    58.44 |    58.76 |   +1%  |  0.7907 |
 | 45      ||     72.3 |    71.2 |   -2%  ||   647.33 |   656.95 |   +1%  |  0.0108 |
 | 48      ||    624.5 |   621.8 |   -0%  ||    78.51 |    78.83 |   +0%  |  0.8505 |
 | 50      ||    159.6 |   158.2 |   -1%  ||   303.13 |   305.53 |   +1%  |  0.3780 |
 | 52      ||    116.8 |   115.9 |   -1%  ||   409.78 |   413.07 |   +1%  |  0.3576 |
 | 55      ||    114.9 |   115.7 |   +1%  ||   416.60 |   414.08 |   -1%  |  0.4503 |
 | 62      ||    408.1 |   401.5 |   -2%  ||   120.41 |   122.31 |   +2%  |  0.1484 |
 | 65      ||    797.4 |   782.1 |   -2%  ||    61.88 |    63.13 |   +2%  |  0.1556 |
 | 69      ||    207.3 |   204.4 |   -1%  ||   233.85 |   237.86 |   +2%  |  0.2631 |
 | 73      ||    120.5 |   119.5 |   -1%  ||   397.65 |   401.08 |   +1%  |  0.1871 |
 | 79      ||    308.1 |   303.8 |   -1%  ||   159.04 |   161.21 |   +1%  |  0.1737 |
 | 81      ||    178.5 |   175.5 |   -2%  ||   271.93 |   276.44 |   +2%  |  0.0292 |
 | 83      ||     84.2 |    83.3 |   -1%  ||   561.73 |   567.59 |   +1%  |  0.1371 |
 | 85      ||    333.6 |   325.9 |   -2%  ||   147.11 |   150.17 |   +2%  |  0.1249 |
 | 88      ||   1036.4 |  1033.6 |   -0%  ||    46.53 |    46.58 |   +0%  |  0.9548 |
 | 91      ||     96.3 |    96.0 |   -0%  ||   495.71 |   496.68 |   +0%  |  0.6274 |
 | 93      ||   1602.2 |  1577.3 |   -2%  ||    30.42 |    30.98 |   +2%  |  0.6226 |
 | 96      ||    140.5 |   142.1 |   +1%  ||   342.81 |   339.33 |   -1%  |  0.2244 |
 | 97      ||   4620.8 |  4494.2 |   -3%  ||    10.28 |    10.57 |   +3%  |  0.4267 |
 | 99      ||   1051.3 |  1032.9 |   -2%  ||    46.71 |    47.60 |   +2%  |  0.3115 |
 +---------++----------+---------+--------++----------+----------+--------+---------+
 | Sum     ||  24677.5 | 24193.9 |   -2%  ||          |          |        |         |
 | Geomean ||          |         |        ||          |          |   +2%  |         |
 +---------++----------+---------+--------++----------+----------+--------+---------+
```
</details>


**hyriseBenchmarkTPCC - single-threaded**
<details>
<summary>
Sum of avg. item runtimes: +0%
 ||
Geometric mean of throughput changes: +0%
</summary>

```diff
 +Configuration Overview-------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter        | /home/Markus.Dreseler/hyrise5/build-release/benchmark_all_results/hyriseBenchmarkTPCC_afa7559f02a5714bc2cea7c3b213840b1fdf01c3_st.json | /home/Markus.Dreseler/hyrise5/build-release/benchmark_all_results/hyriseBenchmarkTPCC_1c5715cbffb21ad6a89b2406d6f010072106a0b6_st.json |
 +------------------+----------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH        | afa7559f02a5714bc2cea7c3b213840b1fdf01c3-dirty                                                                                         | 1c5715cbffb21ad6a89b2406d6f010072106a0b6-dirty                                                                                         |
 |  benchmark_mode  | Shuffled                                                                                                                               | Shuffled                                                                                                                               |
 |  build_type      | release                                                                                                                                | release                                                                                                                                |
 |  chunk_size      | 65535                                                                                                                                  | 65535                                                                                                                                  |
 |  clients         | 1                                                                                                                                      | 1                                                                                                                                      |
 |  compiler        | gcc 9.2                                                                                                                                | gcc 9.2                                                                                                                                |
 |  cores           | 0                                                                                                                                      | 0                                                                                                                                      |
 |  date            | 2020-08-25 22:30:32                                                                                                                    | 2020-08-26 05:22:07                                                                                                                    |
 |  encoding        | {'default': {'encoding': 'Dictionary'}}                                                                                                | {'default': {'encoding': 'Dictionary'}}                                                                                                |
 |  indexes         | False                                                                                                                                  | False                                                                                                                                  |
 |  max_duration    | 60000000000                                                                                                                            | 60000000000                                                                                                                            |
 |  max_runs        | -1                                                                                                                                     | -1                                                                                                                                     |
 |  scale_factor    | 1                                                                                                                                      | 1                                                                                                                                      |
 |  time_unit       | ns                                                                                                                                     | ns                                                                                                                                     |
 |  using_scheduler | False                                                                                                                                  | False                                                                                                                                  |
 |  verify          | False                                                                                                                                  | False                                                                                                                                  |
 |  warmup_duration | 0                                                                                                                                      | 0                                                                                                                                      |
 +------------------+----------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+

 +--------------++----------+---------+--------++----------+----------+--------+----------------------+
 | Item         || Latency (ms/iter)  | Change || Throughput (iter/s) | Change |              p-value |
 |              ||      old |     new |        ||      old |      new |        |                      |
 +--------------++----------+---------+--------++----------+----------+--------+----------------------+
 | Delivery     ||     65.0 |    64.9 |   -0%  ||     2.02 |     2.05 |   +2%  | (run time too short) |
 | New-Order    ||     29.0 |    28.7 |   -1%  ||    22.70 |    22.75 |   +0%  | (run time too short) |
 | Order-Status ||      1.5 |     1.5 |   +3%  ||     2.03 |     2.01 |   -1%  | (run time too short) |
 | Payment      ||      3.4 |     3.4 |   -0%  ||    21.61 |    21.78 |   +1%  | (run time too short) |
 | Stock-Level  ||     67.1 |    67.9 |   +1%  ||     2.02 |     2.03 |   +1%  | (run time too short) |
 +--------------++----------+---------+--------++----------+----------+--------+----------------------+
 | Sum          ||    165.8 |   166.3 |   +0%  ||          |          |        |                      |
 | Geomean      ||          |         |        ||          |          |   +0%  |                      |
 +--------------++----------+---------+--------++----------+----------+--------+----------------------+
```
</details>


**hyriseBenchmarkTPCC - multi-threaded (50 clients)**
<details>
<summary>
Sum of avg. item runtimes: -1%
 ||
Geometric mean of throughput changes: -1%
</summary>

```diff
 +Configuration Overview---------+----------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                     | /home/Markus.Dreseler/hyrise5/build-release/benchmark_all_results/hyriseBenchmarkTPCC_afa7559f02a5714bc2cea7c3b213840b1fdf01c3_mt.json | /home/Markus.Dreseler/hyrise5/build-release/benchmark_all_results/hyriseBenchmarkTPCC_1c5715cbffb21ad6a89b2406d6f010072106a0b6_mt.json |
 +-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                     | afa7559f02a5714bc2cea7c3b213840b1fdf01c3-dirty                                                                                         | 1c5715cbffb21ad6a89b2406d6f010072106a0b6-dirty                                                                                         |
 |  benchmark_mode               | Shuffled                                                                                                                               | Shuffled                                                                                                                               |
 |  build_type                   | release                                                                                                                                | release                                                                                                                                |
 |  chunk_size                   | 65535                                                                                                                                  | 65535                                                                                                                                  |
 |  clients                      | 50                                                                                                                                     | 50                                                                                                                                     |
 |  compiler                     | gcc 9.2                                                                                                                                | gcc 9.2                                                                                                                                |
 |  cores                        | 0                                                                                                                                      | 0                                                                                                                                      |
 |  date                         | 2020-08-25 22:31:36                                                                                                                    | 2020-08-26 05:23:12                                                                                                                    |
 |  encoding                     | {'default': {'encoding': 'Dictionary'}}                                                                                                | {'default': {'encoding': 'Dictionary'}}                                                                                                |
 |  indexes                      | False                                                                                                                                  | False                                                                                                                                  |
 |  max_duration                 | 60000000000                                                                                                                            | 60000000000                                                                                                                            |
 |  max_runs                     | -1                                                                                                                                     | -1                                                                                                                                     |
 |  scale_factor                 | 1                                                                                                                                      | 1                                                                                                                                      |
 |  time_unit                    | ns                                                                                                                                     | ns                                                                                                                                     |
 |  using_scheduler              | True                                                                                                                                   | True                                                                                                                                   |
 |  utilized_cores_per_numa_node | [56, 0, 0, 0]                                                                                                                          | [56, 0, 0, 0]                                                                                                                          |
 |  verify                       | False                                                                                                                                  | False                                                                                                                                  |
 |  warmup_duration              | 0                                                                                                                                      | 0                                                                                                                                      |
 +-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+

 +--------------++----------+---------+--------++----------+----------+--------+----------------------+
 | Item         || Latency (ms/iter)  | Change || Throughput (iter/s) | Change |              p-value |
 |              ||      old |     new |        ||      old |      new |        |                      |
 +--------------++----------+---------+--------++----------+----------+--------+----------------------+
 | Delivery     ||    323.4 |   317.8 |   -2%  ||     2.97 |     3.04 |   +2%  | (run time too short) |
 |    unsucc.:  ||      3.9 |     4.1 |   +6%  ||    94.23 |    94.07 |   -0%  |                      |
 | New-Order    ||    142.9 |   140.2 |   -2%  ||    60.56 |    60.68 |   +0%  |               0.1791 |
 |    unsucc.:  ||      5.5 |     5.6 |   +2%  ||  1033.07 |  1031.36 |   -0%  |                      |
 | Order-Status ||      8.1 |     8.1 |   +0%  ||    97.22 |    97.11 |   -0%  | (run time too short) |
-| Payment      ||     15.2 |    16.7 |  +10%  ||     6.65 |     6.30 |   -5%  | (run time too short) |
 |    unsucc.:  ||      4.6 |     4.6 |   +1%  ||  1038.62 |  1037.43 |   -0%  |                      |
 | Stock-Level  ||    107.4 |   107.6 |   +0%  ||    97.06 |    96.92 |   -0%  |               0.8667 |
 +--------------++----------+---------+--------++----------+----------+--------+----------------------+
 | Sum          ||    597.1 |   590.4 |   -1%  ||          |          |        |                      |
 | Geomean      ||          |         |        ||          |          |   -1%  |                      |
 +--------------++----------+---------+--------++----------+----------+--------+----------------------+
```
</details>


**hyriseBenchmarkJoinOrder - single-threaded**
<details>
<summary>
Sum of avg. item runtimes: -3%
 ||
Geometric mean of throughput changes: +3%
</summary>

```diff
 +Configuration Overview------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter        | /home/Markus.Dreseler/hyrise5/build-release/benchmark_all_results/hyriseBenchmarkJoinOrder_afa7559f02a5714bc2cea7c3b213840b1fdf01c3_st.json | /home/Markus.Dreseler/hyrise5/build-release/benchmark_all_results/hyriseBenchmarkJoinOrder_1c5715cbffb21ad6a89b2406d6f010072106a0b6_st.json |
 +------------------+---------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH        | afa7559f02a5714bc2cea7c3b213840b1fdf01c3-dirty                                                                                              | 1c5715cbffb21ad6a89b2406d6f010072106a0b6-dirty                                                                                              |
 |  benchmark_mode  | Ordered                                                                                                                                     | Ordered                                                                                                                                     |
 |  build_type      | release                                                                                                                                     | release                                                                                                                                     |
 |  chunk_size      | 65535                                                                                                                                       | 65535                                                                                                                                       |
 |  clients         | 1                                                                                                                                           | 1                                                                                                                                           |
 |  compiler        | gcc 9.2                                                                                                                                     | gcc 9.2                                                                                                                                     |
 |  cores           | 0                                                                                                                                           | 0                                                                                                                                           |
 |  date            | 2020-08-25 23:08:20                                                                                                                         | 2020-08-26 05:24:17                                                                                                                         |
 |  encoding        | {'default': {'encoding': 'Dictionary'}}                                                                                                     | {'default': {'encoding': 'Dictionary'}}                                                                                                     |
 |  indexes         | False                                                                                                                                       | False                                                                                                                                       |
 |  max_duration    | 60000000000                                                                                                                                 | 60000000000                                                                                                                                 |
 |  max_runs        | -1                                                                                                                                          | -1                                                                                                                                          |
 |  time_unit       | ns                                                                                                                                          | ns                                                                                                                                          |
 |  using_scheduler | False                                                                                                                                       | False                                                                                                                                       |
 |  verify          | False                                                                                                                                       | False                                                                                                                                       |
 |  warmup_duration | 0                                                                                                                                           | 0                                                                                                                                           |
 +------------------+---------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+

 +---------++----------+----------+--------++----------+----------+--------+---------+
 | Item    || Latency (ms/iter)   | Change || Throughput (iter/s) | Change | p-value |
 |         ||      old |      new |        ||      old |      new |        |         |
 +---------++----------+----------+--------++----------+----------+--------+---------+
-| 10a     ||    337.0 |    355.1 |   +5%  ||     2.97 |     2.82 |   -5%  |  0.0000 |
 | 10b     ||    339.3 |    356.0 |   +5%  ||     2.95 |     2.81 |   -5%  |  0.0000 |
 | 10c     ||   1219.0 |   1179.4 |   -3%  ||     0.82 |     0.85 |   +3%  |  0.0000 |
 | 11a     ||    150.6 |    152.4 |   +1%  ||     6.64 |     6.56 |   -1%  |  0.2349 |
 | 11b     ||    140.3 |    142.5 |   +2%  ||     7.13 |     7.02 |   -2%  |  0.1162 |
+| 11c     ||    551.3 |    518.9 |   -6%  ||     1.81 |     1.93 |   +6%  |  0.0000 |
+| 11d     ||   5274.5 |   4691.4 |  -11%  ||     0.19 |     0.21 |  +12%  |  0.0000 |
 | 12a     ||    365.8 |    370.2 |   +1%  ||     2.73 |     2.70 |   -1%  |  0.1825 |
 | 12b     ||    597.9 |    627.0 |   +5%  ||     1.67 |     1.59 |   -5%  |  0.0000 |
-| 12c     ||   3542.9 |   3742.6 |   +6%  ||     0.28 |     0.27 |   -5%  |  0.0000 |
 | 13a     ||    171.5 |    171.1 |   -0%  ||     5.83 |     5.85 |   +0%  |  0.0464 |
+| 13b     ||    400.7 |    249.3 |  -38%  ||     2.50 |     4.01 |  +61%  |  0.0000 |
+| 13c     ||    287.3 |    136.3 |  -53%  ||     3.48 |     7.33 | +111%  |  0.0000 |
 | 13d     ||    171.5 |    171.4 |   -0%  ||     5.83 |     5.83 |   +0%  |  0.5678 |
 | 14a     ||   3867.9 |   4062.5 |   +5%  ||     0.26 |     0.25 |   -5%  |  0.0000 |
-| 14b     ||   4444.1 |   4684.0 |   +5%  ||     0.23 |     0.21 |   -5%  |  0.0000 |
 | 14c     ||   3867.2 |   4064.4 |   +5%  ||     0.26 |     0.25 |   -5%  |  0.0000 |
 | 15a     ||    225.9 |    231.2 |   +2%  ||     4.43 |     4.32 |   -2%  |  0.0002 |
 | 15b     ||    219.2 |    224.2 |   +2%  ||     4.56 |     4.46 |   -2%  |  0.0000 |
+| 15c     ||    168.4 |    153.9 |   -9%  ||     5.94 |     6.50 |   +9%  |  0.0000 |
+| 15d     ||    506.9 |    463.5 |   -9%  ||     1.97 |     2.16 |   +9%  |  0.0000 |
 | 16a     ||   4990.7 |   4775.6 |   -4%  ||     0.20 |     0.21 |   +5%  |  0.0350 |
+| 16b     ||   6809.8 |   6245.6 |   -8%  ||     0.15 |     0.16 |   +9%  |       ˅ |
+| 16c     ||   5171.3 |   4900.3 |   -5%  ||     0.19 |     0.20 |   +6%  |  0.0079 |
+| 16d     ||   5141.1 |   4893.7 |   -5%  ||     0.19 |     0.20 |   +5%  |  0.0010 |
 | 17a     ||   1016.7 |    985.4 |   -3%  ||     0.98 |     1.01 |   +3%  |  0.0000 |
 | 17b     ||    767.3 |    780.1 |   +2%  ||     1.30 |     1.28 |   -2%  |  0.0027 |
 | 17c     ||    721.1 |    736.2 |   +2%  ||     1.39 |     1.36 |   -2%  |  0.0002 |
 | 17d     ||    835.0 |    850.7 |   +2%  ||     1.20 |     1.18 |   -2%  |  0.0009 |
+| 17e     ||   3224.0 |   2949.3 |   -9%  ||     0.31 |     0.34 |   +9%  |  0.0000 |
 | 17f     ||   1667.9 |   1596.5 |   -4%  ||     0.60 |     0.63 |   +4%  |  0.0000 |
 | 18a     ||    686.9 |    674.0 |   -2%  ||     1.46 |     1.48 |   +2%  |  0.0307 |
 | 18b     ||    250.6 |    251.6 |   +0%  ||     3.99 |     3.97 |   -0%  |  0.4746 |
 | 18c     ||   3705.1 |   3781.8 |   +2%  ||     0.27 |     0.26 |   -2%  |  0.0508 |
+| 19a     ||   8595.7 |   7789.5 |   -9%  ||     0.12 |     0.13 |  +10%  |       ˅ |
+| 19b     ||   5368.5 |   4639.5 |  -14%  ||     0.19 |     0.22 |  +16%  |  0.0000 |
+| 19c     ||   8188.5 |   7535.3 |   -8%  ||     0.12 |     0.13 |   +9%  |       ˅ |
+| 19d     ||   6174.5 |   5765.5 |   -7%  ||     0.16 |     0.17 |   +7%  |  0.0000 |
+| 1a      ||     84.4 |     62.7 |  -26%  ||    11.85 |    15.95 |  +35%  |  0.0000 |
 | 1b      ||     23.1 |     23.2 |   +0%  ||    43.26 |    43.16 |   -0%  |  0.0013 |
 | 1c      ||     23.1 |     23.4 |   +1%  ||    43.22 |    42.81 |   -1%  |  0.0000 |
 | 1d      ||     22.7 |     23.1 |   +2%  ||    44.08 |    43.33 |   -2%  |  0.0000 |
+| 20a     ||   1396.8 |   1308.7 |   -6%  ||     0.72 |     0.76 |   +7%  |  0.0000 |
+| 20b     ||   1218.2 |   1134.5 |   -7%  ||     0.82 |     0.88 |   +7%  |  0.0000 |
+| 20c     ||   1256.7 |   1172.8 |   -7%  ||     0.80 |     0.85 |   +7%  |  0.0000 |
 | 21a     ||   3663.6 |   3847.0 |   +5%  ||     0.27 |     0.26 |   -5%  |  0.0000 |
 | 21b     ||    256.3 |    259.3 |   +1%  ||     3.90 |     3.86 |   -1%  |  0.0000 |
-| 21c     ||   3786.6 |   4029.3 |   +6%  ||     0.26 |     0.25 |   -6%  |  0.0000 |
-| 22a     ||   3313.7 |   3493.9 |   +5%  ||     0.30 |     0.29 |   -5%  |  0.0000 |
-| 22b     ||   3313.8 |   3498.8 |   +6%  ||     0.30 |     0.29 |   -5%  |  0.0000 |
-| 22c     ||   3907.8 |   4122.7 |   +5%  ||     0.26 |     0.24 |   -5%  |  0.0000 |
-| 22d     ||   3933.8 |   4200.9 |   +7%  ||     0.25 |     0.24 |   -6%  |  0.0000 |
+| 23a     ||    170.4 |    154.4 |   -9%  ||     5.87 |     6.48 |  +10%  |  0.0000 |
 | 23b     ||    120.5 |    118.6 |   -2%  ||     8.30 |     8.43 |   +2%  |  0.0000 |
+| 23c     ||    192.8 |    174.5 |  -10%  ||     5.19 |     5.73 |  +11%  |  0.0000 |
+| 24a     ||   5395.1 |   4709.5 |  -13%  ||     0.19 |     0.21 |  +15%  |  0.0000 |
+| 24b     ||   5320.3 |   4616.2 |  -13%  ||     0.19 |     0.22 |  +15%  |  0.0000 |
 | 25a     ||    249.3 |    252.2 |   +1%  ||     4.01 |     3.97 |   -1%  |  0.0072 |
 | 25b     ||    256.1 |    257.7 |   +1%  ||     3.90 |     3.88 |   -1%  |  0.0710 |
 | 25c     ||   3613.7 |   3772.7 |   +4%  ||     0.28 |     0.27 |   -4%  |  0.0000 |
+| 26a     ||   1083.8 |    994.5 |   -8%  ||     0.92 |     1.01 |   +9%  |  0.0000 |
+| 26b     ||   1076.0 |    988.1 |   -8%  ||     0.93 |     1.01 |   +9%  |  0.0000 |
+| 26c     ||   1084.7 |    995.0 |   -8%  ||     0.92 |     1.01 |   +9%  |  0.0000 |
 | 27a     ||   3327.7 |   3489.8 |   +5%  ||     0.30 |     0.29 |   -5%  |  0.0000 |
 | 27b     ||   3287.3 |   3454.7 |   +5%  ||     0.30 |     0.29 |   -5%  |  0.0000 |
 | 27c     ||    201.1 |    198.9 |   -1%  ||     4.97 |     5.03 |   +1%  |  0.1494 |
 | 28a     ||   3940.2 |   4104.7 |   +4%  ||     0.25 |     0.24 |   -4%  |  0.0706 |
 | 28b     ||   3222.0 |   3388.0 |   +5%  ||     0.31 |     0.30 |   -5%  |  0.0703 |
 | 28c     ||   3939.2 |   4106.5 |   +4%  ||     0.25 |     0.24 |   -4%  |  0.0630 |
+| 29a     ||   5316.6 |   4532.1 |  -15%  ||     0.19 |     0.22 |  +17%  |  0.0000 |
 | 29b     ||    194.2 |    192.3 |   -1%  ||     5.15 |     5.20 |   +1%  |  0.8404 |
+| 29c     ||   5388.1 |   4660.2 |  -14%  ||     0.19 |     0.21 |  +16%  |  0.0002 |
 | 2a      ||    105.9 |    105.1 |   -1%  ||     9.44 |     9.52 |   +1%  |  0.0000 |
 | 2b      ||     82.8 |     81.9 |   -1%  ||    12.07 |    12.21 |   +1%  |  0.0000 |
 | 2c      ||     53.1 |     52.7 |   -1%  ||    18.82 |    18.97 |   +1%  |  0.0000 |
 | 2d      ||    134.2 |    131.6 |   -2%  ||     7.45 |     7.60 |   +2%  |  0.0000 |
 | 30a     ||    265.8 |    266.5 |   +0%  ||     3.76 |     3.75 |   -0%  |  0.8936 |
 | 30b     ||   1064.6 |   1101.5 |   +3%  ||     0.94 |     0.91 |   -3%  |  0.0750 |
 | 30c     ||   3634.0 |   3793.6 |   +4%  ||     0.28 |     0.26 |   -4%  |  0.0419 |
 | 31a     ||    293.4 |    294.6 |   +0%  ||     3.41 |     3.39 |   -0%  |  0.6848 |
 | 31b     ||   1086.7 |   1123.1 |   +3%  ||     0.92 |     0.89 |   -3%  |  0.0036 |
 | 31c     ||    297.8 |    298.8 |   +0%  ||     3.36 |     3.35 |   -0%  |  0.7222 |
 | 32a     ||     38.1 |     37.2 |   -2%  ||    26.26 |    26.88 |   +2%  |  0.0000 |
 | 32b     ||    287.9 |    283.7 |   -1%  ||     3.47 |     3.53 |   +1%  |  0.0000 |
 | 33a     ||     72.5 |     71.7 |   -1%  ||    13.80 |    13.95 |   +1%  |  0.1038 |
 | 33b     ||     71.2 |     70.5 |   -1%  ||    14.04 |    14.19 |   +1%  |  0.0951 |
 | 33c     ||     87.1 |     86.1 |   -1%  ||    11.48 |    11.62 |   +1%  |  0.0797 |
 | 3a      ||   3778.6 |   3945.7 |   +4%  ||     0.26 |     0.25 |   -4%  |  0.0000 |
 | 3b      ||     35.7 |     35.0 |   -2%  ||    28.03 |    28.56 |   +2%  |  0.0000 |
 | 3c      ||   4885.0 |   5050.7 |   +3%  ||     0.20 |     0.20 |   -3%  |  0.0000 |
 | 4a      ||    133.7 |    127.7 |   -4%  ||     7.48 |     7.83 |   +5%  |  0.0000 |
 | 4b      ||     26.7 |     26.3 |   -1%  ||    37.51 |    38.03 |   +1%  |  0.0000 |
 | 4c      ||    150.5 |    144.7 |   -4%  ||     6.65 |     6.91 |   +4%  |  0.0000 |
 | 5a      ||   3607.0 |   3769.6 |   +5%  ||     0.28 |     0.27 |   -4%  |  0.0000 |
+| 5b      ||    289.2 |    274.1 |   -5%  ||     3.46 |     3.65 |   +6%  |  0.0000 |
 | 5c      ||   4228.1 |   4375.1 |   +3%  ||     0.24 |     0.23 |   -3%  |  0.0000 |
 | 6a      ||    245.1 |    247.9 |   +1%  ||     4.08 |     4.03 |   -1%  |  0.0000 |
 | 6b      ||    956.1 |    961.1 |   +1%  ||     1.05 |     1.04 |   -1%  |  0.0425 |
 | 6c      ||    245.2 |    248.5 |   +1%  ||     4.08 |     4.02 |   -1%  |  0.0000 |
 | 6d      ||    954.9 |    962.5 |   +1%  ||     1.05 |     1.04 |   -1%  |  0.0000 |
 | 6e      ||    245.1 |    248.1 |   +1%  ||     4.08 |     4.03 |   -1%  |  0.0000 |
 | 6f      ||   1546.5 |   1503.8 |   -3%  ||     0.65 |     0.66 |   +3%  |  0.0000 |
 | 7a      ||    278.4 |    265.6 |   -5%  ||     3.59 |     3.76 |   +5%  |  0.0000 |
 | 7b      ||    124.4 |    123.1 |   -1%  ||     8.04 |     8.12 |   +1%  |  0.3598 |
+| 7c      ||  12258.5 |  10917.2 |  -11%  ||     0.08 |     0.09 |  +12%  |       ˅ |
 | 8a      ||    108.5 |    105.2 |   -3%  ||     9.22 |     9.50 |   +3%  |  0.0000 |
+| 8b      ||    179.7 |    159.9 |  -11%  ||     5.57 |     6.25 |  +12%  |  0.0000 |
 | 8c      ||   4654.0 |   4443.3 |   -5%  ||     0.21 |     0.23 |   +5%  |  0.0000 |
 | 8d      ||   1599.8 |   1573.0 |   -2%  ||     0.63 |     0.64 |   +2%  |  0.0000 |
 | 9a      ||   3552.3 |   3444.9 |   -3%  ||     0.28 |     0.29 |   +3%  |  0.0000 |
+| 9b      ||    375.9 |    333.6 |  -11%  ||     2.66 |     3.00 |  +13%  |  0.0000 |
 | 9c      ||   3533.4 |   3465.5 |   -2%  ||     0.28 |     0.29 |   +2%  |  0.0006 |
 | 9d      ||   4173.8 |   4052.5 |   -3%  ||     0.24 |     0.25 |   +3%  |  0.0000 |
 +---------++----------+----------+--------++----------+----------+--------+---------+
 | Sum     || 223484.7 | 216861.7 |   -3%  ||          |          |        |         |
 | Geomean ||          |          |        ||          |          |   +3%  |         |
 +---------++----------+----------+--------++----------+----------+--------+---------+
 |         || ˅ Insufficient number of runs for p-value calculation                  |
 +---------++----------+----------+--------++----------+----------+--------+---------+
```
</details>


**hyriseBenchmarkJoinOrder - multi-threaded (50 clients)**
<details>
<summary>
Sum of avg. item runtimes: -4%
 ||
Geometric mean of throughput changes: +6%
</summary>

```diff
 +Configuration Overview---------+---------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
 | Parameter                     | /home/Markus.Dreseler/hyrise5/build-release/benchmark_all_results/hyriseBenchmarkJoinOrder_afa7559f02a5714bc2cea7c3b213840b1fdf01c3_mt.json | /home/Markus.Dreseler/hyrise5/build-release/benchmark_all_results/hyriseBenchmarkJoinOrder_1c5715cbffb21ad6a89b2406d6f010072106a0b6_mt.json |
 +-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
 |  GIT-HASH                     | afa7559f02a5714bc2cea7c3b213840b1fdf01c3-dirty                                                                                              | 1c5715cbffb21ad6a89b2406d6f010072106a0b6-dirty                                                                                              |
 |  benchmark_mode               | Ordered                                                                                                                                     | Ordered                                                                                                                                     |
 |  build_type                   | release                                                                                                                                     | release                                                                                                                                     |
 |  chunk_size                   | 65535                                                                                                                                       | 65535                                                                                                                                       |
 |  clients                      | 50                                                                                                                                          | 50                                                                                                                                          |
 |  compiler                     | gcc 9.2                                                                                                                                     | gcc 9.2                                                                                                                                     |
 |  cores                        | 0                                                                                                                                           | 0                                                                                                                                           |
 |  date                         | 2020-08-26 01:08:20                                                                                                                         | 2020-08-26 07:20:04                                                                                                                         |
 |  encoding                     | {'default': {'encoding': 'Dictionary'}}                                                                                                     | {'default': {'encoding': 'Dictionary'}}                                                                                                     |
 |  indexes                      | False                                                                                                                                       | False                                                                                                                                       |
 |  max_duration                 | 60000000000                                                                                                                                 | 60000000000                                                                                                                                 |
 |  max_runs                     | -1                                                                                                                                          | -1                                                                                                                                          |
 |  time_unit                    | ns                                                                                                                                          | ns                                                                                                                                          |
 |  using_scheduler              | True                                                                                                                                        | True                                                                                                                                        |
 |  utilized_cores_per_numa_node | [56, 0, 0, 0]                                                                                                                               | [56, 0, 0, 0]                                                                                                                               |
 |  verify                       | False                                                                                                                                       | False                                                                                                                                       |
 |  warmup_duration              | 0                                                                                                                                           | 0                                                                                                                                           |
 +-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+

 +---------++-----------+-----------+--------++----------+----------+--------+----------------------+
 | Item    || Latency (ms/iter)     | Change || Throughput (iter/s) | Change |              p-value |
 |         ||       old |       new |        ||      old |      new |        |                      |
 +---------++-----------+-----------+--------++----------+----------+--------+----------------------+
 | 10a     ||    3259.3 |    3293.9 |   +1%  ||    14.52 |    14.12 |   -3%  |               0.8415 |
 | 10b     ||    2555.0 |    2711.6 |   +6%  ||    17.93 |    17.86 |   -0%  |               0.1826 |
 | 10c     ||    9491.4 |    9494.4 |   +0%  ||     4.35 |     4.32 |   -1%  |               0.9967 |
 | 11a     ||     911.9 |     926.4 |   +2%  ||    52.86 |    52.68 |   -0%  |               0.6280 |
 | 11b     ||     881.3 |     889.1 |   +1%  ||    55.28 |    55.23 |   -0%  |               0.7828 |
+| 11c     ||    3666.2 |    2763.6 |  -25%  ||    12.48 |    16.93 |  +36%  |               0.0000 |
+| 11d     ||   46130.7 |   27824.8 |  -40%  ||     0.60 |     1.10 |  +83%  |               0.0000 |
 | 12a     ||    4000.9 |    3867.4 |   -3%  ||    11.90 |    11.80 |   -1%  |               0.5510 |
 | 12b     ||    1563.8 |    1515.0 |   -3%  ||    30.85 |    31.40 |   +2%  |               0.4375 |
+| 12c     ||   23814.1 |   25334.9 |   +6%  ||     1.25 |     1.33 |   +7%  |               0.4671 |
 | 13a     ||    1337.6 |    1332.9 |   -0%  ||    36.08 |    36.21 |   +0%  |               0.9237 |
+| 13b     ||    2197.9 |    1559.4 |  -29%  ||    21.41 |    30.93 |  +44%  |               0.0000 |
+| 13c     ||    2141.3 |    1543.4 |  -28%  ||    21.91 |    31.10 |  +42%  |               0.0000 |
 | 13d     ||    1380.6 |    1331.3 |   -4%  ||    35.33 |    36.65 |   +4%  |               0.3406 |
 | 14a     ||   21794.9 |   21612.8 |   -1%  ||     1.52 |     1.58 |   +4%  |               0.9165 |
 | 14b     ||   22845.8 |   20871.1 |   -9%  ||     1.45 |     1.48 |   +2%  |               0.2909 |
 | 14c     ||   22921.5 |   19672.3 |  -14%  ||     1.50 |     1.55 |   +3%  |               0.0668 |
 | 15a     ||    2030.7 |    1940.2 |   -4%  ||    23.58 |    24.15 |   +2%  |               0.2988 |
 | 15b     ||    1728.4 |    1696.7 |   -2%  ||    27.93 |    28.48 |   +2%  |               0.6302 |
 | 15c     ||     645.3 |     635.4 |   -2%  ||    75.73 |    77.34 |   +2%  |               0.5413 |
+| 15d     ||    3774.8 |    3090.1 |  -18%  ||    12.50 |    15.40 |  +23%  |               0.0001 |
+| 16a     ||   47028.9 |   37893.5 |  -19%  ||     0.47 |     0.70 |  +50%  |               0.0001 |
+| 16b     ||   53557.5 |   46150.9 |  -14%  ||     0.30 |     0.52 |  +72%  |               0.0001 |
+| 16c     ||   47525.2 |   36053.0 |  -24%  ||     0.45 |     0.70 |  +56%  |               0.0000 |
+| 16d     ||   48388.1 |   37992.5 |  -21%  ||     0.48 |     0.72 |  +48%  |               0.0000 |
+| 17a     ||    9821.2 |    8793.0 |  -10%  ||     4.32 |     4.80 |  +11%  |               0.1781 |
 | 17b     ||    8576.7 |    8651.2 |   +1%  ||     4.68 |     4.90 |   +5%  |               0.8945 |
 | 17c     ||    9232.3 |    8527.2 |   -8%  ||     4.77 |     4.65 |   -2%  |               0.2675 |
 | 17d     ||    9006.5 |    9790.9 |   +9%  ||     4.42 |     4.42 |   -0%  |               0.2521 |
+| 17e     ||   20768.7 |   15350.9 |  -26%  ||     1.73 |     2.53 |  +46%  |               0.0001 |
+| 17f     ||   12896.7 |   12503.7 |   -3%  ||     2.62 |     2.85 |   +9%  |               0.6510 |
 | 18a     ||    5282.0 |    4959.0 |   -6%  ||     7.98 |     8.33 |   +4%  |               0.2993 |
 | 18b     ||    2393.3 |    2184.0 |   -9%  ||    19.83 |    20.18 |   +2%  |               0.0909 |
 | 18c     ||   21133.2 |   20391.4 |   -4%  ||     1.57 |     1.58 |   +1%  |               0.6591 |
+| 19a     ||   44020.1 |   44530.8 |   +1%  ||     0.55 |     0.58 |   +6%  |               0.8356 |
 | 19b     ||   12832.5 |   10736.1 |  -16%  ||     3.00 |     3.03 |   +1%  |               0.0190 |
 | 19c     ||   42706.5 |   39305.9 |   -8%  ||     0.62 |     0.62 |   -0%  |               0.2237 |
+| 19d     ||   52999.3 |   45378.8 |  -14%  ||     0.47 |     0.50 |   +7%  |               0.0000 |
 | 1a      ||     406.7 |     392.7 |   -3%  ||   120.70 |   124.66 |   +3%  |               0.0491 |
 | 1b      ||      74.8 |      74.5 |   -0%  ||   625.53 |   628.79 |   +1%  |               0.5618 |
 | 1c      ||      78.3 |      78.2 |   -0%  ||   601.51 |   602.00 |   +0%  |               0.9459 |
 | 1d      ||      75.0 |      74.4 |   -1%  ||   623.58 |   629.22 |   +1%  |               0.2648 |
 | 20a     ||    8479.6 |    8029.3 |   -5%  ||     4.78 |     4.77 |   -0%  |               0.4543 |
 | 20b     ||    8587.2 |    9031.4 |   +5%  ||     4.78 |     4.93 |   +3%  |               0.5095 |
 | 20c     ||    8695.2 |    9614.4 |  +11%  ||     4.00 |     4.15 |   +4%  |               0.1558 |
+| 21a     ||   19954.2 |   18613.3 |   -7%  ||     1.60 |     1.68 |   +5%  |               0.4189 |
 | 21b     ||    1214.0 |    1209.4 |   -0%  ||    39.16 |    40.40 |   +3%  |               0.9170 |
 | 21c     ||   19749.7 |   18949.6 |   -4%  ||     1.65 |     1.70 |   +3%  |               0.6408 |
 | 22a     ||   21063.6 |   21487.0 |   +2%  ||     1.58 |     1.65 |   +4%  |               0.8200 |
 | 22b     ||   19267.0 |   19625.1 |   +2%  ||     1.62 |     1.67 |   +3%  |               0.8308 |
+| 22c     ||   20878.1 |   21835.8 |   +5%  ||     1.48 |     1.58 |   +7%  |               0.5896 |
+| 22d     ||   21902.4 |   20171.8 |   -8%  ||     1.48 |     1.58 |   +7%  |               0.3051 |
 | 23a     ||     538.1 |     523.9 |   -3%  ||    91.19 |    92.65 |   +2%  |               0.2712 |
 | 23b     ||    2358.7 |    2424.4 |   +3%  ||    19.68 |    19.65 |   -0%  |               0.6009 |
 | 23c     ||     633.7 |     601.0 |   -5%  ||    77.35 |    80.83 |   +5%  |               0.0290 |
 | 24a     ||   12803.1 |   13828.1 |   +8%  ||     2.62 |     2.67 |   +2%  |               0.3193 |
 | 24b     ||   11145.0 |   12971.3 |  +16%  ||     3.13 |     3.20 |   +2%  |               0.1058 |
 | 25a     ||    2440.3 |    2432.0 |   -0%  ||    19.80 |    19.41 |   -2%  |               0.9384 |
 | 25b     ||    2918.2 |    3000.2 |   +3%  ||    16.30 |    15.65 |   -4%  |               0.6198 |
 | 25c     ||   21752.5 |   19090.9 |  -12%  ||     1.53 |     1.55 |   +1%  |               0.1575 |
+| 26a     ||    3862.9 |    3422.2 |  -11%  ||    12.10 |    14.00 |  +16%  |               0.0271 |
+| 26b     ||    3782.5 |    3356.0 |  -11%  ||    12.48 |    13.95 |  +12%  |               0.0315 |
+| 26c     ||    3593.3 |    3364.0 |   -6%  ||    12.18 |    13.62 |  +12%  |               0.2674 |
 | 27a     ||   21303.8 |   18019.0 |  -15%  ||     1.62 |     1.65 |   +2%  |               0.0623 |
 | 27b     ||   19745.4 |   18825.3 |   -5%  ||     1.68 |     1.77 |   +5%  |               0.5727 |
 | 27c     ||    2682.1 |    2684.0 |   +0%  ||    17.73 |    17.68 |   -0%  |               0.9876 |
-| 28a     ||   23486.7 |   22383.5 |   -5%  ||     1.63 |     1.50 |   -8%  |               0.5538 |
 | 28b     ||   19607.4 |   19016.5 |   -3%  ||     1.70 |     1.75 |   +3%  |               0.7169 |
 | 28c     ||   19989.8 |   21293.2 |   +7%  ||     1.48 |     1.55 |   +4%  |               0.4370 |
+| 29a     ||   15072.5 |   11140.9 |  -26%  ||     2.62 |     3.25 |  +24%  |               0.0002 |
 | 29b     ||    2899.4 |    2874.5 |   -1%  ||    16.17 |    16.57 |   +2%  |               0.8784 |
 | 29c     ||   14989.4 |   15895.1 |   +6%  ||     2.38 |     2.45 |   +3%  |               0.4647 |
 | 2a      ||    1060.6 |    1048.2 |   -1%  ||    46.11 |    46.26 |   +0%  |               0.7352 |
 | 2b      ||    1198.4 |    1190.5 |   -1%  ||    40.98 |    40.77 |   -1%  |               0.8642 |
 | 2c      ||     788.1 |     794.3 |   +1%  ||    62.18 |    61.43 |   -1%  |               0.7812 |
 | 2d      ||    1039.2 |    1020.5 |   -2%  ||    47.15 |    47.78 |   +1%  |               0.5841 |
 | 30a     ||    2514.8 |    2507.7 |   -0%  ||    18.46 |    18.05 |   -2%  |               0.9501 |
 | 30b     ||    3025.7 |    2997.0 |   -1%  ||    15.30 |    15.37 |   +0%  |               0.8524 |
 | 30c     ||   22301.2 |   20518.2 |   -8%  ||     1.52 |     1.57 |   +3%  |               0.3252 |
 | 31a     ||    3703.2 |    3332.4 |  -10%  ||    12.38 |    12.46 |   +1%  |               0.0426 |
 | 31b     ||    3451.2 |    3321.8 |   -4%  ||    13.36 |    13.60 |   +2%  |               0.4720 |
 | 31c     ||    3538.8 |    3508.7 |   -1%  ||    13.33 |    13.35 |   +0%  |               0.8957 |
 | 32a     ||     137.3 |     138.9 |   +1%  ||   350.54 |   347.08 |   -1%  |               0.3081 |
 | 32b     ||    1650.6 |    1694.0 |   +3%  ||    29.26 |    28.47 |   -3%  |               0.3902 |
 | 33a     ||     400.3 |     391.7 |   -2%  ||   122.30 |   124.99 |   +2%  |               0.2262 |
 | 33b     ||     349.2 |     346.9 |   -1%  ||   140.48 |   141.30 |   +1%  |               0.7086 |
 | 33c     ||     450.1 |     442.5 |   -2%  ||   108.86 |   110.79 |   +2%  |               0.3762 |
+| 3a      ||   21755.2 |   22106.8 |   +2%  ||     1.55 |     1.63 |   +5%  |               0.8492 |
 | 3b      ||     794.3 |     795.1 |   +0%  ||    61.22 |    61.30 |   +0%  |               0.9739 |
 | 3c      ||   36672.8 |   37788.8 |   +3%  ||     0.80 |     0.78 |   -2%  |               0.6819 |
 | 4a      ||    1187.5 |    1168.6 |   -2%  ||    40.66 |    41.92 |   +3%  |               0.6362 |
 | 4b      ||     281.5 |     274.5 |   -2%  ||   173.48 |   178.05 |   +3%  |               0.1204 |
 | 4c      ||    1409.5 |    1415.3 |   +0%  ||    33.40 |    34.41 |   +3%  |               0.9082 |
+| 5a      ||   18958.3 |   18533.0 |   -2%  ||     1.75 |     1.85 |   +6%  |               0.7750 |
 | 5b      ||    1745.7 |    1724.5 |   -1%  ||    27.25 |    28.00 |   +3%  |               0.7791 |
+| 5c      ||   24374.7 |   22233.6 |   -9%  ||     1.37 |     1.48 |   +9%  |               0.2406 |
 | 6a      ||    5951.1 |    6110.8 |   +3%  ||     7.28 |     7.52 |   +3%  |               0.7329 |
 | 6b      ||    7366.8 |    7348.9 |   -0%  ||     5.55 |     5.40 |   -3%  |               0.9746 |
 | 6c      ||    5813.9 |    5527.3 |   -5%  ||     7.40 |     7.25 |   -2%  |               0.5003 |
 | 6d      ||    7835.1 |    7366.2 |   -6%  ||     5.32 |     5.40 |   +2%  |               0.3928 |
 | 6e      ||    5988.6 |    6141.2 |   +3%  ||     7.08 |     7.42 |   +5%  |               0.6785 |
 | 6f      ||    7975.3 |    7288.1 |   -9%  ||     5.55 |     5.72 |   +3%  |               0.1303 |
 | 7a      ||    3193.3 |    3135.0 |   -2%  ||    14.42 |    14.55 |   +1%  |               0.7089 |
 | 7b      ||    1858.9 |    1820.1 |   -2%  ||    25.68 |    26.53 |   +3%  |               0.6374 |
 | 7c      ||       nan |   55283.5 |        ||     0.00 |     0.07 | +nan%  | (run time too short) |
 | 8a      ||    2921.3 |    2707.5 |   -7%  ||    16.43 |    16.58 |   +1%  |               0.1062 |
 | 8b      ||    2353.3 |    2388.8 |   +2%  ||    20.22 |    20.00 |   -1%  |               0.7897 |
+| 8c      ||   31213.0 |   26120.4 |  -16%  ||     0.83 |     1.18 |  +42%  |               0.0250 |
 | 8d      ||   10854.5 |   11728.7 |   +8%  ||     3.33 |     3.43 |   +3%  |               0.3129 |
 | 9a      ||   26428.4 |   26993.3 |   +2%  ||     1.12 |     1.07 |   -4%  |               0.8095 |
 | 9b      ||    4204.3 |    4123.7 |   -2%  ||    10.90 |    11.17 |   +2%  |               0.7532 |
 | 9c      ||   29715.3 |   29389.9 |   -1%  ||     1.02 |     1.03 |   +2%  |               0.8915 |
+| 9d      ||   30841.2 |   29988.5 |   -3%  ||     0.98 |     1.03 |   +5%  |               0.6823 |
 +---------++-----------+-----------+--------++----------+----------+--------+----------------------+
 | Sum     || 1320574.7 | 1272187.9 |   -4%  ||          |          |        |                      |
+| Geomean ||           |           |        ||          |          |   +6%  |                      |
 +---------++-----------+-----------+--------++----------+----------+--------+----------------------+
```
</details>

**Comment by Bouncner** [comment]
How hard would it be to include the commit message of the commits? Would help me to see what this comparison is about (especially interesting when the post is two weeks old and I am too lacy to click on the commit).

If you don't think that makes sense: zündable.

**Review by Bouncner — APPROVED** [review]

**Comment by mrks** [comment]
**Commit Info and Build Time**
| commit | date | message |  build time |
| -- | -- | -- | -- |
| afa7559f0 | 24.08.2020 15:43 | Show absolute runtime sum in compare benchmarks script (#2091) | real 287.22 user 2552.80 sys 149.19|
| 1c5715cbf | 25.08.2020 20:17 | Add some scan shortcuts | real 286.31 user 2544.61 sys 152.38|

**Comment by julianmenzler** [comment]
What about the ToDo from above? ("Include TPCH SF 0.1")

**Comment by julianmenzler** [comment]
> What about the ToDo from above? ("Include TPCH SF 0.1")

Addressed with #2206
