### PR TITLE
Hyrise server

### LINKED ISSUE #853: ServerTest crashes memcheck sometimes (pqxx::connection_base::set_up_state())
I'm having this problem right now: https://ares.epic.hpi.uni-potsdam.de/jenkins/blue/organizations/jenkins/Hyrise%2Fhyrise/detail/refactor%2Ftable_statistics2/13/pipeline

any idea @lawben?

### LINKED ISSUE #1032: TSAN error in ~ClientConnection
https://gist.github.com/mrks/304cfb67b51cf63fe77ae33df47a64a0

### LINKED ISSUE #1182: TPC-H Query 10 fails in hyriseServer with SF=1
Probably because the result size is too big.

### LINKED ISSUE #1357: Boost asio occasionally fails in SystemTests
```
[ RUN      ] ServerTestRunner.TestParallelConnections
/usr/include/boost/asio/basic_io_object.hpp:212:15: runtime error: member call on address 0x60400005eb90 which does not point to an object of type 'boost::asio::stream_socket_service<boost::asio::ip::tcp>'
0x60400005eb90: note: object has invalid vptr
 0c 00 00 30  1e 00 80 53 00 00 00 00  20 dd a6 0a 00 00 00 00  00 00 00 00 00 00 00 00  30 42 02 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/include/boost/asio/basic_io_object.hpp:212:15 in 
script returned exit code 1
```

The same happens in ServerTestRunner.TestSimpleInsertSelect. I cannot reproduce it on nemea.

### PR DESCRIPTION
**Pull request by toniSta**
This PR introduces the new server implementation developed in the context of my master's thesis. Biggest change is the switch from async to sync operation using one thread per connection.

Fixes:
- fixes #1357, fixes #1032 both TSAN errors: ran system tests multiple time without any issue (both debug + release build)
- fixes #853 ASAN error: see above
- fixes #1182 result size too big: validated capability by transferring whole lineitem table at SF10

An option for server benchmarking in the existing benchmark runner will be introduced by a separate PR.

### CODE REVIEW

**Comment by tobodner** [comment]
Thanks for this PR, @toniSta. I will be able to look into this sometime end of next week.

File: src/bin/server.cpp [hunk 1]
```diff
@@ -1,36 +1,49 @@
...
+#include "tpch/tpch_table_generator.hpp"
+
+cxxopts::Options get_server_cli_options() {
+  cxxopts::Options cli_options("./hyriseServer", "Starts Hyrise Server in order to accept network requests.");
+
+  // clang-format off
+  cli_options.add_options()
+    ("help", "Display this help and exit")
+    ("p,port", "Specify the port number. 0 means randomly select an available one", cxxopts::value<uint16_t>()->default_value("5432"))  //NOLINT
+    ("generate_tpch", "Generate all TPC-H tables with specified scale factor (1.0 ~ 1GB)", cxxopts::value<float>()->default_value("0"))  //NOLINT
```
[the remark this answers is not in the document]
Comment (Bouncner) [reply src/bin/server.cpp]: Since we will probably have 4-5 benchmarks soon, should the generator (+ linked benchmarklib) really be part of the server?

File: src/bin/server.cpp [hunk 2]
```diff
@@ -1,36 +1,49 @@
...
+    ("debug_note", "Send operator runtimes to the client after statement execution", cxxopts::value<bool>()->default_value("false")) // NOLINT
```
Comment (Bouncner) [inline src/bin/server.cpp]: Seeing what you actually do with the `debug_note`, I don’t think it’s a good name.

File: src/lib/server/hyrise_communicator.cpp [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+#include "expression/value_expression.hpp"
+#include "hyrise.hpp"
+#include "sql/sql_pipeline.hpp"
+#include "sql/sql_pipeline_builder.hpp"
+#include "sql/sql_translator.hpp"
+
+namespace opossum {
+
+ExecutionInformation HyriseCommunicator::execute_pipeline(const std::string& sql, const bool debug_note) {
+  // A simple query command invalidates unnamed statements
```
Comment (Bouncner) [inline src/lib/server/hyrise_communicator.cpp]: I don’t get that.

File: src/lib/server/hyrise_communicator.cpp [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+    sql_pipeline->get_result_table();
+  } catch (const InvalidInputException& exception) {
+    execution_info.error = exception.what();
+    return execution_info;
+  }
+
+  const auto [pipeline_status, result_table] = sql_pipeline->get_result_table();
+  if (pipeline_status == SQLPipelineStatus::Success) {
+    execution_info.result_table = result_table;
+    execution_info.root_operator = sql_pipeline->get_physical_plans().front()->type();
```
Comment (Bouncner) [inline src/lib/server/hyrise_communicator.cpp]: What is the purpose of that `root_operator`?
Just curious and I cannot search right now (mobile).

File: src/lib/server/hyrise_communicator.cpp [hunk 5]
```diff
@@ -0,0 +1,111 @@
...
+  // Named prepared statements must be explicitly closed before they can be redefined by another Parse message
+  // https://www.postgresql.org/docs/10/static/protocol-flow.html
+  if (Hyrise::get().storage_manager.has_prepared_plan(statement_name)) {
+    AssertInput(statement_name.empty(),
+                "Named prepared statements must be explicitly closed before they can be redefined.");
+    Hyrise::get().storage_manager.drop_prepared_plan(statement_name);
+  }
+
+  auto pipeline_statement = SQLPipelineBuilder{query}.create_pipeline_statement();
+  auto sql_translator = SQLTranslator{UseMvcc::Yes};
```
Comment (Bouncner) [inline src/lib/server/hyrise_communicator.cpp]: `const`?

File: src/lib/server/hyrise_communicator.cpp [hunk 6]
```diff
@@ -0,0 +1,111 @@
...
+}
+
+std::pair<std::string, std::shared_ptr<AbstractOperator>> HyriseCommunicator::bind_prepared_plan(
+    const PreparedStatementDetails& statement_details) {
+  Assert(Hyrise::get().storage_manager.has_prepared_plan(statement_details.statement_name),
+         "The specified statement does not exist.");
+
+  const auto prepared_plan = Hyrise::get().storage_manager.get_prepared_plan(statement_details.statement_name);
+
+  if (statement_details.statement_name.empty()) {
```
Comment (Bouncner) [inline src/lib/server/hyrise_communicator.cpp]: What are you doing here with that conditional?

File: src/lib/server/hyrise_communicator.cpp [hunk 7]
```diff
@@ -0,0 +1,111 @@
...
+  std::shared_ptr<AbstractOperator> pqp;
+  std::string error = "";
+  try {
+    const auto lqp = prepared_plan->instantiate(parameter_expressions);
+    pqp = LQPTranslator{}.translate_node(lqp);
+  } catch (const std::exception& exception) {
+    error = exception.what();
+  }
+
+  return std::make_pair(error, pqp);
```
Comment (Bouncner) [inline src/lib/server/hyrise_communicator.cpp]: Could there be a better way than signaling errors via non-empty strings?

File: src/lib/server/hyrise_communicator.cpp [hunk 8]
```diff
@@ -0,0 +1,111 @@
...
+}
+
+std::shared_ptr<TransactionContext> HyriseCommunicator::get_new_transaction_context() {
+  return Hyrise::get().transaction_manager.new_transaction_context();
+}
+
+std::shared_ptr<const Table> HyriseCommunicator::execute_prepared_statement(
+    const std::shared_ptr<AbstractOperator>& physical_plan) {
+  std::shared_ptr<const Table> result_table;
```
Comment (Bouncner) [inline src/lib/server/hyrise_communicator.cpp]: 104 & 105: shouldn’t the compiler complain about unused variables?

File: src/lib/server/hyrise_communicator.hpp [hunk 9]
```diff
@@ -0,0 +1,34 @@
...
+namespace opossum {
+
+struct ExecutionInformation {
+  std::shared_ptr<const Table> result_table;
+  OperatorType root_operator;
+  std::string execution_information;
+  std::string error;
+};
+
+// This class manages the interaction between the server and the database component. Furthermore, most of the SQL based
```
Comment (Bouncner) [inline src/lib/server/hyrise_communicator.hpp]: SQL-based

File: src/lib/server/network_message_types.hpp [hunk 10]
```diff
@@ -1,7 +1,5 @@
 #pragma once
 
-namespace opossum {
```
Comment (Bouncner) [inline src/lib/server/network_message_types.hpp]: Why no name space?

File: src/lib/server/postgres_protocol_handler.cpp [hunk 11]
```diff
@@ -0,0 +1,277 @@
+#include "postgres_protocol_handler.hpp"
+
+#include "network_message_types.hpp"
+
+namespace opossum {
+
+static constexpr auto LENGTH_FIELD_SIZE = 4u;
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/postgres_protocol_handler.cpp]: Each message contains a field indicating the packet's size including itself. Hence, to get the payload's size we need to subtract this field's size. To avoid magic numbers I used `constexpr`. Gonna add a comment in the code.

File: src/bin/server.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (toniSta) [reply src/bin/server.cpp]: > Doesn’t it rather “include the info in the response” than “sending it”?
It's more like "send an extra message including operator execution information".

>  ... should the generator (+ linked benchmarklib) really be part of the server?
Included this for benchmarking purposes. However, you're right. Let's get rid of this.

File: src/bin/server.cpp [hunk 12]
```diff
@@ -1,36 +1,49 @@
...
-#include "utils/load_table.hpp"
+#include "tpch/tpch_table_generator.hpp"
+
+cxxopts::Options get_server_cli_options() {
+  cxxopts::Options cli_options("./hyriseServer", "Starts Hyrise Server in order to accept network requests.");
+
+  // clang-format off
+  cli_options.add_options()
+    ("help", "Display this help and exit")
+    ("p,port", "Specify the port number. 0 means randomly select an available one", cxxopts::value<uint16_t>()->default_value("5432"))  //NOLINT
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/bin/server.cpp]: I specified the default port in this line via `default_value("5432")`, so it will be automatically printed in the help text.

File: src/lib/server/hyrise_communicator.cpp (hunk 4 above)
Comment (toniSta) [reply src/lib/server/hyrise_communicator.cpp]: For the PostgreSQL protocol we need to find out the type of a statement, such as SELECT, INSERT, UPDATE, ...

File: src/lib/server/hyrise_communicator.cpp (hunk 5 above)
Comment (toniSta) [reply src/lib/server/hyrise_communicator.cpp]: Nope

File: src/lib/server/hyrise_communicator.cpp (hunk 8 above)
Comment (toniSta) [reply src/lib/server/hyrise_communicator.cpp]: I have no clue why ...

1. this is still there
2. the compiler isn't complaining

File: src/lib/server/hyrise_communicator.cpp (hunk 4 above)
Comment (Bouncner) [reply src/lib/server/hyrise_communicator.cpp]: Could you add a short comment to the hpp?

File: src/lib/server/hyrise_communicator.cpp (hunk 3 above)
Comment (toniSta) [reply src/lib/server/hyrise_communicator.cpp]: This is a PostgreSQL thing. The [documentation](https://www.postgresql.org/docs/11/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY) states:

> If successfully created, a named prepared-statement object lasts till the end of the current session, unless explicitly destroyed. An unnamed prepared statement lasts only until the next Parse statement specifying the unnamed statement as destination is issued. (Note that a simple Query message also destroys the unnamed statement.) Named prepared statements must be explicitly closed before they can be redefined by another Parse message, but this is not required for the unnamed statement. Named prepared statements can also be created and accessed at the SQL command level, using PREPARE and EXECUTE.

Gonna add a comment with a link to the documentation.

File: src/lib/server/hyrise_communicator.cpp (hunk 6 above)
Comment (toniSta) [reply src/lib/server/hyrise_communicator.cpp]: This is already done at parsing step. Removing this piece of code.

File: src/bin/server.cpp [hunk 13]
```diff
@@ -1,36 +1,42 @@
...
-#include <cstdio>
-#include <cstdlib>
-#include <iostream>
+#include "cxxopts.hpp"
 
 #include "hyrise.hpp"
 #include "scheduler/node_queue_scheduler.hpp"
 #include "server/server.hpp"
-#include "utils/load_table.hpp"
+#include "tpch/tpch_table_generator.hpp"
```
Comment (tobodner) [inline src/bin/server.cpp]: Please remove this. The server should be independent of benchmarks.

**Comment by Bouncner** [comment]
@toniSta : any idea why the tests are failing?

**Comment by toniSta** [comment]
> any idea why the tests are failing?
Tests are currently WIP.

**Comment by toniSta** [comment]
@tobodner 

>  It is related to PostgreSQL (https://www.postgresql.org/docs/current/protocol-message-formats.html) and this should be visible (in name and comments).

Agree.

> Alternatively, you could move the handler and the messages formats into a new subdirectory "postgres".

We can hardly distinguish between the Postgres protocol related and unrelated code because those mix up. For example, the `Session` contains the basic Postgres message flow, the buffer does byte conversion for integer types and so on. We would end up putting almost any file into this folder. Hence, in my opinion renaming the `network_message_types.hpp` should be the way to go.

File: src/lib/server/query_handler.hpp [hunk 14]
```diff
@@ -0,0 +1,38 @@
...
+  OperatorType root_operator;
+  std::string execution_information;
+  std::string error;
+};
+
+// This class manages the interaction between the server and the database component. Furthermore, most of the SQL-based
+// error handling happens in this class.
+class QueryHandler {
+ public:
+  static ExecutionInformation execute_pipeline(const std::string& sql, const bool debug_note);
```
Comment (tobodner) [inline src/lib/server/query_handler.hpp]: Align with above member name. Maybe metrics, since it boils down to the sql statement metrics/timings being collected? debug seems a little misleading.

File: src/bin/server.cpp [hunk 15]
```diff
@@ -1,36 +1,41 @@
...
 #include "server/server.hpp"
-#include "utils/load_table.hpp"
+
+cxxopts::Options get_server_cli_options() {
+  cxxopts::Options cli_options("./hyriseServer", "Starts Hyrise Server in order to accept network requests.");
+
+  // clang-format off
+  cli_options.add_options()
+    ("help", "Display this help and exit")
+    ("p,port", "Specify the port number. 0 means randomly select an available one", cxxopts::value<uint16_t>()->default_value("5432"))  //NOLINT
```
Comment (tobodner) [inline src/bin/server.cpp]: Add comment that this is PostgreSQL's official port assignment.

File: src/bin/server.cpp [hunk 16]
```diff
@@ -1,36 +1,41 @@
...
-#include <iostream>
+#include "cxxopts.hpp"
 
 #include "hyrise.hpp"
 #include "scheduler/node_queue_scheduler.hpp"
 #include "server/server.hpp"
-#include "utils/load_table.hpp"
+
+cxxopts::Options get_server_cli_options() {
+  cxxopts::Options cli_options("./hyriseServer", "Starts Hyrise Server in order to accept network requests.");
```
Comment (tobodner) [inline src/bin/server.cpp]: *server

File: src/bin/server.cpp [hunk 17]
```diff
@@ -1,36 +1,41 @@
...
-  // The server registers itself to the boost io_service. The io_service is the main IO control unit here and it lives
-  // until the server doesn't request any IO any more, i.e. is has terminated. The server requests IO in its
-  // constructor and then runs forever.
-  opossum::Server server{io_service, port};
+  const auto execution_info = parsed_options["execution_info"].as<bool>();
+  const auto port = parsed_options["port"].as<uint16_t>();
 
-  io_service.run();
+  auto server = opossum::Server{port, execution_info};
+  server.run();
```
Comment (tobodner) [inline src/bin/server.cpp]: Maybe first setup the server and only if this works, setup the scheduler.

File: src/bin/server.cpp (hunk 15 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/bin/server.cpp]: What for?

File: src/bin/server.cpp (hunk 17 above)
Comment (mrks) [reply src/bin/server.cpp]: Wouldn't that mean that you have to hold all connections until the scheduler is established?

File: src/bin/server.cpp (hunk 15 above)
[the remark this answers is not in the document]
Comment (tobodner) [reply src/bin/server.cpp]: For machines with multiple (virtual) NICs (common amongst servers).

File: src/bin/server.cpp (hunk 17 above)
Comment (tobodner) [reply src/bin/server.cpp]: Good point. Let's keep it this way.

File: src/lib/server/ring_buffer.hpp [hunk 18]
```diff
@@ -0,0 +1,182 @@
...
+static constexpr size_t BUFFER_SIZE = 4096u;
+
+// This class implements the logic of a circular buffer. If the end of the underlying data structure is reached
+// the iterator will start at the beginning if the data has already been processed.
+class RingBufferIterator : public std::iterator<std::forward_iterator_tag, char> {
+ public:
+  explicit RingBufferIterator(std::array<char, BUFFER_SIZE>& data, size_t position = 0)
+      : _data(data), _position(position) {}
+
+  RingBufferIterator& operator=(const RingBufferIterator& other) {
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/ring_buffer.hpp]: Generally, the iterators operate on the same object and the same data. In order to avoid misuse I'm gonna add a `DebugAssert`

File: src/lib/server/ring_buffer.hpp [hunk 19]
```diff
@@ -0,0 +1,182 @@
...
+  }
+
+  RingBufferIterator& operator+(const size_t increment) {
+    _position = (_position + increment) % BUFFER_SIZE;
+    return *this;
+  }
+
+  RingBufferIterator& operator+=(const size_t increment) { return operator+(increment); }
+
+  RingBufferIterator::difference_type operator-(RingBufferIterator const& other) const {
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/ring_buffer.hpp]: Gonna add a `DebugAssert` as well.

File: src/lib/server/session.cpp [hunk 20]
```diff
@@ -0,0 +1,187 @@
...
+  }
+}
+
+void Session::_establish_connection() {
+  const auto body_length = _postgres_protocol_handler->read_startup_packet();
+
+  // Currently, the information available in the start up packet body (such as db name, user name) is ignored
+  _postgres_protocol_handler->read_startup_packet_body(body_length);
+  _postgres_protocol_handler->send_authentication();
+  _postgres_protocol_handler->send_parameter("server_version", "11");
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/session.cpp]: Version 12 was release on October 3rd. I'm going to test the newest version

File: src/lib/server/ring_buffer.hpp [hunk 21]
```diff
@@ -0,0 +1,182 @@
...
+      : _data(data), _position(position) {}
+
+  RingBufferIterator& operator=(const RingBufferIterator& other) {
+    _position = other._position;
+    return *this;
+  }
+
+  RingBufferIterator(const RingBufferIterator& other) = default;
+
+  bool operator==(RingBufferIterator other) const { return (_position == other._position) && (_data == other._data); }
```
Comment (mrks) [inline src/lib/server/ring_buffer.hpp]: move entire code to cpp

File: src/lib/server/ring_buffer.hpp [hunk 22]
```diff
@@ -0,0 +1,182 @@
...
+  }
+
+  RingBufferIterator operator++(int) {
+    RingBufferIterator retval = *this;
+    ++(*this);
+    return retval;
+  }
+
+  RingBufferIterator& operator+(const size_t increment) {
+    _position = (_position + increment) % BUFFER_SIZE;
```
Comment (mrks) [inline src/lib/server/ring_buffer.hpp]: This does not look correct. `operator+` should be const, which would correctly complain that the current iterator should not be modified. boost's iterator_facade makes it easier to correctly implement iterators

File: src/lib/server/ring_buffer.hpp (hunk 19 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/server/ring_buffer.hpp]: (As a DebugAssert. If I remember correctly, comparing two iterators that are on different containers, is UB)

File: src/lib/server/ring_buffer.hpp [hunk 23]
```diff
@@ -0,0 +1,182 @@
...
+
+  // Flush whole buffer, e. g. after a finished request
+  void flush(const size_t bytes_required = 0);
+
+  // Put string into the buffer. If the string is longer than the buffer itself the buffer will flush automatically.
+  void put_string(const std::string& value, const bool terminate = true);
+
+  // Put numerical values into the buffer. Values will be converted into the correct byte order if necessary.
+  template <typename T, typename std::enable_if_t<std::is_same_v<uint32_t, T> || std::is_same_v<int32_t, T>, int> = 0>
+  void put_value(const T network_value) {
```
Comment (mrks) [inline src/lib/server/ring_buffer.hpp]: I wonder if this is easier to read and has less duplication if we work with `if constexpr` in a single implementation

File: src/lib/server/ring_buffer.cpp [hunk 24]
```diff
@@ -0,0 +1,183 @@
...
+
+template <typename SocketType>
+void WriteBuffer<SocketType>::_flush_if_necessary(const size_t bytes_required) {
+  if (bytes_required >= maximum_capacity() - size()) {
+    flush(bytes_required);
+  }
+}
+
+template class ReadBuffer<Socket>;
+template class ReadBuffer<boost::asio::posix::stream_descriptor>;
```
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/server/ring_buffer.cpp]: > macro

https://www.youtube.com/watch?v=umDr0mPuyQc

File: src/lib/server/ring_buffer.cpp [hunk 25]
```diff
@@ -0,0 +1,183 @@
...
+
+  // Socket was closed by client during execution
+  if (error_code == boost::asio::error::broken_pipe || error_code == boost::asio::error::connection_reset) {
+    // Terminate session by stopping the current thread
+    pthread_exit(nullptr);
+  } else if (error_code) {
+    std::cerr << error_code.category().name() << ": " << error_code.message() << std::endl;
+  }
+  _start_position += bytes_sent;
+}
```
Comment (mrks) [inline src/lib/server/ring_buffer.cpp]: Isn't this a case for `Assert`?

File: src/lib/server/response_builder.cpp [hunk 26]
```diff
@@ -0,0 +1,115 @@
...
+        object_id = 701;
+        type_width = 8;
+        break;
+      case DataType::String:
+        object_id = 25;
+        type_width = -1;
+        break;
+      default:
+        Fail("Bad DataType");
+    }
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/response_builder.cpp]: Comes from PostgreSQL itself, see [https://crate.io/docs/crate/reference/en/latest/interfaces/postgres.html](https://crate.io/docs/crate/reference/en/latest/interfaces/postgres.html). Adding a comment...

File: src/lib/server/response_builder.hpp [hunk 27]
```diff
@@ -0,0 +1,26 @@
...
+
+#include <memory>
+#include "operators/abstract_operator.hpp"
+#include "postgres_protocol_handler.hpp"
+#include "storage/table.hpp"
+
+namespace opossum {
+
+// The ResponseBuilder serializes the result data returned by Hyrise.
+class ResponseBuilder {
```
Comment (mrks) [inline src/lib/server/response_builder.hpp]: Naming: It looks like it also writes data. A builder should not modify external state.

File: src/lib/server/response_builder.hpp [hunk 28]
```diff
@@ -0,0 +1,26 @@
...
+ public:
+  template <typename SocketType>
+  static void build_and_send_row_description(
```
Comment (mrks) [inline src/lib/server/response_builder.hpp]: doc?

File: src/lib/server/server.hpp [hunk 29]
```diff
@@ -3,23 +3,31 @@
 #include <boost/asio/io_service.hpp>
 #include <boost/asio/ip/tcp.hpp>
 
-#include "server_session.hpp"
+#include "session.hpp"
 
 namespace opossum {
 
+// The server class is responsible for setting up and listening to the system port.
 class Server {
```
Comment (mrks) [inline src/lib/server/server.hpp]: I'm missing a short description of what components are part of the server and how they interact. This would be a good place to put that.

File: src/lib/server/response_builder.cpp [hunk 30]
```diff
@@ -0,0 +1,118 @@
...
+#include "lossy_cast.hpp"
+
+namespace opossum {
+
+template <typename SocketType>
+void ResponseBuilder::build_and_send_row_description(
+    std::shared_ptr<const Table> table,
+    const std::shared_ptr<PostgresProtocolHandler<SocketType>>& postgres_protocol_handler) {
+  // Calculate sum of length of all column names
+  uint32_t column_lengths_total = 0;
```
Comment (mrks) [inline src/lib/server/response_builder.cpp]: `column_name_length_sum`?

File: src/lib/server/postgres_protocol_handler.cpp [hunk 31]
```diff
@@ -0,0 +1,310 @@
...
+template <typename SocketType>
+void PostgresProtocolHandler<SocketType>::send_command_complete(const std::string& command_complete_message) {
+  const auto packet_size = sizeof(LENGTH_FIELD_SIZE) + command_complete_message.size() + 1u /* null terminator */;
+  _write_buffer.template put_value(PostgresMessageType::CommandComplete);
+  _write_buffer.template put_value<uint32_t>(static_cast<uint32_t>(packet_size));
+  _write_buffer.put_string(command_complete_message);
+}
+
+template <typename SocketType>
+void PostgresProtocolHandler<SocketType>::set_row_description_header(const uint32_t total_column_name_length,
```
Comment (mrks) [inline src/lib/server/postgres_protocol_handler.cpp]: Both this and `send_row_description` write to the output buffer, but one is called "set" and the other one "send"

File: src/lib/server/response_builder.cpp [hunk 32]
```diff
@@ -0,0 +1,118 @@
...
+      case DataType::Double:
+        object_id = 701;
+        type_width = 8;
+        break;
+      case DataType::String:
+        object_id = 25;
+        type_width = -1;
+        break;
+      default:
+        Fail("Bad DataType");
```
Comment (mrks) [inline src/lib/server/response_builder.cpp]: Don't add a default case so that the compiler complains about missing values.

File: src/lib/server/response_builder.cpp [hunk 33]
```diff
@@ -0,0 +1,118 @@
...
+    }
+    postgres_protocol_handler->send_row_description(table->column_name(column_id), object_id, type_width);
+  }
+}
+
+template <typename SocketType>
+void ResponseBuilder::build_and_send_query_response(
```
Comment (mrks) [inline src/lib/server/response_builder.cpp]: "build" seems superfluous here, as it is not an externally visible result of this method.

File: src/lib/server/response_builder.cpp [hunk 34]
```diff
@@ -0,0 +1,118 @@
...
+    std::shared_ptr<const Table> table,
+    const std::shared_ptr<PostgresProtocolHandler<SocketType>>& postgres_protocol_handler) {
+  auto attribute_strings = std::vector<std::optional<std::string>>(table->column_count());
+
+  const auto chunk_count = table->chunk_count();
+
+  // Iterate over each chunk in result table
+  for (ChunkID chunk_id{0}; chunk_id < chunk_count; chunk_id++) {
+    const auto chunk_size = table->get_chunk(chunk_id)->size();
+    const auto segments = table->get_chunk(chunk_id)->segments();
```
Comment (mrks) [inline src/lib/server/response_builder.cpp]: Get the chunk only once, don't copy `segments`

File: src/lib/server/response_builder.cpp [hunk 35]
```diff
@@ -0,0 +1,118 @@
...
+    // Iterate over each row in chunk
+    for (ChunkOffset current_chunk_offset{0}; current_chunk_offset < chunk_size; ++current_chunk_offset) {
+      auto string_lengths = 0;
```
Comment (mrks) [inline src/lib/server/response_builder.cpp]: Analogous to above: string_length_sum?

File: src/lib/server/response_builder.cpp [hunk 36]
```diff
@@ -0,0 +1,118 @@
...
+      // Iterate over each attribute in row
+      for (size_t current_segment = 0; current_segment < segments.size(); current_segment++) {
+        const auto attribute_value = segments[current_segment]->operator[](current_chunk_offset);
```
Comment (mrks) [inline src/lib/server/response_builder.cpp]: `(*segments[current_segment])[..]`

File: src/lib/server/response_builder.cpp [hunk 37]
```diff
@@ -0,0 +1,118 @@
...
+        const auto string_value = lossy_variant_cast<pmr_string>(attribute_value);
+        if (string_value.has_value()) {
+          // Sum up string lengths for a row to save an extra loop during serialization
+          string_lengths += string_value.value().size();
+        }
+        attribute_strings[current_segment] = std::move(string_value);
```
Comment (mrks) [inline src/lib/server/response_builder.cpp]: I haven't seen a comment explaining why we send everything as a string

File: src/lib/server/server.cpp [hunk 38]
```diff
@@ -1,40 +1,43 @@
...
 
-void Server::_start_session(boost::system::error_code error) {
+void Server::_start_session(const std::shared_ptr<Session>& new_session, const boost::system::error_code& error) {
   if (!error) {
-    auto connection = std::make_shared<ClientConnection>(std::move(_socket));
-    auto task_runner = std::make_shared<TaskRunner>(_io_service);
-    auto session = std::make_shared<ServerSession>(connection, task_runner);
-    // Start the session and release it once it has terminated
-    session->start() >> then >> [=]() mutable { session.reset(); };
+    std::thread session_thread([new_session] { new_session->start(); });
```
Comment (mrks) [inline src/lib/server/server.cpp]: I'm admittedly quite late to the party, but spawning an undefined number of threads outside of the scheduler does not seem right.

File: src/lib/server/server.cpp [hunk 39]
```diff
@@ -1,40 +1,43 @@
...
+    session_thread.detach();
+  } else {
+    std::cerr << error.category().name() << ": " << error.message() << std::endl;
```
Comment (mrks) [inline src/lib/server/server.cpp]: Why not assert?

File: src/test/server/server_test_runner.cpp [hunk 40]
```diff
@@ -126,7 +145,48 @@ TEST_F(/* #1357 */ DISABLED_ServerTestRunner, TestPreparedStatement) {
...
+  pqxx::connection connection{_connection_string};
+  pqxx::nontransaction transaction{connection};
+
+  const std::string prepared_name = "";
+  const auto param = 1234u;
+  // Ill-formed prepared statement
+  connection.prepare(prepared_name, "SELECT * FROM WHERE a > ?");
+  EXPECT_THROW(transaction.exec_prepared(prepared_name, param), pqxx::sql_error);
+
+  // // Well-formed but table does not exist
```
Comment (mrks) [inline src/test/server/server_test_runner.cpp]: Yo dawg, I heard you like comments.

File: src/test/server/server_test_runner.cpp [hunk 41]
```diff
@@ -23,62 +23,81 @@ class /* #1357 */ DISABLED_ServerTestRunner : public BaseTest {
...
   std::string _connection_string;
 
   std::shared_ptr<Table> _table_a;
 };
 
-TEST_F(/* #1357 */ DISABLED_ServerTestRunner, TestSimpleSelect) {
+TEST_F(ServerTestRunner, TestSimpleSelect) {
+  pqxx::connection connection{_connection_string};
+
+  // We use nontransactions because the regular transactions use SQL that we don't support. Nontransactions auto commit.
```
Comment (mrks) [inline src/test/server/server_test_runner.cpp]: Be more specific about what we do not support?

File: src/test/server/postgres_protocol_handler_test.cpp [hunk 42]
```diff
@@ -0,0 +1,300 @@
...
+  _mocked_socket->write(std::string{'\0', '\0', '\0', '\b', '\x04', '\xd2', '\x16', '\x2f'});
+  // Server will wait for new message with authentication details. Message contains length (12 B), protocol (0) and
+  // body (4 B). No body provided here, since we throw it away anyway.
+  _mocked_socket->write(std::string{'\0', '\0', '\0', '\f', '\0', '\0', '\0', '\0'});
+  EXPECT_EQ(_protocol_handler->read_startup_packet(), 4);
+  const std::string file_content = _mocked_socket->read();
+  EXPECT_EQ(file_content.back(), 'N');
+}
+
+TEST_F(PostgresProtocolHandlerTest, GetMessageType) {
```
[the remark this answers is not in the document]
Comment (mrks) [reply src/test/server/postgres_protocol_handler_test.cpp]: You mean sending an unknown message? That should be handled, but I don't think that we need a test for it.

File: src/test/server/response_builder_test.cpp [hunk 43]
```diff
@@ -0,0 +1,67 @@
...
+  void SetUp() override {
+    _test_table = load_table("resources/test_data/tbl/all_data_types_sorted.tbl", 2);
+    Hyrise::get().storage_manager.add_table("_test_table", _test_table);
+
+    _mocked_socket = std::make_shared<MockSocket>();
+    _protocol_handler =
+        std::make_shared<PostgresProtocolHandler<boost::asio::posix::stream_descriptor>>(_mocked_socket->get_socket());
+  }
+
+  uint32_t _get_message_length(std::string::const_iterator start) {
```
Comment (mrks) [inline src/test/server/response_builder_test.cpp]: Saw this before.

File: src/lib/server/ring_buffer.hpp [hunk 44]
```diff
@@ -0,0 +1,182 @@
...
+  PostgresMessageType get_message_type();
+
+ private:
+  std::shared_ptr<SocketType> _socket;
+  void _receive_if_necessary(const size_t bytes_required = 1);
+};
+
+// Dedicated buffer for write operations. The ring buffer gets extended by methods for writing different data types.
+template <typename SocketType>
+class WriteBuffer : public RingBuffer {
```
Comment (mrks) [inline src/lib/server/ring_buffer.hpp]: This is not inheritance. The WriteBuffer is not a special type of a RingBuffer, but does something completely different (talking to boost asio)

File: src/lib/server/ring_buffer.cpp [hunk 45]
```diff
@@ -0,0 +1,183 @@
+#include "ring_buffer.hpp"
+
+#include <pthread.h>
+#include <iostream>
+
+namespace opossum {
+
+template <typename SocketType>
+std::string ReadBuffer<SocketType>::get_string() {
```
Comment (mrks) [inline src/lib/server/ring_buffer.cpp]: Separate files

File: src/lib/server/ring_buffer.cpp (hunk 24 above)
[the remark this answers is not in the document]
Comment (tobodner) [reply src/lib/server/ring_buffer.cpp]: If @mrks has no reservations towards test-only code here, I do neither.

File: src/test/server/postgres_protocol_handler_test.cpp (hunk 42 above)
[the remark this answers is not in the document]
Comment (tobodner) [reply src/test/server/postgres_protocol_handler_test.cpp]: No hard feelings here, just figured what is there should also be properly tested.

File: src/lib/server/server.cpp (hunk 38 above)
Comment (tobodner) [reply src/lib/server/server.cpp]: @mrks Please note that the current implementation spawns an unbounded amount of threads as well. This new implementation does it in a (way) more sane way. We can talk about the unification in the scheduler and whether this needs to happen as part of this change.

File: src/bin/server.cpp [hunk 46]
```diff
@@ -1,36 +1,41 @@
...
 #include "hyrise.hpp"
 #include "scheduler/node_queue_scheduler.hpp"
 #include "server/server.hpp"
-#include "utils/load_table.hpp"
+
+cxxopts::Options get_server_cli_options() {
+  cxxopts::Options cli_options("./hyriseServer", "Starts Hyrise Server in order to accept network requests.");
+
+  // clang-format off
+  cli_options.add_options()
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/bin/server.cpp]: We figured out that the potential speed up by binding the server to a specific NUMA node is not that high (~7-10 %). As  I stated in my defense I wouldn't integrate that.

File: src/bin/server.cpp (hunk 15 above)
[the remark this answers is not in the document]
Comment (toniSta) [reply src/bin/server.cpp]: Good point. However, setting the port to 0 the makes the OS selecting a random port (not the application). The range can be set in `/proc/sys/net/ipv4/ip_local_port_range` (default: 40000 - 60999 [Ubuntu 19.04]). I'd like to continue using this OS functionality in order to avoid bloating the code.

File: src/lib/server/postgres_protocol_handler.cpp [hunk 47]
```diff
@@ -0,0 +1,305 @@
...
+  // The SSL deny packet has a special format. It does not have a field indicating the packet size.
+  _write_buffer.template put_value(PostgresMessageType::SslNo);
+  _write_buffer.flush();
+}
+
+template <typename SocketType>
+void PostgresProtocolHandler<SocketType>::read_startup_packet_body(const uint32_t size) {
+  // As of now, we don't do anything with the startup packet body. It contains authentication data and the
+  // database name the user desires to connect to. Hence, we read this information from the network device as
+  // one large string and throw it away.
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/postgres_protocol_handler.cpp]: Well that sounds more like a hack. However, I think I didn't get the idea behind this.

[the remark this answers is not in the document]
Comment (tobodner) [reply src/lib/server/postgres_protocol_handler.cpp]: Imagine a benchmark with two clients that each hold a connection and separately fire transactions. Now, if we collected performance-relevant metrics within Hyrise w.r.t. the transactions from client #1 vs client #2, how would we be able to distinguish  those? We could pass above information into the metrics utility.

[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/server/postgres_protocol_handler.cpp]: I think we should completely leave this out of this PR. It might be a workaround for a problem that we do not have yet, so even adding a TODO seems too much

File: src/lib/server/postgres_protocol_handler.cpp [hunk 48]
```diff
@@ -0,0 +1,310 @@
...
+// Each message contains a field (4 bytes) indicating the packet's size including itself. Using extra variable here to
+// avoid magic numbers.
+static constexpr auto LENGTH_FIELD_SIZE = 4u;
+
+template <typename SocketType>
+PostgresProtocolHandler<SocketType>::PostgresProtocolHandler(const std::shared_ptr<SocketType>& socket)
+    : _read_buffer(socket), _write_buffer(socket) {}
+
+template <typename SocketType>
+uint32_t PostgresProtocolHandler<SocketType>::read_startup_packet() {
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/postgres_protocol_handler.cpp]: It is the size of the startup packet's body which is limited to 2³² bytes. However, `read_startup_packet` suggests that this message is read completely which is not the case. Gonna rename this method...

File: src/lib/server/postgres_protocol_handler.cpp (hunk 47 above)
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/postgres_protocol_handler.cpp]: My first idea to distinguish two clients is the port. However, I agree with @mrks

File: src/lib/server/postgres_protocol_handler.hpp [hunk 49]
```diff
@@ -0,0 +1,62 @@
...
+namespace opossum {
+
+// This struct stores information about a prepared statements required for execution.
+struct PreparedStatementDetails {
+  std::string statement_name;
+  std::string portal;
+  std::vector<AllTypeVariant> parameters;
+};
+
+// This class implements the message handling according to the PostgreSQL Wire Protocol.
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/postgres_protocol_handler.hpp]: Correct.

File: src/lib/server/query_handler.cpp [hunk 50]
```diff
@@ -0,0 +1,107 @@
...
+    sql_pipeline->get_result_table();
+  } catch (const InvalidInputException& exception) {
+    execution_info.error = exception.what();
+    return execution_info;
+  }
+
+  const auto [pipeline_status, result_table] = sql_pipeline->get_result_table();
+  if (pipeline_status == SQLPipelineStatus::Success) {
+    execution_info.result_table = result_table;
+    execution_info.root_operator = sql_pipeline->get_physical_plans().front()->type();
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/query_handler.cpp]: We need to find out which type of statement we have (Insert, Update, ...). Therefore, we check the first operator's type.

[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/server/query_handler.cpp]: Are we sure that we have exactly one PQP? If yes, add an assertion. Also, I'd change `.front()` to `[0]`.

File: src/lib/server/response_builder.cpp (hunk 32 above)
Comment (toniSta) [reply src/lib/server/response_builder.cpp]: I get your point. This makes the compiler complain about `DataType::Bool` and  `DataType::Null`. The latter is not supported by the PostgreSQL protocol. However, both of them don't seem to be supported as a column's data type in Hyrise at all. How do we want to handle those column types?

Comment (mrks) [reply src/lib/server/response_builder.cpp]: Bool is gone anyway, for Null, we can continue to fail. It's just that I want the fail cases to be explicitly listed, not just defaulted

File: src/test/server/mock_socket.hpp [hunk 51]
```diff
@@ -0,0 +1,43 @@
+#pragma once
+
+#include <boost/asio.hpp>
+#include <filesystem>
+#include <fstream>
+
+namespace opossum {
+
+static constexpr char file_name[] = "socket_file";
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/test/server/mock_socket.hpp]: The read and write operations within the buffer require a file descriptor. Those methods are wrappers for the OS functions `read` and `write`. Since, I don't want to change the buffer implementation for testing I decided to use files instead of network sockets. My solution for parallel testing would be adding a uuid to the file name.

**Comment by mrks** [comment]
You'll ping me once I should re-review or if you have blocking questions, right?

**Comment by tobodner** [comment]
> You'll ping me once I should re-review or if you have blocking questions, right?

@toniSta is currently finishing up the last piece: Exception handling.

File: src/lib/server/session.cpp [hunk 52]
```diff
@@ -0,0 +1,187 @@
...
+  _postgres_protocol_handler->send_parameter("server_encoding", "UTF8");
+  _postgres_protocol_handler->send_parameter("client_encoding", "UTF8");
+  _postgres_protocol_handler->send_ready_for_query();
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/session.cpp]: In my opinion the protocol handler operates on a different level (packet level). What happens here is message flow. However, I agree: it doesn't look nice.

File: src/lib/server/server.cpp [hunk 53]
```diff
@@ -1,40 +1,43 @@
...
-void Server::_start_session(boost::system::error_code error) {
+void Server::_start_session(const std::shared_ptr<Session>& new_session, const boost::system::error_code& error) {
   if (!error) {
-    auto connection = std::make_shared<ClientConnection>(std::move(_socket));
-    auto task_runner = std::make_shared<TaskRunner>(_io_service);
-    auto session = std::make_shared<ServerSession>(connection, task_runner);
-    // Start the session and release it once it has terminated
-    session->start() >> then >> [=]() mutable { session.reset(); };
+    std::thread session_thread([new_session] { new_session->start(); });
+    session_thread.detach();
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/server.cpp]: > Name the threads for later threading behavior analysis

Agree.

> Have we seen any practical limits here?

Not yet.

File: src/lib/server/postgres_protocol_handler.cpp [hunk 54]
```diff
@@ -0,0 +1,310 @@
...
+   FROM: https://www.postgresql.org/docs/current/static/protocol-message-formats.html
+
+   String
+   The field name.
+
+   Int32
+   If the field can be identified as a column of a specific table, the object ID of the table; otherwise zero.
+
+   Int16
+   If the field can be identified as a column of a specific table, the attribute number of the column; otherwise zero.
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/postgres_protocol_handler.cpp]: The first field can contain the table ID (OID in postgres). The second might contain the attribute ID.
Don't know the practical use of it. ¯\_(ツ)_/¯

File: src/lib/server/ring_buffer.hpp [hunk 55]
```diff
@@ -0,0 +1,182 @@
...
+#include <boost/asio.hpp>  // NOLINT
+#include "postgres_message_types.hpp"
+
+namespace opossum {
+
+using Socket = boost::asio::ip::tcp::socket;
+
+static constexpr size_t BUFFER_SIZE = 4096u;
+
+// This class implements the logic of a circular buffer. If the end of the underlying data structure is reached
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/ring_buffer.hpp]: There are two reasons:

1.  It's not possible to read data into the buffer via `read` call. See [here](https://stackoverflow.com/a/48043427)

2. This buffer does only have a begin and an end pointer, no pointer to current position. Defining an own pointer for this leads to some ugly code when writing data. The internal methods `array_one` and `array_two` are useless in this case.

**Comment by toniSta** [comment]
I finished implementing the feedback. In the next days, I'm also gonna update Hyrise' wiki entry about networking especially covering the topics supported/unsupported operations and error handling

File: src/lib/server/postgres_protocol_handler.cpp (hunk 54 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/server/postgres_protocol_handler.cpp]: Add a comment explaining (a) whether we set it and (b) that we don’t know what it’s good for?

File: src/test/server/mock_socket.hpp (hunk 51 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/test/server/mock_socket.hpp]: Two options:
1. See the use of tmpname in abstract_visualizer.hpp (and how we delete the file and the string)
2. Opossum::test_data_path

I think the second one is easier and more consistent with other tests

[the remark this answers is not in the document]
Comment (toniSta) [reply src/test/server/mock_socket.hpp]: Second option seems reasonable. Does the file still need to have a unique name in this case (such as UUID in the file name)?

[the remark this answers is not in the document]
Comment (mrks) [reply src/test/server/mock_socket.hpp]: You may assume that there is only one test running in that folder, so unless you are using multiple mock sockets at the same time, you should be good.

[the remark this answers is not in the document]
Comment (toniSta) [reply src/test/server/mock_socket.hpp]: Good. I only need one mocked socket per test. Gonna remove this UUID stuff...

**Comment by mrks** [comment]
I'll try to do a hopefully final review tomorrow. Just answered some open points when I was on the bus earlier.

File: src/lib/server/session.cpp [hunk 56]
```diff
@@ -0,0 +1,200 @@
...
+  _establish_connection();
+  while (!_terminate_session) {
+    try {
+      _handle_request();
+    } catch (const std::exception& e) {
+      _postgres_protocol_handler->send_error_message(e.what());
+      _postgres_protocol_handler->send_ready_for_query();
+      // In order to avoid multiple ReadyForQuery in case of an error, we set this flag for further operations. As soon
+      // as a new query arrives it must be set to false again.
+      _sync_send_after_error = true;
```
Comment (mrks) [inline src/lib/server/session.cpp]: As a stand-alone comment, this is hard to understand. Any chance to add a sentence to make in clearer?

File: src/lib/server/session.cpp [hunk 57]
```diff
@@ -0,0 +1,200 @@
...
+  // Set TCP_NODELAY in order to disable Nagle's algorithm. It handles congestion control in TCP networks. Therefore,
+  // small packets are buffered and sent out later as one large packet. This might introduce a delay of up to 40 ms
+  // which we have to avoid. Further reading: https://howdoesinternetwork.com/2015/nagles-algorithm
+  _socket->set_option(boost::asio::ip::tcp::no_delay(true));
+  _establish_connection();
+  while (!_terminate_session) {
+    try {
+      _handle_request();
+    } catch (const std::exception& e) {
+      _postgres_protocol_handler->send_error_message(e.what());
```
Comment (mrks) [inline src/lib/server/session.cpp]: Maybe also print the error to `std::cerr`?

File: src/lib/server/session.hpp [hunk 58]
```diff
@@ -0,0 +1,53 @@
...
+  void _handle_simple_query();
+
+  // Parse prepared statement.
+  void _handle_parse_command();
+
+  // Bind prepared statement.
+  void _handle_bind_command();
+
+  // Send parameter and row description.
+  void _handle_describe();
```
Comment (mrks) [inline src/lib/server/session.hpp]: This seems to have lost its purpose

File: src/lib/server/session.cpp [hunk 59]
```diff
@@ -0,0 +1,200 @@
...
+
+  auto portal_it = _portals.find(portal_name);
+  Assert(portal_it != _portals.end(), "The specified portal does not exist.");
+
+  // In case of an error occured during binding there is no pqp available. Hence, early return here since there is
+  // nothing to execute.
+  if (!portal_it->second) {
+    _portals.erase(portal_it);
+    return;
+  }
```
Comment (mrks) [inline src/lib/server/session.cpp]: (1) Why isn't an empty portal an error, too?
(2) Use AssertInput?

File: src/lib/server/result_serializer.cpp [hunk 60]
```diff
@@ -0,0 +1,122 @@
...
+                                                               const std::shared_ptr<PostgresProtocolHandler<Socket>>&);
+
+template void ResultSerializer::send_table_description<boost::asio::posix::stream_descriptor>(
+    std::shared_ptr<const Table>,
+    const std::shared_ptr<PostgresProtocolHandler<boost::asio::posix::stream_descriptor>>&);
+
+template void ResultSerializer::send_query_response<Socket>(std::shared_ptr<const Table>,
+                                                            const std::shared_ptr<PostgresProtocolHandler<Socket>>&);
+
+template void ResultSerializer::send_query_response<boost::asio::posix::stream_descriptor>(
```
Comment (mrks) [inline src/lib/server/result_serializer.cpp]: "serialization is the process of translating data structures or object state into a format that can be stored or transmitted". The process of sending itself is not really the job of a serializer. Any idea for a dfferent name?

File: src/lib/server/result_serializer.cpp [hunk 61]
```diff
@@ -0,0 +1,122 @@
...
+    }
+    postgres_protocol_handler->send_row_description(table->column_name(column_id), object_id, type_width);
+  }
+}
+
+template <typename SocketType>
+void ResultSerializer::send_query_response(
+    std::shared_ptr<const Table> table,
+    const std::shared_ptr<PostgresProtocolHandler<SocketType>>& postgres_protocol_handler) {
+  auto attribute_strings = std::vector<std::optional<std::string>>(table->column_count());
```
Comment (mrks) [inline src/lib/server/result_serializer.cpp]: Copying my previous comment as I did not find where it was addressed:

I haven't seen a comment explaining why we send everything as a string

File: src/lib/server/read_buffer.cpp [hunk 62]
```diff
@@ -0,0 +1,120 @@
...
+    const auto substring_length = std::min(string_length - result.size(), maximum_capacity());
+    _receive_if_necessary(substring_length);
+    std::copy_n(_start_position, substring_length, std::back_inserter(result));
+    std::advance(_start_position, substring_length);
+  }
+
+  // Ignore last character if it is \0
+  if (ignore_null_terminator == IgnoreNullTerminator::No) {
+    result.pop_back();
+  }
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/read_buffer.cpp]: In some cases this looked confusing to me. However, this might still be less confusing than `IgnoreNullTerminator`.

File: src/lib/server/postgres_protocol_handler.cpp [hunk 63]
```diff
@@ -0,0 +1,266 @@
...
+  // Client asks for a description of a statement or a portal
+  // Statement descriptions (S) are returned as two separate messages: ParameterDescription and RowDescription
+  // Portal descriptions are just RowDescriptions
+  const auto description_target = _read_buffer.template get_value<char>();
+
+  Assert(description_target == 'P', "Only portal descriptions are currently supported.");
+
+  // The description itself will be sent out after execution of the prepared statement.
+  /* const auto statement_or_portal_name = */ _read_buffer.get_string(packet_length - LENGTH_FIELD_SIZE - sizeof(char));
+}
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/postgres_protocol_handler.cpp]: The client asks for a description of a statement or portal (== the layout of the result table). At this point, the LQP has been instantiated and translated but hasn't been executed yet. Since I found no way to retrieve the layout of the result table from the LQP I decided to do it after its execution. To answer your questions:

>  Does it modify the state somehow ...

No.

> ... how does it have an effect?

The message has to be read at some point. We also have to check if the client requests a statement description. If there's a way to solve the problem stated above I can implement the logic here.

File: src/lib/server/result_serializer.cpp (hunk 61 above)
Comment (toniSta) [reply src/lib/server/result_serializer.cpp]: I placed it here: https://github.com/hyrise/hyrise/blob/ae8948d6a5aaeb192994cd499056426b1847da3c/src/lib/server/result_serializer.cpp#L72

File: src/lib/server/result_serializer.cpp (hunk 60 above)
Comment (toniSta) [reply src/lib/server/result_serializer.cpp]: ResultHandler? ResultConverter? I'm out of ideas.

File: src/lib/server/write_buffer.hpp [hunk 64]
```diff
@@ -0,0 +1,60 @@
...
+#include <boost/asio.hpp>
+
+#include "ring_buffer_iterator.hpp"
+#include "types.hpp"
+
+using Socket = boost::asio::ip::tcp::socket;
+
+namespace opossum {
+
+// Dedicated buffer for write operations. The ring buffer gets extended by methods for writing different data types.
```
Comment (mrks) [inline src/lib/server/write_buffer.hpp]: The comment should explain that and when the buffer is flushed on inserts

Comment (mrks) [inline src/lib/server/write_buffer.hpp]: Please explain why read and write buffers are different

File: src/test/server/write_buffer_test.cpp [hunk 65]
```diff
@@ -0,0 +1,75 @@
...
+#include "base_test.hpp"
+#include "gtest/gtest.h"
+
+#include "mock_socket.hpp"
+
+#include "server/write_buffer.hpp"
+
+namespace opossum {
+
+class WriteBufferTest : public BaseTest {
```
Comment (mrks) [inline src/test/server/write_buffer_test.cpp]: Does this have something that triggers flush if necessary without an explicit flush?

File: src/lib/server/write_buffer.hpp [hunk 66]
```diff
@@ -0,0 +1,60 @@
...
+    }
+    std::copy_n(reinterpret_cast<const char*>(&converted_value), sizeof(T), _current_position);
+    std::advance(_current_position, sizeof(T));
+  }
+
+  // Put string into the buffer. If the string is longer than the buffer itself the buffer will flush automatically.
+  void put_string(const std::string& value, const HasNullTerminator has_null_terminator = HasNullTerminator::Yes);
+
+  // Flush whole buffer, e. g. after a finished request
+  void flush(const size_t bytes_required = 0);
```
Comment (mrks) [inline src/lib/server/write_buffer.hpp]: Please doc the parameter

File: src/lib/server/write_buffer.cpp [hunk 67]
```diff
@@ -0,0 +1,92 @@
...
+
+  boost::system::error_code error_code;
+  if (std::distance(&*_start_position, &*_current_position) < 0) {
+    // Data not continuously stored in buffer
+    bytes_sent =
+        boost::asio::write(*_socket,
+                           std::array<boost::asio::mutable_buffer, 2>{
+                               boost::asio::buffer(&*_start_position, std::distance(&*_start_position, _data.end())),
+                               boost::asio::buffer(_data.begin(), std::distance(_data.begin(), &*_current_position))},
+                           boost::asio::transfer_at_least(bytes_to_send), error_code);
```
Comment (mrks) [inline src/lib/server/write_buffer.cpp]: I don‘t get this yet. Bytes_to_send can be larger than size - how can I flush data that I don‘t have yet?

File: src/lib/server/ring_buffer_iterator.hpp [hunk 68]
```diff
@@ -0,0 +1,46 @@
+#pragma once
+
+#include <boost/iterator/iterator_facade.hpp>
+#include "utils/assert.hpp"
+
+namespace opossum {
+
+static constexpr size_t BUFFER_SIZE = 4096u;
```
Comment (mrks) [inline src/lib/server/ring_buffer_iterator.hpp]: SERVER_BUFFER_SIZE to avoid future name clashes?

File: src/lib/server/ring_buffer_iterator.hpp [hunk 69]
```diff
@@ -0,0 +1,46 @@
...
+
+// This class implements a circular buffer. If all data has been processed and the end of the underlying data
```
Comment (mrks) [inline src/lib/server/ring_buffer_iterator.hpp]: Implements an iteration on...?

File: src/lib/server/ring_buffer_iterator.hpp [hunk 70]
```diff
@@ -0,0 +1,46 @@
...
+
+  void increment() {  // NOLINT
+    _position = (_position + 1) % BUFFER_SIZE;
+  }
+
+  reference dereference() const {  // NOLINT
+    return _data[_position];
+  }
+
+  std::array<char, BUFFER_SIZE>& _data;
```
Comment (mrks) [inline src/lib/server/ring_buffer_iterator.hpp]: Can you make this reference const?

File: src/lib/server/read_buffer.hpp [hunk 71]
```diff
@@ -0,0 +1,59 @@
...
+  std::string get_string(const size_t string_length,
+                         const HasNullTerminator has_null_terminator = HasNullTerminator::Yes);
+  std::string get_string();
+
+ private:
+  void _receive_if_necessary(const size_t bytes_required = 1);
+
+  std::array<char, BUFFER_SIZE> _data;
+  RingBufferIterator _start_position{_data};
+  RingBufferIterator _current_position{_data};
```
Comment (mrks) [inline src/lib/server/read_buffer.hpp]: Could you doc these two positions, please? Same in WriteBuffer, if applicable

File: src/lib/server/read_buffer.cpp [hunk 72]
```diff
@@ -0,0 +1,120 @@
...
+  while (result.size() < string_length) {
+    const auto substring_length = std::min(string_length - result.size(), maximum_capacity());
+    _receive_if_necessary(substring_length);
+    std::copy_n(_start_position, substring_length, std::back_inserter(result));
+    std::advance(_start_position, substring_length);
+  }
+
+  // Ignore last character if it is \0
+  if (has_null_terminator == HasNullTerminator::Yes) {
+    result.pop_back();
```
Comment (mrks) [inline src/lib/server/read_buffer.cpp]: Assert that the popped value is \0?

File: src/lib/server/read_buffer.cpp [hunk 73]
```diff
@@ -0,0 +1,120 @@
...
+  } else {
+    bytes_read =
+        boost::asio::read(*_socket,
+                          std::array<boost::asio::mutable_buffer, 2>{
+                              boost::asio::buffer(&*_current_position, std::distance(&*_current_position, _data.end())),
+                              boost::asio::buffer(_data.begin(), std::distance(_data.begin(), &*_start_position - 1))},
+                          boost::asio::transfer_at_least(bytes_required - size()), error_code);
+  }
+
+  // Socket was closed by client during execution
```
Comment (mrks) [inline src/lib/server/read_buffer.cpp]: See comments in WriteBuffer

File: src/lib/server/session.cpp [hunk 74]
```diff
@@ -0,0 +1,205 @@
...
+  // Named portals must be explicitly closed before they can be redefined by another Bind message,
+  // but this is not required for the unnamed portal.
+  // https://www.postgresql.org/docs/10/static/protocol-flow.html
+  auto portal_it = _portals.find(parameters.portal);
+  if (portal_it != _portals.end()) {
+    AssertInput(parameters.portal.empty(), "Named portals must be explicitly closed before they can be redefined.");
+    _portals.erase(portal_it);
+  }
+
+  // Since describe and execute packet usually arrive together, we still have to handle the execute packet. Therefore,
```
Comment (mrks) [inline src/lib/server/session.cpp]: Are you sure you mean „describe“ here? Any chance this should read „bind“? Otherwise I am not fully understanding this.

File: src/test/server/server_test_runner.cpp [hunk 75]
```diff
@@ -12,7 +13,7 @@
 
 namespace opossum {
 
-class /* #1357 */ DISABLED_ServerTestRunner : public BaseTest {
+class ServerTestRunner : public BaseTest {
```
Comment (mrks) [inline src/test/server/server_test_runner.cpp]: Are you testing named portals anywhere?

File: src/lib/server/result_serializer.cpp (hunk 60 above)
Comment (mrks) [reply src/lib/server/result_serializer.cpp]: I gave it some more though too and couldn‘t come up with anything good either. Let‘s leave it.

File: src/lib/server/postgres_protocol_handler.cpp (hunk 63 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/server/postgres_protocol_handler.cpp]: > The description itself will be sent out after execution of the prepared statement.

Is this something that is independent of read_describe_packet? If yes, maybe add „in any case, ...“ and clarify that read_describe_packet has no effect.

If I am still mistaken, let‘s take this offline

File: src/lib/server/postgres_protocol_handler.cpp [hunk 76]
```diff
@@ -0,0 +1,265 @@
...
+  _write_buffer.template put_value(PostgresMessageType::AuthenticationRequest);
+  // Since we don't have any authentication mechanism, authentication is always successful
+  constexpr uint32_t authentication_successful = 0;
+  _write_buffer.template put_value<uint32_t>(sizeof(LENGTH_FIELD_SIZE) + sizeof(authentication_successful));
+  _write_buffer.template put_value<uint32_t>(authentication_successful);
+}
+
+template <typename SocketType>
+void PostgresProtocolHandler<SocketType>::send_parameter(const std::string& key, const std::string& value) {
+  const auto packet_size = sizeof(LENGTH_FIELD_SIZE) + key.size() + value.size() + 2u /* null terminator */;
```
Comment (tobodner) [inline src/lib/server/postgres_protocol_handler.cpp]: Same question as @mrks asked below: Why +2 and not +1? Are those two null terminators for the two strings?

File: src/lib/server/postgres_protocol_handler.cpp [hunk 77]
```diff
@@ -0,0 +1,266 @@
...
+  */
+  /*const auto max_rows = */ _read_buffer.template get_value<int32_t>();
+  return portal;
+}
+
+template <typename SocketType>
+void PostgresProtocolHandler<SocketType>::send_error_message(const std::string& error_message) {
+  _write_buffer.template put_value(PostgresMessageType::ErrorResponse);
+  const auto packet_size =
+      LENGTH_FIELD_SIZE + sizeof(PostgresMessageType) + error_message.size() + 2u /* null terminator */;
```
[the remark this answers is not in the document]
Comment (tobodner) [reply src/lib/server/postgres_protocol_handler.cpp]: See my comment on +2/+1 above. If this is wrong, our test is as well.

File: src/lib/server/postgres_protocol_handler.cpp [hunk 78]
```diff
@@ -0,0 +1,266 @@
...
+  // https://www.postgresql.org/docs/current/static/protocol-message-formats.html
+  _write_buffer.template put_value(PostgresMessageType::RowDescription);
+
+  // Total message length can be calculated this way:
+  // length field + column count + values for each column
+  const auto packet_size = sizeof(uint32_t) + sizeof(uint16_t) +
+                           column_count * (sizeof('\0') + 3 * sizeof(uint32_t) + 3 * sizeof(uint16_t)) +
+                           total_column_name_length;
+  _write_buffer.template put_value<uint32_t>(static_cast<uint32_t>(packet_size));
+  // Specifies the number of fields in a row (can be zero).
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/postgres_protocol_handler.cpp]: Took this from the PostgreSQL documentation. They seem to have tables without columns. Gonna remove `(can be zero)`

File: src/lib/server/postgres_protocol_handler.cpp (hunk 77 above)
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/postgres_protocol_handler.cpp]: Both the string and the whole are each terminated by a null terminator. The[ Postgres documentation](https://www.postgresql.org/docs/current/protocol-message-formats.html) states:
> The message body consists of one or more identified fields, followed by a zero byte as a terminator

The library `libpqxx` used in the integration does not seem to care about it. In contrast to this, `psql` does care.

File: src/lib/server/postgres_protocol_handler.cpp [hunk 79]
```diff
@@ -0,0 +1,266 @@
...
+  // We need an additional null terminator for this message
+  _write_buffer.template put_value('\0');
+  _write_buffer.flush();
+}
+
+template <typename SocketType>
+void PostgresProtocolHandler<SocketType>::send_execution_info(const std::string& execution_information) {
+  _write_buffer.template put_value(PostgresMessageType::Notice);
+  const auto packet_size =
+      LENGTH_FIELD_SIZE + sizeof(PostgresMessageType) + execution_information.size() + 2u /* null terminator */;
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/postgres_protocol_handler.cpp]: Same as above

File: src/lib/server/query_handler.cpp [hunk 80]
```diff
@@ -0,0 +1,85 @@
...
+    execution_info.root_operator = sql_pipeline.get_physical_plans().back()->type();
+
+    if (send_execution_info == SendExecutionInfo::Yes) {
+      std::stringstream stream;
+      stream << sql_pipeline.metrics();
+      execution_info.pipeline_metrics = stream.str();
+    }
+  } else {
+    const std::string failed_statement = sql_pipeline.failed_pipeline_statement()->get_sql_string();
+    execution_info.error = "Error during pipeline execution. Failed statement: " + failed_statement;
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/query_handler.cpp]: So what is the right way to handle this? Or is it just bad a name?

File: src/lib/server/read_buffer.hpp [hunk 81]
```diff
@@ -0,0 +1,59 @@
...
+    _receive_if_necessary(sizeof(T));
+    T network_value = 0;
+    std::copy_n(_start_position, sizeof(T), reinterpret_cast<char*>(&network_value));
+    std::advance(_start_position, sizeof(T));
+    if constexpr (std::is_same_v<T, uint16_t> || std::is_same_v<T, int16_t>) {
+      return ntohs(network_value);
+    } else if constexpr (std::is_same_v<T, uint32_t> || std::is_same_v<T, int32_t>) {
+      return ntohl(network_value);
+    } else {
+      return network_value;
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/read_buffer.hpp]: Actually, there is no need to support anything else than `char` since the protocol does not use other types.

File: src/test/server/write_buffer_test.cpp (hunk 65 above)
Comment (toniSta) [reply src/test/server/write_buffer_test.cpp]: This is covered by this test: https://github.com/hyrise/hyrise/blob/aa84e212c6d8d0be24639daa1f6ce8a9b5a2b77c/src/test/server/write_buffer_test.cpp#L68-L73

File: src/lib/server/ring_buffer_iterator.hpp (hunk 70 above)
Comment (toniSta) [reply src/lib/server/ring_buffer_iterator.hpp]: I'm returning references to the underlying data in `dereference()`. Does not seem to work with const references.

File: src/lib/server/session.cpp (hunk 74 above)
Comment (toniSta) [reply src/lib/server/session.cpp]: Yes, "describe" is wrong. Must be "bind".

File: src/lib/server/write_buffer.cpp (hunk 67 above)
Comment (toniSta) [reply src/lib/server/write_buffer.cpp]: You are right, that shouldn't be possible. Adding an Assert...

File: src/test/server/server_test_runner.cpp (hunk 75 above)
Comment (toniSta) [reply src/test/server/server_test_runner.cpp]: Portals are used for operating with cursors. Does Hyrise already support this?
[Here](https://www.postgresql.org/docs/10/protocol-overview.html#PROTOCOL-QUERY-CONCEPTS) is some documentation for this and [here](https://stackoverflow.com/questions/52479293/postgresql-refcursor-and-portal-name) you can find an example. Documentation for this is not that good.

File: src/lib/server/postgres_protocol_handler.cpp (hunk 76 above)
Comment (toniSta) [reply src/lib/server/postgres_protocol_handler.cpp]: Yes, added a comment for this.

File: src/lib/server/query_handler.cpp (hunk 80 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/server/query_handler.cpp]: Hmm, can you return SQL STATE 40001? That looks closest to what postgres is doing. Also please check for `SQLPipelineStatus::RolledBack` and change the text to "Transaction conflict, transaction was rolled back.".

File: src/lib/server/read_buffer.hpp (hunk 81 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/server/read_buffer.hpp]: Not sure if I can follow. Do you mean that the `else` path only needs `char`? If yes, that is something that you could static_assert so that no one uses something else.

File: src/test/server/write_buffer_test.cpp (hunk 65 above)
Comment (mrks) [reply src/test/server/write_buffer_test.cpp]: But here you call `_write_buffer->flush(); ` explicitly before you test something.

File: src/lib/server/ring_buffer_iterator.hpp (hunk 69 above)
Comment (mrks) [reply src/lib/server/ring_buffer_iterator.hpp]: Whoopsie, should have said "implements an iterator", sorry

File: src/lib/server/ring_buffer_iterator.hpp (hunk 70 above)
Comment (mrks) [reply src/lib/server/ring_buffer_iterator.hpp]: Ah, sure

File: src/test/server/server_test_runner.cpp (hunk 75 above)
Comment (mrks) [reply src/test/server/server_test_runner.cpp]: If they are untested and not unsupported, what is the advantage of having them in the code?

**Comment by mrks** [comment]
> Coverage — increased by 1.44 compared to master and is now 94.99% 

Nice!

File: src/lib/server/postgres_protocol_handler.cpp [hunk 82]
```diff
@@ -0,0 +1,266 @@
...
+  // one large string and throw it away.
+  _read_buffer.get_string(size, IgnoreNullTerminator::Yes);
+}
+
+template <typename SocketType>
+void PostgresProtocolHandler<SocketType>::send_authentication_response() {
+  _write_buffer.template put_value(PostgresMessageType::AuthenticationRequest);
+  // Since we don't have any authentication mechanism, authentication is always successful
+  constexpr uint32_t authentication_successful = 0;
+  _write_buffer.template put_value<uint32_t>(sizeof(LENGTH_FIELD_SIZE) + sizeof(authentication_successful));
```
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/server/postgres_protocol_handler.cpp]: I'm surprised that putting 4 or 8 here did not seem to make a difference. Do you have an idea on why that might be more or less ignored?

[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/postgres_protocol_handler.cpp]: `std::cout << sizeof(LENGTH_FIELD_SIZE) << std::endl;` prints `4`. So the value itself was correct.

File: src/lib/server/read_buffer.hpp (hunk 81 above)
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/read_buffer.hpp]: Correct. Added a static_assert for this.

File: src/test/server/write_buffer_test.cpp (hunk 65 above)
Comment (toniSta) [reply src/test/server/write_buffer_test.cpp]: Got your point. Gonna add an explicit EXPECT before `flush`.

File: src/test/server/server_test_runner.cpp (hunk 75 above)
Comment (toniSta) [reply src/test/server/server_test_runner.cpp]: I took this code from the old server implementation. Since there is no support for cursors removing all portal related code should be the way to go.

File: src/lib/server/query_handler.cpp (hunk 80 above)
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/query_handler.cpp]: Returning SQL codes that can be used by clients (such as psql) would require to implement another error message format. In order to keep the code clear I'd stick to the string solution.

You are referring to transactions. Does this (`SQLPipelineStatus::RolledBack`) only happen within a transaction context? So far the server does not support transactions since the parser doesn't understand "begin", "commit" and "rollback".

[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/server/query_handler.cpp]: > So far the server does not support transactions since the parser doesn't understand "begin", "commit" and "rollback".

Every SQL Pipeline uses transactions unless they have been explicitly disabled. Otherwise, we could not perform any data modifications. If no transaction context has been supplied to the builder, one is started for each statement:

https://github.com/hyrise/hyrise/blob/90aaf912a1fdeb335417ae09b9e5a9b95d1c80b3/src/lib/sql/sql_pipeline_statement.cpp#L144

> You are referring to transactions. Does this (SQLPipelineStatus::RolledBack) only happen within a transaction context?

Yes. Running a statements without a transaction context is only legal for read-only statements; those are guaranteed to not conflict.

> Returning SQL codes that can be used by clients (such as psql) would require to implement another error message format. In order to keep the code clear I'd stick to the string solution.

Once we execute multiple modifying statements concurrently (e.g., in the Bachelor's project), we will definitely run into that issue. This is very different from an actual error as a transaction conflict is something that is unwanted but expected. As such, we should not have to resort to string parsing to distinguish conflicts from actual errors.

Can you estimate how much of a change this is? I don't want to burden you with this - if it is more than a couple of lines, we can add it as a todo. In that case, maybe you could outline what needs to happen?

[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/query_handler.cpp]: Thanks for the explanation. Shouldn't be too difficult, since this is documented. Gonna have a look at this tomorrow.

File: src/test/server/server_test_runner.cpp (hunk 75 above)
Comment (mrks) [reply src/test/server/server_test_runner.cpp]: Weird. Can we add that to the documentation and the tests?

File: src/lib/server/result_serializer.hpp [hunk 83]
```diff
@@ -0,0 +1,29 @@
+#pragma once
+
+#include <memory>
+#include "operators/abstract_operator.hpp"
+#include "postgres_protocol_handler.hpp"
+#include "storage/table.hpp"
+
+namespace opossum {
+
+// The ResultSerializer serializes the result data returned by Hyrise.
```
Comment (tobodner) [inline src/lib/server/result_serializer.hpp]: according to PostgreSQL Wire Protocol.

File: src/lib/server/result_serializer.cpp [hunk 84]
```diff
@@ -0,0 +1,122 @@
...
+        object_id = 700;
+        type_width = 4;
+        break;
+      case DataType::Double:
+        object_id = 701;
+        type_width = 8;
+        break;
+      case DataType::String:
+        object_id = 25;
+        type_width = -1;
```
Comment (tobodner) [inline src/lib/server/result_serializer.cpp]: Where did you find these values?

File: src/lib/server/result_serializer.cpp [hunk 85]
```diff
@@ -0,0 +1,122 @@
...
+  // Iterate over each chunk in result table
+  for (ChunkID chunk_id{0}; chunk_id < chunk_count; chunk_id++) {
+    const auto& current_chunk = table->get_chunk(chunk_id);
+    const auto chunk_size = current_chunk->size();
+    const auto& segments = current_chunk->segments();
+    // Iterate over each row in chunk
+    for (ChunkOffset current_chunk_offset{0}; current_chunk_offset < chunk_size; ++current_chunk_offset) {
+      auto string_length_sum = 0;
+      // Iterate over each attribute in row
+      for (size_t current_segment = 0; current_segment < segments.size(); current_segment++) {
```
Comment (tobodner) [inline src/lib/server/result_serializer.cpp]: segment_id?

File: src/lib/server/ring_buffer_iterator.hpp [hunk 86]
```diff
@@ -0,0 +1,47 @@
+#pragma once
+
+#include <boost/iterator/iterator_facade.hpp>
+#include "utils/assert.hpp"
+
+namespace opossum {
+
+static constexpr size_t SERVER_BUFFER_SIZE = 4096u;
+
+// This class implements an iteration on an array to let it behave like a circular buffer. If all data has been
```
Comment (tobodner) [inline src/lib/server/ring_buffer_iterator.hpp]: iterator

File: src/lib/server/ring_buffer_iterator.hpp [hunk 87]
```diff
@@ -0,0 +1,47 @@
...
+// beginning of the data structure.
+class RingBufferIterator : public boost::iterator_facade<RingBufferIterator, char, std::forward_iterator_tag, char&> {
+ public:
+  explicit RingBufferIterator(std::array<char, SERVER_BUFFER_SIZE>& data, size_t position = 0)
+      : _data(data), _position(position) {}
+
+  RingBufferIterator(const RingBufferIterator&) = default;
+
+  RingBufferIterator& operator=(const RingBufferIterator& other) {
+    DebugAssert(&_data == &other._data, "Can't convert iterators from different arrays");
```
Comment (tobodner) [inline src/lib/server/ring_buffer_iterator.hpp]: Cannot

File: src/lib/server/server.cpp [hunk 88]
```diff
@@ -1,40 +1,55 @@
...
+  _acceptor.async_accept(*(new_session->socket()),
+                         boost::bind(&Server::_start_session, this, new_session, boost::asio::placeholders::error));
+}
 
-  _accept_next_connection();
+void Server::_start_session(const std::shared_ptr<Session>& new_session, const boost::system::error_code& error) {
+  Assert(!error, error.message());
+
+  std::thread session_thread([new_session] {
+    const std::string thread_name = "port_" + std::to_string(new_session->socket()->remote_endpoint().port());
```
Comment (tobodner) [inline src/lib/server/server.cpp]: Maybe, server_port to make more explicit from which component the thread comes from.

File: src/test/CMakeLists.txt [hunk 89]
```diff
@@ -128,10 +128,12 @@ set(
...
     scheduler/scheduler_test.cpp
-    server/mock_connection.hpp
-    server/mock_task_runner.hpp
-    server/postgres_wire_handler_test.cpp
-    server/server_session_test.cpp
+    server/mock_socket.hpp
+    server/postgres_protocol_handler_test.cpp
+    server/query_handler_test.cpp
+    server/result_serializer_test.cpp
+    server/read_buffer_test.cpp
```
Comment (tobodner) [inline src/test/CMakeLists.txt]: Nit picky: Order.

File: src/test/server/server_test_runner.cpp [hunk 90]
```diff
@@ -23,62 +24,86 @@ class /* #1357 */ DISABLED_ServerTestRunner : public BaseTest {
...
   std::string _connection_string;
 
   std::shared_ptr<Table> _table_a;
 };
 
-TEST_F(/* #1357 */ DISABLED_ServerTestRunner, TestSimpleSelect) {
+TEST_F(ServerTestRunner, TestSimpleSelect) {
+  pqxx::connection connection{_connection_string};
+
+  // We use nontransactions because the regular transactions use "begin" and "commit" keywords that we don't support.
```
Comment (tobodner) [inline src/test/server/server_test_runner.cpp]: do not

File: src/lib/server/postgres_protocol_handler.cpp [hunk 91]
```diff
@@ -0,0 +1,270 @@
...
+  _write_buffer.template put_value('\0');
+  _write_buffer.flush();
+}
+
+template <typename SocketType>
+void PostgresProtocolHandler<SocketType>::send_execution_info(const std::string& execution_information) {
+  _write_buffer.template put_value(PostgresMessageType::Notice);
+  // Message has 2 null terminators: one terminates the error string, the other one terminates the message
+  const auto packet_size =
+      LENGTH_FIELD_SIZE + sizeof(PostgresMessageType) + execution_information.size() + 2u /* null terminator */;
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/postgres_protocol_handler.cpp]: Moving comment from line 248 above line 250 looks weird in the middle of a variable assignment.

File: src/lib/server/server.cpp (hunk 88 above)
Comment (toniSta) [reply src/lib/server/server.cpp]: According to the [documentation](http://man7.org/linux/man-pages/man3/pthread_setname_np.3.html) of `pthread_setname_np` (linux) the length is restricted to 16 chars including the null terminator.

File: src/lib/server/result_serializer.cpp (hunk 84 above)
Comment (toniSta) [reply src/lib/server/result_serializer.cpp]: Run the query `select oid, typlen, typname from pg_catalog.pg_type order by oid;` in PostgreSQL. The types and oids are not well documented.

File: src/lib/server/query_handler.cpp [hunk 92]
```diff
@@ -0,0 +1,84 @@
...
+
+void QueryHandler::setup_prepared_plan(const std::string& statement_name, const std::string& query) {
+  // Named prepared statements must be explicitly closed before they can be redefined by another Parse message.
+  // An unnamed prepared statement lasts only until the next Parse statement specifying the unnamed statement as
+  // destination is issued
+  // https://www.postgresql.org/docs/11/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY
+  if (Hyrise::get().storage_manager.has_prepared_plan(statement_name)) {
+    AssertInput(statement_name.empty(),
+                "Named prepared statements must be explicitly closed before they can be redefined.");
+    Hyrise::get().storage_manager.drop_prepared_plan(statement_name);
```
[the remark this answers is not in the document]
Comment (toniSta) [reply src/lib/server/query_handler.cpp]: We drop it here since it is specified in the postgres message protocol.

File: src/lib/server/postgres_protocol_handler.cpp [hunk 93]
```diff
@@ -0,0 +1,270 @@
...
+  }
+
+  return {statement_name, portal, parameter_values};
+}
+
+template <typename SocketType>
+std::string PostgresProtocolHandler<SocketType>::read_execute_packet() {
+  const auto packet_length = _read_buffer.template get_value<uint32_t>();
+  const auto portal = _read_buffer.get_string(packet_length - 2 * sizeof(uint32_t));
+  /* https://www.postgresql.org/docs/11/protocol-flow.html:
```
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/server/postgres_protocol_handler.cpp]: Saw this too late, but using `current` makes no sense to me. Unless you have found a way in which the Hyrise code automatically updates to a Postgres 13 specification, we should link to the version that we actually used as a base.

File: src/lib/server/session.cpp [hunk 94]
```diff
@@ -107,7 +108,10 @@ void Session::_handle_simple_query() {
   const auto execution_information = QueryHandler::execute_pipeline(query, _send_execution_info);
 
   if (!execution_information.error.empty()) {
-    _postgres_protocol_handler->send_error_message(execution_information.error);
+    const auto error_message = ErrorMessage{{PostgresMessageType::HumanReadableError, execution_information.error},
+                                            {PostgresMessageType::SqlstateCodeError,
+                                             std::to_string(static_cast<uint32_t>(ErrorCode::TransactionRolledBack))}};
+    _postgres_protocol_handler->send_error_message(error_message);
```
Comment (mrks) [inline src/lib/server/session.cpp]: How do we know that this is a rollback?

File: src/lib/server/query_handler.cpp [hunk 95]
```diff
@@ -37,7 +36,7 @@ void QueryHandler::setup_prepared_plan(const std::string& statement_name, const
   // Named prepared statements must be explicitly closed before they can be redefined by another Parse message.
   // An unnamed prepared statement lasts only until the next Parse statement specifying the unnamed statement as
   // destination is issued
-  // https://www.postgresql.org/docs/11/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY
+  // https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY
```
Comment (mrks) [inline src/lib/server/query_handler.cpp]: Use 12 (as written above)

File: src/lib/server/postgres_protocol_handler.hpp [hunk 96]
```diff
@@ -7,6 +7,8 @@
 
 namespace opossum {
 
+typedef std::unordered_map<PostgresMessageType, std::string> ErrorMessage;
```
Comment (mrks) [inline src/lib/server/postgres_protocol_handler.hpp]: [using is better than typedef](https://www.internalpointers.com/post/differences-between-using-and-typedef-modern-c)

File: src/lib/server/postgres_message_type.hpp [hunk 97]
```diff
@@ -50,4 +51,9 @@ enum class TransactionStatusIndicator : unsigned char {
   InFailedTransactionBlock = 'e'
 };
 
+// SQL error codes
+enum class ErrorCode : uint32_t {
+  TransactionRolledBack = 40001,
```
Comment (mrks) [inline src/lib/server/postgres_message_type.hpp]: A rollback could also occur as a result of the user aborting the transaction. The "error" here is TransactionConflict.

File: src/lib/server/postgres_protocol_handler.cpp (hunk 93 above)
[the remark this answers is not in the document]
Comment (tobodner) [reply src/lib/server/postgres_protocol_handler.cpp]: Agreed. 12 is better than 'current'.

File: src/lib/server/postgres_protocol_handler.cpp (hunk 91 above)
[the remark this answers is not in the document]
Comment (tobodner) [reply src/lib/server/postgres_protocol_handler.cpp]: On line 250, so /* null terminatorS */ ?

File: src/lib/server/server.cpp (hunk 88 above)
Comment (tobodner) [reply src/lib/server/server.cpp]: Then, maybe server_pXXXXX (my preference) or server_p_XXXXX? I believe that there is value in fully stating the component for debugging.

File: src/lib/server/postgres_message_type.hpp (hunk 97 above)
Comment (tobodner) [reply src/lib/server/postgres_message_type.hpp]: The data type for error codes in PostgreSQL is actually five characters: https://www.postgresql.org/docs/current/errcodes-appendix.html Which code would transaction conflict be?

Comment (mrks) [reply src/lib/server/postgres_message_type.hpp]: Good catch. It's still 40001 (serialization_failure), but should be sent as a string.

Comment (tobodner) [reply src/lib/server/postgres_message_type.hpp]: Let's try to support the error codes with letters from the get to. Otherwise, we need to change data types here once we add one (including potential pitfalls).

File: src/lib/server/server.cpp (hunk 88 above)
Comment (toniSta) [reply src/lib/server/server.cpp]: server_p_XXXXX should be fine.

File: src/lib/server/postgres_message_type.hpp (hunk 97 above)
Comment (toniSta) [reply src/lib/server/postgres_message_type.hpp]: Enum classes only support integral data types. So switching to std::map is the way to go?

Comment (tobodner) [reply src/lib/server/postgres_message_type.hpp]: An alternative would be this enum class + a helper function (with switch case for translation). I am not sure, whether (1) performance is important here and (2) the map would hurt us. It is probably a little nicer to read since less redundant.

Comment (mrks) [reply src/lib/server/postgres_message_type.hpp]: I don't see us adding too many more error codes. If it makes it any easier, a constexpr char* should be fine, too.

Comment (tobodner) [reply src/lib/server/postgres_message_type.hpp]: OK. That's OK with me, too.

File: src/lib/server/session.cpp (hunk 94 above)
Comment (tobodner) [reply src/lib/server/session.cpp]: It looks as if PostgreSQL does not enforce any particular execution_info format - it is just a plain string message. So, how about splitting the error field into two fields 'error code' and 'error message'. They can be set separately in the query handler, where we want the condition to have an additional 'otherwise/unknown' case. Here we check for the error code and act accordingly.

File: src/lib/server/session.cpp [hunk 98]
```diff
@@ -107,11 +107,8 @@ void Session::_handle_simple_query() {
 
   const auto execution_information = QueryHandler::execute_pipeline(query, _send_execution_info);
 
-  if (!execution_information.error.empty()) {
-    const auto error_message = ErrorMessage{{PostgresMessageType::HumanReadableError, execution_information.error},
-                                            {PostgresMessageType::SqlstateCodeError,
-                                             std::to_string(static_cast<uint32_t>(ErrorCode::TransactionRolledBack))}};
-    _postgres_protocol_handler->send_error_message(error_message);
+  if (!execution_information.error_message.empty()) {
+    _postgres_protocol_handler->send_error_message(execution_information.error_message);
```
Comment (tobodner) [inline src/lib/server/session.cpp]: Not exactly what I had in mind, but OK this way.

**Comment by Bensk1** [comment]
Does this directly affect the performance (in a positive way)? Are there any numbers/graphs we could put here for documentation?

**Comment by tobodner** [comment]
> Does this directly affect the performance (in a positive way)? Are there any numbers/graphs we could put here for documentation?

Currently, our benchmark runner does not include the network/server. So, our usual benchmark plumbing does not show any difference (neither positive nor negative).
We are working on including the network-path as an option to the benchmark runner. For now, we refer to Toni's Master's thesis. In a set of measurements against the prior server implementation, we saw 560X lower latency and 44X higher throughput.

**Comment by tobodner** [comment]
> Yes, it does. I'm gonna update the [networking wiki page](https://github.com/hyrise/hyrise/wiki/Networking) anyway. Is that something we should put there?

IMO, most readers are just interested in the status quo, not how things evolved over time.

**Comment by Bensk1** [comment]
> Currently, our benchmark runner does not include the network/server. So, our usual benchmark plumbing does not show any difference (neither positive nor negative).
> We are working on including the network-path as an option to the benchmark runner. For now, we refer to Toni's Master's thesis. In a set of measurements against the prior server implementation, we saw 560X lower latency and 44X higher throughput.

Okay, I didn't specifically talk about our typical benchmarks, any numbers are fine. The latency and throughputs you posted are already something. 

For the wiki page, I agree on referring to Toni's thesis.
