### PR TITLE
Fix Multi-threading support for Insert

### LINKED ISSUE #1086: Multithreaded inserts lead to ChunkID out of range
Example: Connect twice to the server and run multiple inserts simultaneously.

Error: Table throws ChunkID out of range.

Insert.cpp has following code:
```
    // while target chunk is not full
    while (target_start_index != target_chunk->size()) {
      const auto source_chunk = input_table_left()->get_chunk(source_chunk_id);

      ...

      bool source_chunk_depleted = source_chunk_start_index == source_chunk->size();
      if (source_chunk_depleted) {
        source_chunk_id++;
        source_chunk_start_index = 0u;
      }
```

If the target_chunk is expanded during an insertion, the while loop doesn't stop and a chunk from input_table_left is requested that does not exist.

Hotfix: 

 In the while loop there is 
```
still_to_insert -= num_to_insert;
```
which indicates the remaining number of rows that have to be inserted. Break the loop if all rows have been inserted:
```
still_to_insert -= num_to_insert;
if (still_to_insert <= 0) {
   break;
}
```

### PR DESCRIPTION
**Pull request by mrzzzrm**
...and general cleanup. The Insert code is now much more pleasant to read.

Also, fix #1086 

Here is the playground that I used to "test" whether multi-threaded insert works:

```c++
#include <atomic>
#include <iostream>
#include <thread>

#include "operators/print.hpp"
#include "sql/sql_pipeline_builder.hpp"
#include "storage/storage_manager.hpp"
#include "storage/table.hpp"
#include "types.hpp"

using namespace opossum;               // NOLINT
using namespace std::string_literals;  // NOLINT

int main() {
  const auto table =
      std::make_shared<Table>(TableColumnDefinitions{{"a", DataType::Int}}, TableType::Data, 5, UseMvcc::Yes);
  //table->add_unique_constraint({ColumnID{0}}, false);

  StorageManager::get().add_table("T0", table);

  std::atomic<int32_t> global_variable{0};

  std::vector<std::thread> threads;

  for (size_t t{0}; t < 10; ++t) {
    threads.emplace_back([&global_variable, t]() {
      while (global_variable.load() < 50) {
        const auto query = "INSERT INTO T0 VALUES("s + std::to_string(global_variable.load()) + ")";

        auto statement = SQLPipelineBuilder{query}.dont_cleanup_temporaries().create_pipeline_statement();
        statement.get_result_table();

        if (t == 0) global_variable++;
      }
    });
  }

  for (auto& thread : threads) thread.join();

  Print::print(table);

  return 0;
}
```

### CODE REVIEW

File: src/lib/operators/insert.cpp [hunk 1]
```diff
@@ -8,94 +8,80 @@
...
 template <typename T>
-class TypedSegmentProcessor : public AbstractTypedSegmentProcessor {
- public:
-  void resize_vector(std::shared_ptr<BaseSegment> segment, size_t new_size) override {
-    auto value_segment = std::dynamic_pointer_cast<ValueSegment<T>>(segment);
-    DebugAssert(value_segment, "Cannot insert into non-ValueColumns");
-    auto& values = value_segment->values();
+void resize_value_segment(std::shared_ptr<BaseSegment> segment, size_t new_size) {
+  const auto value_segment = std::dynamic_pointer_cast<ValueSegment<T>>(segment);
+  Assert(value_segment, "Cannot insert into non-ValueColumns");
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: Haha, I just thought about refactoring an hour ago and how the column-to-segment thing was largely without complications...

File: src/lib/operators/insert.cpp [hunk 2]
```diff
@@ -8,94 +8,80 @@
...
+using namespace opossum;  // NOLINT
 
 template <typename T>
-class TypedSegmentProcessor : public AbstractTypedSegmentProcessor {
- public:
-  void resize_vector(std::shared_ptr<BaseSegment> segment, size_t new_size) override {
-    auto value_segment = std::dynamic_pointer_cast<ValueSegment<T>>(segment);
-    DebugAssert(value_segment, "Cannot insert into non-ValueColumns");
-    auto& values = value_segment->values();
+void resize_value_segment(std::shared_ptr<BaseSegment> segment, size_t new_size) {
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: Add a comment that it is the callers responsibility to guard the entry to this critical section?

File: src/lib/operators/insert.cpp [hunk 3]
```diff
@@ -8,94 +8,80 @@
...
-    auto casted_target = std::dynamic_pointer_cast<ValueSegment<T>>(target);
-    DebugAssert(casted_target, "Cannot insert into non-ValueColumns");
-    auto& values = casted_target->values();
-
-    auto target_is_nullable = casted_target->is_nullable();
-
-    if (auto casted_source = std::dynamic_pointer_cast<const ValueSegment<T>>(source)) {
-      std::copy_n(casted_source->values().begin() + source_start_index, length, values.begin() + target_start_index);
+template <typename T>
+void copy(const std::shared_ptr<const BaseSegment>& source_base_segment, ChunkOffset source_begin_offset,
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: copy what? I agree that data doesn't mean too much either. copy attribute? That's what the relational algebra would call it.

File: src/lib/operators/insert.cpp [hunk 4]
```diff
@@ -8,94 +8,80 @@
...
+      const auto nulls_begin_iter = source_value_segment->null_values().begin() + source_begin_offset;
+      const auto nulls_end_iter = nulls_begin_iter + length;
+
+      Assert(
+          target_is_nullable || std::none_of(nulls_begin_iter, nulls_end_iter, [](const auto& null) { return null; }),
+          "Trying to insert NULL into non-NULL segment");
+      std::copy(nulls_begin_iter, nulls_end_iter, target_value_segment->null_values().begin() + target_begin_offset);
+    }
+  } else {
+    segment_with_iterators<T>(*source_base_segment, [&](auto source_begin, const auto source_end) {
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: Wouldn't `source_it` be more consistent?

File: src/lib/operators/insert.cpp [hunk 5]
```diff
@@ -8,94 +8,80 @@
...
-    auto target_is_nullable = casted_target->is_nullable();
-
-    if (auto casted_source = std::dynamic_pointer_cast<const ValueSegment<T>>(source)) {
-      std::copy_n(casted_source->values().begin() + source_start_index, length, values.begin() + target_start_index);
+template <typename T>
+void copy(const std::shared_ptr<const BaseSegment>& source_base_segment, ChunkOffset source_begin_offset,
+          const std::shared_ptr<BaseSegment>& target_base_segment, ChunkOffset target_begin_offset,
+          ChunkOffset length) {
+  const auto target_value_segment = std::dynamic_pointer_cast<ValueSegment<T>>(target_base_segment);
+  Assert(target_value_segment, "Cannot insert into non-ValueSegments");
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: DebugAssert that the vector has enough space?

File: src/lib/operators/insert.cpp [hunk 6]
```diff
@@ -107,136 +93,132 @@ std::shared_ptr<const Table> Insert::_on_execute(std::shared_ptr<TransactionCont
...
 
     if (_target_table->chunk_count() == 0) {
       _target_table->append_mutable_chunk();
     }
 
-    start_chunk_id = _target_table->chunk_count() - 1;
-    end_chunk_id = start_chunk_id + 1;
-    auto last_chunk = _target_table->get_chunk(start_chunk_id);
-    start_index = last_chunk->size();
+    while (remaining_rows > 0) {
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: An assumption all through the code base is that the last chunk is the one that will be inserted into. Here, we could end up with a full last chunk that might even later be compressed. Not sure about the implications, but maybe we want to avoid this?

File: src/lib/operators/insert.cpp [hunk 7]
```diff
@@ -107,136 +93,132 @@ std::shared_ptr<const Table> Insert::_on_execute(std::shared_ptr<TransactionCont
...
+        _target_table->append_mutable_chunk();
+        ++target_chunk_id;
+        target_chunk = _target_table->get_chunk(target_chunk_id);
+      }
 
-    auto remaining_rows = total_rows_to_insert;
-    while (remaining_rows > 0) {
-      auto current_chunk = _target_table->get_chunk(static_cast<ChunkID>(_target_table->chunk_count() - 1));
-      auto rows_to_insert_this_loop = std::min(_target_table->max_chunk_size() - current_chunk->size(), remaining_rows);
+      const auto target_chunk_num_inserted_rows =
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: `rows_to_insert_in_target_chunk` has the same length, but might be clearer

File: src/lib/operators/insert.cpp [hunk 8]
```diff
@@ -107,136 +93,132 @@ std::shared_ptr<const Table> Insert::_on_execute(std::shared_ptr<TransactionCont
...
+          std::min<size_t>(_target_table->max_chunk_size() - target_chunk->size(), remaining_rows);
 
-      // Resize MVCC vectors.
-      current_chunk->get_scoped_mvcc_data_lock()->grow_by(rows_to_insert_this_loop, MvccData::MAX_COMMIT_ID);
+      _target_chunk_ranges.emplace_back(
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: `reserve(input_rows / max_chunk_size + 2)`?

File: src/lib/operators/insert.cpp [hunk 9]
```diff
@@ -107,136 +93,132 @@ std::shared_ptr<const Table> Insert::_on_execute(std::shared_ptr<TransactionCont
...
+          ChunkRange{target_chunk_id, target_chunk->size(),
+                     static_cast<ChunkOffset>(target_chunk->size() + target_chunk_num_inserted_rows)});
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: Is the end position really necessary?

File: src/lib/operators/insert.cpp [hunk 10]
```diff
@@ -107,136 +93,132 @@ std::shared_ptr<const Table> Insert::_on_execute(std::shared_ptr<TransactionCont
...
 
-      // Resize current chunk to full size.
-      auto old_size = current_chunk->size();
-      for (ColumnID column_id{0}; column_id < current_chunk->column_count(); ++column_id) {
-        typed_segment_processors[column_id]->resize_vector(current_chunk->get_segment(column_id),
-                                                           old_size + rows_to_insert_this_loop);
-      }
+      // Grow MVCC columns while simultaneously locking them for the current transaction.
+      target_chunk->get_scoped_mvcc_data_lock()->grow_by(target_chunk_num_inserted_rows, context->transaction_id());
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: I first thought "locking them" referred to `get_scoped_mvcc_data_lock`. Maybe "Grow MVCC vectors and mark new (but still empty) rows as being under modification by current transaction"

Comment (mrks) [inline src/lib/operators/insert.cpp]: Explain why we grow MVCC vectors before we touch the segments?

File: src/lib/operators/insert.cpp [hunk 11]
```diff
@@ -107,136 +93,132 @@ std::shared_ptr<const Table> Insert::_on_execute(std::shared_ptr<TransactionCont
...
 
-      remaining_rows -= rows_to_insert_this_loop;
+      // Grow data Segments.
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: Should `Chunk::size()` be changed so that it returns the size of the *last* segment? Accessing the "new" last row is only valid once the MVCC vectors and all segments are extended.

File: src/lib/operators/insert.cpp (hunk 2 above)
Comment (mrks) [reply src/lib/operators/insert.cpp]: Having seen the only call of this method, I wonder if inlining this method could improve readability (and make the previous comment superfluous).

File: src/lib/operators/insert.cpp [hunk 12]
```diff
@@ -107,136 +93,132 @@ std::shared_ptr<const Table> Insert::_on_execute(std::shared_ptr<TransactionCont
...
+      auto old_size = target_chunk->size();
+      for (ColumnID column_id{0}; column_id < target_chunk->column_count(); ++column_id) {
+        resolve_data_type(_target_table->column_data_type(column_id), [&](const auto data_type_t) {
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: Use `BaseValueSegment`?

File: src/lib/operators/insert.cpp [hunk 13]
```diff
@@ -107,136 +93,132 @@ std::shared_ptr<const Table> Insert::_on_execute(std::shared_ptr<TransactionCont
...
     }
   }
-  // TODO(all): make compress chunk thread-safe; if it gets called here by another thread, things will likely break.
 
-  // Then, actually insert the data.
-  auto input_offset = 0u;
-  auto source_chunk_id = ChunkID{0};
-  auto source_chunk_start_index = 0u;
+  /**
+   * 2. Insert the Data into the memory allocated in the first step. Write the transaction_context's transaction_id into
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: Add a comment that the lock has been released?

File: src/lib/operators/insert.cpp [hunk 14]
```diff
@@ -107,136 +93,132 @@ std::shared_ptr<const Table> Insert::_on_execute(std::shared_ptr<TransactionCont
...
+   *    all allocated rows.
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: Didn't you write the txid before?

File: src/lib/operators/insert.cpp [hunk 15]
```diff
@@ -107,136 +93,132 @@ std::shared_ptr<const Table> Insert::_on_execute(std::shared_ptr<TransactionCont
...
+   */
+  auto source_row_id = RowID{ChunkID{0}, ChunkOffset{0}};
 
-  for (auto target_chunk_id = start_chunk_id; target_chunk_id < end_chunk_id; target_chunk_id++) {
-    auto target_chunk = _target_table->get_chunk(target_chunk_id);
+  for (const auto& target_chunk_range : _target_chunk_ranges) {
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: This loop feels unintuitive to me. I wouldn't have expected a loop over the chunks that we insert into as the outermost loop. Also, resolving the data type for each value seems to be quite expensive. Isn't it comparable to using AllTypeVariants?

In pseudocode, this seems to be easier:

```
next_target_chunk_range = target_chunk_ranges[0]
next_target_chunk_offset = next_target_chunk_range.begin
foreach column:
  foreach input_chunk:
    iterate_segment<column.type>(input_chunk.get_segment(column), input_it):
      segment = static_cast<ValueSegment<...>>(next_target_chunk_range.chunk.get_segment(column))
      segment.values[next_target_chunk_offset] = *input_it
      next_target_chunk_offset++
      if (next_target_chunk_offset > next_target_chunk_range.end):
        // update next_target_chunk_range
```

File: src/lib/operators/insert.cpp [hunk 16]
```diff
@@ -107,136 +93,132 @@ std::shared_ptr<const Table> Insert::_on_execute(std::shared_ptr<TransactionCont
...
 void Insert::_on_commit_records(const CommitID cid) {
-  for (auto row_id : _inserted_rows) {
-    auto chunk = _target_table->get_chunk(row_id.chunk_id);
-
-    auto mvcc_data = chunk->get_scoped_mvcc_data_lock();
-    mvcc_data->begin_cids[row_id.chunk_offset] = cid;
-    mvcc_data->tids[row_id.chunk_offset] = 0u;
+  for (const auto& target_chunk_range : _target_chunk_ranges) {
+    const auto target_chunk = _target_table->get_chunk(target_chunk_range.chunk_id);
+    auto mvcc_data = target_chunk->get_scoped_mvcc_data_lock();
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: Do we need to hold the lock for the entire inner loop? (below too)

File: src/lib/operators/insert.cpp [hunk 17]
```diff
@@ -107,136 +93,132 @@ std::shared_ptr<const Table> Insert::_on_execute(std::shared_ptr<TransactionCont
...
-    // We set the begin and end cids to 0 (effectively making it invisible for everyone) so that the ChunkCompression
-    // does not think that this row is still incomplete. We need to make sure that the end is written before the begin.
-    chunk->get_scoped_mvcc_data_lock()->end_cids[row_id.chunk_offset] = 0u;
-    std::atomic_thread_fence(std::memory_order_release);
-    chunk->get_scoped_mvcc_data_lock()->begin_cids[row_id.chunk_offset] = 0u;
-
-    chunk->get_scoped_mvcc_data_lock()->tids[row_id.chunk_offset] = 0u;
+  for (const auto& target_chunk_range : _target_chunk_ranges) {
+    const auto target_chunk = _target_table->get_chunk(target_chunk_range.chunk_id);
+    auto mvcc_data = target_chunk->get_scoped_mvcc_data_lock();
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: Do we need to hold the lock for the entire inner loop?

File: src/lib/operators/insert.cpp [hunk 18]
```diff
@@ -107,136 +93,132 @@ std::shared_ptr<const Table> Insert::_on_execute(std::shared_ptr<TransactionCont
...
+
+    for (auto chunk_offset = target_chunk_range.begin_chunk_offset; chunk_offset < target_chunk_range.end_chunk_offset;
+         ++chunk_offset) {
+      // Set the begin and end cids to 0 (effectively making it invisible for everyone).
+      // Make sure that the end is written before the begin.
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: Write end_cids first, issue a single fence, then write the others?

File: src/lib/storage/chunk.cpp [hunk 19]
```diff
@@ -43,7 +43,7 @@ void Chunk::append(const std::vector<AllTypeVariant>& values) {
   DebugAssert(is_mutable(), "Can't append to immutable Chunk");
 
   // Do this first to ensure that the first thing to exist in a row are the MVCC data.
-  if (has_mvcc_data()) get_scoped_mvcc_data_lock()->grow_by(1u, MvccData::MAX_COMMIT_ID);
+  if (has_mvcc_data()) get_scoped_mvcc_data_lock()->grow_by(1u, TransactionID{0});
```
Comment (mrks) [inline src/lib/storage/chunk.cpp]: **is** the MVCC data

File: src/lib/storage/mvcc_data.cpp [hunk 20]
```diff
@@ -6,7 +6,7 @@
 
 namespace opossum {
 
-MvccData::MvccData(const size_t size) { grow_by(size, 0); }
+MvccData::MvccData(const size_t size) { grow_by(size, TransactionID{0}); }
```
Comment (mrks) [inline src/lib/storage/mvcc_data.cpp]: INVALID_TRANSACTION_ID?

File: src/lib/storage/mvcc_data.hpp [hunk 21]
```diff
@@ -36,9 +36,9 @@ struct MvccData {
   /**
    * Grows mvcc data by the given delta
    *
-   * @param begin_cid value all new begin_cids will be set to
+   * @param transaction_id    value all new tids will be set to
    */
-  void grow_by(size_t delta, CommitID begin_cid);
+  void grow_by(size_t delta, TransactionID transaction_id);
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/storage/mvcc_data.hpp]: I don't think so, the issue was a race of two Insert::_on_execute() running at the same time, both allocating space and then trying to insert **until the table was "full"** instead of stopping when all their input was consumed.

File: src/lib/operators/insert.cpp (hunk 1 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: ;)

File: src/lib/operators/insert.cpp (hunk 2 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: yes, inlining is cool.

File: src/lib/operators/insert.cpp (hunk 3 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: hard one to name right, it is very similar to, e.g., `std::copy`/`memcpy` - just that it operates on segments. `copy_value_range`?

File: src/lib/operators/insert.cpp (hunk 4 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: Nah, why? `segment_with_iterators` gives us the entire Segment's range, but the function just wants to write to a sub-range of it.

Comment (mrks) [reply src/lib/operators/insert.cpp]: Aaah, I see what you're doing. Const it?

File: src/lib/operators/insert.cpp (hunk 5 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: done

File: src/lib/operators/insert.cpp (hunk 4 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: done

File: src/lib/operators/insert.cpp (hunk 7 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: better indeed, some of the namings, old and new, are pretty awkward...

File: src/lib/operators/insert.cpp (hunk 8 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: I'd never expect more than one or two ranges to appear in practice. Each range will cover up to max_chunk_size rows, after all!

File: src/lib/operators/insert.cpp (hunk 9 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: "Not necessary" as in "there are other ways to solve this". "Necessary" as in "this is how I chose to solve this". ;)

Having the end position prevents us from having to check for "have we consumed all input" and "how many rows can we copy into the current chunk" when we actually copy the data in the `2.` step.

File: src/lib/operators/insert.cpp (hunk 10 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: done

File: src/lib/operators/insert.cpp (hunk 3 above)
Comment (mrks) [reply src/lib/operators/insert.cpp]: I like it

File: src/lib/operators/insert.cpp (hunk 9 above)
Comment (mrks) [reply src/lib/operators/insert.cpp]: The discussion about the general structure needs to be resolved first. Generally, I'd like to keep temporary data structures small, especially if we can easily recreate that information later.

File: src/lib/operators/insert.cpp (hunk 12 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: To do what? If want to grow ValueSegment::values(), we need to know its type.

File: src/lib/operators/insert.cpp (hunk 13 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: done

File: src/lib/operators/insert.cpp (hunk 14 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: yep, removed

File: src/lib/operators/insert.cpp (hunk 9 above)
Comment (mrks) [reply src/lib/operators/insert.cpp]: Remember that you're forcing the reader to remember all the things you put into that struct. If you recreate that information later, the reader does not need as much heap space and the information will be fresh. ;)

File: src/lib/operators/insert.cpp (hunk 15 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: Gods, I am not resolving the data type for every value - just for every target chunk range, covering hundred thousands of rows!

Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: I am certain there are other ways to structure the loops. The way I do it is that I first build the target-chunk ranges (aka "this is where the inserted data goes") and then I fill these ranges in the seconds step. I think it's okay enough.

File: src/lib/operators/insert.cpp (hunk 12 above)
Comment (mrks) [reply src/lib/operators/insert.cpp]: Not if `BaseValueSegment` has a virtual `resize` method. Why should I have to know the type of a segment to resize it?

File: src/lib/operators/insert.cpp (hunk 15 above)
Comment (mrks) [reply src/lib/operators/insert.cpp]: Oups. Might have misread that. That makes the performance aspect void, but I'd still like to discuss the general approach from a readability perspective.

File: src/lib/operators/insert.cpp (hunk 6 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: Don't see a problem, can you elaborate? Ending up with full Chunks is okay, is it not?

File: src/lib/operators/insert.cpp (hunk 15 above)
Comment (mrks) [reply src/lib/operators/insert.cpp]: Didn't see the second comment. Let's work through the rest and I'll have another look at this during my second pass.

File: src/lib/operators/insert.cpp (hunk 6 above)
Comment (mrks) [reply src/lib/operators/insert.cpp]: Not sure if there is something in the code that would actually break right now. I am just wondering if we should always have a modifiable chunk at the end as this is how we communicate it, e.g., in our chunk visualization. Saying "the last chunk is where we insert" seems clearer that "the last chunk might be an encoded segment or a ValueSegment, and if its size is less than the maximum_chunk_size, this is where we insert".

Comment (mrks) [reply src/lib/operators/insert.cpp]: @Bouncner was involved in a couple of chunk layout things, too.

File: src/lib/operators/insert.cpp (hunk 16 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: tbh I don't even know why we need that lock. The MvccData uses concurrent_vectors, after all, and Insert holds a lock over the entire table when it resizes them...

File: src/lib/operators/insert.cpp (hunk 6 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: Having the least amount of runtime-constraints like "you can rely on the last chunk being non-full and modifiable" seems desirable for me. Remember how well this "a table will always have at least one chunk"-thing went?

File: src/lib/operators/insert.cpp (hunk 9 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: The readers heap/stack is one of my core concerns, yes. But their compute power is as well. (Re)constructing **where data went/goes** needs to happen in four places: When allocating, when copying, when committing and when rolling back. I'd rather require my reader to have a model of a vector of ranges within a Chunks then having them to parse redundant computations in four different places.

File: src/lib/operators/insert.cpp (hunk 12 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: No hard opinion on this, but there is only one place where we grow/resize segments: `Insert`. I'd rather not add a virtual function which is then only used in one place.I'd inline it.

File: src/lib/operators/insert.cpp (hunk 18 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: Why the fencing? From around 5h of watching c++ memory model talks and very little security gained on the topic I'd say `mvcc_data->tids[chunk_offset] = 0u;` at the very end is the release operation that makes the inserted row visible. No fences needed....

File: src/lib/operators/insert.cpp (hunk 10 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: The table is locked, no one else can resize its segments or mvcc-data.
Every query will see the data through the lenses of mvcc, it does not matter whether the mvcc data is not grown or whether it is grown but locked.

If anything I'd say we should resize the MVCC vectors AFTER the value segments, as the resize of the tid vector will be a release operations and "those should always happen at the end", informally speaking.

Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: @mrks I think we should take 5 minutes tomorrow to synchronize our understanding of the c++ memory model.

Comment (mrks) [reply src/lib/operators/insert.cpp]: Mmh, I thought this was done on purpose; so this was a request to add a comment.

>  Every query will see the data through the lenses of mvcc, it does not matter whether the mvcc data is not grown or whether it is grown but locked.

But how do the "lenses of MVCC" work? The validate operator looks at all rows (i.e., `chunks->size()`). If we resize the segments first, it might end up accessing non-existing MVCC info.

> I think we should take 5 minutes tomorrow to synchronize our understanding of the c++ memory model.

The C++ memory model in five minutes. I giggled.

File: src/lib/operators/insert.cpp (hunk 18 above)
Comment (mrks) [reply src/lib/operators/insert.cpp]: You added the fencing. My suggestion is to remove it from the loop for performance reasons.

File: src/lib/operators/insert.cpp (hunk 12 above)
Comment (mrks) [reply src/lib/operators/insert.cpp]: Works for me.

File: src/lib/operators/insert.cpp (hunk 9 above)
Comment (mrks) [reply src/lib/operators/insert.cpp]: Works for me, still wanted to bring it up.

File: src/lib/operators/insert.cpp (hunk 18 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: the fence was there before, I doubt it was I who added it originally.

File: src/lib/operators/insert.cpp (hunk 10 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: > Mmh, I thought this was done on purpose

c/p from the previous impl


> But how do the "lenses of MVCC" work? The validate operator looks at all rows (i.e., chunks->size()). If we resize the segments first, it might end up accessing non-existing MVCC info.

Then Validate *should* probably look at the mvcc-data-length... Really looking forward to tpcc with 100 clients to stress test all this...

File: src/lib/operators/insert.cpp (hunk 16 above)
Comment (mrks) [reply src/lib/operators/insert.cpp]: I believe it has something to do with the MVCC data being migrated if a chunk is being encoded. Will have to look into it again, though.

File: src/lib/operators/insert.cpp (hunk 18 above)
Comment (mrks) [reply src/lib/operators/insert.cpp]: Ah, ok. As this PR rewrote basically everything, I used split view and didn't check the left side too much.

File: src/lib/operators/insert.cpp (hunk 10 above)
Comment (mrks) [reply src/lib/operators/insert.cpp]: I think `Chunk::size` should return how many valid rows there are and no one should be allowed to touch any offsets in any vectors beyond that.

> Then Validate should probably look at the mvcc-data-length...

Which one of the three vectors?

Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: > Which one of the three vectors?

the tid vector, I guess. it should always be written to as the last operation and read from as the first operation - it contains atomics so this should get us closer to a safe acquire/release pattern

Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: (I am being vague here as really want to discuss this in the presence of a whiteboard...)

File: src/lib/operators/insert.cpp (hunk 9 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: This is roughly how on_commit_records will look like with and without explicitly storing the ChunkRanges. This increased complexity would be there for commit_records/rollback_records and the copy step. I think it is desirable to store the ChunkRanges, given the increased complexity incurred without them

```c++

void Insert::_on_commit_records(const CommitID cid) {
  // Without explicitly storing the target ChunkRanges
  for (auto target_chunk_id = _target_table_begin.chunk_id; target_chunk_id < _target_table_end.chunk_id;
       ++target_chunk_id) {
    const auto target_chunk = _target_table->get_chunk(target_chunk_id);

    const auto target_chunk_begin_offset =
        target_chunk_id == _target_table_begin.chunk_id ? _target_table_begin.chunk_offset : ChunkOffset{0};
    const auto target_chunk_end_offset =
        target_chunk_id == _target_table_end.chunk_id ? _target_table_end.chunk_offset : target_chunk->size();

    auto mvcc_data = target_chunk->get_scoped_mvcc_data_lock();

    for (auto chunk_offset = target_chunk_begin_offset; chunk_offset < target_chunk_end_offset; ++chunk_offset) {
      mvcc_data->begin_cids[chunk_offset] = cid;
      mvcc_data->tids[chunk_offset] = 0u;
    }
  }

  // With explicitly storing the target ChunkRanges
  for (const auto& target_chunk_range : _target_chunk_ranges) {
    const auto target_chunk = _target_table->get_chunk(target_chunk_range.chunk_id);
    auto mvcc_data = target_chunk->get_scoped_mvcc_data_lock();

    for (auto chunk_offset = target_chunk_range.begin_chunk_offset; chunk_offset < target_chunk_range.end_chunk_offset;
         ++chunk_offset) {
      mvcc_data->begin_cids[chunk_offset] = cid;
      mvcc_data->tids[chunk_offset] = 0u;
    }
  }
}
```

File: src/lib/operators/insert.cpp (hunk 18 above)
Comment (mrks) [reply src/lib/operators/insert.cpp]: If we wrote the begin CID before we write the end CID, we might end up in a situation where the row (with begin 0, end infty) is indisinguishable from a row that is visible to everyone. This should be added to the comment.

File: src/lib/operators/insert.cpp [hunk 22]
```diff
@@ -107,136 +84,140 @@ std::shared_ptr<const Table> Insert::_on_execute(std::shared_ptr<TransactionCont
...
-    chunk->get_scoped_mvcc_data_lock()->begin_cids[row_id.chunk_offset] = 0u;
-
-    chunk->get_scoped_mvcc_data_lock()->tids[row_id.chunk_offset] = 0u;
+  for (const auto& target_chunk_range : _target_chunk_ranges) {
+    const auto target_chunk = _target_table->get_chunk(target_chunk_range.chunk_id);
+    auto mvcc_data = target_chunk->get_scoped_mvcc_data_lock();
+
+    for (auto chunk_offset = target_chunk_range.begin_chunk_offset; chunk_offset < target_chunk_range.end_chunk_offset;
+         ++chunk_offset) {
+      // Set the begin and end cids to 0 (effectively making it invisible for everyone).
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: Bring back the reference to the ChunkCompressionTASK

File: src/lib/storage/chunk_encoder.hpp [hunk 23]
```diff
@@ -32,6 +32,9 @@ using ChunkEncodingSpec = std::vector<SegmentEncodingSpec>;
 /**
  * @brief Interface for encoding chunks
  *
+ * TODO(all): make compress chunk thread-safe; if it gets called while another thread is inserting, things will likely
+ *            break.
```
Comment (mrks) [inline src/lib/storage/chunk_encoder.hpp]: Update comment: This thingy does not guarantee thread-safety, the ChunkEncoderTask does

File: src/lib/operators/insert.cpp (hunk 16 above)
Comment (mrks) [reply src/lib/operators/insert.cpp]: It is needed when we shrink the MVCC data:

```
  /**
   * Compacts the internal representation of
   * the mvcc data in order to reduce fragmentation
   * Locks mvcc data exclusively in order to do so
   */
  void shrink();
```

However, 9b15cafcc98e8f82ae731e7601a2fa701ee047bb removed the exclusive lock by mistake. It should be reintroduced (and then removed again by #749).

Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: done

File: src/lib/operators/insert.cpp (hunk 18 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: Added this comment, what do you think?

```c++
    /**
     * !!! Crucial comment, PLEASE READ AND _UNDERSTAND_ before altering any of the following code !!!
     *
     * Set end_cids to 0 (effectively making the rows invisible for everyone) BEFORE setting the begin_cids to 0.
     *
     * Otherwise, another thread might observe a column with `begin_cid == 0` and `end_cid == MAX_COMMIT_ID` which would
     * make this other thread believe it can see a row that was actually rolled back and should never become visible.
     *
     * We need to set `begin_cid = 0` so that the ChunkCompressionTask can identify "completed" Chunks.
     */
```

File: src/lib/operators/insert.cpp (hunk 22 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: done

File: src/lib/storage/chunk_encoder.hpp (hunk 23 above)
Comment (mrzzzrm) [reply src/lib/storage/chunk_encoder.hpp]: Altered to `NOT thread-safe. In a multi-threaded context, the ChunkCompressionTask should invoke the ChunkEncoder.`

File: src/lib/operators/insert.cpp (hunk 17 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: Apparently we do, otherwise someone might call "shrink" on the mvcc data while we access it. Acquiring the lock for each row individually seems bad as well.

File: src/lib/operators/insert.cpp (hunk 8 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: resolved?

File: src/lib/operators/insert.cpp (hunk 10 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: Regarding 

> Explain why we grow MVCC vectors before we touch the segments? 

I added comments:

```c++
      // Grow MVCC vectors and mark new (but still empty) rows as being under modification by current transaction.
      // Do so before resizing the Segments, because the resize of `Chunk::_segments.front()` is what releases the
      // new row count.
      target_chunk->get_scoped_mvcc_data_lock()->grow_by(num_rows_for_target_chunk, context->transaction_id());

      // Grow data Segments.
      // Do so in REVERSE column order so that the resize of `Chunk::_segments.front()` happens last. It is this last
      // resize that makes the new row count visible to the outside world.
      auto old_size = target_chunk->size();
      for (ColumnID reverse_column_id{0}; reverse_column_id < target_chunk->column_count(); ++reverse_column_id) {
```

File: src/lib/operators/insert.cpp (hunk 11 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: done

File: src/lib/operators/insert.cpp [hunk 24]
```diff
@@ -119,9 +119,18 @@ std::shared_ptr<const Table> Insert::_on_execute(std::shared_ptr<TransactionCont
...
                      static_cast<ChunkOffset>(target_chunk->size() + num_rows_for_target_chunk)});
 
+      // Grow MVCC vectors and mark new (but still empty) rows as being under modification by current transaction.
+      // Do so before resizing the Segments, because the resize of `Chunk::_segments.front()` is what releases the
+      // new row count.
+      target_chunk->get_scoped_mvcc_data_lock()->grow_by(num_rows_for_target_chunk, context->transaction_id());
+
       // Grow data Segments.
+      // Do so in REVERSE column order so that the resize of `Chunk::_segments.front()` happens last. It is this last
+      // resize that makes the new row count visible to the outside world.
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: Don't we need a fence here? Right now, there is nothing that keeps the compiler from resizing the segments in any order.

File: src/lib/operators/insert.cpp [hunk 25]
```diff
@@ -209,12 +215,28 @@ void Insert::_on_rollback_records() {
     const auto target_chunk = _target_table->get_chunk(target_chunk_range.chunk_id);
     auto mvcc_data = target_chunk->get_scoped_mvcc_data_lock();
 
+    /**
+     * !!! Crucial comment, PLEASE READ AND _UNDERSTAND_ before altering any of the following code !!!
+     *
+     * Set end_cids to 0 (effectively making the rows invisible for everyone) BEFORE setting the begin_cids to 0.
+     *
+     * Otherwise, another thread might observe a row with `begin_cid == 0` and `end_cid == MAX_COMMIT_ID` which would
+     * make this other thread believe it can see a row that was actually rolled back and should never become visible.
```
Comment (mrks) [inline src/lib/operators/insert.cpp]: Mmh, this is not that easy to understand. Maybe:
Otherwise, another transaction/thread might observe a row with `begin_cid == 0`, `end_cid == MAX_COMMIT_ID` and a foreign tid which is what a visible row that is being deleted by a different transaction looks like. Thus, the other transaction would consider the row that is in the process of being rolled back and should have never been visible as visible.

File: src/lib/storage/mvcc_data.cpp [hunk 26]
```diff
@@ -12,6 +12,15 @@ MvccData::MvccData(const size_t size) { grow_by(size, INVALID_TRANSACTION_ID); }
 size_t MvccData::size() const { return _size; }
 
 void MvccData::shrink() {
+  // tbb::concurrent_vector::shrink_to_fit() is not thread-safe, we need a unique lock to it.
+  //
+  // https://software.intel.com/en-us/node/506205
+  //   "Concurrent invocation of these operations on the same instance is not safe."
+  // https://software.intel.com/en-us/node/506203
+  //   "The method shrink_to_fit()merges several smaller arrays into a single contiguous array, which may improve access
```
Comment (mrks) [inline src/lib/storage/mvcc_data.cpp]: typo

File: src/lib/tasks/chunk_compression_task.cpp [hunk 27]
```diff
@@ -42,6 +42,9 @@ bool ChunkCompressionTask::_chunk_is_completed(const std::shared_ptr<Chunk>& chu
   auto mvcc_data = chunk->get_scoped_mvcc_data_lock();
 
   for (const auto begin_cid : mvcc_data->begin_cids) {
+    // TODO(anybody) Reading the non-atomic begin_cid (which is written to in Insert without a write lock) is likely UB
+    //               When activating the ChunkCompressionTask, please look for a different means of determining whether
+    //               All Inserts to a Chunk finished.
```
Comment (mrks) [inline src/lib/tasks/chunk_compression_task.cpp]: all

File: src/lib/operators/insert.cpp (hunk 24 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: I probably thought of tbb::concurrent_vector::resize() as a full-seq-consistency operation that doesn't need fences....

Added this after the column resize, but I have no idea whether it is necessary or not or whether a release-barrier would be enough...:

```c++

        // Make sure the first columns rewrite actually happens last and doesn't get reordered.
        std::atomic_thread_fence(std::memory_order_seq_cst);
```

File: src/lib/operators/insert.cpp (hunk 25 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: mmh, okay, changed.

File: src/lib/operators/insert.cpp (hunk 24 above)
Comment (mrzzzrm) [reply src/lib/operators/insert.cpp]: I feel like it has to be a seq_cst barrier to make sure the first column's new size only gets observed after the other resizes completed, but it feels awkward...

Comment (mrks) [reply src/lib/operators/insert.cpp]: Yes, the concurrent_vector should be fine for now, but once we put in std::vectors, I can almost guarantee that this will be forgotten.

File: src/lib/operators/insert.cpp (hunk 15 above)
Comment (mrks) [reply src/lib/operators/insert.cpp]: I tried quite a while to get my version to work. Turns out your approach is better suited to handle self-inserts.

**Comment by mrks** [comment]
Inserts into a table with four ints on nemea:

```
./hyriseBenchmarkFileBased --table_path=../foo --query_path=../foo --mvcc --scheduler --clients=100 --runs=100000
Executed 100000 times in 1.89297 seconds (52827.2 iter/s)
```

Not bad given that we haven't really optimized the OLTP part too much yet.

**Comment by mrzzzrm** [comment]
How many iter/s with a single client?

**Comment by mrks** [comment]
100 clients, all cores: 52827.2 iter/s
single client, all cores: 99.1388 iter/s
single client, single-threaded: 71554.3 iter/s

File: src/lib/operators/insert.cpp [hunk 28]
```diff
@@ -97,6 +97,10 @@ std::shared_ptr<const Table> Insert::_on_execute(std::shared_ptr<TransactionCont
    *    Do so while locking the table to prevent multiple threads modifying the table's size simultaneously.
    *    Since allocation is expected to be faster than writing to the memory, allocating under lock and then writing -
    *    in a second step - without lock will minimize the time that the Table's append_mutex is locked.
+   *
+   *    In the rare case where the input table is the table that we write to (OperatorsInsertTest.SelfInsert), this
```
Comment (mrzzzrm) [inline src/lib/operators/insert.cpp]: I am not sure such vague comments pointing in the direction of possible complications if a problem would have been attempted to be solved in a different manner are very helpful...

**Comment by mrks** [comment]
Added a run with a single NUMA node

**Comment by mrks** [comment]
I have no idea what happened here, but this reduced the TPC-H Q2 performance from 8.51236 to 7.18498. I don't see a single line in here that is used for Q2, so this might be another alignment issue. :/
