### PR TITLE
Add query plan cache resize() and fix memory access in random_cache

### LINKED ISSUE #619: Memory access error in RandomCache
While working on the cache visualizer, we found an issue with the iterators that are stored in the RandomCache. @Bensk1 has a fix and should push it.

### PR DESCRIPTION
**Pull request by Bensk1**
Adds resize method and fixes #619

### CODE REVIEW

File: src/lib/sql/abstract_cache.hpp [hunk 1]
```diff
@@ -36,6 +36,9 @@ class AbstractCache {
   // Remove all elements from the cache and resize to the given capacity.
   virtual void clear_and_resize(size_t capacity) = 0;
 
+  // Resize to the given capacity.
+  virtual void resize(size_t capacity) = 0;
```
Comment (mrks) [inline src/lib/sql/abstract_cache.hpp]: Now that we have `resize`, what it `clear_and_resize`'s reason to exist?

File: src/lib/sql/gdfs_cache.hpp [hunk 2]
```diff
@@ -87,6 +87,19 @@ class GDFSCache : public AbstractCache<Key, Value> {
     this->_capacity = capacity;
   }
 
+  void resize(size_t capacity) {
+    if (_queue.size() > capacity) {
+      for (size_t difference = 0; difference < _queue.size() - capacity; ++difference) {
```
Comment (mrks) [inline src/lib/sql/gdfs_cache.hpp]: Couldn't you do this in one line with `while (_queue.size > capacity)`?

File: src/lib/sql/gds_cache.hpp [hunk 3]
```diff
@@ -87,6 +87,19 @@ class GDSCache : public AbstractCache<Key, Value> {
...
   }
 
+  void resize(size_t capacity) {
+    if (_queue.size() > capacity) {
+      for (size_t difference = 0; difference < _queue.size() - capacity; ++difference) {
+        auto top = _queue.top();
+
+        _inflation = top.priority;
+        _map.erase(top.key);
+        _queue.pop();
```
Comment (mrks) [inline src/lib/sql/gds_cache.hpp]: Seeing this code again, shouldn't each cache implement a protected `_evict` method? That way, `resize` could be part of the `AbstractCache`.

File: src/lib/sql/abstract_cache.hpp (hunk 1 above)
Comment (Bensk1) [reply src/lib/sql/abstract_cache.hpp]: Good point. We could either remove it completely or implement it in the AbstractCache by calling `clear()` and `resize()`

File: src/lib/sql/gds_cache.hpp (hunk 3 above)
Comment (Bensk1) [reply src/lib/sql/gds_cache.hpp]: You mean the Abstract cache would have a loop like `while (_queue.size > capacity)` calling `_evict()` inside? I see two problems. The loop condition depends on the cache type. Furthermore, there is cache dependent resize code, e.g., the random cache's reinitialization of the random generator.

File: src/lib/sql/abstract_cache.hpp (hunk 1 above)
Comment (mrks) [reply src/lib/sql/abstract_cache.hpp]: The `AbstractCache` already has `clear()`. As no one uses `clear_and_resize` now and because it can be easily replaced with clear+resize, let's get rid of it.

File: src/lib/sql/gds_cache.hpp (hunk 3 above)
Comment (mrks) [reply src/lib/sql/gds_cache.hpp]: Ok, I missed that part about the implementation being different. I would still put the eviction part in its own method so that it can be shared with `set`

Comment (Bensk1) [reply src/lib/sql/gds_cache.hpp]: Done

File: src/lib/sql/gdfs_cache.hpp (hunk 2 above)
Comment (Bensk1) [reply src/lib/sql/gdfs_cache.hpp]: Done

File: src/lib/sql/abstract_cache.hpp (hunk 1 above)
Comment (Bensk1) [reply src/lib/sql/abstract_cache.hpp]: Done
