### PR TITLE
ColumnVsValueScan: Fix MatchesAll optimization on Dictionaries

### LINKED ISSUE #1361: ColumnVsValue: Dictionary early out for MatchesAll includes null values in the result

### PR DESCRIPTION
**Pull request by mrzzzrm**
Fix #1361

### CODE REVIEW

File: src/lib/operators/table_scan/column_vs_value_table_scan_impl.cpp [hunk 1]
```diff
@@ -100,7 +100,8 @@ void ColumnVsValueTableScanImpl::_scan_segment(const BaseDictionarySegment& segm
   if (_value_matches_all(segment, search_value_id)) {
     iterable.with_iterators(position_filter, [&](auto it, auto end) {
       static const auto always_true = [](const auto&) { return true; };
-      _scan_with_iterators<false>(always_true, it, end, chunk_id, matches);
+      // MatchesAll, so include all rows except those with NULLs in the result.
```
Comment (mrks) [inline src/lib/operators/table_scan/column_vs_value_table_scan_impl.cpp]: Where does "MatchesAll" come from? It looks like an enum or a class.

Comment (mrzzzrm) [reply src/lib/operators/table_scan/column_vs_value_table_scan_impl.cpp]: My personal whimsy of camel casing every word that I want to stand out....
