### PR TITLE
Aggregate: When adding a Projection before an Aggregate, don't add unused columns

### LINKED ISSUE #1239: SELECT COUNT(1) does not work
```
(debug)!> SELECT COUNT(1) FROM t
terminate called after throwing an instance of 'std::logic_error'
  what():  src/lib/logical_query_plan/abstract_lqp_node.cpp:207 This node has no column '1'
```

### PR DESCRIPTION
**Pull request by mrks**
Previously, a Projection was added in front of every Aggregate to prepare things like `SUM(a+b)`. That projection would include all previous columns, even those discarded by the Aggregate. As the Aggregate would materialize all columns, that resulted in unnecessary work.

Also, this finally gets one of the queries above 200 items/s. ;)
Also, fixes #1239.

Before (TPC-H Q6): 
screenshot 2018-10-22 at 17 35 26

Now:
screenshot 2018-10-22 at 17 36 05

```
+-----------+---------------+-------+---------------+-------+--------+---------------------------------+
| Benchmark | prev. iter/s  | runs  | new iter/s    | runs  | change | p-value (significant if <0.001) |
+-----------+---------------+-------+---------------+-------+--------+---------------------------------+
| TPC-H 1   | 4.40639781952 | 265   | 5.30486726761 | 319   | +20%   |                          0.0000 |
| TPC-H 2   | 112.906433105 | 6775  | 114.690803528 | 6882  | +2%    |     (run time too short) 0.0000 |
| TPC-H 3   | 57.4701728821 | 3449  | 60.1957435608 | 3612  | +5%    |     (run time too short) 0.0000 |
| TPC-H 4   | 22.3861083984 | 1344  | 22.2296047211 | 1334  | -1%    |     (run time too short) 0.0000 |
| TPC-H 5   | 48.2288169861 | 2894  | 48.8474121094 | 2931  | +1%    |     (run time too short) 0.0000 |
| TPC-H 6   | 121.251754761 | 7276  | 128.708496094 | 7723  | +6%    |     (run time too short) 0.0000 |
| TPC-H 7   | 13.4902563095 | 810   | 12.9428510666 | 777   | -4%    |     (run time too short) 0.0000 |
| TPC-H 8   | 81.6524505615 | 4900  | 82.1357650757 | 4929  | +1%    |     (run time too short) 0.0000 |
| TPC-H 9   | 25.1611022949 | 1510  | 25.1464252472 | 1509  | -0%    |     (run time too short) 0.4843 |
| TPC-H 10  | 31.4642696381 | 1888  | 30.134771347  | 1809  | -4%    |     (run time too short) 0.0000 |
| TPC-H 11  | 176.11126709  | 10000 | 201.746307373 | 10000 | +15%   |     (run time too short) 0.0000 |
| TPC-H 12  | 55.1143455505 | 3307  | 58.0923233032 | 3486  | +5%    |     (run time too short) 0.0000 |
| TPC-H 13  | 27.1664848328 | 1630  | 27.3592720032 | 1642  | +1%    |     (run time too short) 0.0000 |
| TPC-H 14  | 138.363037109 | 8302  | 174.277603149 | 10000 | +26%   |     (run time too short) 0.0000 |
| TPC-H 15  | 61.4931755066 | 3690  | 70.0050811768 | 4201  | +14%   |     (run time too short) 0.0000 |
| TPC-H 16  | 69.5052490234 | 4171  | 70.2973251343 | 4218  | +1%    |     (run time too short) 0.0000 |
| TPC-H 17  | 4.34858798981 | 261   | 4.34827947617 | 261   | -0%    |                          0.9753 |
| TPC-H 18  | 19.8779430389 | 1193  | 19.9056377411 | 1195  | +0%    |     (run time too short) 0.0699 |
| TPC-H 19  | 1.48631441593 | 90    | 1.49421310425 | 90    | +1%    |                          0.0529 |
| TPC-H 20  | 2.74949455261 | 166   | 2.76349020004 | 166   | +1%    |                          0.0042 |
| TPC-H 21  | 1.29217803478 | 78    | 1.30081343651 | 79    | +1%    |                          0.1305 |
| TPC-H 22  | 118.539421082 | 7113  | 117.99005127  | 7080  | -0%    |     (run time too short) 0.0000 |
| average   |               |       |               |       | +4%    |                                 |
+-----------+---------------+-------+---------------+-------+--------+---------------------------------+
```

### CODE REVIEW

File: src/lib/sql/sql_translator.cpp [hunk 1]
```diff
@@ -782,6 +794,18 @@ void SQLTranslator::_translate_select_list_groupby_having(const hsql::SelectStat
     if (hsql_expr->type == hsql::kExprStar) {
       AssertInput(_from_clause_result, "Can't SELECT with wildcards since there are no FROM tables specified");
 
+      if (is_aggregate) {
+        // SELECT * is only valid if every input column in named in the GROUP BY clause
```
Comment (mrks) [inline src/lib/sql/sql_translator.cpp]: This was handled differently before (including all columns from the group by list), but I believe this is the only correct way to do it. MySQL is weird anyway in that it generally allows non-GROUP BY columns to be added and simply picks the first (or any?) row. Postgres agrees:

http://sqlfiddle.com/#!17/683eb/1

Comment (Bouncner) [reply src/lib/sql/sql_translator.cpp]: Did not know MySQL allows such things. I would have expected the behavior you've apparently implemented (I just read the comment ;) ).

File: src/lib/operators/aggregate.cpp [hunk 2]
```diff
@@ -440,6 +440,9 @@ void Aggregate::_aggregate() {
 
     const auto& hash_keys = keys_per_chunk[chunk_id];
 
+    // Sometimes, gcc is really bad at accessing loop conditions only once, so we cache that here.
+    const auto input_chunk_size = chunk_in->size();
```
Comment (Bouncner) [inline src/lib/operators/aggregate.cpp]: This reminds me of http://llvm.org/docs/CodingStandards.html#don-t-evaluate-end-every-time-through-a-loop.
Just as a side note ...

Comment (mrks) [reply src/lib/operators/aggregate.cpp]: That's a good summary of the problem. We probably should include that in the seminar at some point

File: src/lib/sql/sql_translator.cpp [hunk 3]
```diff
@@ -757,14 +757,26 @@ void SQLTranslator::_translate_select_list_groupby_having(const hsql::SelectStat
...
-    _current_lqp = ProjectionNode::make(pre_aggregate_expressions, _current_lqp);
-  }
+  const auto is_aggregate = !aggregate_expressions.empty() || !group_by_expressions.empty();
+
+  const auto pre_aggregate_lqp = _current_lqp;
 
   // Build Aggregate
-  const auto is_aggregate = !aggregate_expressions.empty() || !group_by_expressions.empty();
   if (is_aggregate) {
+    // Build pre_aggregate_projection, i.e. evaluate all Expression required for GROUP BY/Aggregates
```
Comment (mrzzzrm) [inline src/lib/sql/sql_translator.cpp]: Few points for this block: I know it's c/p, but there is no variable "pre_aggregate_projection", but the comment suggests so.

```c++
const auto aggregate_argument_required_computation = std::any_of(pre_aggregate_expressions.begin(), pre_aggregate_expressions.end(), [&](const auto& aggregate_argument) {
  return !_current_lqp->find_column_id(*expression);
});
```

would be shorter and clearer to me.

File: src/lib/sql/sql_translator.cpp [hunk 4]
```diff
@@ -782,6 +794,18 @@ void SQLTranslator::_translate_select_list_groupby_having(const hsql::SelectStat
     if (hsql_expr->type == hsql::kExprStar) {
       AssertInput(_from_clause_result, "Can't SELECT with wildcards since there are no FROM tables specified");
 
+      if (is_aggregate) {
```
Comment (mrzzzrm) [inline src/lib/sql/sql_translator.cpp]: This is unclear to me. You iterate over all pre_aggregate_expressions, which are the groupby expressions and arguments to aggregates. Then you assert that all of these are among the groupby columns. 

What about `SELECT * FROM x GROUP BY a, b HAVING SUM(x+y) > 5`? Wouldn't you needlessly require `x+y` to be part of the groupby expressions, here?
What about table-specific wildcards like in `SELECT t1.*, t2.a, SUM( t2.b) FROM t1, t2 GROUP BY t1.a, t1.b, t2.a`? Why would ` t2.b` need to be part of the groupby expressions?
Please add a bit of testing regarding these two scenarios.

File: src/lib/sql/sql_translator.cpp (hunk 3 above)
Comment (mrks) [reply src/lib/sql/sql_translator.cpp]: Fixed. Continued to use `any_expression_not_yet_available` instead of `aggregate_argument_required_computation` because we are not only talking about aggregate arguments, but also group by expressions

File: src/lib/sql/sql_translator.cpp (hunk 4 above)
Comment (mrks) [reply src/lib/sql/sql_translator.cpp]: > What about SELECT * FROM x GROUP BY a, b HAVING SUM(x+y) > 5? Wouldn't you needlessly require x+y to be part of the groupby expressions, here?

Assuming you mean `SUM(a+b)`, that still works because `a+b` is not part of the `pre_aggregate_lqp`.

We do not have any HAVING tests, so I will add two.

>  What about table-specific wildcards like in SELECT t1.*, t2.a, SUM( t2.b) FROM t1, t2 GROUP BY t1.a, t1.b, t2.a? Why would t2.b need to be part of the groupby expressions?

Optimally, I would like the computer to blow up into the user who comes up with that query. :(

Fixed and added tests.

File: src/lib/sql/sql_translator.cpp [hunk 5]
```diff
@@ -683,34 +683,34 @@ SQLTranslator::TableSourceState SQLTranslator::_translate_cross_product(const st
...
-
     /**
      * If the AggregateExpression has already been computed in a previous node (consider "x" in
      * "SELECT x FROM (SELECT MIN(a) as x FROM t) AS y)", it doesn't count as a new Aggregate and is therefore not
      * considered an "Aggregate" in the current SELECT list. Handling this as a special case seems hacky to me as well,
      * but it's the best solution I can come up with right now.
      */
-    if (_current_lqp->find_column_id(*sub_expression)) return ExpressionVisitation::DoNotVisitArguments;
+    if (_current_lqp->find_column_id(*sub_expression)) {
+      if (pre_aggregate_expression_set.emplace(sub_expression).second) {
```
Comment (mrzzzrm) [inline src/lib/sql/sql_translator.cpp]: Can you remember why 

```c++

      if (pre_aggregate_expression_set.emplace(sub_expression).second) {
        pre_aggregate_expressions.emplace_back(sub_expression);
      }
```

was necessary here? I removed it and apart from affecting the order of columns in some non-root LQP nodes, it didn't break anything.

Also, the lambda is called "find_aggregates_and_arguments" and this block feels alien here as it doesn't work with aggregates at all.

**Comment by mrzzzrm** [comment]
I pushed a commit containing my suggestion regarding that one code block. Feel free to revert

File: src/lib/sql/sql_translator.cpp (hunk 5 above)
Comment (mrks) [reply src/lib/sql/sql_translator.cpp]: Hmm, no, I can't find a way to break it even without that block. Seems logical as well, because if we don't add it here, it's not part of an aggregate. If it's not part of an aggregate, it has to be part of the `GROUP BY`, and will get added later.
