### PR TITLE
Use UnionAll for combining Index- and TableScan results

### LINKED ISSUE #1711: LQPTranslator uses wrong Union for combining the results of Index- and TableScan
The LQPTranslator uses the expensive UnionPositions which is meant for other use cases. Instead, the cheapest possible unioning method (UnionAll) should be used.

### PR DESCRIPTION
**Pull request by d-justen**
fixes  #1711

### CODE REVIEW

File: src/lib/optimizer/join_ordering/join_graph_builder.cpp [hunk 1]
```diff
@@ -83,15 +83,10 @@ void JoinGraphBuilder::_traverse(const std::shared_ptr<AbstractLQPNode>& node) {
        */
 
       const auto union_node = std::static_pointer_cast<UnionNode>(node);
+      const auto parse_result = _parse_union(union_node);
```
Comment (mrks) [inline src/lib/optimizer/join_ordering/join_graph_builder.cpp]: Could you please explain the changes in this file?

Comment (mrks) [reply src/lib/optimizer/join_ordering/join_graph_builder.cpp]: (Not in the code, but here)

Comment (d-justen) [reply src/lib/optimizer/join_ordering/join_graph_builder.cpp]: The original thought was that the distinction of UnionModes didn't make sense in the first place since there was only one. I basically just wanted to see if something bad happens if the UnionModes are treated the same there and then forgot about it.
Anyway, I don't really get yet why we should only parse and traverse over a UnionPositions, but not UnionAll.

Comment (mrks) [reply src/lib/optimizer/join_ordering/join_graph_builder.cpp]: Is this covered by any test at all?

Comment (d-justen) [reply src/lib/optimizer/join_ordering/join_graph_builder.cpp]: Actually, the UnionAll doesn't appear in any test (except for UnionAllTest of course)

Comment (mrks) [reply src/lib/optimizer/join_ordering/join_graph_builder.cpp]: Did I understand you right that you wanted to look into that? Otherwise, we should open an issue.

**Comment by Bouncner** [comment]
@bensk1: does that have a measurable impact on your work together with Marcel?

**Comment by Bensk1** [comment]
We were not working with partially indexed tables yet.
