### PR TITLE
LQPColumnReference

### LINKED ISSUE #568: Columns from subqueries incorrectly marked ambiguous
Doing this in the console:

```
(debug)> load src/test/tables/int_float.tbl int_float
(debug)> load src/test/tables/int_float2.tbl int_float2

(debug)> SELECT * FROM (SELECT "right".a a, "left".b b FROM int_float AS "left" LEFT JOIN int_float2 AS "right" ON "left".a = "right".a) t where t.a > 0
```

throws this exception: `Column name a is ambiguous.`.

Any idea why @mrzzzrm  ?

### PR DESCRIPTION
**Pull request by mrzzzrm**
Fixes #568

This PR changes the way Columns are referenced in the LQP. Previously a node would specify a Column using the index that Column had in its input node ("ColumnID"). This becomes cumbersome when the LQP is manipulated as ColumnIDs would need to be adjusted.

With this PR, the LQP nodes use a `LQPColumnOrigin` to reference to a Column, which consists of the node that creates this Column (either StoredTables, Aggregates or Arithmetics) and the ColumnID within that node. Only when creating the PQP are these `LQPColumnOrigins` resolved to ColumnIDs in the input nodes.

Besides making future optimizer rules less cumbersome, this reduces the amount of code in derived LQP node types. Most of the lifting is now done in `AbstractLQPNode`, with `output_column_origins()` and `output_column_names()` remaining the two essential methods for derived nodes to override, if they change the column layout.

This made it necessary to introduce `LQPExpression` (referring to Columns via `LQPColumnOrigin`s) and `OperatorExpression` (using `ColumnID`s), both CRTP deriving from `BaseExpression`. 

## Suggestion for Reviewers
Look into the changes in `abstract_lqp_node` first, then into the remaining changes in `lib/logical_query_plan/`, then into the SQL/LQP Translator. Save the changes in tests and all the renamings for later.

## Things I don't like myself and am aware of 
- Deep copying a LQP node has become cumbersome, because of ColumnOrigin cloning. 

## ToDo

* [x] Refactor LQPColumnOrigin to LQPColumnReference
* [x] LQPDeepCopy: Use std::transform? @mrks
* [x] LQPDeepCopy: left child -> copied left child
* [x] Pair VS ColumnID[2]  @mrks
* [x] deep_copy_column_origin -> adapt column origin to different lqp @mrks
* [x] NamedColumnReference -> QualifiedColumnName @mrks
* [x] find_column_origin_by_named_column_reference -> find_column
* [x] _resolve_local_column_prefix & "what is a column prefix?" @mrks
* [x] doc deep_copy_column_origin

### CODE REVIEW

**Comment by TwoLaid** [comment]
> +3,226 −2,790 

well, fuck. 😆

File: src/lib/operators/abstract_join_operator.cpp [hunk 1]
```diff
@@ -10,15 +10,15 @@ namespace opossum {
 
 AbstractJoinOperator::AbstractJoinOperator(const std::shared_ptr<const AbstractOperator> left,
                                            const std::shared_ptr<const AbstractOperator> right, const JoinMode mode,
-                                           const std::pair<ColumnID, ColumnID>& column_ids, const ScanType scan_type)
+                                           const JoinColumnIDs& column_ids, const ScanType scan_type)
```
Comment (mrks) [inline src/lib/operators/abstract_join_operator.cpp]: ColumnID[2]?

File: src/lib/logical_query_plan/lqp_translator.cpp [hunk 2]
```diff
@@ -146,65 +159,62 @@ std::shared_ptr<AbstractOperator> LQPTranslator::_translate_join_node(
...
+        return aggregate_expression->aggregate_function_arguments()[0]->is_arithmetic_operator();
+      });
 
   /**
-   * If there are arithmetic expressions create a Projection with:
-   *
-   *  - arithmetic expressions,
-   *  - columns used in aggregate functions, and
-   *  - GROUP BY columns
+   * If there are arithmetic expressions create a Projection with:   *
```
Comment (mrks) [inline src/lib/logical_query_plan/lqp_translator.cpp]: stray `*`

Comment (mrks) [reply src/lib/logical_query_plan/lqp_translator.cpp]: Also the "then" part is missing.

File: src/lib/logical_query_plan/lqp_translator.cpp [hunk 3]
```diff
@@ -217,46 +227,52 @@ std::shared_ptr<AbstractOperator> LQPTranslator::_translate_aggregate_node(
...
         continue;
       }
 
       // Add original expression of the function to the Projection.
-      column_expressions.emplace_back(aggregate_expression->expression_list()[0]);
+      Assert(aggregate_expression->aggregate_function_arguments().size() == 1,
+             "Aggregate functions with more than one argument not supported right now");
+      const auto argument_lqp_expression =
+          std::dynamic_pointer_cast<OperatorExpression>(aggregate_expression->aggregate_function_arguments()[0]);
+      DebugAssert(argument_lqp_expression, "Expression in AggregateNode was not an LQPExpression");
```
Comment (mrks) [inline src/lib/logical_query_plan/lqp_translator.cpp]: I think we always use present tense in error messages

File: src/lib/logical_query_plan/lqp_translator.cpp [hunk 4]
```diff
@@ -217,46 +227,52 @@ std::shared_ptr<AbstractOperator> LQPTranslator::_translate_aggregate_node(
...
   aggregate_definitions.reserve(aggregate_expressions.size());
 
   for (const auto& aggregate_expression : aggregate_expressions) {
     DebugAssert(aggregate_expression->type() == ExpressionType::Function, "Only functions are supported in Aggregates");
 
     const auto aggregate_function_type = aggregate_expression->aggregate_function();
-    const auto root_expr = (aggregate_expression->expression_list())[0];
+    const auto argument_expression =
+        std::dynamic_pointer_cast<OperatorExpression>(aggregate_expression->aggregate_function_arguments()[0]);
+    DebugAssert(argument_expression, "Couldn't cast Expression to OperatorExpression.");
```
Comment (mrks) [inline src/lib/logical_query_plan/lqp_translator.cpp]: This error message is too close to the implementation and redundant. Something like "The aggregate function argument is not an expression"?

File: src/lib/logical_query_plan/lqp_translator.cpp [hunk 5]
```diff
@@ -396,4 +409,19 @@ std::shared_ptr<AbstractOperator> LQPTranslator::_translate_by_node_type(
   }
 }
 
+std::vector<std::shared_ptr<OperatorExpression>> LQPTranslator::_translate_expressions(
+    const std::vector<std::shared_ptr<LQPExpression>>& lqp_expressions,
+    const std::shared_ptr<AbstractLQPNode>& node) const {
+  Assert(node->left_child() && !node->right_child(), "Can only translate expressions if there is one input node");
```
Comment (mrks) [inline src/lib/logical_query_plan/lqp_translator.cpp]: why?

File: src/lib/logical_query_plan/mock_node.hpp [hunk 6]
```diff
@@ -6,28 +6,41 @@
...
+ *  - (mocked) statistics
+ *  - or just a column layout. It will pretend it created the columns.
+ * It is useful in tests (e.g. general LQP tests, optimizer tests that just rely on statistics and not actual data) and
+ * the playground
  */
 class MockNode : public AbstractLQPNode {
  public:
-  MockNode();
-  explicit MockNode(const std::shared_ptr<TableStatistics>& statistics);
+  using ColumnDefinitions = std::vector<std::pair<DataType, std::string>>;
```
Comment (mrks) [inline src/lib/logical_query_plan/mock_node.hpp]: I see a value here, and this does not need to change. Still, I want to comment that hiding everything in aliases does not necessarily improve readability. While it makes the code shorter, it increases the number of indirections that others need to keep track of.

File: src/lib/logical_query_plan/mock_node.hpp [hunk 7]
```diff
@@ -6,28 +6,41 @@
...
+
+  explicit MockNode(const std::optional<std::string>& alias = std::nullopt);
```
Comment (mrks) [inline src/lib/logical_query_plan/mock_node.hpp]: When would a mock node without columns make sense?

File: src/lib/logical_query_plan/mock_node.hpp [hunk 8]
```diff
@@ -6,28 +6,41 @@
...
-  std::shared_ptr<AbstractLQPNode> _deep_copy_impl() const override;
+  std::shared_ptr<AbstractLQPNode> _deep_copy_impl(const std::shared_ptr<AbstractLQPNode>& left_child,
+                                                   const std::shared_ptr<AbstractLQPNode>& right_child) const override;
 
  private:
   std::vector<std::string> _output_column_names;
+
+  // Constructor args to keep around for deep_copy()
+  std::optional<ColumnDefinitions> _column_definitions;
+  std::optional<std::shared_ptr<TableStatistics>> _table_statistics;
```
Comment (mrks) [inline src/lib/logical_query_plan/mock_node.hpp]: union?

File: src/lib/logical_query_plan/projection_node.cpp [hunk 9]
```diff
@@ -36,17 +36,20 @@ std::string ProjectionNode::description() const {
...
 
-std::shared_ptr<AbstractLQPNode> ProjectionNode::_deep_copy_impl() const {
-  std::vector<std::shared_ptr<Expression>> column_expressions;
-  column_expressions.reserve(_column_expressions.size());
-  for (const auto& expression : _column_expressions) {
-    column_expressions.emplace_back(expression->deep_copy());
-  }
+std::shared_ptr<AbstractLQPNode> ProjectionNode::_deep_copy_impl(
+    const std::shared_ptr<AbstractLQPNode>& left_child, const std::shared_ptr<AbstractLQPNode>& right_child) const {
+  Assert(this->left_child() && left_child, "Can't deep copy without child to adjust ColumnOrigins");
```
Comment (mrks) [inline src/lib/logical_query_plan/projection_node.cpp]: I don't understand this error message. This might be because I don't understand the function in general.

File: src/lib/logical_query_plan/sort_node.cpp [hunk 10]
```diff
@@ -9,14 +9,23 @@
...
-  return std::make_shared<SortNode>(_order_by_definitions);
+std::shared_ptr<AbstractLQPNode> SortNode::_deep_copy_impl(const std::shared_ptr<AbstractLQPNode>& left_child,
+                                                           const std::shared_ptr<AbstractLQPNode>& right_child) const {
+  OrderByDefinitions order_by_definitions;
+  std::transform(_order_by_definitions.begin(), _order_by_definitions.end(), std::back_inserter(order_by_definitions),
+                 [&](const auto& order_by_definition) {
+                   return OrderByDefinition{
+                       this->left_child()->deep_copy_column_origin(order_by_definition.column_origin, left_child),
+                       order_by_definition.order_by_mode};
+                 });
```
Comment (mrks) [inline src/lib/logical_query_plan/sort_node.cpp]:
```
for(const auto &definition : _order_by_definitions) {
  order_by_definitions.emplace_back(this->left_child()->deep_copy_column_origin(order_by_definition.column_origin, left_child),
                                    order_by_definition.order_by_mode);
}
```

is shorter by more than 100 characters and is easier to read. Any reason to use transform and back_inserter here? Same in other places.

File: src/benchmark/operators/projection_benchmark.cpp [hunk 11]
```diff
@@ -35,7 +36,7 @@ class OperatorsProjectionBenchmark : public BenchmarkBasicFixture {
 BENCHMARK_DEFINE_F(OperatorsProjectionBenchmark, BM_ProjectionSimple)(benchmark::State& state) {
   clear_cache();
 
-  Projection::ColumnExpressions expressions = {Expression::create_column(ColumnID{0} /* "a" */)};
+  Projection::ColumnExpressions expressions = {OperatorExpression::create_column(ColumnID{0} /* "a" */)};
```
[the remark this answers is not in the document]
Comment (mrks) [reply src/benchmark/operators/projection_benchmark.cpp]: Also, "OperatorExpression" might be understood as if it was an expression containing or referring to an operator.

File: src/lib/operators/operator_expression.cpp [hunk 12]
```diff
@@ -0,0 +1,77 @@
...
+  expression->_alias = alias;
+
+  return expression;
+}
+
+OperatorExpression::OperatorExpression(const std::shared_ptr<LQPExpression>& lqp_expression,
+                                       const std::shared_ptr<AbstractLQPNode>& node)
+    : BaseExpression<OperatorExpression>(lqp_expression->_type) {
+  /**
+   * Ugly, but anyway: Copy all fields from LQPExpression and transform ColumnOrigins to ColumnIDs
```
Comment (mrks) [inline src/lib/operators/operator_expression.cpp]: "Ugly, but anyway" doesn't help anyone. Either it is has to be done like this for a reason or not.

File: src/lib/operators/operator_expression.cpp [hunk 13]
```diff
@@ -0,0 +1,77 @@
...
+std::shared_ptr<OperatorExpression> OperatorExpression::create_column(const ColumnID column_id,
+                                                                      const std::optional<std::string>& alias) {
+  auto expression = std::make_shared<OperatorExpression>(ExpressionType::Column);
+  expression->_column_id = column_id;
+  expression->_alias = alias;
+
+  return expression;
+}
+
+OperatorExpression::OperatorExpression(const std::shared_ptr<LQPExpression>& lqp_expression,
```
Comment (mrks) [inline src/lib/operators/operator_expression.cpp]: This looks like part of translating an LQP to a PQP. As such, it is surprising to find it in `src/lib/operators`.

File: src/benchmark/operators/projection_benchmark.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/benchmark/operators/projection_benchmark.cpp]: Thought the same. Will rename.

File: src/lib/all_parameter_variant.hpp [hunk 14]
```diff
@@ -18,8 +19,9 @@ namespace hana = boost::hana;
 // This holds pairs of all types and their respective string representation
 static constexpr auto parameter_types =
     hana::make_tuple(hana::make_pair("AllTypeVariant", hana::type_c<AllTypeVariant>),
-                     hana::make_pair("ColumnID", hana::type_c<ColumnID>),              // NOLINT
-                     hana::make_pair("Placeholder", hana::type_c<ValuePlaceholder>));  // NOLINT
+                     hana::make_pair("ColumnID", hana::type_c<ColumnID>),                // NOLINT
+                     hana::make_pair("LQPColumnOrigin", hana::type_c<LQPColumnOrigin>),  // NOLINT
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/all_parameter_variant.hpp]: Don't like LQPColumnOrigin as a name either, LogicalColumnReference sounds nice. Would refrain from PhysicalColumnID because the type is used in the LQP as well

[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/all_parameter_variant.hpp]: BUT: LogicalColumnReference doesn't make that much sense. What is a "Logical" Column Reference? LQPColumnReference comes to mind, what do you think about that? @mrks

File: src/lib/base_expression.cpp [hunk 15]
```diff
@@ -0,0 +1,398 @@
...
+std::shared_ptr<DerivedExpressionType> BaseExpression<DerivedExpressionType>::deep_copy() const {
+  // We cannot use the copy constructor here, because it does not work with shared_from_this()
+  auto deep_copy = std::make_shared<DerivedExpressionType>(_type);
+  deep_copy->_value = _value;
+  deep_copy->_aggregate_function = _aggregate_function;
+  deep_copy->_table_name = _table_name;
+  deep_copy->_alias = _alias;
+  deep_copy->_value_placeholder = _value_placeholder;
+
+  std::vector<std::shared_ptr<DerivedExpressionType>> aggregate_function_arguments;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/base_expression.cpp]: Question of taste - and I guess your taste outweighs mine here ;)

File: src/lib/all_parameter_variant.hpp (hunk 14 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/all_parameter_variant.hpp]: (Keep in mind that LQPColumnOrigins are not supposed to have a node member pointing to an arbitrary node, but to the specific node that created the column.)

File: src/lib/base_expression.cpp [hunk 16]
```diff
@@ -0,0 +1,398 @@
...
+    case ExpressionType::NotEquals:
+    case ExpressionType::LessThan:
+    case ExpressionType::LessThanEquals:
+    case ExpressionType::GreaterThan:
+    case ExpressionType::GreaterThanEquals:
+    case ExpressionType::Like:
+    case ExpressionType::NotLike:
+    case ExpressionType::And:
+    case ExpressionType::Or:
+    case ExpressionType::Between:
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/base_expression.cpp]: Between takes two arguments, that's why - it has two children. And it's not the same as is_logical_operator because is_binary_operator also cover +,-,*,/

[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/base_expression.cpp]: (wouldn't argue to much about it, I want Expression gone anyway, soon.)

File: src/lib/base_expression.hpp [hunk 17]
```diff
@@ -6,13 +6,17 @@
...
+#include "logical_query_plan/lqp_column_origin.hpp"
 #include "types.hpp"
+#include "utils/assert.hpp"
 
 namespace opossum {
 
 class AbstractLQPNode;
 
 /**
+ * CRTP class forming the base class for LQPExpression and OperatorExpression
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/base_expression.hpp]: done

File: src/lib/base_expression.hpp [hunk 18]
```diff
@@ -23,7 +27,8 @@ class AbstractLQPNode;
  * For now we decided to have a single Expression without further specializations. This goes hand in hand with the
  * approach used in hsql::Expr.
  */
-class Expression : public std::enable_shared_from_this<Expression>, private Noncopyable {
+template <typename DerivedExpressionType>
+class BaseExpression : public std::enable_shared_from_this<DerivedExpressionType>, private Noncopyable {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/base_expression.hpp]: Don't feel like arguing about this kind of naming, AbstractExpression it will become

File: src/lib/base_expression.hpp [hunk 19]
```diff
@@ -42,55 +47,47 @@ class Expression : public std::enable_shared_from_this<Expression>, private Nonc
...
-                                                   const std::optional<std::string>& alias = std::nullopt);
-
-  static std::vector<std::shared_ptr<Expression>> create_columns(
-      const std::vector<ColumnID>& column_ids, const std::optional<std::vector<std::string>>& aliases = std::nullopt);
-
   // A literal can have an alias in order to allow queries like `SELECT 1 as one FROM t`.
-  static std::shared_ptr<Expression> create_literal(const AllTypeVariant& value,
-                                                    const std::optional<std::string>& alias = std::nullopt);
+  static std::shared_ptr<DerivedExpressionType> create_literal(const AllTypeVariant& value,
+                                                               const std::optional<std::string>& alias = std::nullopt);
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/base_expression.hpp]: Seems like we don't, could have sworn we do. Will change

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 20]
```diff
@@ -19,13 +20,23 @@ class TableStatistics;
...
+
   return deep_copy;
 }
 
+LQPColumnOrigin AbstractLQPNode::deep_copy_column_origin(const LQPColumnOrigin& column_origin,
+                                                         const std::shared_ptr<AbstractLQPNode>& lqp_copy) const {
+  Assert(output_column_count() == lqp_copy->output_column_count(), "lqp_copy must be a copy of this");
+  return lqp_copy->output_column_origins()[get_output_column_id_by_column_origin(column_origin)];
+}
+
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: And the comment in the header doesn't explain it sufficiently?

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 21]
```diff
@@ -170,86 +181,138 @@ const std::vector<std::string>& AbstractLQPNode::output_column_names() const {
   return left_child()->output_column_names();
 }
 
-const std::vector<ColumnID>& AbstractLQPNode::output_column_ids_to_input_column_ids() const {
+const std::vector<LQPColumnOrigin>& AbstractLQPNode::output_column_origins() const {
   /**
-   * This function has to be overwritten if columns or their order are in any way redefined by this Node.
-   * Examples include Projections, Aggregates, and Joins.
+   * Default implementation of output_column_origins() will return the ColumnOrigins of the left_child if it exists,
+   * otherwise will pretend the all Columns originate in this node.
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: yep

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 22]
```diff
@@ -170,86 +181,138 @@ const std::vector<std::string>& AbstractLQPNode::output_column_names() const {
...
    */
-  DebugAssert(left_child() && !right_child(),
-              "Node has no or two inputs and therefore needs to override this function.");
 
-  if (!_output_column_ids_to_input_column_ids) {
-    _output_column_ids_to_input_column_ids.emplace(output_column_count());
-    std::iota(_output_column_ids_to_input_column_ids->begin(), _output_column_ids_to_input_column_ids->end(),
-              ColumnID{0});
+  if (!_output_column_origins) {
+    Assert(!left_child() || !right_child(), "Nodes with both children need to override");
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: as you wish

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 23]
```diff
@@ -170,86 +181,138 @@ const std::vector<std::string>& AbstractLQPNode::output_column_names() const {
...
   /**
-   * This function has to be overwritten if columns or their order are in any way redefined by this Node.
-   * Examples include Projections, Aggregates, and Joins.
+   * If this node carries an alias, that is different from that of the NamedColumnReference, we can't resolve the column
+   * in this node.
    */
-  DebugAssert(left_child() && !right_child(),
-              "Node has no or two inputs and therefore needs to override this function");
+  const auto named_column_reference_without_local_column_prefix = _resolve_local_column_prefix(named_column_reference);
+  if (!named_column_reference_without_local_column_prefix) {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: could turn this into "named column reference prefix". The table_1 part in "table_1.a" - but "table_1" could also be an alias, that's why I didn't call it a "table_name" - or should I? Your call, have no preference here.

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 24]
```diff
@@ -170,86 +181,138 @@ const std::vector<std::string>& AbstractLQPNode::output_column_names() const {
...
+    return std::nullopt;
+  }
 
-  auto named_column_reference_without_local_alias = _resolve_local_alias(named_column_reference);
-  if (!named_column_reference_without_local_alias) {
-    return {};
-  } else {
-    return left_child()->find_column_id_by_named_column_reference(*named_column_reference_without_local_alias);
+  /**
+   * If the table name got resolved, look for the Column in the output of this node
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: The phrase you added would be incorrect, imo. The important part is "resolved" as is "_resolve_local_column_prefix()" which means "if the node has an alias and that alias matches the table_name OR the table_name is not set OR the node is a StoredTableNode and its table_name matches the NamedColumnReferences table_name".
Either I add that - or people just look up what "_resolve_local_column_prefix()" does

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 25]
```diff
@@ -170,86 +181,138 @@ const std::vector<std::string>& AbstractLQPNode::output_column_names() const {
...
+std::shared_ptr<const AbstractLQPNode> AbstractLQPNode::find_table_name_origin(const std::string& table_name) const {
+  // If this node has an ALIAS that matches the table_name, this is the node we're looking for
+  if (_table_alias && *_table_alias == table_name) {
+    return shared_from_this();
+  }
 
-  if (!knows_table(table_name)) {
-    return {};
+  // If this node has an ALIAS, looking for the table_name for children is "blocked". THe same is true if there are no
+  // children
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: yep

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 26]
```diff
@@ -170,86 +181,138 @@ const std::vector<std::string>& AbstractLQPNode::output_column_names() const {
...
 
-  if (_table_alias && *_table_alias == table_name) {
-    return get_output_column_ids();
+  const auto table_name_origin_in_left_child = left_child()->find_table_name_origin(table_name);
+
+  if (right_child()) {
+    const auto table_name_origin_in_right_child = right_child()->find_table_name_origin(table_name);
+
+    if (table_name_origin_in_left_child && table_name_origin_in_right_child) {
+      // Both children could resolve to the same Node, i.e. in UnionNodes that emulate an OR
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: okidoki

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 27]
```diff
@@ -170,86 +181,138 @@ const std::vector<std::string>& AbstractLQPNode::output_column_names() const {
...
 }
 
-std::optional<ColumnID> AbstractLQPNode::find_column_id_by_named_column_reference(
+std::optional<LQPColumnOrigin> AbstractLQPNode::find_column_origin_by_named_column_reference(
     const NamedColumnReference& named_column_reference) const {
   /**
-   * This function has to be overwritten if columns or their order are in any way redefined by this Node.
-   * Examples include Projections, Aggregates, and Joins.
+   * If this node carries an alias, that is different from that of the NamedColumnReference, we can't resolve the column
+   * in this node.
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: done

File: src/lib/logical_query_plan/abstract_lqp_node.hpp [hunk 28]
```diff
@@ -286,26 +275,28 @@ class AbstractLQPNode : public std::enable_shared_from_this<AbstractLQPNode>, pr
...
    */
-  std::optional<NamedColumnReference> _resolve_local_alias(const NamedColumnReference& named_column_reference) const;
+  virtual std::optional<NamedColumnReference> _resolve_local_column_prefix(
+      const NamedColumnReference& named_column_reference) const;
+
+  /**
+   * @return the @param expression (you will probably want to pass in a deep_copy), with all ColumnOrigins pointing to
+   * their equivalent in a deep_copy()ed LQP
+   */
+  std::shared_ptr<LQPExpression> _adjust_expression_to_lqp(const std::shared_ptr<LQPExpression>& expression,
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.hpp]: It will make all ColumnOrigins in an Expression point to another LQP than they previously did. Ugly, but I think that's what we have to do with the current architecture.

File: src/lib/logical_query_plan/aggregate_node.hpp [hunk 29]
```diff
@@ -21,25 +24,23 @@ class Expression;
...
 
-  std::optional<ColumnID> find_column_id_by_named_column_reference(
-      const NamedColumnReference& named_column_reference) const override;
+  const std::vector<std::string>& output_column_names() const override;
+  const std::vector<LQPColumnOrigin>& output_column_origins() const override;
 
   // @{
   /**
-   * AggregateNode::find_column_id_for_expression() looks for the @param expression in the columns this
+   * AggregateNode::find_column_origin_for_expression() looks for the @param expression in the columns this
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/aggregate_node.hpp]: fixed

File: src/lib/logical_query_plan/aggregate_node.hpp [hunk 30]
```diff
@@ -49,21 +50,21 @@ class AggregateNode : public AbstractLQPNode {
...
   // @}
 
-  std::vector<ColumnID> get_output_column_ids_for_table(const std::string& table_name) const override;
-
   std::string get_verbose_column_name(ColumnID column_id) const override;
 
  protected:
-  std::shared_ptr<AbstractLQPNode> _deep_copy_impl() const override;
+  std::shared_ptr<AbstractLQPNode> _deep_copy_impl(const std::shared_ptr<AbstractLQPNode>& left_child,
+                                                   const std::shared_ptr<AbstractLQPNode>& right_child) const override;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/aggregate_node.hpp]: Docs are in the Declaration in the base class right where they belong - is that not sufficient?

File: src/lib/logical_query_plan/lqp_column_origin.hpp [hunk 31]
```diff
@@ -0,0 +1,30 @@
...
+
+#include <memory>
+
+#include "types.hpp"
+
+namespace opossum {
+
+class AbstractLQPNode;
+
+class LQPColumnOrigin final {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/lqp_column_origin.hpp]: oh, embarrassing

File: src/lib/logical_query_plan/lqp_expression.cpp [hunk 32]
```diff
@@ -0,0 +1,67 @@
...
+    for (auto column_index = 0u; column_index < column_origins.size(); ++column_index) {
+      column_expressions.emplace_back(create_column(column_origins[column_index], (*aliases)[column_index]));
+    }
+  }
+
+  return column_expressions;
+}
+
+const LQPColumnOrigin& LQPExpression::column_origin() const {
+  DebugAssert(_column_origin, "Expression " + expression_type_to_string.at(_type) + " does not have a LQPColumnOrigin");
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/lqp_expression.cpp]: I could Assert(type==Column) and then that the optional is actually engaged - but imo as far as this method is concerned, this Assert is sufficient. We do the same in all getters in AbstractExpression, by the way.

File: src/lib/logical_query_plan/lqp_expression.cpp [hunk 33]
```diff
@@ -0,0 +1,67 @@
...
+  return *_column_origin;
+}
+
+void LQPExpression::set_column_origin(const LQPColumnOrigin& column_origin) {
+  Assert(_type == ExpressionType::Column, "Can't set a LQPColumnOrigin on a non-column");
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/lqp_expression.cpp]: yup

File: src/lib/logical_query_plan/lqp_expression.hpp [hunk 34]
```diff
@@ -0,0 +1,39 @@
...
+class LQPExpression : public BaseExpression<LQPExpression> {
+ public:
+  static std::shared_ptr<LQPExpression> create_column(const LQPColumnOrigin& column_origin,
+                                                      const std::optional<std::string>& alias = std::nullopt);
+
+  static std::vector<std::shared_ptr<LQPExpression>> create_columns(
+      const std::vector<LQPColumnOrigin>& column_origins,
+      const std::optional<std::vector<std::string>>& aliases = std::nullopt);
+
+  using BaseExpression<LQPExpression>::BaseExpression;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/lqp_expression.hpp]: In all AbstractExpression<T>::create* methods. Will add comment

File: src/lib/logical_query_plan/lqp_translator.cpp (hunk 2 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/lqp_translator.cpp]: removed the *. What "then" part. The comment makes sense to me

File: src/lib/logical_query_plan/lqp_translator.cpp (hunk 3 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/lqp_translator.cpp]: done

File: src/lib/logical_query_plan/lqp_translator.cpp (hunk 4 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/lqp_translator.cpp]: Na, that wouldn't have been the case here. Sometimes you have these asserts that you can just explain with "WTF, this is a unexpected and some sort of bug." - that's why I'll change it to "Wrong expression type found in LQP. Bug."

File: src/lib/logical_query_plan/lqp_translator.cpp (hunk 5 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/lqp_translator.cpp]: added "...can't resolve ColumnOrigins otherwise"

File: src/lib/logical_query_plan/mock_node.hpp (hunk 6 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/mock_node.hpp]: Yeah, I'd probably agree. Just hate things like `std::vector<std::shared_ptr<Something>>`...

File: src/lib/logical_query_plan/mock_node.hpp (hunk 7 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/mock_node.hpp]: I probably had the idea of building LQPs solely consisting of MockNodes to test basic LQP features but this of course doesn't make sense when nodes have multiple children. Will remove this variant.

File: src/lib/logical_query_plan/mock_node.hpp (hunk 8 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/mock_node.hpp]: hate dealing with variants, but as you wish.

Comment (mrzzzrm) [reply src/lib/logical_query_plan/mock_node.hpp]: I don't hate them in general, they are just so clumsy...

File: src/lib/logical_query_plan/sort_node.cpp (hunk 10 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/sort_node.cpp]: I agree, but then everyone tells me to "express my intent" and use stuff like std::generate and transorm and fill and whatnot....

File: src/lib/operators/abstract_join_operator.cpp (hunk 1 above)
Comment (mrzzzrm) [reply src/lib/operators/abstract_join_operator.cpp]: We've been using a pair here since forever and I don't see any value in an array.

File: src/lib/operators/operator_expression.cpp (hunk 12 above)
Comment (mrzzzrm) [reply src/lib/operators/operator_expression.cpp]: added explanation. Left the "ugly" part in because I want my reader to know that I agree with the sentiment he's likely having when seeing this

File: src/lib/types.hpp [hunk 35]
```diff
@@ -242,4 +244,20 @@ class Noncopyable {
   const Noncopyable& operator=(const Noncopyable&) = delete;
 };
 
+/**
+ * Aggregates are defined by the Column (ColumnID for Operators, ColumnOrigin in LQP) they operate on and the aggregate
+ * function they use.
+ * Optionally, an alias can be specified to use as the output name.
+ */
+template <typename ColumnReferenceType>
+struct AggregateColumnDefinitionTemplate {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/types.hpp]: Will move to own file. Wanted to stick with the "Aggregate" (PQP) vs "AggregateNode" (LQP) style and call this "AggregateColumnDefinition" in the PQP and "Aggregate**Node**ColumnDefinition" in the LQP - but then how call the template? Template suffix to the rescue and I don't care if this reminds someone of another language.

[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/types.hpp]: Moved it to aggregate.hpp for now, since I don't know where to put stuff shared by lqp and pqp

File: src/lib/operators/operator_expression.cpp (hunk 13 above)
Comment (mrzzzrm) [reply src/lib/operators/operator_expression.cpp]: tiny little uncleanness, but better than having a PQPExpression constructor that takes all the class' members as args and then put a translation methods that passes them in into the LQPTranslator - imo.

**Comment by mrzzzrm** [comment]
Let's discuss 
* LQPColumnOrigin naming
* LQP/ColumnOrigin and Expression cloning
in person, shall we?

File: src/lib/all_parameter_variant.hpp (hunk 14 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/all_parameter_variant.hpp]: works for me

File: src/lib/base_expression.cpp (hunk 16 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/base_expression.cpp]: I think I was unclear here. I wanted to say that most of the cases here are covered by `is_logical_operator`. Adding `if (is_logical_operator(...)) return true` would save a lot of lines.

between takes three arguments (a < x < b).

File: src/lib/logical_query_plan/abstract_lqp_node.cpp (hunk 23 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: I suggested something about "qualified column name" somewhere below. We should join those two discussions.

File: src/lib/logical_query_plan/abstract_lqp_node.cpp (hunk 24 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: ok

File: src/lib/logical_query_plan/abstract_lqp_node.hpp (hunk 28 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/logical_query_plan/abstract_lqp_node.hpp]: "adjust" is confusing, because it does not change anything. Also, isn't this a static method? I don't see `this` being used anywhere.

How about

```
std::shared_ptr<LQPExpression> _adapt_expression_to_different_lqp(const std::shared_ptr<LQPExpression>& expression, const std::shared_ptr<AbstractLQPNode>& other_lqp) const;
```

?

File: src/lib/logical_query_plan/abstract_lqp_node.cpp (hunk 20 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: Not really. I also don't understand how this relates to `_adjust_expression_to_lqp`.

File: src/lib/logical_query_plan/abstract_lqp_node.hpp [hunk 36]
```diff
@@ -267,8 +250,14 @@ class AbstractLQPNode : public std::enable_shared_from_this<AbstractLQPNode>, pr
   // @}
 
  protected:
-  // creates a DEEP copy of the other LQP node. Used for reusing LQPs, e.g., in views.
-  virtual std::shared_ptr<AbstractLQPNode> _deep_copy_impl() const = 0;
+  /**
+   * Override and creat a DEEP copy of the other LQP node. Used for reusing LQPs, e.g., in views.
```
Comment (mrks) [inline src/lib/logical_query_plan/abstract_lqp_node.hpp]: creat**e**

File: src/lib/logical_query_plan/aggregate_node.hpp (hunk 30 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/logical_query_plan/aggregate_node.hpp]: Missed it, sorry. But why do I have to give the deep copy method an already copied left_child. Couldn't it copy the child itself?

File: src/lib/logical_query_plan/lqp_translator.cpp (hunk 2 above)
Comment (mrks) [reply src/lib/logical_query_plan/lqp_translator.cpp]: Fresh day, fresh mind. Nevermind.

File: src/lib/operators/abstract_join_operator.cpp (hunk 1 above)
Comment (mrks) [reply src/lib/operators/abstract_join_operator.cpp]: That way we wouldn't have to write `std::pair<ColumnID, ColumnID>` everywhere, which you rightfully don't like because it it is too long, and we wouldn't have to come up with yet another type.

File: src/lib/logical_query_plan/aggregate_node.hpp (hunk 30 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/aggregate_node.hpp]: But then every _deep_copy_impl would have to do this - instead of just the base class doing it and passing the generated objects to the impl.

File: src/lib/logical_query_plan/abstract_lqp_node.hpp (hunk 28 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.hpp]: Could be a free method - not being tied to a single type (but to two: Expression and LQPNode) - but I renamed it and made it static.

File: src/lib/logical_query_plan/aggregate_node.hpp (hunk 30 above)
[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/logical_query_plan/aggregate_node.hpp]: Ok, since it is the internal implementation, we can do it that way. I think that renaming the parameters to `copied_left_child` would make it a bit easier to understand.

File: src/lib/all_parameter_variant.hpp (hunk 14 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/all_parameter_variant.hpp]: Proposal: Let's call it `LQPColumnReference` with members `origin_node` and `origin_column_id` - that makes semantics the most clear, imo.

[the remark this answers is not in the document]
Comment (mrks) [reply src/lib/all_parameter_variant.hpp]: ok

File: src/lib/operators/abstract_join_operator.cpp (hunk 1 above)
Comment (mrzzzrm) [reply src/lib/operators/abstract_join_operator.cpp]: The good thing about pair is that they have implicit bounds checking (via `first` and `second`), whereas when I see `_column_id[1]` somewhere I would instantly wonder whether this might go out of bounds. I opt for pairs.

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 37]
```diff
@@ -19,13 +20,32 @@ class TableStatistics;
...
+  deep_copy->set_left_child(copied_left_child);
+  deep_copy->set_right_child(copied_right_child);
+
   return deep_copy;
 }
 
+LQPColumnReference AbstractLQPNode::adapt_column_reference_to_different_lqp(
+    const LQPColumnReference& column_reference, const std::shared_ptr<AbstractLQPNode>& original_lqp,
+    const std::shared_ptr<AbstractLQPNode>& copied_lqp) {
+  Assert(original_lqp->output_column_count() == copied_lqp->output_column_count(), "lqp_copy must be a copy of this");
```
Comment (mrks) [inline src/lib/logical_query_plan/abstract_lqp_node.cpp]: This method is static, so "this" does not exist.

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 38]
```diff
@@ -169,86 +189,139 @@ const std::vector<std::string>& AbstractLQPNode::output_column_names() const {
...
    */
-  DebugAssert(left_child() && !right_child(),
-              "Node has no or two inputs and therefore needs to override this function.");
 
-  if (!_output_column_ids_to_input_column_ids) {
-    _output_column_ids_to_input_column_ids.emplace(output_column_count());
-    std::iota(_output_column_ids_to_input_column_ids->begin(), _output_column_ids_to_input_column_ids->end(),
-              ColumnID{0});
+  if (!_output_column_references) {
+    Assert(!left_child() || !right_child(), "Nodes that have two children must override this method");
```
Comment (mrks) [inline src/lib/logical_query_plan/abstract_lqp_node.cpp]: If `right_child() != nullptr`, we have a big problem and this assertion makes things worse. `Assert(!right_child(), ...)`?

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 39]
```diff
@@ -169,86 +189,139 @@ const std::vector<std::string>& AbstractLQPNode::output_column_names() const {
...
-  const auto column_id = find_column_id_by_named_column_reference(named_column_reference);
-  Assert(column_id,
-         std::string("NamedColumnReference ") + named_column_reference.column_name + " could not be resolved.");
-  return *column_id;
+  return *_output_column_references;
 }
 
-std::optional<ColumnID> AbstractLQPNode::find_column_id_by_named_column_reference(
-    const NamedColumnReference& named_column_reference) const {
+std::optional<LQPColumnReference> AbstractLQPNode::find_column_reference(
```
Comment (mrks) [inline src/lib/logical_query_plan/abstract_lqp_node.cpp]: I believe we agreed on `find_column`. If you like `find_column_reference` better, I'm fine with it, too.

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 40]
```diff
@@ -169,86 +189,139 @@ const std::vector<std::string>& AbstractLQPNode::output_column_names() const {
...
+    const QualifiedColumnName& qualified_column_name) const {
   /**
-   * This function has to be overwritten if columns or their order are in any way redefined by this Node.
-   * Examples include Projections, Aggregates, and Joins.
+   * If this node carries an alias, that is different from that of the NamedColumnReference, we can't resolve the column
```
Comment (mrks) [inline src/lib/logical_query_plan/abstract_lqp_node.cpp]: No comma before restrictive clauses (that)

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 41]
```diff
@@ -169,86 +189,139 @@ const std::vector<std::string>& AbstractLQPNode::output_column_names() const {
...
+  return *colum_origin;
 }
 
-std::vector<ColumnID> AbstractLQPNode::get_output_column_ids_for_table(const std::string& table_name) const {
-  /**
-   * This function might have to be overwritten if a node can handle different input tables, e.g. a JOIN.
-   */
-  DebugAssert(left_child() && !right_child(),
-              "Node has no or two inputs and therefore needs to override this function.");
+std::shared_ptr<const AbstractLQPNode> AbstractLQPNode::find_table_name_origin(const std::string& table_name) const {
```
Comment (mrks) [inline src/lib/logical_query_plan/abstract_lqp_node.cpp]: If we rename `find_column_reference` to `find_column`, we could rename this to `find_table`.

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 42]
```diff
@@ -169,86 +189,139 @@ const std::vector<std::string>& AbstractLQPNode::output_column_names() const {
...
-    return {};
+  // If this node has an alias, it hides the names of tables in its children and search does not continue.
+  // Also, it does not need to continue if there are no children
+  if (!left_child() || _table_alias) {
+    return nullptr;
   }
 
-  if (_table_alias && *_table_alias == table_name) {
-    return get_output_column_ids();
+  const auto table_name_origin_in_left_child = left_child()->find_table_name_origin(table_name);
```
Comment (mrks) [inline src/lib/logical_query_plan/abstract_lqp_node.cpp]: `table_in_left_child`?

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 43]
```diff
@@ -169,86 +189,139 @@ const std::vector<std::string>& AbstractLQPNode::output_column_names() const {
...
+      return table_name_origin_in_left_child;
+    } else if (table_name_origin_in_right_child) {
+      return table_name_origin_in_right_child;
+    }
+  }
+
+  return table_name_origin_in_left_child;
+}
+
+std::optional<ColumnID> AbstractLQPNode::find_output_column_id_by_column_reference(
```
Comment (mrks) [inline src/lib/logical_query_plan/abstract_lqp_node.cpp]: `column_reference` seems redundant

File: src/lib/logical_query_plan/aggregate_node.hpp [hunk 44]
```diff
@@ -49,21 +50,22 @@ class AggregateNode : public AbstractLQPNode {
    *
    * NOTE: These functions will possibly result in a full recursive traversal of the ancestors of this node.
    */
-  std::optional<ColumnID> find_column_id_for_expression(const std::shared_ptr<Expression>& expression) const;
-  ColumnID get_column_id_for_expression(const std::shared_ptr<Expression>& expression) const;
+  std::optional<LQPColumnReference> find_column_reference_by_expression(
```
Comment (mrks) [inline src/lib/logical_query_plan/aggregate_node.hpp]: `find_column_reference`?

File: src/lib/logical_query_plan/lqp_translator.hpp [hunk 45]
```diff
@@ -42,6 +44,12 @@ class LQPTranslator final : private Noncopyable {
   // Maintenance operators
   std::shared_ptr<AbstractOperator> _translate_show_tables_node(const std::shared_ptr<AbstractLQPNode>& node) const;
   std::shared_ptr<AbstractOperator> _translate_show_columns_node(const std::shared_ptr<AbstractLQPNode>& node) const;
+
+  // Translate LQP- to OperatorExpressions
```
Comment (mrks) [inline src/lib/logical_query_plan/lqp_translator.hpp]: PQPExpressions?

File: src/lib/operators/abstract_join_operator.cpp (hunk 1 above)
Comment (mrks) [inline src/lib/operators/abstract_join_operator.cpp]: I believe we wanted to call this ColumnIdPair

File: src/lib/logical_query_plan/abstract_lqp_node.cpp (hunk 37 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: done

File: src/lib/logical_query_plan/abstract_lqp_node.cpp (hunk 38 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: agreed

File: src/lib/logical_query_plan/abstract_lqp_node.cpp (hunk 39 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: yep, catchier names are better here

File: src/lib/logical_query_plan/abstract_lqp_node.cpp (hunk 40 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: uargs

File: src/lib/logical_query_plan/abstract_lqp_node.cpp (hunk 41 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: nah, `table_name` as the word for an alias or the stored_table_name needs to stay in, imo.

File: src/lib/logical_query_plan/abstract_lqp_node.cpp (hunk 43 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: `find_output_column_id()` then

File: src/lib/logical_query_plan/aggregate_node.hpp (hunk 44 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/aggregate_node.hpp]: or just `find_column`? Need to test whether this hides the name in the base class

Comment (mrzzzrm) [reply src/lib/logical_query_plan/aggregate_node.hpp]: seems like it does (https://stackoverflow.com/questions/32946364/c-inheritance-and-name-hiding), will go for `find_column_by_expression`

File: src/lib/logical_query_plan/lqp_translator.hpp (hunk 45 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/lqp_translator.hpp]: yep

File: src/lib/operators/abstract_join_operator.cpp (hunk 1 above)
Comment (mrzzzrm) [reply src/lib/operators/abstract_join_operator.cpp]: ... `ColumnIDPair` since the D in ColumnID is capital?...

File: src/lib/logical_query_plan/abstract_lqp_node.cpp (hunk 42 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: See https://github.com/hyrise/hyrise/pull/601#discussion_r161496842

**Comment by mrzzzrm** [comment]
@mrks I guess I'll be okay with whatever you decide for the naming of `AbstractLQPNode::find_table_name_origin`

File: src/lib/logical_query_plan/lqp_translator.cpp [hunk 46]
```diff
@@ -146,65 +158,60 @@ std::shared_ptr<AbstractOperator> LQPTranslator::_translate_join_node(
...
-   * 1. Handle arithmetic expressions in aggregate functions via Projection.
-   *
-   * In Hyrise, only Projections are supposed to be able to handle arithmetic expressions.
-   * Therefore, if we encounter an expression within an aggregate function, we have to execute a Projection first.
-   * The Aggregate will work with the output columns of that Projection.
+   * 1. Handle arithmetic expressions in the arguments of aggregate functions via a Projection.
    *
-   * We only need a Projection before the aggregate if the function argument is an arithmetic expression.
+   * If there are arithmetic expressions in aggregates, e.g. `a+b` in `SUM(a+b)`, we create a Projection to compute it.
+   * If there are no arithmetics expressions we don't need the Projection (i.e. need_projection is false)
```
Comment (Bensk1) [inline src/lib/logical_query_plan/lqp_translator.cpp]: `arithmetic`

File: src/lib/logical_query_plan/predicate_node.hpp [hunk 47]
```diff
@@ -38,10 +38,12 @@ class PredicateNode : public AbstractLQPNode {
...
 
  protected:
-  std::shared_ptr<AbstractLQPNode> _deep_copy_impl() const override;
+  std::shared_ptr<AbstractLQPNode> _deep_copy_impl(
+      const std::shared_ptr<AbstractLQPNode>& copied_left_child,
+      const std::shared_ptr<AbstractLQPNode>& copied_right_child) const override;
 
  private:
-  const ColumnID _column_id;
+  const LQPColumnReference _column_references;
```
Comment (Bensk1) [inline src/lib/logical_query_plan/predicate_node.hpp]: Did you call it _column_reference**S** on purpose?

File: src/lib/logical_query_plan/lqp_translator.cpp (hunk 46 above)
Comment (Bouncner) [reply src/lib/logical_query_plan/lqp_translator.cpp]: expressions*,*

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 48]
```diff
@@ -19,13 +20,33 @@ class TableStatistics;
...
+  deep_copy->set_right_child(copied_right_child);
+
   return deep_copy;
 }
 
+LQPColumnReference AbstractLQPNode::adapt_column_reference_to_different_lqp(
+    const LQPColumnReference& column_reference, const std::shared_ptr<AbstractLQPNode>& original_lqp,
+    const std::shared_ptr<AbstractLQPNode>& copied_lqp) {
+  Assert(original_lqp->output_column_count() == copied_lqp->output_column_count(),
+         "copied_lqp must be a deep copy of original_lqp");
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: It doesn't, and there is no way to actually do this. I'll remove the Assert, I think its a leftover

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 49]
```diff
@@ -169,86 +190,137 @@ const std::vector<std::string>& AbstractLQPNode::output_column_names() const {
...
 
-  auto named_column_reference_without_local_alias = _resolve_local_alias(named_column_reference);
-  if (!named_column_reference_without_local_alias) {
-    return {};
-  } else {
-    return left_child()->find_column_id_by_named_column_reference(*named_column_reference_without_local_alias);
+  /**
+   * If the table name got resolved (i.e., the alias or name of this node equals the table name), look for the Column in the output of this node
+   */
+  if (!qualified_column_name_without_local_table_name->table_name) {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: Nope, `_resolve_local_table_name()` can return a QualifiedColumnReference with a table_name. Please don't make me verbalize when, it's painful. ;)

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 50]
```diff
@@ -169,86 +190,137 @@ const std::vector<std::string>& AbstractLQPNode::output_column_names() const {
...
+  if (!left_child() || _table_alias) {
+    return nullptr;
   }
 
-  if (_table_alias && *_table_alias == table_name) {
-    return get_output_column_ids();
+  const auto table_name_origin_in_left_child = left_child()->find_table_name_origin(table_name);
+
+  if (right_child()) {
+    const auto table_name_origin_in_right_child = right_child()->find_table_name_origin(table_name);
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: its not a table_name that's being returned here, but the ORIGIN of a table_name, i.e. an LQPNode

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 51]
```diff
@@ -169,86 +190,137 @@ const std::vector<std::string>& AbstractLQPNode::output_column_names() const {
...
+      return table_name_origin_in_right_child;
+    }
+  }
+
+  return table_name_origin_in_left_child;
+}
+
+std::optional<ColumnID> AbstractLQPNode::find_output_column_id(const LQPColumnReference& column_reference) const {
+  const auto& output_column_references = this->output_column_references();
+  const auto iter = std::find(output_column_references.begin(), output_column_references.end(), column_reference);
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: Could, yeah, but what's the benefit? `begin()` on a const vector will return a const iterator as well http://en.cppreference.com/w/cpp/container/vector/begin

[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: extra characters that abbreviate things make things harder to read. imo.

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 52]
```diff
@@ -343,10 +415,11 @@ std::vector<std::string> AbstractLQPNode::get_verbose_column_names() const {
   return verbose_names;
 }
 
-std::optional<NamedColumnReference> AbstractLQPNode::_resolve_local_alias(const NamedColumnReference& reference) const {
+std::optional<QualifiedColumnName> AbstractLQPNode::_resolve_local_table_name(
+    const QualifiedColumnName& reference) const {
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: done

File: src/lib/logical_query_plan/abstract_lqp_node.cpp (hunk 51 above)
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: There is `crend()` and `crbegin()`, I love it!!

File: src/lib/logical_query_plan/aggregate_node.cpp [hunk 53]
```diff
@@ -201,13 +156,15 @@ std::optional<ColumnID> AggregateNode::find_column_id_for_expression(
...
    */
   if (expression->type() == ExpressionType::Column) {
-    const auto iter =
-        std::find_if(_groupby_column_ids.begin(), _groupby_column_ids.end(),
-                     [&](const auto& groupby_column_id) { return expression->column_id() == groupby_column_id; });
-
-    if (iter != _groupby_column_ids.end()) {
-      const auto idx = std::distance(_groupby_column_ids.begin(), iter);
-      return ColumnID{static_cast<ColumnID::base_type>(idx)};
+    const auto iter = std::find_if(_groupby_column_references.begin(), _groupby_column_references.end(),
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/aggregate_node.cpp]: we do, and as stated above I don't see the benefit of making it explicit.

File: src/lib/logical_query_plan/join_node.hpp [hunk 54]
```diff
@@ -9,46 +9,47 @@
 #include "types.hpp"
 
 #include "abstract_lqp_node.hpp"
+#include "lqp_column_reference.hpp"
 
 namespace opossum {
 
+using LQPColumnReferencePair = std::pair<LQPColumnReference, LQPColumnReference>;
```
[the remark this answers is not in the document]
Comment (mrzzzrm) [reply src/lib/logical_query_plan/join_node.hpp]: Saves me from typing a lot of special chars, and chars in general. I think **I** like it...

File: src/lib/logical_query_plan/lqp_translator.cpp (hunk 46 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/lqp_translator.cpp]: yep

File: src/lib/logical_query_plan/predicate_node.hpp (hunk 47 above)
Comment (mrzzzrm) [reply src/lib/logical_query_plan/predicate_node.hpp]: nope

**Comment by mrzzzrm** [comment]
@Bensk1 
* Won't argue about cbegin/cend, if you want it, you get it.
* I like aliases (LQPColumnReferencePair) when they are used multiple times (9 times in this case) as I can immediately see what an object is about without having to decipher a template type.

File: src/lib/logical_query_plan/abstract_lqp_node.cpp [hunk 55]
```diff
@@ -19,13 +20,33 @@ class TableStatistics;
...
-  if (_children[0]) deep_copy->set_left_child(_children[0]->deep_copy());
-  if (_children[1]) deep_copy->set_right_child(_children[1]->deep_copy());
+  auto deep_copy = _deep_copy_impl(copied_left_child, copied_right_child);
+  deep_copy->set_left_child(copied_left_child);
+  deep_copy->set_right_child(copied_right_child);
+
   return deep_copy;
 }
 
+LQPColumnReference AbstractLQPNode::adapt_column_reference_to_different_lqp(
```
[the remark this answers is not in the document]
Comment (Bensk1) [reply src/lib/logical_query_plan/abstract_lqp_node.cpp]: Right. Apparently, I didn't see a thing

File: src/lib/operators/abstract_join_operator.cpp (hunk 1 above)
Comment (mrks) [reply src/lib/operators/abstract_join_operator.cpp]: sure

File: src/lib/logical_query_plan/aggregate_node.hpp (hunk 44 above)
Comment (mrks) [reply src/lib/logical_query_plan/aggregate_node.hpp]: ok

File: src/lib/logical_query_plan/join_node.hpp (hunk 54 above)
[the remark this answers is not in the document]
Comment (Bensk1) [reply src/lib/logical_query_plan/join_node.hpp]: Mhhh, as you wish

**Comment by Bensk1** [comment]
I don't need cbegin/cend and I don't have a strong opinion on the pair discussion

**Comment by mrks** [comment]
@mrzzzrm go?

**Comment by mrks** [comment]
I'm fine with `XPair` as an alias for `std::pair<X,X>`

**Comment by Bensk1** [comment]
Ready for merge?!

Loading times are humongous and every interaction with this PR is taking forever

**Comment by mrzzzrm** [comment]
@mrks go
